### ISSUE TITLE
Deleting an existing recipe => Server Error 500

### ISSUE THREAD

**Issue by nicedevil007** [TandoorRecipes/recipes#1011]
### Version
latest 18.0

### Bug description
As the title says, I just deleted an existing recipe that was just created for a test before and it returns:

![image](https://user-images.githubusercontent.com/17103076/139708917-69d40e00-4d00-41ee-b1db-b3f877ac3340.png)

**Comment by nicedevil007** [comment]
Ok tryed an other recipe and it just won't happen anything after confirming the delete process.

**Comment by nicedevil007** [comment]
I'm able to delete those with the admin tool. But I guess it should work with the normal webui right?

**Comment by vabene1111** [comment]
yes this is an issue that cascading models are still preventing deletion, i will look into this

**Comment by vabene1111** [comment]
should be fixed in the next release
