### ISSUE TITLE
Translations missing (German, probably also others)

### ISSUE THREAD

**Issue by MaxJa4** [TandoorRecipes/recipes#1013]
### Version
Version: 0.18

### Bug description
For example the language German is almost 100% translated on Weblate, but some old and new areas of Recipes is still not getting translated (either bc it's simply not set up to be translated with Weblate or it somehow doesn't apply the translations).

While having a quick look I found the following untranslated areas:

- Complete Meal-Planner (since it's new I suppose)
- Table headers and "Finished"-DropDown title in shopping lists
- Default name for a new cook book is "New Book"
- All control titles and check boxes in settings -> preferences
- Some setting descriptions in search-settings
- Buttons in external recipes
- /list/keyword/, /list/food/, ... entirely

If it's not too complicated to make a string translatable with Weblate in the source code, I could fix it myself soon-ish and add the translations in Weblate afterwards. If it's a bug and it should get translated, then I'm probably not able to help.

**Comment by vabene1111** [comment]
this is likely a mix of not yet pushed, non translated and library elements, thanks for reporting, we will look into this and fix as many of those issues as possible

**Comment by Kaibu** [comment]
No, I've checked. These are all translated, somehow something about i18n has broken here

**Comment by Kaibu** [comment]
- [ ] Complete Meal-Planner (since it's new I suppose)
- [ ] Table headers and "Finished"-DropDown title in shopping lists
- [ ] Default name for a new cook book is "New Book"
- [ ] All control titles and check boxes in settings -> preferences
- [ ] Some setting descriptions in search-settings
- [ ] Buttons in external recipes
- [ ] /list/keyword/, /list/food/, ... entirely

**Comment by smilerz** [comment]
@Kaibu are there additional steps that need to be taken to get new translations in weblate?  I've added a LOT of new phrases

**Comment by Kaibu** [comment]
You have to add them to the english `vue\src\locales\en.json` translation file. Then they should appear on weblate for all the other languages.

**Comment by smilerz** [comment]
OK - that's what i've been doing.
