### ISSUE TITLE
Failure when testing new shopping list

### ISSUE THREAD

**Issue by 0utl4w** [TandoorRecipes/recipes#1014]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.18.0

### Bug description
I try to test the new shopping list but when I click on the specific button in the current shopping list, the new shopping list page opens but with no entry. So I click on the "+" and when I click on "save" in the dialogue window I get an error saying: "Failure: There was an error creating a resource!"
[debug-info.txt](https://github.com/TandoorRecipes/recipes/files/7456132/debug-info.txt)

Is that normal because of the beta-status of the new shopping list?

Attached you find the information from the debug-window on the system-page.

**Comment by smilerz** [comment]
@0utl4w sorry about your experience there.  That button shouldn't be there - the updated shopping list hasn't been merged yet.

**Comment by 0utl4w** [comment]
Alright, thanks for the info!
