### ISSUE TITLE
Unable to delete recipe - "still referenced by the following instances"

### ISSUE THREAD

**Issue by rgallo** [TandoorRecipes/recipes#1015]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.17.4

### Bug description
When trying to delete a recipe, I get the following error:
```
Zucchini Ravioli could not be deleted because it is still referenced by the following instances: 

ViewLog
#3 Zucchini Ravioli
```

**Comment by vabene1111** [comment]
thanks for reporting, likely related to #1011, will investigate soon

**Comment by vabene1111** [comment]
should be fixed in the next release
