### ISSUE TITLE
Meal plan sharing

### ISSUE THREAD

**Issue by jk111** [TandoorRecipes/recipes#1024]
### Version
Version: 1.0.0

### Bug description
I see there is an option in django DB to share meal plans with other users. I don't see a way to set this in main web GUI.

Additionally, going to user settings -> preferences -> "Plan share" and adding the user does not result in the meal plan being shared.

**Comment by smilerz** [comment]
When you say 'does not result in meal plan being shared' what do you mean?  When they log in they can't see it?  Or are you expecting some other behavior?

**Comment by vabene1111** [comment]
I am not sure if we may have forgotten to implement this again in the new plan @Kaibu

I remember thinking about using the user setting without having each entry customizable on its own but with how we implemented it I think it should be easy enough to just add a select field to the modal

**Comment by Kaibu** [comment]
Yeah I think that feature is just missing in the new GUI, I think I forgot to add it due to waiting for the generic user selection component thingy.

I'll add that option to the new GUI later today

**Comment by vabene1111** [comment]
Awesome, the new select should be ready, I added it to the books page a while back.

**Comment by jk111** [comment]
@Kaibu and @vabene1111 awesome! Look forward to trying it out.

**Comment by jk111** [comment]
@smilerz yes - If I add a meal to the calendar the user who I shared it with cannot see it.

**Comment by Kaibu** [comment]
I'll make that the default selection when opening the modal, but allow for edits in every plan entry.

**Comment by Cellivar** [comment]
Haha just ran into this issue last night. Manually editing the plan in the Django admin screen worked so looking forward to getting the button back in the UI.

**Comment by Demon-Angelz** [comment]
Also having this issue - makes it a little difficult with my partner and I having our own accounts to see the recipes we have set :)
Any idea when this will be fixed?

**Comment by vabene1111** [comment]
@Kaibu and i were a little busy in the past two weeks but i am confident we are going to get this pretty soon, sorry for the inconvenience.

**Comment by Kaibu** [comment]
Yeah I planned to get this done quicker, it's my top priority on tandoor rn

**Comment by Kaibu** [comment]
Added and will be in the next release 👍
