### ISSUE TITLE
File import from Plan To Eat fails

### ISSUE THREAD

**Issue by cornishefugee** [TandoorRecipes/recipes#1030]
I'm trying to import my PlanToEat recipes. Have downloaded both the .txt file as well as the .csv file and neither works. The following error is displayed. 

"ERROR An unexpected error occurred during the import. Please make sure you have uploaded a valid file.
Imported 0 recipes."

Not sure if there's anything I can do to edit the file to make it work?

[plantoeat.txt](https://github.com/TandoorRecipes/recipes/files/7488412/plantoeat.txt)

**Comment by vabene1111** [comment]
maybe something in their export has changed since i implemented it, i will take a look at the file you provided and see if i can fix it. Might take a few days though, sadly a little busy right now.

**Comment by cornishefugee** [comment]
Thanks for responding, I appreciate it. It isn't a hardship as I can just
add recipes manually. But my wife would love it if I can just import
everything she's added to plan to eat.

Thanks again!

**Comment by vabene1111** [comment]
so i just tested with the example file you provided and the import works fine, did you select "plantoeat" as shown on the screenshot before running the importer ?

![image](https://user-images.githubusercontent.com/6819595/140777301-695abb04-b965-42c9-b185-69d7c3231234.png)

**Comment by cornishefugee** [comment]
Since I sent you my message I've found out I must have installed Tandoor
incorrectly. So I'm about to start the process again. I'm totally new to
this so it'll be a rocky road haha. I'll get back to you if I get it
working correctly. Thanks for your time and patience, you've created a
great thing, I just hope I can get it working!

For the record, yes I did select Plantoeat as you've indicated. Hopefully I
can sort it out :)

**Comment by vabene1111** [comment]
ok perfect, i will close this issue for now, if you need any help getting your setup running let me know and i will see if i can assist :)

**Comment by noja11** [comment]
Hi Vabene,  sorry to bring this up just after you closed it, but I'm having exactly the same issue with importing from Plantoeat.  

I've been trying for a long time to sort out how to get recipes out of CopyMeThat and Plan to Eat has an importer from that service.  

I installed Tandoor from the Community Applications repository on Unraid.  Here is my txt file from Plantoeat [plantoeat-recipes-617955_11-09-2021.txt](https://github.com/TandoorRecipes/recipes/files/7507445/plantoeat-recipes-617955_11-09-2021.txt)

**Comment by vabene1111** [comment]
ok so interesting, i always test the importers locally on my dev environment and apperently that works like a charm but my deployment doesn't (dont always test importers there as it messes with my own database). 

Wil look into this and provide you with a hopefully quick fix.

**Comment by vabene1111** [comment]
ok found the likely cause, similar to #1031 plantoeat and mealmaster had ansi encoding set but it has to be `windows-1250` to work on linux. fixed this for the next release
