### ISSUE TITLE
Buttons hide settings in meal plan

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#1036]
On mobile in the settings tab the last setting is hidden by the buttons at bottom of screen

![BE424C70-D3F4-4BC0-881C-489EDE50B6E5](https://user-images.githubusercontent.com/1808639/140615297-fcc43d04-5c5c-458b-adf8-31bd32e53d12.jpeg)

**Comment by Kaibu** [comment]
Menu is now hidden in the settings tab, the settings are also now way more mobile friendly.

**Comment by smilerz** [comment]
Thanks @Kaibu
