### ISSUE TITLE
Import of Nextcloud Cookbook (v0.9.6) recipes fails

### ISSUE THREAD

**Issue by xkl** [TandoorRecipes/recipes#1039]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: **where is the system page?** (I am using the current web version as a monthly paying user)

### Bug description
Importing a file with 6 recipes exported by Nextcloud Cookbook (v0.9.6) fails with

```
-------------------- 
ERROR 
name 'parse' is not defined
--------------------
Imported 0 recipes.
```
[Rezepte.zip](https://github.com/TandoorRecipes/recipes/files/7492052/Rezepte.zip)

-xkl

**Comment by vabene1111** [comment]
Thanks for submitting the example file, maybe I broke a import on a recent refactoring, will look into this asap

**Comment by vabene1111** [comment]
I am sorry, this was just a stupid little copy past issue. The web hosted version is going to be updated within the next 10-15 minutes, the stable release will follow in a few days, sorry for the inconvenience, if you have any further troubles let me know.

**Comment by xkl** [comment]
thanks, I can confirm that the import works for the json data, but the accompanying full.jpg is not shown. Is there sth wrong on my side?

**Comment by vabene1111** [comment]
I haven't tested that as that always worked, sorry about that. I will check and make sure that works, maybe nextcloud renamed the images in some update and I am still looking for an old file name.

Should I delete the recipes from your instance so you don't need to do that manually or did you only import the 6 test recipes?

**Comment by xkl** [comment]
This was only a test set. Let me try to re-import after image file fix, I saw an option to overwrite already existing recipes. Just let me try this.

**Comment by xkl** [comment]
After the tests I want to import roughly 200 recipes... Maybe I need your help if there are glitches then. Thanks for your quick support.

**Comment by vabene1111** [comment]
hi, sorry for taking so long, nextcloud cookbook changed the structure just a little a while back so that images are no longer found. I fixed it and it will be deployed in a few minutes. 

Usually importing works quite well but i am always happy to get more testing data as some recipe managers just slightly change their format if certain fields are added or whatever so it might be that certain edge cases are not represented correctly in the standard. If you want you can also send me the files via email first and i will run a test to see if everything goes trough correctly.

**Comment by xkl** [comment]
I will donate my recipes as test set and send a link. Where should I send it (I don't want the link to be public....)

**Comment by vabene1111** [comment]
just send it to info@tandoor.dev and i will run a test to tell you if it works alright or maybe even make some direct improvements if i see anything.
