### ISSUE TITLE
Can not start Registration-Proces / E-Mail does not work

### ISSUE THREAD

**Issue by heimi75** [TandoorRecipes/recipes#1040]
## Issue
Please describe your problem here
I have installed Tandoor (congratulations, good stuff) on my synology 1621+ with docker. It works all including subdoman, but I can not start the administration proces for new user. The report is that the registration-Proces is not open.
I have set an E-Mail like instructed in issue "Possibly missing SSL lib for Email SSL #969". But the E-Mail never arrives, it is also not in SPAM. 
If I try to register a new user with E-Mail I get also a blank site with fault "500". I dont know if the two problems are connected.
But If I go back, the link is created and also working.
Because of that i mention here both faults. Sorry, if it is wrong.
On the system-site everything is marked with "ok".

At least to say that your install guide for Synology works perfectly fine, thank you very much!
Thanks for help. Give me a message, If you need more Information.
Sincerly heimi75

## Setup Info
Version: (can be found on the system page since v0.8.4)
The Version is 1.0.0

**Comment by vabene1111** [comment]
There is an environment variable called enable sign up (or similar) is that enabled?

I am not entirely sure because we added those features incrementally but I think you can enable emails but still have sign up disabled. If this is not the case I will need to look into it. One more thing, you can manually copy the invitation link and give it to the person who wants the account.

**Comment by heimi75** [comment]
To copy the invitation link manually works perfect, thank you for the fast answer.
Can you please tell me where I can found enable sign up? I have not found these, neither in "Einstellungen" neither in the Admin-Tools. Thank you very much.

**Comment by vabene1111** [comment]
We update the environment template file whenever we add new variables but we have not yet gotton around to writing some idependet documentation for it, if you came from an older version that might be the reason you dont have it. 

The setting is located in the `.env` file in your installation (or if you use some other installation method it might be directly in the compose file or some kind of management UI). If this is not enabled it is possible that you are seeing the error you describe. 
```
# allow people to create accounts on your application instance (without an invite link)
# when unset: 0 (false)
ENABLE_SIGNUP=1
```

If this does not help we need to look into what else could be wrong.

**Comment by heimi75** [comment]
Thank you very much, now it works! I enter ENABLE_SIGNUP=1 in the "Tandoor-Web"-Container.
But when I want to commit the registration or send invitation for Space always the Server-Error 500. What I forgot: in docker-Container for Tandoor-Web its not possible for me to set the Timezone. The container does not start, when I enter a Timezone. If I left the Timezone away it works, but I have no idea, if it depends to the Server-Error 500.

**Comment by stefan-oskamp** [comment]
I also get a 500 error when trying to set the Default space for a new user in the user preferences of the admin page. The error occurs when trying to save the preferences. When using a share link, the user does not succeed in joining the space. They are always presented the same screen to create or join a space. The gunicorn_err.log does not show any issues.

**Comment by stefan-oskamp** [comment]
It is now working for me.

I completely re-installed the application, because the forwarding via Nginx did not work as it should have. I had configure a base path (/recipes) for the applicaiton. Instead, I have now setup a virtual host (recipes.domain.tld) and no base path.

Also, I set ENABLE_SIGNUP to 1. 

Not sure which one of the two things lead to the 500 error, but it's working like a charme now.

**Comment by heimi75** [comment]
@ stefan-oskamp: how is your installation? Is it also in docker? I dont understand exactly what you have done for your solution. Can you please give me a step by step instruction where you have done which step? That would be very nice, thank you.

**Comment by stefan-oskamp** [comment]
I was planning to write up a detailed summary of the installtion. But here you go:

My installation is a manual installation on a physical server running Fedora 34. It runs a couple of internal and external services, among them a publicly accessible Nginx server with a valid Let's Encrypt wildcard cert.

Steps:

- Install Postgresql: `sudo dnf install postgresql postgresql-contrib postgresql-server`
- Install ldap libs: `sudo dnf install openldap openldap-devel python3-ldap`
- Install libpq: `sudo dnf install libpq libpq-devel`
- Install nodejs and yarn: `sudo dnf install nodejs`, `npm install --global yarn`
- Create user recipes `sudo useradd -c "recipes application user" recipes`
- Login as user `recipes`
- `cd /home/recipes` and clone the repo: `git clone https://github.com/vabene1111/recipes.git -b master`
- Create virtual env: `python3.9 -m venv /home/recipes/recipes`
- `cd /home/recipes/recipes` and run bin/pip3.9 install -r requirements.txt
- `cd /home/recipes/recipes/vue` and install frontend reqs: `yarn instal` and `yarn build`
- Setup postgresql DB and user: `sudo -u postgres psql`
```
CREATE DATABASE recipes;
CREATE USER recipes WITH PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE recipes TO recipes;
ALTER DATABASE recipes OWNER TO recipes;
ALTER ROLE recipes SET client_encoding TO 'utf8';
ALTER ROLE recipes SET default_transaction_isolation TO 'read committed';
ALTER ROLE recipes SET timezone TO 'UTC';
--Grant superuser right to your new user, it will be removed later:
ALTER USER recipes WITH SUPERUSER;
```
- Change the auth method in `/var/lib/pgsql/data/pg_hba.conf`  to `md5` for `127.0.0.1/32` and `::1/128`
- Download the .env configuration file: `wget https://raw.githubusercontent.com/vabene1111/recipes/develop/.env.template -O /home/recipes/recipes/.env`
- `vim /home/recipes/recipes/.env` and add/adjust:
  - `SECRET_KEY`
  - `POSTGRES_HOST`
  - `POSTGRES_USER`
  - `POSTGRES_PASSWORD`
  - `POSTGRES_DB`
  - `ENABLE_SIGNUP`
- Create user service unit file `/home/recipes/.config/systemd/user/recipes.service`:
```
[Unit]
Description=gunicorn daemon for recipes
[Service]
Type=simple
Restart=always
RestartSec=10
WorkingDirectory=%h/recipes
EnvironmentFile=%h/recipes/.env
ExecStart=%h/recipes/bin/gunicorn --error-logfile %h/log/gunicorn_err.log --log-level debug --capture-output --bind 127.0.0.1:8085 recipes.wsgi:application
[Install]
WantedBy=default.target
```
- Note that you need to create a session for a user systemd instance. You can e.g. ssh into the server as the user, but you cannot just use `su - ...`
- Make user services linger on logout: `sudo loginctl enable-linger recipes`
- `mkdir /home/recipes/logs`
- Load the unit file,  enable it and start it:
  - `systemctl --user daemon-reload`
  - `systemctl --user enable recipes.service`
  - `systemctl --user start recipes.service`
- Create a virtual host in `/etc/nginx/nginx.conf` (before the default server block):
```
    server {
        listen       443 ssl;
        server_name  recipes.example.com;
        root         /home/recipes/html;

        # Load configuration files for this server:
        include /etc/nginx/recipes.d/*.conf;
    }
```
- Create new directory `/etc/nginx/recipes.d`, put your `ssl.conf` file there and create a new file `recipes.conf` there:
```
location /static {
    alias /home/recipes/recipes/staticfiles;
}
location /media {
    alias /home/recipes/recipes/mediafiles;
}
location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;
    proxy_buffering off;
    proxy_pass http://localhost:8085/;
}
```
- Make sure that the `staticfiles` and `mediafiles`directories are readable by Nginx.
- Restart Nginx or reload its config: `sudo systemctl restart nginx` or `sudo systemctl reload nginx`
- Call `https://recipes.example.com` and create your admin user.
- Create a share link for the Default space without providing an e-mail address.
- Sign up as another (e.g. in another browser) user and then copy the share link into the browser address field to join the shared Default space.

**Comment by heimi75** [comment]
Thank you very much!
I will try to make that in docker as far as possible.
Sincerly

**Comment by vabene1111** [comment]
awesome, thanks for helping each other. Let me know if it works otherwise i will look into this again

**Comment by heimi75** [comment]
Hello,

Just for information:
This one works with docker:

}
location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;
    proxy_buffering off;
    proxy_pass http://localhost:8080/;

This one not:

    server {
        listen       443 ssl;
        server_name  recipes.example.com;
        root         /home/recipes/html;

        # Load configuration files for this server:
        include /etc/nginx/recipes.d/*.conf;

As I could see the 500-Error appears only with E-Mails otherwise not! Registration also shows fault 500 but registration is complete. It works all, just without E-Mail-Function. For me its ok, its a phantastic programm.

@vabene1111 

Maybe you want to give the information in the synology-Doku that in Web Application Container you can also add the variables and values:

 EMAIL_HOST:                                             smtp.gmail.com  (for example)
      EMAIL_PORT:                                        587                      (for example)
      EMAIL_HOST_USER:                              [HIDDEN]
      EMAIL_HOST_PASSWORD:                    [HIDDEN]
      EMAIL_USE_TLS:                                    0
      EMAIL_USE_SSL:                                    1
      DEFAULT_FROM_EMAIL:                        [HIDDEN]
      ACCOUNT_EMAIL_SUBJECT_PREFIX:     "[Kochbuch] "
      ENABLE_SIGNUP:                                   1

So it works with docker to sign up and E-Mail (for later).
Thank you very much.

**Comment by vabene1111** [comment]
thanks, as i don not 100% understand this at this time and i dont have time to look into it i will not include this in the docs for now but i will keep it in mind if anyone else comes up with similar issues.
