### ISSUE TITLE
Search not showing new recipes

### ISSUE THREAD

**Issue by donkyyyy** [TandoorRecipes/recipes#1042]
### Version
- Version 1.0.0
- DB: sqlite
- Browser: Firefox

### Bug description
After creating a recipe, it does not show up in /search view.
In firefox console window following error message pops up:
```
Uncaught (in promise) TypeError: window.Urls[e] is not a function
recipe_search_view.js:1:293306
```

However if the recipe gets planned for today in /plan view, it also shows up in /search view (in console the error message still pops up)

**Comment by vabene1111** [comment]
that is very interesting, i do all my development testing on sqlite and it has never happend. The `window.Urls[e]` was an issue in one version of tandoor a while back, maybe the service worker for some reason returned you an old script version, can you reload the page without caching ? in chrome this is done with shift+F5 or ctrl+shift+R, i am not entirely sure how firefox does that but i suspect similarly

**Comment by donkyyyy** [comment]
Using Chrome as browser I did reload the page without caching - same problem.
But looking at the console output, I found out, that I receive following output, for all views, not only related to /search (although all other views are working perfectly fine).

```
Error: service-worker.js:4 Uncaught SyntaxError: Cannot use import statement outside a module

Warning: (Index):352 Error whilst registering service worker TypeError: Failed to register a ServiceWorker for scope ('mywebsite.com') with script ('mywebsite.com/service-worker.js'): ServiceWorker script evaluation failed
(anonym)	@	(Index):352
Promise.catch (async)		
(anonym)	@	(Index):351
load (async)		
(anonym)	@	(Index):347
```

This leaves me thinking maybe I did a mistake my setup.

**Comment by vabene1111** [comment]
that is possible but if other things work usually the service worker works to (never seen this issue to be honest) and even if the service worker fails to install the requests should simply go trough directyl 🤔 

Can you give some more details about the setup you did ?

**Comment by donkyyyy** [comment]
Sure, I pretty much followed the '[Contributing](https://docs.tandoor.dev/contribute/)' description. 

- `pip install -r requirements.txt`
- `python manage.py migrate`
- `yarn install`

But I'm running this on quite some specific host machine: it is shared with different users, and processes get automatically killed if they use more than 1.5GB RAM and too much CPU processing - so I limit following file so that workers use max 1GB RAM during building:

- set DEFAULT_MEMORY_LIMIT = 1024 in node_modules/fork-ts-checker-webpack-plugin/lib/index.js`
- `yarn build`

`yarn build` still crashes 3 times (probably too much CPU usage on the machine), but in the end everything gets build (at least the final `yarn build` returns success ` DONE  Build complete. The ../cookbook/static/vue directory is ready to be deployed.`)

I'm using the app with wsgi.
I visit the webpage, create an admin account and directly after that I'm redirected to /search view and receive the exception (just found out it also throws this error if no recipes are created).

**Comment by vabene1111** [comment]
ok interesting setup, have you run `python manage.py collectstatic` and `python manage.py collectstatic_js_reverse` after the build ?

**Comment by donkyyyy** [comment]
Great, thank you!
`python manage.py collectstatic_js_reverse`
This one fixed my issue. View works now as expected.
I have still some service worker issues, but I will find a way to fix them.
Thanks.

**Comment by mheppner** [comment]
I'm having this same issue and `collectstatic_js_reverse` has not solved it for me.

`Uncaught (in promise) TypeError: window.Urls[e] is not a function` is being thrown in the browser console, yet `reverse.[hash].js` is being loaded. I can also access `window.Urls` in the browser console. The service worker is registered and running.

Did you do anything else to solve this?

**Comment by donkyyyy** [comment]
I'm quite sure that this was the only change I did. After executing `collectstatic_js_reverse` I could see that following file changed:
`modified:   cookbook/static/django_js_reverse/reverse.js`
Are you using the same setup as me?

**Comment by mheppner** [comment]
I am using the same setup. I got it working though, I think I fixed it by restarting gunicorn - I think the ManifestStaticFilesStorage may have cached a missing file.
