### ISSUE TITLE
Migration issues when DB starts delayed

### ISSUE THREAD

**Issue by ordo01** [TandoorRecipes/recipes#1046]
I used the instructions for Synology on the web page to install recipes using Docker images on my NAS.
After the containers have been created and started, the web page only shows "Server Error (500)"

In the docker-compose logs I see various error messages "ERROR:  relation "auth_user" does not exist at character 35"

For reference I attached the docker-compose log -f
[docker-compose.log](https://github.com/TandoorRecipes/recipes/files/7493249/docker-compose.log)

**Comment by vabene1111** [comment]
your database server is refusing the connection form you app container (wrong password maybe ?) thus the app cannot run its migrations and gives you the error you are seeing.

**Comment by ordo01** [comment]
I see that the DB server is refusing the connection. The point is, I have not used an existing DB but went for the option to get it created as one of the containers. I provided a postgres password in .env as described here https://docs.tandoor.dev/install/synology/ in step 9. assuming this will create a DB user for me with the given password.

**Comment by vabene1111** [comment]
the synology guide was contributed by a community memeber as i dont have a one to test it for myself but from the guide i would suspect that it works if you follow the steps. But the app cant create the DB if it cant connect so. 

You can try connecting to the db from some kind of client and seing if that works (by exposing the ports), also if you started the DB once without the env variable being set or read correctly it would have created the DB with random credentials so maybe completly deleting the DB again and making sure everything is set correctly helps.

**Comment by ordo01** [comment]
I did some research and figured that your summary of the steps is missing to provide a value for "SECRET_KEY" in .env.
After adding this I re-ran docker-compose and I have a working instance.
You may want to fix this on your Synology install guide.

**Comment by optiprime** [comment]
I've had the same problem and got the same error message. But the first error I received was: **ERROR:  relation "cookbook_keyword" does not exist at character 8**.

When analysing the problem I ran into a funny _Heisenbug_: After setting ```SQL_DEBUG=1``` in my .env file the software started without any error.  I've cleaned everything and started from scratch three times in a row. The result has always been the same.

Maybe this hint helps to further analyse the problem.

**Comment by vabene1111** [comment]
that is interesting, SQL debugging should not cause this issue. @smilerz do you have any idea why SQL_DEBUG would change anything in the way the connection is established ? 

I will change the install guide accordingly but in general all software i know expects the installing user to read trough the environment/config file and add all variables that are required/recommended for the setup. I think i will make a central envirojnment documentation page in the docs and mark the required options there.

**Comment by optiprime** [comment]
In fact, I precisely followed your installation guide and populated the config parameters using the template  'env.template'. In the first place I didn't touch 'SQL_DEBUG' because it was already set (to 0) - a very reasonable value for my non-development use-case. So it has been this default value which causes the problem.

**Comment by vabene1111** [comment]
that is very interesting, i will need to look into the inner workings of that variable to understand how this could cause the issue you describe.

**Comment by sMau** [comment]
I can confirm the behavior too. Having a fresh installation on Ubuntu 20.04 using the *plain* `docker-compose.yml` file. Changing `SQL_DEBUG=0` to `SQL_DEBUG=1` in the `.env` file results in a working setup. Otherwise I face the same database problems as described above.

**Comment by vabene1111** [comment]
This does not make any sense 🙈 the only thing SQL debug does is add this line of code 

```
if bool(int(os.getenv('SQL_DEBUG', False))):
    MIDDLEWARE += ('recipes.middleware.SqlPrintingMiddleware',)
```

The middleware in turn does nothing else than to print the currently used query 😂 im am very interested to find out why this is happending.

**Comment by optiprime** [comment]
Only considering the static dependencies  you are right. Now I assume a concurrency problem. We have 3 docker containers running in parallel. What if the DB is starting is too slow to be available when the application tries to access it?

I tried to prove this assumption: So I set ```SQL_DEBUG=0``` again and started the DB container up front with a 10 seconds advance:
```bash
docker-compose up -d db_recipes; sleep 10; docker-compose up
```  

Now everything works fine! For a fix one might realize a retry logic into the application server for the first DB access. Does somebody have a simple solution?

**Comment by tuxuser** [comment]
This was a suggestion posted on the Discord:

> What do you think about an addition to start flow of the app that ensures the DB is up before it attempts to run any migrations. Imo this would solve two issues:
>
> 1) Unclutter the log messages, make it easier to see what the stack is doing
> 2) Provide higher stability on starting the stack
>
> django-probes is pip-installable module that provides this functionality by adding a new manage subcommand to Django, reference: https://dev.to/javidjms/django-probes-wait-until-database-is-ready-probes-for-docker-and-kubernetes-6o7

**Comment by vabene1111** [comment]
very interesting, also thanks @tuxuser for already putting the link in here so i can find it easier. 
We have been running tandoor like this for almost 3 years now and i never heard of anyone having those kinds of race conditions or concurrency problems but i guess if this comes up now for people then we need to implement some kind of fix for it. 

The good thing is that there is a very easy workaround so this is not the most pressing of matters but it needs to be addressed.

**Comment by vabene1111** [comment]
This should be solved by the waiting and if it's not the waiting that causes this it must be some kind of configuration or setup issue i think.

**Comment by MaxJa4** [comment]
Should be solved now indeed :)
