### ISSUE TITLE
New user from Django admin

### ISSUE THREAD

**Issue by fatflyingpigs** [TandoorRecipes/recipes#1048]
**Is your feature request related to a problem? Please describe.**
The "+ Add" button is missing from the Users section of the Django administration. It would be nice if we could create users manually. Currently the ability to create new users is un clear at best, and downright confusing at worst. 

**Describe the solution you'd like**
I would like the ability to create a user and assign permission from the /admin/ url.

**Describe alternatives you've considered**
--

**Additional context**
Using this app on Unraid + docker. I'd like to use this to both save my recipes and also share then via the web, maybe have friends submit their own. The user creation is not straight forward.

It would also be good if the password could be set without restrictions. The /accounts/signup/ tries to enforce some password security that is unnecessary for guest accounts.

**Comment by vabene1111** [comment]
i agree that user creation is not very well structured in the UI but as there are certain functions an routines running when a new user is created you cannot simply add one in the admin. We will need to improve the flow of how users are created but overall this is not to differnt to how applications like gitlab handle user creation (you basicall generate a link for a user to sign up). 

We will improve this once we rewrite the space management page but i will not add something from the admin as it would introduce a second channel on how users could be created.

> It would also be good if the password could be set without restrictions. The /accounts/signup/ tries to enforce some > password security that is unnecessary for guest accounts.

Only the most necessary of password rules are enforced (mainly lenght and common list). This application is currently not meant for public usage so the password policy will be left in place (it is generally not good to have any weak passwords anywhere, just trains the users to do the wrong thing)
