### ISSUE TITLE
Steps without ingredients are displayed in the list of ingredients

### ISSUE THREAD

**Issue by DeadHunter** [TandoorRecipes/recipes#1049]
### Version
Version: 1.0.0

### Bug description
Steps without ingredients are displayed in the list of ingredients

![Screenshot 2021-11-08 153619](https://user-images.githubusercontent.com/5150351/140761351-7a77eb1e-b47f-40f1-91a0-aced9e623473.png)

**Comment by vabene1111** [comment]
fixed in next release
