### ISSUE TITLE
Error with "DateTimeField" for invitation / 502 error for each email form

### ISSUE THREAD

**Issue by meepmeep** [TandoorRecipes/recipes#1050]
### Version
Version:  1.0.0

### Bug description
Each time I use a form with an email, I get a 502 Gateway timeout.

Example with the "invite links" system (while trying to create a new link associated with an email), when validating the form : 

```
web_recipes_1    | /opt/recipes/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField InviteLink.created_at received a naive datetime (2021-11-08 14:10:44.203274) while time zone support is active.
web_recipes_1    |   warnings.warn("DateTimeField %s received a naive datetime (%s)"
web_recipes_1    | [2021-11-08 17:11:14 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:12)
web_recipes_1    | [2021-11-08 18:11:14 +0100] [12] [INFO] Worker exiting (pid: 12)
nginx_recipes_1  | 10.0.0.103 - - [08/Nov/2021:17:11:14 +0000] "POST /new/invite-link/ HTTP/1.0" 502 157 "https://xyz.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0" "-"
nginx_recipes_1  | 2021/11/08 17:11:14 [error] 23#23: *149 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.103, server: localhost, request: "POST /new/invite-link/ HTTP/1.0", upstream: "http://192.168.96.3:8080/new/invite-link/", host: "xyz.domain.tld", referrer: "https://xyz.domain.tld/"
web_recipes_1    | [2021-11-08 17:11:14 +0000] [13] [INFO] Booting worker with pid: 13

```
And I get a 503 Bad gateway.

In the .env file, I have : 
`TIMEZONE=Europe/Paris`

If I try to send the verification email for my account (blue button "re-send verification"), I got no error from the web_recipes, but it timeouts with a 502 bad gateway error.

**Comment by vabene1111** [comment]
the issue you are seeing is actually just a warning not the error causing the 502/503. Some people have been reporting email issues, could you set `DEBUG=1` in the environment configuration and post the logs again, maybe those contain some more information since i cannot reproduce the issue on my installations

**Comment by meepmeep** [comment]
Ok found the issue !

As it was only on forms with email, I triple-checked the emails configuration, and I was using `EMAIL_USE_TLS=1` instead of EMAIL_USE_SSL (smtp with starttls Vs smtps).

(DEBUG mode didn't help, as it gave the same error message as previous)

**Comment by vabene1111** [comment]
itneresting,thi is the same issue the other people had, i will need to figure out how to catch that particular error and point people to the correct configuration.
