### ISSUE TITLE
drag and duplicate in meal plan

### ISSUE THREAD

**Issue by CWempe** [TandoorRecipes/recipes#1051]
I just installed Tandoor for the first time. (via [heise.de](https://www.heise.de/news/Open-Source-Kantine-Version-1-0-des-Rezeptemanagers-Tandoor-Recipes-6254515.html))
But I hope this is a valid feature request.

**Is your feature request related to a problem? Please describe.**
As a single with limited cooking skills I often eat the same meal back to back. 😄 
But I do not want to create the same entry as a new one each time.

**Describe the solution you'd like**
I would like to duplicate meals in the planer by drag and drop while holding Ctrl (Strg).
This would be the same behavior like dragging a file in Windows Explorer.
Just drag a file = move
Drag a file while holding Ctrl = copy 

**Describe alternatives you've considered**
 `none`

**Additional context**
The mouse pointer even has a `+` while moving (not copying) the entry. (Tested in Chrome)
![image](https://user-images.githubusercontent.com/1270359/140823315-2e6cad98-477f-440e-af66-a1ba1eee4bc7.png)

**Comment by CWempe** [comment]
Ok, I just found the copy function in the context menu. 🤦‍♂️ 
![image](https://user-images.githubusercontent.com/1270359/140825796-6345c295-c7e8-4fe0-9a95-addfdb5b1856.png)

But I still think this would be a nice feature.

**Comment by vabene1111** [comment]
i like the idea, i read the headline on my phone and was thinking about how to do the UI/UX but i like the idea of having a modifier hotkey. It is also planned to have multi day spanning entries which helps if you cook for more than one day but still duplication is a cool thing.

**Comment by Kaibu** [comment]
Love the Idea of key modifiers aswell, will think of some more that might be usefull and add that!

**Comment by Kaibu** [comment]
Added and will be in the next release 👍
