### ISSUE TITLE
Import from Lecker not working

### ISSUE THREAD

**Issue by ordo01** [TandoorRecipes/recipes#1052]
### Version 
Please provide your current version (can be found on the system page since v0.8.4)
Version: 1.0

### Information
Exact URL you are trying to import from: https://www.lecker.de/naan-brot-backen-so-geht-das-rezept-72968.html

When did the issue happen: When pressing the search button with the url 

Response/Message shown 
„ Die angefragte Seite hat ungültige Daten zurückgegeben oder die Daten konnten nicht verarbeitet werden.“

**Comment by vabene1111** [comment]
sadly it appears that lecker.de does not provide any kind of structured or microdata. This means that the importer does not know what to import. You could try the manual mode. 
Other than that feel free to raise an issue with https://github.com/hhursev/recipe-scrapers or add a custom scraper there and we will support it trough them
