### ISSUE TITLE
Import a book: Buttons "text" or "file" doe not work

### ISSUE THREAD

**Issue by heimi75** [TandoorRecipes/recipes#1053]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
1.0.0
I have installed tandoor in a docker on a synology nas.

### Bug description
If I want to import a recipe or a book it is only possible to use "URL", "use" or "source", "text" or "file" are grey and not possible to use.
I have set admin rights with all possibilies but nothing works. Maybee I have set something wrong?

Thank you for help.

**Comment by heimi75** [comment]
Sorry! I have seen in the Demo-Version that’s also like that. I suggest, that is planed to create?
Sincerly

**Comment by vabene1111** [comment]
they are planned features for the future which have not yet been implemented. I guess we could just hide them from the UI to not confuse people to much. It is planned to rework the frontend anyway in the near future.
