### ISSUE TITLE
Ngnix reports 502 bad gateway.

### ISSUE THREAD

**Issue by invisible-walrus** [TandoorRecipes/recipes#1056]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 1.0

### Bug description
I use default docker-compose, and .env files. Only change is i add a postgresql password and secret key as instructed by the docs. When i try to boot up the stack, i get a '502 bad gateway' page from ngnix.

Logs attached below. I wget the docker-compose.yml, as well as the .env. 

OS is Ubuntu 20.04, and the docker-compose is saved in the home directory: /recipes/docker-compose.yml. I tried on a separate drive but the db would give all sorts of errors. I can post those as well, but its not the focus of this issue.

[_recipes_web_recipes_1_logs (1).txt](https://github.com/TandoorRecipes/recipes/files/7516487/_recipes_web_recipes_1_logs.1.txt)
[_recipes_db_recipes_1_logs (1).txt](https://github.com/TandoorRecipes/recipes/files/7516488/_recipes_db_recipes_1_logs.1.txt)
[_recipes_nginx_recipes_1_logs (1).txt](https://github.com/TandoorRecipes/recipes/files/7516490/_recipes_nginx_recipes_1_logs.1.txt)
![502](https://user-images.githubusercontent.com/74975645/141208643-b975b555-8a57-4a7a-9640-36119f1aac53.png)
 
in addition, please refer to my previous (albeit poorly formatted) issue request for those logs: https://github.com/TandoorRecipes/recipes/issues/1032

**Comment by invisible-walrus** [comment]
update: moments after posting this i refreshed and the ngnix version has changed. see below

![502](https://user-images.githubusercontent.com/74975645/141208949-e3fc4c5c-9f0d-4fa4-a2df-2df28ad5cc9b.png)

**Comment by vabene1111** [comment]
did you wait for lets say 1-2 minutes (depending on your setup) to refresh again and see if it works then ? The page returns a 502 while its running the migrations and getting everything ready. 

Regarding the changed nginx version: are you running any proxy servers in front of the application stack ?

The most interesting line from the logs i think is this one 
```
2021/11/10 23:09:04 [error] 23#23: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.101, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.3:2080/favicon.ico", host: "192.168.1.35", referrer: "http://192.168.1.35/"
```
the nginx is trying to connect to another internal docker ip (i suspect the application server) on port `2080`. This wont work as the application server is running on port 8080. Did you change anything with the included nginx configuration that could forward the request to another port ?

**Comment by koch17** [comment]
Can confirm, had the same problem, just change the port to 8080 in the nginx config file.

**Comment by smilerz** [comment]
@invisible-walrus can you confirm if this addressed your issue?

**Comment by smilerz** [comment]
closed due to lack of info
