### ISSUE TITLE
Import of new Cookbook from Marion

### ISSUE THREAD

**Issue by nicedevil007** [TandoorRecipes/recipes#1069]
Here is my request for beeing able to import from Marion's Kochbuch :D

Example URL: [link](https://marions-kochbuch.de/rezept/4229.htm)

**Comment by vabene1111** [comment]
sadly the page does not contain any form of structured data thus you cannot really import from it (apart from the manual html import where you have to select all fields manually). You could add a custom scraper to https://github.com/hhursev/recipe-scrapers that would then be added to tandoor with the next update of that package.
