### ISSUE TITLE
Book Sharing not Working

### ISSUE THREAD

**Issue by KingSlayer907** [TandoorRecipes/recipes#1071]
Version: 1.0.1

I only have one space setup (default) and I shared a book with a few other users but I’m the only one who can see it.

**Comment by vabene1111** [comment]
yes, thanks for reporting. I noticed that yesterday as well but forgot to wrtite it down. Will be fixed with the next update

**Comment by vabene1111** [comment]
fixed this for the next update, the frontend is a little unclear about which books you own and which you dont but that is something that can be improved in the future, for now it works

**Comment by KingSlayer907** [comment]
Sounds good, thanks for the update.

Awesome application by the way, I switched over from openeats last week and love all the features and how nice the web UI looks. I look forward to seeing how you guy improve an already perfect recipe manager!

**Comment by vabene1111** [comment]
thank you for those kind words, thats what keeps us going :)
