### ISSUE TITLE
Python 3.10 not supported

### ISSUE THREAD

**Issue by stefan-oskamp** [TandoorRecipes/recipes#1073]
### Version
Version: 1.0.1

### Bug description
My Python was updated to 3.10 with the latest Fedora update. Recipes depends on microdata. Microdata uses "use_2to3" which was deprecated in Python 3.9 and is no longer available in 3.10.

I did create a venv when installing recipes under Python 3.9, but that only created symlinks and no copies, so it does not really help.

I know that the installation instructions mention Python 3.9. So this is more like a heads up than a real bug report.

**Comment by vabene1111** [comment]
thanks for letting me know. I guess microdata is a library that is required for the website import feature so we will see how we can get around this. This might also be the reason microdata is failing in the CI so thanks for already looking this up for me. 

Maybe we can even remove the microdata dependency as we have changed quite a bit and no longer depend on it so heavily, we will see.

**Comment by staeff** [comment]
I opened a PR at microdata, but the project does not seem to be active. Lets see. If you use a modified version anyway, it might not be so important whether they merge it.

**Comment by staeff** [comment]
There is a new release of microdata, in which `use_2to3` has been removed. @stefan-oskamp - maybe you want to check, if works with 3.10 for you now?

**Comment by vabene1111** [comment]
awesome, thanks for letting me know.

**Comment by vabene1111** [comment]
ok so tests are now running under python 3.10 and it seems to basically work. I will not specify 3.10 as supported yet but i think it should already be quite stable.

**Comment by stefan-oskamp** [comment]
Can confirm it works with python 3.10 with "microdata>=0.7.1" in requirements..txt.
