### ISSUE TITLE
Upload handwritten/printed recipe image and OCR it

### ISSUE THREAD

**Issue by V3ntus** [TandoorRecipes/recipes#1077]
**Is your feature request related to a problem? Please describe.**
May be a difficult feat, but allowing users to take a picture of a recipe written down or printed (say from a cookbook or notebook), and parse it through computer vision would allow much easier importing

**Describe the solution you'd like**

**Describe alternatives you've considered**
As far as I know, there is no current way to import through an image

**Additional context**

**Comment by vabene1111** [comment]
There is no OCR currently but there is a whole feature "complex" called external recipes. Here you can specify a storage provider (lokal, google, nextcloud, ???) and sync files from that storage into your recipe list. You can then view those file trough the page and even add comments, tags, hopefully images soon and maybe even more. This works for images and PDF's alike.

besides that we do plan to add OCR in the future to make importing handwritten/external recipes easier, as this is a little further off and part of another project i will close this issue but be assured its not forgotten :)

**Comment by jonskoglund** [comment]
Having images for external recipes would be very nice. Upon import you could extract the images from the PDF and let the user choose the main image for the recipe. And maybe......futher down the road: automatic import of external recipes.

**Comment by vabene1111** [comment]
This was specifically not meant to be this way as collections can be very large while storage on vps  servers is often limited. But offering both might be interesting
