### ISSUE TITLE
Description for step type "recipe" is not shown on overview

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [TandoorRecipes/recipes#1087]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 1.0.2

### Bug description

If I have a step of type "recipe" and additionally add a description to this step, the description is not shown on the overview page (see pictures below, `Nur ½ Portion!` is nowhere on the overview page):
edit:
![grafik](https://user-images.githubusercontent.com/20322801/143229810-afc493bf-8cfb-49b0-858f-355af939c58d.png)
overview:
![grafik](https://user-images.githubusercontent.com/20322801/143229858-dba8d70a-ae3e-4687-a38a-e1dfc24773e6.png)

Would be nice to either remove the description field for step type "recipe" or - preferably - show the description on the overview page, too. I'd like to use that to add some hints specifically for the current recipe.

Btw: I'm not sure whether this is a feature request or a bug, but as the description field is already there but not shown I've decided for bug.

**Comment by vabene1111** [comment]
i want to completly remove the concept of "step types" and simply render steps differently depending on what information is give. Sadly i haven't had much time in the past few weeks so i could not implement this yet. Closing this as i will fix it with the big refactoring.
