### ISSUE TITLE
Add `yarn.lock` for front-end dependencies

### ISSUE THREAD

**Issue by ambroisie** [TandoorRecipes/recipes#1091]
**Is your feature request related to a problem? Please describe.**

I want to be able to reproducibly build Tandoor Recipes. However there is no `yarn.lock` file to pin node dependencies to specific versions.

**Describe the solution you'd like**

Instead of ignoring `vue/yarn.lock`, it should be committed and updated, similarly to how the `requirements.txt` is handled for python modules.

**Describe alternatives you've considered**

Using a `yarn.lock` file exterior to the project, however this requires manual intervention to check that the lock file is still up to date when trying to bump the version of Tandoor Recipes.

**Additional context**

My personal context is being in the process of packaging this project for NixOS.

**Comment by ambroisie** [comment]
For reference, the official documentation [1] strongly encourages people to version control their lock files for similar reasons.

[1]: https://classic.yarnpkg.com/en/docs/yarn-lock/

**Comment by vabene1111** [comment]
interesting, i did not know about that. I tought it was a generated file from the package.json and would not need VCS checkings (the automated build also just runs yarn install from the package.json so thats something you could do for now)

**Comment by ambroisie** [comment]
Yes, in the meantime I am generating a `yarn.lock` for packaging purposes, but having one in the repo is more reliable:

* no need for the packager to check if an update is needed on the lock file
* it's a better experience for your dev workflow: CI and local environments will not get out of sync with weird errors due to some updated package in one or another

Generally, lock files should be committed, unless under specific scenarios.
