### ISSUE TITLE
Nextcloud Importer recipe source field

### ISSUE THREAD

**Issue by schwantuschke** [TandoorRecipes/recipes#1105]
After Nextcloud import I lost my Source information (example: Website link).
It's possible to add a extra field in the recipes for this information. At the moment I add the text _Source: http://website.com/recipe_ to the last step. Nextcloud Cookbook have a field for source information.

**Comment by vabene1111** [comment]
thanks for the report, going to fix the importer, the extra field is discuessed in this issue #424 and will likely be added in the future

**Comment by vabene1111** [comment]
added with url import rework update
