### ISSUE TITLE
Enhance ingredient markup (template)

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#1113]
Allow a predefined 'ingredient' format to be used as markup in recipe instructions.

instead of 
`{{ ingredient[0].amount }} {{ ingredient[0].unit }} {{ ingredient[0].food }}`

the following would default to the above or a user could modify the formatting.
`{{ ingredient[0] }}`

I saw the discussion related to order vs ID - ID is probably better/more stable? Work around for the concern would be hover-text (or other formatting) so that you can see what it is.  You can also add a 'copy markup' button next to ingredient in edit mode so that the user never has to discover the ID.

**Comment by smilerz** [comment]
Oh - this should probably be polished and made more visible - this is a killer feature.

**Comment by vabene1111** [comment]
I am confused, there is already a copy button and you can use a single tag to print the whole ingredient line.

I know this is a great feature but I never really felt satisfied by how I implemented it thus I never really pushed it 🙈 guess now it's to late to change it anyways so might as well go all on.

I wanted to implement something like GitHub issue linking where you get a drop down to select an ingredient and after that it's display in the edit text in a human readable manner, nur sure yet how to do that.

**Comment by smilerz** [comment]
Oops. I just stumbled upon it and must not have read carefully enough.

**Comment by vabene1111** [comment]
No worried, I think you raised some good points, really need to look at that tipoc again
