### ISSUE TITLE
Add site for migration (Cookmate)

### ISSUE THREAD

**Issue by Battlestar963** [TandoorRecipes/recipes#1114]
**Is your feature request related to a problem? Please describe.**
I would like to import my recipes from my current manager into your web app. Therefore I tried the import function and the site is not listed. 

**Describe the solution you'd like**
Integration of the site to migrate from:
[CookMate](https://www.cookmate.online) 

**Describe alternatives you've considered**
Migrating by hand. 

**Additional context**
The export function in the site offers different options:
Export in .mcb
Export in .XML (no pictures)
Export in .mmf 
Export in .csv
Export in Text
I zipped the different options with the same recipes:
[CookMate_Export.zip](https://github.com/TandoorRecipes/recipes/files/7653806/CookMate_Export.zip)

**Comment by vabene1111** [comment]
thats awesome, quite a few formats supported and thanks for the sample data. I will look into this for one of the next releases, what youc an already try is import the .mmf (meal master file), this is a supported importer and might work for you altough it does not contain images so thats a loss. I will see if i can write a custom importer for the mcb or text file.

**Comment by kgebert** [comment]
Hi vabene,

We have just installed our own instance of Tandoor on a  web server.
Would be great to have this feature. I have 90 recipes appr. on CookMate, my brother has more than 100. It would be tedious to move them by hand and sad if we'd loose all the images.

I'm ready to support you with any information / data you need, and I am also ready to test once you're done.

Cheers,
Kirstin

**Comment by vabene1111** [comment]
i will try to get this into the next release but there are quite a few things that i need to catch up on so not sure if i can make this, but i am optimistic. Still will be a few weeks likely, sorry for that. I will write here if i added the importer to the beta.

**Comment by vabene1111** [comment]
sorry for the long wait, cookmate is implemented now and should work rather well. It will be released with the importer rewrite which is hopefully not too far away.

**Comment by kgebert** [comment]
Hi @vabene1111,
great that this is implemented now. I've tested the import and it works good in general.
However, I got some errors, and only 64 out of 77 got imported.

I'm new here and do not know how you handle this. Should I file a new issue?

**Comment by vabene1111** [comment]
Hi, feel free to open a new issue and Post some sample data of recipes not working (or the whole Export and the recipe namens that are not working) and i will see what's broken
