### ISSUE TITLE
Search bar to locate specific “IDs” on shopping list

### ISSUE THREAD

**Issue by tycap** [TandoorRecipes/recipes#1120]
**Is your feature request related to a problem? Please describe.**
After trying out the demo (which is very detailed and sharp) I came across an installation that I believe could be of use. Shopping lists list items are labeled by specific “ID” numbers that can span for pages and pages. Potentially adding a search bar at the very top adjacent to the filter button could help filter the list even further for the user’s convenience using the sought-upon “ID” number in the search.

**Describe the solution you'd like**
It would be a minor change, but one that I think can prove helpful to those trying to find one specific list via “ID” number.

**Describe alternatives you've considered**
I’ve also discovered that you’re able to click on “Created at”, for example, and filter from recent-to-oldest. This sort of counter-acts my proposal, but let me know what you think. I believe it could still be a useful tool in the future.

**Comment by smilerz** [comment]
@tycap The shopping list is being completely refactored. A beta version of it is complete and should be released soon.  
It changes the shopping list to a single, endless list that only shows 'open' items (and configurable recent items).

Does this meet your use case?  If not, can you explain in more details on how you would like to use shopping lists?

**Comment by tycap** [comment]
Thank you for the reply, I was just looking through to see if I can make any future feature suggestions.

I'll take a look at #893 and reply back if I find anything of interest.

**Comment by smilerz** [comment]
@tycap always appreciate ideas!
