### ISSUE TITLE
Pagination doesn't seem to work correctly

### ISSUE THREAD

**Issue by sportsman87620** [TandoorRecipes/recipes#1121]
### Version
Version:  1.0.2

### Bug description
I seem to be having an issue with the pagination for the "New" Search Style. If I have 30 recipes it seems that no matter what I do several of the recipes are never shown when paging. I have tried disabling recently viewed (which also seems to not work correctly in the "New" Search Style) or changing it to 1 or 2 but that doesn't seem to have changed anything. I also created an account on the hosted website just to make sure it wasn't me and the same behavior occurs there too. 

### Steps to reproduce:
1: Create 7 recipes (1,2,3,4,5,etc..)
2: Set "Recipes per Page" to 4
3: Page back and forth

Also, I just want to say thanks for the awesome work on this project!

**Comment by vabene1111** [comment]
can you please post some Information about your setup as this issue does not appear for me/the demo it is likely related to something in your installation.

**Comment by TheHaf** [comment]
I have the same issue it seems. I have enough recipes added to have two pages displayed. Some recipes are shown on both page one and page two and I also think that some recipes are not shown because of that when I switch between these two pages.
I was on version 1.0.0 until today but updated to 1.0.3 to no avail.
I use the docker compose setup with an nginx container and a postgresql container.
I don't know what other information you might need, but I would be happy to dig deeper into this problem if you can tell me what kind of information is needed.

**Comment by vabene1111** [comment]
very interesting issue, the pagination always behaved just a little bit weird and i had to use some little tricks in the code but its the first time people are actually having issues with it not working at all.

Can you run `docker-compose logs -f` on your server and post the outputs of that ?

can you also open the browser console and see if there are any errors shown there (both when making a request form one page to another)

**Comment by smilerz** [comment]
Some recipes being repeated wouldn't necessarily be a surprise: new recipes & Meal Plan recipes are expected to be repeated.

@TheHaf can you share the output of `/api/recipe/?page=1` and `/api/recipe/?page=2` along with `/api/recipe/?pagesize=1000`

**Comment by vabene1111** [comment]
just FYI: one thing @smilerz i fear might happen is that the frontend is for some reason (browser version, ...) not making the requests with `page=2` but always with `1`. I noticed some very odd things there when first adding the v-bootstrap paginiation component

**Comment by smilerz** [comment]
@vabene1111 it also wouldn’t surprise me if sorting isn’t consistent between page=1 and page=2

**Comment by vabene1111** [comment]
Yes there is this warning I have been ignoring for month 🙈 we will see from the logs and the data.

@op if you don't want to post that data publicly feel free to send it to info@tandoor.dev

**Comment by TheHaf** [comment]
I collected all the data. 😄 

- [docker compose logs.txt](https://github.com/TandoorRecipes/recipes/files/7740459/docker.compose.logs.txt).
- [browser logs.txt](https://github.com/TandoorRecipes/recipes/files/7740460/browser.logs.txt) -> There are no errors or logs there when switching pages, only on the initial loading of the website, something about a missing css map file and something about a missing service worker in the navigator.
- [api-call-page1.txt](https://github.com/TandoorRecipes/recipes/files/7740461/api-call-page1.txt)
- [api-call-page2.txt](https://github.com/TandoorRecipes/recipes/files/7740462/api-call-page2.txt)
- [api-call-pagesize1000.txt](https://github.com/TandoorRecipes/recipes/files/7740463/api-call-pagesize1000.txt)

From the looks of it my thought would also be that the sorting isn't kept between the paginated calls. Or could it be related to the last_viewed parameter in the GET calls?
I did everything on my live data. Sorry that the pages are somewhat long, I somehow couldn't find the setting for the items per page.🙈

Let me know if there's anything else I can do to help.

**Comment by smilerz** [comment]
@TheHaf - I screwed up the parameters.  Can you try the last one again with `/api/recipe/?page_size=100`?

**Comment by TheHaf** [comment]
@smilerz sure, here it is:
- [api-call-recipepagesize100.txt](https://github.com/TandoorRecipes/recipes/files/7741042/api-call-recipepagesize100.txt)

**Comment by smilerz** [comment]
API pagination seems to be working fine.  The first page returns recipes 1-23;27-28.  The second page returns 29-39.  That returns a total of 36 recipes which matches the count.  There are also no duplicates.

Some follow up questions:
- Do you see duplicate recipes when you toggle back and forth between page 1 and page 2?
- Is the last recipe on page 1: _Die perfekten Hamburgerbrötchen - Brioche Burger Buns_
- Is the first recipe on page 2: _Katsudon_?

**Comment by TheHaf** [comment]
> Some follow up questions:
> * Do you see duplicate recipes when you toggle back and forth between page 1 and page 2?
- Yes, for example _One-Pot-Spaghetti mit Champignons_, _Vegetarische Paprika-Zwiebel-Quiche_ and _Feuertopf_ are displayed on both pages.
> * Is the last recipe on page 1: _Die perfekten Hamburgerbrötchen - Brioche Burger Buns_
- No, the last one one page 1 is _One Pot Taco Spaghetti_. The _Brioche Burger Buns_ recipe is number 10 on the first page.
> * Is the first recipe on page 2: _Katsudon_?
- Yes, that is the first one on page 2.

**Comment by smilerz** [comment]
I figure out what was going wrong - thanks for your help @TheHaf 

@vabene1111 I pushed a PR to fix this.  page 2+ was generating a new queryset size & sort by dropping the last_viewed param.

```
/?query=&keywords_or=true&foods_or=true&books_or=true&internal=false&random=false&new=true&page=1&page_size=25&last_viewed=5
/?query=&keywords_or=true&foods_or=true&books_or=true&internal=false&random=false&new=true&page=2&page_size=25
```

I modified the computed property `searchFiltered `to ignore page number as part of its evaluation.

**Comment by smilerz** [comment]
As a temporary workaround until the PR is merged you can set Recently Viewed to 0.  If you have less than 100 recipes you can also set Recipes per Page to 100

![image](https://user-images.githubusercontent.com/1808639/146684532-2f753a4d-0be4-4fcc-9ac2-18c63d78f52e.png)

**Comment by TheHaf** [comment]
@smilerz Thank you very much for fixing the bug! 😄
