### ISSUE TITLE
Recipes Partially Gone After OS Upgrade

### ISSUE THREAD

**Issue by Zadeis** [TandoorRecipes/recipes#1122]
### Version
Version: 1.0.2

### Bug description
After upgrading the operating system on the machine running tandoor from Debian 10 to Debian 11 and deploying via docker just as it was previously to the same volume locations and using the same exact docker-compose file as I had backed it up none of the recipes are displayed in much of the application. Meaning the recipes can't be searched, I can't seem to do anything with recipe books and no recipes appear on the main "*https://url*/search" page. However, if I go to the history via the lunchbox/toolbox at the top right I can click anything in there and open recipes as if there are no problems.

If I open the admin section I can see all of my ingredients, recipes, etc.

So the recipes are still in the application/database but for whatever reason much of the interface can't seem to find them or acknowledge they exist. 

Looking at the debug log in the system section, with debug mode on, there's nothing immediately obvious to me what is causing an issue however I will paste what is being printed there below (I omitted the former half of the log just in case there was any identifying information in it):

> wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f6df4e69fd0>
> wsgi.version:(1, 0)
> wsgi.multithread:False
> wsgi.multiprocess:False
> wsgi.run_once:False
> wsgi.file_wrapper:
> wsgi.input_terminated:True
> wsgi.input:<gunicorn.http.body.Body object at 0x7f6df4e698e0>
> wsgi.url_scheme:http

If further information is required just let me know. Hopefully it is something simple but I also don't want to take too much of your time either.

**Comment by Zadeis** [comment]
My apologies for the delay it's been a busy week.

Excuses aside and to help ensure I get you the information what logs do you need? I'm assuming you want logs from docker so I have attached the logs from today from loading the "Cookbook" page, "Meal-Plan", "Shopping", "Books" pages along with one recipe.

[Tandoor_Docker_Log(17-Dec-2021).txt](https://github.com/TandoorRecipes/recipes/files/7737683/Tandoor_Docker_Log.17-Dec-2021.txt)
[Tandoor_Browser_Console.txt](https://github.com/TandoorRecipes/recipes/files/7737720/Tandoor_Browser_Console.txt)

If you require more logs let me know which ones.

**Comment by smilerz** [comment]
@Zadeis - that bug should be fixed in 1.0.3

**Comment by Zadeis** [comment]
You are correct! My apologies for the delay as that probably would have helped your efforts more. Regardless I'm glad to see it's fixed and I appreciate your efforts for this wonderful software!
