### ISSUE TITLE
Tandoor-Button and subpath

### ISSUE THREAD

**Issue by JSAnyone** [TandoorRecipes/recipes#1123]
### Version
Newest version

### Bug description
I'm running Tandoor under a subpath (more information [here](https://github.com/TandoorRecipes/recipes/issues/266)).
When clicking on the "Tandoor" logo I get redirected to `http://IP/` instead of `http://IP/recipes/`.
![image](https://user-images.githubusercontent.com/74502558/145615718-bf8b03f5-c172-4107-a8ac-6013af2d2be8.jpeg)

**Comment by vabene1111** [comment]
thanks for reporting, i will need to add some proper testing workflows to subpath stuff. Everything else works fine i supose ?

**Comment by JSAnyone** [comment]
Hi,
I just found out that the `Logout` button has the same problem.
However, maybe the documentation would need an update, see
[here](https://github.com/TandoorRecipes/recipes/issues/266#issuecomment-991032928).

Additionally, I'm experiencing issues with the user invite link (had written about that in discord, since I hadn't thought it's a bug).

**Comment by vabene1111** [comment]
thanks, i will take a look at that. Sadly i dont have a subpath setup and currently dont have the time to create one so my ability to test here is very limited (although your issues seem very prominent and i am confused noone else with a subpath setup reported them yet). I fear it might be some time before i can take a crack at this so if any of the subpath people want to try and fix this feel free

**Comment by smilerz** [comment]
> The button is now redirecting to `http://ip/recipes`. However, I would prefer redirection to `http://ip/recipes/`, since my reverse proxy can’t deal with it without a trailing `/`.

the behavior is all upstream - you'll need to modify your proxy to deal with it
