### ISSUE TITLE
Can't get Tandoor to remember data (users, recipes)

### ISSUE THREAD

**Issue by tugdualenligne** [TandoorRecipes/recipes#1124]
Your help welcome as I've tried dozens of changes, to no avail. Thanks for that app, recipe's URL scraping is amazing, from what I tested so far

## Issue
I spin up Tandoor with Docker compose in Portainer.
I create a master user, add some recipes. 
All works fine, BUT the 'admin' page shows my .env data is NOT taken into account (it says no postgres DB, Gunicorn used while Nginx container is running, etc.)
When I reboot the stack (i.e. docker compose), I loose everything (have to recreate user, recipes, etc.)

## Setup Info
docker compose is as follows (.env removed because directly added in portainer's stack; and volumes created for everything):
![image](https://user-images.githubusercontent.com/16443250/145648789-79e2ad1f-4bbb-4db3-b317-999b29443bcc.png)

### `.env`
.env data is a copy and paste of original one with secrets changed:
DEBUG=0
SQL_DEBUG=0
ALLOWED_HOSTS=*
SECRET_KEY=secret
TIMEZONE=Europe/Paris
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=secret
POSTGRES_DB=djangodb
FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=1

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
Provided above

```
### Logs
N/A

**Comment by vabene1111** [comment]
i am sorry but life is keeping me very very busy right now, i sadly cannot assist with setup issues atm. please close this issue if its resolved at any point otherwise i hope to get back to this in january

what i can say is that if .env is not loaded all data is stored in a local sqlite DB which is not mounted and thus lost. you will need to make sure env is loaded correctly but i dont know how this works with portainer

**Comment by smilerz** [comment]
@tugdualenligne I assume you got passed this issue?

**Comment by tugdualenligne** [comment]
Hi Smilerz, yes I eventually managed to get it to work. For it to work, I add to spin off Postgresql from a separate compose file, and set it on the same network as the Tandoor docker-compose.
