### ISSUE TITLE
Merge shopping lists: Generated from meal plan & default one

### ISSUE THREAD

**Issue by phfeustel** [TandoorRecipes/recipes#1128]
## Issue
Let's say, I'm planning my shopping once a week. I have one default continuous shopping list where I throw everything in during the week; mostly refills. The other shopping list is coming from my structured meal plan.

Is there a way to merge those to list? 
At the moment I have to switch tabs on my mobile while going through the super market which is super annoying.

## Setup Info
Version: 1.0.2
OS: vabene1111/recipes

**Comment by smilerz** [comment]
@phfeustel shopping lists are being refactored and will be a continuous list.  You can view the upcoming features here #893

**Comment by phfeustel** [comment]
@smilerz nice to hear; any ideas when it is going to be released? 

Btw: Thank you very much for your great work @smilerz!

**Comment by smilerz** [comment]
@phfeustel its ready for beta. But vabene has been busy with life. Hopefully soon.
