### ISSUE TITLE
Total weight below recipe listing

### ISSUE THREAD

**Issue by Dodoooh** [TandoorRecipes/recipes#1154]
**Is your feature request related to a problem? Please describe.**
I would like to use this awesome tool to manage my ice cream recipes.
For this I am missing the total weight of all ingredients on the recipe overview, so that I can change the ice cream quantities more quickly. 

**Describe the solution you'd like**
the easiest way would be to insert a total under the recipe listing (as shown in the screenshot below) 

**Describe alternatives you've considered**
Also it would be easier for the selection of a certain quantity above directly enter the total weight. 
However, this is probably just overkill, and only for the at least of use, a summary of the ingredients would bring it all times and simplify the calculation. 

**Additional context**

<img width="1148" alt="Bildschirmfoto 2021-12-21 um 00 20 35" src="https://user-images.githubusercontent.com/5958446/146845990-fbf98a12-7854-4ef5-bfed-f8df3f0f7ab2.png">

**Comment by smilerz** [comment]
Tandoor uses servings to scale recipes. Additionally, many recipes mix volume and mass making any sum impractical most of the time.  It’s unlikely this feature would ever be implemented.

**Comment by vabene1111** [comment]
i think what your soltion would be is to change the servings text to the sum unit you want. 

As an example your ice cream needs
100  g milk
50 g sugar
50 g chocolate

you could set the servings to be "200" and the servings text to "g". Now if you scale to 400 all ingredients should scale accordingly. Do you think this is a viable solution for you ?

**Comment by vabene1111** [comment]
ah i see you have already done so in your example. I have see one other request to change something about the ingredients to allow for volumetirc cooking (or something similar) that would maybe go hand in hand with your suggestion. I think this wont be implemented just like this as servings should suffice for now but @smilerz when we add unit conversion we might be able to make some changes in order for things like this to work (maybe in conjunction with a nutirion overview or similar)
