### ISSUE TITLE
Categories not saved for supermarket

### ISSUE THREAD

**Issue by lceWolf** [TandoorRecipes/recipes#1166]
### Version
Version: 1.0.3

### Bug description
Trying to add categories to an (existing) supermarket does to persist. When editing the supermarket after adding some categories, the category list is empty again.

Steps:
- add categories to a supermarket
- save
- edit supermarket
- category field is empty

**Comment by vabene1111** [comment]
i noticed a weired issue with broken sorting on my instance as well, need to see if we can release the new shopping list fast enough so we dont need to fix this or if we want to fix the old one before that.

**Comment by vabene1111** [comment]
this appears to be an issue on the generic multi select item that does not load the values of the foreign objects when the form is opened 

![image](https://user-images.githubusercontent.com/6819595/147770869-eb648757-5f75-4a55-848d-50f1ce2634b5.png)

**Comment by smilerz** [comment]
this is fixed in shopping_v2

**Comment by vabene1111** [comment]
#985
