### ISSUE TITLE
Adding a recipe as a step of another recipe doesn't show a preview of it

### ISSUE THREAD

**Issue by kpontussvensson** [TandoorRecipes/recipes#1167]
### Version
Version: 1.0.3 (on Unraid, with postgresql)

### Bug description
I have a recipe where I added another recipe as a step in it. I asked if it was supposed to show me a preview of it in the view and was told it was supposed to do so. But in my case I only get a link to the other recipe in that step.

### Images
Recipe with another recipe as a step
![b702104eff6921b641dd7879209b85cd](https://user-images.githubusercontent.com/34517108/147704596-043acb17-10f8-44ef-a43b-0f44671d915c.png)

The other recipe
![b15dc2f7a42846873b91940937c73194](https://user-images.githubusercontent.com/34517108/147704661-825cf518-eed4-4140-a4c4-9103e6f88baa.png)

**Comment by vabene1111** [comment]
interesting, this appears to have broken in one of the recent updates, thanks 👍 

- [ ] fix issue
- [ ] add unit test for making sure sub recipes are returned and rendered correctly
