### ISSUE TITLE
Bulk import recipes from list of addresses

### ISSUE THREAD

**Issue by NiekHoupelyne** [TandoorRecipes/recipes#1171]
Importing recipes from internal websites works great, but it has to be done one by one. Would be great to have a feature allowing you to import a list of recipes in bulk, either from the UI, through an API endpoint or both.

**Comment by vabene1111** [comment]
would you want to be presented each recipe once for manual editing or just import them all (maybe with a tag) and edit them later ?

**Comment by NiekHoupelyne** [comment]
for my particular use case, just importing them all would be preferable, since it's too much recipes to review them one by one. I like the idea of being able to add a specific tag. Some options for checking for dupplicates and updating recipes that already exist would also be nice.

**Comment by vabene1111** [comment]
ok, thanks for the info, i will look into this.

**Comment by vabene1111** [comment]
working with new importer
