### ISSUE TITLE
Selected space not honored when creating invitation links

### ISSUE THREAD

**Issue by lceWolf** [TandoorRecipes/recipes#1174]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 1.0.3

### Use Case
Invite people to your tandoor instance within their own space.
This allows to keep the sign ups disabled and work on an invitation-only base, thus keep you in control over who has access.

### Bug description
Create a new space; Create a new invitation and select the newly created space (see below). Clicking the link, one is **not** asked to join the newly created space, but your personal one

![grafik](https://user-images.githubusercontent.com/1565886/147668290-f350a738-153a-4da7-a56e-61a6e4a956a8.png)

**Comment by vabene1111** [comment]
thanks for reporting, will verify and test this

**Comment by vabene1111** [comment]
fixed, a security override was to cautious :D
