### ISSUE TITLE
Bulk add ingredients

### ISSUE THREAD

**Issue by kpontussvensson** [TandoorRecipes/recipes#1177]
**Is your feature request related to a problem? Please describe.**
When you add a recipe from a site that can't be automatically parsed it would be nice to be able to add the ingredients with a copy paste from the site.

**Describe the solution you'd like**
When you create a recipe you could have another button next to the add ingredient button which is called Bulk Add. That button lets you enter all ingredients as text and then every line is parsed as an ingredient.

So let's say I go to a blog post or someone posts a recipe on Instagram/Facebook/e-mail/whatever I could just copy the ingredients section of that recipe and enter it into the Bulk Add text field like:

```
2 avocados
1/2 lime
1/4 cup diced red onion
1/4 cup finely chopped cilantro
1 jalapeño
```

And then you could just parse every line as it's own ingredient.

**Comment by vabene1111** [comment]
i like that idea, it goes hand in hand with something i always wanted to do (make ingredient entering easier). I will look into this

**Comment by tomtjes** [comment]
Perhaps this could come handy? Just stumbled upon it by accident.
https://github.com/suprmat95/recipe-parser

**Comment by smilerz** [comment]
> Perhaps this could come handy? Just stumbled upon it by accident. https://github.com/suprmat95/recipe-parser

thanks - a library would need to be python, but there appears to be a couple out there along with some services.
https://github.com/openculinary/ingredient-parser
https://github.com/mtlynch/ingredient-phrase-tagger
https://github.com/MichielMag/parse-ingredients
https://stackoverflow.com/questions/203684/how-can-i-use-nlp-to-parse-recipe-ingredients

**Comment by kpontussvensson** [comment]
I'm closing this issue since it's added.
