### ISSUE TITLE
Docker Swarm Compatibility: Wait for DB to be ready / auto restart

### ISSUE THREAD

**Issue by orangelynx** [TandoorRecipes/recipes#1178]
**Is your feature request related to a problem? Please describe.**
When using the provided docker compose file from the docs in a docker swarm environment, the `depends_on` and `restart` flags are ignored, see [docker-compose reference](https://docs.docker.com/compose/compose-file/compose-file-v3/). This leads to race conditions between the django recipes app and the db.

**Describe the solution you'd like**
A proper solution as described [here](https://docs.docker.com/compose/startup-order/).

> To handle this, design your application to attempt to re-establish a connection to the database after a failure. If the application retries the connection, it can eventually connect to the database.

**Describe alternatives you've considered**
A workaround is the "wait-for" docker helper script, adding `entrypoint: ["/opt/recipes/wait-for", "db:5432", "--", "/opt/recipes/boot.sh"]` and mounting `wait-for` from the host.

**Comment by vabene1111** [comment]
thanks, we have had some smaller problems with this in the past so i will look at how this could be done at some point, thanks for the detailed report
