### ISSUE TITLE
Do not hard code the name of the app service in the nginx configuration

### ISSUE THREAD

**Issue by orangelynx** [TandoorRecipes/recipes#1179]
**Is your feature request related to a problem? Please describe.**
In the [nginx configuration](https://github.com/TandoorRecipes/recipes/blob/develop/nginx/conf.d/Recipes.conf) provided by the project, the host name of the app is hard coded as `web_recipes`. If someone renames the service in the provided docker-compose file, this leads to errors, which are hard to understand from the user point of view.

**Describe the solution you'd like**
Best solution would probably be to use environment variables and have a helper script update the nginx configuration (i.e. making it a template).

**Describe alternatives you've considered**
One could also revert to have the user manually write and provide an nginx config.

**Comment by vabene1111** [comment]
i do understand your concern but overall having this hard coded and automatically linked is likely the easiest solution for the majority of users (as most dont change the container names). one could add a hint to the docker compose though i guess. 

A script sounds cool and is something that i can look at when taking another look at the setup but with the huge amount of setups used by different users i dont think a script could really cover all options and i dont want to spend weeks developing something that works for everyone so i think the current solution is the best for now.
