### ISSUE TITLE
Better explain the purpose of the `SECRET_KEY` env variable in the docs.

### ISSUE THREAD

**Issue by orangelynx** [TandoorRecipes/recipes#1180]
Title pretty much says it all. It's not clear what this secret protects or why it's needed. Explaining this would probably incline the user to choose a suitable value.

**Comment by vabene1111** [comment]
the value should be generated with the command line utility shown above the line. other than that the secret key is a base feature of django, i will add a link to the django docs once i get around to writing documentation for the .env file were all variables will be properly explained
