### ISSUE TITLE
koket.se recipe import

### ISSUE THREAD

**Issue by kpontussvensson** [TandoorRecipes/recipes#1181]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 1.0.3

### Information
Exact URL you are trying to import from: 
https://www.koket.se/mitt-kok/tommy-myllymaki/myllymakis-toast-skagen

When did the issue happen: When pressing the search button with the url

Response/Message shown 
Wrong data is imported

Message
Koket.se is a really big recipe website in Sweden with lots of recipes from famous Swedish chefs and recipes from a Swedish cooking TV show called "Mitt kök".

If I inspect the page source I find
```
<script type="application/ld+json">[
{"@context":"https://schema.org","@type":"Corporation","name":"Köket","url":"https://www.koket.se/","logo":"https://www.koket.se/static/img/logo.svg"},{"@context":"https://schema.org/","@type":"Recipe","name":"Myllymäkis toast skagen","image":"https://img.koket.se/standard-mega/myllymakis-toast-skagen-2.jpg","description":"Toast skagen är en klassisk förrätt på årets festdag - nyårsafton. Tommys variant görs med hemslagen majonnäs, pepparrot och löjrom.","author":{"@type":"Person","name":"Tommy Myllymäki"},"totalTime":"PT25M","recipeYield":"4 null","recipeIngredient":["1 kg räkor med skal (gärna färska av fin kvalitet)","2  äggulor","2 tsk senap","1 msk vitvinsvinäger","6 dl matolja","1 kruka dill","10 cm färsk pepparrot, skalad","4 skiva vitt bröd (ej levain)","smör, till stekning","50 g löjrom","1  citron"],"recipeInstructions":[{"@type":"HowToStep","text":"Skala alla räkor och ställ åt sidan."},{"@type":"HowToStep","text":"Gör en majonnäs genom att lägga ner äggulor, senapen och vinägern i en bunke. Tillsätt matoljan i en tunn stråle medan du vispar hela tiden. Använd elvisp eller handvisp. När majonnäsen är tjock och du ser dragen/spåren av vispen i majonnäsen är den klar."},{"@type":"HowToStep","text":"Lägg alla räkor i en bunke, tillsätt fint plockad dill och blanda ner lite majonnäs i taget."},{"@type":"HowToStep","text":"Tillsätt lite riven pepparrot och smaka av. Slå på mer majonnäs för en rinnigare röra eller mer pepparrot för mer sting."},{"@type":"HowToStep","text":"Ta fram brödet och skär ut önskad form utan att ta med kanterna, använd en skål eller ett glas som mall om ni vill ha runda bröd. Stek sedan gyllene i smör."},{"@type":"HowToStep","text":"Lägg upp bröden på tallrik, toppa med skagenröra och en rejäl klick löjrom. Avsluta med en dillkvist och en citronskiva."}],"aggregateRating":{"@type":"AggregateRating","ratingValue":3.6,"ratingCount":358,"bestRating":"5","worstRating":"1"},"video":{"@type":"VideoObject","name":"Myllymäkis toast skagen","description":"Myllymäkis toast skagen","uploadDate":"2014-12-29T05:00:00.000Z","thumbnailUrl":"https://img.koket.se/standard-mega/myllymakis-toast-skagen-2.jpg","contentUrl":"https://www.tv4play.se/iframe/video/3036821?autoload=true","embedUrl":"https://www.tv4play.se/iframe/video/3036821?autoload=true"}}
]</script>
```
which seems to be the correct format. However when I import recipes from that site they seem to fetch some other data. See the image:

![image](https://user-images.githubusercontent.com/34517108/147705604-d8423a98-37f1-4162-b835-42f728423300.png)

**Comment by vabene1111** [comment]
this looks very broken 😂 we will take a look on whats parsed wrong here

**Comment by smilerz** [comment]
@kpontussvensson this is broken in the library we use for scraping.  You will need to report a bug on https://github.com/hhursev/recipe-scrapers/  

Once it is fixed there it'll will be imported on tandoor

as an example of what's wrong - the scrape.ingredients() should return a list of text strings like:

`"1 kg räkor med skal"`

but is returning an object

`{'id': 10543, 'name': 'räkor med skal', 'plural': None, 'type': 'ingredient', 'preparation': None, 'comment': 'gärna färska av fin kvalitet', 'alternative_amount': None, 'unit': 'kg', 'amount_info': {'to': None, 'from': 1, 'approximate': None, 'optional': None}}"`

**Comment by kpontussvensson** [comment]
Okay! I'll open an issue over there.

**Comment by vabene1111** [comment]
since we update recipe scrapers regularly i will close this issue as eventually (if it gets fixed) we will pull it in anyway
