### ISSUE TITLE
Use another recipe as ingredient

### ISSUE THREAD

**Issue by Programie** [TandoorRecipes/recipes#1183]
I'm currently evaluating Tandoor Recipes as a replacement for Nextcloud Cookbook as it as some nice features which I;m missing in Nextcloud Cookbook.

But there is one feature, I'm currently missing in Tandoor Recipes which is helpful in Nextcloud Cookbook: Linking an existing recipe (e.g. a sauce) as an ingredient of another recipe.

It would be really cool if such a feature could be implemented.

**Comment by smilerz** [comment]
@Programie - this is available, though could probably be more intuitive.

Any food can be linked to a recipe and added to another recipe.  Alternatively, a step can also be a recipe.

**Comment by Programie** [comment]
I tried that. But in the "Select Food" dropdown, I can only select ingredients. I can't select an existing recipe.

I'm using the "Text" step type where I can add individual ingredients. And one (or more) of those ingredients should be another recipe.

**Comment by smilerz** [comment]
@Programie the recipe needs an associated food.  Create/edit a food (ingredient) and link it to a recipe.
![image](https://user-images.githubusercontent.com/1808639/147773545-746293d2-2449-4051-bd7a-12a5301f1223.png)

**Comment by Programie** [comment]
Ah... found it. Yes, it could be a bit more intuitive. Directly selecting another recipe as ingredient would be more intuitive than having to specify the recipe in the ingredient separately.
