### ISSUE TITLE
map ingredients to supermarket

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1185]
**Is your feature request related to a problem?**
Is it possible to add a Supermarket field in the ingredients entry? I normally buy an ingredient always in the same supermarket.

**Describe the solution you'd like**
When adding into shopping list v2, the ingredient is then automatically preselected (dropdown), but can be changed. The same applies to adding a recipe to the shopping list.

**Comment by smilerz** [comment]
I don’t understand.  Can you try describing this differently?

**Comment by TWART016** [comment]
If I edit a Food e.g. cheese, I want a field with supermarket. There I can select the supermarket.
shopping list:
Any in shopping list v2 group by supermarket would also be great

![image](https://user-images.githubusercontent.com/29805669/147803246-fc79108a-0ce2-4001-a95d-ae6dab23052d.png)

![image](https://user-images.githubusercontent.com/29805669/147803358-3fb30c9e-6031-4272-9b78-e0859d6b94b9.png)


![image](https://user-images.githubusercontent.com/29805669/147803121-51ac8477-e85b-4068-bd4a-1d782a0c5860.png)

![image](https://user-images.githubusercontent.com/29805669/147803282-fe979f2c-345e-455b-91da-105261f7355a.png)

**Comment by vabene1111** [comment]
i dont really see why this should be done because basically everything can be bought in multiple stores but couldn't you just create seperate categories for each supermarket if you really want to do this ? e.g. Aldi - Meat, Aldi - Vegetables, .. ? 

Alternatively you could use (as it is intended by us) generic categories and link them to supermarkets so that you get all vegetables in aldi in correct order

**Comment by TWART016** [comment]
Partly this can work, but I see it as more of a workaround.

With Aldi - Meat, Aldi - Vegetables the categories and the supermarket are mixed. For example, I buy steaks at Aldi, but minced meat somewhere else. Or olive oil only at this supermarket Z.
Categories are for me rather: vegetables, fruit, meat, salad, spices, cheese, dairy products.

Let's say there are 5 supermarkets and at least 7 categories. That would be already 35 entries.

For the Meal Planner it would also be better, because I select there: I would like to have vegetables and meat. There the supermarket is only a hindrance.

However, I may not have understood the concept behind it.

**Comment by smilerz** [comment]
@TWART016 in that scenario you would have two supermarket categories: meat & minced meat.  
You can assign meat to Aldi and minced meat to storeX.  In shopping v2 you can filter the supermarkets to only include the categories they've been assigned.

It is unlikely we'd add that much complexity for such a narrow use case.

**Comment by TWART016** [comment]
I have a supermarket with no category. In shopping list v2 I filter for this supermarket and I get some ingredients.

When it is too complex than I am fine with that.

**Comment by smilerz** [comment]
@TWART016 do you have the Supermarket Categories Only filter enabled too?
![image](https://user-images.githubusercontent.com/1808639/147830894-61d824fa-8c25-4df8-b02d-797b2511b5c1.png)

**Comment by smilerz** [comment]
@TWART016 you can also make this the default behavior on the settings tab
![image](https://user-images.githubusercontent.com/1808639/147831693-a580862a-67de-40b2-b7aa-963beaef6fb5.png)

**Comment by TWART016** [comment]
Supermarket Categories Only is activated
![image](https://user-images.githubusercontent.com/29805669/147833769-ea082baf-a4d0-4e71-8469-eb4c630aeef4.png)
![image](https://user-images.githubusercontent.com/29805669/147833811-250efcbe-36f9-47ee-8d73-066902a603ca.png)


Thi Supermarket hat no category assigned
![image](https://user-images.githubusercontent.com/29805669/147833781-c17f4de2-1e5f-4ec0-8ca5-c5482a3dfd94.png)

It does matter which supermarket I select it is always the same search result with or without the button categories only. The Supermarket field does not have any function.

**Comment by smilerz** [comment]
OK - I'll take a look, that should work.

**Comment by smilerz** [comment]
fixed in #1240
