### ISSUE TITLE
shopping list v2: finish all with one click

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1187]
In Shopping list v2: It would be great if it's possible to finish all ingredients of a recipe / categories / Created_by with one click

**Comment by vabene1111** [comment]
could be a context menu on the group header and check depending on what you group by 🤔

**Comment by smilerz** [comment]
> could be a context menu on the group header and check depending on what you group by 🤔

I like that - you can finish a category all at once

**Comment by smilerz** [comment]
Implemented in #1240
