### ISSUE TITLE
Try to Import from KALORIO data export

### ISSUE THREAD

**Issue by peschau** [TandoorRecipes/recipes#1188]
Hi,

just installed a test for tandoor recipes with the actual docker image (Version 1.0.4). Quite happy with the interface, it ist nessessary for a good WAF to import the "old" data from our current KALORIO Database. Kalorio is able to export in different formats (e.g. MealMaster, CookML and RezKonv). I exported one recipe in all versions but it is not possible to import to Tandoor Recipes. (Import, Anwendung, select MealMaster / RezKonv, select file to import). Always get errormessage:

`
ERROR An unexpected error occurred during the import. Please make sure you have uploaded a valid file.
Imported 0 recipes.
`

Any Idea what may be wrong? Added one Recipe in RezKonv and MealMaster Format.

Regards,
Peter

[RezKonvExample.zip](https://github.com/TandoorRecipes/recipes/files/7795678/RezKonvExample.zip)
[MealMasterExample.zip](https://github.com/TandoorRecipes/recipes/files/7795679/MealMasterExample.zip)

**Comment by vabene1111** [comment]
dont have time to properly investigate now but there is this line in there with QUELLE which i have neither seen in rezkonv nor in mm spec, i will take a look in a few days and fix this or look what else might be broken, then it should be working

**Comment by peschau** [comment]
Hi,
my wife is really interested in using Tandoor recipes but not without a way to migrate all recipes from our old system. Is there a way to get a working rezkonv or mealmaster file, that is importable? It should be possible to adjust the output of kalorio to an importable format with some awk or sed magic. But for that I need a working template.

Regards 
Peter

**Comment by vabene1111** [comment]
hi peter, sorry i have not yet had time to look at this (and have also overlooked this issue). These old MM and rezkonv formats are a bit of a pain to work with but it is probably easier to fix the importer in tandoor than to write a script to fix the source files. 

this is an example rezkonv recipe
```
========== RezkonvSuite Rezept ==========

     Titel: Bataten-Thymian-Pfanne
Kategorien: Kartoffel-, Gemüsegerichte, Kartoffel
     Menge: 4 Portionen

    250     Gramm  Speck; mager, geräuchert
      1        kg  Bataten; (Süßkartoffel)
      2            Zwiebeln
     20     Gramm  Butterschmalz
    1/8       Ltr. Trockener Weißwein
    1/8       Ltr. Gemüsebrühe; Instant
                   ; Salz
                   ; Pfeffer
    1/2      Bund  Thymian

===================== ZUBEREITUNGSZEIT CA. =====================
     45            - Minuten

======================== PRO PORTION CA ========================
                   -- Kalorien: 702
                   -- Joule: 2945

Zubereitung:
Speck würfeln. Bataten schälen, waschen und in 3 bis 4 cm große
Würfel schneiden.

Zwiebel pellen und ebenfalls würfeln. Butterschmalz erhitzen, Speck
darin anbraten. Bataten und Zwiebel zufügen und ebenfalls darin
anbraten.

Mit Wein und Brühe ablöschen, mit Salz und Pfeffer würzen. Zugedeckt
etwa Minuten garen.

Thymian waschen, Blättchen von den Stielen streifen und 5 Minuten
vor Garende zu den Bataten geben. Sofort servieren.

Dazu paßt gebratenes Rumpsteak
* Quelle: erfaßt von I. Benerts 03.02.96

:Erfasser       : Ingrid
:Datum          : 31.03.1996

=====
```

this is from the example above
```
========== 'Kalorio V4.03' (reg.) nach REZKONV

     Titel: Nudelauflauf mit Paprika und Zucchini
Kategorien: Auflauf, Hauptspeise, Teigwaren
     Menge: 4 Personen

    300     Gramm  Zucchini
    500     Gramm  Paprika
                   - rot und gelb
      1     Stück  Zwiebel
    500     Gramm  Nudeln
     50     Gramm  Butter
     30     Gramm  Mehl
    300        ml  Brühe
    150        ml  Sahne
    100        ml  Weißwein
    150     Gramm  Reibekäse
                   Basilikum
                   Salz
                   Pfeffer
                   Muskat

============================= QUELLE ================================
           ck
           - Erfasst am 20.3.2010 von
           - Birgit

Nudeln in Salzwasser bissfest kochen

Zwiebeln in etwas Öl andünsten, Paprika würfeln, Zucchini in dünne
Scheiben schneiden und kurz mitdünsten.

Butter schmelzen, mit Mehl bestäuben und etwas anschwitzen lassen. Mit
der Brühe, den Wein (wenn kein Wein da ist, kann man auch etwas mehr
Brühe nehmen) und der Sahne ablöschen und etwas köcheln lassen. Die
Hälfte des Käses einrühren und in der Sauce schmelzen lassen. Die
Sauce mit Salz, Pfeffer und Muskat abschmecken und über die
Nudel-Gemüse-Mischung in die Auflaufform geben.

Basilikum fein schneiden und mit dem restl. Reibekäse über dem Auflauf
verteilen. Bei 200 °C ca. 30 Min. backen.

:Quelle         : ck
:Erfasser       : Birgit
:Erfasst am     : 20.3.2010
:Letzte Änderung: Birgit
:Letzte Äend. am: 20.3.2010
:Fingerprint    : 31695711,1690076609,Kalorio


=====
```

i will see if i find time today to fix this as i hace improved several importers for the next update but not sure, if i dont get back to this its probably just removing the ==QUELLE line. Or you can take a look at the `rezkonv.py` and see if you can fix that mess of an importer I made there :joy:

**Comment by vabene1111** [comment]
ok i improved the rezkonv importer so now you should be able to import KALORIO data. Will be released with the next version but feel free to give the dev branch a try if you haven't setup tandoor anyway and just see if your import goes trough.
