### ISSUE TITLE
Duplicate recipe

### ISSUE THREAD

**Issue by Programie** [TandoorRecipes/recipes#1190]
Sometimes, I want to reuse a recipe (i.e. using the same ingredients) for another recipe I want to create.

A simple "Duplicate" option should be added to the dropdown menu of a recipe. The new option should then open the "Edit Recipe" page but labeled "Create recipe" and save the recipe as a new one instead of editing the existing one.

Example:
![image](https://user-images.githubusercontent.com/1206521/147822574-cb265b91-3733-473e-9aba-5111e5ee573a.png)

**Comment by Nokkvi** [comment]
This seems like a good issue to start with. Can I work on this?

**Comment by vabene1111** [comment]
sure, you can. I would suggest you implement a method on the recipe model that handles duplication which can be reused later on.
