### ISSUE TITLE
Wrong textsize by unsing "line" in texteditor 

### ISSUE THREAD

**Issue by solaris7590** [TandoorRecipes/recipes#1204]
### Version
Version: 1.0.4

### Bug description

When I create a recipe, there is the possibility to insert a line in the texteditor. Everything is correct in the preview on the right side:

![1](https://user-images.githubusercontent.com/77384001/147858079-f62d183e-5e57-4b4f-b10f-12799f54dfa2.PNG)

After saving and viewing the recipe, there is no line. Everything above the line is written in big letters and the numbering is incorrect:

![2](https://user-images.githubusercontent.com/77384001/147858087-10503dfa-8c09-4381-8f80-b4770e0f2a20.PNG)

**Comment by vabene1111** [comment]
can you put an empty row between the first point and the rest ? i think the python markdown renderer interprets the line under text as a headline while the javascript frontend does not

**Comment by solaris7590** [comment]
Yes, that solves the porblem with the lines and the big letters. But the numbering problem is still there. In the editor is 1. 2. 3. in the recipe is 1. 1. 1.

<img width="427" alt="1" src="https://user-images.githubusercontent.com/77384001/147873474-107c644e-d857-457d-9f33-b8229778ca6b.PNG">
<img width="615" alt="2" src="https://user-images.githubusercontent.com/77384001/147873477-0b3ea208-296d-40ce-9935-2a6039b6c879.PNG">

**Comment by vabene1111** [comment]
the "recipe" version is actually the correct rendering according to your input and the commonly accepted markdown spec. 
if you want to put an element between list items you need to indent it by 4 spaces or a tab

```
1. first

    ----

2. second
```
you can refer to this as the specification on how formatting is done https://www.markdownguide.org/basic-syntax/#adding-elements-in-lists 

I have tested the above in Tandoor 1.0.4 and it works as expected
![image](https://user-images.githubusercontent.com/6819595/147875676-9679f97e-3987-4449-b254-32d94cbb1a27.png)


Please see this for why the "preview" differs from the actual render https://github.com/TandoorRecipes/recipes/issues/1152#issuecomment-1000259010

**Comment by solaris7590** [comment]
yes, now it's working. Thanks for your support.
