### ISSUE TITLE
Description in shopping list V2

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1205]
**Is your feature request related to a problem? Please describe.**
I have some text in the Description field of an ingredient. In shopping list v2 these description is not visible.

**Describe the solution you'd like**
With `Show Details` I see the user and time the ingredients was added. I want also the description field from the ingredient.

**Comment by vabene1111** [comment]
intersting, this could be displayed under show details and there could be a small icon on the entry to indicate there is something more to this ? maybe same for notes

**Comment by MarcusWolschon** [comment]
I have the same issue.
A practical example:

_amount: "1"
unit: "pcs"
ingredient: "lemon"
Note: "zest only"<<<<<_  

In the shopping list, this would show you that you'll have lemon juice left over and should think about doing something with it.

**Comment by smilerz** [comment]
> I have the same issue. A practical example:
> 
> _amount: "1" unit: "pcs" ingredient: "lemon" Note: "zest only"<<<<<_
> 
> In the shopping list, this would show you that you'll have lemon juice left over and should think about doing something with it.

Ingredient notes are included in the shopping list

**Comment by MarcusWolschon** [comment]
> > I have the same issue. A practical example:
> > _amount: "1" unit: "pcs" ingredient: "lemon" Note: "zest only"<<<<<_
> > In the shopping list, this would show you that you'll have lemon juice left over and should think about doing something with it.
> 
> Ingredient notes are included in the shopping list

No.
The note of the system-wide Ingredient is but not the note that Ingredient has in the receipt when it was added to the list.

**Comment by smilerz** [comment]
> > > I have the same issue. A practical example:
> > > _amount: "1" unit: "pcs" ingredient: "lemon" Note: "zest only"<<<<<_
> > > In the shopping list, this would show you that you'll have lemon juice left over and should think about doing something with it.
> > 
> > 
> > Ingredient notes are included in the shopping list
> 
> No. The note of the system-wide Ingredient is but not the note that Ingredient has in the receipt when it was added to the list.

The v2 shopping list does this.
