### ISSUE TITLE
Meaningful Servings Error

### ISSUE THREAD

**Issue by melayyalem** [TandoorRecipes/recipes#1206]
When creating/changing a recipe and adding non numeric values to Servings field I get an error:  There was an error updating a resource!

Took a while to figure it out, that it has to do with the Servings input. In my example I had Servings: "4 baguettes".
A suggestion would be a more descriptive error message. Or even better, only the first numeric value should be taken as the calculation factor for the ingredients.

**Comment by vabene1111** [comment]
this was just fixed in 1.0.4, can you confirm this ?

**Comment by melayyalem** [comment]
Oh, sorry, my bad! Just forgot to remove the version tag in docker.
Can confirm that this is solved with #1164.

**Comment by vabene1111** [comment]
Awesome, thanks
