### ISSUE TITLE
"There was an error updating a resource!" in case of validation errors while saving recipe

### ISSUE THREAD

**Issue by Programie** [TandoorRecipes/recipes#1212]
### Version
Version: 1.0.4

### Bug description
Tandoor Recipes validates the user input while saving the recipe. In case of an input error, the request is rejected with an HTTP error 400 (Bad Request) and the error is returned in the JSON response. Unfortunately, the website only shows a popup saying "There was an error updating a resource!", but the exact cause is not included.

### Steps to reproduce
Edit a recipe and change something to an invalid input value. In my case, I triggered the error by removing the step time (leaving the field empty) which resulted in an error "A valid integer is required." being returned in the JSON response of the API call.

### What I would expect
The error popup should show the exact cause. For example if something in the steps went wrong, at least the cause (i.e. "A valid integer is required.") should be shown in the popup, ideally in combination with the name/number of the step (i.e. "Step 4: A valid integer is required.").

**Comment by vabene1111** [comment]
this should already have been fixed, i will look into it why this is still happending. other than that you are correct in that a better front hand error handling is needed, i just cant find the issue were i already talked about this right now but its on the shedule.

**Comment by vabene1111** [comment]
in my current version i found no input with wich i could trigger an issue, if you see anything after the 1.0.5 release let me know and i will fix it. Otherwise a proper frontend input validation system is on the roadmap.
