### ISSUE TITLE
Import of Mela recipes

### ISSUE THREAD

**Issue by Metaman99** [TandoorRecipes/recipes#1226]
I would like to see an import function for recipes from Mela.
https://mela.recipes/
available for iOS and macOS

**Comment by vabene1111** [comment]
since i dont own any apple products do you think you could provide me with a data export from the mela application that i can use to develop the importer ?

you can send it to me via email if you dont want to post it publicly you can send it to info@tandoor.dev

**Comment by Metaman99** [comment]
Here are some export files from Mela 1.2.2 (macOS)
There three supported export formats, when exporting one recipe: melarecipes, PDF and Markdown (without pictures)
Export of the complete recipe database is melarecipes only.
Please find attached examples for Markdown and PDF.
I will send you the other examples by email, as GitHub will not let me upload that files.

[Rezepte für wenig Geld: Gnocchi wie in Italien – selbst gemacht.md](https://github.com/TandoorRecipes/recipes/files/7841351/Rezepte.fur.wenig.Geld.Gnocchi.wie.in.Italien.selbst.gemacht.md)
[Rezepte für wenig Geld: Gnocchi wie in Italien – selbst gemacht.pdf](https://github.com/TandoorRecipes/recipes/files/7841356/Rezepte.fur.wenig.Geld.Gnocchi.wie.in.Italien.selbst.gemacht.pdf)

**Comment by vabene1111** [comment]
awesome, thank you. I have not yet received a mail yet but i will assume that it will follow (just letting you know in case you send it and it did not went trough).

**Comment by Metaman99** [comment]
I sent the email directly after my post.
But ... not to info@tandoor.dev :-/
Resubmitted that email now.

**Comment by vabene1111** [comment]
awesome, thank you. I saved the files for when i will implement this

**Comment by vabene1111** [comment]
implemented in next release, thanks for the sample files those really helped
