### ISSUE TITLE
Can't import recipe from chefkoch.de

### ISSUE THREAD

**Issue by screendriver** [TandoorRecipes/recipes#1231]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 1.0.4

According to [this test](https://github.com/TandoorRecipes/recipes/blob/f66bf13ec57b0b4ca1603059656b8721593f80f6/cookbook/tests/other/_recipes.py#L322) importing from chefkoch.de should work.

### Information
Exact URL you are trying to import from: https://www.chefkoch.de/rezepte/1491131254215808/Spaghetti-Carbonara.html (but it happens to **all** URLs from chefkoch.de)

When did the issue happen: When pressing the search button with the url

Response/Message shown 
```
There was an error loading a resource! <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>
```

<img width="364" alt="Screenshot 2022-01-04 at 18 45 19" src="https://user-images.githubusercontent.com/149248/148101605-536f997a-9d1b-4507-b168-f778bc02babe.png">

It is a completely fresh and completely new (because I just found `Tandoor` out today 🙂 ) on my `Synology` NAS with the help of [this installation instructions](https://docs.tandoor.dev/install/synology/).

**Comment by vabene1111** [comment]
interesting i am importing from chefkoch all the time and it has always worked .. we will take a look

**Comment by screendriver** [comment]
It's working now. Seems like a temporary issue yesterday on chefkoch.de? 🤔
