### ISSUE TITLE
Sort list of keywords, ingredients and books in advanced search settings

### ISSUE THREAD

**Issue by Programie** [TandoorRecipes/recipes#1232]
Currently, the list of keywords, ingredients and books in the advanced search settings are sorted in a random order (I guess in the order they appear in the database).

Those list items should be sorted alphabetically to make it easier to find them.

![image](https://user-images.githubusercontent.com/1206521/148113219-f40e7df5-3afa-4d1f-812e-0887af6583f1.png)

**Comment by smilerz** [comment]
@Programie you have two choices to get the ordering that you want for ingredients/keywords, both require using admin interface located in the top right corner.

option 1:  Sort all keywords/foods using the option highlighted below.   This is an extremely expensive operation and can cause some setups to freeze completely.
![image](https://user-images.githubusercontent.com/1808639/148114981-8ce76441-92b1-429c-812d-e68cbe3f51bb.png)

option 2: manually sort objects in admin using the drag/drop handle.
![image](https://user-images.githubusercontent.com/1808639/148115047-858696d0-e9c9-492f-b8d9-57c059a1be07.png)

**Comment by Programie** [comment]
I've tried with "Fix problems and sort tree by name" which works. But this would only fix the issue temporarily until I add another keyword/ingredients.

A real thinks for the issue would be to simply sort the list either whenever something is changed in the table (i.e. while adding or modifying keywords/ingredients) or sort the list while retrieving the data.

As the application is using a database in the background, shouldn't a simple "ORDER BY name" help in that case? Sorting a few hundred items in a table shouldn't be a big issue.

**Comment by smilerz** [comment]
> A real fix for the issue would be to simply sort the list either whenever something is changed in the table (i.e. while adding or modifying keywords/ingredients) or sort the list while retrieving the data.
Unfortunately, the food/keywords are a hierarchy so there isn't really an 'order' to sort by.  Various workarounds we've tried have had severe performance impacts for larger implementations.

**Comment by Programie** [comment]
OK, that makes sense to me.

**Comment by smilerz** [comment]
> OK, that makes sense to me.

thanks for understanding.  It's something that we want to improve, there just isn't a quick fix.
