### ISSUE TITLE
servings in shopping list v2

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1233]
In Shopping list v2 I can change the servings in recipes tab.

I can set decimals with comma separated values. e.g. `2,5`. With a point `2.5` the recipe disappears. Is it possible to do a check in the field?

It would be great If the servings steps (arrow up/down) could be changed in the settings: step 1 or 0,5.

**Comment by vabene1111** [comment]
i dont really like fixed steps for increments and decrements, people expect the default browser behavior but we need to look into why , works and . not. Usually those fields work depending on the browser locale, so it should be automatic but we can look into this.

**Comment by smilerz** [comment]
I use US for decimal and it works fine, so must be a browser issue.

**Comment by smilerz** [comment]
> i dont really like fixed steps for increments and decrements, people expect the default browser behavior but we need to look into why , works and . not. Usually those fields work depending on the browser locale, so it should be automatic but we can look into this.

for the locale selected this works as expected
