### ISSUE TITLE
number of ingredients/recipes in shopping list v2 tabs

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1234]
**Is your feature request related to a problem? Please describe.**
In the shopping list v2 I see the different ingredients, default grouped by category. It would be great If I can see the number of added ingredients/recipes in the tabs.

**Describe the solution you'd like**
tab recipes: `Shopping List (19) | Recipes (3) | Supermarkets (2)`

**Comment by vabene1111** [comment]
interesting idea. i think the list is easy i dont know if the other tabs are loaded asyncly so that would not work but if they are loaded in advance (at least the recipes should be) this should be easy to implement

**Comment by GauravPawarGithub** [comment]
hey i am a newbie in open source 
I know HTML , can i work on this issue 
and can you please give me some hint about what exactly i should do @vabene1111 @TWART016

**Comment by TWART016** [comment]
It would be great if there is the count in the headline of the tab.
- Shopping List: count items on shopping list.
- Recipes: count of recipes on shopping list

![image](https://user-images.githubusercontent.com/29805669/161859227-6bb3c1e4-2d5c-4d52-b704-d3e464090dd5.png)

**Comment by GauravPawarGithub** [comment]
I am interested in this issue, can I work on this?

**Comment by vabene1111** [comment]
sure, go for it

**Comment by anaymody** [comment]
@GauravPawarGithub @vabene1111 
Hey, I am also a newbie and I am interesting in taking a crack at the issue. Are you still working on it? Thanks

**Comment by vabene1111** [comment]
Feel free to give it a try

**Comment by vabene1111** [comment]
Why are you coukting html elements instead of just taking the length of the array that is rendered?

**Comment by anaymody** [comment]
I am not entirely sure how to do that since I am trying open source contributions for the first time for my school project, but I will look into the array method and try to find a solution. Thanks!

**Comment by Ishjot-Singh** [comment]
Hey, I am new to open-source and I am trying to make my first contribution. Can I have a go at this issue?
