### ISSUE TITLE
Clicking export all recipes should not require selecting a recipe first

### ISSUE THREAD

**Issue by Tuphal** [TandoorRecipes/recipes#1237]
**Is your feature request related to a problem? Please describe.**
In the export page I need to choose every single recipe.

**Describe the solution you'd like**
A placeholder like "*" to choose all recipes for a json-backup would be perfect

**Additional context**
I'd like to backup the recipes as json. A backup of the container&database is too much "work".
A json-file is more futture proof for later migration/restore.

**Comment by kpontussvensson** [comment]
If you check the "All" checkbox you get all recipes even though you only choose one. However the real issue is that you shouldn't need to choose a recipe at all if you check the "All" checkbox in my opinion.

**Comment by Tuphal** [comment]
I thought this, but I get the error, that I should choose an entry:
![grafik](https://user-images.githubusercontent.com/42291781/148222836-d5e78201-c2c4-4040-9ca9-b84aa855a61b.png)

**Comment by vabene1111** [comment]
fixed in next release
