### ISSUE TITLE
Server error (500): DoesNotExist at /accounts/login/

### ISSUE THREAD

**Issue by solaris7590** [TandoorRecipes/recipes#1241]
### Version
Version: 1.0.4
Installed on a Raspberry Pi 3B+ with the newest Raspian with docker-compose.

### Bug description
My tandoor ran absolutely without any problems until yesterday. Suddenly I can no longer access the login page. It always appears "Server Error (500)".
With the devices where the login is saved and I no longer have to log in, everything still works without any problems (I just can't logout otherwise I won't be able to login again).
I've already tried everything possible with the docker-compose command with down, rm, stop, but it's always the same.
Now I have activated the debugging mode in the .env file; now it brings the following error message:

<img width="525" alt="1" src="https://user-images.githubusercontent.com/77384001/148297620-948bb0d9-6af6-4073-802f-1a04fca33937.png">

I have no idea why the site /accounts/login/ suddenly no longer exists?!

The log of the container start is absolutly correct.

That's the log of the debug page:

> Environment:
> 
> 
> Request Method: GET
> Request URL: http://***.ddns.net/accounts/login/?next=/search/
> 
> Django Version: 3.2.10
> Python Version: 3.9.5
> Installed Applications:
> ['dal',
>  'dal_select2',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.sites',
>  'django.contrib.staticfiles',
>  'django.contrib.postgres',
>  'django_prometheus',
>  'django_tables2',
>  'corsheaders',
>  'django_filters',
>  'crispy_forms',
>  'rest_framework',
>  'rest_framework.authtoken',
>  'django_cleanup.apps.CleanupConfig',
>  'webpack_loader',
>  'django_js_reverse',
>  'hcaptcha',
>  'allauth',
>  'allauth.account',
>  'allauth.socialaccount',
>  'cookbook.apps.CookbookConfig',
>  'treebeard']
> Installed Middleware:
> ['corsheaders.middleware.CorsMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'whitenoise.middleware.WhiteNoiseMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.locale.LocaleMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'cookbook.helper.scope_middleware.ScopeMiddleware']
> 
> 
> 
> Traceback (most recent call last):
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
>     return view(request, *args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 146, in dispatch
>     return super(LoginView, self).dispatch(request, *args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 74, in dispatch
>     response = super(RedirectAuthenticatedUserMixin, self).dispatch(
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 90, in get
>     response = super(AjaxCapableProcessFormViewMixin, self).get(
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 133, in get
>     return self.render_to_response(self.get_context_data())
>   File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 177, in get_context_data
>     site = get_current_site(self.request)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
>     return Site.objects.get_current(request)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/models.py", line 58, in get_current
>     return self._get_site_by_id(site_id)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
>     site = self.get(pk=site_id)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
>     raise self.model.DoesNotExist(
> 
> Exception Type: DoesNotExist at /accounts/login/
> Exception Value: Site matching query does not exist.
>

**Comment by smilerz** [comment]
can you share your docker compose and .env file please

**Comment by solaris7590** [comment]
I think my config is the standard config.

Here the .yml:

```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 85:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media

volumes:
  nginx_config:
  staticfiles:
```

And here the .evn:

```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=1
SQL_DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=kochbuch.ddns.net

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
SECRET_KEY=****

# your default timezone See https://timezonedb.com/time-zones for a list of timezones
TIMEZONE=Europe/Berlin

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
# DB_OPTIONS= {} # e.g. {"sslmode":"require"} to enable ssl
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=****
POSTGRES_DB=djangodb

# database connection string, when used overrides other database settings.
# format might vary depending on backend
# DATABASE_URL = engine://username:password@host:port/dbname

# the default value for the user preference 'fractions' (enable/disable fraction support)
# default: disabled=0
FRACTION_PREF_DEFAULT=0

# the default value for the user preference 'comments' (enable/disable commenting system)
# default comments enabled=1
COMMENT_PREF_DEFAULT=1

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# Default for user setting sticky navbar
# STICKY_NAV_PREF_DEFAULT=1

# If base URL is something other than just /  (you are serving a subfolder in your proxy for instance http://recipe_app/recipes/)
# SCRIPT_NAME=/recipes

# If staticfiles are stored at a different location uncomment and change accordingly, MUST END IN /
# this is not required if you are just using a subfolder
# This can either be a relative path from the applications base path or the url of an external host
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly, MUST END IN /
# this is not required if you are just using a subfolder
# This can either be a relative path from the applications base path or the url of an external host
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0

# S3 Media settings: store mediafiles in s3 or any compatible storage backend (e.g. minio)
# as long as S3_ACCESS_KEY is not set S3 features are disabled
# S3_ACCESS_KEY=
# S3_SECRET_ACCESS_KEY=
# S3_BUCKET_NAME=
# S3_REGION_NAME= # default none, set your region might be required
# S3_QUERYSTRING_AUTH=1 # default true, set to 0 to serve media from a public bucket without signed urls
# S3_QUERYSTRING_EXPIRE=3600 # number of seconds querystring are valid for
# S3_ENDPOINT_URL= # when using a custom endpoint like minio

# Email Settings, see https://docs.djangoproject.com/en/3.2/ref/settings/#email-host
# Required for email confirmation and password reset (automatically activates if host is set)
EMAIL_HOST=smtp.mail.de
EMAIL_PORT=587
EMAIL_HOST_USER=****
EMAIL_HOST_PASSWORD=****
EMAIL_USE_TLS=1
EMAIL_USE_SSL=0
DEFAULT_FROM_EMAIL=****@mail.de # email sender address (default 'webmaster@localhost')
ACCOUNT_EMAIL_SUBJECT_PREFIX="[Tandoor Rezeptwelt] "# prefix used for account related emails (default "[Tandoor Recipes] ")

# allow authentication via reverse proxy (e.g. authelia), leave off if you dont know what you are doing
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0

# Default settings for spaces, apply per space and can be changed in the admin view
# SPACE_DEFAULT_MAX_RECIPES=0 # 0=unlimited recipes
# SPACE_DEFAULT_MAX_USERS=0 # 0=unlimited users per space
# SPACE_DEFAULT_MAX_FILES=0 # Maximum file storage for space in MB. 0 for unlimited, -1 to disable file upload.
# SPACE_DEFAULT_ALLOW_SHARING=1 # Allow users to share recipes with public links

# allow people to create accounts on your application instance (without an invite link)
# when unset: 0 (false)
# ENABLE_SIGNUP=0

# If signup is enabled you might want to add a captcha to it to prevent spam
# HCAPTCHA_SITEKEY=
# HCAPTCHA_SECRET=

# if signup is enabled you might want to provide urls to data protection policies or terms and conditions
# TERMS_URL=
# PRIVACY_URL=
# IMPRINT_URL=

# enable serving of prometheus metrics under the /metrics path
# ATTENTION: view is not secured (as per the prometheus default way) so make sure to secure it
# trough your web server (or leave it open of you dont care if the stats are exposed)
# ENABLE_METRICS=0

# allows you to setup OAuth providers
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# SOCIAL_PROVIDERS = allauth.socialaccount.providers.github, allauth.socialaccount.providers.nextcloud,

# Should a newly created user from a social provider get assigned to the default space and given permission by default ?
# ATTENTION: This feature might be deprecated in favor of a space join and public viewing system in the future
# default 0 (false), when 1 (true) users will be assigned space and group
# SOCIAL_DEFAULT_ACCESS = 1

# if SOCIAL_DEFAULT_ACCESS is used, which group should be added
# SOCIAL_DEFAULT_GROUP=guest

# Django session cookie settings. Can be changed to allow a single django application to authenticate several applications
# when running under the same database
# SESSION_COOKIE_DOMAIN=.example.com
# SESSION_COOKIE_NAME=sessionid # use this only to not interfere with non unified django applications under the same top level domain

# by default SORT_TREE_BY_NAME is disabled this will store all Keywords and Food in the order they are created
# enabling this setting makes saving new keywords and foods very slow, which doesn't matter in most usecases.
# however, when doing large imports of recipes that will create new objects, can increase total run time by 10-15x
# Keywords and Food can be manually sorted by name in Admin
# This value can also be temporarily changed in Admin, it will revert the next time the application is started
# This will be fixed/changed in the future by changing the implementation or finding a better workaround for sorting
# SORT_TREE_BY_NAME=0
# LDAP authentication
# default 0 (false), when 1 (true) list of allowed users will be fetched from LDAP server
#LDAP_AUTH=
#AUTH_LDAP_SERVER_URI=
#AUTH_LDAP_BIND_DN=
#AUTH_LDAP_BIND_PASSWORD=
#AUTH_LDAP_USER_SEARCH_BASE_DN=
```

**Comment by smilerz** [comment]
Are you using a reverse proxy in front of the nginx container?

**Comment by solaris7590** [comment]
No, I dont

**Comment by smilerz** [comment]
I just setup a blank copy of the 1.0.4 container and don't have an issue.
The nginx port is listening on 85 instead of 80 - how are you getting the domain to resolve to port 85?
```
  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 85:80
```

**Comment by solaris7590** [comment]
It's a router configuration; I opened the port 80 and forward it to port 85. I did this because on port 80 there's something different.
The weird thing about that is that everything worked fine for about one month and suddenly this error appears...

**Comment by solaris7590** [comment]
And as I wrote above, on my PC, where I use the option "remember Login", everything is perfect - no error.
But if I open the website with icognito mode (without Cookies etc.), the error exists. It's only the Login page, that makes the error

**Comment by smilerz** [comment]
> And as I wrote above, on my PC, where I use the option "remember Login", everything is perfect - no error. But if I open the website with icognito mode (without Cookies etc.), the error exists. It's only the Login page, that makes the error

If you Shift-F5 to clear the cache do you still have the issue?

**Comment by solaris7590** [comment]
Yes, and the error appears on multiple devices

**Comment by vabene1111** [comment]
and just to be clear you did not perform any updates, it just stopped working from one day to the other ?

**Comment by solaris7590** [comment]
yes. I did the update to 1.0.4 on the 01.01.2022 and the error appears since 04.01.2022.

The only thing that could be related to the error is a power failure on this day.

**Comment by smilerz** [comment]
> and just to be clear you did not perform any updates, it just stopped working from one day to the other ?

@vabene1111  could this be the same thing as the issue we've seen a couple times about a missing file after power loss?

@solaris7590 can you stop your container, delete the file staticfiles.json located in staticfiles and restart the container?

**Comment by solaris7590** [comment]
I'm not sure if I deleted the right staticfiles.json (/var/lib/docker/volumes/pi_staticfiles/_data).
That file wasn't empty. I deleted it, but the error is still there.

**Comment by smilerz** [comment]
@solaris7590 - it would be staticfiles configured in the docker config here
```
  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
```

**Comment by solaris7590** [comment]
The path /opt/recipes/staticfiles does not exist here. In opt is no folder called recipes :(

Pulling a new image I already tried, but it looks like he's not redownload the image, just keeps the image that has already been downloaded. How can I delete the downloaded image, that i can pull it one more time?

**Comment by smilerz** [comment]
the /opt path is inside the container.  the /staticfiles/ path would be wherever your docker configuration is by default.

to force a image refresh:
- docker stop web_recipes
- docker container prune
- docker image prune
- then pull/compose image as normal

**Comment by vabene1111** [comment]
very interesting, how did that image get so broken 🤔 but this definitely explains the issue. Maybe also `docker system prune -a` this really kills everything that is not up (even dangling volumes that might be broken)

**Comment by solaris7590** [comment]
I tried it some times, also with the docker system prune -a, but still the same. The command deleted about 1Gb and also pulling worked fine, but my recipes and the Error is still there.

**Comment by vabene1111** [comment]
and the folder inside the container still missing ?

**Comment by smilerz** [comment]
none of this makes any sense.
can you access the site directly?  x.x.x.x:85
are you blocking any cookies somehow?
another thing to try would be to move the contents of staticfiles someplace else and let it rebuild

**Comment by solaris7590** [comment]
@smilerz Same Error as with the domain. No I'm not blocking anything. I'll try with another staticfile path.

@vabene1111 I really don't find anyone of the folder.

**Comment by solaris7590** [comment]
So I deleted again everything with the `docker system prune -a` command, changed the path in the .yml file, did a new pull and after `docker-compose up` everything is still the same.
Looking in the starting log shows, that he still takes the old path.
I backuped all recipes, so is there a possibility so remove all completely and start with a new installation?

**Comment by smilerz** [comment]
> So I deleted again everything with the `docker system prune -a` command, changed the path in the .yml file, did a new pull and after `docker-compose up` everything is still the same. Looking in the starting log shows, that he still takes the old path. I backuped all recipes, so is there a possibility so remove all completely and start with a new installation?

Yes, you can export all of the recipes at /export/ and import them again at /import/  

Then I'd change the name of each container to *_2 (and changing the necessary env settings) and see what that gets you while provding an opportunity to revert back if necessary.

**Comment by smilerz** [comment]
I have one more idea before you blow it all away - what records exist in table `django_site` in the postgres_db?

**Comment by solaris7590** [comment]
How can I see the records in teh table?

**Comment by smilerz** [comment]
connect to the console on the container
`psql djangodb -U djangouser`

then

`select * from django_site`

**Comment by solaris7590** [comment]
After `psql djangodb -U djangouser` `psql: Fehler: FATAL:  Peer-Authentifizierung für Benutzer »djangouser« fehlgeschlagen`

**Comment by smilerz** [comment]
maybe try `psql djangodb -U djangouser --host=localhost`

if that still doesn't work I'm all out of ideas.

**Comment by solaris7590** [comment]
Now he's asking for a password, but the password I set in the .evn file is not working

**Comment by solaris7590** [comment]
Can you tell me how I can remove everything, so that I can start completely new. The `docker system prune -a` command does not remove everything?

**Comment by smilerz** [comment]
stop the nginx, postgres and tandoor containers and delete (or move) the postgres, staticfiles, mediafiles folders in the home directory.

**Comment by solaris7590** [comment]
Today I deleted everything and made a new pull and installation. In the beginning everything worked fine, but after creating my admin account the same error appears.
Next week I will install a completely new raspian-image on the RaspberryPi and hope that solves the problem. Thanks for your help

**Comment by solaris7590** [comment]
I did everything one more time and now I found out what causes this error.

Under admin -> websites there is the standard entry `example.com`. In the moment I delete this entry, the error appears and even adding example.com again can't solve the problem. Maybe you know, why this action causes this error?

**Comment by smilerz** [comment]
> I did everything one more time and now I found out what causes this error.
> 
> Under admin -> websites there is the standard entry `example.com`. In the moment I delete this entry, the error appears and even adding example.com again can't solve the problem. Maybe you know, why this action causes this error?

I was beginning to suspect this is what was going on - that's where I was going with trying to access psql (which I still don't understand why you couldn't connect).

Authentication requires a site and django has a default one in place (ID=1, example.com).  In order to enable authentication tandoor has SITE_ID=1 set.  

@vabene1111 I think I may have done this too in early days.  maybe a migration to rename example.com to something less likely to look like it can be deleted?

**Comment by vabene1111** [comment]
Interesting, I thought Auth worked without sites as well but I guess once it's enabled it doest work without. We could also disallow deletion in the admin so people simply can't delete the default site

**Comment by solaris7590** [comment]
@vabene1111 I think that's a good idea. The reason I wanted to change the domain is because in the verification mail for the mail address always says "Hallo von example.com". So I thought I could change it here.

**Comment by smilerz** [comment]
> @vabene1111 I think that's a good idea. The reason I wanted to change the domain is because in the verification mail for the mail address always says "Hallo von example.com". So I thought I could change it here.

you can edit - you just can't delete!

**Comment by geisterfurz007** [comment]
At the very least it's a documentation issue though, I think.

The [docs](https://docs.tandoor.dev/features/authentication/) mention (emphasis mine)

> Select Sites and edit the default site with the URL of your installation **(or create a new)**.

Since the queries site_id appears to be hardcoded (I haven't looked at the code yet), the highlighted part is incorrect. I faced the same issue and the moment I edited the default site and used that in my application, everything worked as expected.

I'd even argue that the site lookup should not be fixed to any site_id but check against the host the request was made from; however I haven't had the chance to dive into the code to see if that was possible or is even a viable idea.

**Comment by serbans99** [comment]
I have ran into the same issue (deleted the example.com site and created a new one for my site), and am getting only error 500 when attempting to get the login page. How can I recover the content of the site before burning it and rebuilding? Or is there a way to "recreate" the default example.com part?

Thanks a lot for your help !
