### ISSUE TITLE
unable to connect to my tandoor website

### ISSUE THREAD

**Issue by maku1958** [TandoorRecipes/recipes#1258]
## Issue
unable to connect

I tried http://myserver:82
and  https://myserver:82

firefox tells me that it is unable to connect to this website 

I would appreciate some Tips.
Manfred

## Setup Info
Version: (can be found on the system page since v0.8.4)
OS: Ubuntu 20.04.5 LTS

Other relevant information regarding your problem (proxies, firewalls, etc.)

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
```
I use the .env file provided by ct.de/yug8 and added POSTGRES_PASSWORD, my SECRET_KEY generated by `base64 /dev/urandom | head -c50` 
and I changed tp the TIMEZONE=Europe/Paris

```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
<-- 
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/DATA/recipes/staticfiles
      - nginx_config:/DATA/recipes/nginx/conf.d
      - ./mediafiles:/DATA/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 82:8080
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media

volumes:
  nginx_config: "cannot find the config file
  staticfiles:.-->
```

### Logs
If you feel like there is anything interesting please post the output of `docker-compose logs` at
container startup and when the issue happens.

**Comment by smilerz** [comment]
The nginx port needs to be 82:80

**Comment by maku1958** [comment]
This is what I get for myserver:82

Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.

**Comment by smilerz** [comment]
@maku1958 can you please share your .env (secrets/passwords redacted) and the output from all 3 docker containers.

**Comment by maku1958** [comment]
`# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=0
SQL_DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
# ---------------------------- REQUIRED -------------------------
SECRET_KEY=***********************************************
# ---------------------------------------------------------------

# your default timezone See https://timezonedb.com/time-zones for a list of timezones
TIMEZONE=Europe/Paris

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
# DB_OPTIONS= {} # e.g. {"sslmode":"require"} to enable ssl
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
# ---------------------------- REQUIRED -------------------------
POSTGRES_PASSWORD=**************************
# ---------------------------------------------------------------
POSTGRES_DB=djangodb

# database connection string, when used overrides other database settings.
# format might vary depending on backend
# DATABASE_URL = engine://username:password@host:port/dbname

# the default value for the user preference 'fractions' (enable/disable fraction support)
# default: disabled=0
FRACTION_PREF_DEFAULT=0

# the default value for the user preference 'comments' (enable/disable commenting system)
# default comments enabled=1
COMMENT_PREF_DEFAULT=1

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# Default for user setting sticky navbar
# STICKY_NAV_PREF_DEFAULT=1

# If base URL is something other than just /  (you are serving a subfolder in your proxy for instance http://recipe_app/recipes/)
# SCRIPT_NAME=/recipes

# If staticfiles are stored at a different location uncomment and change accordingly, MUST END IN /
# this is not required if you are just using a subfolder
# This can either be a relative path from the applications base path or the url of an external host
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly, MUST END IN /
# this is not required if you are just using a subfolder
# This can either be a relative path from the applications base path or the url of an external host
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0

# S3 Media settings: store mediafiles in s3 or any compatible storage backend (e.g. minio)
# as long as S3_ACCESS_KEY is not set S3 features are disabled
# S3_ACCESS_KEY=
# S3_SECRET_ACCESS_KEY=
# S3_BUCKET_NAME=
# S3_REGION_NAME= # default none, set your region might be required
# S3_QUERYSTRING_AUTH=1 # default true, set to 0 to serve media from a public bucket without signed urls
# S3_QUERYSTRING_EXPIRE=3600 # number of seconds querystring are valid for
# S3_ENDPOINT_URL= # when using a custom endpoint like minio

# Email Settings, see https://docs.djangoproject.com/en/3.2/ref/settings/#email-host
# Required for email confirmation and password reset (automatically activates if host is set)
# EMAIL_HOST=
# EMAIL_PORT=
# EMAIL_HOST_USER=
# EMAIL_HOST_PASSWORD=
# EMAIL_USE_TLS=0
# EMAIL_USE_SSL=0
# DEFAULT_FROM_EMAIL= # email sender address (default 'webmaster@localhost')
# ACCOUNT_EMAIL_SUBJECT_PREFIX= # prefix used for account related emails (default "[Tandoor Recipes] ")

# allow authentication via reverse proxy (e.g. authelia), leave off if you dont know what you are doing
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0

# Default settings for spaces, apply per space and can be changed in the admin view
# SPACE_DEFAULT_MAX_RECIPES=0 # 0=unlimited recipes
# SPACE_DEFAULT_MAX_USERS=0 # 0=unlimited users per space
# SPACE_DEFAULT_MAX_FILES=0 # Maximum file storage for space in MB. 0 for unlimited, -1 to disable file upload.
# SPACE_DEFAULT_ALLOW_SHARING=1 # Allow users to share recipes with public links

# allow people to create accounts on your application instance (without an invite link)
# when unset: 0 (false)
# ENABLE_SIGNUP=0

# If signup is enabled you might want to add a captcha to it to prevent spam
# HCAPTCHA_SITEKEY=
# HCAPTCHA_SECRET=

# if signup is enabled you might want to provide urls to data protection policies or terms and conditions
# TERMS_URL=
# PRIVACY_URL=
# IMPRINT_URL=

# enable serving of prometheus metrics under the /metrics path
# ATTENTION: view is not secured (as per the prometheus default way) so make sure to secure it
# trough your web server (or leave it open of you dont care if the stats are exposed)
# ENABLE_METRICS=0

# allows you to setup OAuth providers
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# SOCIAL_PROVIDERS = allauth.socialaccount.providers.github, allauth.socialaccount.providers.nextcloud,

# Should a newly created user from a social provider get assigned to the default space and given permission by default ?
# ATTENTION: This feature might be deprecated in favor of a space join and public viewing system in the future
# default 0 (false), when 1 (true) users will be assigned space and group
# SOCIAL_DEFAULT_ACCESS = 1

# if SOCIAL_DEFAULT_ACCESS is used, which group should be added
# SOCIAL_DEFAULT_GROUP=guest

# Django session cookie settings. Can be changed to allow a single django application to authenticate several applications
# when running under the same database
# SESSION_COOKIE_DOMAIN=.example.com
# SESSION_COOKIE_NAME=sessionid # use this only to not interfere with non unified django applications under the same top level domain

# by default SORT_TREE_BY_NAME is disabled this will store all Keywords and Food in the order they are created
# enabling this setting makes saving new keywords and foods very slow, which doesn't matter in most usecases.
# however, when doing large imports of recipes that will create new objects, can increase total run time by 10-15x
# Keywords and Food can be manually sorted by name in Admin
# This value can also be temporarily changed in Admin, it will revert the next time the application is started
# This will be fixed/changed in the future by changing the implementation or finding a better workaround for sorting
# SORT_TREE_BY_NAME=0
# LDAP authentication
# default 0 (false), when 1 (true) list of allowed users will be fetched from LDAP server
#LDAP_AUTH=
#AUTH_LDAP_SERVER_URI=
#AUTH_LDAP_BIND_DN=
#AUTH_LDAP_BIND_PASSWORD=
#AUTH_LDAP_USER_SEARCH_BASE_DN=

# Enables exporting PDF (see export docs)
# Disabled by default, uncomment to enable
# ENABLE_PDF_EXPORT=1

`
@simlerz here is the .env. As told above it from ct.de/yug8 

Sorry but can you explain how to get the output from all docker containers?
I am normal Linux User for many years but an old school one. I am very new to docker and snap so I have to look up everything. But the install is very convenient so I want to get into it and not staying behind,
Manfred

**Comment by smilerz** [comment]
> Sorry but can you explain how to get the output from all docker containers?
> I am normal Linux User for many years but an old school one. I am very new to docker and snap so I have to look up everything. But the install is very convenient so I want to get into it and not staying behind,

 docker logs CONTAINER_NAME

**Comment by maku1958** [comment]
```
CONTAINER ID   IMAGE                   COMMAND                  CREATED        STATUS       PORTS                               NAMES
0c56756d8dcd   nginx:mainline-alpine   "/docker-entrypoint.…"   46 hours ago   Up 4 hours   0.0.0.0:82->80/tcp, :::82->80/tcp   tandoor_nginx_recipes_1
d16f0fa3e63b   vabene1111/recipes      "/opt/recipes/boot.sh"   2 days ago     Up 4 hours   8080/tcp                            tandoor_web_recipes_1
e31509564b68   postgres:11-alpine      "docker-entrypoint.s…"   2 days ago     Up 4 hours   5432/tcp                            tandoor_db_recipes_1

Did you mean this output ? docker ps

```

**Comment by maku1958** [comment]
```
[2022-01-09 01:07:23 +0000] [1] [INFO] Shutting down: Master
Updating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.
js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse

1 static file copied to '/opt/recipes/staticfiles', 1018 unmodified, 1981 post-processed.
Done
chmod: /opt/recipes/mediafiles: No such file or directory
[2022-01-09 11:49:14 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-01-09 11:49:14 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2022-01-09 11:49:14 +0000] [1] [INFO] Using worker: sync
[2022-01-09 11:49:14 +0000] [18] [INFO] Booting worker with pid: 18
[2022-01-09 18:45:15 +0000] [1] [INFO] Handling signal: term
[2022-01-09 19:45:15 +0100] [18] [INFO] Worker exiting (pid: 18)
[2022-01-09 18:45:15 +0000] [1] [WARNING] Worker with pid 18 was terminated due to signal 15
[2022-01-09 18:45:15 +0000] [1] [INFO] Shutting down: Master
Updating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.
js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse

1 static file copied to '/opt/recipes/staticfiles', 1018 unmodified, 1981 post-processed.
Done
chmod: /opt/recipes/mediafiles: No such file or directory
[2022-01-09 18:53:39 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-01-09 18:53:39 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2022-01-09 18:53:39 +0000] [1] [INFO] Using worker: sync
[2022-01-09 18:53:39 +0000] [11] [INFO] Booting worker with pid: 11
[2022-01-10 00:42:19 +0000] [1] [INFO] Handling signal: term
[2022-01-10 01:42:19 +0100] [11] [INFO] Worker exiting (pid: 11)
[2022-01-10 00:42:20 +0000] [1] [WARNING] Worker with pid 11 was terminated due to signal 15
[2022-01-10 00:42:20 +0000] [1] [INFO] Shutting down: Master
Updating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.
js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse

1 static file copied to '/opt/recipes/staticfiles', 1018 unmodified, 1981 post-processed.
Done
chmod: /opt/recipes/mediafiles: No such file or directory
[2022-01-10 12:26:05 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-01-10 12:26:05 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2022-01-10 12:26:05 +0000] [1] [INFO] Using worker: sync
[2022-01-10 12:26:05 +0000] [11] [INFO] Booting worker with pid: 11
```


Or this? it is the log from Container ID vabene...

**Comment by maku1958** [comment]
here the log from nginx Container-ID:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/01/08 18:24:41 [notice] 1#1: using the "epoll" event method
2022/01/08 18:24:41 [notice] 1#1: nginx/1.21.5
2022/01/08 18:24:41 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
2022/01/08 18:24:41 [notice] 1#1: OS: Linux 5.4.0-92-generic
2022/01/08 18:24:41 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:524288
2022/01/08 18:24:41 [notice] 1#1: start worker processes
2022/01/08 18:24:41 [notice] 1#1: start worker process 24
2022/01/08 18:24:41 [notice] 1#1: start worker process 25
2022/01/08 18:24:41 [notice] 1#1: start worker process 26
2022/01/08 18:24:41 [notice] 1#1: start worker process 27
192.168.178.44 - - [08/Jan/2022:18:24:58 +0000] "GET / HTTP/1.1" 200 615 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
2022/01/08 18:24:58 [error] 27#27: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.178.44, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "mk-server:82", referrer: "http://mk-server:82/"
192.168.178.44 - - [08/Jan/2022:18:24:58 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "http://mk-server:82/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
2022/01/09 01:07:12 [notice] 1#1: signal 15 (SIGTERM) received, exiting
2022/01/09 01:07:12 [notice] 24#24: exiting
2022/01/09 01:07:12 [notice] 25#25: exiting
2022/01/09 01:07:12 [notice] 26#26: exiting
2022/01/09 01:07:12 [notice] 24#24: exit
2022/01/09 01:07:12 [notice] 25#25: exit
2022/01/09 01:07:12 [notice] 26#26: exit
2022/01/08 18:26:03 [notice] 27#27: signal 15 (SIGTERM) received, exiting
2022/01/09 01:07:12 [notice] 27#27: exiting
2022/01/09 01:07:12 [notice] 27#27: exit
2022/01/09 01:07:13 [notice] 1#1: signal 17 (SIGCHLD) received from 24
2022/01/09 01:07:13 [notice] 1#1: worker process 24 exited with code 0
2022/01/09 01:07:13 [notice] 1#1: signal 29 (SIGIO) received
2022/01/09 01:07:13 [notice] 1#1: signal 17 (SIGCHLD) received from 25
2022/01/09 01:07:13 [notice] 1#1: worker process 25 exited with code 0
2022/01/09 01:07:13 [notice] 1#1: signal 29 (SIGIO) received
2022/01/09 01:07:13 [notice] 1#1: signal 17 (SIGCHLD) received from 26
2022/01/09 01:07:13 [notice] 1#1: worker process 26 exited with code 0
2022/01/09 01:07:13 [notice] 1#1: worker process 27 exited with code 0
2022/01/09 01:07:13 [notice] 1#1: exit
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/01/09 11:46:37 [notice] 1#1: using the "epoll" event method
2022/01/09 11:46:37 [notice] 1#1: nginx/1.21.5
2022/01/09 11:46:37 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
2022/01/09 11:46:37 [notice] 1#1: OS: Linux 5.4.0-92-generic
2022/01/09 11:46:37 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:524288
2022/01/09 11:46:37 [notice] 1#1: start worker processes
2022/01/09 11:46:37 [notice] 1#1: start worker process 23
2022/01/09 11:46:37 [notice] 1#1: start worker process 24
2022/01/09 11:46:37 [notice] 1#1: start worker process 25
2022/01/09 11:46:37 [notice] 1#1: start worker process 26
2022/01/09 18:45:15 [notice] 1#1: signal 15 (SIGTERM) received, exiting
2022/01/09 18:45:15 [notice] 25#25: signal 15 (SIGTERM) received, exiting
2022/01/09 18:45:15 [notice] 25#25: exiting
2022/01/09 18:45:15 [notice] 24#24: signal 15 (SIGTERM) received, exiting
2022/01/09 18:45:15 [notice] 24#24: exiting
2022/01/09 18:45:15 [notice] 25#25: exit
2022/01/09 18:45:15 [notice] 24#24: exit
2022/01/09 18:45:15 [notice] 23#23: signal 15 (SIGTERM) received, exiting
2022/01/09 18:45:15 [notice] 23#23: exiting
2022/01/09 18:45:15 [notice] 23#23: exit
2022/01/09 18:45:15 [notice] 26#26: signal 15 (SIGTERM) received, exiting
2022/01/09 18:45:15 [notice] 26#26: exiting
2022/01/09 18:45:15 [notice] 26#26: exit
2022/01/09 18:45:15 [notice] 1#1: signal 17 (SIGCHLD) received from 24
2022/01/09 18:45:15 [notice] 1#1: worker process 24 exited with code 0
2022/01/09 18:45:15 [notice] 1#1: signal 29 (SIGIO) received
2022/01/09 18:45:15 [notice] 1#1: signal 17 (SIGCHLD) received from 25
2022/01/09 18:45:15 [notice] 1#1: worker process 25 exited with code 0
2022/01/09 18:45:15 [notice] 1#1: signal 29 (SIGIO) received
2022/01/09 18:45:15 [notice] 1#1: signal 17 (SIGCHLD) received from 23
2022/01/09 18:45:15 [notice] 1#1: worker process 23 exited with code 0
2022/01/09 18:45:15 [notice] 1#1: signal 29 (SIGIO) received
2022/01/09 18:45:15 [notice] 1#1: signal 17 (SIGCHLD) received from 26
2022/01/09 18:45:15 [notice] 1#1: worker process 26 exited with code 0
2022/01/09 18:45:15 [notice] 1#1: exit
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/01/09 18:52:24 [notice] 1#1: using the "epoll" event method
2022/01/09 18:52:24 [notice] 1#1: nginx/1.21.5
2022/01/09 18:52:24 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
2022/01/09 18:52:24 [notice] 1#1: OS: Linux 5.4.0-92-generic
2022/01/09 18:52:24 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:524288
2022/01/09 18:52:24 [notice] 1#1: start worker processes
2022/01/09 18:52:24 [notice] 1#1: start worker process 24
2022/01/09 18:52:24 [notice] 1#1: start worker process 25
2022/01/09 18:52:24 [notice] 1#1: start worker process 26
2022/01/09 18:52:24 [notice] 1#1: start worker process 27
2022/01/10 00:42:19 [notice] 1#1: signal 15 (SIGTERM) received, exiting
2022/01/10 00:42:19 [notice] 24#24: signal 15 (SIGTERM) received, exiting
2022/01/10 00:42:19 [notice] 26#26: signal 15 (SIGTERM) received, exiting
2022/01/10 00:42:19 [notice] 24#24: exiting
2022/01/10 00:42:19 [notice] 26#26: exiting
2022/01/10 00:42:19 [notice] 25#25: signal 15 (SIGTERM) received, exiting
2022/01/10 00:42:19 [notice] 25#25: exiting
2022/01/10 00:42:19 [notice] 24#24: exit
2022/01/10 00:42:19 [notice] 26#26: exit
2022/01/10 00:42:19 [notice] 25#25: exit
2022/01/10 00:42:19 [notice] 27#27: signal 15 (SIGTERM) received, exiting
2022/01/10 00:42:19 [notice] 27#27: exiting
2022/01/10 00:42:19 [notice] 27#27: exit
2022/01/10 00:42:20 [notice] 1#1: signal 17 (SIGCHLD) received from 26
2022/01/10 00:42:20 [notice] 1#1: worker process 26 exited with code 0
2022/01/10 00:42:20 [notice] 1#1: signal 29 (SIGIO) received
2022/01/10 00:42:20 [notice] 1#1: signal 17 (SIGCHLD) received from 24
2022/01/10 00:42:20 [notice] 1#1: worker process 24 exited with code 0
2022/01/10 00:42:20 [notice] 1#1: signal 29 (SIGIO) received
2022/01/10 00:42:20 [notice] 1#1: signal 17 (SIGCHLD) received from 27
2022/01/10 00:42:20 [notice] 1#1: worker process 27 exited with code 0
2022/01/10 00:42:20 [notice] 1#1: signal 29 (SIGIO) received
2022/01/10 00:42:20 [notice] 1#1: signal 17 (SIGCHLD) received from 25
2022/01/10 00:42:20 [notice] 1#1: worker process 25 exited with code 0
2022/01/10 00:42:20 [notice] 1#1: exit
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/01/10 12:24:09 [notice] 1#1: using the "epoll" event method
2022/01/10 12:24:09 [notice] 1#1: nginx/1.21.5
2022/01/10 12:24:09 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
2022/01/10 12:24:09 [notice] 1#1: OS: Linux 5.4.0-92-generic
2022/01/10 12:24:09 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:524288
2022/01/10 12:24:09 [notice] 1#1: start worker processes
2022/01/10 12:24:09 [notice] 1#1: start worker process 23
2022/01/10 12:24:09 [notice] 1#1: start worker process 24
2022/01/10 12:24:09 [notice] 1#1: start worker process 25
2022/01/10 12:24:09 [notice] 1#1: start worker process 26
```

**Comment by maku1958** [comment]
here from database today:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-01-10 12:24:16.092 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-01-10 12:24:16.092 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-01-10 12:24:16.707 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-01-10 12:24:19.030 UTC [21] LOG:  database system was shut down at 2022-01-10 00:42:22 UTC
2022-01-10 12:24:19.820 UTC [1] LOG:  database system is ready to accept connections

```

So I am getting deeper into the VM .

Hope you can make out something.
Manfred

**Comment by smilerz** [comment]
Is this actually in your `docker-compose.yml`?

```
volumes:
  nginx_config: "cannot find the config file
  staticfiles:.-->
```

**Comment by maku1958** [comment]
I made a new copy of docker-composer.yml

```
Version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/DATA/recipes/staticfiles
      - nginx_config:/DATA/recipes/nginx/conf.d
      - ./mediafiles:/DATA/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 82:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media

volumes:
  nginx_config:
  staticfiles:
```

**Comment by smilerz** [comment]
> I made a new copy of docker-composer.yml

What happens when you recompose the containers and start everything up again?

**Comment by maku1958** [comment]
I cannot find the command recompose

**Comment by smilerz** [comment]
what are the contents of nginx_config?

**Comment by maku1958** [comment]
the path indicated in the docker-composer.yml for nginx_config:/etc/nginx/conf.d:ro
does not exist!
In /etc there is no folder nginx

**Comment by smilerz** [comment]
> the path indicated in the docker-composer.yml for nginx_config:/etc/nginx/conf.d:ro does not exist! In /etc there is no folder nginx

can you join the discord server?

**Comment by maku1958** [comment]
I need more support to jpin the discord server! Do I have to google it? I am not signed up there and do not know discord.

**Comment by smilerz** [comment]
> I need more support to jpin the discord server! Do I have to google it? I am not signed up there and do not know discord.

you can find the link [here](https://github.com/TandoorRecipes/recipes#get-in-touch)

**Comment by scazadar** [comment]
Hi.

you have to change your volumes to the right path:

`  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes`

DATA -> opt (The right side is inside the container and should not be changed.)

Otherwise the nginx config folder can not be shared with the other container, because there ist nothing under /DATA/...


The problem now is, that you have a wrong config docker volume. So you have to delete these.

`
docker-compose down
docker volume rm <foldername>_nginx_config <foldername>_staticfiles
docker-compose up -d
`

Maybe it helps :)

**Comment by smilerz** [comment]
is this issue still open?

**Comment by maku1958** [comment]
I thought I closed it - at least I clicked the button. Manfred --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 25.01.22, 17:05 schrieb smilerz ***@***.***>:

   
  is this issue still open?
