### ISSUE TITLE
tandoor-db_recipes-l segmentation fault

### ISSUE THREAD

**Issue by glammster** [TandoorRecipes/recipes#1259]
Hi @all,

##Issue
I'm facing a problem when starting up tandoor recipe. It ends up in error 502 Manfred mentioned in #1258 but in my case reason seems to be a problem during start of db. I would appreciate any ideas to get this very nice project running.Thanks in advance to all developers for that cool stuff.

Regards 
Jens

## Setup Info
Version: (can be found on the system page since v0.8.4)
OS="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian

I use the .env file provided by ct.de/yug8, just changed Nginx port from 80 to 8081

### `.env`
DEBUG=0
SQL_DEBUG=0

ALLOWED_HOSTS=*

# ---------------------------- REQUIRED -------------------------
SECRET_KEY=
# ---------------------------------------------------------------
timezones
TIMEZONE=Europe/Berlin

POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
# ---------------------------- REQUIRED -------------------------
POSTGRES_PASSWORD=
# ---------------------------------------------------------------
POSTGRES_DB=djangodb

FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0

### `docker-compose.yml`
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 8081:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media

volumes:
  nginx_config:
  staticfiles:

### Logs
Here is the log from db-startup phase

tandoor-db_recipes-1     |
tandoor-db_recipes-1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
tandoor-db_recipes-1     |
tandoor-db_recipes-1     | 1970-05-05 21:57:20.010 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
tandoor-db_recipes-1     | 1970-05-05 21:57:20.010 GMT [1] LOG:  listening on IPv6 address "::", port 5432
tandoor-db_recipes-1     | 1970-05-05 21:57:20.010 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
tandoor-db_recipes-1     | 1970-05-05 21:57:20.010 GMT [1] LOG:  startup process (PID 21) was terminated by signal 11: Segmentation fault
tandoor-db_recipes-1     | 1970-05-05 21:57:20.010 GMT [1] LOG:  aborting startup due to startup process failure
tandoor-db_recipes-1     | 1970-05-05 21:57:20.010 GMT [1] LOG:  database system is shut down
tandoor-db_recipes-1     |

**Comment by smilerz** [comment]
@glammster are you running on Raspberry Pi?  If so, you might need to upgrade docker - see this issue: https://github.com/timescale/timescaledb-docker/issues/136

**Comment by glammster** [comment]
@smilerz yes, running on raspberry Pi 4. upgraded docker but nothing changed. Following mentioned link i ended up that libseccomp2 should be the main cause, but i do not know how to change version. Or alternatively how to use other alpine version. Kindly asking for some hints how to change.

**Comment by smilerz** [comment]
> @smilerz yes, running on raspberry Pi 4. upgraded docker but nothing changed. Following mentioned link i ended up that libseccomp2 should be the main cause, but i do not know how to change version. Or alternatively how to use other alpine version. Kindly asking for some hints how to change.

beyond my skills unfortunately.  maybe [this ](https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/)will help

**Comment by vabene1111** [comment]
this appears to be an issue within the postgres container so i am also out of ideas on what could cause this, especially since tandoor is working on some peoples raspis ...

**Comment by glammster** [comment]
thank you for all your assistance and hints. Now container recipes_db starts correctly. The base problem, why it doesn't work after upgrading docker and libseccomp2 was, not recycling postgresql data from previous container 'faulty' container startups. Deletion with 'rm -rf postgresql' fixed that. Now it's working.
