### ISSUE TITLE
Keywords not saved when importing recipes

### ISSUE THREAD

**Issue by materpillar** [TandoorRecipes/recipes#1263]
### Version
Version: 1.0.4

### Bug description
When importing a recipes (here from chefkoch.de), the keywords are listed properly on the importing page, but are not saved. My keyword list stays empty after the import (I am on a fresh 1.0.4 installation without a recipe book, if it matters).

**Comment by smilerz** [comment]
On the import page did you select the button under keywords that says “import all, even keywords that don’t exist”?

**Comment by materpillar** [comment]
This indeed saved the keywords. So let's correct his bug report to: doesn't import any keywords (also not the new ones), when the box is not ticked.

**Comment by smilerz** [comment]
> This indeed saved the keywords. So let's correct his bug report to: doesn't import any keywords (also not the new ones), when the box is not ticked.

Just to confirm - when the box was not selected some of the keywords that you expected to be imported already existed in the database?

**Comment by materpillar** [comment]
Okay this is on me. I misunderstood the "not only the ones already" construction.

So I understand correctly now:
- If the checkbox is ticked, the imported recipe is tagged with all keywords that the importer shows. Keywords that don't exist yet in the database are added to it.
- if the checkbox is not ticked, the imported recipe is only tagged with the keywords that the importer shows **and** are already existent in the database.

Maybe I am the only one to find the label confusing but I would suggest to call this tickbox "Import new keywords"

**Comment by smilerz** [comment]
a visual indicator of which will be imported vs nice would probably accomplish the same thing.  green = exists/imported, red = not-exist/not-imported, orange = not-exist-imported

or something similar

**Comment by vabene1111** [comment]
yes thats a cool idea !

The idea behind this feature is that some recipe pages add literally hundreds of tags to a recipe and by default this should not clutter your database. But this is a little confusing, i guess we should improve this at some point, maybe together with the rewrite of the importer page to hopefully the normal recipe editor.

**Comment by TWART016** [comment]
I was also confused with Not import. Maybe rename it to: import tags 
and de/activate by default is better.

**Comment by vabene1111** [comment]
or make a drag and drop field of which ones are imported and which ones not .. but i would love to integrate this into the default editor

**Comment by smilerz** [comment]
> No, I do not want to import all keywords, I added an existing keyword. If the checkbox is not checked, no keyword is added in the end.

I just confirmed it works - did you select the keyword from the picklist, or did you type it in manually?

**Comment by Forceu** [comment]
Hm weird. I tried it again and even after clearing the cache I had the same behaviour. I Entered the first two letters of the keyword and then clicked on the entry in the list. The first keyword however that was automatically added is actually a keyword I use as well, however in lowercase and therefore not considered by Tandoor as an existing keyword (the one I selected was a different one though). Maybe that is connected to this bug?

**Comment by vabene1111** [comment]
i honestly have not tested creating a new keyword on the import screen but one of the next things i want to do anyway is remove that screen all together and bascially pass all data directly to the normal recipe editor. There is an open issue for that somewhere
