### ISSUE TITLE
Tandoor on Synology without SSH

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1264]
**Describe the solution you'd like**
An official, single Docker image for use on Synology that can be installed and updated purely via the Synology GUI without having to use docker-compose and thus SSH.
Containing Tandoor, PostgreSQL and web-server in a single image.

**Describe alternatives you've considered**
One of the 0-star rated 3rd party images that probably never get updated.

**Comment by smilerz** [comment]
nginx and postgres are community maintained docker images and won't be recreated as part of Tandoor

**Comment by smilerz** [comment]
Instructions for installing on Synology are [here ](https://docs.tandoor.dev/install/synology/)- no SSH required.
