### ISSUE TITLE
meal plan ton receipt navigation

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1267]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to navigate from the meal plan or the details of a single entry of the meal plan to the receipt.

**Describe the solution you'd like**

1. Add another option to the context menu of a meal plan entry
2. and a button next to the receipt selection in the details of an entry
to navigate to that receipt.

**Additional context**
The meal plan is the obvious start page when the user wants to navigate to the meal to cook next.
The user can not be expected to search the receipt database for the exact name of the receipt seen in the meal plan.

**Comment by smilerz** [comment]
duplicate #1093
