### ISSUE TITLE
ingredient table alignment only per step

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1269]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version:  1.0.4

### Bug description
The ingredients should be one HTML table for all steps instead of a separate table per step.
(using colspan for the rows showing step-names)
This would align the ingredients of the entire receipt in a readable fashion.

![grafik](https://user-images.githubusercontent.com/604692/148701745-17c88ecb-8f50-4a53-96e3-120708493acd.png)

**Comment by smilerz** [comment]
duplicate #967
