### ISSUE TITLE
import nutritional information 

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1270]
**Is your feature request related to a problem? Please describe.**
recipe_html_import.py is missing the fields to attempt an import of nutritional information

**Describe the solution you'd like**
The "nutrition" array as given in
https://developers.google.com/search/docs/advanced/structured-data/recipe
should be added.
Parsing looks similar to ingredients at first glance.

**Additional context**
Sample data:
major website 1
"nutrition":{"@type":"NutritionInformation","calories":"569 kcal","carbohydrateContent":"64 g","fatContent":"20 g","proteinContent":"26 g"}

major website 2
"nutrition":{"calories":405,"proteinContent":30,"fatContent":25,"carbohydrateContent":10,"@type":"NutritionInformation"}

Schema:
https://schema.org/NutritionInformation

**Comment by smilerz** [comment]
duplicate #436

**Comment by MarcusWolschon** [comment]
@smilerz this is NOT a duplicate of #436
#436 is about additing additional fields to the existing nutritional information in receipts

This is about importing nutritional information AT ALL stored in https://schema.org/NutritionInformation format into the receipt when importing a receipt.

**Comment by MarcusWolschon** [comment]
I did add some code to fetch the nutrient data from the scaper.
I just don't know abough about the codebase to put them into the imported receipt yet.
https://github.com/MarcusWolschon/recipes/commit/1609bb347689477375eb0528fa40911ba5365eb4

**Comment by smilerz** [comment]
Before the PR can be merged and nutritional values be imported several other things will need updated:
- the front end will need to be modified to accept the new fields `templates/url_import.html`
- import tests updated `tests/other/test_url_import`

I think all of the existing APIs will function fine.

**Comment by MarcusWolschon** [comment]
@smilerz I got it as far as `templates/url_import.html` with 4 added fields.
The last step would be the method `importRecipe()` to get ir from the form fields into an actual receipt.
It seems to do some HTTP POST but I can't quite see where the form data ends up.

**Comment by smilerz** [comment]
for non-openapi urls you can look in urls.py.

for `data_import_url` you'll find this line:
`path('data/import/url', data.import_url, name='data_import_url'),`

the 2nd element of the tuple shows what code is executed (all urls originate in ./cookbook/views/):  `data.import_url`

**Comment by MarcusWolschon** [comment]
Got it!
https://github.com/TandoorRecipes/recipes/pull/1294

**Comment by smilerz** [comment]
the tests in import tests updated tests/other/test_url_import will need updated before this can be merged.

**Comment by MarcusWolschon** [comment]
If you add to the "docs/contribute.md" how to RUN the tests, I can look into adding a test case.

**Comment by vabene1111** [comment]
its just pytest you can see how they are run in the CI.yml for the CI workflow :) but good idea to add that to the docs as well

**Comment by MarcusWolschon** [comment]
All existing tests for cookbook\tests\other\test_url_import.py are green.
Lots of untouched tests fail.
I'll add test cases (or extend existing ones)  tomorrow.

**Comment by smilerz** [comment]
my guess is that you need to `yarn build` or you have some database setup issues

**Comment by vabene1111** [comment]
and static files need to be collected first as the test runner does not start the dev server

**Comment by smilerz** [comment]
Some context you may find helpful:

- test_data has 14(?) sample html pages
- _recipes.py has the expected values for each of those pages
- test_recipe_import loops through each sample and imports it
- cookbook.tests.conftest.validate_recipe() compares the import to the expected values

**Comment by MarcusWolschon** [comment]
Does anyone know how to ignore the CodeQL false-positives in the pull request?
https://github.com/TandoorRecipes/recipes/pull/1294/checks?check_run_id=4805123637
