### ISSUE TITLE
structured receipt stept end up as single text

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1271]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 1.0.4

### Bug description
It seems that in an import,
structured receipts that already contain separate steps are imported as a single step with all texts combined.
They should become separate steps.
Sample data:
`"recipeInstructions":[{"@type":"HowToStep","text":"this is step 0"},{"@type":"HowToStep","text":"this is step 1"},{"@type":"HowToStep","text":"this is step 2"}]`

**Comment by smilerz** [comment]
duplicate #476
