### ISSUE TITLE
"pop from empty list" in Nextcloud importer

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1274]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version:  1.0.4

### Bug description
At [line 32 in nextcloud.py](https://github.com/TandoorRecipes/recipes/blob/develop/cookbook/provider/nextcloud.py#L32) a list "files" is not checked for being empty with an error message for the user/site administrator.
Instead the application just crashes.
The user/site-administrator should get an erro message. Preferably indicating what settings may be wrong
or at the very least wich of the configured storage sources the issue happened with.

Steps:
Set up a Nextcloud folder according to https://docs.tandoor.dev/features/external_recipes/#Nextcloud
1. "external receips"
2. press button "sync now"
3. "receipts being imported" shown for 2 seconds
4. Get redirected to "/api/sync_all/" showing a very helpful "Server Error (500)"

Error: (only visible with DEBUG=1 in Docker. Else there is no information at all. That missing error message is the bug.)
Exception Value: | pop from empty list
/opt/recipes/cookbook/provider/nextcloud.py, line 32, in import_all
![grafik](https://user-images.githubusercontent.com/604692/148819111-c65f490e-ccdd-4b42-8853-331406df5222.png)

**Comment by MarcusWolschon** [comment]
(
 I already had to guess that a DEBUG=0 means that at least the value 1 could provide some kind of helpful output here.
 There is nothing about error logging in the documentation on the website.
)

**Comment by MarcusWolschon** [comment]
Suggestion:

```
if len(files) == 0:
    log_entry = SyncLog(
            status='FAILED',
            msg='No files in ' + monitor.path,
            sync=monitor,
        )
else 
    files.pop(0)
```

**Comment by vabene1111** [comment]
importing nothing from an empty folder is the expected and correct behavior thus i have added a check to the pop function to not crash if the folder is empty but return a successful but empty import.
