### ISSUE TITLE
allow directories as an alternative to zip files in storage backends

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1276]
**Describe the solution you'd like**
Currently exported receipts need to be stored as .zip files or a .zip file containing many .zip files on a local directory as an external receipt.
It would be an improvement to recognize a directory containing the content of a zip file the same as a .zip file.
This would help to make a directory of exported receipts more human readable and prevent frustration due to
users unpacking the exported .zip files because they aren't told how exactly to handle them by documentation or UI.

**Comment by vabene1111** [comment]
i dont really see why having the export more human readable would improve it ? You export a file and import that exact file again.

We should add a small hint to that in the docs but i am planning on rewriting the whole export/import system anyways, i will add some more context there

**Comment by MarcusWolschon** [comment]
You get a zip file in the export. 
The first thing any user will do is to extract it.
There's more zip files in there. One for every receipt. Well, a user WILL extract these. (Currently a user is not told what to do with it but even if, that will happen.)
Then the obvious thing for a user to do is to store the result for other people to use in a shared directory.
1. Currently setting up such a directory as an external source will not find any receipts and leave the user confused.
2. Other people may use no software at all and just look through the directories on the storage file server for the exported preview-images and PDF and ignore ther .json file next to it. That would be very inconvenient with a directory full of zip files as the user has to download each of them to look inside.

**Comment by vabene1111** [comment]
this is simply not meant/out of scope for what the exporter does. It needs to be clear in the docs how to work with the exporter but i cannot support any special use case. If someone wants to look trough their recipes they can use the new PDF exporter, tandoor or any other recipe manager that can import from tandoor.

**Comment by MarcusWolschon** [comment]
It's for the importer. Not the exporter.
Making the importer more robust.

**Comment by vabene1111** [comment]
in that case i do not understand what you want to do. The importer is already pretty robust as far as i know (and if someone modifies the file its simply not supported). 

But feel free to elaborate what you think is wrong here

**Comment by MarcusWolschon** [comment]
It ignores zip files that have been extracted. There's no reason to not handle these subdirectories the same way a zip file would be handled.

**Comment by vabene1111** [comment]
there is a reason: it adds unnecessary complexity to the importer to handle a format that is only happening if a user changes a file he is not supposed to change. This just does not make sense. No import export system handels files which are corrupted by the user. This will not be changed.
