### ISSUE TITLE
i18n: decimal separator

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1277]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 1.0.4

### Bug description
With the language set to German, the decimal separator is "," instead of "."
Using "," in a nutritional value, a receipt can not be saved when editing.
With a "." it works.

**Comment by MarcusWolschon** [comment]
https://www.npmjs.com/package/vue-numeric 
seems to do exactly what is needed here.

**Comment by vabene1111** [comment]
see comment in linked issue

**Comment by MarcusWolschon** [comment]
The linked issue is about "serving" and the solution was to make it an integer.
But nutritional values are definately not integer.
