### ISSUE TITLE
link food and instructions in recipes

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1284]
**Is your feature request related to a problem? Please describe.**
I manually create a recipe. I can add food and the amount. 
If I  write a fix value in the instruction text it is not scalable to the servings.

**Describe the solution you'd like**
Inside the instructions it would be great if I can link the food to the list of ingredients to the top. 

The problem I see if the food is split into different steps.

**Comment by smilerz** [comment]
This exists.  Documentation on how to use is here https://docs.tandoor.dev/features/templating/
