### ISSUE TITLE
edit title in meal plan

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1286]
**Is your feature request related to a problem? Please describe.**
In meal plan I can create a new entry. With search for a recipe the title will be automatically the name of the recipe. The string value of `Title` is grayed out. If I select the field there is nothing in it. Sometimes I just want to add something to the title

**Describe the solution you'd like**
After selecting the recipe in meal plan and select the title field I can rename the title.

**Comment by TWART016** [comment]
Correct the title is pre filled but if I select the field the cursor is not the first position. After typing the first letter the pre filled is gone.
![image](https://user-images.githubusercontent.com/29805669/149243834-fdc711bc-1e46-4e80-83df-51831362923e.png)


Sometimes I just want to add something in front of the title. In this case I have to type everything by hand.
![image](https://user-images.githubusercontent.com/29805669/149243937-27e2765d-46fc-46f0-b262-7b9ef59475cd.png)

**Comment by vabene1111** [comment]
so everything is working as you would need it to work ?

**Comment by TWART016** [comment]
it is only a small optimization request.

I select the recipe. In the title I can see the same text but when I click into title field and write something the text field is empty (of course in background I can see the text). The cursor navigation is not possible because there is no letter in this field.

I want that the text is standing in the title field and I can correct/add/remove something there and not have to completely write it.

**Comment by vabene1111** [comment]
now i understand what you mean. The problem is that i for example prefer it the way it currently is. I guess some user like it the one way and some the other but i am not sure if this is to minor to add a setting for this as it likely causes more confusion.
