### ISSUE TITLE
very first startup fails with docker-compose

### ISSUE THREAD

**Issue by oceanBT** [TandoorRecipes/recipes#1295]
### Version
Current Version: 1.0.4

### Bug description
I am using docker-compose with traefik and am currently testing and setting up tandoor. Thanks for the great work!

I have noticed the following bug: on the very first start of tandoor the UI via the browser does not reach. I then have to stop and start tandoor again, then it applies a lot of database script and it works as expected.

It is no big problem  (simple` docker-compose stop && docker-compose up -d`), but it could be quite annoying for new users. So maybe it should be documented or fixed :)

**Comment by vabene1111** [comment]
can you provide some logs of the first start ?

**Comment by oceanBT** [comment]
first `docker-compose up` 
      Creating network "tandoor-recipes_default" with the default driver
      Creating volume "tandoor-recipes_nginx_config" with default driver
      Creating volume "tandoor-recipes_staticfiles" with default driver
      Creating tandoor-recipes_db_recipes_1 ... done
      Creating tandoor-recipes_web_recipes_1 ... done
      Creating tandoor-recipes_nginx_recipes_1 ... done
      Attaching to tandoor-recipes_db_recipes_1, tandoor-recipes_web_recipes_1, tandoor-recipes_nginx_recipes_1
      db_recipes_1     | The files belonging to this database system will be owned by user "postgres".
      db_recipes_1     | This user must also own the server process.
      db_recipes_1     | 
      db_recipes_1     | The database cluster will be initialized with locale "en_US.utf8".
      db_recipes_1     | The default database encoding has accordingly been set to "UTF8".
      db_recipes_1     | The default text search configuration will be set to "english".
      db_recipes_1     | 
      db_recipes_1     | Data page checksums are disabled.
      db_recipes_1     | 
      db_recipes_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
      db_recipes_1     | creating subdirectories ... ok
      nginx_recipes_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
      nginx_recipes_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
      web_recipes_1    | Updating database
      db_recipes_1     | selecting default max_connections ... 100
      db_recipes_1     | selecting default shared_buffers ... 128MB
      nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
      nginx_recipes_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
      db_recipes_1     | selecting default timezone ... UTC
      db_recipes_1     | selecting dynamic shared memory implementation ... posix
      nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
      db_recipes_1     | creating configuration files ... ok
      nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
      db_recipes_1     | running bootstrap script ... ok
      nginx_recipes_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
      db_recipes_1     | performing post-bootstrap initialization ... sh: locale: not found
      db_recipes_1     | 2022-01-12 22:18:39.023 UTC [32] WARNING:  no usable system locales were found
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: using the "epoll" event method
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: nginx/1.21.5
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: OS: Linux 5.13.0-25-generic
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: start worker processes
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: start worker process 22
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: start worker process 23
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: start worker process 24
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: start worker process 25
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: start worker process 26
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: start worker process 27
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: start worker process 28
      nginx_recipes_1  | 2022/01/12 22:18:39 [notice] 1#1: start worker process 29
      web_recipes_1    | Traceback (most recent call last):
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
      web_recipes_1    |     self.connect()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
      web_recipes_1    |     self.connection = self.get_new_connection(conn_params)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
      web_recipes_1    |     connection = Database.connect(**conn_params)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
      web_recipes_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
      web_recipes_1    | psycopg2.OperationalError: could not connect to server: Connection refused
      web_recipes_1    | 	Is the server running on host "db_recipes" (172.23.0.2) and accepting
      web_recipes_1    | 	TCP/IP connections on port 5432?
      web_recipes_1    | 
      web_recipes_1    | 
      web_recipes_1    | The above exception was the direct cause of the following exception:
      web_recipes_1    | 
      web_recipes_1    | Traceback (most recent call last):
      web_recipes_1    |   File "/opt/recipes/manage.py", line 15, in <module>
      web_recipes_1    |     execute_from_command_line(sys.argv)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
      web_recipes_1    |     utility.execute()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
      web_recipes_1    |     django.setup()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
      web_recipes_1    |     apps.populate(settings.INSTALLED_APPS)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
      web_recipes_1    |     app_config.ready()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django_prometheus/apps.py", line 23, in ready
      web_recipes_1    |     ExportMigrations()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django_prometheus/migrations.py", line 52, in ExportMigrations
      web_recipes_1    |     executor = MigrationExecutor(connections[alias])
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
      web_recipes_1    |     self.loader = MigrationLoader(self.connection)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
      web_recipes_1    |     self.build_graph()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 220, in build_graph
      web_recipes_1    |     self.applied_migrations = recorder.applied_migrations()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
      web_recipes_1    |     if self.has_table():
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
      web_recipes_1    |     with self.connection.cursor() as cursor:
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
      web_recipes_1    |     return self._cursor()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
      web_recipes_1    |     self.ensure_connection()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
      web_recipes_1    |     self.connect()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
      web_recipes_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
      web_recipes_1    |     self.connect()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
      web_recipes_1    |     self.connection = self.get_new_connection(conn_params)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
      web_recipes_1    |     connection = Database.connect(**conn_params)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
      web_recipes_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
      web_recipes_1    | django.db.utils.OperationalError: could not connect to server: Connection refused
      web_recipes_1    | 	Is the server running on host "db_recipes" (172.23.0.2) and accepting
      web_recipes_1    | 	TCP/IP connections on port 5432?
      web_recipes_1    | 
      db_recipes_1     | ok
      db_recipes_1     | syncing data to disk ... ok
      db_recipes_1     | 
      db_recipes_1     | Success. You can now start the database server using:
      db_recipes_1     | 
      db_recipes_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
      db_recipes_1     | 
      db_recipes_1     | 
      db_recipes_1     | WARNING: enabling "trust" authentication for local connections
      db_recipes_1     | You can change this by editing pg_hba.conf or using the option -A, or
      db_recipes_1     | --auth-local and --auth-host, the next time you run initdb.
      db_recipes_1     | waiting for server to start....2022-01-12 22:18:39.637 UTC [38] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
      db_recipes_1     | 2022-01-12 22:18:39.649 UTC [39] LOG:  database system was shut down at 2022-01-12 22:18:39 UTC
      db_recipes_1     | 2022-01-12 22:18:39.652 UTC [38] LOG:  database system is ready to accept connections
      db_recipes_1     |  done
      db_recipes_1     | server started
      db_recipes_1     | CREATE DATABASE
      db_recipes_1     | 
      db_recipes_1     | 
      db_recipes_1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
      db_recipes_1     | 
      db_recipes_1     | waiting for server to shut down....2022-01-12 22:18:39.990 UTC [38] LOG:  received fast shutdown request
      db_recipes_1     | 2022-01-12 22:18:39.991 UTC [38] LOG:  aborting any active transactions
      db_recipes_1     | 2022-01-12 22:18:39.991 UTC [38] LOG:  background worker "logical replication launcher" (PID 45) exited with exit code 1
      db_recipes_1     | 2022-01-12 22:18:39.991 UTC [40] LOG:  shutting down
      db_recipes_1     | 2022-01-12 22:18:39.999 UTC [38] LOG:  database system is shut down
      db_recipes_1     |  done
      db_recipes_1     | server stopped
      db_recipes_1     | 
      db_recipes_1     | PostgreSQL init process complete; ready for start up.
      db_recipes_1     | 
      web_recipes_1    | Traceback (most recent call last):
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
      web_recipes_1    |     self.connect()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
      web_recipes_1    |     self.connection = self.get_new_connection(conn_params)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
      web_recipes_1    |     connection = Database.connect(**conn_params)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
      web_recipes_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
      web_recipes_1    | psycopg2.OperationalError: could not connect to server: Connection refused
      web_recipes_1    | 	Is the server running on host "db_recipes" (172.23.0.2) and accepting
      web_recipes_1    | 	TCP/IP connections on port 5432?
      web_recipes_1    | 
      web_recipes_1    | 
      web_recipes_1    | The above exception was the direct cause of the following exception:
      web_recipes_1    | 
      web_recipes_1    | Traceback (most recent call last):
      web_recipes_1    |   File "/opt/recipes/manage.py", line 15, in <module>
      web_recipes_1    |     execute_from_command_line(sys.argv)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
      web_recipes_1    |     utility.execute()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
      web_recipes_1    |     django.setup()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
      web_recipes_1    |     apps.populate(settings.INSTALLED_APPS)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
      web_recipes_1    |     app_config.ready()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django_prometheus/apps.py", line 23, in ready
      web_recipes_1    |     ExportMigrations()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django_prometheus/migrations.py", line 52, in ExportMigrations
      web_recipes_1    |     executor = MigrationExecutor(connections[alias])
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
      web_recipes_1    |     self.loader = MigrationLoader(self.connection)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
      web_recipes_1    |     self.build_graph()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 220, in build_graph
      web_recipes_1    |     self.applied_migrations = recorder.applied_migrations()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
      web_recipes_1    |     if self.has_table():
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
      web_recipes_1    |     with self.connection.cursor() as cursor:
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
      web_recipes_1    |     return self._cursor()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
      web_recipes_1    |     self.ensure_connection()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
      web_recipes_1    |     self.connect()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
      web_recipes_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
      web_recipes_1    |     self.connect()
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
      web_recipes_1    |     self.connection = self.get_new_connection(conn_params)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
      web_recipes_1    |     return func(*args, **kwargs)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
      web_recipes_1    |     connection = Database.connect(**conn_params)
      web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
      web_recipes_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
      web_recipes_1    | django.db.utils.OperationalError: could not connect to server: Connection refused
      web_recipes_1    | 	Is the server running on host "db_recipes" (172.23.0.2) and accepting
      web_recipes_1    | 	TCP/IP connections on port 5432?
      web_recipes_1    | 
      db_recipes_1     | 2022-01-12 22:18:40.098 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
      db_recipes_1     | 2022-01-12 22:18:40.098 UTC [1] LOG:  listening on IPv6 address "::", port 5432
      db_recipes_1     | 2022-01-12 22:18:40.100 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
      db_recipes_1     | 2022-01-12 22:18:40.112 UTC [52] LOG:  database system was shut down at 2022-01-12 22:18:39 UTC
      db_recipes_1     | 2022-01-12 22:18:40.115 UTC [1] LOG:  database system is ready to accept connections
      web_recipes_1    | 
      web_recipes_1    | 1019 static files copied to '/opt/recipes/staticfiles', 2878 post-processed.
      web_recipes_1    | Done
      web_recipes_1    | [2022-01-12 22:18:45 +0000] [1] [INFO] Starting gunicorn 20.1.0
      web_recipes_1    | [2022-01-12 22:18:45 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
      web_recipes_1    | [2022-01-12 22:18:45 +0000] [1] [INFO] Using worker: sync
      web_recipes_1    | [2022-01-12 22:18:45 +0000] [11] [INFO] Booting worker with pid: 11

my `docker-compose.yml`:

    version: "3"
    services:
      db_recipes:
        restart: always
        image: postgres:11-alpine
        volumes:
          - ./postgresql:/var/lib/postgresql/data
        env_file:
          - ./.env
    
      web_recipes:
        image: vabene1111/recipes
        restart: always
        env_file:
          - ./.env
        volumes:
          - staticfiles:/opt/recipes/staticfiles
          - nginx_config:/opt/recipes/nginx/conf.d
          - ./mediafiles:/opt/recipes/mediafiles
        depends_on:
          - db_recipes
    
      nginx_recipes:
        image: nginx:mainline-alpine
        restart: always
        ports:
          - 80:80
        env_file:
          - ./.env
        depends_on:
          - web_recipes
        volumes:
          - nginx_config:/etc/nginx/conf.d:ro
          - staticfiles:/static
          - ./mediafiles:/media
    
    volumes:
      nginx_config:
      staticfiles:


second `docker-compose up`:

    tarting tandoor-recipes_db_recipes_1 ... done
    Starting tandoor-recipes_web_recipes_1 ... done
    Starting tandoor-recipes_nginx_recipes_1 ... done
    Attaching to tandoor-recipes_db_recipes_1, tandoor-recipes_web_recipes_1, tandoor-recipes_nginx_recipes_1
    db_recipes_1     | 
    db_recipes_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
    db_recipes_1     | 
    db_recipes_1     | 2022-01-12 22:21:52.458 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
    db_recipes_1     | 2022-01-12 22:21:52.458 UTC [1] LOG:  listening on IPv6 address "::", port 5432
    nginx_recipes_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
    nginx_recipes_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
    db_recipes_1     | 2022-01-12 22:21:52.460 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
    nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
    db_recipes_1     | 2022-01-12 22:21:52.474 UTC [21] LOG:  database system was shut down at 2022-01-12 22:21:49 UTC
    db_recipes_1     | 2022-01-12 22:21:52.477 UTC [1] LOG:  database system is ready to accept connections
    nginx_recipes_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
    nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
    web_recipes_1    | Updating database
    nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
    nginx_recipes_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: using the "epoll" event method
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: nginx/1.21.5
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: OS: Linux 5.13.0-25-generic
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: start worker processes
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: start worker process 23
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: start worker process 24
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: start worker process 25
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: start worker process 26
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: start worker process 27
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: start worker process 28
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: start worker process 29
    nginx_recipes_1  | 2022/01/12 22:21:53 [notice] 1#1: start worker process 30
    web_recipes_1    | Operations to perform:
    web_recipes_1    |   Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
    web_recipes_1    | Running migrations:
    web_recipes_1    |   Applying contenttypes.0001_initial... OK
    web_recipes_1    |   Applying auth.0001_initial... OK
    web_recipes_1    |   Applying account.0001_initial... OK
    web_recipes_1    |   Applying account.0002_email_max_length... OK
    web_recipes_1    |   Applying admin.0001_initial... OK
    web_recipes_1    |   Applying admin.0002_logentry_remove_auto_add... OK
    web_recipes_1    |   Applying admin.0003_logentry_add_action_flag_choices... OK
    ....

**Comment by smilerz** [comment]
tandoor couldn't access the DB - it seems to happen occassionally, not sure why though

**Comment by vabene1111** [comment]
i think there is an open issue (and maybe even PR) discussing how to best solve this so we can close this one.

**Comment by vabene1111** [comment]
but thank you for reproting
