### ISSUE TITLE
Empty Keyword is created when importing from nextcloud recipes 

### ISSUE THREAD

**Issue by oceanBT** [TandoorRecipes/recipes#1296]
### Version
Current Version: 1.0.4

### Bug description
I have imported recipes from nextcloud recipes app. All Recipes have got an empty keyword. When i now try to edit a recipe, i got a 400 response until I remove the empty tag.

**Comment by vabene1111** [comment]
interesting, this means that the importer could not create the import tag for some reason. Can you run another import and send me the logs while its running ? Maybe with just 2 or 3 recipes so you dont clutter your instance (please disable duplication prevention)

**Comment by vabene1111** [comment]
cant reproduce and no response so closing this for now.
