### ISSUE TITLE
Improve Issue Forms

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#1304]
@MaxJa4 has already improvde the issue template but we can also migrate it to the new github issue forms system https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

The old forms basically need to be rewritten in the new templating system

**Comment by MaxJa4** [comment]
That looks like a great and long needed feature of GH itself 👍🏻
I'm tempted to take a look.

**Comment by smilerz** [comment]
as a future idea a template for "can't install tandoor" that links to various things that need checked first: nginx config, debug logs, headers, etc, etc, etc would be good too

**Comment by MaxJa4** [comment]
Like a little FAQ "Before you report, see these FAQs". Sounds good

**Comment by MaxJa4** [comment]
No worries.

Maybe a label like 'FAQ' would be good to label an issue for evaluation in that regard. That way, you don't need to worry about it right away @vabene1111

**Comment by MaxJa4** [comment]
When creating a new issue inside the GitHub App (iOS), there is no issue template. That's probably because the template structure is still in beta and the app doesn't support it yet. Maybe enabling the old ones again helps (if GH automatically prefers the new format but can fall back to the old one; will test this)

**Comment by MaxJa4** [comment]
Update: Having both enabled causes either conflicts (when they have the same name) and the old format overwrites the new one by default.
So the only two options I see are either reenabling the old templates and adding something like a "(old)" behind their names or just leave the GitHub-App without templates for now. @vabene1111

**Comment by MaxJa4** [comment]
One downside of having checkboxes in a template (like in the feature request form): GH thinks there are tasks, so it says "1/3 tasks" in the issue overview... having a simple input field for writing Yes/No/Partly/... would solve that issue or it can also be removed entirely...

**Comment by vabene1111** [comment]
I think I am fine with the app not working. Regarding the task lists I think that is OK to, we will see if it annoys to much we can still change it.

Thanks for all the testing and writing things up, really like the new templates.
