### ISSUE TITLE
How to configure Apache?

### ISSUE THREAD

**Issue by beedaddy** [TandoorRecipes/recipes#1312]
I own a VPS with apache2 already running some sites. I was able to setup tandor recipes and the systemd service is up and running. But could you please give more infos about setting up Apache? As mentioned, the VPS already runs apache so nginx is no option for me. Perhaps someone could show an configuration example? Thanks a lot!

**Comment by smilerz** [comment]
I'm not aware of any example configs - maybe [this ](https://docs.djangoproject.com/en/4.0/howto/deployment/wsgi/modwsgi/)can assist.  If you get it working can you please post a configuration here so that it can be included in an FAQ?

**Comment by smilerz** [comment]
Someone on the [community Discord](https://github.com/TandoorRecipes/recipes#get-in-touch) might be able to assist as well.

**Comment by vabene1111** [comment]
i have zero experience with apache but i know some people have tandoor setup using it. Feel free to ask on discord but since i cannot provide any help i will close this issue for now.

**Comment by vabene1111** [comment]
i have zero experience with apache but i know some people have tandoor setup using it. Feel free to ask on discord but since i cannot provide any help i will close this issue for now.

**Comment by MaxJa4** [comment]
@beedaddy Someone posted their somewhat working config here: #1292
Be sure to add the following headers too:
```apache
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set Host %{REMOTE_HOST}s
RequestHeader set X-Forwarded-Host %{REMOTE_HOST}s
```

I don't have any feedback from that user yet if that fixed the issue, but it should surely get you going.

**Comment by beedaddy** [comment]
@MaxJa4 Thanks for the hint.
My current config (which seems to work, but I'll do some more tests is:
```
<IfModule mod_ssl.c>

<VirtualHost *:80>
        ServerName recipes.mydomain.de

        Redirect permanent / https://recipes.mydomain.de/
</VirtualHost>

<VirtualHost *:443>
        ServerName recipes.mydomain.de

        SSLEngine on

        RequestHeader set X-Forwarded-Proto "https"
        #RequestHeader set Host %{REMOTE_HOST}s
        RequestHeader set X-Forwarded-Host %{REMOTE_HOST}s

        Alias /staticfiles /var/www/recipes/staticfiles
        Alias /mediafiles /var/www/recipes/mediafiles

        ProxyPreserveHost  On
        ProxyRequests Off
        ProxyPass  / unix:/var/www/recipes/recipes.sock|http://127.0.0.1/
        ProxyPassReverse / unix:/var/www/recipes/recipes.sock|http://127.0.0.1/

        SSLCertificateFile /etc/letsencrypt/live/mydomain.de/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.de/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```
`RequestHeader set Host %{REMOTE_HOST}s` is commented out, though, because it causes an error and the page cannot be displayed.

**Comment by MaxJa4** [comment]
Thanks for letting us know. If it keeps working for you without any issues, we could add it as an example to the docs if you don't mind.

**Comment by beedaddy** [comment]
It would be nice if someone could confirm the configuration (just to be sure). But from my point of view you are of course welcome to use it. Anyway, here it works.

**Comment by beedaddy** [comment]
Just for the record: Since I was having still problems with Apache, I revised the config file again. This is my current working Apache configuration:
```
<IfModule mod_ssl.c>

<VirtualHost *:80>
        ServerAdmin webmaster@mydomain.de
        ServerName recipes.mydomain.de

        Redirect permanent / https://recipes.mydomain.de/
</VirtualHost>


<VirtualHost *:443>
        ServerAdmin webmaster@mydomain.de
        ServerName recipes.mydomain.de

        SSLEngine on

        RequestHeader set X-Forwarded-Proto "https"

        ProxyPass /static/ !
        ProxyPass /media/ !

        Alias /static/ /var/www/recipes/staticfiles/
        Alias /media/ /var/www/recipes/mediafiles/
        <Directory /var/www/recipes/mediafiles>
             Require all granted
        </Directory>
        <Directory /var/www/recipes/staticfiles>
             Require all granted
        </Directory>

        ProxyPreserveHost  On
        ProxyRequests Off
        ProxyPass / http://localhost:8088/

        SSLCertificateFile /etc/letsencrypt/live/mydomain.de/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.de/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf

        ErrorLog ${APACHE_LOG_DIR}/recipes_error.log
        CustomLog ${APACHE_LOG_DIR}/recipes_access.log combined
</VirtualHost>
</IfModule>
```

And this is how I start the tandoor recipe daemon (/etc/systemd/system/gunicorn_recipe):
```
[Unit]
Description=gunicorn daemon for recipes
After=network.target

[Service]
Type=simple
Restart=always
RestartSec=3
User=recipes
Group=www-data
WorkingDirectory=/var/www/recipes
EnvironmentFile=/var/www/recipes/.env
ExecStart=/var/www/recipes/bin/gunicorn --error-logfile /tmp/gunicorn_err.log  --capture-output --bind 127.0.0.1:8088 recipes.wsgi:application

[Install]
WantedBy=multi-user.target
```

**Comment by solaris7590** [comment]
I changed today to Apache Webserver with ReverseProxy and SSL-cert from letsencrypt. The Apache-conifg from obove didn't worked here. (I think the staticfiles and mediafilespath is the problem). But I found a config that worked for me.
I just want to present my solution here, maybe it helps one or the other:

```
<IfModule mod_ssl.c>

<VirtualHost *:80>
        ServerAdmin webmaster@mydomain.de
        ServerName mydomain.de

        Redirect permanent / https://mydomain.de/
</VirtualHost>


<VirtualHost *:443>
        ServerAdmin webmaster@mydomain.de
        ServerName mydomain.de

        SSLEngine on

        RequestHeader set X-Forwarded-Proto "https"
	Header always set Access-Control-Allow-Origin "*"

        ProxyPreserveHost  On
        ProxyRequests Off
        ProxyPass / http://localhost:85/
        ProxyPassReverse / http://localhost:85/

        SSLCertificateFile /etc/letsencrypt/live/mydomain.de/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.de/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf

        ErrorLog ${APACHE_LOG_DIR}/recipes_error.log
        CustomLog ${APACHE_LOG_DIR}/recipes_access.log combined
</VirtualHost>
</IfModule>
```
Port 85 is the port, where my tandoor is running.
