### ISSUE TITLE
Admin Username and Password

### ISSUE THREAD

**Issue by gummipunkt** [TandoorRecipes/recipes#1315]
Hi, 
in the docs no where is described the URL to the admin interface. Ok, wasn't hard to figure out its /admin

Much harder is to find out how the login credentials are. I think the password is the generated one which I'd to put into the .env file during the docker-compose setup. Is it? If it is right, what is the username?

admin, superuser, django superuser, administrator didn't work. All of this information should be added into the docs.

Thank you.

**Comment by smilerz** [comment]
there is a navigation in the top right context menu - the initial user (or any other user you give admin permissions to) has access to the interface.
