### ISSUE TITLE
Advanced search doesn't work for ingredient parent nodes

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#1320]
### Tandoor Version

1.0.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

I moved some ingredients of existing recipes into a hierarchy of ingredients:
- dairy
  - cheese
    - Gouda
    - creme cheese
  
In advanced search, recipes still appear, when I select "creme cheese" from the dropdown list, but nothing shows when I select "cheese" instead.

With "creme cheese", I find one recipe (which I think is correct), but in the list it looks like its associated with 3 recipes: "creme cheese (3)".

By the way, the main search field also delivers 0 recipes, when I search for either "cream cheese", "cheese" or "dairy".

**Comment by smilerz** [comment]
You’ve described the expected behavior for 1.04 (children not included in results for “OR” searches).  The next release changes this behavior and will improve the quality of counts (though probably not perfect)
