### ISSUE TITLE
Change hostname from web_recipes

### ISSUE THREAD

**Issue by mholti** [TandoorRecipes/recipes#1322]
### Issue

Hi,
the hostname "web_recipes" doen't fit into my naming-convention.
But when i change it, nginx won't work.
Is there a way (e.g. within .env) to change it?

### Tandoor Version

1.0.4

### OS Version

docker / Synology DSM

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

**Comment by smilerz** [comment]
it can be changed to anything - the references to web_recipes in the nginx configuration will need to be changed accordingly.

**Comment by mholti** [comment]
Hi,
sorry, my question wasn't clear enough...
There is a /etc/nginx/conf.d/Recipes.conf created / copied automarically.
I wanted to know wether there is a way to change this file-content to the choosen hostname via environment or so..

**Comment by smilerz** [comment]
> There is a /etc/nginx/conf.d/Recipes.conf created / copied automatically. I wanted to know wether there is a way to change this file-content to the choosen hostname via environment or so..

No, the built in nginx conf doesn't seem to work with Synology so will need to be created manually.
The guide on [this page](https://docs.tandoor.dev/install/synology/) has command line instructions - the linked word/pdf document on the same page have instructions that utilize the Synology UI.

**Comment by mholti** [comment]
Thanks for your very fast answer.
Please forget about Synology.
I did my own docker-stuff on my machine, giving the containers own ips (if needed) and so on.
The only thing i want to solve with my question is, that a can forget about editing nginx-conig when there should be the need to restore my docker-containers and volumes manually.
All my other containers sumpy need a (huge) docker-compose.yml and .env, no need to edit files manually in case of desater.

**Comment by smilerz** [comment]
In that case you’ll need to copy Recipe.conf and provide a mount to the  modified file in the docker compose

**Comment by mholti** [comment]
Hi,
found another solution: I just added an alias "web_recipes" to the networking-section of my docker-compose.yml for that container.
My container-name is now how i want it to be and there is no need to change Recipe.conf

Thanks again, i'll close this...
