### ISSUE TITLE
Enable scrolling when dragging ingredients from one step to another

### ISSUE THREAD

**Issue by cornydesouza** [TandoorRecipes/recipes#1324]
### Is your feature request related to a problem? Please describe.

I can drag an ingredient from one step to another, however if the target step is not visible in the viewable portion of the browser page then the page does not scroll to make the target step visible.

### Describe the solution you'd like

When dragging an ingredient from one step to another step that is not currently visible the page should scroll in the appropriate direction when I move off the top or bottom of the viewable portion of the page.

An alternative solution would be the ability to duplicate a step.

### Describe alternatives you've considered

I have tried in both Firefox and Chrome.

### Additional context

After importing a recipe everything ends up in one step. I would like to split this step into multiple steps each with its own ingredients and I do not want to have to reenter the ingredients.

### Contribute

- [ ] Yes
- [X] Partly
- [ ] No

**Comment by vabene1111** [comment]
This used to work 🤔 but I also want to add an option to the context menu so you can move ingredients to other steps without scrolling at all.

I will take a look at this when working on the editor
