### ISSUE TITLE
Import recipies from 'Sueddeutsche Zeitung'

### ISSUE THREAD

**Issue by krafeiner** [TandoorRecipes/recipes#1335]
### Describe the solution you'd like

Importing of cooking recipes works well for the following German sites:

- https://eatsmarter.de/rezepte
- http://www.chefkoch.de/

However, there are nice recipes on the 'Sueddeutsche Zeitung' in the following area:

- https://sz-magazin.sueddeutsche.de/tag/das-rezept

It would be nice if importing recipes from this site would be supported, too.

### Contribute

- [ ] Yes
- [X] Partly
- [ ] No

**Comment by smilerz** [comment]
Tandoor uses a third party library for recipe importing.  Please open a feature request on https://github.com/hhursev/recipe-scrapers.  It appears that the site has the necessary data, so should be added fairly quickly.
