### ISSUE TITLE
Share whole meal plan with someone

### ISSUE THREAD

**Issue by thomasthe1st** [TandoorRecipes/recipes#1338]
### Is your feature request related to a problem? Please describe.

Currently it seems like I have to share each single entry in the meal plan with a person.
Have not found another way to make the plan available to someone else.

### Describe the solution you'd like

Share the whole plan with another person so I do not need to share each single entry and the other person still sees all the entries.

### Additional context

Might be able to help on this also I might need to change a lot to implement this.

### Contribute

- [ ] Yes
- [X] Partly
- [ ] No

**Comment by vabene1111** [comment]
there is a setting on the settings page, its the same as the shopping setting, there you can set the users to share a new entry with by default. At some point we will add a group sysstem and also probabaly split the settings for shopping and meal planning

**Comment by smilerz** [comment]
> there is a setting on the settings page, its the same as the shopping setting, there you can set the users to share a new entry with by default. At some point we will add a group sysstem and also probabaly split the settings for shopping and meal planning

shopping and meal planning are split with shoppingV2

**Comment by vabene1111** [comment]
ah awesome, thanks
