### ISSUE TITLE
Import Bookmarklet not doing anything

### ISSUE THREAD

**Issue by Stooovie** [TandoorRecipes/recipes#1339]
Hi, I have dragged the "Bookmark me!" bookmarklet for importing recipes to my Favorites. Upon pressing it on any recipe page, it does absolutely nothing. Tried in Safari on Mac and iPhone, Edge on Mac, Edge on Windows, same behavior - absolutely nothing. Any ideas? I don't see it in the documentation.

This is the content of the bookmarklet as present in Edge: 
`javascript:(function(){if(window.bookmarkletTandoor!==undefined){bookmarkletTandoor();}else{localStorage.setItem('importURL','http://192.168.0.181:9928/api/bookmarklet-import/');localStorage.setItem('redirectURL','http://192.168.0.181:9928/data/import/url');localStorage.setItem('token','xxxxx');document.body.appendChild(document.createElement('script')).src='http://192.168.0.181:9928/static/js/bookmarklet.a43f756e9acd.js?r=%27+Math.floor(Math.random()*999999999);}})();`

I run Tandoor 1.0.4 as a Docker container in Home Assistant HAOS system. Tandoor seems to work fine otherwise. Thanks.

**Comment by smilerz** [comment]
What is the output in your browser console after you click the bookmark on a recipe site?

**Comment by Stooovie** [comment]
`Mixed Content: The page at 'https://www.toprecepty.cz/recept/55975-pecena-kureci-stehna-a-bucek-na-pive-medu-a-barevnem-pepri-2v1/' was loaded over HTTPS, but requested an insecure script 'http://192.168.0.181:9928/static/js/bookmarklet.a43f756e9acd.js?r=274870637'. This request has been blocked; the content must be served over HTTPS.`

Ah, I see the issue now. Is there a way to fix this other than running HTTPS on the Home Assistant Pi? I really don't want to deal with SSL and stuff (I'm not really an IT person). Thanks!

**Comment by smilerz** [comment]
Unfortunately, that is a policy set on the source website (www.toprecepty.cz).  Most websites run with that content policy, which will make the bookmarklet mostly unusable. 

You will need to use the URL import in most cases or Source import for the few sites that block scraping.

**Comment by Stooovie** [comment]
I think this should be in the documentation (maybe I just haven't found it but I don't think so). Thanks!

**Comment by Stooovie** [comment]
I have enabled SSL on my system and I am able to use the bookmarklet in Edge but still not in Safari. Is there a way to enable it somehow?

**Comment by smilerz** [comment]
> EDIT: fixed it myself by editing http:// URLs to https:// in the page source... Brutal but working :) Still only working on desktop Safari only. Cannot get it to work on an iPhone.

If you changed the SSL after installing the bookmarklet you would have had to delete the bookmarklet and save it again.
The javascript bookmarklets don't seem to work on the mobile version of safari - they work fine with Chrome or Edge though.

**Comment by Stooovie** [comment]
I did it again, for some reason it was still http... Thanks.

**Comment by DanielHabenicht** [comment]
Is anybody still successfully using the Bookmark? 

I get the following error:
```
Access to script at 'https://recipes.mydomain.de/static/js/bookmarklet_v3.js?r=868605081' from origin 'https://www.chefkoch.de' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

With the following NGINX config it works: 
```
# serve /static/ files
  location /static/ {
    # for OPTIONS return these headers and HTTP 200 status
    if ($request_method = OPTIONS) {
        add_header Access-Control-Allow-Origin $http_origin;

        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Private-Network' 'true';
        add_header Content-Type text/plain;
        add_header Content-Length 0;
        return 204;
    }


    alias /static/;
    add_header Access-Control-Allow-Origin $http_origin;
    add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';

  }

  # pass requests for dynamic content to gunicorn
  location / {
    proxy_set_header Host $http_host;
    proxy_pass http://web_recipes:8080;
    add_header 'Access-Control-Allow-Private-Network' 'true';

    error_page 502 /errors/http502.html;
  }
```

**Comment by smilerz** [comment]
> Is anybody still successfully using the Bookmark? (with the default configuration from the documentation?) 
> 
> 
> 
> I get the following error:
> 
> ```
> 
> Access to script at 'https://recipes.mydomain.de/static/js/bookmarklet_v3.js?r=868605081' from origin 'https://www.chefkoch.de' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> ```
> 
> 
> 
> With the following NGINX config it works: 
> 
> ```
> 
> # serve /static/ files
> 
>   location /static/ {
> 
>     # for OPTIONS return these headers and HTTP 200 status
> 
>     if ($request_method = OPTIONS) {
> 
>         add_header Access-Control-Allow-Origin $http_origin;
> 
> 
> 
>         add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
> 
>         add_header 'Access-Control-Allow-Credentials' 'true';
> 
>         add_header 'Access-Control-Allow-Private-Network' 'true';
> 
>         add_header Content-Type text/plain;
> 
>         add_header Content-Length 0;
> 
>         return 204;
> 
>     }
> 
> 
> 
> 
> 
>     alias /static/;
> 
>     add_header Access-Control-Allow-Origin $http_origin;
> 
>     add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
> 
> 
> 
>   }
> 
> 
> 
>   # pass requests for dynamic content to gunicorn
> 
>   location / {
> 
>     proxy_set_header Host $http_host;
> 
>     proxy_pass http://web_recipes:8080;
> 
>     add_header 'Access-Control-Allow-Private-Network' 'true';
> 
> 
> 
>     error_page 502 /errors/http502.html;
> 
>   }
> 
> ```

I use the bookmarklet almost daily with the default config.
