### ISSUE TITLE
Incorrect counting of recipes per units

### ISSUE THREAD

**Issue by CraftingDub** [TandoorRecipes/recipes#1341]
### Tandoor Version

Hosted by Tandoor

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

Hosted by Tandoor

### Bug description

I only have one recipe in the database:
![image](https://user-images.githubusercontent.com/8700202/149681558-bb4128c5-0b5a-4b07-bd4b-0436939ae67e.png)

On the ingredients I use the unit "g" twice:
![image](https://user-images.githubusercontent.com/8700202/149681601-81e94ab1-d3b0-47c0-9768-0df3ac0dffe9.png)

On the unit overview I see that "g" occurs on two recipes:
![image](https://user-images.githubusercontent.com/8700202/149681637-7b4790b9-3159-459b-8e0a-71325c947102.png)

**Comment by smilerz** [comment]
this is mostly fixed in the next version - there will remain some corner cases where this remains true, however.
