### ISSUE TITLE
Estimated Costings Calculations

### ISSUE THREAD

**Issue by frg** [TandoorRecipes/recipes#1342]
### Describe the solution you'd like

For budget-conscious users and small businesses, it would be useful to be able to get an estimate on how much a recipe would cost and even a shopping list. Now I would like to stress that I do not expect accurate values, and simply an estimate. The flow would go like this.

A page would give users the ability to associate a unit, and an ingredient and assign a price per unit. Then in other pages where there is a reference to a unit and an ingredient (like the recipe page), if a record is found for a price per unit for the particular ingredient and unit combination it would automatically calculate the estimated cost.

### Additional context

![image](https://user-images.githubusercontent.com/1245426/149741245-dfd0b7ee-9226-4ba7-9d63-726e4aefcda9.png)

### Contribute

- [X] Yes
- [ ] Partly
- [ ] No

**Comment by vabene1111** [comment]
it is planned to add more properties to foods, together with automatic unit conversion this will definitely be possible and is also definitely planned

**Comment by frg** [comment]
Oh, that's great news! You wouldn't have an ETA for that, would you? Or priority within the roadmap?

**Comment by vabene1111** [comment]
i cannot really estimate this as unit conversion and some other things need to work first but once that is done, this should not be very hard to do. It would basically use the same logic as the nutrition rework which is a thing i really want to start working on.

**Comment by frg** [comment]
Ah okay, thanks for the info!

**Comment by taubmann** [comment]
Another possible use case could be some sort of CO2 Budget Calculator like this (standalone) example:
https://interaktiv.tagesspiegel.de/lab/co2-bilanz-von-essen-der-klimarechner-fuer-deine-kueche

**Comment by sebweb3r** [comment]
when the functions are implemented, you should be able to disable them via the user settings.
otherwise the ui is pretty crowded

**Comment by wligtenberg** [comment]
I am interested in working on this. If I am not mistaken the conversion functions have been implemented.
Are you accepting PRs for this? If so, I would really appreciate some pointers on where to start and if there are already some thoughts on how it should be implemented.

**Comment by vabene1111** [comment]
to be honest this should already be possible, I just missed this issue.

You can add a property called "Price" and add that to your foods. Than recipes will calculate automatically. Closing this, if I missed anything let me know.
