### ISSUE TITLE
Wrong display of the version number

### ISSUE THREAD

**Issue by sebastian0511** [TandoorRecipes/recipes#1345]
### Tandoor Version

0.0.0

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

I installed tandoor manual like its discribt in the installation guide with the actual master branch.
Everything looks fine but the version number is not displayed correct.
It shows me only 0.0.0.
![Bildschirmfoto vom 2022-01-17 12-53-38](https://user-images.githubusercontent.com/97887831/149765132-8dbc762f-f741-4097-b664-b2b474eb6c05.png)

**Comment by smilerz** [comment]
duplicate #156
