### ISSUE TITLE
nginx example in documentation not correct/misleading

### ISSUE THREAD

**Issue by beedaddy** [TandoorRecipes/recipes#1355]
The [documentation](https://docs.tandoor.dev/install/manual/#nginx) says for manual installation:
```
    location /mediafiles {
        alias /var/www/recipes/mediafiles;
    }
```
but it should rather be
```
    location /media {
        alias /var/www/recipes/mediafiles;
    }
```
I'm not sure if the same is true for `location /staticfiles`. Can you please check the above mentioned nginx example?

**Comment by vabene1111** [comment]
fixed
