### ISSUE TITLE
ingredient list does not show step names anymore

### ISSUE THREAD

**Issue by beedaddy** [TandoorRecipes/recipes#1356]
### Tandoor Version

beta-branch

### Setup

Manual Setup

### Reverse Proxy

Apache2

### Bug description

I'm quite sure that version 1.0.4 showed the step names in the ingredient list. Now, after upgrading to beta branch, the step names are gone in that list.

**Comment by vabene1111** [comment]
thanks, fixed

**Comment by beedaddy** [comment]
Seems not to be fixed here.

**Comment by vabene1111** [comment]
in my dev environment its definitely working, can you reload the page without cache (shift + f5) to see if that makes a difference ?

**Comment by beedaddy** [comment]
Hmm, interesting. shift + f5 didn't make a difference. I've attached a small video to show you what I mean. The step names should appear in the summary ingredient list, right?
https://user-images.githubusercontent.com/3264939/149977635-9898ac96-e84e-439b-b243-c4fc4b97f043.mp4

**Comment by vabene1111** [comment]
they should and they are showing for me, thats very interesting 🤔
![2022-01-18_13-57-48-chrome](https://user-images.githubusercontent.com/6819595/149991511-c345cbf1-06e2-49cd-aab3-7865687c694f.png)

sure you are running the latest beta image ?

EDIT: the stupid beta image build is still running https://github.com/TandoorRecipes/recipes/actions/runs/1713450220 wait for the notifcation on discord, then its done.

**Comment by beedaddy** [comment]
I don't use the docker image but manual installation. The update procedure is as described [here](https://docs.tandoor.dev/install/manual/#updating).

**Comment by smilerz** [comment]
> I don't use the docker image but manual installation. The update procedure is as described [here](https://docs.tandoor.dev/install/manual/#updating).

the new code is available to update as soon as the image starts building - so you should be good to upgrade

**Comment by beedaddy** [comment]
I did another update today and can confirm that the step names are back again.

**Comment by vabene1111** [comment]
very intertesting, might have been a small timing issue between releases
