### ISSUE TITLE
DRF Permission Classes Update

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#136]
Wait for Update on https://github.com/encode/django-rest-framework/pull/7155 and update DRF in order to avoid un-intuitive and potentially insecure behavior of permission class operators

**Comment by smilerz** [comment]
the PR this is linked to is closed without merging - what is the underlying issue?

**Comment by vabene1111** [comment]
to be totally honest i am not sure, I think it was an issue that if you were not paying close enough attention to how you design you permission classes it would sometimes not execute certain permission checks. I dont really think DRF will fix it so we probably best stick to writing proper tests for the permissions of each API endpoint.
