### ISSUE TITLE
Unable to add/link supermarket categories to supermarket

### ISSUE THREAD

**Issue by beedaddy** [TandoorRecipes/recipes#1360]
### Tandoor Version

beta-branch

### Setup

Manual Setup

### Reverse Proxy

Apache2

### Bug description

I've added some supermarket categories and some supermarkets. But I'm unable to add the categories to the markets. When I edit a supermarket, I can select categories and save. But when I edit the market again, the categorie filed is empty again. Furthermore, the first category field is shown very small and without text (see screenshot).
![Bildschirmfoto_von_2022-01-17_19-55-01](https://user-images.githubusercontent.com/3264939/149962437-fa0eec2b-9c39-4d1c-8e2b-82f7f0cdc7fe.png)

**Comment by smilerz** [comment]
fixed with #1353

**Comment by beedaddy** [comment]
I doubt myself, but it doesn't work here (I've tried other browsers as well). I double-checked that the fix has been git-pulled.

**Comment by beedaddy** [comment]
After deleting (moving) staticfiles and doing `bin/python3.9 manage.py collectstatic` again, it works now. Sorry for that. I think the documentation on manual updates is not detailed enough for me. :)

**Comment by smilerz** [comment]
Did that fix the step display issues too?

**Comment by beedaddy** [comment]
step names have been displayed again after another git pull (und update procedure) earlier today. I think I will ask in discussions if someone can give more information about the manual update process.
