### ISSUE TITLE
allow selecting a cook book for an import

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1361]
### Describe the solution you'd like

For use when importing a zip file with many receipts.
Allow selecting a cookbook in the import screen to add all of them to.
For a single file to be imported likely contains many receipts that are related.

### Describe alternatives you've considered

Using the "show receipts" links provided after the import to manually add each one of the to the cook book.

### Contribute

- [ ] Yes
- [X] Partly (not Javascript or  HTML)
- [ ] No

**Comment by vabene1111** [comment]
i think this is solved by something smilerz has planned. Imports are automatically tagged and using batch editing or smilerz saved searches/attribute based cook books feature it should be easy to dump a complete import into a book.
