### ISSUE TITLE
"show receipts" after import is empty if there is a stored search query

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1364]
### Tandoor Version

1.0.4.1

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

After importing receipts, there is a link "show receipts"
If there is still a stored phrase to search for, the opened search window will contain that phrase in addition to the tag to search for.
Only the imported receipts that contain that (unrelated) phrase will be shown until
the user manually empties the search text field.

**Comment by smilerz** [comment]
search parameters including: search query, keywords, foods, etc are cached by design

**Comment by MarcusWolschon** [comment]
How does it being "by design" makes it not a bug that someone at some time could improve?
Did you mean to mark this bug as rejected because in your eyes it can't ever be fixed?

If a keyword can be added and all keywords of the last search be removed, can the search query not be set (to en empty string) at the same time?

**Comment by smilerz** [comment]
it's working the way that it is intended to work.  There is no bug.
