### ISSUE TITLE
setting for default step header type

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#1375]
### Describe the solution you'd like

Currently, the ingredient summary shows the step title when there is more than one step - it should also skip titles that don't have any ingredients.

### Additional context

create settings to disable headings all, none, without ingredients plus ability to force on/off for specific steps.

### Contribute

- [ ] Yes
- [ ] Partly
- [ ] No

**Comment by vabene1111** [comment]
i am not sure actually if this is better 🤔 if you use the ingredients list as a guideline for cooking having step titles even without ingredients might be a good thing. 

You can always disabled step titles as a per step setting. I know we both use tandoor very differently so maybe some additional input from the community would be nice.

**Comment by smilerz** [comment]
Didn't know they could be hidden, maybe just a configuration for default behavior would serve my needs.

**Comment by vabene1111** [comment]
currently the default is showing as header, its just one place in the default step configuration we could easily add a setting.

**Comment by igorsantos07** [comment]
A tooltip on the :eye: button explaining what it does would go a loooong way! I thought it would hide the step title on the recipe body, not in the summary.

Does that button do something else other than hiding the title from the overview? If not, I can try to submit a tiny PR with that :)

**Comment by smilerz** [comment]
> A tooltip on the 👁️ button explaining what it does would go a loooong way! I thought it would hide the step title on the recipe body, not in the summary.
> 
> Does that button do something else other than hiding the title from the overview? If not, I can try to submit a tiny PR with that :)

the front-end is being rewritten - nothing about the current interface will be changed and no PRs are being accepted.

**Comment by igorsantos07** [comment]
Oh well, bad news and good news :tada:
I just hope that closed-but-not-solved issues don't go forgotten on the rewrite :pray: 

Best wishes and a great 2025 for everyone!

**Comment by stleusc** [comment]
It seems like that the old way of hiding step 'title' does no longer exist after rewrite.
<img width="115" height="84" alt="Image" src="https://github.com/user-attachments/assets/939e4149-2b71-4858-ba8d-365aa2bdf663" /> 
Should this maybe be reopened?

**Comment by smilerz** [comment]
no, open a new issue
