### ISSUE TITLE
Images path incorrect

### ISSUE THREAD

**Issue by ArMaTeC** [TandoorRecipes/recipes#1383]
Hi im new to the system but whenever i add images to my recipes they upload to the correct path but when viewing the item the image url is messed up including my root dir path.

http://192.168.1.55:8002/var/www/recipes/mediafiles/recipes/f574d5fe-3016-48e6-af19-f2d72ce08c31_2.jpeg

Any one know what could cause this?

The install type is manual and everything is working except this issue

thanks

**Comment by smilerz** [comment]
@ArMaTeC based on that path it looks like you set the media_url ENV variable to a physical path

**Comment by ArMaTeC** [comment]
Thank you I solved it by commenting out the 2 paths in the .env file and now the images are showing.

Thank you for your help now time to create an import routine
