### ISSUE TITLE
MealPlan: Add 'show recipe' to 3-dot-menu

### ISSUE THREAD

**Issue by Athan1** [TandoorRecipes/recipes#1387]
### Is your feature request related to a problem? Please describe.

Sometime I like to have a look ats the recipe, when reviewing the mealplan.
It would be fine to have a dirct link.

### Describe the solution you'd like

Add an menu button "show recipe" to the context menu of the mealplaner

### Contribute

- [ ] Yes
- [ ] Partly
- [ ] No

**Comment by vabene1111** [comment]
this is already implemented in the next release, thanks for the report. It should actually also show as a card but that is currently broken see #1093
