### ISSUE TITLE
Rewe recipes 

### ISSUE THREAD

**Issue by Dschonnie** [TandoorRecipes/recipes#1394]
### Is your feature request related to a problem? Please describe.

Rewe resipes cannot be imported 

### Describe the solution you'd like

Here a link to test it

https://www.rewe.de/rezepte/avocado-basilikum-pasta/

### Contribute

- [ ] Yes
- [ ] Partly
- [ ] No

**Comment by vabene1111** [comment]
rewe appears to have changed their website embedded data to an non standardized format. 

Tandoor uses https://github.com/hhursev/recipe-scrapers for pages that contain non standard data, you can add a custom scraper there or raise an issue to ask someone to do it. Once its done there we will update the library and you can import from rewe again.
