### ISSUE TITLE
URLs to resources and for API calls are not relative but seem to be absoulte (HTTP/HTTPS mismatch) (CORS issue?)

### ISSUE THREAD

**Issue by Daywalker01** [TandoorRecipes/recipes#1396]
### Tandoor Version

1.0.4.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

Links to Images and Javascript API Calls seem to be created with absolute paths with the wrong header.
I have set up my apache server as a reverse Proxy to the Nginx Container. I guess my setup is also flawed in this case, but it might not be apparent when all the created URLs are just relative paths where the browser would just do its part and use the websites Hostname and Protokoll to connect to any API endpoint.

Safari is complaining:
`[Warning] [blocked] The page at https://rezepte.mydomain.com/search/ was not allowed to display insecure content from http://rezepte.mydomain.com/api/meal-plan/?from_date=2022-01-22&to_date=2022-01-22. (chunk-vendors.124c48fd4079.js, line 254)`

Example:

```
$ curl --cookie "sessionid=some_already_invalid_id" "https://rezepte.mydomain.com/api/recipe/?query=&keywords_or=true&foods_or=true&books_or=true&internal=false&random=false&new=true&page=1&page_size=25&last_viewed=5" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2103  100  2103    0     0   5079      0 --:--:-- --:--:-- --:--:--  5079
{
  "count": 4,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 5,
      "name": "Kartoffelgulasch",
      "description": "some description",
      "image": "http://rezepte.mydomain.com/media/recipes/41f82fcf-b2f1-4692-a07a-3b3bf50902c7_5.jpeg",
      "keywords": [],
      "working_time": 15,
      "waiting_time": 20,
      "created_by": 1,
      "created_at": "2022-01-22T18:03:22.482576+01:00",
      "updated_at": "2022-01-22T18:03:26.252192+01:00",
      "internal": true,
      "servings": 2,
      "servings_text": "",
      "rating": 0,
      "last_cooked": null,
      "new": true
    },
....
```

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
   ServerAlias rezepte.mydomain.com

   LogLevel warn
   CustomLog ${APACHE_LOG_DIR}/tandoor_access.log combined
   ErrorLog ${APACHE_LOG_DIR}/tandoor_error.log

   ProxyPreserveHost On
   <Location />
   ProxyPass http://127.0.0.1:82/
   ProxyPassReverse https://127.0.0.1:82/
   </Location>

   SSLCertificateFile /etc/ssl/private/mydomain.com/fullchain.pem
   SSLCertificateKeyFile /etc/ssl/private/mydomain.com/privkey.pem
   Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

```
Proxy what is as follows:
Apache (SSL) -> Nginx (NonSSL, docker container)

Any Ideas what I might have done wrong?

Best regards, and thanks in advance!

**Comment by smilerz** [comment]
django requires specific headers to be set when operating behind a proxy.  Please see #1312 for a working apache configuration.

**Comment by Daywalker01** [comment]
@smilerz Thank you for your reply!
the Header
`RequestHeader set X-Forwarded-Proto "https"`
Did the trick.
Thank you!
