### ISSUE TITLE
Provide quick buttons to halve or double serving sizes in the recipe view

### ISSUE THREAD

**Issue by TheHaf** [TandoorRecipes/recipes#1397]
### Is your feature request related to a problem? Please describe.

I mainly use Tandoor on a tablet or sometimes on a phone and it's always a hassle to change the serving size of a recipe when I cook. On the desktop version of the app, the browser will render small arrow buttons in the input to increase and decrease the serving size by one on each click. To my knowledge there is no such thing on the mobile version of the app, at least on the Android devices that I use.

### Describe the solution you'd like

So I got the idea to add small buttons to the serving size input to let the user quickly change the serving size. The following image shows a quick mockup for how the serving change buttons could be integrated:
![image](https://user-images.githubusercontent.com/2690120/150653527-92260e2c-1bca-4a30-8fe4-ddc20fed2b49.png)

### Describe alternatives you've considered

There could be alternative ways to let the user modify the serving size more intuitively on a mobile device. I haven't gotten around to look into that further yet though.
Maybe the small arrows to increment and decrement the value by 1 could be added to the mobile view instead.

### Additional context

I hacked what's visible in the mockup screenshot directly into the RecipeView.vue page for now without any fancy layouting declarations.
If this proposal is popular, I could try to improve it according to suggestions and create a pull request so that the solution can be iterated upon.

### Contribute

- [X] Yes
- [ ] Partly
- [ ] No

**Comment by smilerz** [comment]
The lack of step buttons seems to be related to how mobile browsers render the number input field.

You can try using an [inline spinbutton](https://bootstrap-vue.org/docs/components/form-spinbutton#inline) which should handle most of the styling.

**Comment by TheHaf** [comment]
Thanks for that suggestion! I just tried it out on my PC and it does look nice already.

Unselected:
![image](https://user-images.githubusercontent.com/2690120/150654914-7b109b96-946c-474d-8d80-a63a034bb33c.png)

Selected:
![image](https://user-images.githubusercontent.com/2690120/150654921-a5ff9b3c-37de-4d25-aac2-fc242d17f1e5.png)

I'll need to check later how it looks on a mobile browser.

**Comment by vabene1111** [comment]
when i originally added that field i played around with that stupid input for way to long to get it somewhat decent but could not manage to do so :joy: so i resigned and made a simple input but i like something like on your last screenshots. Definitely something i want to look at again.

**Comment by TheHaf** [comment]
It took me a while to make the dev service instance accessible from a mobile device, but I was finally successful. 😸 
![image](https://user-images.githubusercontent.com/2690120/150800063-60064ff7-f261-446b-8475-4d42553a5846.png)

It basically looks the same now as there is no native component being used anymore for displaying the input.

I don't have the time right now unfortunately but unless there are any comments keeping me from doing so, I will open a PR later on. The change itself is quite small.

**Comment by vabene1111** [comment]
this looks cool, thanks 👍 you can still click into the input and put in a number right away correct ?

**Comment by TheHaf** [comment]
> this looks cool, thanks 👍 you can still click into the input and put in a number right away correct ?

Good point! I double-checked to be sure, and while this still works on Desktop Browsers, for some reason it currently doesn't work on mobile browsers. I'll look into it, maybe there is a config property for the web component that I am missing or there is some kind of styling issue that prevents clicking into the input field on mobile.

**Comment by TheHaf** [comment]
Ok, seems like this is intended behavior for the spinbutton component according to the official documentation:
> Similar to range type inputs, BootstrapVue's <b-form-spinbutton> does not allow the user to type in a value.

People on the bootstrap-vue recommended recreating the look and feel using a custom input group, so similar to my original attempt, but more pretty. 😉 I'm going to try it out.

**Comment by vabene1111** [comment]
awesome, let me know when its done or you need any help

**Comment by TheHaf** [comment]
Ok, I'll try to get it to work by following the code [here](https://github.com/bootstrap-vue/bootstrap-vue/issues/4977#issuecomment-740215609).

It may take a while, I'm not that familiar yet with Vue, but I keep my fingers crossed that I can make it work. 😸 If I come across a showstopper, I'll write a comment.

**Comment by TheHaf** [comment]
It now looks like this:
![image](https://user-images.githubusercontent.com/2690120/151061933-a90e85d4-b70b-4f91-9032-39ad97e98257.png)

I don't have access to my mobile right now, so I'll need to check it there later.

Anyway, I created a draft pull request just now.

**Comment by smilerz** [comment]
looks great!

**Comment by TheHaf** [comment]
I'm glad that you like it. 😸 

I was able to try it out on my mobile as well. It looks and behaves the same as on a Desktop browser, including the ability to enter a number.

**Comment by vabene1111** [comment]
i like that 👍 do the buttons actually double/half or do they increase by 1 ?

**Comment by TheHaf** [comment]
They increase and decrease by 1, I kept the functionality the same as a normal spin button.I am fine with either type and it's easy to modify the functionality. But I think it will be a challenge to find good icons to represent the double/ half type.Also, at the moment using the arrow up and down keys on the keyboard changes the value by 1 as well. I am not sure how this would be affected when the function that is triggered by the buttons is switched to the double/ half type. My guess is the keyboard arrow keys would still only change the value by 1 and this might be unexpected behavior for the user. Maybe that could also be adapted.Am 27.01.22, 08:23 schrieb vabene1111 ***@***.***>:

   
  i like that 👍 do the buttons actually double/half or do they increase by 1 ?

**Comment by vabene1111** [comment]
i prefer +/- 1 as well so no need to change that in my opinion. Just mark your PR as ready whenever you feel its done and i will test and merge the changes, thank you very much for your contribution.
