### ISSUE TITLE
Recipes from dm.de cannot be imported

### ISSUE THREAD

**Issue by ramteid** [TandoorRecipes/recipes#1398]
### Tandoor Version

1.0.4.1

### Import URL

https://www.dm.de/unternehmen/alverde-magazin/linzertorte-832932

### When did the issue happen?

Error message "Page returned invalid data" occurred when I was trying to import this recipe via Import -> Url.

### Response / message shown

```shell
Die angefragte Seite hat ungültige Daten zurückgegeben oder die Daten konnten nicht verarbeitet werden.
```

**Comment by smilerz** [comment]
Unfortunately, that site doesn't expose the recipe in HTML at all, so there is nothing to import.  It does look like they allow you to download a PDF of the recipe which you can store in Tandoor - at some point in the future we would like to be able to support importing PDF data as well.
