### ISSUE TITLE
Unbare to migrate recipe from Default Space into other Space because "Desc search vector:" field needs to be filled out

### ISSUE THREAD

**Issue by Daywalker01** [TandoorRecipes/recipes#1402]
### Tandoor Version

1.0.4.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

A Recipe was created in the Default Space without Description. But the Management complains that I need to fill out a "Desc search vector:"
The Normal Description field is left empty
Inserting two single quotes causes a 500 Server error, because I don't know the correct sync for that field.
Two Questions arise from this issue:
1) Why Is this field empty, and can reside in the Default Space?
2) What needs to be input in this filed if the description of a recipe is left empty intentionally? (would it make sense to have this value be the default?)

**Comment by smilerz** [comment]
How are you trying to move a recipe to a different space?
Can you please share the DEBUG logs (.env should have DEBUG=1 and the server restarted)

**Comment by vabene1111** [comment]
closed stale

**Comment by depasseg** [comment]
I also ran into this (not sure what caused it), and I resolved it by editing the recipe in the main webUI and adding words in the description and hitting save.
