### ISSUE TITLE
False URL redict

### ISSUE THREAD

**Issue by heartsaver1859** [TandoorRecipes/recipes#1403]
### Tandoor Version

1.0.4.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

False url when rying to open this: 
Das direkte ausliefern von Mediendateien mit gunicorn/python ist nicht empfehlenswert! Bitte folge den beschriebenen Schritten [hier](https://recpies.mydomain.de/system/https/://github.com/vabene1111/recipes/releases/tag/0.8.1), um Ihre Installation zu aktualisieren.
There is a type error https/:// that shoud be https:// like this. 
There is also no information how to fix this error code. 

### Relevant logs

```shell
No Logs nedded.
```

**Comment by smilerz** [comment]
That link is hard coded in the HTML correctly.  Do the other links on that page work?

**Comment by smilerz** [comment]
no response to request for further information
