### ISSUE TITLE
Ingredients not displayed with fractions since upgrading from 1.0.4 to 1.0.5

### ISSUE THREAD

**Issue by Programie** [TandoorRecipes/recipes#1408]
### Tandoor Version

1.0.5.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

Since the update to 1.0.5 and 1.0.5.1, fractions are not displayed in the ingredients list anymore, despite it's enabled in the user settings.

**Comment by vabene1111** [comment]
very interesting, thanks for letting me know, i will look into it

**Comment by vabene1111** [comment]
ok that was broken in a merge of different version i think, fix is pushed and will be included in the next release (or already on develop in a few minutes)
