### ISSUE TITLE
Ingredients overview contains steps without ingredients

### ISSUE THREAD

**Issue by Programie** [TandoorRecipes/recipes#1410]
### Tandoor Version

1.0.5.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

Recipes with a step containing no ingredients but with a title are listed in the ingredients overview.

![image](https://user-images.githubusercontent.com/1206521/151024506-088b382e-c600-4f41-865a-9284cea7e5e5.png)

![image](https://user-images.githubusercontent.com/1206521/151024604-cceca06c-7b1a-4b05-886b-47dba5be8116.png)

Additionally to that, the step titles are shown twice for each step.

**Comment by smilerz** [comment]
duplicate #1375
