### ISSUE TITLE
Hompage button

### ISSUE THREAD

**Issue by weetgeen** [TandoorRecipes/recipes#1412]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

I have set up reverse proxy with Apache2. The home button in the topbar is redirecting to localhost:8181 (The port i set for the reverse proxy). So the home button is not working from when working on other machines. 

All other buttons and hyperlinks are working well

![image](https://user-images.githubusercontent.com/11819689/151121650-d9f8622b-eeeb-42ae-9078-9ef3c57980e9.png)

![image](https://user-images.githubusercontent.com/11819689/151121156-dac5fe83-2d89-4cd9-a19c-ea3b8a956d96.png)

**Comment by ramanand-rv** [comment]
Hi @weetgeen, I would like to work on this issue.

**Comment by MaxJa4** [comment]
Take a look at #1312

Did you set all required headers correctly in your Apache config?

**Comment by weetgeen** [comment]
Thanks, this looked to work:
https://github.com/TandoorRecipes/recipes/issues/1312#issuecomment-1020034375

I thought all headers where correct because all was working except this but apperantly it was de apache2 conf file for the site
