### ISSUE TITLE
shopping list v2 settings

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1413]
### Tandoor Version

1.5.0.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

In `/shopping/new/` their is a tab `Settings`. But the `Save` button is not on the page.

Same menu is in `User Settings` tab `Shopping-Settings` with a save button.

There is also a missmatch of the order and descriptions
![image](https://user-images.githubusercontent.com/29805669/151139635-f2e64c2a-ded4-4815-9555-543d7da714e5.png)

**Comment by smilerz** [comment]
One page requires a post to save settings. One  does not. 
I don’t think the order matters.
