### ISSUE TITLE
Storeable searches or dynamic books

### ISSUE THREAD

**Issue by Programie** [TandoorRecipes/recipes#1416]
### Is your feature request related to a problem? Please describe.

Searching for something (i.e. filtering by a specific keyword) and saving the search for the future to make it easier to search for specific things would be a nice feature.

Those searches might be also shareable with other users (like books).

Another possibility would be to create dynamic books based on keyword.

An example for both variants:

I have keywords like "Hauptgerichte" (meals), "Soßen" (sauces), "Salate" (salads), etc. which I want to use as categories and quickly want to see whats in it. I.e. just like categories known from the Nextcloud Cookbook.

In my case, I often want to see which meals I've in my cookbook to get some inspirations what I could cook next. For that I only want to see recipes with a specific keyword.

### Describe the solution you'd like

Allow to save a search using the current filters, search query, sorting, etc.

OR

Allow to create dynamic books (i.e. specify a keyword which defines which recipes should be included in a book)

### Describe alternatives you've considered

Creating browser bookmarks by using the links used by the "click on keywords" implementation (#1287). But unfortunately, those are browser specific and sharing is not as intuitive as implementing it directly in Tandoor (with sharing like implemented in meal plans and books).

### Contribute

- [ ] Yes
- [ ] Partly
- [X] No

**Comment by smilerz** [comment]
You are in luck - saved filters and dynamic books are both in the next feature #1417  I'm working on.  It's substantially complete and will likely be ready for the next release.

**Comment by Programie** [comment]
Cool, I've searched for existing issues but couldn't find that one. Thanks for the hint!

**Comment by smilerz** [comment]
You reminded me to create it. :)

**Comment by Programie** [comment]
Ah right, you just created that. I haven't looked at the higher issue number and creation time. :D
