### ISSUE TITLE
Custom Filters

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#1417]
Enhance recipe search:

Filter by:
 - [x] last time cooked #784
 - [x] number of times cooked
 - [x] units
 - [x] recipes that can be cooked with OnHand foods

Other features:
- [x] Quick sort by Name, Last Viewed, Last Cooked, Search Rank, Rating
- [x] Sort by multiple values
- [x] Hide/Enable search fields
- [x] Expert Mode to search for [ANY items NOT in a list] and/or [ALL items NOT in a list]
- [x] Expert Mode to add up to 4 variations on the above
- [x] Ability to save search as a Custom Filter
- [x] Ability to assign Custom Filter to a Cookbook
- [x] Ability to order Cookbook with Custom Filter into chapters

Open Tasks
- [x] Tests for substitute inheritance
- [x] Tests for makenow

**Comment by vabene1111** [comment]
ok so as discussed on discord the things i found when playing around a bit. Some of these are actually just observations and dont require any changes, i just want to write them down so we can talk about them 

- [ ] the button next to the "+" (which adds another filter) does not show the "-" when only one row is shown, but it can still be clicked to remove the field
- [ ] after selecting a custom filter the keywords dont load their names and just show emtpy pills (just tested with keywords)
- [ ] the Field "Filters" to apply one of the saved custom filter should probably always show as this i think is the most useful feature and also adds a lot to explaining what this does. 
- [ ] do we need something to manage custom filters (or at least delete) ? maybe load the values into the form and show a delete and save button to save into a filter while its selected or delete it 
- [ ] explain the behavior of the and/or in the UI (maybe a string that automatically builds itself that shows the query in a human friendly way or some kind of "explain" button ?) 
- [ ] something is broken with sorting (i have sorting by name, the first recipe is Aioli, then Quinoa, then nudelauflauf...)
- [ ] after adding a custom filter to a book a reload is needed to load the recipes 
- [ ] maybe find some kind of idea how to communicate the or or or problem trough UI

**Comment by smilerz** [comment]
> maybe find some kind of idea how to communicate the or or or problem trough UI

other option is to disable the ability to select an OR filter again

**Comment by vabene1111** [comment]
awesome, thanks for working on all those things.

- [ ] add filter fields for "created after/before" "updated after/before" date (to for example show only recipes that were added in the last week or ones that have been around for a long time)
- [ ] sort order indicator backwards (at least on the name), the arrow up orders from A->Z which is think is reversed
- [ ] help text on book custom filter change "instead of adding manually" -> "in addition to manually added recipes"

**Comment by smilerz** [comment]
RE: created before/after:

the RecipeSearch class and query parameters should be refactored to combine these with the _new parameter.

the created_after would search for recipes created after YYYY-MM-DD, when combined with `?_new=true` the recipes would be sorted first, when `?_new=false` the recipes would be filtered.  This would also let the client specify how many days are considered 'new' instead of hard coding the value to 7 days (or 14? I forget)
