### ISSUE TITLE
New shopping list: Incorrect amount of ingredients (due to erroneous recipe scaling?)

### ISSUE THREAD

**Issue by philip-n** [TandoorRecipes/recipes#1419]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

**Observations / how to reproduce**

0. Remove all previous shopping lists (e.g. mark as finished).
~~1. Add some recipes to meal planner, leave everything on default settings (just set the required meal type field).~~
~~2. In meal planner, add recipes to shopping list via their context menu.~~
~~3. In meal planner, click the "shopping list" button at the bottom and create a new shopping list via the slide-in menu at the side.~~
1. Just add any recipe to shopping list (no need to go via meal planner).
4. Check the shopping list in the "old" view - amounts look okay. At this step, each recipe should show up with `1` portion (default).
5. Save the shopping list in the "old" view. Amounts still look okay.
6. Click the nice "try new shopping list" button.
7. **Find that in the new view, for each ingredient, some percentage of the required amount was added in addition**.
8. Click on the "details" button of any ingredient:
    * Each recipe is listed twice in the small subtext
    * For each recipe, there are two entries: One with the full amount (e.g. 500 ml water) and one "extra-amount" (like an additional 125 ml).
9. The "old" shopping list still shows the correct amounts, so it looks like some logic error when calculating the required amounts from the (correct) data in the backend.

---

Additional information / assumptions:
* This also happens for items without a quantity. E.g. "salt and pepper" is used in 3 recipes, so it shows up 3 * 2 times with quantity 0.
* **The issue seems to be related to the portions set in the recipe.**
    * A recipe for 2 portions shows the original amount from the recipe + an additional 50%.
    * A recipe for 4 portions shows the original amount from the recipe + an additional 25%.

---

**Workaround**

Manually set the portions in the shopping list to the same value as the recipes portions (e.g. recipe for 3 portions - set to three portions in the shopping list). This makes the additional ingredients disappear.

**Comment by smilerz** [comment]
I'm having a hard time visualizing what you are describing - can you add screenshots?

**Comment by philip-n** [comment]
Sure!

An example recipe, set to 4 portions:
![original_recipe](https://user-images.githubusercontent.com/3903619/151209639-a50e0db3-7abb-4aa1-bd5e-ef66811f3db1.png)

Adding it to the shopping list gives this (old view, recipe set to 1 portion [i.e. default]):
![old_shopping_list_:correct_amounts_one_portion](https://user-images.githubusercontent.com/3903619/151209968-30da388e-dd75-472a-a3f2-92ca75c86cd2.png)

The new shopping list adds some more ingredients (in this case, 1/4):
![new_shopping_list_wrong_additional_amounts](https://user-images.githubusercontent.com/3903619/151210118-2fa316b2-fe98-4045-8fb5-b59cc99b1289.png)

**Comment by smilerz** [comment]
How did you add it to the shopping list?

**Comment by smilerz** [comment]
Oh!!  I think I see now - you added the recipe using the old and new method.  Correct?
The old shopping list didn't scale recipes properly.  1 servings = 1*recipe servings so 1 servings would be 4/4 of the recipe
The new shopping list correctly scales the servings to the recipe.  1 serving in your example would be 1/4 of the recipe.

Did I capture the difference you were seeing?

**Comment by philip-n** [comment]
Yes, I guess that's correct. When I use the three-dots-menu in the recipe and click the "Add to NEW shopping list" item, then there is a scaling dialog that asks how many portions shall be added. This seems to work fine.

If I go via the old shopping list, the old lists seems to add the full recipe (1* recipe servings), and the new list additionally adds the scaled servings.

So currently, I think that the "Add to NEW shopping list" button is the only working route to use the new shopping list; other alternatives (e.g. via meal planner where there is no new shopping list yet) lead to the problem I described above.

**Comment by smilerz** [comment]
> If I go via the old shopping list, the old lists seems to add the full recipe (1* recipe servings), and the new list additionally adds the scaled servings.
>

You are seeing both recipes in your shopping list (one added from new list & one added from old list).  If you switch to the 'Recipes' tab you can see both.  One will have 1 serving size, the other will have 4 serving size

**Comment by philip-n** [comment]
> You are seeing both recipes in your shopping list (one added from new list & one added from old list). If you switch to the 'Recipes' tab you can see both. One will have 1 serving size, the other will have 4 serving size

I have to admit that I'm not fully convinced.

When I go via the "old shopping list route" the recipes tab in the new list only shows the recipe only once (with the value assigned in the new list). Otherwise I would have realized sooner what's the cause ;)

1.25 recipes shown in list tab,
![Bildschirmfoto von 2022-01-26 18-57-49](https://user-images.githubusercontent.com/3903619/151219797-7860bd1d-19ac-4068-b704-73586da4fb56.png)

, but only one recipe visible in recipe tab:
![Bildschirmfoto von 2022-01-26 18-57-39](https://user-images.githubusercontent.com/3903619/151219758-d0173de4-1cf0-492e-bf82-5e2eb75c5aef.png)


As I have written somewhere above, if I scale up to 4 portions in the recipes tab in the new view, then the list shows each ingredient exactly as in the recipe (and not double the amount, as would result from 1x by old shopping list and 4/4x by new shopping list):

Starting at the situation above, changing from 1 to 4 portions...
![Bildschirmfoto von 2022-01-26 19-02-34](https://user-images.githubusercontent.com/3903619/151220567-5aeb9fe1-90b0-4203-8c65-c75288b7350a.png)

... leads to 1x the recipe.
![Bildschirmfoto von 2022-01-26 19-02-41](https://user-images.githubusercontent.com/3903619/151220548-83f5622c-7355-47e4-9a4b-95209a7583e0.png)

**Comment by smilerz** [comment]
OK - I see the behavior now.  Thanks for your patience.
