### ISSUE TITLE
Shopping v2 unavailable from meal planner page

### ISSUE THREAD

**Issue by lceWolf** [TandoorRecipes/recipes#1423]
### Is your feature request related to a problem? Please describe.

Planning meals for the week, one is unable to use the new shopping list from the meal planner page as there is no option to add it to the new shopping list. Only the old version is available

### Describe the solution you'd like

Add the ability to chosse "add to NEW shopping list" in the context menu for the meal planner - just like from the recipe's context menu

### Contribute

- [ ] Yes
- [X] Partly
- [ ] No

**Comment by smilerz** [comment]
When adding a recipe to the meal plan you can either select the 'add to shopping' checkbox in the add/edit dialogue

![image](https://user-images.githubusercontent.com/1808639/151252740-e2df5f62-a6d7-4e06-a2b4-8d4fd6000c08.png)


or set your shopping preferences to automatically add meal plans to your shopping list

![image](https://user-images.githubusercontent.com/1808639/151252895-540bb4cf-3a4a-445e-8fc4-8eafe95fbc1c.png)

**Comment by lceWolf** [comment]
@smilerz Not sure if I understand correctly. When I try to add a recipe to the planner I do not see the "Add to shopping list" checkbox (I am on 1.0.5.2)
![grafik](https://user-images.githubusercontent.com/1565886/151669940-281742fe-19a4-45d8-b0d3-22b79de6a595.png)

Usually my workflow is as follows: search recipes I want to cook next week and add them to the planner. From the planner I want to add them to the shopping list. I'd prefer to do it manually, because when adding them automatically I can not check for food I have already on hand (but maybe I missed it until now). 
When adding them manually from the context menu of the planned recipe, I expected a pop-up to show up, just like when adding a recipe from the recipe view (recipe selected from the cookbook) to the shopping list, but currently it is not possible to add a recipe to the shopping list v2 from within the planner

My workaround for this is to fill the meal planner and add the recipes from the recipe's view (meal planner: context menu -> recipe) which is a little cumbersome
Maybe it is just me and this is no common usecase tho 😀

**Comment by smilerz** [comment]
> @smilerz Not sure if I understand correctly. When I try to add a recipe to the planner I do not see the "Add to shopping list" checkbox (I am on 1.0.5.2) ![grafik](https://user-images.githubusercontent.com/1565886/151669940-281742fe-19a4-45d8-b0d3-22b79de6a595.png)
> 
Do you have Auto Add MealPlan enabled in the shopping list settings?  If so, you won't see the shopping list.
![image](https://user-images.githubusercontent.com/1808639/151670943-16896aff-11e9-4c45-89c7-49e917091ea5.png)

Right now, you cannot review the individual entries when added this way, but I'm working on adding that capability.  Should be done in the next week or so.

**Comment by lceWolf** [comment]
Yes, I was messing around with that...

> Right now, you cannot review the individual entries when added this way, but I'm working on adding that capability. Should be done in the next week or so.

Nice! Looking forward to that feature 😄
