### ISSUE TITLE
shopping list v2 - complete item error

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1426]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I want to mark an item as complete in shopping list v2.

I get the error `There was an error updating a resource!`

In browser developer tools I get this message
```
chunk-vendors.d286c480be2e.js:530 PATCH http://192.168.178.15:10005/api/shopping-list-entry/20/ 403 (Forbidden)
(anonymous) @ chunk-vendors.d286c480be2e.js:530
e.exports @ chunk-vendors.d286c480be2e.js:530
e.exports @ chunk-vendors.d286c480be2e.js:103
l.request @ chunk-vendors.d286c480be2e.js:13
(anonymous) @ chunk-vendors.d286c480be2e.js:41
(anonymous) @ shopping_list_view.be43e7b54a00.js:1
(anonymous) @ shopping_list_view.be43e7b54a00.js:1
Promise.then (async)
partialUpdateShoppingListEntry @ shopping_list_view.be43e7b54a00.js:1
saveThis @ shopping_list_view.be43e7b54a00.js:1
(anonymous) @ shopping_list_view.be43e7b54a00.js:1
updateChecked @ shopping_list_view.be43e7b54a00.js:1
ot @ chunk-vendors.d286c480be2e.js:503
n @ chunk-vendors.d286c480be2e.js:503
ot @ chunk-vendors.d286c480be2e.js:503
Tn.e.$emit @ chunk-vendors.d286c480be2e.js:503
updateChecked @ shopping_list_view.be43e7b54a00.js:1
ot @ chunk-vendors.d286c480be2e.js:503
n @ chunk-vendors.d286c480be2e.js:503
Uo.o._wrapper @ chunk-vendors.d286c480be2e.js:503
shopping_list_view.be43e7b54a00.js:1 Error: Request failed with status code 403
    at e.exports (chunk-vendors.d286c480be2e.js:69:3074)
    at e.exports (chunk-vendors.d286c480be2e.js:93:3304)
    at XMLHttpRequest._ (chunk-vendors.d286c480be2e.js:530:2824) {data: {…}, status: 403, statusText: 'Forbidden', headers: {…}, config: {…}, …}#
```

In Network Tab
`detail: "You do not have permission to perform this action."`

**Comment by smilerz** [comment]
Can you provide any more details on the scenario?  I've been running it for some time and don't have this issue.

**Comment by TWART016** [comment]
I just add a recipe to the new shopping list and want to mark an item as complete.

What more information do you need?

**Comment by smilerz** [comment]
Enough information to recreate the error.  Is it all items?  A single item?  What is different between ones that work and ones that don't?

If I can't reproduce the problem, I can't fix it.

**Comment by TWART016** [comment]
Yes all items and also mark all from one category.

I updated a few days from 1.0.4 to 1.0.5.2. I tried first time and get the error. It never was successful.

**Comment by smilerz** [comment]
Were the items created with the previous version of the shopping list?  Were they created on 1.0.4?  Are there other users in the space?  If so, did another user create the shopping entries?  The recipe?

**Comment by TWART016** [comment]
I think they were created in 1.0.4. 
I can create a new food and this is working fine with mark as complete. Seems that I can't mark the items from another user.

Yes there are other users in that spaces. I think I created the recipe with another user. With this one I can mark these items as completed without an error.

**Comment by smilerz** [comment]
In the shopping list, if you expend 'Details' it should say 'created by xxxx'.
Can you confirm that it is a different user?  Does that user have the shopping list shared with you ('Share Shopping List' on the settings tab).  Do you have the shopping list shared with that user?

**Comment by TWART016** [comment]
Yes I can confirm all items from another user have the problem.

The user have shared the list with the user who gets the error.

**Comment by smilerz** [comment]
thanks - I was able to reproduce the issue.  A PR has been submitted

**Comment by TWART016** [comment]
thank you were much

**Comment by TWART016** [comment]
will this be fixed in the next version? 1.0.8 still have the problem.

**Comment by smilerz** [comment]
> Will this be fixed in the next version? 1.0.8 still have the pro

I just switched to 1.0.8 and can't reproduce this.

**Comment by TWART016** [comment]
I tried with latest 1.0.8 and develop and get the error while mark the item of another user as complete. 

With that fix is was working.
https://github.com/TandoorRecipes/recipes/issues/1426#issuecomment-1023711819
Is this not in the release?

**Comment by smilerz** [comment]
It is. And there is a unit test to catch a failure of that scenario.

**Comment by TWART016** [comment]
I still can see `detail: "You do not have permission to perform this action."`

```
chunk-vendors.98c793768798.js:530 PATCH https://recipe.twhome.de/api/shopping-list-entry/10/ 403
(anonymous) @ chunk-vendors.98c793768798.js:530
e.exports @ chunk-vendors.98c793768798.js:530
e.exports @ chunk-vendors.98c793768798.js:103
l.request @ chunk-vendors.98c793768798.js:13
(anonymous) @ chunk-vendors.98c793768798.js:41
(anonymous) @ shopping_list_view.70a5cbf274b2.js:1
(anonymous) @ shopping_list_view.70a5cbf274b2.js:1
Promise.then (async)
partialUpdateShoppingListEntry @ shopping_list_view.70a5cbf274b2.js:1
saveThis @ shopping_list_view.70a5cbf274b2.js:1
(anonymous) @ shopping_list_view.70a5cbf274b2.js:1
updateChecked @ shopping_list_view.70a5cbf274b2.js:1
ot @ chunk-vendors.98c793768798.js:503
n @ chunk-vendors.98c793768798.js:503
ot @ chunk-vendors.98c793768798.js:503
Tn.e.$emit @ chunk-vendors.98c793768798.js:503
updateChecked @ shopping_list_view.70a5cbf274b2.js:1
ot @ chunk-vendors.98c793768798.js:503
n @ chunk-vendors.98c793768798.js:503
Uo.o._wrapper @ chunk-vendors.98c793768798.js:503
```

**Comment by TWART016** [comment]
correction: with develop I get no error.

**Comment by smilerz** [comment]
> correction: with develop I get no error.

I just double checked - the code that fixes this is in 1.0.8.  As is the unit test, which passes.

Can you:
- confirm that you are running 1.0.8 when you get the error.
- confirm that you are attempting to complete a V1 shopping list that is shared using the new V2 shopping page
-  go to Admin and share all of the details on the shopping list entry that is causing an error
- in Admin: share all of the details from the user preference for the entry creator and the attempted closer

**Comment by vabene1111** [comment]
i remember you are using a manual setup correct ? are you sure you updated correctly ?

**Comment by TWART016** [comment]
Version is 1.0.8 from docker-compose.

Just items from V1 list have the problem.

With admin user I shared the list with the user
e.g. number 9 is not possible to check with the user
![image](https://user-images.githubusercontent.com/29805669/152954079-81dd7db4-2feb-4be2-8749-15a4aa621143.png)

admin:
![image](https://user-images.githubusercontent.com/29805669/152954671-9c2df8dd-4981-47f0-a6e8-24ccdaa01884.png)

user:
![image](https://user-images.githubusercontent.com/29805669/152955685-4cc298ff-0de2-4743-b5bc-47b87f0136b0.png)

**Comment by vabene1111** [comment]
ok so this issue only affects v1 lists, that might be something different, i have not tested that.

**Comment by smilerz** [comment]
> ok so this issue only affects v1 lists, that might be something different, i have not tested that.

I did - there is a unit test for it and I just confirmed it works as a general case.

@TWART016 can you click into the details on Entry 9 please and provide the details.

**Comment by TWART016** [comment]
This is entry 9
![image](https://user-images.githubusercontent.com/29805669/153042671-c3610313-3cff-46ad-bf23-3482bb477fe8.png)

**Comment by smilerz** [comment]
sorry - the details in the admin - I want to see all of the underlying data.

**Comment by TWART016** [comment]
![image](https://user-images.githubusercontent.com/29805669/153046794-2b584b11-a296-4052-a053-ae1a396c463c.png)
