### ISSUE TITLE
mobile view optimization for shopping list v2

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1427]
### Is your feature request related to a problem? Please describe.

I want to use the shopping list v2 on mobile view (iPhone 11).

1) clearer if the three dots are a category or an item
2) On right-handed mode it is difficult to touch the details arrow. It is too close to the box.
3) On left-handed mode the box is cut of
4) Save space on the top and the bottom

### Describe the solution you'd like

1) items more on the right side
![image](https://user-images.githubusercontent.com/29805669/151434167-5e6a46be-30e4-4162-906e-d16838fba344.png)

2) more space between the two elements
![image](https://user-images.githubusercontent.com/29805669/151434960-401c3847-92a4-4148-ae5e-84f3b7c41eaa.png)

3) fix box
![image](https://user-images.githubusercontent.com/29805669/151435293-b2611e3e-ba5f-49e0-8298-67a754f00be6.png)

4) top: menu in one line, bottom: empty space
![image](https://user-images.githubusercontent.com/29805669/151435890-5ab8848b-43a9-442e-8ea6-c73b5562b5ff.png)

### Contribute

- [ ] Yes
- [X] Partly
- [ ] No

**Comment by vabene1111** [comment]
some of those things are already on the main list, some are new some i am not sure about. Will link this in the collective issue so we can take a look at it when working on it again.

**Comment by smilerz** [comment]
tabs at the top won't be fixed - they are responsive and intentionally wrap when the width is too narrow.

**Comment by Kaibu** [comment]
Tabs are icons on mobile now, empty space at the bottom is fixed.
All collisions with the sides should be fixed too, I've tried to test many devices/screens.
