### ISSUE TITLE
Error "Endpoint creation" when starting the containers

### ISSUE THREAD

**Issue by strangezuffi** [TandoorRecipes/recipes#1428]
Hi,

it's probably more a docker issue than a Tandoor issue, but as I haven't knowingly changed anything in the default setup, I have to ask:

When starting Tandoor with `docker compose up`, I get the following error message.
```
pi@tandoor:~/tandoor $ docker compose up
[+] Running 4/4
 ⠿ Network tandoor_default            Created                                                                      0.1s
 ⠿ Container tandoor-db_recipes-1     Created                                                                      0.4s
 ⠿ Container tandoor-web_recipes-1    Created                                                                      0.3s
 ⠿ Container tandoor-nginx_recipes-1  Created                                                                      0.3s
Attaching to tandoor-db_recipes-1, tandoor-nginx_recipes-1, tandoor-web_recipes-1
Error response from daemon: failed to create endpoint tandoor-db_recipes-1 on network tandoor_default: failed to add the host (veth1147bde) <=> sandbox (vethd356d84) pair interfaces: operation not supported
```

As I said, I didn't knowingly change any config files, so I don't even know where to start looking.

Any idea?

**Comment by smilerz** [comment]
definitely a docker issue - this [this](https://stackoverflow.com/questions/33600154/docker-not-starting-could-not-delete-the-default-bridge-network-network-bridg)

**Comment by strangezuffi** [comment]
followed the instructions, still have the same problem.

The service restart of Docker did not bring up any error messages. The start of Tandoor brought up the same error as shown above.

**Comment by smilerz** [comment]
You'll probably have better luck in a docker support forum.
