### ISSUE TITLE
Prevent switching display off after OS timeout

### ISSUE THREAD

**Issue by 2Fake** [TandoorRecipes/recipes#1434]
### Is your feature request related to a problem? Please describe.

If you are cooking a recipe from your Tandoor recipe instance on a mobile device the display switches off after the timeout declared in the setting of your OS. Some apps, e.g. [Chefkoch](https://play.google.com/store/apps/details?id=de.pixelhouse&referrer=utm_source%3Dchefkoch.de%26utm_medium%3Dbanner%26utm_content%3Dmagazin_top%26utm_campaign%3Dchefkoch.generalcamp) keeps the display on.

### Describe the solution you'd like

Keep the display on

### Additional context

Maybe i can implement this on my own. I am able to contribute python code, but never worked with django

### Contribute

- [X] Yes
- [X] Partly
- [ ] No

**Comment by smilerz** [comment]
How do you do this within the context of a browser?  My understanding is that this requires a native mobile application.

**Comment by 2Fake** [comment]
I'm not sure, if this is possible in a mobile browser.

**Comment by 2Fake** [comment]
At least chrome supports a way to keep the display on

https://chromestatus.com/feature/4636879949398016

**Comment by smilerz** [comment]
good catch, its' something I've wanted for awhile. Looks like it is still experimental and limited availability for now.

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API

**Comment by screendriver** [comment]
👍  for that. At least Android Chrome user like me [can benefit from](https://caniuse.com/wake-lock) it.
