### ISSUE TITLE
Search doesn't work with non-english or accented characters 

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1436]
### Tandoor Version

1.0.5.1

### Setup

Manual Setup

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Search for food items doesn't find any results when searching for 
French accents like in " Crème fraîche"
or German Umlauts like in "Eiweiß".
Both can be entered in editing a recipe perfectly are also shown to the user without issues.
Just the search doesn't handle them.

**Comment by vabene1111** [comment]
i guess the unaccent function was present in the `/dal/` endpoints but is not part of the DRF api endpoint, i will fix that.

**Comment by smilerz** [comment]
This works for me - can you provide some additional details?
Where are you searching? How are your search-settings setup in `/settings`?

**Comment by MarcusWolschon** [comment]
I noticed it in "/list/food/" with a German Firefox.
Just tried to reproduce it on a freshly pulled "develop" Branch. Looks like it has already been fixed.
