### ISSUE TITLE
tags for ingredients ("safe for heat preservation", "vegan", "kosher", "gluten free")

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1440]
### Describe the solution you'd like

1. Allow ingredients to have tags, similar to recipes
2. Display these tags next to them
3. Allow filtering search results to recipes where all or none ingredients match a tag

example:

- only ingredients that can be preserved by heating to make canned, prepared meals
- only ingredients that are kosher
- no ingredients that are not vegan

### Describe alternatives you've considered

Allow filtering recipe search for recipes that do NOT contain a specific ingredient

### Contribute

- [X] Yes
- [ ] Partly
- [ ] No

**Comment by smilerz** [comment]
Duplicate #665

**Comment by MarcusWolschon** [comment]
Thanks. I couldn't find that one as it didn't use the work "tag".
