### ISSUE TITLE
Unable to select icon for new tag in mobile

### ISSUE THREAD

**Issue by Forceu** [TandoorRecipes/recipes#1441]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Nginx

### Bug description

On mobile it is not possible to open the icon selector when creating a new tag. It only openes if you hover on it, by tapping on it on a mobile it does not or simply select a random emoji

Also there is no more search, which was very important for me. And there is a white text field with white text next to the icon chooser.

![image](https://user-images.githubusercontent.com/1593467/151717152-fb8b104c-b948-4717-a2dc-7d8a60ca20b4.png)

**Comment by vabene1111** [comment]
fixed by changing open condition for emoji picker to `click` instead of `hover`
