### ISSUE TITLE
Number of servings from meal plan gets ignored

### ISSUE THREAD

**Issue by 0utl4w** [TandoorRecipes/recipes#1461]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

The number of servings of a meal from the meal plan gets ignored when you add the meal to the shopping list. 

Example: The recipe is for 2 servings, I add that meal to the plan and change it to 4 servings. Afterwards I add the meal from the plan to the shopping list and on the shopping list it shows only ingredients for 2 servings. 

Expectation: The number of servings from the meal plan is taken into account on the shopping list.

**Comment by vabene1111** [comment]
are you using the old or new shopping ist ? the old one had a bug with servings which was not fixed due to the new shopping list already being close to finished.

**Comment by 0utl4w** [comment]
No, I used the old shopping list. My problem with the new shopping list is, that it is full with entries from the past (on the tabs "shopping list" and "recipes") I cannot delete...

And it seems that the new shopping list ist one long list and I cannot create a new empty one anymore. To this moment, I really don't like the new shopping list.

**Comment by 0utl4w** [comment]
Ok, I was able to empty the new shopping list. I had to check all entries under "shopping list" one by one. After 500 clicks... every entry was checked and also the recipes tab was empty. 

Then I retested the points I reported and they worked with the new shopping list. So you can close my two tickets.
