### ISSUE TITLE
Import „Servings Text“

### ISSUE THREAD

**Issue by JSAnyone** [TandoorRecipes/recipes#1465]
### Describe the solution you'd like

It would be really great if the `servings text` gets imported automatically.
If that’s not possible, an option to change that manual directly at import would be great. Right now you have to edit the recipe afterwards to change this parameter.

### Contribute

- [ ] Yes
- [x] Partly
- [ ] No

**Comment by MarcusWolschon** [comment]
You mean the JSON  `"recipeYield":"2 Portionen"` being imported as 2 but with servings text empty?

**Comment by JSAnyone** [comment]
The default servings text is `Portionen`. But very often different texts are used, like `Bleche` or `Gläser` `Stücke`. Right now they are not imported automatically (which maybe just isn’t possible), but you also can’t change this text directly at export. However Tandoor supports it in general and when editing a recipe afterwards it‘s possible to change this text.

**Comment by vabene1111** [comment]
in the microdata/json markup its as marcus said stored in one field. I have a function to extract the number but not for the text, might be possible to add tough

**Comment by vabene1111** [comment]
will be imported with next importer update
