### ISSUE TITLE
Inconsistency in unselected dropdown styling

### ISSUE THREAD

**Issue by benscobie** [TandoorRecipes/recipes#1467]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

After performing a lookup using the URL Import using [this recipe](https://www.bbcgoodfood.com/recipes/beef-vegetable-casserole), if you de-select a measurement size, the _Select one_ styling is different to that of one where the there was no selection made by the importer. Example below (bottom was unselected):

![image](https://user-images.githubusercontent.com/944312/152038411-40d46af7-d19e-4d64-a2fb-70289dfb65ad.png)

They should probably be consistent, what's the preference here? _Select one_ to me reads as 'I must select one in order to save'. I'm happy to have a shot at aligning these once I know your preference.

**Comment by vabene1111** [comment]
this whole page needs some rework done to it but i have so far not gotten to implementing that. But definitely, all dropdowns should be the same eventually. 

thanks for reporting :)

**Comment by vabene1111** [comment]
i will close this as i am planning on removing all those inputs anyway so when i get to it this will also be resolved
