### ISSUE TITLE
Ingredients not rendering correctly after being edited

### ISSUE THREAD

**Issue by jcpetro97** [TandoorRecipes/recipes#1481]
### Tandoor Version

1.0.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

I noticed that the ingredients section does not render when the ingredients list has been altered after import.   I had an imported recipe, where the ingredients were broken up into two groups based on the size of what you were making.  To separate these I edited the recipe, clicked on the + sign at the bottom of the ingredients, and then changed from an ingredient to a Header, with the info I needed.  When I hit save/view I noticed the ingredients didn't render.  Going back into the edit mode of the recipe, everything was there as expected. 

If I remove the header I added, then the recipe renders as expected.  

I also noticed the same thing happens, if I add an ingredient, but instead of filling out the measurement quantity and the food, I just put a note in the notes field.

**Comment by vabene1111** [comment]
thank you very much, i will try to fix this asap.

**Comment by vabene1111** [comment]
ok thanks for pointing this out. this was an issue with the new shopping function not handling note only ingredients correctly. Its fixed in the next release which will likely be out very soon.
