### ISSUE TITLE
Prevent data loss while editing recipes 

### ISSUE THREAD

**Issue by Brotzocker** [TandoorRecipes/recipes#1483]
### Is your feature request related to a problem? Please describe.

While editing / creating a recipe a click on the "View" Button deletes all of my changes without a warning or asking to proceed.
Yes there is a Button "Safe & View" but in the process I clicked often the wrong button and had to start all over again.

### Describe the solution you'd like

It would be good to get a warning that my not saved changes will get lost or have them saved automatically. 

### Describe alternatives you've considered

When my changes to a recipe will be cached and I still can use them later on.

### Contribute

- [ ] Yes
- [X] Partly
- [ ] No

**Comment by vabene1111** [comment]
interesting, there should be a warning alert before leaving the page but maybe the view button cirumvents that check, will need to look at that

**Comment by vabene1111** [comment]
ok so i just tested this. When i edit a recipe in any field it gives me a warning message if i want to leave the page when clicking the view button, can you test this and make sure this is the same for you. 

if not please provide some information about the browser you are using and how your setup is installed.

**Comment by Brotzocker** [comment]
I have tested it know with Safari, Firefox and Chrome.
With Firefox and Safari it didn't give me a warning message, only Chrome warned me.

My installed Setup is a simple Docker Setup with just the Secret_key and Postgres_password set, nothing else. 
Using Tandoor Version 1.0.4.1 at the moment, but planing to update in the next days.

**Comment by vabene1111** [comment]
i hate safari and firefox so much .. why cant they just work as chrome does all the time 😕 its not even that special of a function ...

i will test on the latest version and see if its still broken and how to fix it, thanks for reporting

**Comment by dlaukamp** [comment]
I have also noticed this (using Firefox), when entering a lot of ingredients manually, it can be a bit frustrating. 

I'm on 1.0.8 by now and can still reproduce this, if it it's of any interest.

**Comment by vabene1111** [comment]
ok awesome, thanks for the feedback. i will look into fixing this

**Comment by vabene1111** [comment]
ok so apperently firefox does not allow an empty string for a value that can be any string and is not used anywhere .. from what i read this has been causing headaches to developers for >6 years so good job again mozilla 😂 fixed with the next release .. also maybe they have a reason and i just have not found the explanation 😂
