### ISSUE TITLE
Incorrect number of servings when importing Paprika Recipe Manager 3 recipes

### ISSUE THREAD

**Issue by Hausmeister486** [TandoorRecipes/recipes#1485]
### Tandoor Version

1.06

### Setup

Unraid

### Reverse Proxy

No reverse proxy

### Bug description

when importing a recipe from Paprika Manager 3, the number of servings is always "1" even if the number in the recipe is "2". The entries for "total time" are also ignored

**Comment by Hausmeister486** [comment]
![2022-01-30_08-32](https://user-images.githubusercontent.com/76865047/152627225-a5667f72-16dc-4a70-8f36-437e65965c11.png)

**Comment by vabene1111** [comment]
the paprika importer is rather old and might be lacking some features, i will review this and see if i can add those fields

**Comment by Hausmeister486** [comment]
Please tell me if you need an exported recipe.

Thanks for your Support

**Comment by vabene1111** [comment]
I think I have some old sample files I will test with those if they don't suffice I will let you know, thanks for the offer

**Comment by Hausmeister486** [comment]
It is not necessary to add an additional field for the "total_time", if you do not import from Paprika but from the original source URL, then everything is correct.
In this case from https://www.hellofresh.de/recipes/

After importing from Paprika the false assignment is:
Paprika      /        Tandoor
rep_time     =    Preparation
cook_time   =    Waiting
total__time  =    n.a.

After importing from the source URL:
Hellofresh  /       Tandoor
cook_time   =     Preparation
Tandoor Waiting time is ignored, so always set to "0"

**Comment by vabene1111** [comment]
hmm is this a general problem accross all your recipes or does it just happen with this particular instance

**Comment by Hausmeister486** [comment]
I am not sure if I understand and answer your question correctly.

I manage about 180 recipes from Hellofresh in Paprika, Hellofresh recipes are by default always designed for 2 servings, the Paprika importer makes 2 servings then incorrectly 1 serving.  This happens with all 180 recipes.

The other problem is the incorrect assignment of the different time specifications, also in all 180 recipes.

With a direct import from Hellofreh to Tandoor everything is correct.

**Comment by vabene1111** [comment]
ok, understood, do you have any other recipes in paprika that are not from hellofresh ? or can you create one and import that to tandoor and see if thats also broken ?

**Comment by Hausmeister486** [comment]
These are two examples how the Paprika export looks like in json format. 

![RW_Rezept](https://user-images.githubusercontent.com/76865047/153057132-4c69e0d3-49b3-40f0-9030-e236b7e58baf.png)

![HF_Rezept](https://user-images.githubusercontent.com/76865047/153057172-4d7e9f72-6b82-45f9-91eb-217fa9198c54.png)

**Comment by vabene1111** [comment]
ok thanks, i will look into this :+1:

**Comment by Hausmeister486** [comment]
These are the recipes imported in Tandoor 

![RW_Rezept_tandoor](https://user-images.githubusercontent.com/76865047/153060197-5e93e349-413a-457d-8e13-bb9afc0c5250.png)

![HF_Rezept_Tandoor](https://user-images.githubusercontent.com/76865047/153060227-3e24456d-724c-4b7f-943d-d2b43b3f1efa.png)

**Comment by vabene1111** [comment]
i have very limited test data for paprika but this should be fixed in the next release. If not please open a new issue and provide a sample paprika file either on github or via email info@tandoor.dev
