### ISSUE TITLE
Pre-Sets of Units and Ingreedients

### ISSUE THREAD

**Issue by murphy83** [TandoorRecipes/recipes#1487]
### Is your feature request related to a problem? Please describe.

Just discovered this nice piece of software and started inserting the first of my recipes. Works great, and over time the amount of selectable units grows, same goes for the ingredients.
This is a bit tedious and time consuming for new users.

### Describe the solution you'd like

What I really would like to have is an import function of some "basic" units and ingredients, maybe even with translations, and maybe even with prefixes know such as:
1000 g = 1kg
1000 ml = 1l

For sure the basic set would only be a basic set, if you need specific units or ingredients not along the basic line you will need to add those, but I think everyone will insert the "basic" units like g, kg, tbsp. etc. as well as the "basics" in almost every kitchen such as salt, pepper, flour, sugar, potatoes.

### Additional context

I did not look into the database model yet, but I think this could be done with simple "Update-Statement-File"

### Contribute

- [X] Yes
- [X] Partly
- [ ] No

**Comment by vabene1111** [comment]
this is rather hard to do for an international project as every country has its own "rules" in the kitchen so we decided at some point that providing a standard set would likely not help much as everyone has different preferences (start for example with tbsp. vs. tablespoons) and also different preferences regarding pluralization. 

it is however planned to add unit conversion #495 which will likely use the pint library. They have spent much time thinking about units so when implementing this feature we might take a look at if it makes sense to provide their unit table as a default set of units. 

thanks for the idea/feedback tough
