### ISSUE TITLE
comments on units and foods get lost on updating recipes

### ISSUE THREAD

**Issue by zhankuun** [TandoorRecipes/recipes#1493]
### Tandoor Version

1.0.7

### Setup

Synology

### Reverse Proxy

Others (please state below)

### Other

nginx:mainline-alpine

### Bug description

Scenario:
- user 1 is editing a recipe
- user 2 is adding a comment to a food or unit which is used in the recipe edited by the user 1.

- user 2 saves the comment which is also visible. 
- later user 1 saves the recipe. 

 Now the comment on the food/unit made by user 2 is lost.

**Comment by vabene1111** [comment]
there is no locking mechanism implemented in tandoor that would prevent editing and live syncing changes between clients is kinda out of scope for such a "small" project so this behaves like most multi client applications behave, it just overrides what someone else did before. 

This is not good and maybe we can implement a warning of sorts but properly fixing this is out of scope for the current and mid to long term future of this project. 

but thank you for reporting this 👍
