### ISSUE TITLE
Minor change: Rename "Cookbook"

### ISSUE THREAD

**Issue by bodagrave** [TandoorRecipes/recipes#1494]
### Is your feature request related to a problem? Please describe.

For new users, it is a bit confusing to distinguish between "cookbook" and "book". This is also mentioned in a German article of one of the most popular IT magazines:

["Etwas verwirrend ist die Benennung einer weiteren Funktion: Unter dem Menüpunkt „Bücher“ können Sie Rezeptsammlungen wie „Gesunde Küche“ anlegen und darin Rezepte einfügen."
](https://www.heise.de/select/ct/vorschau/2135712173833025969)

Translated it would mean: "somewhat irritating is the name of another function [as for we have cookbook already]: at the menu entry "Books" you can create collections of recipes like "wholesome cuisine" and add recipes there."

### Describe the solution you'd like

I'd suggest using another Name for "cookbook". Having all my recipes together in my shelf, this would not be a cookbook, but a collection of all sorts of paper. Back covers of some food packages with recipes, books, folder, loose sheets and so on (at least, this is what it looks like with me ;-) ).
Having this in mind I would more likely speak of "recipes" instead of cookbook.
On the other hand a collection of recipes with a special theme (like "vegetarian cuisine" or "desserts") in my opinion would definitively fit better in a book.

So other like the mentioned article of the magazine I think the renaming of "cookbook" to "recipes" would make the function of "books" more clear and thus easier to understand for new users.

### Describe alternatives you've considered

Calling the menu entry "Collection" would also work, I think.

### Contribute

- [ ] Yes
- [X] Partly
- [ ] No

**Comment by vabene1111** [comment]
very interesting, i have spend thousands of hours working on this and have never thought about this 😂 but you are right, its confusing, just making the "home" page "recipes" makes much more sense. Thanks for reporting
