### ISSUE TITLE
Error when sharing recipe

### ISSUE THREAD

**Issue by solaris7590** [TandoorRecipes/recipes#1500]
### Tandoor Version

1.0.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

Creating a URL for sharing a recipe workes fine, but after entering the sharing link in icognito mode (where I'm not signed in), the following Error appears `Not Found There was an error loading a resource! {"detail":"Nicht gefunden."}`.

**Comment by solaris7590** [comment]
Something like that? Or do you need the exact URL?

https://xxxx.net/view/recipe/42/a4b5ef40-dfac-4bc7-b14e-691a102a888c

**Comment by vabene1111** [comment]
no thats ok, just wanted to make sure you are copying the correct link. This seems to indeed be an issue with the latest upate, i will review and fix it asap.

**Comment by vabene1111** [comment]
ok i found the issue and added a fix, thanks for reporting
