### ISSUE TITLE
Import of Chowdown recipes from zip-file ignores all files with parentheses or umlauts in file name

### ISSUE THREAD

**Issue by haeuslein** [TandoorRecipes/recipes#1506]
### Tandoor Version

1.0.5.2

### Setup

Synology

### Reverse Proxy

Others (please state below)

### Other

Synology DSM built-in

### Bug description

Bulk import of chowdon recipes from zip-file fails if the individual recipe file names contain special characters like "()öäüß" - I have not tested with more than these, but these are reproducible. This only happens when going via the zip-file - individual upload of the problematic files works just fine.

Steps to reproduce:
1. Create a chowdown-style recipe and name the file "söme_recipe.md"
2. Add file to Chowdown-style zip-file (Recipes.zip/_recipes/söme_recipe.md)
3. Upload to Tandoor via web interface
4. 0 recipes imported

**Comment by vabene1111** [comment]
thanks for reporting, this is likely due to the file name filtering not including such charactes, i will fix this

**Comment by haeuslein** [comment]
My pleasure, thank you for the quick response!

**Comment by vabene1111** [comment]
![image](https://user-images.githubusercontent.com/6819595/155878834-2de1cbd3-842c-4985-8107-df1bebf71514.png)
updated the regex, should be fixed in next version
