### ISSUE TITLE
Wrong servings number after logging a cooking

### ISSUE THREAD

**Issue by phu77** [TandoorRecipes/recipes#1514]
### Tandoor Version

1.0.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

After a cooking is logged, the serving number appears of the logged item appears, but the quantities of the ingredients are still based of the old serving number. It should taken the serving number of the of the receipe not of the logged value.

Steps to reproduce:
- Create a receipe with 4 servings
- Log the cooking with 6 servings
=> Failure: The receipe now shows with 6 servings, but with calculation of 4 servings

**Comment by vabene1111** [comment]
this is actually the intended behavior, because you log the cooking and tell the system "i got 6 servings out of this" so it will show you the 6 servings as a base. But this is confusing and was discussed at some point that we need to change it, just not decided yet how to do so.
