### ISSUE TITLE
Meal plan 'add to shopping' remains checked in modal when enabling Auto Add mode

### ISSUE THREAD

**Issue by 0utl4w** [TandoorRecipes/recipes#1521]
### Tandoor Version

1.0.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When adding a meal to the meal plan and let it also add to the shopping list the recipe is added twice to the shopping list and you have 2 entries under the recipes tab
[Bug_Meal_plan_shopping_list.pdf](https://github.com/TandoorRecipes/recipes/files/8040518/Bug_Meal_plan_shopping_list.pdf)
.

**Comment by vabene1111** [comment]
thats very interesting, i cannot reproduce this behavior neither on the hosted instance nor on my personal one. Can you post some information about the recipe content and your setup ?

**Comment by 0utl4w** [comment]
The behaviour occours with every recipe I have, so it should not depend on the recipe, I guess.
Here you see the settings of my shopping-list. The only "special" thing is maybe that I share it with another user.
![image](https://user-images.githubusercontent.com/80005700/153407584-74ad3e56-214a-4a32-90d0-d53937f9135e.png)

About my setup, Tandoor under Docker on a Raspi 3B+ (aarch64) with dietpi installed. Do you need more info? Any logs I can provide?

**Comment by smilerz** [comment]
How are you adding the meal pan to the shopping list?

**Comment by 0utl4w** [comment]
Automatically (see the screenshot "Auto Add Meal Plan")

**Comment by smilerz** [comment]
Can you disabled 'Auto Add' and add an entry to meal plan and tell me if the 'add to shopping list' checkbox is checked by default?

**Comment by smilerz** [comment]
Short term - you can uncheck it and re-enable Auto Add.

**Comment by 0utl4w** [comment]
Oh, wow, it was interpreted as 2-checks... once in the wizard when adding a recipe to the meal plan, that is hidden, when the "Auto Add" is active and once more when "Auto Add" is enabled.... 

Thanks again for your quick replies
