### ISSUE TITLE
Public link doesn't work

### ISSUE THREAD

**Issue by ToLaTE4u** [TandoorRecipes/recipes#1522]
### Tandoor Version

1.0.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

1. Create a recipe
2. Try to share recipe to your friend via link share
3. Friend can not view recipe.
4. The following error message shows up in the bottom right:
-->There was an error loading a resource! {"detail":"Nicht gefunden."}

I've found out that when the other person logs in with my credentials then the share link will work.

**Comment by vabene1111** [comment]
yes this was an issue in 1.0.7 :)
