### ISSUE TITLE
food parent `On hold`

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1524]
### Is your feature request related to a problem? Please describe.

I have defined spices as parent and set it to `On hand`.
`On Hold` is not inherited by the children.

### Describe the solution you'd like

Inheritance for `On Hold`

### Contribute

- [ ] Yes
- [ ] Partly
- [ ] No

**Comment by smilerz** [comment]
On hand isn’t intended to be inherited. It’s an attribute you toggle when it is used/purchased. If you never want to manage it at the individual level mark it as ignore shopping.
