### ISSUE TITLE
keep restarting

### ISSUE THREAD

**Issue by lidans5** [TandoorRecipes/recipes#1526]
### Issue

I'll be great full for some help I followed the pdf guide for my synology (ds220+) and the "Web Application Container (Tandoor_Web)" keeps stopping and restarting, when "Start the Containers" phase thx

### Tandoor Version

pg ver 11.4 ??

### OS Version

DSM 7.0.1-42218

### Setup

Synology

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Environment file

```shell
I don't know where to find
```

**Comment by MaxJa4** [comment]
Without any logs/info at all, we can't really help here I'm afraid.
Try to get the logs from the web container by connecting to your NAS via SSH and get logs via `docker logs` followed by the container name (e.g. recipes_web_recipes_1). Please then edit your issue above and paste it into the section "relevant logs". Thanks.

**Comment by smilerz** [comment]
Also include a copy of the configuration. (Container->export)

**Comment by lidans5** [comment]
Well in the mean time I'm struggling getting the log file
can't get permission to the Docker folder..
thx for your help

**Comment by smilerz** [comment]
It’s in the UI in container details.

**Comment by lidans5** [comment]
ok found it, what lines should I remove?

**Comment by smilerz** [comment]
obfuscate anything that is sensitive to you: hostname, secrets, passwords

**Comment by smilerz** [comment]
> ok I can allready see a problem before I upload it I get an error for: asia/jerusalem timezone, to what should I chane it?

Asia/Jerusalem is correct - you can also try IL

**Comment by lidans5** [comment]
does it matter upper/lower case?

**Comment by smilerz** [comment]
> does it matter upper/lower case?

don't know for sure, but most things in linux/databases do

**Comment by lidans5** [comment]
[Tandoor_DBjson.docx](https://github.com/TandoorRecipes/recipes/files/8049137/Tandoor_DBjson.docx)
[Tandoor_Proxyjson.docx](https://github.com/TandoorRecipes/recipes/files/8049138/Tandoor_Proxyjson.docx)
[Tandoor_Web.docx](https://github.com/TandoorRecipes/recipes/files/8049139/Tandoor_Web.docx)
[Tandoor_Proxy.docx](https://github.com/TandoorRecipes/recipes/files/8049140/Tandoor_Proxy.docx)
[Tandoor_DB.docx](https://github.com/TandoorRecipes/recipes/files/8049141/Tandoor_DB.docx)
[Tandoor_Webjson.docx](https://github.com/TandoorRecipes/recipes/files/8049142/Tandoor_Webjson.docx)

**Comment by smilerz** [comment]
The username/password on either the DB or the Web is wrong.

`django.db.utils.OperationalError: FATAL:  password authentication failed for user "Cookbook" `

**Comment by lidans5** [comment]
changed the password still have problem
[Tandoor_Proxy(2).docx](https://github.com/TandoorRecipes/recipes/files/8054078/Tandoor_Proxy.2.docx)
s

**Comment by smilerz** [comment]
`nginx: [emerg] host not found in upstream "Tandoor_Web" in /etc/nginx/conf.d/default.conf:14 `

Either the name Tandoor_Web is wrong, the web service isn't started or the web server isn't accessible to the proxy server on the shared network.

**Comment by lidans5** [comment]
no it's not started because in the pdf it says to wait a minute between starting them, but even when I start all of them in the same time I get the same problem - restart
any case the Tandor_web does the same problem restarting, I know there is the line error with the password but I copy paste, what else I can do?
[Tandoor_Web.docx](https://github.com/TandoorRecipes/recipes/files/8054156/Tandoor_Web.docx)

**Comment by smilerz** [comment]
If the db was created with the wrong username/password it needs to be deleted and recreated `/docker/Tandoor/db`

Make 100% sure that username passwords are identical and don't have any leading/trailing spaces.

**Comment by lidans5** [comment]
thank you, now everything works
I have a little confusion. when finishing the Update TROI section phase 6. i find four containers:
![image](https://user-images.githubusercontent.com/66837329/153725373-3c6f9d6f-d720-442a-a71f-bf81173a7e9d.png)

**Comment by smilerz** [comment]
The 1.0.8 is probably duplicate. But it might be the other one.  Try stopping them 1 at a time the one that you can turn off and still use the app can be deleted.
