### ISSUE TITLE
Configurable decimals in shopping list

### ISSUE THREAD

**Issue by fastFox2** [TandoorRecipes/recipes#1529]
### Describe the solution you'd like

Currently, on teh shopping list ingridients have to decimals. In my oppinion it would be better to make this configurable, like the ingredients in the recipes. Maybe this can even use the same setting?

### Contribute

- [ ] Yes
- [ ] Partly
- [ ] No

**Comment by fastFox2** [comment]
Maybe, I'll be willing and able to contribute to that feature myself, but that's a big maybe. If this becomes the case, I'll update the checkmarks.

**Comment by vabene1111** [comment]
i think it happes quite often that an ingredient has a decimal place (1,5kg of steak, 0,5 L or gallons or whatever of milk) so i dont think removing decimals from the shopping list makes sense. It also does not show decimals for ingredients that dont have any decimals (at least in the new shopping list) so this should not be a problem either. I think you might be using the old shopping list were it was always shown, we improved that in the new one that will likely be made the default with the next release.

**Comment by fastFox2** [comment]
Yes, I'm still using the old version, I'm in the process of updating right now. When I looked over the changes in the new shopping list I didn't see it. And thanks for the response.
