### ISSUE TITLE
Step images (step.file) only show png files

### ISSUE THREAD

**Issue by FHantke** [TandoorRecipes/recipes#1545]
### Tandoor Version

1.0.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

The following line only checks png files, all other checks reference the false path. As a result, only PNG images are shown in the steps.
https://github.com/TandoorRecipes/recipes/blob/de1efcb81e43ef35ae7157ddf3e9c74cd43e45dd/vue/src/components/StepComponent.vue#L57

**Comment by vabene1111** [comment]
thanks for reporting :+1:
