### ISSUE TITLE
Jump to "select food" does not work with pressing TAB

### ISSUE THREAD

**Issue by wall121** [TandoorRecipes/recipes#1546]
### Tandoor Version

1.0.8

### Setup

Synology

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

If you add ingredients you can jump from Number to unit by pressing tab, but not from unit to "Select food". Neither does Enter work.
Would make adding ingredients much easier form the workflow if the logic would be always the same

However: Thx for this great solution

### Relevant logs

```shell
no log
```

**Comment by vabene1111** [comment]
yes this needs to be fixed, if the library we are using allows this behavior. Currently you have to press enter then tab. 

There is an open issue ragarding this already, so i am closing this #1305
