### ISSUE TITLE
Cannot use Meal Plan with multiple Accounts

### ISSUE THREAD

**Issue by tknaller** [TandoorRecipes/recipes#1549]
### Tandoor Version

1.0.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Sharing Meal Plan Items via the default sharing settings works as described in #1338

but: one can only edit  their own entries and not someone else's, doesn't matter whether users are admin, superadmin, sharedWith, ...

**Comment by vabene1111** [comment]
fixed in the next release
