### ISSUE TITLE
Massimport of HTML/JSON files

### ISSUE THREAD

**Issue by codac** [TandoorRecipes/recipes#1553]
### Is your feature request related to a problem? Please describe.

I have a huge amount of recipes in HTML/JSON format that I would like to import.
Currently I need to open a HTML file copy the code and paste it into the import window of Tandoor Recipes.

### Describe the solution you'd like

I would like to drag and drop a list of HTML/JSON files to that window, so that Tandoor Recipes imports them automatically one after another and reads the content of the provided files with out the need oy copy and paste it.

### Describe alternatives you've considered

/

**Comment by vabene1111** [comment]
that highly depends on the format of you html/json files. If they come from a certain application we can build an application importer. I also want to build some kind of generic importer at some point but that will be some time in the future. 

Definitely need more information about whats in your files.

**Comment by codac** [comment]
This is one Json Example.
It would be nice to define the mapping one time before importing and then just import all files the same way.

The application behind it is [Cookidoo.com](https://cookidoo.co.uk)

```
{
   "id":"12345",
   "language":"de-DE",
   "title":"YummyRecipe",
   "rating_count":"123",
   "rating_score":"2.1",
   "tm-versions":[
      "tm6",
      "tm5"
   ],
   "Schwierigkeitsgrad":"medium",
   "Arbeitszeit":"20 Min",
   "Gesamtzeit":"1 Std. 15 Min",
   "Portionen":"2 St\u00fccke",
   "ingredients":[
      "100 g Butter, weich",
      "\u00bd TL Salz",
      "200 g Emmentaler, in St\u00fccken",
      "\u00bc TL Pfeffer"
   ],
   "nutritions":{
      "n\u00e4hrwerte":"pro 1 st\u00fcck",
      "brennwert":"1234 kj / 123 kcal",
      "eiwei\u00df":"12 g",
      "kohlenhydrate":"12 g",
      "fett":"12 g",
      "ballaststoffe":"1.2 g"
   },
   "steps":[
      "Step 1 Description",
      "Step 2 Description"
   ],
   "tags":[
      "nice",
      "deutsch",
      "yummy",
   ]
}
```

**Comment by vabene1111** [comment]
hmm export from cookiedoo is a little tricky, dont want to get into any copyright issues here. Easiest thing to do (as you likely already have a script to dump those json files) is to just add a second part to that script to pump those files into tandoor. 

You can use the undocumented `api/ingredient-from-string/` (post body `text` in json)endpoint to convert those ingredients into tandoor compatible splitted ones, and then send them to /api/recipe (which is documented) to create the recipes. 

But a mapping import feature is definitely something i want to do at some point.
