### ISSUE TITLE
Version Info in non Docker Deployment

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#156]
Since the version number is only packed in the image at release, deployments not using docker will not contain a version number.

**Comment by smilerz** [comment]
maybe save version number in the DB and do a migration with each release?

**Comment by vabene1111** [comment]
would be an option .. but i fear that everything except tags or some kind of automation will lead to me forgetting to change the number. But i am sure that there is some way to automate this, maybe with an automated commit or so.

**Comment by sebastian0511** [comment]
...or what is with a file like XML or JSON with the version number and changelog in it.
It would deploy with every update and overwrite the existing. The gui load this file an display it and with this way you see directly the version and changelog in all ways of deployment.
And you have of course the ability to automate this with the automated commit or whatever.

**Comment by mfeurer** [comment]
Would this entail that the version number is shown on `https://app.tandoor.dev` or would this be a separate issue (if it does not exist yet, I'd be happy to open it)?

**Comment by mfeurer** [comment]
> The system page should also not be visible for non superuser users (which i just fixed) although it does not contain any kind of sensitive data.

Sorry, I don't fully understand your answer. What I would basically like to know is: "as a regular user, can I find out which version is running on `https://app.tandoor.dev`" and "if not, does this issue add such version information".

**Comment by vabene1111** [comment]
ok now i understand: 

1. A regular user cannot see any version information at the moment
2. this issue does not add this information as i dont think this is benefitial to the user. Also the hosted version might run special hotfix branches from time to time so it would not really work anyway as long as this issue is not resolved. 

generally speaking the hosted version (currently) always gets the latest release when its released or a few days after that. In the future there might be some kind of more stable branch that will get the latest update lets say 2-3 weeks after the main branch so that its generally more stable. But currently development is to fast/unstable to do this.

**Comment by vabene1111** [comment]
the next version will include a version iformation page based on commit refs
