### ISSUE TITLE
Manual import redirects to 'null'

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [TandoorRecipes/recipes#1563]
### Tandoor Version

1.0.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Using drag and drop within the manual import function causes Mozilla Firefox to open the page 'null'. Doing the same using Chrome works as expected.

Please see the attached video:
https://user-images.githubusercontent.com/20322801/154839290-2b8bb1f8-204e-4c3d-a26a-fc09dbe97797.mp4

I tried the same within a new Firefox profile without any addons but this caused the same problem. Firefox version is 98.0b3

The site I tried to import was this one: https://ich-liebe-kaese.de/rezepte/ueberbackene-hackbaellchen-mit-kaese-vom-blech/

**Comment by vabene1111** [comment]
have i mentioned that i hate firefox 😂 but the importer is being reworked anyway and i will make sure to test this in firefox as well then. Not sure if we are going to fix this for the existing importer. @smilerz what do you think, any idea why this could fail in firefox. I dont think we should spend too much time on this.

**Comment by smilerz** [comment]
> have i mentioned that i hate firefox 😂 but the importer is being reworked anyway and i will make sure to test this in firefox as well then. Not sure if we are going to fix this for the existing importer. @smilerz what do you think, any idea why this could fail in firefox. I dont think we should spend too much time on this.

Not even a guess

**Comment by vabene1111** [comment]
Ok, this will be fixed with the new importer
