### ISSUE TITLE
Allow user to log into multiple spaces

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#1569]
allow a logged in user to be assigned rights to multiple spaces (user/guest/admin as per space admin preferences)

**Comment by vabene1111** [comment]
Yes, this has long been on my whish list but requires substantial work in the permission system which needs to be carefully planned and even more carefully executed and tested.

In the end I would like to habe

A a space switcher somewhere in the nav
B maybe even a combined list of search results


I would also like to use that opportunity to add further depth to the permission system (e.g. Individual permissions for feature like shopping, planning,..)
