### ISSUE TITLE
Ingredients are not calculated

### ISSUE THREAD

**Issue by hyperbit00** [TandoorRecipes/recipes#1573]
### Tandoor Version

1.0.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

![image](https://user-images.githubusercontent.com/16324569/155325246-a7b0fe00-666c-49b2-ad52-a5d00cdeb859.png)
As you see in the image the ingredients are not calculated.
Only the Last Amount is shown in the upper list.
10+50g Olivenöl should be 60g

**Comment by smilerz** [comment]
duplicate #1325
