### ISSUE TITLE
Ingredients doubled on shopping v2

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#1575]
couldn't reproduce myself but on my firends phone the shopping list i created was suddenly duplicating the amout of ingredients for all recipes and manually added entries.

This happend once for no apparent reason and once after trying to manually add an ingredient. 

Maybe a second API request not merging but adding to the ingredients 🤔 if it happens again i will look at the details

**Comment by vabene1111** [comment]
![image](https://user-images.githubusercontent.com/6819595/155507497-c05c7cd8-e577-47c1-ab73-793e97af0450.png)

ok its as i thought, the entries are loaded twice fro some reason, dont know what triggers this issue yet

**Comment by smilerz** [comment]
Does the 2nd entry persist if you reload the page?

**Comment by vabene1111** [comment]
no they are gone, haven't found a way to reproduce this yet but maybe it has something to do with this being on the account the entries are shared with not the one that was originally used to create them

we had some strange problems recently as well when we were shopping that the auto sync appeared to not be working even tough it was before but i wasn't sure if the internet was just bad

**Comment by smilerz** [comment]
> we had some strange problems recently as well when we were shopping that the auto sync appeared to not be working even tough it was before but i wasn't sure if the internet was just bad

Does it happen while shopping and the item was created during the shopping trip?

**Comment by vabene1111** [comment]
i think it happend before, i created the list form my work pc and when opened on mobile by shared user it happend a few time but since i was not there i could not figure out what exactly triggered it. will test wit multiple accounts on deskop i feel like this is likely share related
