### ISSUE TITLE
Better error message why recipe can't be saved

### ISSUE THREAD

**Issue by Micha10** [TandoorRecipes/recipes#1590]
### Tandoor Version

latest 2022-02-27 git pull

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

After editing a new recipe, I want to save. A red error is displayed "Beim Aktualisieren einer Ressource ist ein Fehler aufgetreten", but no further hint why.

In the developertools the answer of the request is
```
{"nutrition":{"carbohydrates":["A valid number is required"],"fats":["A valid number is required"],"proteins":["A valid number is required"]}}
```

After removing letters after the nutrition data the recipe could be saved.

Most users will not find the reason, so please show a meaningful error-message
i.E. displaying a red border around the wrong fields

**Comment by vabene1111** [comment]
thanks fore reporting, this is definitely an issue but was not handled yet since multiple front end libs were used for API requests in whcih error responses looked differently. Since almost everything is unified now this will be handled under issue #682
