### ISSUE TITLE
[Beta][New Shopping List] Can't create new supermarket category

### ISSUE THREAD

**Issue by MaxJa4** [TandoorRecipes/recipes#1592]
### Tandoor Version

Develop / Beta (089e634)

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

Local dev

### Bug description

1. Supermarket categories are empty
2. Create a new entry
3. New entry is added but no name is shown (not even after reload)
4. No other entries can be added, until the single broken one is removed

![image](https://user-images.githubusercontent.com/74194322/155900208-2808afba-a1ce-44e5-8465-082cea09beab.png)

Also no name in the shopping list itself:
![image](https://user-images.githubusercontent.com/74194322/155900451-f038e44e-d129-422b-abed-da1e952dd8ca.png)

**Comment by vabene1111** [comment]
thanks, will look at this before releasing the new version
