### ISSUE TITLE
[Beta][New Shopping List] Supermarket's edit button triggers category edit instead

### ISSUE THREAD

**Issue by MaxJa4** [TandoorRecipes/recipes#1593]
### Tandoor Version

Develop / Beta (089e634)

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

Local dev

### Bug description

1. Create one or more supermarkets
2. Click on edit icon to change name of the supermarket for example
3. Only right column (shopping categories) switch to edit mode (or drag&drop sorting mode rather), supermarkets on the left can't be edited

![image](https://user-images.githubusercontent.com/74194322/155900340-255f347e-c866-4c84-8bdf-3f4b6089f620.png)

**Comment by smilerz** [comment]
This would be a feature request.  Currently the editing of existing SM is via the briefcase menu at the top right.

**Comment by MaxJa4** [comment]
Then the edit symbol should be removed, shouldn't it? Or rather moved to the shopping categories, since they are being triggered for editing when pressing that button anyway.

**Comment by smilerz** [comment]
It’s editing the categories. But I agree it isn’t super intuitive.  
It will be updated.

**Comment by vabene1111** [comment]
the whole page is functional but not intuitive, there also needs to be some convenience things like select all or deselect all i think.

**Comment by vabene1111** [comment]
closing and moving this onto the shopping v2 todo list
