### ISSUE TITLE
Cryptography dependencies

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#1609]
verify that 36099b80abf884346aaba123c0ae9ba5da9aa56f does not have any negative consequences (see this SO post https://stackoverflow.com/questions/50619166/docker-installing-python-cryptography-on-alpine-linux-distribution)

if everything is fine remove all dependencies no longer needed in dockerized build

**Comment by MaxJa4** [comment]
Maybe some runtime dependencies (upper ones) from the Dockerfile beginning can be moved to the build dependencies (lower ones) down below too, which would reduce image size further.
But most important is probably making it work right now, so 1.1.0 can go live I suppose.

**Comment by vabene1111** [comment]
interestingly i tought that removing cryptography would help because i added it as a OS package but one of the libs seems to require a specific version not satisfied by the py-cryptography package. So will need to try a bit more i guess.

**Comment by vabene1111** [comment]
ok only arm v7 build thats failing, released with just x86 and arm 64 for now, working on arm v7 (testing with beta image)
