### ISSUE TITLE
Merge Ingredients

### ISSUE THREAD

**Issue by obi134** [TandoorRecipes/recipes#1629]
### Is your feature request related to a problem? Please describe.

If I create a recipe with different steps and add ingredients for each step, on the top of recipe the complete list of ingredients is shown. But some are shown twice when used in multiple steps:

**Steps:**
![steps](https://user-images.githubusercontent.com/6304830/156923115-42c102a9-de96-4713-817f-3716ef554724.jpg)

**Ingredient list:**
![ingrediants](https://user-images.githubusercontent.com/6304830/156923125-8e728922-15a5-4ad5-9890-9170f81e70d7.jpg)

### Describe the solution you'd like

Would it be possible to merge the ingredients if they are the are of the same type (Prise) and description (Salz) and add the amounts?

**Comment by smilerz** [comment]
duplicate #1325
