### ISSUE TITLE
Support for Cooking Professionally's Recipe Import

### ISSUE THREAD

**Issue by boomhaur** [TandoorRecipes/recipes#1630]
### Is your feature request related to a problem? Please describe.

Tandoor will not import recipes from the [Cooking Professionally](https://cookingprofessionally.com/) site and provides the following error:

_There was an error loading a resource!{"error": true, "msg": "The requested site provided malformed data and cannot be read."}_

### Describe the solution you'd like

I'd like Tandoor to support imports from Cooking Professionally since it's my primary source of recipes.

It would also be helpful if Tandoor provided a list somewhere of links to recipe sites that it supports.

### Describe alternatives you've considered

Finding a site with similar recipes to the ones on Cooking Professionally that will import but that's not ideal.

**Comment by smilerz** [comment]
You can find a list of supported sites [here](https://github.com/hhursev/recipe-scrapers#scrapers-available-for).  You can also request sites be added on that project.

From a cursory glance it looks like that site provides structured data, though in a non-standard format so can probably be implemented.
