### ISSUE TITLE
[suggestion] Youtube import?

### ISSUE THREAD

**Issue by adrianmihalko** [TandoorRecipes/recipes#1631]
### Describe the solution you'd like

It would be great to have a feature to import recipes from Youtube? 

My idea:

- import video's thumbnail as recipe image 
- import description of the video (many times the ingredients and instructions are listed here)
- add link to the youtube video to description

I follow many BBQ channels on Youtube and I want to add recipes from there. It often happens that I like a recipe on the video, but I don't know where to save it. If we could just save a picture and a link to the video to the recipes, that would be great.

**Comment by vabene1111** [comment]
that makes sense, as youtube is a large platform we could justify writing a special case for the improter for this. i like the idea, thanks 👍

**Comment by vabene1111** [comment]
maybe you can even load the embed url of the video and embed it in markdown, not sure if that is within spec

**Comment by tomtjes** [comment]
You could also try and grab the subtitles and add them to the recipe, just in case the video description doesn't contain the cooking instructions.

**Comment by parkroland** [comment]
Hi all, I think I'm going to give this one a shot.
