### ISSUE TITLE
XHR requests not using the correct port

### ISSUE THREAD

**Issue by jonahwh** [TandoorRecipes/recipes#1632]
### Issue

I have an installation of Tandoor that's accessible both in and outside of my firewall.

Inside my LAN it's accessible at: `https://subdomain.mydomain.com`
Outside my LAN, it's accessible at: `https://mydomain.com:35000`

The `https://subdomain.mydomain.com` works fine. If I try to access the site from `https://mydomain.com:35000`, it _mostly_ works, except all the XHR requests from the Javascript drop the port, so they try to request `https://mydomain.com`, which obviously fail.

This didn't always use to be the case, so something changed at some point, but I'm not sure what or when - the external version is rarely accessed.

If I have to stop using the LAN domain so that I can somehow force the port to be added to the XHR requests, that's fine, but I'm not sure if that's even possible. This feels like a bug, because the site and assets load, but XHR requests fail because they drop the nonstandard port.

<img width="668" alt="Screen Shot 2022-03-06 at 7 57 29 PM" src="https://user-images.githubusercontent.com/794237/156965553-6c3f0188-2b4b-4529-bce6-b52697a2dcc2.png">

nginx config:

```
server {
  server_name subdomain.domain.com;

  location /media/ {
    alias /recipes_mediafiles/;
  }

  location / {
    proxy_pass http://web_recipes:8080;
    include /config/nginx/proxy.conf;
    proxy_set_header Referer $scheme://$host;
  }

  listen 35000 ssl http2;
  listen [::]:35000 ssl http2;
  include /config/nginx/ssl.conf;
  client_max_body_size 16M;
}
```

### Tandoor Version

1.1.2

### OS Version

Debian 10

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx (I'm using SWAG but custom nginx config)

### Environment file

```shell
I'm not using a .env file, setting environment variables manually in docker-compose.
```

### Docker-Compose file

```shell
x-common:
  &common
  dns:
    - 172.16.238.200
  logging:
    driver: syslog
    options:
      syslog-address: "udp://host.name:12345"
      tag: "{{.Name}}/{{.ID}}"
  networks:
    - proxy-net
  restart: unless-stopped
  labels:
    - "diun.enable=true"
  profiles: ["standard"]

  web_recipes:
    image: vabene1111/recipes
    volumes:
      - /home/username/services/recipes/staticfiles:/opt/recipes/staticfiles
      - /home/username/services/recipes/nginx_config:/opt/recipes/nginx/conf.d
      - /home/username/services/recipes/mediafiles:/opt/recipes/mediafiles
    ports:
      - 8080
    depends_on:
      - postgres
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
      - DEBUG=0
      - GUNICORN_MEDIA=0
      - DB_ENGINE=django.db.backends.postgresql
      - SECRET_KEY=${RECIPES_SECRET_KEY}
      - TIMEZONE=America/Los_Angeles
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${RECIPES_DB_NAME}
    <<: *common
    networks:
      proxy-net:
        ipv4_address: 172.16.238.111

  postgres:
    image: postgres:12
    container_name: database
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${RECIPES_DB_NAME}
    volumes:
      - /home/username/services/postgres/data:/var/lib/postgresql/data
    <<: *common
```

**Comment by smilerz** [comment]
you aren't setting the custom port as part of the header
`proxy_set_header Referer $scheme://$host;`

**Comment by jonahwh** [comment]
Hm. I don't think this is an nginx issue because it's the requests initiating from the browser that are being made without including the port.

Regardless, I tried that, and it doesn't seem to make any difference.

**Comment by smilerz** [comment]
it is 100% an nginx issue.  Django requires properly formatted headers to function correctly.

**Comment by jonahwh** [comment]
Hm. Do you know which header would be controlling the hostname:port used for XHR requests? Maybe I can dig around and see if there's anything that jumps out at me.
 

Like I said, the reverse proxy seems to be 100% functional - it's just the XHR requests, which aren't even making it to nginx, because they're hitting the wrong port - `443` instead of `35000`.

**Comment by smilerz** [comment]
urls are constructed server side based on the headers.  if django doesn't know that the client is connecting on a custom port it won't append port to any of the server-side constructed urls.

**Comment by jonahwh** [comment]
Alright, I'll look through the documentation again and see if I can figure anything out.

**Comment by smilerz** [comment]
If you go to /system/ there is a list of headers that Django sees.  For your config you will know it is setup correctly if you see
HTTP_HOST: mydomain.com:35000

**Comment by jonahwh** [comment]
Makes sense - that's only showing the hostname without the port.

**Comment by smilerz** [comment]
Wish I could be more helpful.  You can try the discord channel to see if anyone else has their proxy set with a custom port.

**Comment by jonahwh** [comment]
Ok this is resolved! Thanks for getting me on the right path. I just needed to fix the `HTTP_HOST` header. Adding this line to my nginx config was all that was needed:

`proxy_set_header Host $host:$server_port;`
