### ISSUE TITLE
Categorising ingredients used for different components of a recipe

### ISSUE THREAD

**Issue by ExodosPavilion** [TandoorRecipes/recipes#1636]
### Is your feature request related to a problem? Please describe.

Sometimes the recipe websites will split their ingredients into separate parts so that we know what ingredients are used in which part. Take for example these 2 websites for [Chilli Cheese Paratha](https://www.mobkitchen.co.uk/recipes/chilli-cheese-paratha) and [Chicken Chow Mein](https://www.joshuaweissman.com/post/the-cheapest-noodle-dish-ever-chicken-chow-mein-but-cheaper). In the first one they split the ingredients for _The Dough_ and _The Filling_, in the second one they split the ingredients for _Sauce_ and _Noodles_. Far as I can tell tandoor has no way of doing this.

### Describe the solution you'd like

A way to split the ingredients depending on what it will be used for. So it can be something like; category: sauce, ingredients:[...], category: noodles, ingredients:[...].

### Describe alternatives you've considered

I did consider putting these in their own recipe, but abandoned the idea cause it would make no sense to me even with keywords linking them. 

### Additional context

Just a heads up both the sites in the example don't work with tandoor's URL import feature. For this one, [Chilli Cheese Paratha](https://www.mobkitchen.co.uk/recipes/chilli-cheese-paratha), at least I can import and manually alter the things, but for the other one, [Chicken Chow Mein](https://www.joshuaweissman.com/post/the-cheapest-noodle-dish-ever-chicken-chow-mein-but-cheaper), it just refuses to import it (both automatic and manual). Its not really an issue for me since I had these saved elsewhere so i just need to do some copy-pasting, but I thought I should tell you folks just in case.

**Comment by smilerz** [comment]
You can create multiple steps for a recipe to do what you want: 

![image](https://user-images.githubusercontent.com/1808639/157112710-5c8aa420-80bb-4e18-af65-15bc4449639f.png)


RE: sites not importing - please open a PR on the project tandoor leverages for recipe scraping [here](https://github.com/hhursev/recipe-scrapers/issues).

**Comment by ExodosPavilion** [comment]
Not exactly what I was looking for since adding steps seem to indicate that there are more instructions to give. I did find out, while looking for how to add a new step, that I can convert an ingredient to a header and move that around to categorize the ingredients:

![image](https://user-images.githubusercontent.com/48080229/157116241-05597f6a-ff88-4e1a-bb30-dcc4acac2a3f.png)

Thank you for the super quick response.

**Comment by smilerz** [comment]
It's fairly flexible - steps can be just instructions, just ingredients, just files, another recipe.

The header approach works too - glad you find a configuration that meets your needs.
