### ISSUE TITLE
Nutrition information 

### ISSUE THREAD

**Issue by afly007** [TandoorRecipes/recipes#1637]
### Describe the solution you'd like

We have a type 1 diabetic in the family, so nutrition information is incredibly important in our recipes.   It'd be great to be able to import ingredients from the USDA's nutrition database and use that information to help in calculating nutrition information for a recipe.

https://fdc.nal.usda.gov/api-guide.html#bkmk-5

**Comment by smilerz** [comment]
duplicate #896
