### ISSUE TITLE
Deleting the only step in a recipe removes Add Step button

### ISSUE THREAD

**Issue by chorca** [TandoorRecipes/recipes#1655]
### Tandoor Version

1.1.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Upon creating a new recipe, if the only step in the recipe is deleted, then the "Add Step" button below the step also disappears, leaving no way to add a step back into the recipe; the entire recipe must be deleted and re-created.

**Comment by chorca** [comment]
![tandoor](https://user-images.githubusercontent.com/1699703/158898409-dd170e35-ecef-4927-8f74-fccad9c3c520.png)

**Comment by vabene1111** [comment]
I think reloading the page fixes this temporarily but yes, this is not good 🤣

**Comment by Sidahmed-ben** [comment]
Hello @vabene1111  , I'm interested by the issue if you agree i can find a solution 😉

**Comment by vabene1111** [comment]
sure, should be an easy fix, just the condition on the button (its not rendering for the last step but this way also not for no step)
