### ISSUE TITLE
Setting default Theme globally (pre-login)

### ISSUE THREAD

**Issue by delight** [TandoorRecipes/recipes#1662]
### Is your feature request related to a problem? Please describe.

I would like to be able set the default theme for the Tandoor Recipes for pre-login and for shared recipes.

It could happen only at setup time via (docker) env variables. Or inside an admin menu. The later one would be more flexible for a quick try out. But for sure the former is absolute fine, as you don't change it all the time.

### Describe the solution you'd like

Ability to change the web-apps theme globally / pre-login. User-prefs can still override by using there own setting.

### Additional context

I know there is already a few discussions mentioning default themes (e.g. [discussion1169](https://github.com/TandoorRecipes/recipes/discussions/1169)), but not a valid feature Request as far as I can tell. So here we go :-)

**Comment by vabene1111** [comment]
this makes sense, will add an .env setting
