### ISSUE TITLE
Admin console search query "Server Error 500" in comments

### ISSUE THREAD

**Issue by L1nKinc** [TandoorRecipes/recipes#1664]
### Tandoor Version

1.1.2

### Setup

Synology

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

First of all, I wanted to greatly thank you for that impressive and awesome recipe manager you build!

Just a minor issue that I came across. I open the admin panel and navigate to the "comment" register and can see all comments in the db to all recipes as expected. but when I try to search something I get an server error (500).
Searching in other db entries like "foods" and so on is working well. Just in comments I get the error page and it seems not to be related to the search string, as it is the same behaviour for different queries.

**Comment by vabene1111** [comment]
thanks for the report, seems to be some filter field i missed when refactoring 

FieldError at /admin/cookbook/comment/
Cannot resolve keyword 'user' into field. Choices are: created_at, created_by, created_by_id, id, recipe, recipe_id, text, updated_at
