### ISSUE TITLE
Images not saved

### ISSUE THREAD

**Issue by vcesinger** [TandoorRecipes/recipes#1665]
### Tandoor Version

1.1.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Hi,
when saving images all are displayed correct. When the docker image is restarted , none of the images are there.
On command line they are saved in the correct folder,  after a container restart the folder is cleared.
Any advise?

Regards

Volker

**Comment by smilerz** [comment]
please share your docker file

**Comment by vcesinger** [comment]
Hi,
see config below. Anything else i can/should share?

---
version: "2"
services:
  db_recipes:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=XXXXXX
      - POSTGRES_DB=recipes
  
  recipes:
    image: vabene1111/recipes
    container_name: recipes
    ports:
      - 82:8080
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles/recipes
    environment:
      - SECRET_KEY=XXXXXX
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=XXXXXX
      - POSTGRES_DB=recipes
      - ENABLE_PDF_EXPORT=1
      
    restart: unless-stopped
    depends_on:
      - db_recipes

**Comment by smilerz** [comment]
when you save images to tandoor do they appear in the mediafiles and staticfiles directories at the root of the machine running docker?

**Comment by vcesinger** [comment]
yes - they are visible and remain there until the container is restarted / lost e.g. after a reboot. then the folders are emptied
