### ISSUE TITLE
Copy Ingredient Action

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1667]
### Is your feature request related to a problem? Please describe.

In Ingredients (edit recipe) there are some actions for Delete, Make Header, Disable Amount and Copy template reference.

### Describe the solution you'd like

Additional Action for copy and paste the line of an ingredient.
This is useful when separating into multiple steps.

**Comment by smilerz** [comment]
@TWART016  do you want to copy the ingredient (in your example split an ingredient into multiple steps)?  or move the entire ingredient to a separate step?

**Comment by vabene1111** [comment]
i think the most straight forward thing would be to add a "duplicate" button and a "move up" or "move down" to change the step

**Comment by vabene1111** [comment]
you are correct, scrolling while dragging is always difficult, thats why i tought about adding a "move to other step" buttons

**Comment by TWART016** [comment]
That would also be ok. Together with Duplicate it would be great.

**Comment by Ram-Z** [comment]
The issue this is trying to solve is that "ingredients are not listed in the correct step". This usually gets noticed when reading the steps instruction. So the best place to add this functionality is in the step. I'd suggest adding a "Copy Ingredient From" and "Move Ingredient From" button to the step which will list all the ingredients (and which step they are in) and allow selecting which to move/copy. This avoids loads of scrolling and trying to remember which of the ingredients need to be moved. Ideally the instructions are still visible when selecting which ingredients to move.

**Comment by vabene1111** [comment]
implemented a very basic version, further improvements will be part of the editor rework
