### ISSUE TITLE
import fails because description is limited to 512 bytes.

### ISSUE THREAD

**Issue by HollisTech** [TandoorRecipes/recipes#1678]
### Tandoor Version

1.1.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

I import a lot of recipes and many of the imports initially fail when the import button is pressed after the recipe fetch because the description field is longer than 512 bytes.  I then have to edit the description to fit the arbitrary limit.  The specific error message is "Recipe description is longer than 512 characters". Easily reproduced by importing almost any recipe from the New York Times Cooking website: https:///cooking.nytimes.com, but that is behind a paywall.

**Comment by fethomm** [comment]
Can confirm. Same behavior here. Is that wanted?

**Comment by vabene1111** [comment]
no its not, needs a fix.

**Comment by vabene1111** [comment]
fixed, long descriptions will now be but at the start of the instructions text since they wont look good on the recipe cards
