### ISSUE TITLE
Smitten Kitchen Imports Fail [Wordpress]

### ISSUE THREAD

**Issue by zemsten** [TandoorRecipes/recipes#1692]
### Tandoor Version

1.1.4

### Import URL

https://smittenkitchen.com/2015/03/baked-chickpeas-with-pita-chips-and-yogurt/

### When did the issue happen?

The scraper/parser doesn't know how to ingest this data. It doesn't appear to follow the schema.org format. I'm not sure if this is a wordpress issue or specific to this site.

Separately, I'm no python guru but I'm learning and would be happy to try and work on this. Any sort of documentation on the libraries/functionality you have already would be great if you wanted to point me that way.

Love Tandoor so far, thanks!

**Comment by smilerz** [comment]
Please open a request to add the site to the scraper at https://github.com/hhursev/recipe-scrapers

**Comment by zemsten** [comment]
Will do, thank you.
