### ISSUE TITLE
Recipe import fails with an error message

### ISSUE THREAD

**Issue by MegamikeMUC** [TandoorRecipes/recipes#1693]
### Tandoor Version

1.0.4

### Setup

Synology

### Reverse Proxy

No reverse proxy

### Bug description

I made an export of recipes from y insance on https://app.tandoor.dev/
On my new instance on my private synology NAS I tried to import this zip file (i tried with all recipes or just with one)
However - i got this error message for all entries in the export file:

ERROR 
duplicate key value violates unique constraint "u_unique_name_per_space"
DETAIL:  Key (space_id, name)=(1, g) already exists.

--------------------
Imported 0 recipes.

The error message changes - depending on different keys.
The database an all entries where empty before import.

Regardless what the error message remarks - there are all recipes imported - but unfortunely without content, only headers - so useless

**Comment by vabene1111** [comment]
interesting, i just pulled an export from app.tandoor.dev and imported it just fine into my local instance. can you send me an example of your export so i can see whats wrong. if you dont want to post it here feel free to email it to me info@tandoor.dev

**Comment by MegamikeMUC** [comment]
[export_2022-04-02.zip](https://github.com/TandoorRecipes/recipes/files/8412232/export_2022-04-02.zip)
[export_2022-04-02(1).zip](https://github.com/TandoorRecipes/recipes/files/8412233/export_2022-04-02.1.zip)
Two versions: one with only one recipe, one with "all"

**Comment by vabene1111** [comment]
ok so first of all those recipes look very nice 😋 second i could import all of them without problems. Maybe wait for the next release, its possible i fixed something in the meantime, if it still does not work we will need to debug your local setup to see whats going on there.
