### ISSUE TITLE
Scale recipe title image better

### ISSUE THREAD

**Issue by HarHarLinks** [TandoorRecipes/recipes#1699]
### Tandoor Version

Current Version: 1.1.4 Ref: 0c841ec6862763c82961c3f8bf9ecfdac28e6604

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

I have a recipe with 2 dozen ingredients. My title image is large, but in practice it is limited by `max-height: 30vh;` which leaves a lot of space in its column:
![image](https://user-images.githubusercontent.com/2803622/161614712-a5334147-c077-4c4f-8c72-a9ea6a87b04a.png)

It would be lots better to fill this space at least to 100% of its container in 1 direction (in this case horizontal)

**Comment by Kaibu** [comment]
Fixed if the image resolution is high enough

https://github.com/TandoorRecipes/recipes/commit/dc8ce0f6a45a6ea337f5a41f37a36596c5616e51
