### ISSUE TITLE
Manually sort and sub-chapter books

### ISSUE THREAD

**Issue by HarHarLinks** [TandoorRecipes/recipes#1701]
### Is your feature request related to a problem? Please describe.

I want to faithfully digitize a family cookbook, which has a certain thought-out order as well as chapters with certain recipe types.

I realize that I can implement this using tags and filtering by them, however I think the feature of having "books" should be able to replicate/model this behaviour of real life books. It is relevant for example when browsing for ideas.

### Describe the solution you'd like

- I would like to manually re-order recipes in a book, similar to how I can reorder steps within a recipe
- I would like to add chapters like "Grandmas Recipes" or "appetisers" or any arbitrary thing

**Comment by smilerz** [comment]
I'm working on chapters now.  That will definitely be part of my next contribution.

**Comment by vabene1111** [comment]
awesome, i know @Kaibu had that on his list as well but has not gotten to it (together with sorting). Should probably be possible to implement this in an efficent and easy way.
