### ISSUE TITLE
Scale arbitrary amounts in the text by the global portions multiplier

### ISSUE THREAD

**Issue by HarHarLinks** [TandoorRecipes/recipes#1706]
### Is your feature request related to a problem? Please describe.

#218 added the ability to reference ingredients in the text which automatically can use the same amount from the ingredients list, which is scaled by the global amount of portions multiplier.

Beyond that, I'd like to be able to scale arbitrary numbers by the same multiplier.

This is useful for example when you are going to layer something, but also save some amount for later to garnish.

In my current recipe I added
1. step: grate an amount of cheese
2. step: use half of that cheese
3. step: use the other half minus a garnish amount
4. garnish with grated cheese

### Describe the solution you'd like

Maybe just make the portions variable (or the fraction of the default amount) available to be used in the text with jinja:
`set {{ 100 * portionsFrac }}g of flour aside for later` will become
- `set 100g of flour aside for later` with default portions of the recipe
- `set 500g of flour aside for later` if you set portions to 5 times the default

**Comment by vabene1111** [comment]
i like the idea, i will look into this at some point. For now its likely easiest to add that ingredient multiple times so you can insert it at multiple locations in the text

**Comment by tomtjes** [comment]
Here's another example for which there's no easy workaround:
`Put 350g frozen raspberries into a blender and puree (makes about 180ml)`
You can scale the raspberries, but not the puree. However, this is not a huge pain for me, personally....
