### ISSUE TITLE
Email subject prefix not replaced with default

### ISSUE THREAD

**Issue by mstrandbo** [TandoorRecipes/recipes#1707]
### Tandoor Version

Current Version: 1.1.4 Ref: 0c841ec6862763c82961c3f8bf9ecfdac28e6604

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Enabling the email config, without changing the 'ACCOUNT_EMAIL_SUBJECT_PREFIX' from what it is default...

`ACCOUNT_EMAIL_SUBJECT_PREFIX= # prefix used for account related emails (default "[Tandoor Recipes] ")`

...results in the email being sent with the subject "  # prefix used for account related emails (default "[Tandoor Recipes] ")"

The commented part of the line isn't ignored and the default prefix is not used.

**Comment by vabene1111** [comment]
thanks for reporting, i will change the .env template
