### ISSUE TITLE
User-file in Api Function createRecipe  

### ISSUE THREAD

**Issue by ignis-draco** [TandoorRecipes/recipes#1708]
### Issue

Hi, 

I am working on an image parser to automatically digitize recipes. When using the API I have seen a strange behavior. 

What I did:
1) uploaded multiple images using createUserFile.
2) created a json for createRecipe and at a "step" under "file" used the name of one of the uploaded images. 

As a response when uploading I get from the server: "Cannot create File over this view".

I have then test instead of: 
`
"file": {
    "name": "string"
},
`
tried this:
`
"file": {
 "name": "string",
  "file":  "string",
  "id": 0
},
`

What make times works. 
Wouldn't it be better at this point to just include the id in createRecipe?

### Tandoor Version

1.1.4

### OS Version

Debian 11

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

**Comment by vabene1111** [comment]
I am not sure if u understood correctly but the image file serializer is nested so you need to pass an object even on create. Please test if user file: {ID : x} works. Sorry for the short description I am on my phone. Hope this makes sense.

**Comment by ignis-draco** [comment]
I tried 
`"file": {"id":1}` 
and I get 
`"steps": [
        {
            "file": {
                "name": [
                    "This field is required."]}}]`

I have tested if I enter different images under Name and Id. 
`"file": {"name":"step1","id":4},`
The ID is taken. 

So the "name" is simply ignored. However, the entry must be there and must not be empty. 
`"file": {"name":"foo","id":4},`

**Comment by vabene1111** [comment]
the 500 error shows if you enable `DEBUG` in the environment settings.

I just tested, if a recipe has no user file its `"file": null,`

if there is one its
```
"file":{
            "name":"name",
            "file":"file url",
            "id":2
         },

```
(i just opened the network inspector on the recipe edit page. Honestly i am not sure if the create endpoint behaves slightly differently since the application never uses that endpoint but those two endpoints should behave the same

**Comment by ignis-draco** [comment]
Hi, 

first of all, thank you for the answers. 

I was able to create 6 recipes with Step Images only by using the ID (with a dummy string as the name) , but I got the error 500 again with the 7th recipe. 
I will now try again with name, file url and id and maybe it will run stable. 

In general, I noticed that the API does not always behave the same way. 

How can I best help to systematically find and fix these problems? 

(I get the 500 error even without DEBUG=1)

**Comment by vabene1111** [comment]
the api should definitely not behave inconsistently, i think it will likely be some kind of edge case triggered by input data. the 500 will not go away with debug but if you look at your logs (with docker ist `docker-compose logs` it should show you an error message. With that message i will likely be able to fix the issue or at least reproduce it at first.
