### ISSUE TITLE
Markdown in recipe description

### ISSUE THREAD

**Issue by andy47** [TandoorRecipes/recipes#1713]
### Is your feature request related to a problem? Please describe.

I'd like to be able to put links and other formatting in the 'Description' field of my recipes. As Markdown is supported in the step Instructions fields would it be possible to extend this to the recipe description field as well?

### Describe the solution you'd like

Description field of recipe allows me to enter Markdown and renders it correctly on display

**Comment by vabene1111** [comment]
I have decided against allowing markdown in the description as this field is meant to be displayed at various locations across the application and having formatting there would make it very hard to have a consistent looking ui at those places.

**Comment by andy47** [comment]
Ok, thanks for the feedback.
