### ISSUE TITLE
Manual entry nits

### ISSUE THREAD

**Issue by dsm1212** [TandoorRecipes/recipes#1715]
### Tandoor Version

1.1.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Other

Safari on MacBook Air but I've seen these things on windows with chrome too.

### Bug description

I'm using manual entry quite a bit and there are a few nits that I wanted to report.

When entering an ingredient after I enter the unit, if I hit tab it goes to keyword entry instead of the item name field to the right of the unit. Made this mistake about a 100 times now. Would be nice if the tab order on the ingredient entry just went to the next field to enter :-).

The entry in these ingredient fields is very strange as far as normal web apps go. I can type but tab out doesn't cause an enter so the field still shows the old value. I have to actually hit enter and then tab. Fortunately going back to the field my edits are still there when I make this mistake.

The ingredients fields sometimes are difficult to clear. Could we have an entry in the list for None or blank?  For example when I want to say "1 egg" there is no unit. I usually manage to do it but it takes a couple tries and I'm not sure what the right sequence really is.

I can't for the life of me figure out how the steps are supposed to be used. If I try to use them I get a page with the ingredients listed multiple times. I would like to have one ingredients list with multiple steps for things like cake vs icing. Is it possible?

Would really like to have steps work AND have a pic for each step.

thanks!!

**Comment by dsm1212** [comment]
On the ingredients list and steps I'll make a suggestion. If I have two steps, each with an ingredient list, then at the top the main ingredient list should use the step name above those ingredients. And don't list those ingredients again under the step. So I have entered through edit something like this.

Step 1 - make the cake
  ingredients...

Step 2 - make the icing
  ingredients...

What is produced is:

Ingredients
    Make the cake
       ingredients..
    Make the icing
       ingredients...

Step 1 - Make the cake

instructions

Step 2 - Make the icing

instructions

**Comment by smilerz** [comment]
Steps and ingredients are working as intended. 
you can get the behavior you are looking for by listing all ingredients in a single step and putting instructions in subsequent steps. 

The other suggestions you have submitted or duplicated elsewhere.

**Comment by dsm1212** [comment]
I don't think I've entered anything about this before, but if some else has great. I don't get the comment about putting all ingredients in a single step. The second I had a second step the ingredients are listed twice. Just put one ingredient in the first step and add a second step. The ingredient will be listed at the top of the recipe and in the first step. Is there some way to not do that?

**Comment by smilerz** [comment]
The first card is a summary of all steps.  You can enter everything in 1 step and control the formatting of the instructions using markdown if you want to control the display to that degree.  

There are other feature requests for controlling the behavior of the summary card.
