### ISSUE TITLE
Some API calls ignore subpath

### ISSUE THREAD

**Issue by JSAnyone** [TandoorRecipes/recipes#1718]
### Tandoor Version

newest

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

I have a Tandoor instance hosted at `mydomain/recipes/` and a personal API hosted at `mydomain/api/`. The API is secured by [Basicauth with Traefik](https://doc.traefik.io/traefik/v2.0/middlewares/basicauth/).

Sometimes when I use Tandoor in a Browser, I am asked to enter the Login credentials for `mydomain/api/`. My only explanation is that Tandoor sometimes ignores its subpath and wants to access its own API at `mydomain/api/` instead of using the right location `mydomain/recipes/api/`.

**Comment by smilerz** [comment]
I run at a subpath and never encounter this issue.  Can you describe exactly how to reproduce this behavior?

**Comment by JSAnyone** [comment]
You can cancel the login prompt and all stuff is loaded correctly, it doesn’t look like the website is broken. I think if I wouldn’t have the secured API at `mydomain/api` I wouldn’t have notices this behavior since all works as expected, except oft the login prompt popping up.
The problem is that I haven’t found out yet how to reproduce it. It just happens „randomly“ when scrolling/filtering/searching recipes at the main page.
 
I can try to enable the logging of Traefik, maybe it displays which URL `mydomain/api/…`is exactly requested by tandoor.

**Comment by JSAnyone** [comment]
And it happens very rarely…

**Comment by smilerz** [comment]
what does 'cancel the login prompt' mean?

What you are describing doesn't even really make any sense the APIs are all constructed the same way - either everything should break or none of it.  Perhaps there is some hardcoded functionality somewhere?  If you can crank up logging and provide exactly what function and/or API is returning incorrectly that would be useful.

**Comment by JSAnyone** [comment]
> what does 'cancel the login prompt' mean?

![image](https://user-images.githubusercontent.com/74502558/163052515-473fa430-8339-41e6-999b-44badd38efdf.jpeg)

I understand that it doesn't make sense, and since it does happen that rate it isn't a big problem at all.
I just enabled logging of Traefik and will report back when I know which API-requests fail.

**Comment by smilerz** [comment]
why are you getting login prompts like that?  tandoor shouldn't be doing that

**Comment by JSAnyone** [comment]
Looks like my explanation wasn't that good to understand.

I know that Tandoor (hosted at `mydomain/recipes/` doesn't cause this Login prompts.
They are from my own API hosted at `mydomain/api/`, so login promt is normal when accessing `mydomain/api/`.
But since the prompt is displayed while browsing on Tandoor, I think that Tandoor sometimes wants to access `mydomain/api/` by mistake (instead of `mydomain/recipes/api/`).

**Comment by vabene1111** [comment]
can you, when this happens the next time, open the inspector of the page and copy the list of network requests that happen so we can see which route after the /api/ is queried ? this would make it much easier to find the function that goes wrong. 

If you are using chrome you can also filter which should make it very easy to see (filter for `mydomain/api/`) which requests are wrong

**Comment by vabene1111** [comment]
but those are all requests that are API going to /api right ? only the static file requests properly value the subpath. This points to some kind of general setup issues and should basically lead to nothing working or am i getting something wrong here ?

**Comment by JSAnyone** [comment]
Yes it are all API requests.
However, Tandoor is working perfectly fine since almost all API requests are mapped correctly, it happen really rarely that API requests muss the subpath.

**Comment by smilerz** [comment]
@JSAnyone what was happening in the browser at that time?  Does it always occur with a specific client?  Is that client inside the network? 

What you are describing isn't possible given a fully functional system.  All generation of URLs is done in a single function so will either work or not work.
Either there is some cached code that gets used in some scenarios or there is an alternative path to tandoor that doesn't use the proxy that gets used in some situations.
-  To eliminate any cached files interfering follow instructions for your browser to remove all traces of local files for that website (clearing cache doesn't always get the job done)
- not even sure where to begin trying to isolate the other possibility.

**Comment by JSAnyone** [comment]
This time it happened right after Login after I updated Tandoor. 
It occurred with multiple clients, all in the same Network, but accessing Tandoor over an exposed WWW url.

I will try deleting the cache, however I th

**Comment by JSAnyone** [comment]
Clearing the cache didn’t fix the issue.

> you might also want to clear all application data
How do I do this?

**Comment by vabene1111** [comment]
depends on which browser you are using, in chrome its in the dev tools (F12) under the application tab there is a clear all application data button
