### ISSUE TITLE
import recipes from YooRecipe into tandoor

### ISSUE THREAD

**Issue by m4tz3** [TandoorRecipes/recipes#1720]
### Is your feature request related to a problem? Please describe.

I would like to import recipes from the Joomla based YooRecipe. On YooRecipe I only have the possibility to export the recipes as .xml files. Does anyone know of a way I can import my recipes into tandoor?

### Describe the solution you'd like

Possibility to transfer my recipes.

**Comment by vabene1111** [comment]
If this is a custom service there is likely no importer yet. Feel free to provide me a sample file with recipes and I will see if we can build an importer for that Manager.

**Comment by m4tz3** [comment]
Hi, I've attached the exported zip. The recipes should be in the *_yoorecipe.xml.
Thanks in advance

[2022.04.13-10h19.yoorecipe.zip](https://github.com/TandoorRecipes/recipes/files/8480731/2022.04.13-10h19.yoorecipe.zip)

**Comment by vabene1111** [comment]
thanks for the sample data, i will look at this once i find time to do so.

**Comment by m4tz3** [comment]
Hi, is there a chance that the importer will be implemented. Does anyone know of another possibility to import the xml?

**Comment by vabene1111** [comment]
i am sure it will, but its dependent on how much time i have, sorry. added it to the next milestone

**Comment by m4tz3** [comment]
Are you still planning to add this feature? Otherwise I'll have to think of something else :)

**Comment by vabene1111** [comment]
i will but i have no idea when i will be able to. Working basically alone on such a huge project there is only so much you can do.

**Comment by smilerz** [comment]
> i will but i have no idea when i will be able to. Working basically alone on such a huge project there is only so much you can do.

this makes me feel really guilty...

**Comment by smilerz** [comment]
> that was in no way targeted in your direction, i am happy about every help I get but overall this is just an open source project, everyone needs to do what they have fun doing and time for.

I know you didn't intend it that way - just a guilty conscience.  So much that I would like to do!

**Comment by m4tz3** [comment]
Can be closed for me. I imported all the 192 recipes manually :)
