### ISSUE TITLE
Dark Mode Tandoor Theme

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#1741]
tandoor theme dark mode 🥳

**Comment by winniecarole** [comment]
Hi I would like to solve this issue .Can I try it?

**Comment by vabene1111** [comment]
sure, give it a try 👍

**Comment by nagua** [comment]
Also it is currently almost impossible to read the Meal-Plan when you have a dark mode activated. Can this somehow be fixed?

**Comment by vabene1111** [comment]
can you open another issue for that maybe with a screenshot

**Comment by nagua** [comment]
Yes,will do

**Comment by hofq** [comment]
i really like the official Theme, i can't wait for a nice dark mode :)
