### ISSUE TITLE
recipe import issue smittenkitchen.com

### ISSUE THREAD

**Issue by indigoisblue** [TandoorRecipes/recipes#1746]
I used the demo to test recipe import from a recipe site I use often, to see if Tandoor would work for me.  I am able to import from this site into other apps but Tandoor could not read it.  This site may not have properly structured data?  I'm unsure:
https://smittenkitchen.com/2010/10/apple-and-cheddar-scones/

Thanks!

**Comment by smilerz** [comment]
Tandoor uses a scraper library to import recipes. Please open an issue at the link below to have that site added. 

https://github.com/hhursev/recipe-scrapers/issues
