### ISSUE TITLE
Add to Shopping from Meal-Plan

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1765]
### Tandoor Version

1.2.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I would like to add the ingredients from the meal plan to the shopping list. With 1.2.1 I get the message
`Success Added to shopping list`. But the list is empty.

It seems that the action want to add to the old shopping list v1.

In Recipes `Add to Shopping` I get the wizard but not from meal-plan.

**Comment by vabene1111** [comment]
Add to shopping from the meal plan works automatically, there is not difference in the data from shopping v1 and v2.

I just tested it locally and it seems to work just fine, can you post what exactly you are doing ?

**Comment by Carunga** [comment]
Hi,
came here to report the same problem. Great app, we love it btw!

Steps to reproduce:
- in the settings make sure automatic addition from the mealplan to shoppinglist is ticked
- add recipie to mealplan
- go to shoppinglist
- items from the recipie are not there

also:
- go to mealplan
- click on the three dots next to the recipie, click on add to shoppinglist
- there is s success message
- go back to shoppinglist, items do not appear 

Before 1.2. it was working fine, error on 1.2.3 still there.

In the logs there is a lot of:

`web_recipes_1    | 192.xxxx- - [04/May/2022:22:35:14 +0200] "GET /api/shopping-list-entry/?recent=1&autosync=1 HTTP/1.0" 200 352 "http://192.1xxxx/list/shopping-list/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 ``Safari/537.36"`

`nginx_recipes_1  | 192.xxxx- - [04/May/2022:20:35:14 +0000] "GET /api/shopping-list-entry/?recent=1&autosync=1 HTTP/1.1" 200 352 "http://192.1xxxxist/shopping-list/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"`

Thanks for any help!

**Comment by jorgnyg** [comment]
Can confirm this one. Experiencing the same behaviour.

**Comment by vabene1111** [comment]
very interesting, looking into it

**Comment by vabene1111** [comment]
ok so i dont have more time but i pushed a build to develop that adds some debug code. If anyone is interested you could look at the application looks and send me everything with `MEAL_AUTO_ADD` so that when i get back to it i hopefully know whats causing this. If not i will test it on monday or so with the hosted version.

**Comment by TWART016** [comment]
Hi,

I mean the `Add to Shopping`
![image](https://user-images.githubusercontent.com/29805669/167154449-2980e68c-db10-40f6-ae4a-67685f479777.png).

Were can I find `MEAL_AUTO_ADD` ?

**Comment by vabene1111** [comment]
in the container logs which in general are `docker-compose logs -f`

and ok than i need to test that, i tought you ment the other two ways of adding to shopping from the meal plan page :joy: (which now that i am writing it sounds ridiculous)

**Comment by TWART016** [comment]
In the logs I just can see regular logs

`
web_recipes_1    | 192.168.96.3 - - [09/May/2022:16:49:03 +0200] "GET /api/shopping-list-entry/?recent=1&autosync=1 HTTP/1.0" 200 443 "http://192.168.178.15:10006/list/shopping-list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
nginx_recipes_1  | 192.168.178.21 - - [09/May/2022:14:49:08 +0000] "GET /api/shopping-list-entry/?recent=1&autosync=1 HTTP/1.1" 200 443 "http://192.168.178.15:10006/list/shopping-list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" "-"
web_recipes_1    | 192.168.96.3 - - [09/May/2022:16:49:08 +0200] "GET /api/shopping-list-entry/?recent=1&autosync=1 HTTP/1.0" 200 443 "http://192.168.178.15:10006/list/shopping-list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
nginx_recipes_1  | 192.168.178.21 - - [09/May/2022:14:49:13 +0000] "GET /api/shopping-list-entry/?recent=1&autosync=1 HTTP/1.1" 200 443 "http://192.168.178.15:10006/list/shopping-list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" "-"
web_recipes_1    | 192.168.96.3 - - [09/May/2022:16:49:13 +0200] "GET /api/shopping-list-entry/?recent=1&autosync=1 HTTP/1.0" 200 443 "http://192.168.178.15:10006/list/shopping-list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
`

Do I need to enable debug logs?

**Comment by vabene1111** [comment]
i did not think so but it might be required. Just set `DEBUG=1` in your `.env` file

**Comment by vabene1111** [comment]
ok so now i that i am looking at the code the issue makes total sense because tandoor is actually behaving as intended (altough this is not really clear since we have fundamentally changed how shopping and meal plan interact).

The add to Shopping add a list that first is just saved temporarily until you open the shopping list button at the bottom and actually push it to the shopping list. This comes from a time where there were multiple shopping lists and back then it made sense, now it does not. 

I will just remove this functionality entirely as its already implemented by the automatic and manual adding and also on the card thats shown in the plan entries preview.

**Comment by Carunga** [comment]
Perfect solution!

**Comment by TWART016** [comment]
If I edit the Meal plan entry and the box `Add to shopping list` is not set the ingredients will not be added to the shopping list if I check the box. I need to create a new meal plan entry to add it to the shopping list.
Is that intentionally?

**Comment by TWART016** [comment]
Is there something new about that? I easy want to add recipes to the shopping list.

Mostly I do a week plan and add it to shopping list before I go shopping. If I tick the button ```Review shopping entries before saving``` after the entry was created the wizard does not appear.

**Comment by vabene1111** [comment]
have you tested with the latest release ?

i just tested it on my instance and it works just fine. You need to set auto add to false, than the buttons should appear and you can check "review before saving". After adding an entry the normal add to shopping dialog should pop up and allow you to choose what to add.

**Comment by TWART016** [comment]
Yes, I tested with 1.4.8. 

If I create a new entry it works fine just with edit the entry afterwards I have the problem.

**Comment by smilerz** [comment]
Add to shopping only work on create. This is by design.

**Comment by vabene1111** [comment]
Yes this is by design for now. We should probably hide the button when editing an existing entry. There are some other features that come to my mind when thinking about this but to much for now.

**Comment by TWART016** [comment]
Ok thanks for the information.

Then a Add to  shopping from Meal Plan would be great (without opening the recipe)
![image](https://user-images.githubusercontent.com/29805669/225788447-1a54ab64-17f7-452d-afaa-0664cc857538.png)
