### ISSUE TITLE
No armv7

### ISSUE THREAD

**Issue by rubenixnagios** [TandoorRecipes/recipes#1769]
### Tandoor Version

1.1.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

latest version for tag linux/arm/v7 still 1.1.4 and 1.2.2 for linux/arm64 will this be the last one for armv7 architecture?
development stopped for our 32bit beloved systems?

**Comment by rubenixnagios** [comment]
sorry, I checked the releases page --> ' arm v7 temporarily disabled '
will be an update for our armv7 docker systems soon?
in the tandoor demo site can see my translations online ;P

**Comment by vabene1111** [comment]
i am super sorry about arm v7, for some reason despite not changing anything noteworthy the build failed since the last update. I have not yet had the time to fix it as my attemt yesterday was unsuccessfull. I hope to get it done in the next few days.

**Comment by rubenixnagios** [comment]
fair enought, just wanted to see my translations onto my nice tandoor instance!
good job!

**Comment by rubenixnagios** [comment]
fixed arm v7 build, specifically raspberry pi images (now using the tags latest-raspi, beta-raspi and <version-tag>-raspi

`Error response from daemon: manifest for vabene1111/recipes:latest-raspi not found: manifest unknown: manifest unknown`

What am missing here?

**Comment by gloriousDan** [comment]
There were some runtime issues about missing libs with the raspi images. That's why @vabene1111 put them down again to prevent broken installations for raspi users. I just opened a PR which fixes the issues (https://github.com/TandoorRecipes/recipes/pull/1786). After it gets merged, the armv7 images should work again.
