### ISSUE TITLE
Step 1 contains ingredient list

### ISSUE THREAD

**Issue by JGBMichalski** [TandoorRecipes/recipes#1770]
### Tandoor Version

1.2.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

All of the ingredients are populated for a second time inside of the first step.

![image](https://user-images.githubusercontent.com/31932269/166726910-416307d5-a749-4787-9517-e7464b2c3d60.png)

**Comment by JGBMichalski** [comment]
> this is a feature not a bug, steps are shown on top as a summary and in each step they are linked to. There is a feature request to make this configurable but it has not yet been implemented.

I had initially assumed so, but the fact that they were not being filtered led me to believe it was a bug. Maybe I could reword this bug description to reflect that there is an issue with all of the ingredients being listed in the first step?

**Comment by vabene1111** [comment]
so you have ingredients that are assoiciated with lets say the second or third step but they are rendered all in the first one ?

because i have the lastest version on my server and it all looks fine ? can you post a screenshot of the editor ?

**Comment by JGBMichalski** [comment]
> so you have ingredients that are assoiciated with lets say the second or third step but they are rendered all in the first one ?
> 
> because i have the lastest version on my server and it all looks fine ? can you post a screenshot of the editor ?

Ah! I see where I went wrong! They are all listed in the first step's ingredients. My apologies!

Thank you for the great work you are doing!

**Comment by vabene1111** [comment]
no worrys, this is just not very intuitive, need to improve this in the future :)
