### ISSUE TITLE
Calculated Nutitional Information

### ISSUE THREAD

**Issue by DigitalWarrior** [TandoorRecipes/recipes#1773]
### Describe the solution you'd like

Recipes nutritional information could be calculated for each recipe and not rely on information during scraping or user input. 
The United States government has published nutritional information for not only completed products like a TV dinner but also generic individual ingredients to name brand ingredients. 

There is two ways that this information can be utilized. 

1. Rest API calls with a rate limit of 3,600 requests per hour per IP address. Each individual would also need to sign up for API access. This is not a bad way of doing it if nutritional information is done on the fly when viewing a recipe for the first time then storing the nutritional information for that recipe. As some users probably have large recipe collections and would hit the API limit when doing the whole recipe collection at once. Another con would be that it does require a live internet connection. 
2. The data is also presented as several files in either JSON or CSV format. 
     a. The nutritional information could be then imported into the database and be called when ever.  As with everything there is some cons to this method also. As in increased download size and space required to run. 
     b. Could be a supplemental image to fetch that would have all data and only downloaded when an api key is not put into the .env. Doing it this way might be the most effective way as  some of the nutritional information available is updated on a monthly basis. 

The data that is available is broken up into several sources. 
| | Foundation Foods | Experimental Foods | Food and Nutrient Database for Dietary Studies (FNDDS) | Branded Foods
| -- | -- | -- | -- | -- |
| Definition | Data and metadata on individual samples of commodity/commodity-derived minimally processed foods with insights into variability | Data on food published in peer-reviewed journals supported by or in collaboration with USDA | ata on nutrients and portion weights for foods and beverages reported in What We Eat in America, NHANES | Data from labels of national and international branded foods collected by a public-private partnership
| Data Source | USDA: based on analytically derived values | Researchers: based on scientific publications |  USDA: compiled based on values from FDC data types| Manufacturers: based on food label information
|Update Frequency | April and October of each year | April and October of each year as data are available |  Every two years in concert with WWEIA, NHANES release | Monthly

All the nutritional data is located at [FoodData Central](https://fdc.nal.usda.gov)
Api documentation is located here [Api guid](https://fdc.nal.usda.gov/api-guide.html)
Download of the information in JSON or CSV at [Download Data](https://fdc.nal.usda.gov/download-datasets.html)

No matter how this is information is implemented it would be a huge benefit and allows further enhancements ie search for low carb meals or meals that are high in vitamin C ect. 

### Describe alternatives you've considered

There really is not any alternatives besides looking up the nutritional information and calculating it all yourself.

**Comment by vabene1111** [comment]
thanks for the writeup, will consider this as part of #896
