### ISSUE TITLE
Add danish translations

### ISSUE THREAD

**Issue by math625f** [TandoorRecipes/recipes#1780]
### Is your feature request related to a problem? Please describe.

I'd like to translate the project to my native language, Danish, but it's currently not available on [the site](https://translate.tandoor.dev).

### Describe the solution you'd like

Enabling Danish translations on the translation site

### Describe alternatives you've considered

I considered looking to Swedish/Norwegian as alternative for Danish, since they're quite similar, but I'd really prefer to have my native tongue.

**Comment by vabene1111** [comment]
i have added the danish language, thanks for helping to translate tandoor :)
