### ISSUE TITLE
shopping list - update food after recipe change

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1781]
### Is your feature request related to a problem? Please describe.

I add a recipe to shopping list. After changing the recipe (change the food from "Pilze" to "Champignons") the shopping list will not update the food. Therefore the food is still "Pilze".

### Describe the solution you'd like

After saving a recipe there would be a check to the shopping lists items if a recipe is assigned.

**Comment by smilerz** [comment]
The instrumentation to make this work automatically isn't worth the effort for how often the use case comes up.
You can review a recipe's ingredients in the shopping list on the Recipe tab.

**Comment by TWART016** [comment]
In recipes tab I just see the meal name, and servings recipe.
![image](https://user-images.githubusercontent.com/29805669/167169246-16c31bc7-9dda-4ed1-a33f-cbacd2a131b1.png)

It would be great if the recipe is clickable.

**Comment by vabene1111** [comment]
that was in there at some point and must have gotten lost when we rewrote the ui, will add it back

**Comment by smilerz** [comment]
> In recipes tab I just see the meal name, recipe and servings. ![image](https://user-images.githubusercontent.com/29805669/167169246-16c31bc7-9dda-4ed1-a33f-cbacd2a131b1.png)
> 
> It would be great if the recipe is clickable.

Click the eyeball - it puts you back into 'add to shopping' mode on the recipe.

**Comment by vabene1111** [comment]
yes but you cannot open the recipe from there or at least i did not see it 

i know you @smilerz had a hover effect for the recipe card in there at some point but i think we removed that, we could just make the "recipe" colum a clickable link

**Comment by TWART016** [comment]
> i know you @smilerz had a hover effect for the recipe card in there at some point but i think we removed that, we could just make the "recipe" colum a clickable link

That would be nice.

**Comment by vabene1111** [comment]
added this back in :)
