### ISSUE TITLE
Import more recipe from Mealie

### ISSUE THREAD

**Issue by HStep20** [TandoorRecipes/recipes#1785]
### Is your feature request related to a problem? Please describe.

Im working with Tandoor alongside my year-long instance of Mealie, so I was excited to be able to import things. 

### Describe the solution you'd like

The one improvement I'd like to see out of it is to import the 'Original URL' for each recipe into the 'imported from' field in Tandoor. Mealie stores it in the backup json in an "org_url" field, so it should be able to be mapped from there to the "imported_from" field in Tandoor.

I'd also like to see Comments be able to be imported. I comment on a recipe every time I make it, and add notes of things I've changed - possible updating the recipe if my change was for the better. Having that 'history' of meals is a nice reminder of things when Im looking for what to eat. Dealing with different users may be an issue, so perhaps just assigning each comment imported to the user doing the importing would be the best course of action.

**Comment by vabene1111** [comment]
sure, its been a while since i looked at mealies export format, i will see whats missing and add it to the importer.

**Comment by 13robin37** [comment]
@vabene1111 I've tested this however the original URL doesn't seem to be imported. Format is still "org_url" for mealie exports but it's not picked up (imported from is staying empty).

Also the servings and total/prep time aren't imported, doesn't seem to matter if you use "x servings", "x Portionen" or something else, the recipe is always set up with 1 serving and 0 minutes.

Example json from mealie:

`  "recipe_yield": "4 servings",
  "total_time": "20 Minutes",
  "prep_time": "20 Minutes",`

**Comment by vabene1111** [comment]
as sated above, its been a while since i updated the importer and mealie has changed a lot since then. I need to find the time to work on this or anyone willing can contribute it (the parsers are relatively easy once the foundation is laid). 

Trying to schedule this for one of the next releases

**Comment by vabene1111** [comment]
added several of the most prominent missing fields to the mealie beta importer, will need some time to add a mealie v1 importer as well but should be in one of the next releases

**Comment by DrSpaldo** [comment]
Did this end up having a chance to be added? I am on Mealie 1 and have been having trouble importing into Tandoor. I would like to switch over as it appears there is quite a bit more activity and user integration with this project.

**Comment by vabene1111** [comment]
sadly integrating mealie 1.0 is not trivial. I will try to do it soonish but it requires completely changing the structure of the importer. 

But it seems there is quite a high demand so i will try to get it done sooner than later

**Comment by DrSpaldo** [comment]
Thanks for the reply @vabene1111 , I appreciate it and your efforts with the project. Hopefully I can work out a way to transfer over my recipes, I wonder if I can get from 1 to an older version then import

**Comment by vabene1111** [comment]
i fear this might not be possible. If you have some programming skills you might be best off by retrieving from mealis API and posting to tandoors, tandoor can create all objects in a nested manner so you would only need to call one endpoint per recipe. 

You can also try to call mealies API and transform the result into a schema.org json recipe schema which can be imported with the nextcloud cookbook importer (its pretty close at least)

**Comment by DrSpaldo** [comment]
Unfortunately I am not a programmer... I can follow instructions well but more than that it will be a bit tough. I've got Nextcloud installed so I will do some Googling
