### ISSUE TITLE
Wrong number of servigs

### ISSUE THREAD

**Issue by solaris7590** [TandoorRecipes/recipes#1789]
### Tandoor Version

1.2.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

I have a recipe (only one!) that always has the wrong number of servings.
The weird thing is, that in the editor stands the right number of 2, also if I take a look in the Django Admin Panel, and also in the database is the correct value of 2. Only when I open the recipe normally, there is the wrong number of 1.
I already tried to change to number to another value, but it changes nothing.

<img width="629" alt="1" src="https://user-images.githubusercontent.com/77384001/167660527-0b91472c-4467-4713-8fc3-f62fb3d1a9f0.PNG">

And here the correct value in Django Admin Panel:
<img width="358" alt="2" src="https://user-images.githubusercontent.com/77384001/167660546-4fd4429e-e8ff-4e3d-93a5-bfdda4cadd5a.PNG">

**Comment by vabene1111** [comment]
do you have a cook log for that recipe where you have entered one serving ? If so this is intended behavior as this allows you to have user customized servings. This feature needs to be communicated more clearly.

**Comment by solaris7590** [comment]
I looked up in the history. You were right. I deleted the cook log, and now it's correct again.

But whats the sence behind them, because Tandoor did not calculate the ingredients, too. For example I wrote 500g Nudeln for 2 serving and after this cooklog the recipe said 500g Nudeln for 1 serving.

**Comment by smilerz** [comment]
> I looked up in the history. You were right. I deleted the cook log, and now it's correct again.
> 
> But whats the sence behind them, because Tandoor did not calculate the ingredients, too. For example I wrote 500g Nudeln for 2 serving and after this cooklog the recipe said 500g Nudeln for 1 serving.

The intention is to allow multi-tenant sharing of recipes - but needs refactored.

As example - you are a normal person and eat a normal amount.  The recipe that is documented at 2 servings is sufficient for you and your partner.
I am a pig and eat both servings all by myself, so log that I cooked that recipe as 1 serving.  

The scaling for ingredients doesn't change - but the number of people it theoretically is for is different.

**Comment by vabene1111** [comment]
the reason behind this is that i for example am a very hungry person and a recipe might yield me 4 servings while i have a friend how eats basically nothing so the same recipe would yield him 8 servings. 
I also am more hungry sometimes than other times thats why tandoor takes an average over all logged cookings. 

But this is not communicated very clearly so we need to improve on that.

**Comment by genebean** [comment]
I just ran into this too… this is not intuitive at all.
