### ISSUE TITLE
Incorrect number of servings when importing Paprika Recipe Manager 3 Part 2

### ISSUE THREAD

**Issue by Hausmeister486** [TandoorRecipes/recipes#1791]
### Tandoor Version

1.2.4

### Setup

Unraid

### Reverse Proxy

No reverse proxy

### Bug description

Unfortunately the problem from issues #1485 is still present,
I will mail Paparika export files for testing.
Best regards,

#1485 
#1789

**Comment by vabene1111** [comment]
fixed again :)
