### ISSUE TITLE
Ingredient Editor in mobile UI

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1794]
### Tandoor Version

1.2.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

1. Food, Unit and Search field is not translated into the languages (german)
![image](https://user-images.githubusercontent.com/29805669/167961249-0db19b66-0609-49d8-9994-aec41b5159f8.png)

2. The dropdown is cut of on the right side.
![image](https://user-images.githubusercontent.com/29805669/167961319-4e753751-b044-4909-9ab5-6717f58de3be.png)

also the search field to the left side.
![image](https://user-images.githubusercontent.com/29805669/167961544-26dd423f-1b55-46ec-8bcb-f7ccadd846af.png)

**Comment by vabene1111** [comment]
interesting but to be honest the ingredient editor probably something that, just from its functionality, cannot really be used on mobile. But i will look into how it can be improved.

**Comment by TWART016** [comment]
Thanks. There it is easier to search for 200g Champignons. In Recipes we can just search for Champignons

**Comment by vabene1111** [comment]
ok so i improved the ingredient editor to a certain degree on mobile, still not really good as this is just not something that works well on mobile web pages but already much better
