### ISSUE TITLE
Edit recipe in mobile view

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1795]
### Tandoor Version

1.2.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

In `recipe edit` I can scroll to the right and left on mobile device, iOS. In `recipe view` it is correct.
![image](https://user-images.githubusercontent.com/29805669/167962216-c27a104f-a196-443d-90fd-fc1d8de67071.png)

**Comment by vabene1111** [comment]
fixed in next release
