### ISSUE TITLE
Contact | Security Issues

### ISSUE THREAD

**Issue by wsmi22** [TandoorRecipes/recipes#1797]
### Tandoor Version

1.1.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Dear TandoorRecipes contributors,

Im approaching you here, following your security policy instructions :) Our research team has found several security issues in your software.
Please provide us an email to send you the reports or get back to me at: [vulnerability@whitesourcesoftware.com](mailto:vulnerability@whitesourcesoftware.com) or [miriam.iomin@whitesourcesoftware.com](mailto:miriam.iomin@whitesourcesoftware.com) for the details.

Thanks,
Miriam

**Comment by vabene1111** [comment]
Hi Miriam, thanks for reaching out  you can contact us via info@tandoor.dev
