### ISSUE TITLE
Delete/Upload Image throws an Bad Request Error

### ISSUE THREAD

**Issue by naimo84** [TandoorRecipes/recipes#1798]
### Tandoor Version

Current Version: develop Ref: 378938812c8b1100bf054f9f31398fee4332d979

### Setup

Kubernetes

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Hi @vabene1111,

I'm trying to upload an image via Rest-API, but it's failing with an error 400 (Bad Request). The same error occurs, if I want to delete some image on the frontend (as you can see on the screenshot). Unfortunately the logs don't offer any more information, what i'm doing wrong (DEBUG is set to 1)

The frontend error might be a bug I think. The Rest-Api is definitely on my side ;)

Thanks and kind regards from Bavaria,
Benjamin

```js
async function uploadImage(id, mongoid) {

  // If you need the binary data as a Buffer
  // create one from data chunks    
  const got = await import('got');

  var formData = {
    name: 'image',
    file: {
      value: fs.createReadStream(`/home/rezepte/${mongoid}`),
      options: {
        filename: `${mongoid}.png`,
        contentType: 'image/png'
      }
    }
  };

  await got.default.put(`https://tandoor.dev/api/recipe/${id}/image/`, {
    headers:
    {
      Authorization: "Token e12346568145a7937c22fd80e9f93e50244b6789",
      'Content-Type': 'multipart/form-data'
    },
    _form: formData,
  })
}
```

![image](https://user-images.githubusercontent.com/11535502/168062822-7d6ec95b-caa3-400b-96b3-ceeda4a56929.png)

### Relevant logs

```shell
10.42.0.0 - - [12/May/2022:13:13:04 +0200] "PUT /api/recipe/21/image/ HTTP/1.1" 400 2 "https://tandoor.dev/edit/recipe/internal/21/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
59
Bad Request: /api/recipe/21/image/
58
10.42.0.0 - - [12/May/2022:13:13:09 +0200] "GET /edit/recipe/internal/21/ HTTP/1.1" 200 18922 "https://tandoor.dev/view/recipe/21" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
57
10.42.0.0 - - [12/May/2022:13:13:09 +0200] "GET /manifest.json HTTP/1.1" 200 1325 "https://tandoor.dev/edit/recipe/internal/21/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
56
Bad Request: /api/recipe/21/image/
```

**Comment by vabene1111** [comment]
i will need to look at the frontend but if you are using the rest api make sure to do form/multipart to properly transmit the data

**Comment by naimo84** [comment]
Many many thanks for looking at the frontend 👍 

I found a workaround 😁 Uploading an image_url works like a charm 👍 
Therefore I must me doing something wrong with the binary data... 

Is it possible to output some more informations in the error log? DEBUG=1 doesn't work for me?

I have another case: Updating an recipe with PUT also leads me to an HTTP400 and i don't see, what I'm doing wrong ;)

**Comment by vabene1111** [comment]
generally speaking you should get a descriptive error message as a json response to your API requests, have you looked at those ?

**Comment by naimo84** [comment]
Yes, I expected you see an error there 😉 But it's empty as you can see here for deleting an picture via frontend:

![image](https://user-images.githubusercontent.com/11535502/168651969-e4cd2827-798e-40e2-9b6c-38cee29a52b4.png)
 
Many many thanks for getting into this issue 👍

**Comment by vabene1111** [comment]
interesting, will take a look, thanks

**Comment by vabene1111** [comment]
fixed
