### ISSUE TITLE
Recipe Filter

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1800]
### Is your feature request related to a problem? Please describe.

I have some Saved Filters in Recipes. I want to delete some of these old filters.

### Describe the solution you'd like

Option to complete delete saved filters.

**Comment by smilerz** [comment]
Filters can be accessed and deleted  via the list screen (food/units/etc)

**Comment by TWART016** [comment]
I mean the Custom Filters in `Recipes`
![image](https://user-images.githubusercontent.com/29805669/169409236-0c9dcd79-5aad-4ca8-b4a8-af3835763496.png)

I cannot find it in (food/units)

**Comment by smilerz** [comment]
![image](https://user-images.githubusercontent.com/1808639/169409594-39efaba0-90f9-4fc5-a9a0-93c9baf8fb04.png)

**Comment by TWART016** [comment]
Thanks. I always looked in the menu. Maybe you can add a link there.
![image](https://user-images.githubusercontent.com/29805669/169420146-5036e504-d822-4689-a4c9-308719ad9c44.png)
