### ISSUE TITLE
change entry in shopping list

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1801]
### Is your feature request related to a problem? Please describe.

I added a recipe to shopping list or manually created an entry. After that I cannot change the entry and amount. 

### Describe the solution you'd like

Edit existing entry in shopping list.

If possible additionally from add to shopping .
![image](https://user-images.githubusercontent.com/29805669/168183611-3d97d957-c0fb-4837-81ad-710444be9003.png)

**Comment by smilerz** [comment]
Duplicate #1278
