### ISSUE TITLE
update search in new food

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1802]
### Tandoor Version

1.2.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Inside a New Food I filter for shopping categories. I type something but the dropdown entries do not change 
![image](https://user-images.githubusercontent.com/29805669/168186663-2140ddb5-3e93-482a-b665-ae13f921f367.png)

**Comment by vabene1111** [comment]
this is no live searching dropdown, it just shows all available categories (as usually people have just a handfull). If you type in seomthing that is already there like "Gemüse" it should come to the top (it did for me when i just tested) but if you type in something you dont already have it just shows that at the top of the list and asks you if you want to create said entry.

i fixed that the placeholder is not properly localized.

**Comment by vabene1111** [comment]
interesting, in my testing this worked but i tested again on my hosted instance and it makes problems, i will look into it

**Comment by vabene1111** [comment]
fixed, had the wrojng mixin on the api view
