### ISSUE TITLE
Meal-Plan not readable in any dark mode

### ISSUE THREAD

**Issue by nagua** [TandoorRecipes/recipes#1806]
### Tandoor Version

1.2.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

It isn't possible to read the recipe names in any dark mode on the meal plan. Also the date isn't readable.
All in all the meal plan doesn't integrate very well into any dark mode. The attached screenshot is taken
with the darkly theme on firefox. (Chrome is looking the same for me.)

![image](https://user-images.githubusercontent.com/3310583/168473834-33d2ec8b-0568-44f4-9829-1fee53e59858.png)

I tried to look into (fix) the issue myself, but I found it very hard to do properly. First off it seems to be possible to select a color for a meal type. This will probably never play well with themes. The selected color will look right for one theme but not for the others. The second issue that I found was that all themes have a rather limited set of colors available so that it was very hard to find enough colors so that all aspects of the meal plan could properly be colorized.

So I don't know how to go from here. What would you suggest?

**Comment by vabene1111** [comment]
![image](https://user-images.githubusercontent.com/6819595/169059133-74fa43e1-745a-48ed-82eb-8ae356b3d42a.png)

- [ ] calendar day backgorund color for days in the future
- [ ] meal type badge on plan item
- [ ] day name headers
- [ ] shown date range and labels for time range selector

@Kaibu can you take a look or should i ?
