### ISSUE TITLE
Refactoring of endpoint /api/recipe-from-source/

### ISSUE THREAD

**Issue by phantomate** [TandoorRecipes/recipes#1808]
### Is your feature request related to a problem? Please describe.

The api endpoint of /api/recipe-from-source/ is still unoffical

### Describe the solution you'd like

Refactoring of this endpoint with proper dokumentation and without a csrf token requirement

### Describe alternatives you've considered

Scraping the csrf token from the cookie. But thats not passible if you make requests by API Token without knowledge of username and password

### Additional context

**Comment by vabene1111** [comment]
done in next release

**Comment by vabene1111** [comment]
all other endpoints will follow
