### ISSUE TITLE
Autocomplete on Quick Entry for Shopping list

### ISSUE THREAD

**Issue by tmllull** [TandoorRecipes/recipes#1810]
### Is your feature request related to a problem? Please describe.

When you add new items to a shopping list using “Quick entry”, if the item it's not written exactly how has saves previously, a new item has added to the food items. I think it's a little frustrating to manage the recipes if you have, for example in spanish, plátanos, platanos, Plátanos and Platanos. 

### Describe the solution you'd like

On Quick Entry items for shopping list, just autocomplete as on "non-quick entry". If the item not exists, create directly.

**Comment by vabene1111** [comment]
it is possible to do this with automations but that is likely very cumbersome. Generally speaking i have always dreamed about having a syntax completing component that would allow the entry of both foods and units and i guess that might be possible but i did not have any luck implementing it so far.

Closing this as i already have this on my mind but this definitely needs a solution, just dont know when i will find the time as its a very complex thing to do.
