### ISSUE TITLE
Default Sharing for Meal Plan Entries

### ISSUE THREAD

**Issue by martyfuhry** [TandoorRecipes/recipes#1811]
By default, entries to meal plans are not shared and therefore only visible to the user who created the entry. When my wife went to add entries to the meal plan, she was confused why I was ignoring them and adding my own entries. I realized I needed to add both of our users to "Plan Sharing" under settings to prevent future entries from being hidden from me. This confused me, as recipes are by default shared with everyone in the space.

I thought this a rather odd design choice. Shouldn't meal plans by default be shared with all members in the space? I'd propose an option in Settings which, when selected, shares all of the meal plan entries with all of the users in that space. I'd leave it up to discussion whether it should be selected by default. The current method of adding your own user name into the Plan Sharing section was unintuitive, and I'm unsure if it worked or is the intended workflow for enabling this default sharing functionality.

This is probably my favorite self-hosted application, so thank you for all the great work you folks do.

**Comment by vabene1111** [comment]
yes we need some kind of wizard, probably on a per feature basis to explain stuff like this. Generally speaking seperate sharing makes sense if you share a space or example with a family across different homes where each have their own plans/shopping lists and so on so default will probably not happen (maybe a space setting at some point :thinking: )
