### ISSUE TITLE
Make sharing meal option editable via api call

### ISSUE THREAD

**Issue by phantomate** [TandoorRecipes/recipes#1816]
### Is your feature request related to a problem? Please describe.

Currently it is not possible to change the setting about sharing a meal plan via API

### Describe the solution you'd like

Make it possible to edit the meal plan sharing via the api endpoint PUT/PATCH /api/user-preference/{user}/

**Comment by vabene1111** [comment]
should be possible after the next release, lacking the time to write a test for it now so please report if its still broken
