### ISSUE TITLE
Cleanup unreferenced DB entries

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#182]
When deleting an ingredient, or stept or shopping list entry DRF only removes the reference but not the actual object.

Find an efficient way to delete stale DB entries. Probably either by using Signals or a job run by some kind of scheduler that cleans up daily (whatever is more performanc/efficent)

**Comment by kowshikRoy** [comment]
Assign me please

**Comment by smilerz** [comment]
resolved be #2488
