### ISSUE TITLE
Performance Issue: Unnecessary REST Api Calls

### ISSUE THREAD

**Issue by maxboehm** [TandoorRecipes/recipes#1821]
### Tandoor Version

1.2.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

I am currently tinkering around running Tandoor on my RaspberryPi.

However, I have noticed the recipe detail page being quite slow. I have inspected the network traffic and identified two rest calls which seem to be quite similar (regarding size and structure) and also quite expensive (about 1.3s per call) to calculate. 

![grafik](https://user-images.githubusercontent.com/8388836/170492119-1277c479-9819-4265-bc76-be2f8d3d57ce.png)

I don't know too much aboutTandoor, but they only differ in the parameter "?Share=none".

**Comment by vabene1111** [comment]
this is related to the quick switching component and was implemented at the time to quickly get the feature out. This will need to be improved in the future as part of the various performance and architectural issues we have found over the time. 

Currently tough this should not cause the side to load slower as the second request is made after all page render relevant parts are already there. I will close this but keep it in mind when working on the performance update (either next or the version after next one)
