### ISSUE TITLE
meal plan actions

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1823]
### Tandoor Version

1.2.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

The meal plan actions are overlapping with the footer bar.

![image](https://user-images.githubusercontent.com/29805669/170705165-cf42d973-deee-4444-b3f7-6b3ea53a7f81.png)

**Comment by rarjun7777** [comment]
I would like to contribute .

**Comment by smilerz** [comment]
fixed with Meal Plan refactor
