### ISSUE TITLE
on hold notification in add to shopping list

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1824]
### Is your feature request related to a problem? Please describe.

After clicking on `On hold` the notification is persistent. To click on add/remove from shopping list I first need to click on another place so the notification disappears.
![image](https://user-images.githubusercontent.com/29805669/170706100-09410043-701b-4833-aef6-f1ed20262f43.png)

### Describe the solution you'd like

The notification fades after 1-2 seconds

**Comment by vabene1111** [comment]
thanks for reporting
