### ISSUE TITLE
line break in add to shopping list

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1825]
### Tandoor Version

1.2.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

If the food is too long the boxes on the right side are not visible in mobile view.

![image](https://user-images.githubusercontent.com/29805669/170707449-41b25912-3298-4546-aa51-96d75330ffa8.png)

**Comment by vabene1111** [comment]
thanks for the report
