### ISSUE TITLE
Change minutes to hours and minutes when at or above 60 minutes 

### ISSUE THREAD

**Issue by genebean** [TandoorRecipes/recipes#1830]
### Is your feature request related to a problem? Please describe.

Reading wait time for recipes that cook a long time isn’t intuitive as most of us think in hours and minutes, not just minutes. For example, a crockpot recipe I added takes 10 hours but shows up as 600 minutes. 

### Describe the solution you'd like

I’d like values at or above 60 minutes to show as hours and minutes.

**Comment by vabene1111** [comment]
fixed

**Comment by genebean** [comment]
Very cool, thanks!

**Comment by spidersouris** [comment]
Could we have the same change for Home/Search/Recipe View pages? It seems this is not applied there.

**Comment by vabene1111** [comment]
I think I need to build a general formatter class to make the formatting of units/amounts/times/servings and what not standardized
