### ISSUE TITLE
pasting ingredient without a unit breaks page

### ISSUE THREAD

**Issue by xenoguy** [TandoorRecipes/recipes#1858]
### Tandoor Version

1.2.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

when creating or editing a recipe attempting to paste an ingredient with without a unit value breaks the page.

paste in some of these sample inputs:
"2 shallots, sliced"
"1 onion, halved and sliced thin"
"6 bone-in, skin-on chicken thighs"

hit save, error is thrown.

if you then select and de-select a unit for the ingredient, everything works.

also if you pasted other ingredients in at the same time as one of these, the unit drop downs seem to get stuck.

**Comment by vabene1111** [comment]
thanks for pointing this out, we changed an api but forgot to change the frontend, fixed in next release
