### ISSUE TITLE
Error after updating - ValueError Couldn't load manifest 'staticfiles.json'

### ISSUE THREAD

**Issue by 6562422** [TandoorRecipes/recipes#1859]
### Tandoor Version

1.2.7

### Setup

Synology

### Reverse Proxy

No reverse proxy

### Bug description

Hello all,

I am very sorry for probably having a beginner issue.
I installed Tandoor on Synology NAS w/o Reverse Proxy and everything was working fine. 
But after updating to latest Tandoor Pacakage, I receive the following error everytime I start it.

Does anybody maybe know, what I could do?
It would be highly appreciated and again I am sorry for being a beginner.

Thank you so much
65

```
ValueError at /accounts/login/
Couldn't load manifest 'staticfiles.json' (version 1.0)  

Request Method: | GET
-- | --
http://xxx/accounts/login/?next=/search/
3.2.13
ValueError
Couldn't load manifest 'staticfiles.json' (version 1.0)
/opt/recipes/venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py, line 394, in load_manifest
/opt/recipes/venv/bin/python
3.10.4
['/opt/recipes',  '/opt/recipes/venv/bin',  '/usr/local/lib/python310.zip',  '/usr/local/lib/python3.10',  '/usr/local/lib/python3.10/lib-dynload',  '/opt/recipes/venv/lib/python3.10/site-packages']
Thu, 09 Jun 2022 10:55:06 +0200
```

**Comment by 6562422** [comment]
I am sorry, issue is resolved and please ignore my topic.
I was able to find the staticfiles.json and deleted it manually. after restart everything is now fine :)

**Comment by vabene1111** [comment]
sadly this is something that happens from time to time but we have not yet found a fix for it
