### ISSUE TITLE
No Images are shown after following the complete manual guide

### ISSUE THREAD

**Issue by nicedevil007** [TandoorRecipes/recipes#1867]
### Tandoor Version

0.00 (I guess latest, but isn't shown in the webui)

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

I setup tandoor with the guide for manual setup on my ubuntu LXC. I also added my PR to get the manual a bit more up to date and some requirements.

Now it seems to work, I was able to setup my admin user account and put in my email and the verification succeeded as well.

Then I tryed adding my first recipe. Unfortunately it wasn't possible to be shown, maybe I missunderstood the manual docs and missconfigured it?

Here the part where I'm not absolutly sure if that is correct (`.env`):

```
# If base URL is something other than just / (you are serving a subfolder in your proxy for instance http://recipe_app/recipes/)
# Be sure to not have a trailing slash: e.g. '/recipes' instead of '/recipes/'
# SCRIPT_NAME=/recipes

# If staticfiles are stored at a different location uncomment and change accordingly, MUST END IN /
# this is not required if you are just using a subfolder
# This can either be a relative path from the applications base path or the url of an external host
STATIC_URL=/var/www/recipes/staticfiles/

# If mediafiles are stored at a different location uncomment and change accordingly, MUST END IN /
# this is not required if you are just using a subfolder
# This can either be a relative path from the applications base path or the url of an external host
MEDIA_URL=/var/www/recipes/mediafiles/
```

Maybe the ownership isn't right for the staticfiles?

```
root@tandoor:/var/www/recipes# ls -la  | grep staticfiles
drwxr-xr-x 18 root    root        19 Jun 18 20:29 staticfiles
```

Never touched it, all was done by the scripts. Also I think the pictures of the meals are stored inside the mediafolder and this folder got this ownership here:

```
root@tandoor:/var/www/recipes# ls -la  | grep media      
drwxr-xr-x  3 recipes www-data     3 Jun 18 17:41 mediafiles
```

EDIT: 

Tested it with recipes:www-data on the static files folder but didn't make any difference.
What I can tell so far, the image is shown inside the mediafiles folder correctly. On the devtools of my browser I get a 404.

maybe here is something wrong as well? `nginx.conf`

```
server {
    listen 8002;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # serve media files
    location /static {
        alias /var/www/recipes/staticfiles;
    }

    location /media {
        alias /var/www/recipes/mediafiles;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://unix:/var/www/recipes/recipes.sock;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by vabene1111** [comment]
I am not sure where exactly but it Sounds like a very typical issue many people are having when deploying manual Setups without setting the proxy up correctly. See the faq of the docs, there is I think a section about images.
