### ISSUE TITLE
Importing Recipes from old Tandoor installation f.e.

### ISSUE THREAD

**Issue by nicedevil007** [TandoorRecipes/recipes#1868]
### Is your feature request related to a problem? Please describe.

I have an old tandoor installation that was deployed via docker with the "develop" image.
This service seems to be broken because I get an `Server Error (500)` on clicking the `Show links` Button of my invitation links.

So I decided to start from scratch with a stable release version inside an LXC.

As I'm able to login to my old setup I was able to export my recipes from there into a `*.zip` file.

While we are able to export all recipes at once, it seems that we are not able to import them all at once.
The import only works with a zip file that contains just 1 recipe. So I have to do all one by one...

### Describe the solution you'd like

Add the possibility to import a zip file from an old tandoor setup with all recipes in it instead of just one.

**Comment by vabene1111** [comment]
How old is the old develop Version? I recommend upgrading that to the latest version which should work for almost everything we ever commited and migrate data then (the next release will fix load and dumpdata)

**Comment by nicedevil007** [comment]
the reference should be from your commit 3 days ago?

![image](https://user-images.githubusercontent.com/17103076/174497764-c42079eb-caa8-41bd-a6ad-eb0f501dd594.png)

**Comment by vabene1111** [comment]
ok so in that case i recommend you wait for the next release which should be in 2-3 weeks from now and migrate over from two identical versions. Or use the current develop on both machines and use dump and load data, thats probably the easiest. 

Exporting recipes from the webinterface has been neglected a bit and is not really a backup but meant more to send friends a few recipes.
