### ISSUE TITLE
Social login permits users to create new space

### ISSUE THREAD

**Issue by stewartadam** [TandoorRecipes/recipes#1871]
### Tandoor Version

0.17.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

Sign-up is closed for my site, but social login permits users to authenticate, create a new space, and become admins of their own space if they choose.

I also can't seem to find how to disable this self-space-creation behavior in docs or Django admin.

**Comment by vabene1111** [comment]
there is no way to disable self space creation at the moment and likely wont be as it really should not hurt in any way (on a private instance you only allow trusted people access, on a more public instance you want to allow space creation).

The other thing is a bug, social signup should be disabled when normal signup is disabled, i will fix that.

**Comment by vabene1111** [comment]
ok so i just tested this on my instance and everything is working as expected:

with `ENABLE_SIGNUP=0` (default) users cannot create a new account with a social provider. They can however always create a new space (at least with the new version).

Can you confirm that you have set signup to false and are not using an invite link ? 

If so please send me the debug info shown on the system page for further investigation

**Comment by stewartadam** [comment]
My env file is from an older release, so I don't have ENABLE_SIGNUP declared at all - maybe that's why?

Can confirm I didn't provide the user in question a signup link though.

Current Version: [0.17.1](https://github.com/vabene1111/recipes/releases/tag/0.17.1)
Ref: [73527e7f4835d258f6c11b15c1c83e501da25117](https://github.com/vabene1111/recipes/commit/73527e7f4835d258f6c11b15c1c83e501da25117)

**Comment by vabene1111** [comment]
ok so it does not make sense for me to test anything in the latest version. Please update to a current version and let me know if you have any issues, i generally dont update any older version for any kind of fix, its just the latest version (one person can only support so much sadly ..)

**Comment by stewartadam** [comment]
Ah my bad, I thought I was on latest tag with docker but just checked and it was fixed on 0.17.1 as I'm behind a reverse proxy with subpath and had fixed it to address #972 at the time.

I'll try again with the latest version tonight and report back :)

**Comment by stewartadam** [comment]
@vabene1111 tested again:
```
Current Version: [1.2.7](https://github.com/vabene1111/recipes/releases/tag/1.2.7)
Ref: [0e2a27ad4131624fc4219be3235fd1b159484341](https://github.com/vabene1111/recipes/commit/0e2a27ad4131624fc4219be3235fd1b159484341)
```
Can confirm that with `ENABLE_SIGNUP=0`, I can still sign-in as a social user and they get access to the default space (I updated my env to include `SOCIAL_DEFAULT_ACCESS=1` which might be why)

I would expect disabling signup would include disabling social sign-ups.

<details>
<summary>Settings</summary>

```
DEBUG=0
SQL_DEBUG=0
ENABLE_SIGNUP=0
ALLOWED_HOSTS=<redacted>
SECRET_KEY=<redacted>
TIMEZONE=America/Los_Angeles
DB_ENGINE=django.db.backends.postgresql_psycopg2
POSTGRES_HOST=recipes_db
POSTGRES_PORT=5432
POSTGRES_USER=djangodb
POSTGRES_PASSWORD=<redacted>
POSTGRES_DB=djangodb
FRACTION_PERF_DEFAULT=1
COMMENT_PREF_DEFAULT=0
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
MEDIA_URL=/recipes/media/
STATIC_URL=/recipes/static/
GUNICORN_MEDIA=1
REVERSE_PROXY_AUTH=0
SOCIAL_PROVIDERS=allauth.socialaccount.providers.google
SOCIAL_DEFAULT_ACCESS = 1
SOCIAL_DEFAULT_GROUP=guest
ENABLE_PDF_EXPORT=1
JS_REVERSE_SCRIPT_PREFIX=/recipes/
```
</details>


<details>
<summary>System page</summary>

```
Gunicorn Media: True
Sqlite: False
Debug: False

SERVER_PROTOCOL:HTTP/1.1
REMOTE_ADDR:172.19.0.1
SERVER_PORT:8080

HTTP_HOST:<redacted>
HTTP_SEC_CH_UA:" Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
HTTP_SEC_CH_UA_MOBILE:?0
HTTP_SEC_CH_UA_PLATFORM:"Windows"
HTTP_UPGRADE_INSECURE_REQUESTS:1
HTTP_DNT:1
HTTP_USER_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
HTTP_SEC_FETCH_SITE:same-origin
HTTP_SEC_FETCH_MODE:navigate
HTTP_SEC_FETCH_USER:?1
HTTP_SEC_FETCH_DEST:document
HTTP_REFERER:https://<redacted>/recipes/search/
HTTP_ACCEPT_ENCODING:gzip, deflate, br
HTTP_ACCEPT_LANGUAGE:en-US,en;q=0.9,fr;q=0.8
HTTP_COOKIE:csrftoken=<redacted>; sessionid=<redacted>
HTTP_X_FORWARDED_PROTO:https
HTTP_SCRIPT_NAME:/recipes
HTTP_X_FORWARDED_FOR:10.0.1.1
HTTP_X_FORWARDED_HOST:<redacted>
HTTP_X_FORWARDED_SERVER:<redacted>
HTTP_CONNECTION:Keep-Alive

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f06adb8c760>
wsgi.version:(1, 0)
wsgi.multithread:False
wsgi.multiprocess:False
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x7f06adb8d8a0>
wsgi.url_scheme:http 
```
</details>

**Comment by stewartadam** [comment]
@vabene1111 Sorry took a while to test this again, but with the latest release 1.4.2, I still see behavior that I think is unexpected. When ENABLE_SIGNUP=0 social users can still create new accounts by trying to sign-in - they'll get a new account added and if SOCIAL_DEFAULT_ACCESS=1 then they also get the default group.

My expectation would be that ENABLE_SIGNUP=0 would permit existing social users to sign-in, but prevent social login from creating new accounts. I see SOCIAL_DEFAULT_ACCESS as entirely independent from ENABLE_SIGNUP; *if* new user-signups are permitted, then the SOCIAL_DEFAULT_ACCESS setting should take effect.

**Comment by vabene1111** [comment]
i cannot reproduce what you are writing.

I have `ENABLE_SIGNUP=0` and `SOCIAL_DEFAULT_ACCESS=1` set in my environment and it wont let me register a new account.

**Comment by stewartadam** [comment]
Just to clarify - these new accounts are via social sign-ins. Local account sign-up is indeed disabled

**Comment by vabene1111** [comment]
yes, i press "Sign In with Github" without an account with github link existing and it tells me that the signup is closed.

**Comment by stewartadam** [comment]
I wonder if this is perhaps Google specific. I'll try configuring different social providers and see if that changes things.

**Comment by vabene1111** [comment]
thank you for testing and also please provide me with a full overview of your setup if you find anything
