### ISSUE TITLE
Saving throws exception after using "Zutaten einfügen"

### ISSUE THREAD

**Issue by favoritefood** [TandoorRecipes/recipes#1873]
### Tandoor Version

1.2.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Hi TandoorRecipes team,

when ever I user the "Zutaten einfügen" feature, I am no longer able to save the recipe. To reproduce the error:
1. Create a new recipe
2. Use the button "Zutaten einfügen" to paste a list of ingredients and finish the action with the button "OK"
![image](https://user-images.githubusercontent.com/100162453/175004335-8092de12-4ccc-4533-9973-679e03754aa6.png)

3. Use button "Speichern" to save the recipe. --> Error: Beim Aktualisieren einer Ressource ist ein Fehler aufgetreten!

![image](https://user-images.githubusercontent.com/100162453/175005163-c101dc2b-155f-4a19-80d1-779ce5cd14cd.png)

With this error you have no chance to use this cool feature any more.

Regards

**Comment by favoritefood** [comment]
Hi,

just found the real issue and the workaround. The issue is the ingredient without amount and unit, like Salz, Pfeffer in the example above.

After insertion the ingredient appears with 0 and no unit selected. 

![image](https://user-images.githubusercontent.com/100162453/175007291-ff3c0af4-9188-40c3-a83b-960759d075df.png)

It is also not possible to select "Menge deaktivieren" it keeps throwing an error. It seems that at least the unit has to be placed. After this you can use "Menge deaktiviere" and saving is possible.

It would be greate if ingredients without amount and unit could show up after insertion without amount aktivated.

**Comment by vabene1111** [comment]
this issue has been resolved already and is waiting for the next release :) thanks for reporting
