### ISSUE TITLE
note in recipe view on mobile devices

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1874]
### Is your feature request related to a problem? Please describe.

In mobile view I can see the ingredients in recipe view. But I cannot view the note of the food without open the edit mode.
In desktop version I can hover over the speech bubble and see the note.

### Describe the solution you'd like

Possibility to view the note in recipe view on mobile devices

**Comment by vabene1111** [comment]
usually you should be able to see the note by clicking on it and that is working on my device/instance, can you confirm this ?

**Comment by TWART016** [comment]
On iOS I cannot click on it.
On Android it is working fine.

**Comment by vabene1111** [comment]
did i mention that i hate iOS 😂 but i am sure we will find a fix for that :)

**Comment by smilerz** [comment]
> did i mention that i hate iOS 😂 but i am sure we will find a fix for that :)

The linked case has a fix.  I just haven’t had a chance to submit a PR.
