### ISSUE TITLE
Review shopping entries before saving ignored on second recipe

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1876]
### Tandoor Version

1.2.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

In Meal Plan I add a new meal plan entry and enable `Add to shopping list` and `Review shopping entries before saving`. There is a popup with the The recipe is successful added to shopping list. 
![image](https://user-images.githubusercontent.com/29805669/175178618-74f82f23-f638-4bc1-82ab-fdd6f6b3d9ca.png)

Then I add another recipe in meal plan. Both boxes are ticked. The recipe is added to shopping but there is no popup.

**Comment by vabene1111** [comment]
collected into central issue

**Comment by TWART016** [comment]
Is there something new on this issue? Review shopping entries before saving still does not work with 1.4.7.

**Comment by vabene1111** [comment]
no there is not, was planning on working on the meal plan in the next time, might fix is while doing that.

**Comment by vabene1111** [comment]
fixed when feature/card_ui2 is merged
