### ISSUE TITLE
Disable Amount not showing in recipe view

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1877]
### Tandoor Version

1.2.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I disabled the amount of 2 foods.
![image](https://user-images.githubusercontent.com/29805669/175429766-e3cf00d3-5c8c-447e-85c5-d2fb08dca9e0.png)

In recipe view there is still the old value and not the disabled field
![image](https://user-images.githubusercontent.com/29805669/175429892-931a67c3-d8bd-467d-a648-60444c460372.png)

**Comment by vabene1111** [comment]
thanks, i will fix that :)
