### ISSUE TITLE
Some layout issues

### ISSUE THREAD

**Issue by kgebert** [TandoorRecipes/recipes#1879]
### Tandoor Version

Beta 20.06.2022

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

![grafik](https://user-images.githubusercontent.com/28644593/175830540-334038e2-8ac8-48ec-b628-a37565660f39.png)

The following layout issues are in the recipe view (see also screenshot):

- The ingredients and the description are not aligned anymore.
- In the first step only, the name of the step is duplicated to the ingredients list.
- In the first step only, the remark bubble sticks to close to the ingredient.

**Comment by vabene1111** [comment]
i noticed something off about the ingredients table too, need to look into why this broke. thanks fore summing this up

**Comment by vabene1111** [comment]
should be fixed in the next release, let me know if there is anything left for your screen size

**Comment by kgebert** [comment]
Much better now. One issue, though
![image](https://user-images.githubusercontent.com/28644593/176710206-16289215-ce8f-4a37-9ea2-9786d5842544.png)

The name of step one is displayed in the ingredients list. The name of the other steps are not.
Recipe link: 
https://tandoor.trebeg.de/view/recipe/614/8117ad41-7758-4263-865e-9263f01f3caf

**Comment by vabene1111** [comment]
that depends if you set the step header to show, the fact that the default is still not equal is something i need to fix but basically next to the step name there is a button (in the editor) which decides if the name should be shown in the overview or not.

I will fix the inconsistent defaults

**Comment by kgebert** [comment]
Ah, OK. Didn't know that. It could be that I've accidentally clicked that button.

**Comment by vabene1111** [comment]
no i think you did nothing wrong, i messed up the defaults at some point and need to see if they are correct now, maybe its just an older recipe in your instance or maybe the defaults are still wrong.

**Comment by vabene1111** [comment]
ok its just and old recipe from the time this was broken, everything is fixed now
