### ISSUE TITLE
Add field for recipe source

### ISSUE THREAD

**Issue by itsmejoeeey** [TandoorRecipes/recipes#1880]
### Describe the solution you'd like

Rather than just adding the recipe source location to the end of the instructions (as pictured).

![DeepinScreenshot_select-area_20220628002231](https://user-images.githubusercontent.com/9375730/175941122-934119ef-0c1b-4343-b84d-64192c90bb1c.png)

It would be nice to have a special field:

![DeepinScreenshot_select-area_20220628002412](https://user-images.githubusercontent.com/9375730/175941230-be88ee56-ca9f-49bb-a484-e27f7dc9bfbb.png)

If the recipe source location is a URL we could add it to the context menu for the recipe:

![DeepinScreenshot_select-area_20220628002222](https://user-images.githubusercontent.com/9375730/175941282-f2c4be53-830d-46ed-b612-ef09fea7ab08.png)

Even if the user decides not to use it for this purpose, the field could be used by the user to put other source details such as "TV"/"Book" or something specific like "Food Magazine Apr 2021".

### Describe alternatives you've considered

The alternative is just putting this information in the recipe instructions. By having a specific field we would allow for more flexibility if the recipes are exported down the line (rather than having to process the instructions block to try and get this information).

### Additional context

Happy to help working on an implementation, but would like your blessing first.

**Comment by vabene1111** [comment]
there is already a special field for this but its not editable trough the UI as its just set for imported recipes automatically. I will add that to the next release
