### ISSUE TITLE
logout button in user menu

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1881]
### Tandoor Version

beta

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

On mobile devices there are a lot of topics in the user menu. This windows is not scrollable and logout is not possible.

![image](https://user-images.githubusercontent.com/29805669/176052580-d4a600fa-dd91-4444-84cf-264ef1f141da.png)

**Comment by vabene1111** [comment]
thanks, fixed in next release by making the nav scrollable
