### ISSUE TITLE
table in recipe view

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1884]
### Tandoor Version

1.2.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

In Recipe View the table is not correctly display.
![image](https://user-images.githubusercontent.com/29805669/176315645-bbadf2c8-6aee-4780-933d-861baefe8814.png)

Just in `Edit Recipe` and Preview it is correct.
![image](https://user-images.githubusercontent.com/29805669/176315705-7f54a6f4-cfc7-42bc-a7d3-64dff4d33359.png)

**Comment by vabene1111** [comment]
this is an issue with the markdown editor, it does not insert the table in the correct formatting thus the table does not work. 

For now i have removed the table button to prevent confusions like this, when we rework the editor page making sure the markdown editor works correctly
