### ISSUE TITLE
Cannot Import from Evernote Shared Link

### ISSUE THREAD

**Issue by mrsdoubtfire613** [TandoorRecipes/recipes#1907]
### Tandoor Version

1.2.7

### Setup

Unraid

### Reverse Proxy

SWAG

### Bug description

I am attempting to import some recipes I had stored in Evernote.  When I enter the share link Evernote creates into the URL box the options page shows no information besides a keyword of "www.evernote.com".
![tandoor-options](https://user-images.githubusercontent.com/6241932/176962532-105a9376-487f-46be-930b-ead0a53cecec.png)

If I then open the Import section and select any option (I will use "Import & View" for the following screenshot) I receive the error "there was an error creating a resource!" and the URL appears with a status of "Failure".
![image](https://user-images.githubusercontent.com/6241932/176962707-ab039d23-0f08-4155-b09a-6b654484200c.png)

I do not experience this issue when trying to import a recipe from Allrecipes.com:
![image](https://user-images.githubusercontent.com/6241932/176963027-7609301a-7b45-42f2-9a17-5c0765c6c77b.png)
![image](https://user-images.githubusercontent.com/6241932/176963051-c0c26a5f-c0f0-4e0b-ae64-e7e0b31f8e1d.png)

I have attempted this import on multiple of my own Evernote recipes and I have done so by accessing Tandoor both from my subdomain (recipes.mydomain.com) and from the IP address + port on my local network (unraidIP.lan:8155).  Neither change impacts the error.  I have attempted the import with Firefox and Chrome as well, no change.  I have also attempted to use the Import bookmarklet which simply does nothing visible when try to import from Evernote but which does function normally when importing from AllRecipes.com.

### Relevant logs

```shell
I am unsure of what logs to provide.  I will provide whatever is requested.
```

**Comment by vabene1111** [comment]
I do not think that it is possible to import from evernote because that likely will not include any Kind of structured data. But the error message needs improvements to communicate that fact.
