### ISSUE TITLE
Show recipies of spaces where i am guest in search result and recipie overview

### ISSUE THREAD

**Issue by subbiesub** [TandoorRecipes/recipes#1916]
### Is your feature request related to a problem? Please describe.

Show recipies of spaces where i am guest in search result and recipie overview

### Describe the solution you'd like

1. When opening the search page please show recipies of spaces in which i am at least a guest.
2. Additionally when searching for specific words, please show recipies of spaces in which i am at least a guest.

Those recipies could be shown with a special background color or if readonly with a lock as a symbol.

**Comment by subbiesub** [comment]
The new release is a big step in correct direction. Thanks a lot for all your effort!

Would be cool if this can be added to the multitenancy feature.

**Comment by vabene1111** [comment]
this was specifically not included in the current release as it adds a signifikant layer of complexity that goes far beyond just showing the recipes. That said it is definitely planned to do full transparent multi space tenancy in the future, its just not ready yet and the current implementation is a first step. 

can you confirm that all multi space tennancy features are working for you in your instance ?

closing this as it needs no issue, will definitely be implemented at some point as part of a larger project, just not sure yet when it will be done.

**Comment by subbiesub** [comment]
Great to hear that! I will wait for the final implementation, as it will definitly help with family recipie sharing.

As far as i have tested it, i can't find an issue with the current implementation.
