### ISSUE TITLE
Recipe source/json import always failing with "There was an error fetching a resource!"

### ISSUE THREAD

**Issue by medienexpedition** [TandoorRecipes/recipes#1920]
### Tandoor Version

1.3.0

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Recipe source/json import always failing with "There was an error fetching a resource". Normal creation of recipes is working correctly, though. This happens since the latest update (8.7.2022)

**Comment by smilerz** [comment]
@vabene1111 this is fixed in #1917

**Comment by medienexpedition** [comment]
Did I get something wrong, but the issue I mentioned is not about bookmarklet, but on JSON import. So I'm still looking forward to get a fix.

Besides, tandoor is such a great work! Thanks a lot.

**Comment by smilerz** [comment]
> Did I get something wrong, but the issue I mentioned is not about bookmarklet, but on JSON import. So I'm still looking forward to get a fix.
> 
> Besides, tandoor is such a great work! Thanks a lot.

Same underlying issue is causing both failures.

**Comment by vabene1111** [comment]
ok so closing this as it will be resolved with the mentioned PR
