### ISSUE TITLE
[Frontend] Unreadable markdown previews in edit mode

### ISSUE THREAD

**Issue by mikhail5555** [TandoorRecipes/recipes#1921]
### Tandoor Version

1.3.0

### Setup

Unraid

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Themes Darkly and Superhere have unreadable contrast in the editor.

![image](https://user-images.githubusercontent.com/7824786/178139084-a3f89aad-d96d-4ff6-8b89-9c21d110a0c0.png)
![image](https://user-images.githubusercontent.com/7824786/178139099-a2117401-ac83-4d48-a607-1a59cfe559f4.png)

**Comment by vabene1111** [comment]
that is interesting, i just checked this in both darkly and superhero and boith look fine for me

![image](https://user-images.githubusercontent.com/6819595/178553577-632645e1-da3d-4a9b-8b20-569f28c17782.png)

what kind of setup are you running ? can you clear your browser cache and try again ? on what platform/browser are you on ?
