### ISSUE TITLE
Editing ingredients/units when importing

### ISSUE THREAD

**Issue by solaris7590** [TandoorRecipes/recipes#1922]
### Is your feature request related to a problem? Please describe.

In older versions (I think < 1.2.0) is was possible to edit the ingredients when importing a recipe. Since the new Import UI is implemented, there is no longer the possibility to do that. The problem is, that I have a kind of fixed norm for myselfe, for example Eggs should always be in recipes in the form "Egg(s)" and not "Eggs" or "Egg". Otherwise I have 3 different entries in the ingredient list for the same thing and looking for recipes with a certain ingredient makes that more difficult. Currently I have to put much work in importing recipes, because after importing I have to rework the recipe and delete all wrong ingredients again.
Same problem exists with units.

### Describe the solution you'd like

Implementing the possibility to change ingredients and units before importing the recipe.

**Comment by vabene1111** [comment]
there is some other issues asking for this and @smilerz proposed that as well, i dont want to implement two editors but i see the need here, will need to find some kind of solution, thanks for the feedback.

Will close this as there is some other issue somewhere
