### ISSUE TITLE
Dumpdata failes with error: A scope on dimension(s) space needs to be active for this query.

### ISSUE THREAD

**Issue by Mikhail5555** [TandoorRecipes/recipes#1923]
### Tandoor Version

1.3.0

### Setup

Unraid

### Reverse Proxy

No reverse proxy

### Bug description

Currently i'm trying to migrate from sqlite to postgresql. For that I'm try to dump the data on the old instance to be able to move it to the new instance.
During the `dumpdata` command on the old instance, i get the following error:
```cmd
/opt/recipes # ./venv/bin/python manage.py dumpdata > /data/dump.json 
CommandError: Unable to serialize database: A scope on dimension(s) space needs to be active for this query.
/opt/recipes # ./venv/bin/python manage.py dumpdata cookbook > /data/dump.json
CommandError: Unable to serialize database: A scope on dimension(s) space needs to be active for this query.
```
```cmd
/opt/recipes # ./venv/bin/python manage.py dumpdata -a > /data/dump2.json
CommandError: Unable to serialize database: A scope on dimension(s) space needs to be active for this query.
Exception ignored in: <generator object cursor_iter at 0x14c154532ff0>
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1876, in cursor_iter
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

enabling verbosity or debug env variable yields no extra log messages/info.

If there is anything i can do to narrow the problem please let me know,

**Comment by vabene1111** [comment]
i tought that @AliveDevil resolved this with this PR in version 1.3 https://github.com/TandoorRecipes/recipes/pull/1854 

I have to first focus on some of the more pressing bugs with 1.3 and need to come back to this later, maybe it just does not work yet.

**Comment by AliveDevil** [comment]
Yeah, you need `manage.py export` instead of `dumpdata`.
Didn't use the same name as I didn't want to create any incompatibilities.

**Comment by vabene1111** [comment]
ah ok thanks, did not remember this from merging the PR
