### ISSUE TITLE
Switching Spaces fails

### ISSUE THREAD

**Issue by xcojonny** [TandoorRecipes/recipes#1924]
### Tandoor Version

V1.30

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Change space is not working.  If I click on ‚user —> your spaces —> overview‘ I get the error, that I don‘t have the permissions.  Furthermore I’m not able to go back to my space. I‘ll get a server error (500) and when I go back, the list of spaces gets longer.

I can only access the Django administration page. 

Any help is appreciated, since I can’t use my tandoor instance right now.

![859C3F6E-B0E0-44D9-915C-BA01C5E20416](https://user-images.githubusercontent.com/22481238/178161201-f4ba702d-23f9-45d7-8d72-a2bb712ef201.jpeg)

**Comment by vabene1111** [comment]
can you show me the contents of the admin page in the "Space" and "UserSpace" list so i can see which permissions you have. 

Can you open the "Overview" of your spaces and show whats shown there ?

it looks like you are getting permissions for the same space multiple times wich should not happen

**Comment by TheOneValen** [comment]
I have the same problem. I cannot open the spaces overview due to now permissions, even as admin.

**Comment by xcojonny** [comment]
hej, thanks for the fast reply. 
what do you exactly mean by "admin pages (after the update)"

**Comment by vabene1111** [comment]
If you click on admin there is a list of the different databases objects including the `UderSpace` and `Space` object.

I need to know what's in those databases so I know what goes wrong for you.

**Comment by TheOneValen** [comment]
I only see an entry for space. No entry "UserSpace"

**Comment by xcojonny** [comment]
Same for me.

Am 11.07.2022 um 20:29 schrieb TheOneValen ***@***.***>:

﻿

I only see an entry for space. No entry "UserSpace"

**Comment by xcojonny** [comment]
I have copied the 1.27 database and started with docker-compose up. Then i reproduced the error from above.

To me it looks like there are no errors in the log
[log.txt.txt](https://github.com/TandoorRecipes/recipes/files/9087270/log.txt.txt)

**Comment by vabene1111** [comment]
You are right, it does not Look like there are any issues in the migrations.

Can you decribe your instance, especially how many users and spaces you have and how they are members of each other?

**Comment by vabene1111** [comment]
i just saw one thing: are you guys using social auth on your instances, especially do you have the `SOCIAL_DEFAULT_ACCESS` variable set in your `.env` file ?

**Comment by vabene1111** [comment]
in case you were, please feel free to update your instance to the latest beta (should be out in about 10 minutes), maybe this resolves your issues. If not please also let me know.

**Comment by xcojonny** [comment]
I'm using social auth (kexcloak),
`SOCIAL_DEFAULT_ACCESS ` is set to `1`

With the beta i can click on my space, that's working. But the Overview throws an error.

**Comment by vabene1111** [comment]
Would you Mond Posting some Details about the error? You might have to Set `DEBUG=1`to see the message

**Comment by xcojonny** [comment]
Does this help?

![Screenshot 2022-07-12 192302](https://user-images.githubusercontent.com/22481238/178555133-bc3e79eb-dbbd-4298-b110-1fe4545207f8.png)

**Comment by vabene1111** [comment]
yes that helps, fixed, update will be released asap

**Comment by xcojonny** [comment]
Great. Thanks a lot :)

**Comment by TheOneValen** [comment]
> I'm using social auth (kexcloak), `SOCIAL_DEFAULT_ACCESS ` is set to `1`
> 
> With the beta i can click on my space, that's working. But the Overview throws an error.

Sorry for my late replay. But yes, same constellation.

Thank you for your help!
