### ISSUE TITLE
recipe steps not shown after update to 1.3 

### ISSUE THREAD

**Issue by ignis-draco** [TandoorRecipes/recipes#1926]
### Tandoor Version

1.3.0

### Setup

Manual Setup

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

After updating from 1.2.7 to 1.3.0, the recipe steps are no longer displayed (both text and image).
However, all the information is available under Edit recipe.

**Comment by ignis-draco** [comment]
Hi, 

Sorry of course

System: 
- Debian 11 in LXC (Proxmox).
- Connection without NPM. 

I have cloned the container from my fully functional system (1.2.7) and carried out a manual update as described in the documentation. What else I just noticed during testing. When I create a new recipe, the steps are displayed. When writing, I also see that the first step is displayed for some recipes. 
Right now it looks to me like the problem is related to the image files. If there is no picture in the step or I remove it, it works. 
 

[gunicorn_err.log](https://github.com/TandoorRecipes/recipes/files/9083265/gunicorn_err.log)

**Comment by vabene1111** [comment]
ok thanks for the feedback, honestly with what you describe there are simply sooooo many things that can be wrong that i cannot help you fix this issue. It sounds like either the image wasn't build correctly, the JS or the migrations did not go trough. 

I just sadly do not have the time to diagnose this issue, i will leave it open for a while so maybe someone from the community can help.

**Comment by ignis-draco** [comment]
It works for me again now. 
Unfortunately, I can not say 100% exactly what it is. 

What I have done: 
- Update as in the docu 
- yarn update 
- again update like in the documentation
