### ISSUE TITLE
Drag-ingredient-to-scroll in recipe editor barely works—the "zone" for scrolling up is tiny and the zone for scrolling down is even smaller.

### ISSUE THREAD

**Issue by dchawisher** [TandoorRecipes/recipes#1938]
### Tandoor Version

1.3.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

When using both Chrome and Firefox on Windows, scrolling while dragging ingredients is nearly impossible, which in turn makes moving ingredients between steps very cumbersome. The mouse wheel and arrow keys do not scroll. The traditional method of scrolling while dragging something, holding the cursor at the edge of the window, barely works. To scroll up, you have to hold the cursor exactly on the top of the Tandoor window (on the dividing line between the page and the navigation bar). To scroll down, you have to hold the cursor exactly on the down arrow on the window's scroll bar—just putting the cursor at the bottom of the page does nothing.

My suggestion is that while dragging an ingredient, holding the cursor at the top or bottom 5 or 10% of the screen should scroll up or down.

**Comment by vabene1111** [comment]
yes that is really annoying, it will be fixed as part of #1872

**Comment by dchawisher** [comment]
Wow. Thanks!
