### ISSUE TITLE
Instruction editor hidden in Fullscreen mode

### ISSUE THREAD

**Issue by solaris7590** [TandoorRecipes/recipes#1942]
### Tandoor Version

1.3.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

After activating Fullscreen mode in the decription editor the upper part of the box is hidden by the header. So the control panel is hidden, there is no way to make is small again and you can't edit the first lines. The only way to make it small again is to reload the site.

<img width="939" alt="Unbenannt" src="https://user-images.githubusercontent.com/77384001/179368028-57456425-ac4f-415d-92e9-60fb0bf1105f.PNG">

**Comment by vabene1111** [comment]
thanks for reporting, i will look into that, its probably a layer issue with the fixed nav

**Comment by vabene1111** [comment]
ok for now, so that people dont get lost, i will disable full screen in the editor. In the future i will look for a proper editor and improve things like this.
