### ISSUE TITLE
Download and serve images from S3

### ISSUE THREAD

**Issue by dmaes** [TandoorRecipes/recipes#1943]
### Tandoor Version

1.3.0

### Setup

Manual Setup

### Reverse Proxy

Others (please state below)

### Other

haproxy -> traefik -> tandoor

### Bug description

When using S3 to store recipe images, Tandoor sets the image url to the S3 url. This is all fine when using a publicly-available S3 provider that uses globally accepted certificates, but when using a self-hosted S3 setup that's only internally accessible and/or uses self-signed/internal ssl certs, images cannot be loaded by public/external viewers. Solution would be to let Tandoor get the image from S3, then serve it from it's own server.

**Comment by vabene1111** [comment]
that kinda defeats the purpose of having an provider serve the images as you would move all the load back to the server 🤔 

but maybe we can have and option for that, i can look into that. Generally this is not a very common problem so might take some time for me to get to it. If you want to work on this, the library we are using is django storages

**Comment by dmaes** [comment]
You do indeed move all the load back to the server, but S3 is still a good feature to have in dynamic containerised environments, to make storage a lot easier, aside from externalising load.

**Comment by dmaes** [comment]
> If you want to work on this, the library we are using is django storages

I'll take a look. Can't promise anything though, my programming experience is mostly sysadmin scripting stuff, never worked with django.

**Comment by dmaes** [comment]
Created #1947, which fixes this issue for me. I can now configure a limited public proxy to my private S3 provider, which will be used by django in the image url's instead of the normal S3 endpoint. Added benefit is no additional load on gunicorn.
