### ISSUE TITLE
Chefs Plate: "There was an error fetching a resource"

### ISSUE THREAD

**Issue by mattjmeier** [TandoorRecipes/recipes#1944]
### Tandoor Version

1.3.2

### Import URL

https://www.chefsplate.com/recipes/creamy-veggie-pasta-primavera-62a8950d1f567c06230c2cea

### When did the issue happen?

When pressing the search button with the url

After some inspection of the page source, it seems that schema.org tags may not be present. Perhaps there is no way to import from this site?

### Response / message shown

```shell
Failure
There was an error fetching a resource!
```

**Comment by vabene1111** [comment]
yes it seems like the data does not contain any usable information, sorry but thats probably not possible. You might be able to write a completely custom scraper in recipe-scrapers but looking at the source that might be pretty annoying 🤔

**Comment by mattjmeier** [comment]
Thanks for taking a look anyway - and thanks for the awesome software!
