### ISSUE TITLE
Can Tandoor import from website that requires authentication?

### ISSUE THREAD

**Issue by stratus-ss** [TandoorRecipes/recipes#1946]
### Tandoor Version

n/a

### Import URL

n/a

### When did the issue happen?

I have a Atlassian Confluence instance that has years worth of recipes. Confluence requires a login in order to access a URL (be default). Does Tandoor have a way to authenticate before importing a webpage?

It would be possible to work around the issue by blocking Confluence access to the internet and disable authentication, however it would be really helpful if Tandoor could handle authentication

**Comment by smilerz** [comment]
The bookmarklet allows you to work around authentication walls - otherwise, no.
