### ISSUE TITLE
Option to show all notes fields in ingredient list

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#1955]
### Is your feature request related to a problem? Please describe.

In some recipes there's quite a lot of information in the ingredients' notes fields, especially steps for prepping the ingredients. This information is difficult to access while cooking and you want to limit the number of interactions with your device. Also, you can only reveal one note field at a time, which means having to go back and forth between them, when working on multiple things at once.

### Describe the solution you'd like

Either or both of these:
- a toggle that reveals/hides all notes fields
- a theme that doesn't hide the notes behind the bubbles

### Describe alternatives you've considered

- adding prep steps to the foods themselves. But `1 cup finely chopped peanuts` is different from `1 cup peanuts, chopped`. (In the first case you measure the chopped peanuts, in the second case the whole peanuts)
- adding prep steps to the recipe. That's a lot of extra manual work.

### Additional context

Just a related thought I want to share here: Would it make sense to have two different note fields?
- One that is related to buying/choosing the food:
    - `2 plum tomatoes, ripe`
    - `1 tbsp olive oil, or butter`
    - `12 strawberries, select only the prettiest ones` 
- One that is related to prep/instructions. 

In many cases, both types of notes are mixed in my ingredients and I'm not sure how I feel about that. On the other hand, more input fields are not necessarily better...

**Comment by vabene1111** [comment]
yes this was proposed before. you can for now open the print preview wich will show all notes but there should be an additional option.

**Comment by MattSidney** [comment]
Adding a +1 on this request.
