### ISSUE TITLE
Alphabetical index for Food list

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#1956]
### Is your feature request related to a problem? Please describe.

My database has more than 2000 foods. There are still some duplicates or parsing errors that need to be fixed, but it is hard to find them, because I have to scroll through the entire list.

### Describe the solution you'd like

An A-Z index that allows me to jump to the respective section of the list.

### Describe alternatives you've considered

A paged food list might help too, but I think for an alphabetically sorted list a alphabetical index makes more sense.

Using the food list in the Django admin is an option, but lacks some information and functionality that the front end list provides.

### Additional context

Another minor issue: I noticed that some foods that needed fixing contained characters like `()[],-`, but it seems impossible to find them using the list's search field. The results contain all sorts of foods without the special character in the name (or do I need to turn off fuzzy search for this to work?).

**Comment by vabene1111** [comment]
yes, the ModelListView as we call it needs some significant refactoring/rework to be really user friendly for large instances. smilerz is already working on parts of that and i will at some point as well, just not sure yet when. Will close this as some solution (either mentioned here or equally good) will be implemented.
