### ISSUE TITLE
Import URL via API

### ISSUE THREAD

**Issue by ExarchD** [TandoorRecipes/recipes#1957]
### Describe the solution you'd like

I don't see an ability to import a recipe through the api. I'm interested in being able to trigger an import through an external program, is there any way to do that at the moment?

**Comment by tomtjes** [comment]
I think that's what `/api/recipe-from-source/` does.

**Comment by vabene1111** [comment]
exactly, thanks for resolving this. It is not a direct process, it first returns a json for local editing but you can simply send the result back to the recipe endpoint to save it, it has the same structure (at least since version 1.3)

**Comment by ExarchD** [comment]
Thanks so much. Sorry to reopen, but I'm having the hardest time getting the API to work. Do I need to enable it somewhere? I'm getting this:

`curl -X GET -H "Authorization: Token ________________" https://recipes.exarch.duckdns.org/api/recipe/`

{"detail":"Authentication credentials were not provided."}
