### ISSUE TITLE
Internal links

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#1958]
### Is your feature request related to a problem? Please describe.

I'm trying to include things like "goes well with *Garlic Potatoes*" or "use method described in *Yeasted Buns*" in both recipe descriptions and steps. Currently, it is not possible to create links in descriptions at all and in steps there can only be static links as far as I know.

### Describe the solution you'd like

- ability to add links to descriptions
- dynamic links, i.e. including a link to a recipe, where the link text changes when the linked recipe's title changes.

### Describe alternatives you've considered

Adding links manual to instructions using markdown is an okay workaround.

### Additional context

Sorry for all the issues. I just moved from an observer to a heavy user...

**Comment by vabene1111** [comment]
no worries about the issues, i love getting feedback, i just need to balance a bit between power user features (which i love myself as well) and usability for "normal" users like for example my mum how mainly needs reduced complexity and ease of use

description: the descriptions is purposely held simple without any formatting so i can display it in the search and other locations

dynamic links: this could be done something like the github issues system, you would still "hard code" the link/id but it would render as the recipe name. Altough i personally probably never change the name of any recipe so just hard coding it from the start on would be sufficent this would be kinda nice. This is probably something for when we rework the editor and add things like auto complete. Will reference it in that issue and take a look again then.
