### ISSUE TITLE
cannot setup due to CSRF_TRUSTED_ORIGINS setting not available

### ISSUE THREAD

**Issue by blockomat2100** [TandoorRecipes/recipes#1964]
### Tandoor Version

latest

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

Django introduces CSRF_TRUSTED_ORIGINS setting which is required to perform POST requests.
This setting is not available in tandoor recipes, which prevents setting up tandoor.

**Comment by vabene1111** [comment]
PR already open, will likely come with next release https://github.com/TandoorRecipes/recipes/pull/1948
