### ISSUE TITLE
version.py has 0.0.0 as the version

### ISSUE THREAD

**Issue by ciphermenial** [TandoorRecipes/recipes#1976]
### Tandoor Version

1.3.2

### Setup

Manual Setup

### Reverse Proxy

Others (please state below)

### Other

haproxy

### Bug description

version.py has 0.0.0 as the version and that is what is displayed on System Information page.

**Comment by vabene1111** [comment]
this is a know issue for the manual setup as the version number is added during build. I should probably indicate that in the UI somewhere but at the moment this wont be fixed because knowing myself, i will definitely forget to increase the version number if i have to do that manually 😂

**Comment by ciphermenial** [comment]
No worries. I figured it might be the case.
