### ISSUE TITLE
Unable to change settings in Space Settings

### ISSUE THREAD

**Issue by BeansIsFat** [TandoorRecipes/recipes#1979]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

In Space Settings, trying to update anything under the Settings section results in the following error:

    Failure  
    There was an error updating a resource!

I also tried using the most recent `develop` tag and got the same error. I reverted to 1.3.2 and confirmed that it worked properly in that version.

**Comment by vabene1111** [comment]
fixed, forgot to make a field nullable, thanks for the report
