### ISSUE TITLE
Paste Ingredients with space in the ingredient's name

### ISSUE THREAD

**Issue by stoney321** [TandoorRecipes/recipes#1982]
### Describe the solution you'd like

Would like to paste an ingredient that has a space in its name into just the food part as at present it splits it into food and notes.

### Additional context

![image](https://user-images.githubusercontent.com/56794394/183244454-504c9fcc-94d6-4aeb-a2c7-651ce831e46e.png)
![image](https://user-images.githubusercontent.com/56794394/183244461-cf8d5db0-10d1-4424-b16e-87cb525f8402.png)

**Comment by vabene1111** [comment]
Note for myself: I think normally this works but likely due to the special handling of amount and unit directly connected.

**Comment by vabene1111** [comment]
fixed
