### ISSUE TITLE
Auto-updating mechanism

### ISSUE THREAD

**Issue by tandy-1000** [TandoorRecipes/recipes#1987]
This feature would be really useful, I find it hard to keep up with the frequent releases and manual upgrading.
Could be implemented similar to Radarr/Sonarr/Lidarr, which offer stable and nightly branch updates.

**Comment by vabene1111** [comment]
This is probably difficult to implement in docker but you could use some external tool to monitor your containers, I think one of them is called watchtower.

**Comment by tandy-1000** [comment]
I'm currently using a manual install, not docker, should this remain closed for that usecase?

**Comment by vabene1111** [comment]
yes as well, i do not offically support the manual installation. Also an auto update for the manual installation is basiccally putting the update commands in a `.sh` file and setting up cron to run it every 24 hours or so
