### ISSUE TITLE
Sharing Meal Types?

### ISSUE THREAD

**Issue by baumandm** [TandoorRecipes/recipes#1988]
Hi, I'm just getting started with Tandoor and trying to understand how sharing works for Meal Plan meal types.  I've setup a shared instance with my wife, and we found the `Plan sharing` setting and added each other.   If she creates a Meal Plan Entry, it shows up on my calendar, and vice versa.

She created a number of different meal types, and they show up correctly on my side when looking at shared entries.  But I cannot use those types to create new entries myself.  Is this expected?  Am I supposed to create the same matching meal types on my side, or is there a way to share the meal type as well?  I poked around in the admin section but couldn't see a way to do that.

Thanks in advance!

**Comment by vabene1111** [comment]
Hi, currently sharing meal types is not supported. You can simply create the ones you need.

This is probably not the most convenient way and we might find something better in the future but for now it needs to suffice.

**Comment by Siridar** [comment]
Hello. The thing is that the other user can't even create same meal types. When You try to create a meal type that already exist on the other user - there is a popup that the resource has been created but nothing is created really.

**Comment by smilerz** [comment]
> Hello. The thing is that the other user can't even create same meal types. When You try to create a meal type that already exist on the other user - there is a popup that the resource has been created but nothing is created really.

this shouldn't be true on the latest release

**Comment by dzubybb** [comment]
I have the same issue, still can't add same meal type on 1.5.12, no error in logs, no new row in `cookbook_mealtype`.

**Comment by vabene1111** [comment]
ok so i just had a look at this. Between spaces worked before but not multiple of the same type in the same space, that is fixed now. 
![image](https://github.com/TandoorRecipes/recipes/assets/6819595/2fa01c5a-b478-45b5-87c4-047858c489ac)

At some point I might need to change this back to a space level attribute, not sure yet.
