### ISSUE TITLE
Sqlite search setting edge case 

### ISSUE THREAD

**Issue by SoleInvictus** [TandoorRecipes/recipes#1990]
Using version 1.3.3 on Unraid. Loving the new search options...but searching by what's in the title no longer works. For example, I have a recipe for Haitian Pork Griot. I can search by its ingredient, lime, but if I simply type in 'griot', no recipes are found.

**Comment by vabene1111** [comment]
can you apply the fuzzy preset on the search settings page ?

from what version did you update ?

**Comment by SoleInvictus** [comment]
Thanks for getting back to me. I upgraded from 1.3.2, but I'm not sure how
long the issue has been present. My wife just noticed it. I have tried
applying the fuzzy preset and noticed that none of the settings stick. For
example, if I try to add "name" to the "Starts With" field, nothing remains
after I click save.

**Comment by vabene1111** [comment]
are you using sqlite as a databse backend ?

**Comment by SoleInvictus** [comment]
Indeed I am!

**Comment by vabene1111** [comment]
yes thats a bug i am afraid, at least with the settings, searching should still work but i will need to look into this. sorry might take a few weeks as i am on vacation now

**Comment by SoleInvictus** [comment]
No rush, I appreciate your taking the time to look into it at all. Please
let me know if I can do anything to help. Enjoy your vacation!

**Comment by nough** [comment]
Hi @SoleInvictus, just chiming in with my experience. I'm running 1.3.3 in docker with the standard postgresql. I noticed that the update to 1.3.3 broke my search by title functionality, so I came searching in the issues page. 

Interestingly, the search settings page said that the "fuzzy" preset was the default, but this was not set on my installation. I set it, and it fixed the search functionality. 

Sorry that this doesn't help with your sqlite settings!

**Comment by vabene1111** [comment]
Yes his problem is that he uses sqlite and there is a bug that presets don't work there

**Comment by vabene1111** [comment]
fixed with next release, still not nice but i want to rework all the settings so dont want to spend to much time on something i will remove anyway.

**Comment by SoleInvictus** [comment]
Thank you so much!
