### ISSUE TITLE
Converting an ingredient to a header does not remove the food from the recipe

### ISSUE THREAD

**Issue by AmaranthineCodices** [TandoorRecipes/recipes#1997]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

I have a series of recipes that I imported from Paprika. In Paprika, there are recipe headers in the ingredients; in Tandoor, these have been imported as Markdown-bolded ingredients:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/31936135/185722777-50a6c5a0-87cf-4375-8915-a70b98ecb0e7.png">

This isn't ideal, as these aren't actual foods! When I convert them to section headers manually by editing the recipe, however, they continue to exist in the foods list and are attributed to the recipe that previously contained them. There's no way to actually remove these as foods, so they appear in the suggestions box and are generally in the way.

Here's an image of the foods list showing the section header that's been attached to the recipe:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/31936135/185723018-e453caf8-bc44-453e-8f08-7e6a1c4f1d7f.png">

Here's what the "Test" recipe actually looks like:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/31936135/185723030-8e260d5a-40df-40d2-aeb9-f588a1c3a572.png">

It's worth noting that this is **not** an issue with the Paprika import functionality (though perhaps the importer shouldn't be doing _this_ to the ingredient section headers); you can replicate this bug purely in Tandoor without importing any data. Below are reproduction steps for producing this inconsistency without importing anything.

## Reproduction steps

- Create a new recipe. Add an ingredient, call it whatever you want (I used `**Test header**` when verifying this).
- Save the recipe.
- Edit the recipe. Convert the ingredient to a header, removing it as an ingredient in the process.
- Save the recipe again.
- Check the Foods list. You'll notice that the original ingredient name is still there, and is still associated with the recipe. You cannot delete the food, because it's still in use, even though the recipe doesn't actually reference the food anymore.

**Comment by vabene1111** [comment]
Thanks for the detailed report, need to clean that code up properly.
