### ISSUE TITLE
Not able to create a public share link for recipes of a space the user is not owner of

### ISSUE THREAD

**Issue by kgebert** [TandoorRecipes/recipes#1998]
### Tandoor Version

 1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Me, my sister and my brother are sharing an installation of Tandoor. We have a dedicated recipe space for each and given each other read permissions.
I'm able to publicly share recipes of my own space. Currently I noticed that I'm not able to share recipes of my sister. When clicking **Share**, I get the following pop-up:

![grafik](https://user-images.githubusercontent.com/28644593/185747623-ee2d4a61-feff-4ecb-bfba-ffd40d4a2521.png)

The public share link is not generated correctly.

- Either the link should be generated correctly...
- or - if it is not allowed to share recipes of others - the function should be disabled.

(This could be related to [Share link doesn't work between spaces for logged in users #1238](https://github.com/TandoorRecipes/recipes/issues/1238)).

**Comment by kgebert** [comment]
FYI: Just updated to 1.3.3 and this issue is still there.

**Comment by vabene1111** [comment]
Interesting, thanks for reporting. I guess that's something I never tested.

In the long term this should probably also be a seperate permission.

**Comment by vabene1111** [comment]
ok so the problem was actually that you gave each other guest (read only) permission. a guest cannot create a share link (because he is only a guest). I added a proper error message but will rework the permission system in the future to improve this further and make it possible to select those permissions individually
