### ISSUE TITLE
Question: new release

### ISSUE THREAD

**Issue by GettingTechnicl** [TandoorRecipes/recipes#1999]
My apologies if this isn't the place to ask this question,  however I checked the changelog prior to updating my tandoor insurance,  it appears in the changelog that user servings have been disabled?

I'm assuming this means the serving feature when adding the item to my meal plan/when adding a recipe to tandoor?

I'm seeking verification on this as this is a must for my household and I don't want to upgrade if I'm going to lose this feature. Thank you!

**Comment by vabene1111** [comment]
Sorry for the late reply. No servings have not been removed entirely. The only thing that was removed is that each user can have different servings for the same recipe by logging its cooking with different servings. Your probably did not even know this was possible as it was communicated very poorly
