### ISSUE TITLE
Printing recipe from list prints entire recipe page

### ISSUE THREAD

**Issue by RealOrangeOne** [TandoorRecipes/recipes#2000]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

When attempting to print a recipe from the main search page, the search page is printed rather than the actual recipe.

As this is just using the browser print functionality, I suspect removing "print" as an option here is the easiest solution.

**Comment by vabene1111** [comment]
Yes print should not be there on the card as it's currently client print only.
