### ISSUE TITLE
Shared meal plans in entire space

### ISSUE THREAD

**Issue by RealOrangeOne** [TandoorRecipes/recipes#2001]
### Describe the solution you'd like

It'd be very useful to be able to specify that meal plans are always shared with everyone in a space. Meal plans as a household are very useful, but having to manually share with everyone (and sync up meal types) is a bit of a pain.

### Additional context

This would probably need to be something set up at a space level by the owner

**Comment by smilerz** [comment]
@RealOrangeOne you can't specify 'everyone' but you can share meal plans with a set of individuals by default on the settings page `/settings/#preferences`.

**Comment by vabene1111** [comment]
Other than that something like groups is planned for sharing which will also include special groups line space everyone

**Comment by cattaneod** [comment]
I can't set set this preference, every time i click on an user on the "meal plan share" setting, the page automatically reload, and the preference is reset to blank.

**Comment by vabene1111** [comment]
Please open a new issue with all required details for this
