### ISSUE TITLE
Cannot edit and delete "imported from" link

### ISSUE THREAD

**Issue by screendriver** [TandoorRecipes/recipes#2021]
### Is your feature request related to a problem? Please describe.

Right now I'm not able to edit and/or delete the "imported from" link at the bottom of a recipe. At least I don't find a way how to do it.

Furthermore it would be great to give the link a descriptive name like for example [GitHub](https://github.com) instead of https://github.com

### Describe the solution you'd like

I would like to edit or delete the "imported from" link.

**Comment by vabene1111** [comment]
You can edit it by clicking on the additional information button in the editor. Does this resolve your issue?

The markup is something I could see being worked on, maybe by using markdown or automatically extracting only the main domain name.

**Comment by screendriver** [comment]
Could you point me to where to find the additional information button? Maybe with a screenshot? I can't find it unfortunately.

**Comment by MattSidney** [comment]
When editing a recipe it is just under the nutrition section. See image below:
![image](https://user-images.githubusercontent.com/45581528/188339693-722b2013-dcce-4362-8c0a-b475fd182534.png)

**Comment by screendriver** [comment]
I don't see that kind of information 🤔 

![2022-09-05 08 41 27 tandoor dataky synology me 40bfaea26854](https://user-images.githubusercontent.com/149248/188381359-a9a75d2e-5ad2-40ce-9d4e-1bb6682ac5d7.png)

**Comment by MattSidney** [comment]
For me I have to actually click on the additional options. Then the section expands :)

**Comment by screendriver** [comment]
Ah! 💡 Forget it. I have to click on `Additional Options` 🙈 I totally overlooked that link because of the not so good visible blue color of the text.
