### ISSUE TITLE
Food parser doesn't recognize food amount range 

### ISSUE THREAD

**Issue by iamkarlson** [TandoorRecipes/recipes#2023]
### Tandoor Version

develop

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

I got some difficulties pasting the ingredients list. Whenever the amount has variations stated as smallest amount to highest with a hyphen in the middle, tandoor cannot correctly import it and do some weird transformations with text. 

Ingredients list example:

```
1 lb (454g) frozen lima beans (or fresh, but NOT dried — maybe canned?)
1 bunch green onions
1-2 fresh red chilies
1 thumb of ginger
2-3 garlic cloves
1 bunch cilantro (Thai basil would be nice instead)
1 lime's juice (of half a lime if you want less acid)
2 teaspoons cornstarch
1/4 cup (60mL) gochujang (replace some or all with ketchup if you don't want it too spicy)
1/4 cup (60mL) 
1-2 teaspoons sugar
water
oil
```

If you look at the [food parser code](https://github.com/TandoorRecipes/recipes/blob/6605b87c5c779dff03f5819da67ee29a5c069eb4/cookbook/helper/ingredient_parser.py#L206), you may see that there's no expectation of hyphen in the food amount. So I removed smallest amounts and hyphens from the list and it worked correctly.

It would be great if the parser could trim the smallest amount and hyphens so it works. Ideally, it would be to have a **range value** for the ingredient rather than just a number. 

Tandoor info:
```
System Information
Django Recipes is an open source free software application. It can be found on [GitHub](https://github.com/vabene1111/recipes). Changelogs can be found [here](https://github.com/vabene1111/recipes/releases).

Current Version: [develop](https://github.com/vabene1111/recipes/releases/tag/develop)
Ref: [d974ad2e87edda2077612d77bc5b8968706a4a6d](https://github.com/vabene1111/recipes/commit/d974ad2e87edda2077612d77bc5b8968706a4a6d)


Media Serving Ok
Everything is fine!

Secret Key Ok
Everything is fine!

Debug Mode Warning
This application is still running in debug mode. This is most likely not needed. Turn of debug mode by setting DEBUG=0 int the .env configuration file.

Database Ok
Everything is fine!
```

**Comment by smilerz** [comment]
duplicate #1959
