### ISSUE TITLE
Same ingidients not merged between steps

### ISSUE THREAD

**Issue by acul009** [TandoorRecipes/recipes#2024]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

When including the same ingredient in multiple steps, they are not merged.

The second and the last entry are the same ingredient, but are listed separately in the summary.
![image](https://user-images.githubusercontent.com/54124197/189232337-6898b060-ae4c-4456-9eb9-7fd2dc4b64a8.png)

**Comment by vabene1111** [comment]
this is a feature not a bug, see past issues to this topic for explanation, this will be configurable in a future release
