### ISSUE TITLE
'Currently On Hand' not working

### ISSUE THREAD

**Issue by jdubbs4051** [TandoorRecipes/recipes#2031]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

The 'currently on hand' designation when looking at a recipe ingredients in your shopping cart does not work as expected.

**Comment by vabene1111** [comment]
what means "not as expected"

**Comment by jdubbs4051** [comment]
I'm not sure what the original design was intended to do however my expectation (based on the link 'currently on hand') is there is a way to mark items you already have on hand in your pantry/fridge which would be removed when shopping lists are generated from a recipe. Maybe I am misunderstanding the function of 'currently on hand'

**Comment by vabene1111** [comment]
no thats correct, but everyone expects different things so asking this first makes debugging much easier

**Comment by vabene1111** [comment]
moved to higher level issue
