### ISSUE TITLE
Issue with deleting Recipe and displaying single-step Recipe

### ISSUE THREAD

**Issue by BMarcin** [TandoorRecipes/recipes#2041]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

# Bug1
During testing of TandoorRecipes I've encountered a small bug. I've created my test recipe called "test1" and I've added just one step to prepare the meal. After saving and refreshing recipe view page there were just the ingredients withouts notes and the only step. It was missing.
![image](https://user-images.githubusercontent.com/22682338/189950158-0f2cb841-6daf-4b53-a078-ff27f8ab7684.png)
(There is missing step in the picture)
![image](https://user-images.githubusercontent.com/22682338/189950211-b7356ecb-3310-4831-8a2e-898cca99b055.png)
(It is the current state of "test1" recipe, which has got only one step)

## Workaround
Add second step called "Have a great day" 😆

# Bug2
Also, there is another bug which I've found. I've created another recipe called "test2" (test1 still exists in the database). In second step of my three step recipe I've linked my "test1" recipe and I've saved the recipe "test2".  After some time I've came back to my "test2" recipe and I've deleted the link to "test1" recipe in second step. I've saved "test2" recipe and then I've opened editing mode of my "test1" recipe. I wanted to delete it, but I was not able to do that. In the database (I saw that in Django admin panel) there was still an object (cookbook/step) which was linked to my "test1" recipe with "protected" relation type. My workaround for that is to delete manually the linked recipe to the step.

![image](https://user-images.githubusercontent.com/22682338/189950465-67031a81-c6a5-42f3-9a40-6f93c9243d4d.png)
("test2" recipe with linked "test1" recipe in second step)
![image](https://user-images.githubusercontent.com/22682338/189950753-6cca0315-4b78-4d67-9536-81c2e8cb25b1.png)
("test2" recipe after deleting second step from the recipe)
![image](https://user-images.githubusercontent.com/22682338/189950802-635e36d0-5456-4a4d-bd3c-0fea88660aa2.png)
(deleting "test1" recipe view)

## Workaround
Go to the Django admin page and delete "step" object manually.

## My use case
I would like to use TandoorRecipes together with my girlfriend. She is not a technical preson, so going deep into Django admin panel and manually deleting steps with linked recipes can be hard for her. Also I'm a little bit confused with a mess with left "step" objects in the database which has got no titles or even no recipes assigned.
![image](https://user-images.githubusercontent.com/22682338/189952410-331d56d7-be84-4e94-8e74-68cfd1e9a17d.png)
(mess with "step" objects in my database)
![image](https://user-images.githubusercontent.com/22682338/189952875-f5d56998-c558-488a-b087-8bca844d9425.png)
(empty step object linked just to my "Space", it has no recipe linked!)

**Comment by vabene1111** [comment]
thanks for the report, next time please use one issue per issue you have. I will look into this anyway :)

**Comment by BMarcin** [comment]
Ok, thanks for the advice!

**Comment by vabene1111** [comment]
ok finally got to reading this

1. The first bug seems to be because you neither have text nor ingrediedients in your step. Due to the special rendering of single step recipes this will not display the step header. Since having only one step without content does not make sense we probably dont need to fix this. 
2. This is something that sadly has been around for a while. Deleting the step deletes the relation but not the step. I could fix it by automaticall deleting it when deleting the recipe but i dont really want to do this. The reason is that i am still not certain how i want to handle steps. I could leave the 1:1 relation between recipes and steps but i am thinking about making steps more "prominent" by being re-usable between recipes. Not sure yet, until thats decided i am afraid the admin workaround needs to suffice.

thanks for letting me know about both issues, sorry for not changing anything for now but it will be adressed in the future

**Comment by BMarcin** [comment]
Thanks for the reply! 
1. Now I understand. It make sense, but I miss some warning in GUI to know that my header will not be displayed. Or maybe You should display the title of first step somewhere in the page like it is done with note?
![image](https://user-images.githubusercontent.com/22682338/190868654-5c96d6cb-7d9b-4d78-9559-5a5ba37d3504.png)
![image](https://user-images.githubusercontent.com/22682338/190868670-7cdeee77-26a8-4ec6-8328-d31853e078b9.png)
2. What do You think about adding some bash script to be able to clean "messy" steps from the database (kind of workaround)? It would be really useful to add the script to cron and for example clean empty steps every day.

**Comment by vabene1111** [comment]
it could be a django management command. Not sure, if i do this i will take the pressure of myself to fix it properly 😂
