### ISSUE TITLE
Invite Link E-Mail not working

### ISSUE THREAD

**Issue by manuelkamp** [TandoorRecipes/recipes#2042]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

I added new users to my space but none of them actually gets an email. I configured the mail server settings in the .env correctly, but no users get any email. Even more curious: actually I do not even see an attempt from tandoor to log in into the mailserver to send the mails (nothing in the maillog). But I do not get any error on the webpage. I could manually copy the links, but I want it to send the email like it is intended to send.

### Relevant logs

```shell
none available
```

**Comment by vabene1111** [comment]
please post your email configuration without any secrets

**Comment by manuelkamp** [comment]
# Email Settings, see https://docs.djangoproject.com/en/3.2/ref/settings/#email-host
# Required for email confirmation and password reset (automatically activates if host is set)
EMAIL_HOST=mx.mydomain.at
EMAIL_PORT=465
EMAIL_HOST_USER=rezepte@mydomain.at
EMAIL_HOST_PASSWORD=supersecret
EMAIL_USE_TLS=0
EMAIL_USE_SSL=1
# email sender address (default 'webmaster@localhost')
DEFAULT_FROM_EMAIL=rezepte@mydomain.at
# prefix used for account related emails (default "[Tandoor Recipes] ")
ACCOUNT_EMAIL_SUBJECT_PREFIX="mydomain.at Rezepte "

**Comment by vabene1111** [comment]
so i have just tested this on the hosted instance where i know the email server is configured correctly and everything seems to work. Can you take a look at the django logs with `DEBUG=1` to see if any errors are shown ?

**Comment by jadsy2107** [comment]
Hi @vabene1111  

great project, im setting up for my mum on our K8s cluster, just wondering how to configure SMTP on K8S deployment ? 

I cant find the setting anywhere in the web interfaces back end and front end 


Thanks!

**Comment by vabene1111** [comment]
i have absoulutely 0 clue on how to configure k8. There should be some other variables that are already passed to the application, you can just look at `.env` how they are named other than that the k8 configs were contributed by the community so not sure how to change those

**Comment by jadsy2107** [comment]
> i have absoulutely 0 clue on how to configure k8. There should be some other variables that are already passed to the application, you can just look at `.env` how they are named other than that the k8 configs were contributed by the community so not sure how to change those

That's ok, so nowhere in the config is the SMTP server in the web UI ? 

I'll figure it out and post back when I've got it going :)

**Comment by vabene1111** [comment]
it only works with environment variables, there should already be some that are passed to the app so it should be easy to just add the other ones.

**Comment by Sepphod** [comment]
I have a similar issue. I don't get any email. But I have tandoor in a docker. So must I add the port 587 (in my case) to the docker??

**Comment by jadsy2107** [comment]
East thanks

Kind Regards,
Jad
________________________________

**Comment by vabene1111** [comment]
you need to add whatever configuration is appropriate for you provider, they should document which ports and addresses need to be used. Tandoor just uses the default django built in mail system so not much that can go wrong there.

**Comment by jadsy2107** [comment]
> you need to add whatever configuration is appropriate for you provider, they should document which ports and addresses need to be used. Tandoor just uses the default django built in mail system so not much that can go wrong there.

Sorry when mention the Django system, https://docs.djangoproject.com/en/4.1/topics/email/

I cannot see where to set these values in the recipes backend ?

![Screen Shot 2022-11-18 at 6 17 32 pm](https://user-images.githubusercontent.com/107200645/202643714-0c917848-64f8-418c-bba4-5c7ff32b0b62.png)

**Comment by Sepphod** [comment]
> you need to add whatever configuration is appropriate for you provider, they should document which ports and addresses need to be used. Tandoor just uses the default django built in mail system so not much that can go wrong there.

OK that supports my current suspicion as the docker runs on a raspi and it seems that with one of the latest updates raspbian stops its support of smtp. It uses mstmp now. Any of my emails on my raspis are stopped working.. Anyway I will deploy tandoor on an ubuntu to prove it.

**Comment by vabene1111** [comment]
Ok, please open a seperate issue with your findings, might be that we need to allow another setting to be passed to the djanfo mail function
