### ISSUE TITLE
Optional Ingredients flag

### ISSUE THREAD

**Issue by vspaziani** [TandoorRecipes/recipes#2045]
### Is your feature request related to a problem? Please describe.

I have several recipes that contain optional ingredients. For example:  Make brownies optional add 1 cup of walnuts. The issue this is causing is that when I search for recipes that. contain ingredients I have on-hand it currently includes the optional ingredients. 

### Describe the solution you'd like

Provide a selection for each ingredient where you can signify that an ingredient is not required.

### Describe alternatives you've considered

I considered using the note section but it does not  resolve my filtering need.

**Comment by vabene1111** [comment]
yes, pretty sure there is a nother open issue somewhere so closing this altough i dont know where the other is. But will probably be done as part of the recipe editor rework.

**Comment by vspaziani** [comment]
@vabene1111  Did this feature get lost in the new version? I cannot locate how to set something as optional and swear I could do it in V1.

**Comment by vabene1111** [comment]
no this is not yet done. I have ideas for it but its a lot of work, no idea when it will be implemented

**Comment by vspaziani** [comment]
Thanks for the follow up
