### ISSUE TITLE
False claim about website importer

### ISSUE THREAD

**Issue by Pheggas** [TandoorRecipes/recipes#2046]
### Tandoor Version

1.3.3

### Import URL

https://tojenapad.dobrenoviny.sk/karamelovy-cheesecake-do-poharov/

### When did the issue happen?

Automatically when i pasted the link

There are some other examples:
http://www.bozskerecepty.sk/jednoduche-makove-kocky-so-zltkovou-polevou/
https://zenskerady.sk/index.php/2022/09/09/manzel-ochutnal-tento-jednoduchy-veternik-z-plechu-a-odvtedy-ho-musim-robit-kazdy-vikend-je-naozaj-vynikajuci/
https://tortyodmamy.sme.sk/recept/kolace/hrncekovy-kolac-s-tvarohom-cernicami

It seems to work only with recipe dedicated sites that has differently built whole site and all ingredients are in it's table. So the claim "Our Importer works with all of your favorite recipe sharing platforms." is false as i'm unable to parse my favorite websites for recipes. Please, remove that claim.

**Comment by vabene1111** [comment]
I dont know how someone can be given a free super powerful application for which people worked hundreds if not thousands of hours to develop it and just rant about some edge case that does not work, if there were only people like you there wouldn't be any open source applications ...

btw. you can impolement a custom scraper in recipe-scrapers which will allow you to import even your obsucure websites that dont provide structured data, even that is something we accounted for. 

I will fix the description to add an "almost" or "most" or something

**Comment by vabene1111** [comment]
btw tahts what the github readme says 
Import recipes from thousands of websites supporting [ld+json or microdata](https://schema.org/Recipe)
