### ISSUE TITLE
Search function does not search based on recipe title

### ISSUE THREAD

**Issue by delize** [TandoorRecipes/recipes#2047]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

When searching for `curry` using Tandoor's search function, even though Curry is in the recipe title for various recipes, it results in 0 results.

<img width="1257" alt="Screen Shot 2022-09-18 at 19 56 47" src="https://user-images.githubusercontent.com/4028612/190921703-29094fa3-6c63-4cdc-9f38-bc342b72db2a.png">
<img width="1209" alt="Screen Shot 2022-09-18 at 19 56 59" src="https://user-images.githubusercontent.com/4028612/190921706-bcb8a820-c0a9-4c16-9b49-47b4fe37e782.png">

After I add a keyword of `curry` it returns a result. This should really return results that are also in the title of the recipe.

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/4028612/190921724-2a8d149a-983a-4d91-baa4-9290548a5f04.png">

```
Current Version: [1.3.3](https://github.com/vabene1111/recipes/releases/tag/1.3.3)
Ref: [9ef21241bf93243b2a08b13de86e6b4c4774c594](https://github.com/vabene1111/recipes/commit/9ef21241bf93243b2a08b13de86e6b4c4774c594)

Gunicorn Media: True
Sqlite: False
Debug: False

SERVER_PROTOCOL:HTTP/1.1
REMOTE_ADDR:172.26.0.6
SERVER_PORT:8080

HTTP_REMOTE_USER:firstname
HTTP_REMOTE_GROUPS:admins,dev
HTTP_REMOTE_NAME:firstname lastname
HTTP_REMOTE_EMAIL:me@firstnamelastname.org
HTTP_CONNECTION:close
HTTP_HOST:recipes.domain.org
HTTP_X_FORWARDED_FOR:my.ip.address.here
HTTP_X_FORWARDED_HOST:recipes.domain.org
HTTP_X_FORWARDED_PROTO:https
HTTP_X_FORWARDED_SSL:on
HTTP_X_REAL_IP:my.ip.address.here
HTTP_SEC_CH_UA:"Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
HTTP_DNT:1
HTTP_UPGRADE_INSECURE_REQUESTS:1
HTTP_SEC_CH_UA_MOBILE:?0
HTTP_USER_AGENT:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
HTTP_SEC_CH_UA_PLATFORM:"macOS"
HTTP_SEC_FETCH_SITE:same-origin
HTTP_SEC_FETCH_MODE:navigate
HTTP_SEC_FETCH_DEST:empty
HTTP_REFERER:https://recipes.domain.org/view/recipe/42
HTTP_ACCEPT_ENCODING:gzip, deflate, br
HTTP_ACCEPT_LANGUAGE:en-US,en;q=0.9,sv;q=0.8
HTTP_COOKIE:csrftoken=omit; sessionid=sessionid; omit

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f2d84b4ad40>
wsgi.version:(1, 0)
wsgi.multithread:False
wsgi.multiprocess:False
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x7f2d84b4b9a0>
wsgi.url_scheme:http
```

**Comment by delize** [comment]
I did see #1990 however, I am not using SQLite based on the troubleshooting output, so filed a different issue. If this is a duplicate of that even when not using SQLite, please close this.

**Comment by vabene1111** [comment]
thanks for the report. Your observation is correct, all of these functions use the same search class.

Did you go to the search settings and apply the fuzzy preset? There was a bug thats fixed in 1.3.3, i tought not to many people got corrupted preferences so i did not write a migration but i am slowly thinking that this might not have been the best idea 🙈

**Comment by delize** [comment]
I have not gone into any advanced search settings, I just went through what I would consider is the "standard" of searching, typing something and hitting enter. 

It's really strange though - searching some phrases sorta works?
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/4028612/190925449-3c83b392-a4fc-42e0-a969-e4449c3a8309.png">

`Garlic` is an ingredient and in the steps for the "Instant Pot Butter Chicken" recipe, but searching `Chicken` does not return that same result. `Chicken Thights` is an ingredient and `Chicken` is in the steps.

This is what I have by dropping it down (without modifying anything):
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/4028612/190925514-2467ee09-b55c-44f8-9b11-1ffeac08f14b.png">
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/4028612/190925519-2398367d-0b01-4f67-9f08-b2fcdaa70c55.png">

**Comment by vabene1111** [comment]
Ok, so please try again applying the preset.


The problem was that for some versions the database default for the search settings was wrong. You had one of those versions when you created your user. If you add a new user now or apply the preset for existing ones everything should work again (although I definitely need to work on search again for some other things, the next version for example will increase performance a lot )

**Comment by thelonelyrider** [comment]
I had the same issue, setting the fuzzy preset fixed it for me. But I had to chose at least one field to make this work. So I chose the title resp. name field.

But shouldn't the name of a recipe be searched out of the box?

**Comment by vabene1111** [comment]
Yes, it should also automatically be set when applying the pre set.

The search setting were implemented in an effort to give the user freedom to choose the search style but I they are confusing and introduced lots of potential for errors, we are working on that, expect to see some major improvements here in the next updates.

**Comment by jonskoglund** [comment]
I had a similar problem. Couldn't find a recipe with a regular search. The word I was looking for was both in the recipe description and in the keywords. Had to change it to this to make it work:
<img width="295" alt="Screenshot 2022-12-05 at 09 42 41" src="https://user-images.githubusercontent.com/593324/205592639-be7dac3f-c4bd-4488-a99d-4acb3fc94406.png">
Searching like this should work out of the box as @thelonelyrider mentioned before.
