### ISSUE TITLE
Allow automatic creation of admin account on first startup

### ISSUE THREAD

**Issue by max-tet** [TandoorRecipes/recipes#2049]
### Is your feature request related to a problem? Please describe.

I have Tandoor in the app store of a product I am currently building. It allows single-click installations of apps but that constrains the things that can be done during istallation a bit. The need for an admin to create an admin account in a separate step is making integration difficult.

### Describe the solution you'd like

Add a new environment variable, e.g. `ADMIN_ACCOUNT_NAME`. When present, automatically create an admin account with that name during startup. Then, the reverse proxy auth feature can be used to login.

To support cases without proxy auth, add the variable `ADMIN_ACCOUNT_PASSWORD` to set the password.

### Describe alternatives you've considered

I considered building my own docker image and creating the admin accound during the build. But that would be complicated since I would have to start the application during the docker build process. Quite awkward.

### Additional context

This feature is needed in order to fully integrate Tandoor into my product called Portal: https://getportal.org/

**Comment by vabene1111** [comment]
https://docs.djangoproject.com/en/dev/intro/tutorial02/#creating-an-admin-user
