### ISSUE TITLE
Upgrading tandoor to latest image causes web_recipes panic

### ISSUE THREAD

**Issue by Szeraax** [TandoorRecipes/recipes#2051]
### Tandoor Version

latest

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

When you update to the latest docker images, the app does not run. 

### RCA
The root cause is that the .env template was updated in https://github.com/TandoorRecipes/recipes/commit/904358bb003ab581da2f4219f90e55a010bb426c but user .env files that don't have that setting cause the app to fail. It appears that this commit was added to the image, but the commit that reverts the setting of these values was NOT added to the docker image. 

### Possible Fixes
I prefer fix 1 from below. Will look at submitting a PR if I get a few minutes. 

1. Update boot.sh to use a default workers/threads count if not specified in the env file
2. Add a release note that tells people to update their env file from template
3. Add a release note that tells people to add the worker/thread env settings to their env file.

### Workaround
Add the following lines to your tandoor .env file:

```
GUNICORN_WORKERS=1
GUNICORN_THREADS=1
```

### Relevant logs

```shell
web_recipes_1    | usage: gunicorn [OPTIONS] [APP_MODULE]
web_recipes_1    | gunicorn: error: argument -w/--workers: expected one argument
recipes1200x_web_recipes_1 exited with code 2
```

**Comment by Szeraax** [comment]
Related revert of the code: 

https://github.com/TandoorRecipes/recipes/commit/2eed5143fe26bd0f0e7af04d881d268e1aba1b8b

**Comment by Szeraax** [comment]
Here is my PR to fix this bug that I would like to see merged and published to the image: https://github.com/TandoorRecipes/recipes/pull/2052

**Comment by vabene1111** [comment]
Awesome thanks

**Comment by Szeraax** [comment]
Verified fixed. Closing issue
