### ISSUE TITLE
Receipe Keeper import is not working

### ISSUE THREAD

**Issue by BigDi** [TandoorRecipes/recipes#2054]
### Tandoor Version

1.4.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

I exported ZIP file from Receipe Keeper 3.33.2.0 pro and tried to import the file. 
Tandoor show 0 from 0 recipes will imported but the ZIP contains 337 recipes.

**Comment by vabene1111** [comment]
its possible that they changed their format, can you provide me with an example file, possibly to info@tandoor.dev

**Comment by BigDi** [comment]
Many thanks for your Support!

**Comment by BigDi** [comment]
I  have tested version 1.4.4. and I used my package with 347 recipes. After 48 imported recipes an exception happened.
Where can I find the import log?

**Comment by vabene1111** [comment]
exceptions are logged to the server console if you set `DEBUG=1` if you want feel free to send me the failing recipes and i will see what needs to be fixed.
