### ISSUE TITLE
Unable to choose which ingredient to add to the chopping list

### ISSUE THREAD

**Issue by lceWolf** [TandoorRecipes/recipes#2056]
### Tandoor Version

1.4.1-raspi-raspi

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

## Problem
When adding a recipe to the shopping list, previously one was able to mark individual items as "do not add". That way it was possible to select which ingredients are supposed to be added to the shopping list and which are not needed at the moment. 
IIRC this stopped working one version ago already.

## Use case:<br/>
I have a breakfeast recipe where I can choose from different toppings I want to get, but I do not need all of them.
Several Recipes have "optional" ingredients, ones which I do not feel like adding everytime, but now and then.
OTH there are recipes which have something like flour for example which is set to not be added to the shopping list per default. But from time to time flour has to be added to the shopping list and it was quite convenient to just tick it from the "add to shopping list" screen
Plus I liked the flexibility 😄

**Comment by vabene1111** [comment]
there is another issue for this already, i dont know why it disappeard, i must have removed it accidentally, will re-enable/find the code that did it and add it back
