### ISSUE TITLE
Add To Shopping Overhaul

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#2057]
- [x] Re add functionality to choose ingredients #1876
- [ ] add scaling for related recipes individually
- [x] fix currently on hand not working #2031

**Comment by D3v01dZA** [comment]
Not sure where to put this, I don’t use meal plan but I used to be able to select which ingredients to add to shopping from the recipe add to shopping option

**Comment by vabene1111** [comment]
yes thats the first entry of the list, i broke this and need to re-add it, thanks for the report
