### ISSUE TITLE
Nextcloud importer nutrition information

### ISSUE THREAD

**Issue by ambroisie** [TandoorRecipes/recipes#2067]
### Tandoor Version

1.4.1

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

When importing a recipe from Nextcloud Cookbook which has its nutrition information filled-up, Tandoor Recipes fails to fill-in the corresponding fields in the imported recipe.

Here's an excerpt of the JSON file for this recipe, containing the nutrition information:

<details>
<summary>JSON excerpt</summary>

```json
  "nutrition": {
    "@type": "NutritionInformation",
    "calories": "45 calories",
    "carbohydrateContent": "11.6 g",
    "cholesterolContent": "",
    "fatContent": "0.1 g",
    "fiberContent": "0.1 g",
    "proteinContent": "0.4 g",
    "saturatedFatContent": "",
    "servingSize": "",
    "sodiumContent": "226 mg",
    "sugarContent": "",
    "transFatContent": "",
    "unsaturatedFatContent": ""
  },
```

</details>

**Comment by vabene1111** [comment]
yes, nutrition is not implemented in most importers because it was added afterwards, should be an easy fix tough, thanks for reporting

**Comment by vabene1111** [comment]
fixed in next update

**Comment by ambroisie** [comment]
Thanks!
