### ISSUE TITLE
Markdown in instructions does not get rendered for some recipes

### ISSUE THREAD

**Issue by marmata** [TandoorRecipes/recipes#2093]
### Tandoor Version

1.4.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

### Bug description

Hi! I've a weird issue that I cannot seem to solve. Basically for imported recipes, while I can edit the istructions and the markdown preview renders the markdown correctly, when I save, the markdown is not rendered. Everything does work correctly when I create a recipe from scratch.
See below while I edit the text (BTW, you can use both * and - in markdown for bulletted lists, but for some reason the help file only states about the latter):
![2022-10-01 18_44_46-Window](https://user-images.githubusercontent.com/3251511/193420195-668d6a00-fc96-4639-af13-d6af86ddcbb7.png)
And here's when I view the recipe:
![2022-10-01 18_47_56-Window](https://user-images.githubusercontent.com/3251511/193420220-21b16c49-61ac-4a40-a73d-59e052a81116.png)
Any hint on what I could do wrong?

**Comment by vabene1111** [comment]
the preview is not 100% accurate as the view later uses a different parser. Please insert a line break before the list, thats the markdown spec we are using.

There are some old issues detailing this further but the short version is: will be fixed at some point. Thanks for the report.

**Comment by marmata** [comment]
> the preview is not 100% accurate as the view later uses a different parser. Please insert a line break before the list, thats the markdown spec we are using.
> 
> There are some old issues detailing this further but the short version is: will be fixed at some point. Thanks for the report.

That was totally the issue, what an idiot, sorry to have wasted your time!

**Comment by vabene1111** [comment]
no, you are not an idiot, the editor and preview indicate that this format works, it says nowhere that this is not the case. This sucks but there arn't many markdown editor packages out there and this one worked best for now, need to really improve this in the future or make sure the client editor preview is the same as the server render.
