### ISSUE TITLE
Buttons are not aligned in WEB GUI

### ISSUE THREAD

**Issue by chiaramistro** [TandoorRecipes/recipes#2102]
### Is your feature request related to a problem? Please describe.

When I landed on the Login page, I noticed that the buttons for login, registration and password reset are not aligned. When I use the website on a small viewport, the GUI looks okay, but when I switch to a bigger screen, the buttons are not nicely aligned.

### Describe the solution you'd like

I would like to see the buttons aligned nicely to have a better feel of the GUI.

### Describe alternatives you've considered

No alternatives considered.

### Additional context

![image](https://user-images.githubusercontent.com/41189322/193867854-44608ecf-ba9f-4555-9d69-8fb122d5631d.png)

**Comment by chiaramistro** [comment]
I would like to work on this enhancement :)

**Comment by amankumar11** [comment]
Can i work on the following issue ?

**Comment by chiaramistro** [comment]
Thank you @vabene1111 ! Would you be so kind to assign this issue to me? So that it is clear to everyone that I am currently working on it. Thank you

**Comment by vabene1111** [comment]
@amankumar11 please wait for @chiaramistro to work on this issue as he created it. If you want feel free to work together.
