### ISSUE TITLE
Glowing text intro 

### ISSUE THREAD

**Issue by ankita-104** [TandoorRecipes/recipes#2107]
### Is your feature request related to a problem? Please describe.

I want to work on this task.

please assign me.

### Describe the solution you'd like

This feauture is to enhance the initial UI..will provide a glowing text to welcome users to the website.
for example "WELCOME!"
this will be displayed in unit wise glowing text

**Comment by ankita-104** [comment]
please assign it to me

**Comment by vabene1111** [comment]
hi, thank you for this idea but I do not think that a glowing text "WELCOME" is appropriate for the application. What would really be useful is some kind of interactive tutorial explaning the user how certain features work, thats something i always wanted to do
