### ISSUE TITLE
When Updating: ModuleNotFoundError: No module named 'oauth2_provider'

### ISSUE THREAD

**Issue by xgrnsxs** [TandoorRecipes/recipes#2110]
Hi Folks

I had Tandoor Recipes running on Proxmox LXC for a while now and today i wanted to see if there is an update.
There is a Section "Update" on you Website https://docs.tandoor.dev/system/updating/ and another in the installation area here: https://docs.tandoor.dev/install/manual/#updating
Since the latter is more detailed and I did a manual install anyway, i figured this might be right.

However, when i run "python3 manage.py migrate" I get an error instantly. It is missing the module "oauth2_provider" I attached the whole error output in this file: [error.txt](https://github.com/TandoorRecipes/recipes/files/9733915/error.txt)

I think I am on Version 1.3.0. I made the last update on 10. Jul. 2022
Honestly i could not find any information about the version i am running. In Settings it says "Version 0.0.0"

I guess the module is missing or not the right version, but i don't know a lot about django and pip and all these dependencies. I tried to update pip and some modules like the oauth module, but i had no luck.

Could you give me some advice, what to update or clarify the instructions?

- Container is a Debian 11
- Python 3 is 3.9.2

What else do you need to know?

thanks in advance!

**Comment by smilerz** [comment]
are you updating all of the python requirements?  Via something like `pip install -r requirements.txt`

**Comment by xgrnsxs** [comment]
Hmm no, I didn't. The instructions didn't say anything about it, but yeah this makes sense.

I just tried pip install -r requirements.txt and it successfully installed a bunch of new versions. Then I tried to update again, but still, the same error pops up.

**Comment by smilerz** [comment]
Can you try `pip install django-oauth-toolkit` and try again?

**Comment by xgrnsxs** [comment]
I will try it on Sunday, I'm not @home anymore.
I will get back to you then.
Thx

**Comment by xgrnsxs** [comment]
So, today i finally got time to test.

I rolled the Container back to the snapshot, when everything was working. Then did:
`cd /var/www/recipes`
`pip install django-oauth-toolkit`
This resulted in:
`Installing collected packages: wrapt, deprecated, jwcrypto, django-oauth-toolkit
Successfully installed deprecated-1.2.13 django-oauth-toolkit-2.1.0 jwcrypto-1.4.2 wrapt-1.14.1`
Then I did
`git pull`
followed by:
`pip install -r requirements.txt`
No Errors so far. But when i do `bin/python3 manage.py migrate` i still get the same error.
Btw: should this command be executed as user "recipes" or as "root" ?

**Comment by smilerz** [comment]
> Btw: should this command be executed as user "recipes" or as "root" ?

I dont' think user matters as long as it has permissions.

Did you install tandoor under a virtual python environment?  (venv or conda)

**Comment by xgrnsxs** [comment]
I setup an LXC Container with Debian 11 and followed the manual installation instructions.
Just looked it up again and the prerequisites section says: 
> Create virtual env: python3 -m venv /var/www/recipes
So yes, i guess so.

**Comment by smilerz** [comment]
> So yes, i guess so.

can you execute the above steps again starting with `source venv/bin/activate`

**Comment by smilerz** [comment]
> So yes, i guess so.

can you try 
1. `source venv/bin/activate`
2. `cd /var/www/recipes`
3. `pip install -r requirements.txt`

if you still get the same error at that point continue with 
4. `pip install django-oauth-toolkit`

**Comment by xgrnsxs** [comment]
I tried, but...
`root@tandoor:/# source venv/bin/activate`
`-bash: venv/bin/activate: No such file or directory`
I'm a little bit confused right now. Something seems to be missing.

**Comment by xgrnsxs** [comment]
Ah lol i misunderstood.
I should have executed
`source /var/www/recipes/bin/activate`
then repeat the above steps.
I will try that now.

**Comment by xgrnsxs** [comment]
Thanks a lot! It worked.
I'm not very familiar with all this python stuff. But i think i learned a bit how all of that works.
Thx again, i will try to finish the update now.

**Comment by smilerz** [comment]
> Thanks a lot! It worked. I'm not very familiar with all this python stuff. But i think i learned a bit how all of that works. Thx again, i will try to finish the update now.

Was it necessary to manually install django-oauth-toolkit?  or was it just missing the activation of the venv?

**Comment by xgrnsxs** [comment]
I just activated the venv. But, i did not roll back the container, after installing the oauth toolkit.
I will rollback the container now and execute the steps again, in a clean environment and definite order. Maybe we can work out some a little bit more precise instructions for the update process.

**Comment by smilerz** [comment]
> Maybe we can work out some a little bit more precise instructions for the update process.

That's what I was aiming for - thanks!

**Comment by xgrnsxs** [comment]
Ok, so let's rework the update process :)
I'm glad to help.
On the rolled back container I did:
- `cd /var/www/recipes`
- `git pull`
- `source bin/activate`
- `pip install -r requirements.txt`
- `bin/python3 manage.py migrate`

This worked until the next step:
`bin/python3 manage.py collectstatic --no-input`
This fails with:
`Post-processing 'js/bootstrap-vue.min.js' failed!`
I have attached the complete log here: [collectstatic error.txt](https://github.com/TandoorRecipes/recipes/files/9792442/collectstatic.error.txt)

**Comment by smilerz** [comment]
`python manage.py collectstatic_js_reverse` after migrate (that's not the error though)

does `/var/www/recipes/cookbook/static/js/bootstrap-vue.min.js` exist?

**Comment by xgrnsxs** [comment]
Yes, that file exists. However, the filebootstrap-vue.min.js.map is missing. Which is exactly what is stated in the error message. Maybe the file is missing in the repo? :man_shrugging: :thinking:

**Comment by smilerz** [comment]
> Yes, that file exists. However, the filebootstrap-vue.min.js.map is missing. Which is exactly what is stated in the error message. Maybe the file is missing in the repo? 🤷‍♂️ 🤔

bootstrap-vue.min.js isn't in the repo and I don't believe should exist.  Try deleting it (or moving it somewhere outside the directory structure)

**Comment by smilerz** [comment]
> > Yes, that file exists. However, the filebootstrap-vue.min.js.map is missing. Which is exactly what is stated in the error message. Maybe the file is missing in the repo? 🤷‍♂️ 🤔
> 
> bootstrap-vue.min.js isn't in the repo and I don't believe should exist. Try deleting it (or moving it somewhere outside the directory structure)

instead of responding to every extra file you can also run `git clean -n .` from `/var/www/recipes/` to discover if there are other extra files left behind.

**Comment by xgrnsxs** [comment]
> instead of responding to every extra file you can also run git clean -n . from /var/www/recipes/ to discover if there are other extra files left behind.

Excellent, git clean -f removed a bunch of files, thanks. I don't know how they got there.

Still: after cleaning i get another error when I issue the collectstatic command:
`ModuleNotFoundError: No module named 'oauth2_provider'`
Again... :hankey: :rofl:  I'm still in the venv though.

**Comment by smilerz** [comment]
> > instead of responding to every extra file you can also run git clean -n . from /var/www/recipes/ to discover if there are other extra files left behind.
> 
> Excellent, git clean -f removed a bunch of files, thanks. I don't know how they got there.
> 
> Still: after cleaning i get another error when I issue the collectstatic command: `ModuleNotFoundError: No module named 'oauth2_provider'` Again... 💩 🤣 I'm still in the venv though.

Can you start from the cloned container again with these steps?

```
cd /var/www/recipes
git pull
git clean -f .
source bin/activate
pip install -r requirements.txt
pip install django-oauth-toolkit
bin/python3 manage.py migrate
python manage.py collectstatic_js_reverse
python manage.py collectstatic
```

**Comment by xgrnsxs** [comment]
I don't know, what has changed, but I rolled back the container and did the steps above. On pip install -r requirements.txt I get new errors suddenly.
I have attached them here: 
[pip install error.txt](https://github.com/TandoorRecipes/recipes/files/9792707/pip.install.error.txt)

**Comment by smilerz** [comment]
can you repeat the above and after source bin/activate run
```
venv/bin/python -m pip install --upgrade pip 
venv/bin/pip install wheel==0.37.1 
venv/bin/pip install setuptools_rust==1.1.2 
```

**Comment by xgrnsxs** [comment]
Thx a lot so far. I will test it tomorrow.

**Comment by xgrnsxs** [comment]
Ok I tested the update process and it really seems there were some too old versions of pip, rust and wheel. After the update steps, the update procedure went fine, but now the gunicorn Service won't restart.

> 2022-10-16 12:27:36 +0000] [694] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/recipes/recipes/wsgi.py", line 11, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'

**Comment by smilerz** [comment]
I’m not in front of my PC, but not finding django is extremely odd. It should be in the requirements, did it install correctly?

How are you launching the site, is it leveraging the venv?
