### ISSUE TITLE
Line breaks in receipe steps not displayed correctly (neither in lists nor normal text)

### ISSUE THREAD

**Issue by christofkac** [TandoorRecipes/recipes#2113]
### Tandoor Version

1.4.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Linebreaks do not work in lists and in normal test.
Edit mode:
![image](https://user-images.githubusercontent.com/33951830/194757901-98a533dc-ba68-40cd-9bd5-6c7b80728a55.png)
Display Mode:
![image](https://user-images.githubusercontent.com/33951830/194757906-de17fff2-29ba-44ba-aa9d-703d511a91ef.png)

Normal Text.
Edit Mode:
![image](https://user-images.githubusercontent.com/33951830/194757941-81d506e0-6b6e-40be-8d75-3542c9adfe81.png)
Display Mode:
![image](https://user-images.githubusercontent.com/33951830/194757994-7dc25a01-2c0f-4187-97f2-907f063353a4.png)

I'm using Chrome on Windows 10 in case that matters.

Looking forward to any hint.

**Comment by smilerz** [comment]
Add a line break before the list.

**Comment by christofkac** [comment]
Thanks, that worked.
And what is the trick in "normal" text? If I add there linebreaks, I get an extra space between the lines.
Not really a problem, just wanted to know if there is another trick

**Comment by christofkac** [comment]
Thanks a lot for the clarfication and the fast support!
