### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by MaiklT** [TandoorRecipes/recipes#2116]
### Describe the solution you'd like

I think it would be nice to have a full text search capability in the recipes, that searches the titles, the descriptions, the comments, the keywords, the ingredients and the recipe's texts. Do you think this is possible?

**Comment by vabene1111** [comment]
thats already implemented. It is a little rough around some edges but if you play around a bit witht the search settings it should work. 

Improvements are planned for the future.
