### ISSUE TITLE
Images not loading (image.png)

### ISSUE THREAD

**Issue by ulimanaio** [TandoorRecipes/recipes#2117]
### Tandoor Version

1.4.4

### Setup

Unraid

### Reverse Proxy

No reverse proxy

### Bug description

Hello,
I have installed TandoorRecipes using Unraid. The UI is loading kind of slow. Every click is taking a few seconds.
When I want to add an image to a recipe it shows in the preview but is not saved. 
![image](https://user-images.githubusercontent.com/95037770/195321584-869ae395-37a0-4cd9-9dd3-a18ad08ce4f2.png)
After saving it looks like this:
![image](https://user-images.githubusercontent.com/95037770/195321808-65f2ade9-8981-4ad4-be37-146bc9122399.png)

System shows: - is that causing the issue?
Medien ausliefern - Warnung (Das direkte ausliefern von Mediendateien mit gunicorn/python ist nicht empfehlenswert! Bitte folge den beschriebenen Schritten [hier](https://github.com/vabene1111/recipes/releases/tag/0.8.1), um Ihre Installation zu aktualisieren.)

I had a look in appdata and can only find time title image (appdata\recipes\media\recipes).

**Comment by vabene1111** [comment]
you cannot add a local image in markdown steps. you can load it from a url but just using logo.png does not work, at least not when really rendering, it might during preview.
