### ISSUE TITLE
Plain setup, indefinite 502 error, database authentication issues, web container restarting loop

### ISSUE THREAD

**Issue by The-Bozo** [TandoorRecipes/recipes#2123]
Fresh install using thee plain docker compose yml provided in the install directions.

Logs show that the djangouser is failing to authenticate even though the env variable file is set and using portainer I have confirmed that the ENV variables are set on each container properly.

web_recipies is also stuck in a constant restart loop

**docker-compose.yml (seperate container already using port 80)**
> version: "3"
> 
> services:
>   db_recipes:
>     restart: always
>     image: postgres:11-alpine
>     volumes:
>       - ./postgresql:/var/lib/postgresql/data
>     env_file:
>       - ./.env
> 
>   web_recipes:
>     restart: always
>     image: vabene1111/recipes
>     env_file:
>       - ./.env
>     volumes:
>       - staticfiles:/opt/recipes/staticfiles
>       - nginx_config:/opt/recipes/nginx/conf.d
>       - ./mediafiles:/opt/recipes/mediafiles
>     depends_on:
>       - db_recipes
> 
>   nginx_recipes:
>     image: nginx:mainline-alpine
>     restart: always
>     ports:
>       - 8090:80
>     env_file:
>       - ./.env
>     depends_on:
>       - web_recipes
>     volumes:
>       - nginx_config:/etc/nginx/conf.d:ro
>       - staticfiles:/static:ro
>       - ./mediafiles:/media:ro
> 
> volumes:
>   nginx_config:
>   staticfiles:

**.env variable set:**
> SECRET_KEY=*****
> TIMEZONE=America/Los_Angeles
> DB_ENGINE=django.db.backends.postgresql
> POSTGRES_HOST=db_recipes
> POSTGRES_PORT=5432
> POSTGRES_USER=djangouser
> POSTGRES_PASSWORD=****
> POSTGRES_DB=djangodb

**db_recipes log**
> Connection matched pg_hba.conf line 95: "host all all all md5"
> 2022-10-16 19:59:13.479 UTC [311] FATAL:  password authentication failed for user "djangouser"
> 2022-10-16 19:59:13.479 UTC [311] DETAIL:  Password does not match for user "djangouser".
> 	Connection matched pg_hba.conf line 95: "host all all all md5"
> 2022-10-16 19:59:14.244 UTC [312] FATAL:  password authentication failed for user "djangouser"
> 2022-10-16 19:59:14.244 UTC [312] DETAIL:  Password does not match for user "djangouser".
> 	Connection matched pg_hba.conf line 95: "host all all all md5"
> 2022-10-16 19:59:14.354 UTC [313] FATAL:  password authentication failed for user "djangouser"
> 2022-10-16 19:59:14.354 UTC [313] DETAIL:  Password does not match for user "djangouser".
> 	Connection matched pg_hba.conf line 95: "host all all all md5"
> 2022-10-16 19:59:14.445 UTC [314] FATAL:  password authentication failed for user "djangouser"
> 2022-10-16 19:59:14.445 UTC [314] DETAIL:  Password does not match for user "djangouser".
> 	Connection matched pg_hba.conf line 95: "host all all all md5"

**nginx_recipes log**
> /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
> /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
> 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
> /docker-entrypoint.sh: Configuration complete; ready for start up
> 2022/10/16 19:25:15 [notice] 1#1: using the "epoll" event method
> 2022/10/16 19:25:15 [notice] 1#1: nginx/1.23.1
> 2022/10/16 19:25:15 [notice] 1#1: built by gcc 11.2.1 20220219 (Alpine 11.2.1_git20220219) 
> 2022/10/16 19:25:15 [notice] 1#1: OS: Linux 5.15.0-47-generic
> 2022/10/16 19:25:15 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:524288
> 2022/10/16 19:25:15 [notice] 1#1: start worker processes
> 2022/10/16 19:25:15 [notice] 1#1: start worker process 24
> 2022/10/16 19:25:15 [notice] 1#1: start worker process 25
> 2022/10/16 19:25:15 [notice] 1#1: start worker process 26
> 2022/10/16 19:25:15 [notice] 1#1: start worker process 27
> 2022/10/16 19:38:41 [error] 24#24: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.1.137, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.18.0.9:8080/", host: "192.168.1.12:8090"
> 192.168.1.137 - - [16/Oct/2022:19:38:41 +0000] "GET / HTTP/1.1" 502 4295 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
> 2022/10/16 19:38:44 [error] 24#24: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.1.137, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.9:8080/favicon.ico", host: "192.168.1.12:8090", referrer: "http://192.168.1.12:8090/"
> 192.168.1.137 - - [16/Oct/2022:19:38:44 +0000] "GET /favicon.ico HTTP/1.1" 502 4295 "http://192.168.1.12:8090/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
> 2022/10/16 19:40:08 [error] 25#25: *4 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.1.137, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.18.0.9:8080/", host: "192.168.1.12:8090"
> 192.168.1.137 - - [16/Oct/2022:19:40:08 +0000] "GET / HTTP/1.1" 502 4295 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
> 192.168.1.137 - - [16/Oct/2022:19:40:10 +0000] "GET /favicon.ico HTTP/1.1" 502 4295 "http://192.168.1.12:8090/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
> 2022/10/16 19:40:10 [error] 25#25: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.137, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.9:8080/favicon.ico", host: "192.168.1.12:8090", referrer: "http://192.168.1.12:8090/"
> 

**web_recipes log**
> django.db.utils.OperationalError: FATAL:  password authentication failed for user "djangouser"
> 
> [2022-10-16 13:00:17 -0700] [14] [INFO] Worker exiting (pid: 14)
> [2022-10-16 13:00:17 -0700] [15] [ERROR] Exception in worker process
> Traceback (most recent call last):
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
>     self.connect()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
>     return func(*args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
>     return func(*args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError: FATAL:  password authentication failed for user "djangouser"
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/recipes/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
>     worker.init_process()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
>     super().init_process()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
>     self.load_wsgi()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
>     self.wsgi = self.app.wsgi()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
>     self.callable = self.load()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
>     return self.load_wsgiapp()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
>     return util.import_app(self.app_uri)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
>     mod = importlib.import_module(module)
>   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/opt/recipes/recipes/wsgi.py", line 15, in <module>
>     _application = get_wsgi_application()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
>     django.setup(set_prefix=False)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
>     app_config.ready()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django_prometheus/apps.py", line 24, in ready
>     ExportMigrations()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django_prometheus/migrations.py", line 52, in ExportMigrations
>     executor = MigrationExecutor(connections[alias])
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
>     self.loader = MigrationLoader(self.connection)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
>     self.build_graph()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
>     self.applied_migrations = recorder.applied_migrations()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
>     if self.has_table():
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
>     with self.connection.cursor() as cursor:
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
>     return func(*args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 284, in cursor
>     return self._cursor()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 260, in _cursor
>     self.ensure_connection()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
>     return func(*args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 243, in ensure_connection
>     with self.wrap_database_errors:
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
>     self.connect()
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
>     return func(*args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
>     return func(*args, **kwargs)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/opt/recipes/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> django.db.utils.OperationalError: FATAL:  password authentication failed for user "djangouser"
> 
> [2022-10-16 13:00:17 -0700] [15] [INFO] Worker exiting (pid: 15)
> [2022-10-16 20:00:17 +0000] [1] [WARNING] Worker with pid 15 was terminated due to signal 15
> [2022-10-16 20:00:17 +0000] [1] [WARNING] Worker with pid 14 was terminated due to signal 15
> [2022-10-16 20:00:17 +0000] [1] [INFO] Shutting down: Master
> [2022-10-16 20:00:17 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by smilerz** [comment]
Delete the local folder for postgresql and restart all the containers.

**Comment by The-Bozo** [comment]
amazing, that worked, thanks!
