### ISSUE TITLE
PostgreSQL version not compatible

### ISSUE THREAD

**Issue by jonskoglund** [TandoorRecipes/recipes#2126]
### Tandoor Version

1.4.4

### Setup

Others (please state below)

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Other

Portainer

### Bug description

The tandoor-db_recipes-1 container won't start because of an incompatibility issue. I have been using Tandoor for a few months now so there is data in the 'old' version 14 database. 
Because of an automatic update via Watchtower in Portainer the PostgreSQL DB became incompatible. The log file mentions a Debian version but I am running Ubuntu 20.04. That doesn't look right to me. Is there any way to fix this?
This is my Portainer stack:
```
---
version: "2"
services:
  db_recipes:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=xxxxxxxx
      - POSTGRES_PASSWORD=xxxxxxxxxx
  
  recipes:
    image: vabene1111/recipes
    container_name: recipes
    ports:
      - 82:8080
    volumes:
      - /mnt/pool1/vm/appdata/tandoor/Configs/Recipes/staticfiles:/opt/recipes/staticfiles
      - /mnt/pool1/vm/appdata/tandoor/Configs/Recipes/mediafiles:/opt/recipes/mediafiles
      - /mnt/pool1/vm/appdata/tandoor/Configs/Recipes/external_recipe:/opt/recipe/external_recipe
    environment:
      - SECRET_KEY=YOUR_SECRET_KEY
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_USER=xxxxxxxxxx
      - POSTGRES_PASSWORD=xxxxxxxxxxx
      - POSTGRES_DB=postgres
      - DEBUG=0
    restart: unless-stopped
    depends_on:
      - db_recipes
```

### Relevant logs

```shell
PostgreSQL Database directory appears to contain a database; Skipping initialization
2022-10-18 15:19:59.249 UTC [1] FATAL:  database files are incompatible with server
2022-10-18 15:19:59.249 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 15.0 (Debian 15.0-1.pgdg110+1).
```

**Comment by vabene1111** [comment]
You need to start the db on the old version, dump it and load the dump into the new version.

That's the only way to upgrade postgres major versions.

**Comment by jonskoglund** [comment]
That seems doable. I will try that.
