### ISSUE TITLE
Underline works in preview but not the actual recipe

### ISSUE THREAD

**Issue by dscottboggs** [TandoorRecipes/recipes#2129]
### Tandoor Version

1.4.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

#### Steps to reproduce:
 - create or edit a recipe
 - in the instructions box, write some text. Either bookend some of it with `++` or highlight some and click the underline key in the Instructions box toolbar.
 - Press the preview :eye: icon. Note that the text is underlined.
 - press *Save & View* or *View*

#### Expected behavior
Either of:
 - Text is displayed with an underline in the recipe, or
 - the underline feature is not present in the edit screen

#### Actual behavior
The text is displayed without underlines, with the `++` visible.

**Comment by vabene1111** [comment]
this is due to a difference between the preview rendering and the final rendering. I added an faq section explaining why this happens. Generally the rendere follows this spec https://daringfireball.net/projects/markdown/

**Comment by vabene1111** [comment]
https://docs.tandoor.dev/faq/#why-does-the-textmarkdown-preview-look-different-than-the-final-recipe
