### ISSUE TITLE
Error Deleting Certain Foods

### ISSUE THREAD

**Issue by danielharrelson** [TandoorRecipes/recipes#2130]
Unable to delete certain foods in the database:

![image](https://user-images.githubusercontent.com/6757039/197260629-19d87cbb-eb37-41f2-b209-4ded2f8f2c5a.png)

Some foods delete fine, but this one is having an issue.

Logs from HTTPD:

```
172.25.6.20 - - [21/Oct/2022:13:57:35 -0400] "DELETE /api/food/13/ HTTP/1.1" 403 85 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.25.6.20 - - [21/Oct/2022:13:57:43 -0400] "DELETE /api/food/33/ HTTP/1.1" 204 0 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.25.6.20 - - [21/Oct/2022:13:57:49 -0400] "DELETE /api/food/49/ HTTP/1.1" 204 0 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.25.6.20 - - [21/Oct/2022:13:57:58 -0400] "DELETE /api/food/43/ HTTP/1.1" 204 0 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.25.6.20 - - [21/Oct/2022:13:58:06 -0400] "DELETE /api/food/13/ HTTP/1.1" 403 85 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.25.6.20 - - [21/Oct/2022:13:59:11 -0400] "DELETE /api/food/13/ HTTP/1.1" 403 85 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
```

**Comment by Anim3shSinha** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by danielharrelson** [comment]
If I can offer up any more logs to help, let me know. 😊

**Comment by singhvaishu** [comment]
hellow sir !
please assign this project to me . i want to work on this issue.

**Comment by smilerz** [comment]
> Unable to delete certain foods in the database:
> 
> ![image](https://user-images.githubusercontent.com/6757039/197260629-19d87cbb-eb37-41f2-b209-4ded2f8f2c5a.png)
> 
> Some foods delete fine, but this one is having an issue.
> 
> Logs from HTTPD:
> 
> ```
> 172.25.6.20 - - [21/Oct/2022:13:57:35 -0400] "DELETE /api/food/13/ HTTP/1.1" 403 85 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
> 172.25.6.20 - - [21/Oct/2022:13:57:43 -0400] "DELETE /api/food/33/ HTTP/1.1" 204 0 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
> 172.25.6.20 - - [21/Oct/2022:13:57:49 -0400] "DELETE /api/food/49/ HTTP/1.1" 204 0 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
> 172.25.6.20 - - [21/Oct/2022:13:57:58 -0400] "DELETE /api/food/43/ HTTP/1.1" 204 0 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
> 172.25.6.20 - - [21/Oct/2022:13:58:06 -0400] "DELETE /api/food/13/ HTTP/1.1" 403 85 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
> 172.25.6.20 - - [21/Oct/2022:13:59:11 -0400] "DELETE /api/food/13/ HTTP/1.1" 403 85 "http://172.25.3.1:8002/list/food/" "Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
> ```

Which food in the screenshot are you trying to delete?

**Comment by danielharrelson** [comment]
Cilantro

**Comment by smilerz** [comment]
It’s likely that it is still connected to a step that isn’t part of a recipe (known condition will be addressed eventually). 

In the meantime you can resolve in 2 different ways. 

The hard way is to go into the admin interface and try to delete the food. It will fail, but will report on which Ingredient (and maybe step?) it is associated with and you can then search for those in the admin interface and delete. 

The easy way is to merge “cilantro” with “fresh cilantro” either by dragging the first onto the second or via the action menu to the right.  
If you would like “cilantro” to always be renamed to “fresh cilantro” you can “merge & automate” instead of just merge.

**Comment by riteshhon** [comment]
Hey, 
I want to contribute.

**Comment by vabene1111** [comment]
moved to #2283

**Comment by tobiashochguertel** [comment]
Is this resolved?

I have this issue atm.  and I want to fix this, but I can't do it with the django admin interface or?

**Comment by vabene1111** [comment]
No this is not resolved, its moved to another issue since it is larger than this
