### ISSUE TITLE
privacy policy to get updated to the native language

### ISSUE THREAD

**Issue by bhavyasingh75** [TandoorRecipes/recipes#2133]
### Is your feature request related to a problem? Please describe.

![Screenshot (65)](https://user-images.githubusercontent.com/102183018/197835962-067f8ed7-494a-48ad-b3b8-cb5686489d4b.png)
The privacy page is in German. I faced problem while translating it to my native language.

### Describe the solution you'd like

I really liked the concept of the website. It is a rare resource. If only this webpage has an option where the language could be translated into the native language just below the page as you scroll down.

**Comment by vabene1111** [comment]
as the hosted service is only available to german users it will be german for now, once we expand to international clients it will be updated to include english as well
