### ISSUE TITLE
Change name and logo in menu bar

### ISSUE THREAD

**Issue by xxredxpandaxx** [TandoorRecipes/recipes#2134]
### Describe the solution you'd like

An option to change the logo and name in the menu bar for further customization.

**Comment by shrehatiwari** [comment]
Hello, Can I Please solve this issue ?

**Comment by smilerz** [comment]
> Hello, Can I Please solve this issue ?

go for it

**Comment by manuelkamp** [comment]
is there a solution for that?

**Comment by Harsh-pandey9999** [comment]
i feel like working on this issue, can you please assign this issue to me so that i can work on this?

**Comment by Harsh-pandey9999** [comment]
can you please tell me what name should be changed to in the menu bar?
and how do i know what logo do you need to be updated there?
