### ISSUE TITLE
How to change Space to allow user to share recipe?

### ISSUE THREAD

**Issue by comfreak89** [TandoorRecipes/recipes#2136]
### Issue

When I want to share a recipe publicly I get this message:

`Sharing is not enabled for this space or your user account.`

It worked at some point in the past before, its probably a new security feature...how can I allow a user to share a recipe? I can not find the appropiate setting for it.

### Tandoor Version

1.4.4

### OS Version

Ubuntu 22.04 on Proxmox VM

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

**Comment by vabene1111** [comment]
its a setting that can be changed on a per space basis, have you changed anything on your space settings in the django admin interface that could have changed this ?

**Comment by comfreak89** [comment]
I am not sure, but I think that I have nothing changed in the django admin interface.
![Screenshot_1](https://user-images.githubusercontent.com/30108673/198847264-ac3df2d7-88c7-4c43-87ad-35df8d547837.png)
![Screenshot_2](https://user-images.githubusercontent.com/30108673/198847265-73eb033e-a030-429a-9e06-ccfbc34dc3c6.png)
![Screenshot_3](https://user-images.githubusercontent.com/30108673/198847266-de2390e2-4a40-4b84-9c4e-c31e0b6acc36.png)

**Comment by vabene1111** [comment]
it appears there was an issue with share link creation. Will be fixed with the next update.
