### ISSUE TITLE
Update Problem on Raspberry Pi 3

### ISSUE THREAD

**Issue by Alf-Gordon** [TandoorRecipes/recipes#2138]
### Issue

Hello,
I have an Installation of Tandoor 1.0.8 runing in a Docker compose container on a Raspberry Pi 3 with Raspian Bullseye 32 bit.
I tried to upate to 1.4.x, but I always get the Errormessage : No Manifest found for  armV7
What can I do ? 
Do I have to migrate to 64 Bit ? And when , how can i migrate my large recipes database ?

Greetings 

Alf

### Tandoor Version

1.0.8

### OS Version

Raspian Bullseye 5.15.74-v7+

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Environment file

```shell
DEBUG=0
SQL_DEBUG=0
ALLOWED_HOSTS=*
SECRET_KEY=
TIMEZONE=Europe/Berlin

DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=
POSTGRES_DB=djangodb

FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0
```

### Docker-Compose file

```shell
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
```

**Comment by Alf-Gordon** [comment]
The original Error-message is : no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by Alf-Gordon** [comment]
I finally found the solution
It works now.

**Comment by labsnoir** [comment]
Hi Alf-Gordon, I got the same problem. How did you solve it?

**Comment by labsnoir** [comment]
Just for info: on my side, I used the wrong tandoor docker image on a 32 bit OS. New setup with 64 bit os on my Raspberry Pi and everything works.
