### ISSUE TITLE
Adding ingredients to the third step during creation, adds to the second

### ISSUE THREAD

**Issue by delize** [TandoorRecipes/recipes#2139]
### Tandoor Version

1.4.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

When adding ingredients in the third step using the `Paste Ingredients` feature, it adds all pasted ingredients to the second step.

This has occurred for me twice when trying to create a recipe (manually moving the recipe from an EPUB, so copy and pasting to Tandoor).

**Comment by vabene1111** [comment]
interesting, i probably never tested this with more than one step. What i personally also dont like is that the order is not kept, there is a seperate issue for that, probably going to fix both things at once
