### ISSUE TITLE
recipe image

### ISSUE THREAD

**Issue by casimpunkt** [TandoorRecipes/recipes#2155]
### Tandoor Version

1.4.4

### Setup

Synology

### Reverse Proxy

No reverse proxy

### Bug description

Thanks for developing Tandoor recipes!

If nutritional values ​​are stored, the recipe image is only displayed very small because the space is taken up by the nutritional value display. This was not the case with version 1.3.3.

**Comment by vabene1111** [comment]
can you post a screenshot on how this looks on your screen ?

**Comment by casimpunkt** [comment]
[with nutritional values.pdf](https://github.com/TandoorRecipes/recipes/files/9914338/with.nutritional.values.pdf)
[without nutritional values.pdf](https://github.com/TandoorRecipes/recipes/files/9914340/without.nutritional.values.pdf)

**Comment by vabene1111** [comment]
Ok something definitely broke there

**Comment by rmitchellscott** [comment]
This is still happening for me on 1.4.5.
