### ISSUE TITLE
Addition of the quantities of ingredients that occur several times

### ISSUE THREAD

**Issue by twiese99** [TandoorRecipes/recipes#2157]
### Tandoor Version

1.4.4 (89a5f92ace52e8a4ee5247a5d8d76ce19c763509)

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

### Bug description

Hi, I don't know if this fits more into the bug or feature request category, but when you assign the same ingredients to the individual steps (see screenshot), they are not added together in the ingredients list.

Originally I thought it was because I used two different forms (singular and plural), which would logically be recognised as different ingredients. As a result, I adjusted the ingredient name and expected that the quantities would be added together as they are the same names / strings.

In the case of multiple ingredients without a quantity description, such as the spices salt and pepper, I would only list them once (unless you have a better idea).

Please adjust when you get a chance :)

<img width="510" alt="Bildschirm­foto 2022-11-05 um 16 13 47" src="https://user-images.githubusercontent.com/38278057/200126834-a1a9e295-08a1-4792-9ef5-f170770bcebd.png">

<img width="435" alt="Bildschirm­foto 2022-11-05 um 16 15 19" src="https://user-images.githubusercontent.com/38278057/200126869-d230759c-f7d9-46fb-abb0-5b2025bd60cb.png">

**Comment by vabene1111** [comment]
Ther are some old issues detailing why this behavior is like this currently. It is planned to add setting to change this in the future
