### ISSUE TITLE
Re posting: TandoorRecipes on a QNAP NAS

### ISSUE THREAD

**Issue by jimmyz5150** [TandoorRecipes/recipes#2165]
Hi I wanted to re new this post. 
I also am trying to get this up and running but I am a noob when it comes to Dockers.
I also want to get my Home Assistant in on the Tandoor action (which I think is setup n working looking at logs) via my database of recipes on my QNAP. 

I don't understand how to get the docker in container station to work properly.  How to point HA to QNAP?
I honestly don't know where to start. It's installed in container station so docker is there, I used _latest version_ option. Never really saw any variables to modify though, unless I missed it.
Can @vabene1111 possibly help me out? I will gladly buy you a Coffee!! ... I've been wanting to get my recipes on to HA for a while now.. somehow lol.

### Discussed in https://github.com/TandoorRecipes/recipes/discussions/1376

<div type='discussions-op-text'>

<sup>Originally posted by **mastles** January 19, 2022</sup>
My situation: 
I just got an QNAP TS-230 NAS.
I want to run TandoorRecipes in its so-called Container Station. That's designed for running Docker containers.

Has anyone of you experience with running TandoorRecipes on a QNAP NAS?
</div>

**Comment by vabene1111** [comment]
I know that people have, have you looked trough the old qnap issues if anyone explained how to do it or if there is a section in docs.tandoor.dev?

I feel like I have seen some instructions somewhere but can't really remember.

I don't have a qnap system so I can't really test anything here but I would guess that you can enter a container name and run it, for a small personal setup you can probably get away with just the app and no postgres or nginx, just make sure to mount the sqlite db then.

Maybe take a look at synology, I would guess the setups are somewhat similar,mqybe that guide can help as its quite extensive.

**Comment by jimmyz5150** [comment]
Ok thanks for responding, I guess I'll see what I can did up. Thanks for the feedback
