### ISSUE TITLE
Copy button for ingredients list

### ISSUE THREAD

**Issue by jonskoglund** [TandoorRecipes/recipes#2170]
### Is your feature request related to a problem? Please describe.

When I want to copy all the ingredients (text) from a recipe to somewhere else Tandoor doesn't format the copied text in a usable way. In my case when I use Todoist I always need to use Visual Studio Code as an inbetween.
Todoist expects each ingredient on its own line. Like this:
<img width="144" alt="Screenshot 2022-11-15 at 14 00 02" src="https://user-images.githubusercontent.com/593324/201925735-0c1eb4cb-a7cf-4442-9e75-73c25f283b33.png">
But I always get this when selecting and copying the ingredients list:
<img width="572" alt="Screenshot 2022-11-15 at 14 05 17" src="https://user-images.githubusercontent.com/593324/201926836-588fd0df-1d67-41f5-9f90-e7c2439fdaef.png">

### Describe the solution you'd like

A copy ingredients button on the top right corner of the ingredients table like this:
<img width="819" alt="Screenshot 2022-11-15 at 14 10 30" src="https://user-images.githubusercontent.com/593324/201927931-03a74155-6283-4360-bdb3-b640572e539b.png">

Another option could be:

- Copy as Markdown list

### Describe alternatives you've considered

None

### Additional context

None

**Comment by vabene1111** [comment]
may i ask why copying ingredients is necessary in the first place? Tandoor was explicitly developed to not rely on any other tools and offer a standardized, well structured view of your recipes. 
If you start to copy out stuff from tandoor it should either be fixed because the reason is a bug or tandoor might not be the recipe manager you need because you dont like the format or am I missing any reason this could be required?

**Comment by jonskoglund** [comment]
When I go shopping I use Todoist as a grocery list. There are other groceries than the ingredients from the recipe and I don’t want to switch back and forth between Tandoor and Todoist.

**Comment by vabene1111** [comment]
ok, in that case i recommend adding the ingredients to tandoors shopping list. in there you have an export option to copy various different formats to you shopping list app. There are integrations planned for shopping but those are not yet done

**Comment by jonskoglund** [comment]
Okay. Will try that for now. Thanks. And  looking forward to the shopping integrations 👍
