### ISSUE TITLE
Kitchenowl sync

### ISSUE THREAD

**Issue by Kurisutian** [TandoorRecipes/recipes#2177]
### Is your feature request related to a problem? Please describe.

The tandoor shopping list kinda feels a bit counter-intuitive especially if someone is used to the Bring app. Also the browser based approach has it's downsides to shopping lists and a distinct app just for the shopping list seems superior to me. Also somehow the shopping list in tandoor seems to be heavily focused on anything derived from recipes but items apart from that are just not intuitively to be put there and dealt with. The usability compared to a card approach like Bring has is not as good. 

### Describe the solution you'd like

Being a user of the Bring shopping list for quite some time I really favor the card like items over the plain list. Looking for a self-hosted replacement I found kitchenowl which pretty much does exactly that. It also comes with a recipe manager which of course I do not use because of tandoor. However it would be nice to connect both approaches with each other. I would really like to have my shopping list managed in kitchenowl and recipes in tandoor but keep them synced in both directions. New shopping items can be pushed to kitchenowl derived from recipes and kitchenowl can access the recipes from tandoor. I think this will be a huge improvement as dealing with both shopping lists manually does not really save much time and the card layout seems to be more intuitive. Sure kitchenowl misses clustering for shops (if needed) which is a really good thing but coming with an own app and the layout (and optionally keeping track of expenses) makes it a great alternative to look at for shopping lists.

**Comment by Friendly-Banana** [comment]
There is an unofficial app for Tandoor https://github.com/phantomate/Untare with support for shopping lists.

**Comment by Kurisutian** [comment]
> There is an unofficial app for Tandoor https://github.com/phantomate/Untare with support for shopping lists.

Thanks for the hint. But it's totally different than the Kirchenowl app when it comes to shopping lists. However, it's a great frontend for all my recipes in tandoor so I installed it anyway.
Kirchenowl is still to me the better shipping list app the way the lists are designed. Combining those or actually using the same visualization for items to shop would make it perfect is you ask me.

**Comment by vabene1111** [comment]
hi, I personally like the shopping list in tandoor but I agree that it is very "technical" and sometimes a bit clunky. There has been countless feeback on this, for me there are two takeaways

- implement some kind of system to sync the lists with external services (was always planned but highly depends on the interoperability of the external app)
- look at how common shopping list apps realize the list and maybe learn something from it to improve tandoors native shopping list. 

apart from that offline support is planned as well

syncing with kitchenowl does not make much sense for me as it would only be a solution if we accept that tandoor is unable to implement a proper shopping list (which i do not think), other than that I do not see that it is useful to use both applications at the same time as so much of the features overlap.

**Comment by Kurisutian** [comment]
I totally agree, multiple apps for the same purpose are very redundant and most likely not needed. 
The intention was more based on the view to re-use apps rather than reinvent the wheel. 
Nevertheless the Shopping List using tiles (like KitchenOwl or Bring) makes it somehow very easy to handle things.
Personally I do only store the most valuable recipes in Tandoor so sometimes I need to add things to the shopping list which do not come out of a certain recipe. Doing that kinda feels a lot easier with KitchenOwl than the "traditional" approach from Tandoor. Also it makes crossing out items during shopping at least to me a lot easier than classical lists also reducing crossing out the wrong items by accident (as the tiles are bigger than the listed items). So from an UX point of view there is a very high value in the tile UI approach. At least the way I've dealt with it in the past either there or in bring. Also not to forget, the WAF is way higher with it than with classical or worse "more technical" lists ;-)

**Comment by vabene1111** [comment]
thanks for the feedback, i will look into this when working on improving the shopping list UI in the future. Closing this for now but its referenced in my internal notes for this.
