### ISSUE TITLE
description in shopping list

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#2178]
### Is your feature request related to a problem? Please describe.

In ```Edit food``` I set a description for the food e.g. the brand.

### Describe the solution you'd like

Please add this comment field in the details in shopping list

**Comment by chloec2** [comment]
I would like to take this issue!

**Comment by vabene1111** [comment]
could be in the expanded view, probably a good idea

**Comment by vabene1111** [comment]
implemented in new shopping list
