### ISSUE TITLE
Hide ingredients from steps?

### ISSUE THREAD

**Issue by ck3mp** [TandoorRecipes/recipes#2183]
### Issue

Is it possible to hide the ingredients in the steps? I know they can be summarised at the top but I prefer to just have that and then the steps listed?

![image](https://user-images.githubusercontent.com/37331850/203523835-5a79d005-2ea9-4637-8ccc-0c39d03d0d42.png)

### Tandoor Version

1.4.4

### OS Version

Fedora CoreOS 36

### Setup

Kubernetes

### Reverse Proxy

Others (please state below)

### Other

HAProxy

**Comment by vabene1111** [comment]
there is a very old issue somewhere wishing for this, i have not gotten around to adding that but it will be implemented
