### ISSUE TITLE
move and scroll ingredient in edit recipe

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#2186]
### Tandoor Version

1.4.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

In Recipe Edit view I have a lot of ingredients and a long instructions text. I want to split the ingredients in multiple steps. 

If the instruction text is too long I cannot move the ingredient to the other step because scrolling is not possible when dragging the item.

**Comment by Sooyoung98** [comment]
Hey! My team and I are interested in tackling on this issue for our [class assignment](https://cmu-313.github.io//assignments/hw6). Would it be fine for us to make a pull request?

**Comment by vabene1111** [comment]
planned as part of the recipe editor rework project
