### ISSUE TITLE
Ingredients don't import from www.waitrose.com

### ISSUE THREAD

**Issue by SiJiL82** [TandoorRecipes/recipes#2188]
### Tandoor Version

1.4.5

### Import URL

https://www.waitrose.com/home/recipes/recipe_directory/s/sausage_and_apple_toad_in_the_hole.html

### When did the issue happen?

When pressing the search button with the url

![image](https://user-images.githubusercontent.com/65114782/204104961-097d16e9-6dc7-4b3d-b8dd-52c14297dde2.png)

**Comment by vabene1111** [comment]
it appears that the page does not contain any kind of structured data that could be parsed. Feel free to open an issue over on https://github.com/hhursev/recipe-scrapers so that maybe someone there implements a custom parser for it
