### ISSUE TITLE
Hide ingredients list so they aren't shown twice

### ISSUE THREAD

**Issue by rinosaur681** [TandoorRecipes/recipes#2201]
### Is your feature request related to a problem? Please describe.

I understand the reasoning behind having the list of ingredients at the top and then separated out into each step. But it would be good to have an option in the settings to hide the ingredients from the steps so that they are only shown at the top.

![image](https://user-images.githubusercontent.com/93617243/205898950-5d06c9d2-14ac-439c-bb48-511ad3048278.png)

### Describe the solution you'd like

An toggle in the cosmetic settings for example where it could be "hide ingredients from steps" so that they are only shown at the top and not again later down in the recipe.

**Comment by cinderblockgames** [comment]
Edit > Additional Options > Ingredients Overview > Display a list of all ingredients at the start of the recipe.

**Comment by rinosaur681** [comment]
That's great thanks very much I hadn't noticed the additional options area. Is there any way to do the reverse of this?
