### ISSUE TITLE
Ingredients list doesn't update when adding new steps

### ISSUE THREAD

**Issue by cinderblockgames** [TandoorRecipes/recipes#2202]
### Tandoor Version

1.4.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

If you import a recipe with two steps then add additional steps in the edit view, the summary ingredients at the top don't show the additional steps.

**Comment by vabene1111** [comment]
can you post a screenshot as an example because this is something i really cant imagine how its happening.

**Comment by cinderblockgames** [comment]
I can no longer recreate, so closing.
