### ISSUE TITLE
Button to make all comments visible permanent

### ISSUE THREAD

**Issue by falcon10001** [TandoorRecipes/recipes#2208]
### Describe the solution you'd like

For each Ingredient in the receipe a comment can be added.
At the moment I have to hover over the comments in order to see the content.
If you have many comments, you have to look at each one after another, which could be annoying.
A little button would be helpful, so that all comments can be seen immedeately and permanent.

Many Thanks

**Comment by vabene1111** [comment]
hi, thanks for the request. I am not sure where exactly but i know there is an open issue for this so i am closing this one. Will take a look at some point when reworking the UI of the recipe view but did not yet have a good idea on how to really nicely implement this.

**Comment by falcon10001** [comment]
Hi,  many thanks for the feedback.

Perhaps just a proposal to place the button here:
***@***.***

When the row then extends, the picture coulld either be shrinked, as it is already the case, or the picture could be switched off.
So no redesign would be needed.

Thanks&Regards
Dirk

Von: vabene1111 ***@***.***
Gesendet: Donnerstag, 15. Dezember 2022 20:40
An: TandoorRecipes/recipes ***@***.***>
Cc: ***@***.***; Author ***@***.***>
Betreff: Re: [TandoorRecipes/recipes] Button to make all comments visible permanent (Issue #2208)


hi, thanks for the request. I am not sure where exactly but i know there is an open issue for this so i am closing this one. Will take a look at some point when reworking the UI of the recipe view but did not yet have a good idea on how to really nicely implement this.
