### ISSUE TITLE
django-allauth broken

### ISSUE THREAD

**Issue by ciphermenial** [TandoorRecipes/recipes#2210]
### Tandoor Version

1.4.5

### Setup

Manual Setup

### Reverse Proxy

Others (please state below)

### Other

haproxy

### Bug description

[0.51.0](https://github.com/pennersr/django-allauth/releases/tag/0.51.0) of django-allauth does not correctly work with django 4.1.

I updated to current by running ```pip install git+https://github.com/pennersr/django-allauth``` which install it to 0.52.0.dev0. Everything is working as expected after this.

**Comment by vabene1111** [comment]
thanks for the information, i will fix this for the next release the last released version should be fine as the versions are locked i think

**Comment by vabene1111** [comment]
ok so need to decide, next release will probably be a while but if django allauth does not publish a release till then might need to go back to django 4.x which would also be fine.

**Comment by vabene1111** [comment]
allauth has been updated to 0.52.0 which now offically supports django 4.1
