### ISSUE TITLE
(Re-)Import of recipes from the file system

### ISSUE THREAD

**Issue by lostwald** [TandoorRecipes/recipes#2218]
### Tandoor Version

1.4.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

I want to import some recipes from the file system. To get to know the file formats I had a look at the created exports (Default, Saffron, Recipe Sage). My goal was to write some code to convert some recipes that I have in a custom format.

As a first test I just changed the name in exports of recipes created with Tandoor and tried to re-import them. I used import selected "app" and then the previously created file. The check to import duplicates was activated. However I generally do not succeed to import any of the exports created with Tandoor. I always end up with 0 imported recipes and the following details: "ERROR An unexpected error occurred during the import. Please make sure you have uploaded a valid file. Imported 0 recipes.".

Example files:
Default (renamed to txt so I can upload it here)
[recipe.json.txt](https://github.com/TandoorRecipes/recipes/files/10249874/recipe.json.txt)
(Recipe Sage)
[Der beste Pizzateig.txt](https://github.com/TandoorRecipes/recipes/files/10249869/Der.beste.Pizzateig.txt)

As the import from Websites works flawlessly, is there some issue importing from the file system?

**Comment by vabene1111** [comment]
website and app are two very different topics. An export from tandoor should be importable again (use the same file, dont unpack/change anything).

Each app works differently and  you will need to change your source files very carefully or else it will not work. If you know how to script i would recommend just using the API to create recipes from custom files.
