### ISSUE TITLE
URL import fails, but pasting the HTML works

### ISSUE THREAD

**Issue by jschwalbe** [TandoorRecipes/recipes#2219]
### Tandoor Version

1.4.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Trying URL import of "https://www.cookbooks4u.com/recipe/3649482/slow-cooker-zuppa-toscana-copycat.html" fails with the error `There was an error fetching a resource!`

But if I paste the HTML code into the Source tab, it works. 

### Relevant logs

```shell
(not sure which logs would be necessary or helpful)
```

**Comment by vabene1111** [comment]
many sites prevent accessing them programatically so this is not something completely unexpected. Thats why we have the option to import html directly or use the bookmarklet. 

Thanks for reporting but if the page das not want to be accessed we wont do that (in part for legal reasons).
