### ISSUE TITLE
Recipe Description Character Limit

### ISSUE THREAD

**Issue by richamc01** [TandoorRecipes/recipes#2221]
### Is your feature request related to a problem? Please describe.

It seems that there is a limitation of 512 characters allowed to be entered in the description field of a recipe. 

### Describe the solution you'd like

Unless this is a database limitation or I am missing something in the admin settings, it would be great if the character limitation could be increased.

**Comment by vabene1111** [comment]
Thanks for the request. The description is short so that I am able to display it somewhat safely at different parts of the application and so that the user gets a short note to the recipe.

That's why it's limited to 512.
