### ISSUE TITLE
Adding and moving ingredients

### ISSUE THREAD

**Issue by Jokersmile4711** [TandoorRecipes/recipes#2232]
### Tandoor Version

1.4.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Synology

### Bug description

Hi,
I want to split a recept into multiple steps. But if I do this (for example "1 tomate" step 1, "1 tomate" step 2, I don't get a summary number of tomatos. It seems that the incredients get appended.

And I have not found a way to move ingredients to other steps in a recipe with only one step. So I have created a new ingredient accordingly.

Step 1
![image](https://user-images.githubusercontent.com/91393403/209541386-2a387391-51eb-4c84-af04-d197264f88e4.png)
Step 2
![image](https://user-images.githubusercontent.com/91393403/209541424-56ac0f50-434a-420f-8056-64cd527bbab6.png)
Summary
![image](https://user-images.githubusercontent.com/91393403/209541489-0451ea3e-d20a-4755-a28d-47755276e95c.png)

**Comment by vabene1111** [comment]
The top list does not sum the ingredients. This is on purpose. There is an issue somewhere to enable summing in the header but its not implemented yet.

**Comment by vabene1111** [comment]
Moving works using drag and drop, it's planned to add a button to make this easier.
