### ISSUE TITLE
Export of recipes failed

### ISSUE THREAD

**Issue by update-freak** [TandoorRecipes/recipes#2234]
### Tandoor Version

1.4.5

### Setup

Synology

### Reverse Proxy

Others (please state below)

### Other

buildin functionality in DSM (Synology)

### Bug description

Hello developer,

I used the instructions on this website https://mariushosting.com/how-to-install-tandoor-recipes-on-your-synology-nas/ to install Tandoor on Synology in Docker.
For testing I created a recipe "Spaghetti Bolognese" and tried to export this one.
Unfortunatelly the export failed (I also tried different settings in the export options).

If logs are required please let me know.

![export_error](https://user-images.githubusercontent.com/40196995/209673257-1a666e53-53fa-4f94-ac6a-3f80333c162f.png)

**Comment by vabene1111** [comment]
please provide some logs so we can take a look.

**Comment by update-freak** [comment]
how is it possible to create a log?

**Comment by vabene1111** [comment]
set `DEBUG=1` in your `.env` file (or UI) and post the output of the container logs, I sadly have no idea how this works on synology but the container should show some logs somewhere

**Comment by update-freak** [comment]
ok, thanks. Here is the log. I changed the DynDNS-address and the cookie

`Gunicorn Media: False
Sqlite: False
Debug: True

SERVER_PROTOCOL:HTTP/1.0
REMOTE_ADDR:172.22.0.4
SERVER_PORT:8080

HTTP_HOST:changeddyndns.spdns.org:1046
HTTP_CONNECTION:close
HTTP_X_REAL_IP:xx.xxx.xx.xxx
HTTP_X_FORWARDED_FOR:xx.xxx.xx.xxx
HTTP_X_FORWARDED_PROTO:https
HTTP_SEC_CH_UA:"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
HTTP_SEC_CH_UA_MOBILE:?0
HTTP_UPGRADE_INSECURE_REQUESTS:1
HTTP_USER_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
HTTP_SEC_CH_UA_PLATFORM:"Windows"
HTTP_SEC_FETCH_SITE:same-origin
HTTP_SEC_FETCH_MODE:navigate
HTTP_SEC_FETCH_DEST:empty
HTTP_REFERER:https://changeddyndns.spdns.org:1046/space-manage/1
HTTP_ACCEPT_ENCODING:gzip, deflate, br
HTTP_ACCEPT_LANGUAGE:de-DE,de;q=0.9
HTTP_COOKIE:csrftoken=changed; sessionid=changed

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f3ef7903af0>
wsgi.version:(1, 0)
wsgi.multithread:True
wsgi.multiprocess:True
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x7f3ef7d431f0>
wsgi.url_scheme:http`

**Comment by vabene1111** [comment]
sorry but this is not the log, its the debug info from the system page (which can be confusing but sadly does not help me in this case). 

I need the container and browser console logs. 

Also: does it always fail or sometimes work?

**Comment by update-freak** [comment]
here is the log from portainer:
[_Tandoor_logs.txt](https://github.com/TandoorRecipes/recipes/files/10337023/_Tandoor_logs.txt)

And here is the screen from chrome (I hided my dyndns-adress there):
![2023-01-03 14_49_46-Einstellungen](https://user-images.githubusercontent.com/40196995/210370291-9a349eb1-417e-4a58-bbcf-499cc9b4bfaa.png)

**Comment by vabene1111** [comment]
interesting, this appears to be the same issue as #2166

**Comment by update-freak** [comment]
ok.
When it's maybe related to a setup issue, here is the docker compose to check.

`version: "3.9"
services:
  db:
    image: postgres
    container_name: Tandoor-DB
    hostname: tandoor-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "recipes", "-U", "recipesuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    user: 1026:100
    volumes:
      - /volume1/docker/tandoor/db:/var/lib/postgresql/data
    env_file:
      - stack.env
    restart: always

  tandoor:
    image: vabene1111/recipes:latest
    container_name: Tandoor
    hostname: tandoor
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
    user: 1026:100
    volumes:
      - /volume1/docker/tandoor/staticfiles:/opt/recipes/staticfiles
      - /volume1/docker/tandoor/mediafiles:/opt/recipes/mediafiles
      - /volume1/docker/tandoor/nginx:/opt/recipes/nginx/conf.d
    env_file:
      - stack.env
    restart: always
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:mainline-alpine
    container_name: Tandoor-NGINX
    hostname: nginx-tandoor
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1
    volumes:
      - /volume1/docker/tandoor/staticfiles:/static:ro
      - /volume1/docker/tandoor/mediafiles:/media:ro
      - /volume1/docker/tandoor/nginx:/etc/nginx/conf.d:ro
    ports:
      - 9815:80
    env_file:
      - stack.env
    restart: always
    depends_on:
      tandoor:
        condition: service_healthy`

**Comment by update-freak** [comment]
@moritz453
Can you please check if this issue also appear in your setting (because you have also used the same setup explanation as I)

**Comment by vabene1111** [comment]
i have also updated the beta image, this might resolve your issue (careful downgrading not possible and beta is not tested yet so maybe backup before).

**Comment by update-freak** [comment]
ok, thanks.
Where can I find the beta release?

**Comment by vabene1111** [comment]
You can cha he the tag in the docker compose image

**Comment by update-freak** [comment]
I can confirm that the export with the beta version will work for me (Synology Docker Setup).

![export](https://user-images.githubusercontent.com/40196995/211471272-5656305e-996d-42fc-a973-e0a351c0e843.png)

**Comment by vabene1111** [comment]
perfect, then I will close this issue.
