### ISSUE TITLE
Multiple users for self hosted Tandoor instance

### ISSUE THREAD

**Issue by update-freak** [TandoorRecipes/recipes#2235]
### Is your feature request related to a problem? Please describe.

Hello developer,

it would be nice if I could add more than one user for Tandoor.
I checked the settings and didn't found a option to create additional users. If there is this functionally already included please let me know.

I used the instructions on this website https://mariushosting.com/how-to-install-tandoor-recipes-on-your-synology-nas/ to install Tandoor on Synology in Docker.
![space_settings](https://user-images.githubusercontent.com/40196995/209673675-bd77ad5d-8b50-4de8-8d3a-183ccdf59f9f.png)

### Describe the solution you'd like

Possibility to have more than one user.

### Describe alternatives you've considered

I checked the settings and didn't found a option to create additional users.

**Comment by vabene1111** [comment]
please go to the space settings page and generate an invite link. you can send that to the people you want to add.

**Comment by update-freak** [comment]
As you can see from the screenshot, I have no further settings in the space settings, so it's not possible for me to send such a link.

**Comment by vabene1111** [comment]
it appears that something with your space settings page is broken, if that works inviting users will work as well. Since the settings page works for other instances this is either an edge case or setup issue. please follow this issue and/or provide the information asked for there to help investigating #2241
