### ISSUE TITLE
importer assigns all ingredients to step 0

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#2238]
### Is your feature request related to a problem? Please describe.

Importer should assign ingredients to the first step they are mentions in on a best-effort base.

### Describe the solution you'd like

The Python-Method I wrote to do this in January is a simple
```
def find_step_for_ingredient(steps, ingredient):
    for step in steps:
        if ingredient.food.name in step.instruction:
            return step
    return steps[0]
```

A similar function could be implemented in vue/src/apps/ImportView/ImportStepEditor.vue 
where the current implementation is
```
/**
         * utility function used by splitAllSteps and splitStep to split a single step object into multiple step objects
         * @param step: single step
         * @param split_character: character to split steps at
         * @return array of step objects
         */
        splitStepObject: function (step, split_character) {
            let steps = []
            step.instruction.split(split_character).forEach(part => {
                if (part.trim() !== '') {
                    steps.push({'instruction': part, 'ingredients': []})
                }
            })
            steps[0].ingredients = step.ingredients // put all ingredients from the original step in the ingredients of the first step of the split step list
            return steps
        },
```

### Describe alternatives you've considered

Do it in Python, but I don't understand the new Import enough to make an alternative proposal.

**Comment by vabene1111** [comment]
interesting idea to split of based on name. I am not sure if people will be confused about this when we do it automatically because the automation will most certainly get it wrong sometimes so it might be better to add a button "smart sort ingredients" (or something similar), what do you think?

**Comment by MarcusWolschon** [comment]
With 246 recipes imported, that simple rule already worked quite fine.
A few times a plural name couldn't be found or half of an ingredient was used early and half in a later step.

A button still sounds like a good idea. 
I'd suggest to give it a text-label and not just an icon and to enable it only when there are >1 steps.

**Comment by vabene1111** [comment]
that sounds like a good idea, will look into adding it.

**Comment by vabene1111** [comment]
Ok so I have implemented a two step approach with a button on the importer page

1. the algorithm searches for a direct match of a substring of instrucitons with the food name
2. if no full match is found a similarity function is applied to each word in each step, the best match from each step is wieghted against each other with the first step in order taking presedence. 

This can also be applied multiple times if after splitting a recipe at first and not being happy one decides to split or merge again.
