### ISSUE TITLE
Wrong update of the docker-compose.yml for plain install

### ISSUE THREAD

**Issue by CL0Pinette** [TandoorRecipes/recipes#2240]
### Documentation link

https://docs.tandoor.dev/install/docker/#docker-compose

### Affected section

Installation

### Issue description

It looks like 37bd2017b01458b01bda29c7b919d36c931d47e3 changed the ports from the nginx container to tandoor. However, the default usage is by serving media files and static files with nginx : tandoor is configured not to serve media files by default [.env.template:69](https://github.com/TandoorRecipes/recipes/blob/develop/.env.template#L69).

If we change these ports, we should also update the default .env so that the media files are served by default by the tandoor container; otherwise, they are just not served at all.

**Comment by vabene1111** [comment]
thanks for letting me know, i need to look into that, i do not really like to change to tandoor serving media as thats not recommended but it should work overall,

**Comment by vabene1111** [comment]
ah i just see that this change has already been reverted but since the docs only refresh when tandoor has a new release the old one is still in the docs, sorry for the confusion. Not sure when i will get a version running ready for release but then the docs will be updated.
