### ISSUE TITLE
Issues with the "space settings" page

### ISSUE THREAD

**Issue by moritz453** [TandoorRecipes/recipes#2241]
### Issue

I can not for the life of me figure out how to make the space settings page work.
When I open the site I get the following issue:

![Screenshot_2022-12-30_20 22 40@2x](https://user-images.githubusercontent.com/71669090/210106098-d54deb14-533a-44a4-9aeb-c2766f4bd226.png)

Everything else works just fine. I just can't open the settings, so I can not create a second account on the same space.
Please let me know if anyone has seen this issue and what I need to do to get it resolved. (A workaround where I create a user in the space some other way would also work for me.)
I am new to self-hosting, so I am unsure about what I need to post for my question to make sense. Please let me know if you need any information that is not in the post.

I used the instruction from there: https://mariushosting.com/how-to-install-tandoor-recipes-on-your-synology-nas/

I would be grateful for any help you can give.

### Tandoor Version

1.4.5

### OS Version

Synology DSM 7.1 (through Docker)

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Synology's Built in

**Comment by vabene1111** [comment]
Please post possible logs from the browser console.

Also try clearing all site data or testing in an incognito or other browser.

**Comment by moritz453** [comment]
Thank you for your answer.
I have tried on multiple devices and even created a new super-user. I still had the same issue.

I am sure its something silly.
Here are the logs:
Gunicorn Media: False
Sqlite: False
Debug: False

SERVER_PROTOCOL:HTTP/1.0
REMOTE_ADDR:192.168.112.4
SERVER_PORT:8080

HTTP_HOST:tandoor.****.com
HTTP_CONNECTION:close
HTTP_X_REAL_IP:84.113.42.74
HTTP_X_FORWARDED_FOR:84.113.42.74
HTTP_X_FORWARDED_PROTO:https
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
HTTP_UPGRADE_INSECURE_REQUESTS:1
HTTP_USER_AGENT:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
HTTP_SEC_GPC:1
HTTP_ACCEPT_LANGUAGE:en-GB,en
HTTP_SEC_FETCH_SITE:same-origin
HTTP_SEC_FETCH_MODE:navigate
HTTP_SEC_FETCH_DEST:empty
HTTP_REFERER:https://tandoor.****.com/space-manage/1
HTTP_ACCEPT_ENCODING:gzip, deflate, br
HTTP_COOKIE:shopping_settings=%7B%22ui%22%3A%7B%22entry_mode_simple%22%3Atrue%7D%2C%22settings%22%3A%7B%22entrymode%22%3Atrue%7D%7D; csrftoken=8YMEMkg64GEf4Y9332uz7THkcAGLAMMaukRHPWe9WpA0DO74xsaKWitvFicGCeCJ; sessionid=jl7ayvpvac669irm6scl50p11y80uqss

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f5c1cab3280>
wsgi.version:(1, 0)
wsgi.multithread:True
wsgi.multiprocess:True
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x7f5c1cc92c20>
wsgi.url_scheme:http

**Comment by vabene1111** [comment]
thanks for these logs and the answer. Can you open the browser console (in chrome that F12) and see if any errors are shown there ?

**Comment by update-freak** [comment]
I have got the same issue and also used the linked explanation from marius hosting.
I tried F12 in Chrome. I attached the picture:
![2023-01-01 14_37_56-](https://user-images.githubusercontent.com/40196995/210172600-e108414f-34b1-4c02-a52c-dbe3061059a9.png)

**Comment by moritz453** [comment]
I have the same issue as posted by @update-freak.

**Comment by vabene1111** [comment]
that is very interesting, can you go to the system page and check the current version you are using because this sounds like something that broke on develop?

**Comment by moritz453** [comment]
Certainly.
I made a screenshot: 
<img width="1058" alt="Screenshot_2023-01-02_18 18 40@2x" src="https://user-images.githubusercontent.com/71669090/210262384-1fcb9b26-adaf-47fe-affc-298e0f342428.png">

**Comment by update-freak** [comment]
here is my system information:

![2023-01-02 19_36_12-Kochbuch-Setup](https://user-images.githubusercontent.com/40196995/210268393-e6300ca4-6deb-4608-bf31-a589c984fd50.png)

**Comment by vabene1111** [comment]
this is very strange. 
The hosted version runs on 1.4.5 as well and works perfectly fine without any problems. You could try downgrading to 1.4.4 or 1.4.2 to see if this resolves your issue. 

Generally the url issue points to the static reverse file not being generated correctly, i would need the container startup logs to verify that, you can find those normally by running `docker-compose logs -f` but i am not sure how to do this on synology, i would think it should be a button next to the running docker container.

**Comment by vabene1111** [comment]
the error you are showing is actually what prevents the page from working. Its the file/script that tells the frontend where all the URLs are. I know it is broken in the development version #2211 but I tought it worked in 1.4.5 because i have a running instance with 1.4.5 that is. 

One thing you could try just out of curiosity is downgrading to 1.4.3, starting the container and then upgrading again. If that fixes it it was always broken in 1.4.5 but we just did not notice because the static files were saved and i did not see the error booting the container.

**Comment by moritz453** [comment]
Thank you so much for taking the time to actually help me sort through this stuff. I really appriciate the time you take to help me (and others)!!! 

So, I tried to downgrade to the docker 1.4.3 version. I changed the compose file to fetch the according file from the repo.
It seems that I get the same issue.

For fun I then updated to the develop version, since I saw you updated it (on docker hub), and that fixed the issue for me.
So whatever fix you deployed there, did indeed help solve the problem for me!

Here are the logs from startup (of version 1.4.3).

```
No migrations to apply.
Generating static files
Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django_js_reverse/management/commands/collectstatic_js_reverse.py", line 38, in handle
    fs.delete(file)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/files/storage.py", line 355, in delete
    os.remove(name)
PermissionError: [Errno 13] Permission denied: '/opt/recipes/cookbook/static/django_js_reverse/reverse.js'
0 static files copied to '/opt/recipes/staticfiles', 643 unmodified, 1384 post-processed.
Done
[2023-01-06 21:41:02 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-01-06 21:41:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2023-01-06 21:41:02 +0000] [1] [INFO] Using worker: gthread
[2023-01-06 21:41:02 +0000] [12] [INFO] Booting worker with pid: 12
[2023-01-06 21:41:02 +0000] [13] [INFO] Booting worker with pid: 13
[2023-01-06 21:41:02 +0000] [14] [INFO] Booting worker with pid: 14
127.0.0.1 - - [06/Jan/2023:22:41:09 +0100] "GET / HTTP/1.1" 302 0 "-" "Wget"

**Comment by vabene1111** [comment]
yes develop fixes the issue, I will likely release a beta image in a few days or so so people who are having problems with 1.4.5 can use that instead. 

Closing this as I think develop has this resolved.
