### ISSUE TITLE
Remove advertisement from description

### ISSUE THREAD

**Issue by Friendly-Banana** [TandoorRecipes/recipes#2253]
### Tandoor Version

1.4.5

### Import URL

https://www.chefkoch.de/rezepte/460771139185700/Schnelles-Thai-Curry-mit-Huhn-Paprika-und-feiner-Erdnussnote.html

### When did the issue happen?

On importing, chefkoch.de always adds a some kind of advertisement to the description. The text varies: ` Über <number> Bewertungen und für <one or more adjectives> befunden. Mit ► Portionsrechner ► Kochbuch ► Video-Tipps! Jetzt entdecken und ausprobieren! <Optional sentence>`
I have updated my database with a regex to remove all of these, but not importing them would be better.

the regex: ` Über \d+ Bewertungen und für .+ befunden\. Mit ► Portionsrechner ► Kochbuch ► Video-Tipps.*`

database command:
```sql
UPDATE cookbook_recipe SET description = regexp_replace(description, ' Über \d+ Bewertungen und für .+ befunden\. Mit ► Portionsrechner ► Kochbuch ► Video-Tipps.*', '');
```

**Comment by vabene1111** [comment]
This is one of the things i wanted automations to be able to do. I will look into it when I find the time but I have the exact same issue wiuth chefkoch.de

**Comment by Friendly-Banana** [comment]
How do automations work? Maybe I could write that one.

**Comment by vabene1111** [comment]
hi, i liked the idea so much that i already started working on it. 

Some first hints at how it works can be found in https://github.com/TandoorRecipes/recipes/blob/feature/import-automation/docs/features/automation.md 

6176eeb024df6b6db78c910114bdf489c8571720

its already working quite well, just a few more things to do which i will track in #2255

**Comment by Friendly-Banana** [comment]
Great, thanks. 😂love your enthusiasm
