### ISSUE TITLE
Planner won't open because of Calendar component js issue

### ISSUE THREAD

**Issue by iamkarlson** [TandoorRecipes/recipes#2256]
### Tandoor Version

develop

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Tandoor worked fine for me, and then I upgraded for the latest version from develop. Now some vue components are failing with the following issue at `/plan`: 

```
chunk-vendors.js:1061 TypeError: ((e.dateClasses && e.dateClasses[e.isoYearMonthDay]) || null) is not iterable
    at chunk-vendors.js:1055:71180
    at a.Ft [as _l] (chunk-vendors.js:1061:14350)
    at chunk-vendors.js:1055:70600
    at a.Ft [as _l] (chunk-vendors.js:1061:14350)
    at a.r (chunk-vendors.js:1055:70203)
    at e._render (chunk-vendors.js:1061:20103)
    at a.r (chunk-vendors.js:1061:24095)
    at e.get (chunk-vendors.js:1061:33537)
    at e.run (chunk-vendors.js:1061:34274)
    at Kn (chunk-vendors.js:1061:26282)
```

Browser: vivaldi
Tandoor version: `develop`

**Comment by vabene1111** [comment]
you have a completely standard 1.4.5 docker container ?

can you post the logs from the container starting up and also from when openeing the plan (docker compose logs -f)

**Comment by iamkarlson** [comment]
standard container doesn't work for me because of the migrations so I'm just rebuilding from the repo

**Comment by vabene1111** [comment]
Ok so then I would say that you have an issue somewhere in the generation of the frontend. Either yarn or Django js reverse

Need the container logs to say which

**Comment by iamkarlson** [comment]
Alright, I was trying to debug the app locally, but it turned out incredibly difficult to set up my local env, so I gave up. Instead, I manually deleted migrations from `develop` and switched to the `1.4.5` release. The problem is gone. It's not very constructive, as the problem indeed occurs in the latest revision, but I'm not sure if I can help here any further.

**Comment by Kaibu** [comment]
Issue resolved via a hacky fork, has to be properly swapped in the future
