### ISSUE TITLE
Make deleting recipes easier

### ISSUE THREAD

**Issue by besendorf** [TandoorRecipes/recipes#2263]
### Is your feature request related to a problem? Please describe.

At the moment when you want to delete a recipe you have to click the 3 dots, select "Edit" and then click delete on the new page. 

### Describe the solution you'd like

I think it would make be easier to add a "delete" option to the 3 dots menu. There is still a confirmation dialog afterwards so missclicking should not be an issue.

**Comment by redone9211** [comment]
i would like to contribute to this issue , can you let me know how i can solve it.

**Comment by vabene1111** [comment]
This will be reworked as part of a more general nav/edit flow so no need to fix this now, also dont have the time to explain, sorry
