### ISSUE TITLE
Social Share Preview (OpenGraph)

### ISSUE THREAD

**Issue by besendorf** [TandoorRecipes/recipes#2264]
### Is your feature request related to a problem? Please describe.

Tandoor already has a recipe sharing feature for users that are not registered on the tandoor instance. When sharing those links they are not very expressive and the path is only a random uid. It would look much nicer on social media and chat apps if there would be a preview with image and the description of the recipe.

### Describe the solution you'd like

Implement social share preview using the OpenGraph standard. https://ogp.me/

**Comment by vabene1111** [comment]
yes that would make sense for sharing links
