### ISSUE TITLE
Option to Display Only the All Ingredients 

### ISSUE THREAD

**Issue by srwareham** [TandoorRecipes/recipes#2266]
### Is your feature request related to a problem? Please describe.

For simple recipes, it would be great to have the option to _only_ show the top-of-page Ingredients list without needing to display step-level ingredients.

Here is what Tandoor looks like with default settings. Recipe information is redundant and takes up more space than needed.
![image](https://user-images.githubusercontent.com/3392952/211707493-6a2319ea-72f3-4d88-bb56-ee959dcf8f64.png)

Here is what Tandoor looks like with "Display a list of all ingredients at the start of the recipe" unchecked. Less space is used than the above, however, the horizontal space next to the image is wasted. In my opinion , it's not aesthetically the best either.  Relatedly, in this example and I think in most single-dish recipes, the ingredients don't logically "belong" to the first step so it's a bit visually jarring.
![image](https://user-images.githubusercontent.com/3392952/211707627-b159d5c4-e10d-4cae-9b78-4039664c2438.png)

### Describe the solution you'd like

It would be great to have the option for ingredients to be displayed only at the recipe level. Here's a proposed mock below using this same example. I'd love to be able to see the ingredients sharing the same horizontal space as the image without needing to duplicate them again in the recipe steps.
![image](https://user-images.githubusercontent.com/3392952/211708011-2c59e3ae-50a0-4439-a62a-0cad7c47a6ba.png)

### Describe alternatives you've considered

It's not clear to me whether this would require any data model changes. If those are prohibitively complex, one band aid fix could be automatically creating a step 0 to contain a "gather ingredients" step. There could be an "Additional Options" setting to not display this step.

Thank you for the great product!

**Comment by TheGor1lla** [comment]
I'd also be interested in this feature. 
Personally having the ingredients seperated from the steps could be a default

**Comment by mtik00** [comment]
I've been trying to find various workarounds in the UI for this behavior (I'm new to Tandoor), but I've not found one.  Having the ability to _disconnect_ the ingredient list from `Step 1` would be great.  Not sure if this would be easier, but "hidden" steps could be something the serializer might be able to handle.

**Comment by rourke** [comment]
I don't quite understand the logic behind the way it's currently working in Tandoor. The step description holds the information on what to do with what ingredients. Why add the ingredients to the step _again_? The solution you proposed here is how all the recipe tools, recipe sites and cookbooks I know do it.

**Comment by smilerz** [comment]
> I don't quite understand the logic behind the way it's currently working in Tandoor. The step description holds the information on what to do with what ingredients. Why add the ingredients to the step _again_? The solution you proposed here is how all the recipe tools, recipe sites and cookbooks I know do it.

I don't understand your confusion - Tandoor isn't adding ingredients to the step again.  There is a summary of all ingredients at the top - if you have multiple steps with ingredients then the ingredients are displayed with the step.

**Comment by rourke** [comment]
> > I don't quite understand the logic behind the way it's currently working in Tandoor. The step description holds the information on what to do with what ingredients. Why add the ingredients to the step _again_? The solution you proposed here is how all the recipe tools, recipe sites and cookbooks I know do it.
> 
> I don't understand your confusion - Tandoor isn't adding ingredients to the step again. There is a summary of all ingredients at the top - if you have multiple steps with ingredients then the ingredients are displayed with the step.

I mean why it visually looks like this, not necessarily how it works technically. But even technically speaking it makes more sense to me to have 1 list of ingredients on recipe level, and optionally reference those ingredients on step level in a separate list.

But I don't understand the benefit of having a list of ingredients on step level. I've just never seen a recipe that does that.

**Comment by smilerz** [comment]
> I mean why it visually looks like this, not necessarily how it works technically. But even technically speaking it makes more sense to me to have 1 list of ingredients on recipe level, and optionally reference those ingredients on step level in a separate list.
> 
> But I don't understand the benefit of having a list of ingredients on step level. I've just never seen a recipe that does that.

Visually, it doesn't look any different on mobile - which is likely why this hasn't come up before.

But, technically, there are lots of recipes that have multiple steps that require different sets of ingredients.  Bakery, dishes with sauces or stocks, marinades, rubs, brines, etc, etc, etc.

**Comment by tekjoey** [comment]
+1 for this change. This is honestly the only reason why I am still using Mealie. I agree with @rourke and @srwareham, for most of my recipes the per-step ingredient list is redundant. I totally understand that some people want/need the granularity of per-step ingredients, but as @rourke said, most recipes I find online don't automatically do this, so I think that Tandor's default behavior should mirror them.

**Comment by srwareham** [comment]
Feature has been merged! https://github.com/TandoorRecipes/recipes/pull/2539
