### ISSUE TITLE
enumeration in recipe

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#2268]
### Tandoor Version

1.4.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

In recipe instructions I start with step 2. In View Mode it is displayed as step 1

![image](https://user-images.githubusercontent.com/29805669/211946155-0dd17bb9-ea9a-4779-99af-c7ec34727700.png)

![image](https://user-images.githubusercontent.com/29805669/211946184-23854eb1-15d6-4432-913a-a8e6ddeb52d0.png)

**Comment by vabene1111** [comment]
you cannot start a markdown list with 2. i think, it will always start with  1 if i remember correctly. While not perfect this is just the way the markdown parser works that is employed in tandoor
