### ISSUE TITLE
ValidationError: webpack Dev Server Invalid Options

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#2269]
### Tandoor Version

1.4.5

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Other

local development server

### Bug description

Starting the development server, the step "yarn serve" gives some error messaes.

It seems that in vue\vue.config.js
".set('hot', 'only')" should be a boolean like ".set('hot', true)"
and it doesn't like the line ".set('static', {watch: true})"

### Relevant logs

```shell
yarn serve
yarn run v1.22.17
$ vue-cli-service serve
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
 ERROR  ValidationError: webpack Dev Server Invalid Options

options should NOT have additional properties
options.hot should be {Boolean} (https://webpack.js.org/configuration/dev-server/#devserverhot)
```

**Comment by vabene1111** [comment]
Possibly this changed since implementing the config. Need to look at the appropriate docs and fix it.

**Comment by vabene1111** [comment]
i think i fixed this the other day when optimizing a bit with the JS
