### ISSUE TITLE
Error in creating additional user

### ISSUE THREAD

**Issue by update-freak** [TandoorRecipes/recipes#2271]
### Tandoor Version

beta (aa5490adb3e58d955d2f4207e767673c3c19e2de)

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Synology NAS

### Bug description

Hello,

after https://github.com/TandoorRecipes/recipes/issues/2241 was solved, I tried to create an additional user (status: user (not admin or guetst))), but I got the error attached, when I click send, Maybe it would be good to have the possibility to create locally the additional users.

I used the instructions on this website https://mariushosting.com/how-to-install-tandoor-recipes-on-your-synology-nas/ to install Tandoor on Synology in Docker.

![2023-01-14 10_58_50-Suchen](https://user-images.githubusercontent.com/40196995/212466708-3be780e1-7c63-458e-bc48-62a1df5508b3.png)

**Comment by vabene1111** [comment]
Do you have a mail server configured? If not you cannot send from tandoor and need to just copy the link and send it manually.

**Comment by update-freak** [comment]
No, I did not have an mail server configured, but it did not create an link.
After the following screen the error form the first screenshot appears.

![2023-01-15 11_56_06-Suchen](https://user-images.githubusercontent.com/40196995/212536702-2515e695-351f-4f86-8557-be8ea55aad25.png)

**Comment by mczeus** [comment]
Here's the same. I can't send an email and I can't get an invitation link

**Comment by vabene1111** [comment]
Can you post the error that is shown in the network request response and the server logs with debug set to 1 in the environment configuration?

**Comment by mczeus** [comment]
172.18.0.4 - - [15/Jan/2023:19:09:23 +0100] "GET /api/group/ HTTP/1.0" 200 72 "http://192.168.1.113/space-manage/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Bad Request: /api/invite-link/
Bad Request: /api/invite-link/
172.18.0.4 - - [15/Jan/2023:19:09:28 +0100] "POST /api/invite-link/ HTTP/1.0" 400 101 "http://192.168.1.113/space-manage/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
172.18.0.4 - - [15/Jan/2023:19:09:28 +0100] "GET /api/invite-link/ HTTP/1.0" 200 2 "http://192.168.1.113/space-manage/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
172.18.0.4 - - [15/Jan/2023:19:11:17 +0100] "GET /api/group/ HTTP/1.0" 200 72 "http://192.168.1.113/space-manage/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Bad Request: /api/invite-link/
Bad Request: /api/invite-link/
172.18.0.4 - - [15/Jan/2023:19:11:20 +0100] "POST /api/invite-link/ HTTP/1.0" 400 101 "http://192.168.1.113/space-manage/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
172.18.0.4 - - [15/Jan/2023:19:11:20 +0100] "GET /api/invite-link/ HTTP/1.0" 200 2 "http://192.168.1.113/space-manage/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"

**Comment by Breadleyg** [comment]
I had the same issue. Console showed an Axios error. In my case it was because of not entering a "valid until" date.
(error message: Date has wrong format. Use one of these formats instead: YYYY-MM-DD.\)

**Comment by update-freak** [comment]
I tried to enter a "valid until" date and then it worked. So I can not leave it blank. Maybe a text that the until date must be filled out could be helpful. So I will close this ticket then

**Comment by vabene1111** [comment]
yes the frontend form validation needs to be improved
