### ISSUE TITLE
Twemoji broken CDN

### ISSUE THREAD

**Issue by Fall1ngStar** [TandoorRecipes/recipes#2274]
### Tandoor Version

1.4.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Twemoji CDN no longer works, this breaks emoji picking in meal type settings:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/12586447/212552416-4c776801-1df2-4946-9933-29ec11c0d188.png">

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/12586447/212552439-f7711473-2710-4c9c-a3fb-a73b059f61a0.png">

[Related issue on twemoji repository](https://github.com/twitter/twemoji/issues/580)

**Comment by vabene1111** [comment]
thanks for reporting, didn't even know the library used an external CDN, I will remove and replace it with a library using only local files (in the hopes that one exists).
