### ISSUE TITLE
Plain Docker Configuration Displaying Old and Non-Functional Version

### ISSUE THREAD

**Issue by brianazick** [TandoorRecipes/recipes#2275]
### Documentation link

https://docs.tandoor.dev/install/docker/#plain

### Affected section

Installation

### Issue description

The docker-compose template for the Plain configuration specifies ports of 80:8080, which does not result in a functional configuration. This should be 80:80. I only discovered the correct volume in this Github Issue: https://github.com/TandoorRecipes/recipes/issues/1258#issuecomment-1008074431

The correct version is available directly in this repository (https://github.com/TandoorRecipes/recipes/blob/develop/docs/install/docker/plain/docker-compose.yml), but has not been updated on the website.

Thank you in advance for your help addressing this!

**Comment by vikaskumar2703** [comment]
can i  solve this issue

**Comment by brianazick** [comment]
As I continue troubleshooting, I noticed that this is a known issue in per issue #2260 .

Closing as this is not needed to be acted on independently.
