### ISSUE TITLE
Icons from `https://cdn.jsdelivr.net/npm/twemoji@11.3.0...` are not shown (404)

### ISSUE THREAD

**Issue by danieldietsch** [TandoorRecipes/recipes#2280]
### Tandoor Version

1.4.5 Ref: 4e13fb3b8cdee2f9f6f1e1d2f9c29d4b77c4d50a

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Apache2 + HAProxy

### Bug description

Icons from `https://cdn.jsdelivr.net/npm/twemoji@11.3.0...` are not shown (404). The same can be observed in the demo instance. 
These icons are, e.g., loaded in Meal Plan -> Settings -> Meal Type -> Edit ...

**Comment by smilerz** [comment]
duplicate #2274 fixed by #5cb0f17
