### ISSUE TITLE
Docker Compose File on Website doesn't work

### ISSUE THREAD

**Issue by lukas7777777** [TandoorRecipes/recipes#2282]
### Documentation link

https://docs.tandoor.dev/install/docker/

### Affected section

Installation

### Issue description

The text of the plain docker compose file shown in the documentation does not work and is different from the linked docker-compose.yml.
The specifications of the opened ports differ and cause a problem.

https://docs.tandoor.dev/install/docker/
wget https://raw.githubusercontent.com/vabene1111/recipes/develop/docs/install/docker/plain/docker-compose.yml

**Comment by vabene1111** [comment]
docs are only build on release, please test again after the release (which should be soon)

the version on develop has been tested and was not changed (the last change was reverted) so next release should be good again.
