### ISSUE TITLE
Extend Length of Description Field

### ISSUE THREAD

**Issue by brianazick** [TandoorRecipes/recipes#2287]
### Is your feature request related to a problem? Please describe.

The description field in recipes is limited at 512 characters. I find that the description for the majority of recipes I import is over that limit by about half a sentence, which means I have the split the text or trim it down if I want to use the description field.

### Describe the solution you'd like

Would it be possible to extend this limit? Perhaps to the next logic step, 1024 characters?

**Comment by vabene1111** [comment]
the description is meant to be shown on preview cards of recipes thus it needs to be short. If you want longer descriptions in the recipe i recommend having a first step without ingredients that holds the description
