### ISSUE TITLE
Recipe Import from Rezepsuite

### ISSUE THREAD

**Issue by vandecook** [TandoorRecipes/recipes#2288]
### Is your feature request related to a problem? Please describe.

Switching from Rezeptsuite<dot>de leads to the situaton, that exported recipes are not possible to be imported in the latest Tandoor version (1.4.5).

### Describe the solution you'd like

Since the format of the xml file is using cookml a standardized format is used, which allows to develop a import filter for this file format. 

In attached sample export (because of github requirements the extension was changed to .xml.txt) there are two recipes inside. One is also with an exported picture inside. 

[rezeptsuite-cloud_2recipes.xml.txt](https://github.com/TandoorRecipes/recipes/files/10530071/rezeptsuite-cloud_2recipes.xml.txt)

### Describe alternatives you've considered

An other possibility is to create a python script which creates a zip archiv including the structure which is similar to the exports created by tandoor itself. This zip file than can be used to import the recipes database.

**Comment by vabene1111** [comment]
added for next release
