### ISSUE TITLE
Install using Docker Cli with sqlite

### ISSUE THREAD

**Issue by grandmastermarco** [TandoorRecipes/recipes#2305]
Hi!
I tried to follow the Docker Install instructions using Docker CLI command line.
I got a postgres database error -> i dont have it installed otherwise. Fair enough.
As i only have very basic docker experience, i hoped postgres would be installed within the tandoor package.
if i am not supposed to have a error message, please advice.

i now try to setup tandoor with sqlite using docker cli.
what is the env variable i have to change to do this?
And how can i store the sqlite in a permanent volume?

maybe the install instructions could be clarified for the different database options (if there are any).
thanks in advance.

———————————
Docker CLI cmd

docker run -d \
    -v tandoor:/opt/recipes \
    -p 8706:8080 \
    -e SECRET_KEY=SECRET \
    -e DB_ENGINE=django.db.backends.postgresql \
    -e POSTGRES_HOST=db_recipes \
    -e POSTGRES_PORT=5432 \
    -e POSTGRES_USER=djangodb \
    -e POSTGRES_PASSWORD=SECRET \
    -e POSTGRES_DB=djangodb \
    --name tandoor \

———————————
Docker log:
Waiting for database to be ready...
Database not reachable. Maximum attempts exceeded.
Please check logs above - misconfiguration is very likely.
Make sure the DB container is up and POSTGRES_HOST is set properly.
Shutting down container.

**Comment by grandmastermarco** [comment]
Okay it was fortunately easy enough so i could figure it out :)
Maybe this is something for the install section of the tandoor manual (docker CLI)?
(Sqlite database is stored in permanent volume "tandoor" like this).

docker run -d \
    -v tandoor:/opt/recipes \
    -p 8080:8080 \
    -e SECRET_KEY=SECRET \
    -e DB_ENGINE=django.db.backends.sqlite3 \
    --name tandoor \
    vabene1111/recipes

**Comment by vabene1111** [comment]
thanks for posting the resoltiuon, i think its fine like this
