### ISSUE TITLE
Web Server 500 Error on Some Clients / Browsers

### ISSUE THREAD

**Issue by mountaintime26** [TandoorRecipes/recipes#2306]
### Tandoor Version

1.4.6 - Latest

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

On Client PC, Mistake Event happened where Django Admin Page accidentally clicked log out. Since that event, the PC that logged out receives a Server Error 500 only when attempting to access via the initial browser Brave, but works fine using MS Edge on the same PC.

Issue also noted by using Ubuntu 22.04 VM on Both Mozilla/Brave with no success logging in. 

Access is perfectly fine using other established clients: original Windows 11 PC using edge, iphones using Brave/Safari, Mac OS using Brave.

Output of docker Logs below truncated to first two lines of output for comparison between requests of working and non-working. Logs show a difference in the second line of the request where working clients asking "GET /search/ HTTP/1.1" 200 20868 and non-working clients asking GET /search/ HTTP/1.1" 302 0.

In all cases the URL requested was the base URL or direct IP address.

### Relevant logs

```shell
#Non-Working Ubuntu VM Request
10.0.1.208 - - [07/Feb/2023:18:29:31 +0000] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "-"
10.0.1.208 - - [07/Feb/2023:18:29:31 +0000] "GET /search/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "-"

#Non-Working Windows Brave Browser Request
192.168.1.2 - - [06/Feb/2023:21:47:48 +0000] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "-" 
192.168.1.2 - - [06/Feb/2023:21:47:48 +0000] "GET /search/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "-" 

#Functional Windows Edge Browser Request
192.168.1.2 - - [07/Feb/2023:18:30:32 +0000] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78" "-"
192.168.1.2 - - [07/Feb/2023:18:30:32 +0000] "GET /search/ HTTP/1.1" 200 20868 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78" "-"
192.168.1.2 -- [07/Feb/2023:18:30:33 +0000] "GET /api/custom-filter/ HTTP/1.1" 200 2 "http://recipes.domain.com/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78" "-"
```

**Comment by vabene1111** [comment]
this was resolved on reddit (if i remmeber correctly) and was due to a browser plugin
