### ISSUE TITLE
Fraction ingredients are converted to 0 and hidden

### ISSUE THREAD

**Issue by martyfuhry** [TandoorRecipes/recipes#2308]
### Tandoor Version

1.4.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

### Bug description

When using fractions to express ingredient amounts (e.g., 1/4), the entry is ignored.

- Create a new recipe
- Add a single ingredient with 1/4 as the first entry
- Save and View
- The amount of the ingredient is completely blank
- **Expected**: Tandoor should convert the fraction to a decimal

![image](https://user-images.githubusercontent.com/100457/217985078-abf8b73f-a456-429b-aee8-60ba66fa3f39.png)
![image](https://user-images.githubusercontent.com/100457/217985093-b8e18678-b67b-41d7-a8ab-e93227959b3b.png)

**Comment by vabene1111** [comment]
it is currently not supported to enter fractions into a number field, honestly i dont even know how you can enter this into the field as this does not work for me (maybe a locale specific thing?)

Filing this as an enhancement for future updates.

**Comment by vabene1111** [comment]
#142
