### ISSUE TITLE
Public Recepies

### ISSUE THREAD

**Issue by Gustav2** [TandoorRecipes/recipes#2311]
### Describe the solution you'd like

I'd be awesome if there was a way to share the recepies with people that does not have an account. This could possibly happen by sharing a link, that shows the same info about the recepie, but without the option to change it etc.

**Comment by smilerz** [comment]
This has already been implemented and can be accessed by the Share option on the context menu of the recipe. 

![0D89AC81-995C-42AC-9BB5-3FED62394B0D](https://user-images.githubusercontent.com/1808639/218286481-aeb870ed-6603-465a-898f-8ee196156db0.jpeg)
