### ISSUE TITLE
"There was an error creating a resource!" with empty unit at importer

### ISSUE THREAD

**Issue by solaris7590** [TandoorRecipes/recipes#2312]
### Tandoor Version

current beta

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Following up on bug #2302, changing ingredients now works great. However, if you change an ingredient without a unit and also save it without a unit, the subsequent step (Import & Edit) fails with the message "There was an error creating a resource!"
If you do not change the ingredient and leave it unedited, i.e. do not click on the "pencil", the import will work.

**Comment by tomtjes** [comment]
Same here.
Logs:
```
Bad Request: /api/recipe/
Bad Request: /api/recipe/
172.30.0.2 - - [12/Feb/2023:00:34:25 +0100] "POST /api/recipe/ HTTP/1.1" 400 113 "https://recipes.redacted.domain/data/import/url?id=68" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
```

**Comment by vabene1111** [comment]
Thanks, I think I know the problem

**Comment by vabene1111** [comment]
fixed, also added the ability to add a note
