### ISSUE TITLE
No plural forms for non-admin accounts

### ISSUE THREAD

**Issue by solaris7590** [TandoorRecipes/recipes#2315]
### Tandoor Version

1.4.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

I see the plural forms as admin of my space. All other users (role user or guest) always see only the singular form.
With admin account:
![1](https://user-images.githubusercontent.com/77384001/218527670-f20fe665-8d0a-44cf-8bad-d0759e3ed02c.PNG)

With another account (role: user)
![2](https://user-images.githubusercontent.com/77384001/218527679-b4738d5a-c87f-44e0-abf0-e328f95fe073.PNG)

**Comment by vabene1111** [comment]
ok thanks for the report, this happens because if plurals are used is a space setting and a normal user cannot request the space settings. 

This should probably be changed, also wondering if using plurals should even be an option as one could simply not add plurals and thus would not use them. Maybe I am going to change that.

**Comment by solaris7590** [comment]
I agree, without the edit function he will not use even that. However, I think that the user should also be able to see at least the plural forms. The decision should be made by the admin, and all who use this space (as user) get this setting displayed.
Until now I had often simply given the plural form in Tandoor, because this is mostly correct. Now, however, if the admin enabled the plural forms, users would only ever see the singular forms. For them, this really great feature is then but rather a disadvantage.

**Comment by vabene1111** [comment]
i understand what you mean and its exactly what i intend to do. By removing the setting everyone will see pluralrs if they are there and not see them if they are not there.

**Comment by vabene1111** [comment]
fixed by removing plural space setting
