### ISSUE TITLE
ERROR:  duplicate key value violates unique constraint "django_migrations_pkey"

### ISSUE THREAD

**Issue by mfr69bs** [TandoorRecipes/recipes#2317]
### Tandoor Version

1.4.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

I've got a Server Error (500). Webinterface does not work anymore.

### Relevant logs

```shell
docker tandoor-recipes_db Log:
2023-02-15 19:58:57.395 CET [30] ERROR:  duplicate key value violates unique constraint "django_migrations_pkey"
2023-02-15 19:58:57.395 CET [30] DETAIL:  Key (id)=(209) already exists.
2023-02-15 19:58:57.395 CET [30] STATEMENT:  INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('cookbook', '0185_food_plural_name_ingredient_always_use_plural_food_and_more', '2023-02-15T18:58:57.394477+00:00'::timestamptz) RETURNING "django_migrations"."id"

docker tandoor-recipes log:
Checking configuration...
Waiting for database to be ready...
Database is ready
Migrating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, oauth2_provider, sessions, sites, socialaccount
Running migrations:
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "django_migrations_pkey"
DETAIL:  Key (id)=(208) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 254, in apply_migration
    self.record_migration(migration)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 269, in record_migration
    self.recorder.record_applied(migration.app_label, migration.name)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 94, in record_applied
    self.migration_qs.create(app=app, name=name)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "django_migrations_pkey"
DETAIL:  Key (id)=(208) already exists.

  Applying cookbook.0185_food_plural_name_ingredient_always_use_plural_food_and_more...Generating static files
js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse
```

**Comment by vabene1111** [comment]
Since this migration hast been working for all other users so far, have you installed any beta version or development versions before at some point?

**Comment by mfr69bs** [comment]
Thanks fpr your reply!

No, i do not remember that I ever had used a beta or devel version. I alway used the latest tag from Docker Hub.

**Comment by vabene1111** [comment]
very interesting, migrations ran trough without problems on my instances and i have not heard from anyone who had trouble with this. 

Can you look into your database and see whats in the list of migrations in `django_migrations`?

**Comment by mfr69bs** [comment]
If you just write me what I should do, then you're welcome.

**Comment by vabene1111** [comment]
honestly i am not really sure how to help you. 

one thing you could try is to dump all data (not the schema) and reload it again.

**Comment by mfr69bs** [comment]
hmm... that doesn't help of course.

I had a recent dump and have now recreated the containers (docker-compose). Then I restored the dump again.

still the same error, only that the id counts up with every start:
django.db.utils.IntegrityError: duplicate key value violates unique constraint "django_migrations_pkey"
DETAIL:  Key (id)=(210) already exists.

it must have something to do with a migration that was initiated in the last few days. before that it worked without any problems.

what can I do? I don't want to lose all my recipes.

**Comment by vabene1111** [comment]
ok so i would try the following
1. dump all data except for the `django_<name>` tables
2. stop the container
3. delete all data (you have a backup, make sure that it works)
4. start the container
5. see if the migrations run trough
6. load the dump

you can also use the exporter to export all recipes to a zip, this will loose you some meal plans and user settings but in case everything goes bad it will save you from a total loss of data.

**Comment by mfr69bs** [comment]
This is the content of django_migrations

[query_django_migrations.txt](https://github.com/TandoorRecipes/recipes/files/10767547/query_django_migrations.txt)

**Comment by vabene1111** [comment]
interesting, that looks perfectly fine. Please try the steps above as this is the only idea i have to fixing this.

**Comment by smilerz** [comment]
the other option is to execute migrations manually and walk through the failures one by one.

**Comment by mfr69bs** [comment]
> the other option is to execute migrations manually and walk through the failures one by one.

Which version came with a new migration? It was still working until a few days ago.

I can't access the container at all at the moment, due to the reported error. So I can't do any exports or anything like that, except directly via sql.

Would it help not to use the latest TAG, but a release before the migration to see what's going wrong?

And:
How is the manual procedure?

**Comment by smilerz** [comment]
You can do it outside of a container (install latest environment locally, point .env to the DB) then run migrations.  [Here ](https://adamj.eu/tech/2022/06/29/run-a-django-migration-by-hand/)is a walk through.  

If you don't feel confident doing it on your own its probably not a good path for resolving the issue though.

**Comment by mfr69bs** [comment]
> You can do it outside of a container (install latest environment locally, point .env to the DB) then run migrations. [Here ](https://adamj.eu/tech/2022/06/29/run-a-django-migration-by-hand/)is a walk through.
> 
> If you don't feel confident doing it on your own its probably not a good path for resolving the issue though.

thanks for the hint.. so, i am also a developer, but i am sure i could walk this path, but it would certainly be rocky for an untrained "django" and "psotgres" person like me. ;)

So I guess I have to rely on the developers here.

**Comment by vabene1111** [comment]
ok so for me it appears that you already did many things correctly. All of the errors you are showing are caused by ALTER TABLE statements. You dump should only contain data (INSERTS/UPDATES) and no ALTER statements (except possibly ones to remove and re add foreign constrains but i dont think this should be required).

Can you open your dump in a texteditor and see if there are any schema alteration commands (should be similar to mysql) in you dump. If so try removing them and run the dump again against an empty DB

**Comment by mfr69bs** [comment]
I edited the dump and I removed any ALTER or DROP TABLES.

Then I received an
`insert or update on table "<nnn>" violates foreign key constraint`

So I deleted all tables that don't start with `cookbook_` from the dump. With an empty database, I created an admin account and a default space via the web.

Then I imported the dump again, which then threw error messages again. So I edited the dump again, this time I did NOT delete all `ALTER TABLE ONLY ... ADD CONSTRAINT ... FOREIGN KEY ...` entries. There were error messages because of the foreign keys.

At the beginning of the dump I dropped the `DROP INDEX` of all `cookbook_tables` and truncated the tables.

Additionally I left all `CREATE INDEX` entries in the dump.

Since I had not created any other users in the new installation apart from the admin, I had to create this before a restore. So start again....

Now there are problems with sending the invitations. I'll write that separately. With "brute force" and manual entries via the Django interface, I created two more users and restored the dump again in the meanwhile xx new installation.

This time it seemed to work, the recipes were found. However, when viewing a recipe, only the image and the introductory text and information appeared. All work steps were not there.

So just "ironed over" (as we say in German) the dump one last time and everything was there again.

That took some doing...

**Comment by mfr69bs** [comment]
It's a new topic, but it now occurs in this case:
Although all entries in the .env are as they were before the whole error above appears, there seems to be a problem when emails are to be sent.

No matter whether I wanted to add my own e-mail address as an admin or when inviting a user. I'm running into a timeout.

However, when I reload the page afterwards, the entry is there, but the email was never sent.

when I copy the invitation link and do the registration manually, I run into a timeout again at the end of the registration. However, the user was created and can log in after a reload. I manually confirmed the email address in the Django administration.

Do you have an idea for this? Debugging is turned on, but there is no usable info.

Only a reference to a curious date is displayed:
```
/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1564: RuntimeWarning: DateTimeField InviteLink.created_at received a naive datetime (2023-02-18 18:00 :04.965611) while time zone support is active.
   warnings.warn(
```

In the selection of the invitaion, February 20, 2023 was set as the expiry date. And the error message here is complete as it is, then there was a timeout.

**Comment by mfr69bs** [comment]
Happy too soon....

The ingredients are missing from the recipes. Everything else is there:
Description, keywords, information, image, work steps...

But no ingredients. And now?

**Comment by mfr69bs** [comment]
Is there anybody out who can fix my dump for restoring? i am really frustrated...

**Comment by vabene1111** [comment]
are there inseret statements for your ingredients in the dump? ingredients rely a lot on foreign keys, maybe the automatic dump dumped them in the wrong order.

Can you trey just running those again without anything else?

Other than that maybe you can join the discord, there are also some german folks there who are very active who might be able to help you out a bit.

**Comment by rodlcopter13** [comment]
I tryed differnet things and have the same issue. I used the backup methode from the manual (https://docs.tandoor.dev/system/backup/#manual-backup-from-docker-build)
I used it once to migrate the db from docker-stack with tandoor version 1.45 into another docker-stack on a different pc with tandoor version 1.45 and it was successful.

1st try I used an old Tandoor version (1.45) and I did a db-dump and import that into a new docker-stack with version 1.47 and I got the same Error that the keys already exists
2nd try I set up Tandoor version 1.47 and add 1 recipe. Then I did a db-dump again. Set up a second docker-stack with Tandoor 1.47 and imported the db and I recived the same Error.

Did anybody else tryed to import the db and could succeed?
However I can't eliminate that I did a mistake, because I am new to docker and databases.

**Comment by vabene1111** [comment]
very interesting. I looked trough the migrations again and I do not see any reason why the plural name should be added twice. 

It exists only once in the migration tree and the order of the migration and the links are all consistent.

Also your dump above with the migration history looks correct. 

From what you describe you are getting the error when you load a dump, this leads me to believe that the behavior you observed in your last comment is related to the dumping/loading not the issue itself. 

Since your setup is screwed anyway can you try the following: setup a 1.4.5 image, add 1 recipe, upgrade the image to 1.4.7 and see if that works? and if it does not do the same but go from 1.4.5 to 1.4.6. to 1.4.7?

 @Knalltuete5000 do you remember us doing anything weird with the migrations that could cause this? I know that I re-create the migrations after merging the PR because I left it laying around so long but that should not cause this issue.

**Comment by Knalltuete5000** [comment]
I do not remember doing anything wired with the migrations. I have not added any in the commits and you have made them after the merge. 

It looks like to me that the migration is run twice for whatever reason. I have looked through them but they seam fine. There were no changes in the migration since they were created. I have also looked through the releases but the migration is only once included and also only once referenced by the following migration

**Comment by rodlcopter13** [comment]
Now I am completly confused.

I tryed differnet things:
1) Deploy Version 1.45 with 1 recipe with 3 ingredients (Ei, Eier Ei(er)) and automate to merge them into Ei(er). Then upgrade to Version 1.47 and everthing works fine. 
2) Deploy Version 1.45 and import recipes (87) with the import feature. Then upgrade to Version 1.47 and everthing works fine.
3) Import dbdump from Version 1.4.5 with 1 recipe into a new deployed version, the import needed to be done two times. Then I upgraded to Version 1.4.7 and it works even after restarting the container.
4) Import dbdump from Version 1.4.5 with 87 recipe into a new deployed version, the import needed to be done two times. Then I upgraded to Version 1.4.7 and it works even after restarting the container.

**Comment by vabene1111** [comment]
ok so the behavior you are experiencing is probably what i would expect since the importer has never really worked across different version. It is a lot of work to maintain such an importer and people can always just start the container with the old version, import there and run the migrations to upgrade the schema.

What so interesting to me is that for you and the other user linked in the references issue it seems that the migrations themselves are failing. This is especially strange because there are most likely already many people on 1.4.7 and it seemed that their migrations ran trough smoothly while yours for some reason failed. With manual/large complicated data migrations that would be something were I would think that we could have broken something but this is only an automatically generated schema migration which so far I have never seen any issues with. 

I guess, given that option 2 worked, there must have been something broken with your instance before and exporting/importing again removed that, but it would be very interesting to know what caused this issue.

**Comment by mfr69bs** [comment]
> are there inseret statements for your ingredients in the dump? ingredients rely a lot on foreign keys, maybe the automatic dump dumped them in the wrong order.
> 
> Can you trey just running those again without anything else?

I've done this several times...

> Other than that maybe you can join the discord, there are also some german folks there who are very active who might be able to help you out a bit.

No, i do not want to switch to discord, because here is the "habour" for issues.

But i would prefer to switch to German language.

**Comment by mfr69bs** [comment]
After further unsuccessful attempts to restore to the current version, I have now restored a dump from November 2022 in a fresh installation.

Create container for the database, then restore and only then the container for tandoor and web. That was the way that I only lost 3 recipes.

Now I'm back to 1.4.5 and everything works.

**Comment by mfr69bs** [comment]
You've got mail.. ;)

**Comment by vabene1111** [comment]
Ok so I just did the following

1. load your dump into an empty psql database
2. start it with tandoor 1.4.5 -> everything works
3. upgrade tandoor to 1.4.7
4. run migrations -> everything works

I am not sure what is happening with your setup but your dump works perfectly fine for me. 

Is your postgres setup standard? and also OS and everything or is there anything unusual about your setup?

**Comment by billbrod** [comment]
> now, i've done this: `docker exec -t tandoor-recipes_db pg_dump -U djangouser --exclude-table-data="django_admin_log" --exclude-table-data="django_content_type" --exclude-table-data="django_migrations" --exclude-table-data="django_session" --exclude-table-data="django_site" --clean djangodb > pgdump_djangodb.sql`
> 
> then i stopped the database and main container, delete the content of the postgres data directory and start the container again. Tandoor works as expected.
> 
> After that i have copied the dump to the database container and restore it from within the container: `psql -U djangouser -d djangodb -f /tmp/pgdump_djangodb.sql`


Just wanted to say that the solution @mfr69bs  described here worked for me.  I did the following:
`sudo docker exec -t appdata_db_recipes_1 pg_dumpall -U djangouser > pgdump.sql`, then I used the `volumes` directive (in my docker compose file) to mount the folder containing that `pgdump.sql` at `/tmp/backup` and ran the following: `sudo docker compose -f linuxserver.yml run db_recipes psql -U djangouser -h db_recipes -d djangodb -f /tmp/backup/pgdump.sql`, where `linuxserver.yml` is the yml file defining my docker compose setup (I think the image was named both `db_recipes` and `appdata_db_recipes_1`). 

I had previously tried using the suggested `cat pgdump.sql | sudo docker compose exec db_recipes psql postgres -U djangouser` based on the [backup](https://docs.tandoor.dev/system/backup/) page and that led to an import of the recipes, but not the ingredients lists.

(I'm not familiar with postgresql or mysql)

**Comment by smilerz** [comment]
@mfr69bs are you still experiencing a problem?
