### ISSUE TITLE
Ingredients are duplicated inside recipe view

### ISSUE THREAD

**Issue by zecar** [TandoorRecipes/recipes#2320]
### Tandoor Version

0.0.0

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

the version is obviously incorrect but that's how it is inside /system

the bug is on the recipe page.. i have the same ingredient in 2 different steps and they show as separate entries in the list of total ingredients at the top of the page

i checked, and is the same ingredient not a different one with same name or different unit; it's the same ingredient used with the same unit but in 2 steps

**Comment by smilerz** [comment]
This isn't a bug - its working as intended.  There is a feature request elsewhere to make this behavior configurable.

**Comment by zecar** [comment]
i could not find in the admin page where i can configure this, can you please help me?

**Comment by zecar** [comment]
https://github.com/TandoorRecipes/recipes/issues/1325

**Comment by smilerz** [comment]
That will only toggle the summary ingredients for a recipe. It’s located under advanced options while editing a recipe.

**Comment by zecar** [comment]
is it in the  current version? i cannot find this section with advanced options

**Comment by smilerz** [comment]
![image](https://user-images.githubusercontent.com/1808639/219767967-59be464f-b655-4314-84c9-46fd16308ec6.png)

**Comment by smilerz** [comment]
![image](https://user-images.githubusercontent.com/1808639/219768053-9c75660d-26c1-468c-9f07-b2ba248208b9.png)

**Comment by zecar** [comment]
yes sorry, i might not have the last version... so about my issue, is it a work in progress?

**Comment by smilerz** [comment]
It’s not currently possible. There’s an open feature request on this functionality.

**Comment by zecar** [comment]
i am not able to find the issue associated with my request, do you mind linking it?
