### ISSUE TITLE
sync button in mobile view

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#2323]
### Tandoor Version

1.4.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

In mobile view on iPhone 13 the sync button is very big and takes up a lot of space.
The shopping list icon is in front of the snyc button

![image](https://user-images.githubusercontent.com/29805669/219824890-2f27c147-bd0c-434c-bfaf-18dc9d213d59.png)

**Comment by vabene1111** [comment]
yes forgot this from debugging, already removed for the next version
