### ISSUE TITLE
Extra information for ingredients and description overlapping

### ISSUE THREAD

**Issue by update-freak** [TandoorRecipes/recipes#2325]
### Tandoor Version

1.4.7

### Setup

Synology

### Reverse Proxy

Others (please state below)

### Other

Reverse Proxy from Synology NAS

### Bug description

The extra explanation and description (steps) are overlapping, so the extra information could not be get when the mouse is on the speech bubble icon.

![mango](https://user-images.githubusercontent.com/40196995/219965408-034e2fbd-4240-46dd-8db4-08ed8cbee12d.png)

**Comment by vabene1111** [comment]
#2220

**Comment by dersimoezdag** [comment]
It seems to be resolved since the last design upgrades.
![grafik](https://github.com/TandoorRecipes/recipes/assets/15947620/1417c5c1-a623-4712-97d0-d11585411359)

-> Could be closed

**Comment by vabene1111** [comment]
thanks
