### ISSUE TITLE
Ghost recipes in homepage

### ISSUE THREAD

**Issue by marcoaddario** [TandoorRecipes/recipes#2327]
### Tandoor Version

1.4.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

jwilder's nginx proxy

### Bug description

After adding meal plan entries without associated recipes, new ghost recipes (new items with no content) are added to the main page:

<img width="1464" alt="homepage" src="https://user-images.githubusercontent.com/3762730/220132529-a7158b67-2b99-4a61-87c3-58c44eff432b.png">

![image](https://user-images.githubusercontent.com/3762730/220133065-3ab57218-d8d0-4644-bf19-9c77ca21f661.png)

**Comment by vabene1111** [comment]
should be fixed in the next version as i completely reworked how the frontpage works
