### ISSUE TITLE
Group full recipe ingredients by header name

### ISSUE THREAD

**Issue by zodac** [TandoorRecipes/recipes#2329]
### Is your feature request related to a problem? Please describe.

Since there are ingredients listed per step, and also ingredients for the full recipe, it would make sense for the 'full recipe' version to be as clear as possible. Instead it remains grouped as in the steps.

### Describe the solution you'd like

When different steps have ingredients that use the same header, they should be grouped together at the top of the recipe. Currently if I have steps 1, 2, and 3, but the same header for ingredients in steps 1 & 3, they will be listed separately.

**Comment by vabene1111** [comment]
This is a feature not a bug, we will likely add a feature to configure the behavior but it's mentioned in some other issue.

**Comment by zodac** [comment]
Ok, that sounds pretty reasonable. Will continue as is and wait for that option.

Thanks vabene1111!
