### ISSUE TITLE
Recipes can't be added to the shipping list if the ingredient list contains headlines/empty entries

### ISSUE THREAD

**Issue by KidA90** [TandoorRecipes/recipes#2330]
### Tandoor Version

1.4.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

If the ingredient list for a recipe contains headlines/notes or an empty list entry, the ingredients can't be added to the shopping list alltogether. The "add to shopping list" dialogue pops up, but you just see an endless loading circle.
I have tried to deactivate the amount for the headline list entry and to move it to a different position in the list, but still can't add the ingredients to the shopping list.
![Bildschirmfoto vom 2023-02-24 13-24-10](https://user-images.githubusercontent.com/58784953/221179130-b1bd55bb-30d1-4b29-8e33-3e6a12b6b77f.png)
![Bildschirmfoto vom 2023-02-24 13-24-29](https://user-images.githubusercontent.com/58784953/221179136-05cbd4c7-a956-4411-8296-44cb94c3aabf.png)

**Comment by vabene1111** [comment]
i am pretty sure that i noticed this too while working on the new UI and fixed it already. Please test again once the new version is out and if its not fixed let me know.
