### ISSUE TITLE
Image scaling in recipe view

### ISSUE THREAD

**Issue by KidA90** [TandoorRecipes/recipes#2332]
### Tandoor Version

1.4.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Images attached to recipes are supposed to be scaled to have the same height as the ingredient card in the recipe view. However, the images are scaled to a much smaller size. See screenshot below and the discussion at #2331  for reference.
![Bildschirmfoto vom 2023-02-24 19-19-32](https://user-images.githubusercontent.com/58784953/221299178-a11bcf62-a11e-4345-adce-798ddcb3531a.png)

This behavior was observed using the browsers Brave, Chrome and Firefox on a Linux laptop as well as Brave on a tablet running LineAge OS.

**Comment by vabene1111** [comment]
very interesting, all my images behave correctly. Is this happending for all your images or just for some?

**Comment by KidA90** [comment]
I just looked through some of my recipes...It doesn't happen for all of the images, but for most of them. Especially if the images are square. Strangely, I did find some square images which were scaled correctly. I can't figure out a pattern for the life of me ☹️

**Comment by vabene1111** [comment]
do you think you could send me one of the images that is failing for you so i can try it ?

**Comment by KidA90** [comment]
I'm not sure if I'm allowed to post the images in question publicly because I don't own them (copyright laws can be a real pain 🙈️), but you could download them directly from the websites where I got them:

This one gets scaled to 14 x 14 px in Tandoor:
https://www.essen-und-trinken.de/rezepte/90643-rzpt-italienischer-pizza-teig

This one on the other hand works just fine:
https://thebeet.com/5-minute-snack-recipe-easy-delicious-chocolate-peanut-butter-truffles/

**Comment by vabene1111** [comment]
ok so i have just imported the recipe in the latest develop version and it seems to work fine 

![image](https://user-images.githubusercontent.com/6819595/221610569-0aa8a088-bb14-4388-ab86-545ef1c0da9c.png)

its not huge, probably due to the small ingredient list, but its visible. 

Do you by chance have any strange monitor resolution or aspect ratio? have you tried on multiple devices?

Generally speaking i really want to redesign the recipe view but have not yet found a good way to do so, need to be creative at some point and also force certain formats for images when uploading.

**Comment by KidA90** [comment]
It actually happens on all my devices in landscape mode (Laptop with 1920x1080 screen, Tablet and Smartphone (Both Android). When my phone is in portrait mode, the images looks fine actually.
Currently I'm on vacation, but when I get back, I will investigate further...I originally imported all my recipes from a Paprika 3 Backup and just updated the pictures and some details. I will try to import the recipes from scratch like you did. Maybe that makes a difference...

**Comment by vabene1111** [comment]
Maybe paprika changed their export over the years and my importer recognizes some kind of thumbnail file, that could lead to very small images being imported. If you want feel free to send me your paprika export to info@tandoor.dev and I can take a look.

**Comment by KidA90** [comment]
So I imported the recipe we used as an example from scratch / the URL and tadaa: 
![image](https://user-images.githubusercontent.com/58784953/224172344-f266f301-47c8-429f-b336-203064d15b1f.png)

The image gets scaled correctly 😃️
So the issue must be with the Paprika export as you suggested. 

BTW: My original journey was from Paprika to Mealie to Tandoor, but the Mealie import in Tandoor is also broken because Mealie changed its backup structure (one big database JSON instead of individual ones for each recipe). I will send you both my Paprika and my Mealie export via email so you can update the import routines in Tandoor when you get a chance.

Thank you so much for your help and your amazing software 😊️

**Comment by vabene1111** [comment]
Awesome, I will fix both integrations, for mealie I think I will add a second importer so both formats stay supported.

**Comment by vabene1111** [comment]
ok so images in paprika exports only contain data with limited resoultion. 

I have improved the importer to first try and import the image_url if its set to possibly get a better resolution, this will be worse if a image has been changed after the import but i think its overall probably the better result.
