### ISSUE TITLE
Cooking plan in mobile view blank

### ISSUE THREAD

**Issue by solaris7590** [TandoorRecipes/recipes#2334]
### Tandoor Version

current beta

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

The cooking plan remains empty/white at first in mobile view. Only after clicking on the arrow to change the week, content is displayed.

![WhatsApp Image 2023-02-26 at 11 45 22](https://user-images.githubusercontent.com/77384001/221405851-fd36036f-9094-4bb3-bc44-0e1675cab47b.jpeg)

**Comment by vabene1111** [comment]
Interesting, does this only happen the first time after the update or is this reproducible?

**Comment by solaris7590** [comment]
It happens every time. Even if you zoom in on the PC so that it switches to the mobile view.

**Comment by vabene1111** [comment]
interesting, its working for me. If this is happending on your PC as well, can you look into the browser console and see if any errors are shown there?

**Comment by vabene1111** [comment]
ok i think this might be the case if nothing is planned, i will add a fix for that.
