### ISSUE TITLE
Reorder books

### ISSUE THREAD

**Issue by ptrotary** [TandoorRecipes/recipes#2338]
### Is your feature request related to a problem? Please describe.

Currently the books section lists the books in the order I create them.

### Describe the solution you'd like

I would like to be able to reorder them, manually/alphabetically/etc.

**Comment by m7modSy** [comment]
## Response to Feature Implementation

Hello @ptrotary ,

 I'm excited to let you know that I've implemented the ability to reorder books in the books section. Users can now manually reorder books according to their preference.

### Changes Made:
- Now you can sort the books in 4 different ways.
1. oldest to newest.
2. newest to oldest.
3. alphabetical order.
4. sort manually:
Here you can re-sort the books as you wish.
The changes are saved even after you leave the website.
you can swap 2 directly adjacent books or you can specify the location where the book should be saved. drag-and-drop functionality was also an idea. but this is inefficient for those who use a phone or table.

You can view the changes in the https://github.com/TandoorRecipes/recipes/pull/2810. I hope this addresses your request. Please feel free to test it out, and let me know if you have any feedback or if there's anything else you'd like to see improved.


Best regards,
@m7modSy

**Comment by m7modSy** [comment]
Little Change to the Solution:
The manual sorting mechanism has been updated to a drag-and-drop functionality.
