### ISSUE TITLE
Mealie import contains some bugs

### ISSUE THREAD

**Issue by Northguy** [TandoorRecipes/recipes#2339]
### Tandoor Version

https://app.tandoor.dev/

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

Demo version on website

### Bug description

Tried to import a Mealie export file and discovered 2 issues with the import:
1) When importing a recipe which only contains a list of ingredients and **NO** stepwise description, the list of ingredients is not imported into Tandoor. It then only generates the recipe title and image.
2) When importing a recipe which contains a list of ingredients **AND** a stepwise description, the list of ingredients is created, but also imported as a table into the 1st step of the recipe. See screenshot below.

![image](https://user-images.githubusercontent.com/1189058/221906562-05d336da-320e-48fc-8ef6-fdf9dadc6eab.png)

I guess this will be tackled when someone finds the time to have a look at #1785

**Comment by vabene1111** [comment]
the second thing is not a bug but a feature, there are some discussions around here but long story short: ingredients are always summed in the head and listed in each step they belong to. Maybe i should add a special case for when only the first step has ingredients. 

The first one is most likely a bug, really need to take a look at this.

**Comment by vabene1111** [comment]
ok so looking at this now: what version of mealie do you use? in the 1.0 beta i only see the option to export the complete database. Do you run a pre 1.0 version?

if so would you mind sending me your export to info@tandoor.dev ?

**Comment by Northguy** [comment]
> 

Hi @vabene1111 As V1.0 is still in beta, I am using the 0.56 release. I sent you a wetransfer link with the recipes from Mealie.

Regards,

Patrick

**Comment by Northguy** [comment]
> the second thing is not a bug but a feature, there are some discussions around here but long story short: ingredients are always summed in the head and listed in each step they belong to. Maybe i should add a special case for when only the first step has ingredients.
> 
> The first one is most likely a bug, really need to take a look at this.

OK, thanks for your response... I was not expecting the feature, but I can sense the logic. Guess I need to toy around a bit more to understand Tandoor's logic. Anyway I sent you a Wetransfer link containing my export. See my other reply.

**Comment by vabene1111** [comment]
fixed the first one for the next release
