### ISSUE TITLE
Sorting by rating (5-1) sorts by rating (1-5)

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#2349]
### Tandoor Version

1.4.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

On the search page the sorting field yields the same result for `Rating (5-1)` and `Rating (1-5)`.

**Comment by vabene1111** [comment]
thanks for the report, the search is sadly both not very performant nor very stable. I need to completely rewrite it, this will also include a fix for certain other aspects.

**Comment by smilerz** [comment]
I fixed this at some point, but don't remember when.
