### ISSUE TITLE
Manually add a link to a recipe to the corresponding video

### ISSUE THREAD

**Issue by HenrikGeiger** [TandoorRecipes/recipes#2353]
### Issue

Hello,

I have a problem/wish for creating recipes:
when i import a recipe the overview shows a field for the url from which the recipe was imported. I do not have this url field when I create the recipe manually. Is this intentional or do I just not find it?
Background is, I have manually imported some recipes from Youtube Videos and would like to link in the recipe to the corresponding video. 
Is this somehow possible?

### Tandoor Version

1.4.7

### OS Version

Docker

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

**Comment by vabene1111** [comment]
In the recipe editor there is an expandable section that contains the field you can input the URL into. This should solve your issue I think
