### ISSUE TITLE
API Filter via Meal Type // Home Assistant Sensors to Display days Meals Planned 

### ISSUE THREAD

**Issue by jasondavies1999** [TandoorRecipes/recipes#2355]
### Is your feature request related to a problem? Please describe.

I was trying to do something similar to what Mealie does on this page: https://hay-kot.github.io/mealie/documentation/community-guide/home-assistant/

However, I was not able to get this working due to having multiple meals planned in a single day. There wasn't a way to filter the results to only get a certain Meal Type. 

### Describe the solution you'd like

Meal Type Filtering in API or Ideally a template for a sensor that allows you to show the days meals by meal type in home assistant including an image as Mealie does in the link provided.

**Comment by vabene1111** [comment]
can probably implemented by adding another query attribute to the api call.

would that be an option for you?

would look something like /api/meal-plan/?fromDate=X&toDate=Y&type=Z

although one would need to note that there can be multiple meals of the same type on the same day

**Comment by jasondavies1999** [comment]
> can probably implemented by adding another query attribute to the api call.
> 
> would that be an option for you?
> 
> would look something like /api/meal-plan/?fromDate=X&toDate=Y&type=Z
> 
> although one would need to note that there can be multiple meals of the same type on the same day

It does seem like that would work. Although yes like you say there could be multiple meals scheduled into the same type. Would an image be accessible from this method?

**Comment by vabene1111** [comment]
there is currently no endpoint to generate an image but this can be added. There is a different issue requesting exactly that so i will close this for now.
