### ISSUE TITLE
Recipe Keeper Online Import missing Ingredients 

### ISSUE THREAD

**Issue by jkexbx** [TandoorRecipes/recipes#2356]
### Tandoor Version

1.4.5

### Import URL

https://recipekeeperonline.com/recipe/M4HV7YnOF0G-EtGoh1eSlw

### When did the issue happen?

The ingredients are not imported for recipe keeper online. Everything else imports fine.

**Comment by vabene1111** [comment]
thats intereting, the ingredients are tagged with the proper microdata, we need to look into the wilde mode parser of https://github.com/hhursev/recipe-scrapers/tree/main/recipe_scrapers why this is not picked up. 

Should probably be an easy fix but need to find the time to do it.

**Comment by PrathyushaModala** [comment]
Hey @jkexbx , @vabene1111  can you guys brief more about this issue. I wanted to solve it :)

**Comment by vabene1111** [comment]
its what i wrote above, there is a parser in recipe scrapers that parses microdata and that seems to miss the data provided.

**Comment by Asish-AP** [comment]
Hey @vabene1111 . I am willing to take up the issue . Currently figuring out the parser and will let u know once done

**Comment by vabene1111** [comment]
awesome, thank you. I have some sample data for older versions as well to test or send you if needed, sadly there are often tons of edge cases with these data imports.

**Comment by DecodersLord** [comment]
@vabene1111  I have 2 options to fix this, please advise: 

The first one is to add recipekeeper class and address the ingredients section there. 
The scrapper returns all other parts correctly for now.. as I do not see rating author or category part for the given referral link I can not look into whether the scrapper will return any error there or not. The complete list of available sections are as below but sharing the recipe as a link requires paid version of the app. 
![Screenshot_20230828-110148](https://github.com/TandoorRecipes/recipes/assets/16672277/c77abb25-4cda-4f06-9974-f879cf3c4dee)
![Screenshot_20230828-110157](https://github.com/TandoorRecipes/recipes/assets/16672277/06249fdc-d270-43e2-9849-64f0ddf9aae4)

The easier solution for this can simply be adding "self.data.get("recipeIngredients")" to the _schemaorg.py to prevent it on any other websites as well.

Please advise as this will also be my first PR and would really like to make it happen. 😄

**Comment by smilerz** [comment]
> The first one is to add recipekeeper class and address the ingredients section there.
> The scrapper returns all other parts correctly for now.. as I do not see rating author or category part for the given referral link I can not look into whether the scrapper will return any error there or not.

Can you please update your reply based on the data format of recipekeeper and how the current importer is implemented?  A screen shot of how the data is displayed isn't helpful.

**Comment by DecodersLord** [comment]
Apologies..
So the issue reported is only for "ingredients" not being imported is due to the scrapper looks for "recipeIngredient" but for recipeKepper the element is named **"recipeIngredients".** 
![Screenshot 2023-08-28 112142](https://github.com/TandoorRecipes/recipes/assets/16672277/5c4877d9-12ae-4dea-97b1-f5a518700f11)

I can only assume whether there are any difference for other elements like rating or Nutrition. so leaving those out the new class only looks like this. 

![image](https://github.com/TandoorRecipes/recipes/assets/16672277/f3d7f30d-e416-48d2-b737-02a1a2b1a646)

The easier solution for this can simply be adding "self.data.get("recipeIngredients")" to the _schemaorg.py to prevent it on any other websites as well.

**Comment by smilerz** [comment]
the code you are suggesting be changed is upstream at https://github.com/hhursev/recipe-scrapers - please submit a PR at that project.

**Comment by smilerz** [comment]
> Apologies.. So the issue reported is only for "ingredients" not being imported is due to the scrapper looks for "recipeIngredient" but for recipeKepper the element is named **"recipeIngredients".** !
> 
> The easier solution for this can simply be adding "self.data.get("recipeIngredients")" to the _schemaorg.py to prevent it on any other websites as well.

the code you are suggesting be changed is upstream at https://github.com/hhursev/recipe-scrapers - please submit a PR at that project.

**Comment by Aksshay88** [comment]
Hey @jkexbx Is there assignments for this issue
I would like to work on this particular issue

**Comment by smilerz** [comment]
> Hey @jkexbx Is there assignments for this issue I would like to work on this particular issue

You don't need the issue assigned - simply submit a working PR that resolves the issue.

**Comment by Prakhar-Tyagi** [comment]
is this issue still open?

**Comment by vabene1111** [comment]
sadly not, been some rather busy month and I haven't gotten around to do much

**Comment by vabene1111** [comment]
closing this as it appears to be on the scrapers side of things, seems like its not fixed as we are on 14.52 and the url is not working.
