### ISSUE TITLE
Autocompletion for import ingredient editor

### ISSUE THREAD

**Issue by phu77** [TandoorRecipes/recipes#2358]
### Is your feature request related to a problem? Please describe.

With the release 1.4.7 it is now possible to edit the ingredients with the import ingredient editor which is a great feature. However, this editor lacks the autocomplete function. Thus, it is not possible to reasonably match the ingredients to be imported with the ingredients which are already in the database.

Duplicates are thus not detected in early stage during the import and have to be corrected each time afterwards.

### Describe the solution you'd like

The ingredient editor should work with autocompletion in same manner as the normal editor with autocompletion.

### Describe alternatives you've considered

An alternative would be to display per ingredient clickable similar existing ingredients which are already in the database on each line.

**Comment by vabene1111** [comment]
Currently this is not supported because I do not want to maintain two versions of the recipe editor. It also has some technical reasons. Once  I figure out a good solution to the ingredient editing I will implement it in both the editor and the importer.
