### ISSUE TITLE
Ingredient substitute

### ISSUE THREAD

**Issue by Dejiire** [TandoorRecipes/recipes#2361]
### Is your feature request related to a problem? Please describe.

Not a problem, but ....
-People could have allergies, or other food restrictions causing them to not be able to follow shared recipes.
-The best alternatives provided by the recipe creator or editor could help.

### Describe the solution you'd like

I'd like to suggest an ingredient substitute feature in the ingredients section during recipe creation. 
-This could be a subsection under a specific ingredient
- It can be optional
-The requirements for an ingredient are the same for the substitute (measurement, unit, food)

**Comment by smilerz** [comment]
You can already setup a substitute for a food (in food detail editor at `/list/food/`)  It isn't yet visible on the recipe page.

**Comment by Dejiire** [comment]
Okay, thank you I will check that out
