### ISSUE TITLE
Confirmation mail shows "example.com" - where to fix?

### ISSUE THREAD

**Issue by kangaroo72** [TandoorRecipes/recipes#2362]
### Issue

Once a user registered, he's getting a confirmation mail like this....

Hello from example.com!

You're receiving this e-mail because user mikki has given your e-mail address to register an account on example.com.

To confirm this is correct, go to https://my-domain/accounts/confirm-email/NA:1pZp86:Uq8Poau9mZaeQHSkrgQ9OpY9ESWzN2kcl1owXopSlKs/

Thank you for using example.com!
example.com

------------------------------------

Where can I customize that?

### Tandoor Version

1.4.7

### OS Version

Ubuntu 22.04

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

**Comment by solaris7590** [comment]
You can change this by clicking on Websites at the bottom of the Django administration and changing the example.com entry there.

Important: Do not delete the example.de entry and create a new one. Only change it! From my own experience I can say that otherwise you destroy the database.

**Comment by kangaroo72** [comment]
I think, you mean this.
![image](https://user-images.githubusercontent.com/6906390/223689516-50fe57f1-f72c-4e7b-a4e3-961abe97b4e6.png)

But my credentials mentioned in the .env-file will not work....
Do I need special settings for admin-access?

**Comment by solaris7590** [comment]
if you are assigned the admin role, you should be able to access it directly from the menu in Tandoor without logging in.

![image](https://user-images.githubusercontent.com/77384001/223696467-62e71e4b-52e1-4742-b8bb-02a8b7e3bc84.png)

**Comment by kangaroo72** [comment]
I think I am admin, but it looks other than yours...
![image](https://user-images.githubusercontent.com/6906390/223711933-6f1c1365-0996-487d-80e7-55fe1d48faab.png)
![image](https://user-images.githubusercontent.com/6906390/223712023-2697bc56-50a2-41d1-a4f5-cb358e0cd968.png)

**Comment by kangaroo72** [comment]
I just created a superuser with python - it should work now. Thanks.
