### ISSUE TITLE
Navigation bar Color Contrast Accessibility

### ISSUE THREAD

**Issue by a-Adeola** [TandoorRecipes/recipes#2367]
### Is your feature request related to a problem? Please describe.

While changing the color theme of the website in Settings - Cosmetic, I think the menu text colors of the Dark, Info, and Danger themes could be more contrasting. 

It is hard to read the menu with these themes.

-I have included screenshots in the Additional context section

### Describe the solution you'd like

The menu text color could also change to a contrasting color, depending on what theme is chosen.

Maybe for Dark theme - White text, Danger theme - yellow text, Info theme - yellow/white text. 

### Additional context

![dark](https://user-images.githubusercontent.com/75056152/224437323-9041d596-737e-4282-b74c-3c4c1a4e7beb.jpg)
![danger](https://user-images.githubusercontent.com/75056152/224437347-063e0ff1-3334-45a7-99fb-d757da6cd714.jpg)
![info](https://user-images.githubusercontent.com/75056152/224437373-434fc638-cc22-4c37-b5fb-cf236bde5304.jpg)

**Comment by vabene1111** [comment]
I guess the text class has to be changed as well with the color

**Comment by mud1tx** [comment]
Is this issue is still open I can work on it.

**Comment by vabene1111** [comment]
it is, feel free to fix this, should be just the class in the template helper.

**Comment by Parth-Chavda** [comment]
Can I try to fix it?

**Comment by vabene1111** [comment]
this can now be changed in any way liked
