### ISSUE TITLE
View Pictures in Fullscreen

### ISSUE THREAD

**Issue by smilebasti** [TandoorRecipes/recipes#237]
I would love to see pictures of a recipe in Fullscreen. Maybe also scrolling through them in this modus.

Thanks

**Comment by B5m3M** [comment]
Also - More picture might be a big addon. I often keep more than one picture in my Paprika App to show me steps or how the food should look like.

**Comment by vabene1111** [comment]
you can add "files" to you recipes. This feature is very beta and not mentioned anywhere on purpose (as i did not yet have the time to properly test it) but it should be usable. Feel free to try it out and let me know how it works

**Comment by vabene1111** [comment]
#664
