### ISSUE TITLE
Pic search on the internet for a recipe

### ISSUE THREAD

**Issue by iamkarlson** [TandoorRecipes/recipes#2383]
### Is your feature request related to a problem? Please describe.

I built up some recipes on my own. however, they're based on some common dishes. I would love to quickly add a photo to the recipe. I can search for photos over the internet but if I want to add it, I have to save the picture on my computer, and the edit the recipe. It's a bit tedious. 

### Describe the solution you'd like

Recipe edit page supports drag-n-drop, some confirmation dialog here would be nice.

or as an alternative, to have a hook for Ctrl+V keyboard event, and if clipboard contains image - replace the cover (again would be nive to have a confirmation dialog).

**Comment by vabene1111** [comment]
improving how to store images will be part of the new recipe editor design at some point, i probably wont build a custom image browser like for example whatsapp has, but having ctrl + v ability would certainly be nice. 

closing this and moving to recipe editor rework
