### ISSUE TITLE
0 recipes for the ingrdient but can't delete

### ISSUE THREAD

**Issue by iamkarlson** [TandoorRecipes/recipes#2385]
### Tandoor Version

1.4.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

For this particular example, I'm trying to delete "dried elbow pasta". Interface shows that there's no associtated recipes. 
![image](https://user-images.githubusercontent.com/4534374/227041475-9dc242ce-c6eb-4e9b-bac1-3f8425e5c724.png)

However, I'm getting an error when trying to delete it. 

### Relevant logs

```shell
Response:

The object you are trying to delete is still used and can't be deleted.
{"error":true,"msg":"dried elbow pasta is part of a recipe step and cannot be deleted"}
```
```

**Comment by vabene1111** [comment]
sadly deletion is a little bit broken. i need to build some speical pages for that. for now if you want it gone just merge it witht something else.
