### ISSUE TITLE
Add API Endpoint to describe currently running version

### ISSUE THREAD

**Issue by thickconfusion** [TandoorRecipes/recipes#2386]
### Is your feature request related to a problem? Please describe.

Is there an API endpoint or URL that will tell me Tandoor Recipes deployed version?

### Describe the solution you'd like

I know I can see it at /system/, but I'd like to have an API endpoint. I'm not sure it makes sense for this to be publicly available or if you need API key header or not.

### Additional context

https://discord.com/channels/890556779023466497/890574810000797707/1003715872185122946

**Comment by thickconfusion** [comment]
@vabene1111 Do you think this is still upcoming?

**Comment by vabene1111** [comment]
the /openapi/ endpoint already contains version information if the container is build correctly. This might be broken on the last update but all other versions have had this information for quite a while. 

Need to close this issue, dont know why I left this open last time.

**Comment by thickconfusion** [comment]
When I access `/openapi/` from Version 1.5.5/docker, I get

`openapi: 3.0.2
info:
  title: Django Recipes
  version: ''
`

I'll look at it in the next version.

> probably need to write some more documentation for using the API

I was also looking at `/api/`, which is different and doesn't provide a version.

**Comment by thickconfusion** [comment]
Request to re-open. /openapi/ in today's pull/version 1.5.10 still shows `openapi: 3.0.2 info: title: Django Recipes version: '' `

**Comment by vabene1111** [comment]
ok so this should be fixed now, if no version number can be found it will use the commit ref as the API version. Need to check again after next tagged release but hope this works.

**Comment by thickconfusion** [comment]
@vabene1111 This works at /openapi/ version 1.5.11. Thanks!

**Comment by vabene1111** [comment]
perfect, thanks for confirming it works now :)
