### ISSUE TITLE
Social Account Providers is of type str

### ISSUE THREAD

**Issue by EvanDurfee** [TandoorRecipes/recipes#2400]
### Tandoor Version

1.4.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

I set up a working Tandoor instance, and am trying to add integration with keycloak based on the instructions here: https://docs.tandoor.dev/features/authentication/

However, if I try to set `SOCIALACCOUNT_PROVIDERS`, Tandoor crashes trying on startup.

Here's the relevant config.env section:

```
SOCIAL_PROVIDERS=allauth.socialaccount.providers.keycloak
SOCIALACCOUNT_PROVIDERS='{ "keycloak": { "KEYCLOAK_URL": "https://auth.mydomain.com/", "KEYCLOAK_REALM": "MyRealm" } }'
```

I tried setting `SOCIALACCOUNT_PROVIDERS='{}'` and `SOCIALACCOUNT_PROVIDERS='{"keycloak": {}}'`as well for a simple test, but those result in the same error messages and crash.

Has something changed with the parsing since the guide was written?

### Relevant logs

```shell
File "/opt/recipes/venv/lib/python3.10/site-packages/allauth/socialaccount/providers/keycloak/provider.py", line 5, in <module>
    from allauth.socialaccount.providers.openid_connect.provider import (
  File "/opt/recipes/venv/lib/python3.10/site-packages/allauth/socialaccount/providers/openid_connect/provider.py", line 85, in <module>
    for server_settings in app_settings.PROVIDERS.get(OpenIDConnectProvider.id, {}).get(
AttributeError: 'str' object has no attribute 'get'
[2023-03-27 20:27:36 +0200] [13] [INFO] Worker exiting (pid: 13)
```

**Comment by smilerz** [comment]
I was able to succesfully set `SOCIALACCOUNT_PROVIDERS`  Can you update to the latest releast and confirm if you still have the issue.

![image](https://github.com/TandoorRecipes/recipes/assets/1808639/033df82b-df5e-42d0-ab36-a8a438a9609f)

**Comment by siggnal460** [comment]
For the record, it's probably because you had single quotes around the value (as I did).
