### ISSUE TITLE
Add input for a missing ingredient count to the "Make Now" search

### ISSUE THREAD

**Issue by ignas2526** [TandoorRecipes/recipes#2402]
### Is your feature request related to a problem? Please describe.

When the "Make Now" search filter is switched on, it shows recipes for which all ingredients are available or one is missing. In some situations, it would be very useful to see recipes for which two or more ingredients are missing.

The motivation behind this request is that the difficulty of obtaining ingredients does not correlate with their count. Obtaining one seasonal ingredient outside of the season can be impossible while obtaining two readily available ones from a supermarket five minutes away is easy.

### Describe the solution you'd like

Next to the "Make Now", add an input field that would accept a number of the ingredients starting from zero. Show recipes with the missing ingredient count that is lower or equal to that number.

### Describe alternatives you've considered

Go to the specific recipe, click "Add to Shopping" and see how many ingredients will be added. With a small number of recipes and a rough knowledge of which recipes require what ingredients it is feasible, but as the number of recipes grows, this will become not feasible.

**Comment by smilerz** [comment]
I looked into doing something similar to this, but the query that it generates is very resource intensive, so is very unlikely to ever be implemented on the front end.

There is a technical workaround (requires knowledge and ability to edit database tables directly) that I can share with you if you ping me on Discord. Not exactly what you are looking for, but it's close.
