### ISSUE TITLE
current day in meal plan on mobile view

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#2423]
### Is your feature request related to a problem? Please describe.

It is difficult to find the current day or recipe. 
1) If today is friday or weekend I need to scroll to view the entry
2) all days have the same color (in desktop view the current day has another background color)

### Describe the solution you'd like

1) show today on the top and remove last days (if the same week). Probably show next 7/14 days no matter which week
2) mark background of current day

**Comment by khuslenmisheel** [comment]
Fixed the issue
