### ISSUE TITLE
External recipe iframe is not aware of base path variable

### ISSUE THREAD

**Issue by upbeat-eggplant** [TandoorRecipes/recipes#2424]
### Tandoor Version

1.4.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

I have a nginx reverse proxy that passes the requests to the nginx that comes with the tandoor docker compose config.

### Bug description

Setup:

My Tandoor installation resides at example.com/recipes. Static files also need to be loaded form example.com/recipes/static and media from example.com/recipes/media. Other than the issue I am reporting this setup is completely functional to the best of my knowledge. Because Tandoor is otherwise functional I do not believe this to be a configuration issue.

Issue:

I have imported a pdf to be displayed as an external recipe. However, the iframe that is supposed to load the recipe references `/static/pdfjs/viewer.html?file=<file>`. This path does not exist in my installation.

Instead it should reference `/recipes/static/pdfjs/viewer.html?file=<file>`. 
When I adjust the path in the inspector of my browser the file loads as expected.

I've done a bit of poking around and suspect the issue to be in one of the following files:
[PdfViewer.vue](https://github.com/TandoorRecipes/recipes/blob/f66bf13ec57b0b4ca1603059656b8721593f80f6/vue/src/components/PdfViewer.vue)
[FileViewer.vue](https://github.com/TandoorRecipes/recipes/blob/956693b7ca61cdee7f1c557b782bf30b689ce8c7/vue/src/components/FileViewer.vue)

But since I am unfamiliar with the project I may be mistaken.
Thank you for making this awesome app!

**Comment by vabene1111** [comment]
Interesting, it could be that we never added sub path compatibility for external recipes
