### ISSUE TITLE
MealPlan Dates in EU format

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#2430]
### Tandoor Version

8a8be7f

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

Displayed dates in Search view and Meal Plan view show in DD-MM format in the US instead of expected MM-DD format.

**Comment by vabene1111** [comment]
Interseimting, moment is loaded with the current locale. For me it is in the correct German Format.

![Screenshot_2023-04-23-09-19-00-24_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/6819595/233825750-45d69f39-eb91-48ab-b498-2c989e7b059e.jpg)

What locale do you have set?

**Comment by smilerz** [comment]
That’s also how it displays in US locale which is incorrect.

**Comment by vabene1111** [comment]
ah ok understood, its the other way around i missread your issue, so we need to see why the localization is wrong there

**Comment by aditiirathod** [comment]
can I work on this issue? can u please assign this to me.

**Comment by vabene1111** [comment]
feel free to work on this issue
