### ISSUE TITLE
Search for single words fails on Desktop and Mobile browsers

### ISSUE THREAD

**Issue by strangezuffi** [TandoorRecipes/recipes#2438]
A search for words contained in the title of recipes turns up nothing in my installation.

I have for example a recipe called "Munich Mule".
A search for "Munich", "Mule" or "Mule Munich" (without quotation marks) turns up nothing. A search for "Munich Mule" returns the recipe.

Is it a missing option, or a handling error?

![image](https://user-images.githubusercontent.com/55065045/234669095-de5c23fa-f13b-4a97-ab45-e4847aa53d5e.png)

![image](https://user-images.githubusercontent.com/55065045/234669161-84720e19-481e-4a6e-a42e-a9a0902380ff.png)

**Comment by strangezuffi** [comment]
here you are:

![image](https://user-images.githubusercontent.com/55065045/234671120-13930b41-047e-4df8-85f9-d414cbed38ef.png)

**Comment by strangezuffi** [comment]
And lo and behold, when I add "name" to "Start with" and "partial match", it works!

Thanks, I'd never have expected it to be missing basic settings!

**Comment by smilerz** [comment]
> And lo and behold, when I add "name" to "Start with" and "partial match", it works!
> 
> Thanks, I'd never have expected it to be missing basic settings!

Yeah, depending on when you installed initially defaults don’t always flow through.
