### ISSUE TITLE
Send Language Header when importing

### ISSUE THREAD

**Issue by MeneDev** [TandoorRecipes/recipes#2441]
### Is your feature request related to a problem? Please describe.

I was trying to import recipes from KptnCook. It’s working, but despite the German link and my German ui, the recipe is important in English.

### Describe the solution you'd like

Apparently that changes when the language header is set. I haven’t tried that inside this project, but only with curl.

### Describe alternatives you've considered

It’s also possible to add a query parameter to the URL, but that is specific to KptnCook and I imagine other websites may have the same problem.

**Comment by smilerz** [comment]
This would be a feature request for the library we use for url importing. 

https://github.com/hhursev/recipe-scrapers
