### ISSUE TITLE
can´t import from 99rezepte

### ISSUE THREAD

**Issue by mczeus** [TandoorRecipes/recipes#2442]
### Issue

it is possible to import from https://99rezepte.com/. Unfortunately I always get an error message

### Tandoor Version

1.4.9

### OS Version

ubuntu 20.10

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

**Comment by smilerz** [comment]
You can request that site to be added here. https://github.com/hhursev/recipe-scrapers
