### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by tinju87** [TandoorRecipes/recipes#2459]
### Tandoor Version

latest

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Hi,

I am using docker-compose running on portainer. I had to change port 80 to port 8081 because it is taken by another container.
This is only concerning images everything else is working fine on both LAN IP and domain name.

Not working:
https://domain.com/media/recipes/b0b88398-ba8e-4ee8-85ad-7367b1f92a78_30.jpg

Working:
http://172.20.20.1:8081/media/recipes/b0b88398-ba8e-4ee8-85ad-7367b1f92a78_30.jpg

I already played around with some env variables but without any luck.

### Relevant logs

```shell
#######
docker-compose
#######
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - stack.env

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - stack.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 8081:80
    env_file:
      - stack.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro

volumes:
  nginx_config:
  staticfiles:

#######
env
#######
DEBUG=0
SQL_DEBUG=0
DEBUG_TOOLBAR=0
ALLOWED_HOSTS=*
SECRET_KEY=hidden
TIMEZONE=Europe/Berlin
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=hidden
POSTGRES_DB=djangodb
FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0
```

**Comment by smilerz** [comment]
can you please provide logs from your nginx container and browser console

**Comment by smilerz** [comment]
how are you providing SSL and name services?  Is there another proxy in front of nginx?

**Comment by smilerz** [comment]
The GET request for the image never hits nginx.  My guess is that the front-end proxy needs to be modified to forward all of the headers required by Tandoor.
You can get a sense for what is missing by reviewing the headers in the DEBUG section of `/system/ ` with and without the HAProxy.

**Comment by smilerz** [comment]
not sure what that's for - your nginx log never sees the request for the image. 
That means the problem is upstream from tandoor.

**Comment by tinju87** [comment]
I don't know why I only start to see those logs for now... however the request is hitting nginx and tandoor behind.

Logs from the tandoor-web_recipes container:
172.240.9.4 - - [08/May/2023:07:52:44 +0200] "GET /favicon.ico HTTP/1.0" 404 22295 "https://domain.com/media/recipes/b0b88398-ba8e-4ee8-85ad-7367b1f92a78_30.jpg" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"[tandoor-web_recipes-1]

Logs from the tandoor-nginx_recipes container:
172.30.30.107 - - [08/May/2023:05:52:44 +0000] "GET /favicon.ico HTTP/1.1" 404 22295 "https://domain.com/media/recipes/b0b88398-ba8e-4ee8-85ad-7367b1f92a78_30.jpg" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0" "172.30.30.24"

**Comment by smilerz** [comment]
those logs don't look right - they are all attempting to GET favicon.ico
additionally, media requests can't hit tandoor_web and definitely can't get fulfilled by it as /media is being served by the nginx container.
