### ISSUE TITLE
Recipe images served behind Cloudflare aren't fetched or saved correctly

### ISSUE THREAD

**Issue by Georift** [TandoorRecipes/recipes#2466]
### Tandoor Version

develop@135640dd5832621f2ac26eaff56dc4351686f1e4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

I noticed a couple recipes that were imported didn't have the images attached. When checking out the media file on disk the contained HTML

```
$ head ef81fbdd-ed84-47e4-8b0f-3d1e07269935_26.jpeg

<!DOCTYPE html>
<html lang="en-US">
   <head>
      <title>Access denied</title>
      <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
      <meta name="robots" content="noindex, nofollow" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <link rel="stylesheet" href="/cdn-cgi/styles/errors.css" media="screen" />
      <script>
(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:
```

This occur when the server makes a request to a website which is being served by Cloudflare. It looks like the user agent `python-request/x.xx.x` is being blocked to stop scrapers? You can see this illustrated here:

```
$ curl -o - -I -H "User-Agent: python-requests/2.27.1" https://thebigmansworld.com/wp-content/uploads/2020/10/snickers-cake8.jpg

HTTP/2 403
date: Sun, 14 May 2023 09:53:07 GMT
content-type: text/plain; charset=UTF-8
content-length: 16
x-frame-options: SAMEORIGIN
referrer-policy: same-origin
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
server: cloudflare
cf-ray: 7c724097ea588xae
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

However if we remove this user agent is seems happy with us:

```
$ curl -o - -I -H "User-Agent: " https://thebigmansworld.com/wp-content/uploads/2020/10/snickers-cake8.jpg

HTTP/2 200
date: Sun, 14 May 2023 09:54:49 GMT
content-type: image/jpeg
content-length: 53848
access-control-allow-origin: *
cache-control: public, must-revalidate, proxy-revalidate, immutable, max-age=31536000, stale-while-revalidate=86400, stale-if-error=604800
cf-bgj: imgq:85,h2pri
cf-polished: status=not_needed
etag: "5f87c2ca-d258"
last-modified: Thu, 15 Oct 2020 03:32:26 GMT
vary: Accept-Encoding
x-hosted-by: BigScoots
x-powered-by: centminmod
cf-cache-status: HIT
age: 6672
accept-ranges: bytes
server: cloudflare
cf-ray: 7c7243117b2e5150
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

A couple things that I think we should attempt to do:

- [ ] Change the user agent that we send when fetching the image
  - perhaps the User-Agent that of the web browser that's saving the recipe?
- [ ] Look at the response status code and content-type, if they aren't 200 and `image/*` then don't save the image.
  - at the moment it just saves anything returned.  

Example recipe where this is occurring: https://thebigmansworld.com/vegan-snickers-cake/

**Comment by smilerz** [comment]
The scraper is an external library. You can report your enhancement here: https://github.com/hhursev/recipe-scrapers

**Comment by Georift** [comment]
Thinks @smilerz, I've checked out that library, they appear to be [injecting a user-agent correctly](https://github.com/hhursev/recipe-scrapers/blob/0e7058bf6c1ad023587112dda29e31ff523cace7/recipe_scrapers/_abstract.py#L15-L17) to fake being a browser.

```python
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
}
```

The issue we're encountering here is when we fetch the image with `requests` that's being done in the project, not that library.

https://github.com/TandoorRecipes/recipes/blob/7a2ccc075c3fbb087d445f257f02ffa600f39264/cookbook/views/api.py#L897-L901

Would you be open to a PR that adds this user-agent to this `request.get()` call?

**Comment by vabene1111** [comment]
thanks for the well prepared instructions, added the user agent and was able to import your example recipe with an image

**Comment by Georift** [comment]
Amazing thank you!
