### ISSUE TITLE
Can't import rescipes from rezeptsuite

### ISSUE THREAD

**Issue by boospy** [TandoorRecipes/recipes#2467]
### Tandoor Version

1.4.9

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Hello all, 

i have about 600 recipes on my local software from rezeptsuite.de. For import, i exported the DB as xml like rezeptSuite-15-05-2023.cml. But if i import the file, i get success on the importpage with 0 imported recipes. So i enabled debug and get this error message below.

Can anyone help to get importer running with rezeptsuite.de?

Very thanks
Best Regards :)

### Relevant logs

```shell
tandoor-rezepte-web_recipes-1    | Traceback (most recent call last):
tandoor-rezepte-web_recipes-1    |   File "/opt/recipes/cookbook/integration/integration.py", line 212, in do_import
tandoor-rezepte-web_recipes-1    |     recipe = self.get_recipe_from_file(f['file'])
tandoor-rezepte-web_recipes-1    |   File "/opt/recipes/cookbook/integration/rezeptsuitede.py", line 22, in get_recipe_from_file
tandoor-rezepte-web_recipes-1    |     name=recipe_xml.find('head').attrib['title'].strip(),
tandoor-rezepte-web_recipes-1    | AttributeError: '_io.BytesIO' object has no attribute 'find'
```

**Comment by boospy** [comment]
Thank you for your reply. I have generated a new DB with some recipes. File attached. 
[rezeptSuite-17-05-2023.cml.zip](https://github.com/TandoorRecipes/recipes/files/11499332/rezeptSuite-17-05-2023.cml.zip)

**Comment by boospy** [comment]
I've read in forum and the handbook, but i can't find something to export directly as XML.

**Comment by vabene1111** [comment]
interesting, i will need to investigate this, might be that something changed there

**Comment by boospy** [comment]
> interesting, i will need to investigate this, might be that something changed there

ok, thank you

**Comment by vabene1111** [comment]
ok so looks like recipesuite zips there exports and renames their xml to .cml for whatever reason.

I added to the docs that you need to unzip the export and rename .cml to .xml

I also hardened the importer to better handle non available fields and got your import to work very well.

**Comment by boospy** [comment]
Very thanks @vabene1111 so i wait for the next relelase (i use docker), right?

**Comment by vabene1111** [comment]
Correct, shouldn't be too long, just waiting for some feedback on the latest beta (which you can test if you want) and will release it afterwards.
