### ISSUE TITLE
Ability to leave comments on recipes 

### ISSUE THREAD

**Issue by hoggatt** [TandoorRecipes/recipes#2469]
### Describe the solution you'd like

Feel free to correct me if I'm wrong, but I don't believe tandoor has an easy way of leaving comments or notes on recepies that I've made. For example, I might want to say "do this different next time". 

It would be nice to have a way of leaving yourself notes or comments on the recipe for next time you make it! There is something about logging when you've made a recipe, but it's hard to get to get to and you can't easily add/view notes. Maybe a comments section at the bottom of each recipe would be nice.

**Comment by vabene1111** [comment]
![image](https://github.com/TandoorRecipes/recipes/assets/6819595/7e051e03-025e-4e07-bdb0-0eb23ea13122)

thats already possible, but can be disabled in the .env file

**Comment by hoggatt** [comment]
Thank you so much! I didn't see it in the demo so I assumed it didn't exist. Sorry for wasting your time, I appreciate the quick response.

**Comment by vabene1111** [comment]
No worries, Demo I think has comments disabled.
