### ISSUE TITLE
Copy and Paste Images

### ISSUE THREAD

**Issue by TheDeluxeThrowaway** [TandoorRecipes/recipes#2473]
### Describe the solution you'd like

I would just like the ability to be able to copy and paste or drag and drop an image when creating a recipe instead of having to download the image and upload it.

### Describe alternatives you've considered

Drag and drop image, copy and paste, copy image link and upload that way

**Comment by Dibyarajanan** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> _No response_
> 
> ### Describe the solution you'd like
> 
> I would just like the ability to be able to copy and paste or drag and drop an image when creating a recipe instead of having to download the image and upload it.
> 
> ### Describe alternatives you've considered
> 
> Drag and drop image, copy and paste, copy image link and upload that way
> 
> ### Additional context
> 
> _No response_
>use break

**Comment by TheDeluxeThrowaway** [comment]
idk github etiquette and think it would be rude to just spam a bunch of feature requests so ill just add comments here. When you're trying to edit a recipe it really shouldn't default to a long list of past ingredients and should instead default to letting you edit your text. It's really annoying having to scroll past 130+ spices to just change the brand of peanut butter

**Comment by TheDeluxeThrowaway** [comment]
![image](https://github.com/TandoorRecipes/recipes/assets/134332457/dd2add04-52a3-4880-b480-d959a9d237db)
When typing in new keywords if my cursor is accidentally hovering over the box when I press enter whatever the cursor is hovering over supersedes whatever text I just typed which is wonky asf

**Comment by smilerz** [comment]
That 

> ![image](https://user-images.githubusercontent.com/134332457/241792023-dd2add04-52a3-4880-b480-d959a9d237db.png)
> When typing in new keywords if my cursor is accidentally hovering over the box when I press enter whatever the cursor is hovering over supersedes whatever text I just typed which is wonky asf

This is unrelated to the original ticket. Additionally this would need to be address upstream in vue-multiselect.

**Comment by TheDeluxeThrowaway** [comment]
How much of this selection screen is just up stream?

**Comment by TheDeluxeThrowaway** [comment]
Auto save and link and multiple image embeds should be a thing. 1 it's annoying to have to default save every time so a toggle would be certainly useful 2. some recipes have images for each step to help cause they're complicated and that's useful

**Comment by TheDeluxeThrowaway** [comment]
Being able to ctrl+click to edit would be better when you add a bunch of new recipes but all don't apply to the tag you want to add but they all have the same search string you want to use. For example I might want to import all claire saffitz recipes but only want to tag some of them with the chocolate tag but notall of her recipes use chocolate
