### ISSUE TITLE
Add step for venv activation

### ISSUE THREAD

**Issue by nabim777** [TandoorRecipes/recipes#2479]
### Documentation link

https://docs.tandoor.dev/install/manual/

### Affected section

Installation

### Issue description

Since the virtual environment is not activated after creation, we can add code 
source bin/activate.

**Comment by imharyohm** [comment]
Hey, please assign this to me

**Comment by The-Priya-Saw** [comment]
hello @TandoorRecipes, I would like to solve this issue. can u please assign me ?

**Comment by vabene1111** [comment]
feel free to take up this issue :)
