### ISSUE TITLE
issue related to split view

### ISSUE THREAD

**Issue by KarunAtreya** [TandoorRecipes/recipes#2495]
### Tandoor Version

latest develop branch

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

On units page(/list/unit/)
when the split view button is toggled on and off multiple times the unit items get added each time on the right split part

## steps to reproduce
1. Browse to units page
2. Turn on the split view 
3. Turn off the  split view and turn it on again

## Actual Behavior
[unitpagesplitissue.webm](https://github.com/TandoorRecipes/recipes/assets/33852651/213321c8-0daa-404a-9182-d11177926c6c)

## Expected Behaviour
Splitting multiple times should not make copy of the unit items each time

**Comment by smilerz** [comment]
interesting - the infinite loader gets destroyed at each toggle, so doesn't know that there are items already loaded.
The alternative would be to destroy the already loaded cards, but you'd end up losing any filtering that had already occurred.

Will have to look at this after the vue upgrade.

**Comment by smilerz** [comment]
duplicate with #1654
