### ISSUE TITLE
Adding in same unit for different ingredients make up duplicates to the unit list

### ISSUE THREAD

**Issue by KarunAtreya** [TandoorRecipes/recipes#2502]
### Tandoor Version

latest develop branch

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

## Actual behavior
While adding unit for the ingredient when same unit is added for another ingredient, both get added to the unit list creating duplicates.

## Expected behavior
The duplicates of same unit should not be created in the unit list.

[ingredintsunitduplicateissue.webm](https://github.com/TandoorRecipes/recipes/assets/33852651/14e5d87c-aca1-4e10-874e-037bd8bce540)

## Note: 
this issue is also same for the name of ingredients

**Comment by smilerz** [comment]
That's the behavior of the component being used - duplicates aren't created in the database.  
You can open an issue for the component [here](https://vue-multiselect.js.org/).
