### ISSUE TITLE
"ignore shopping" is not honored when adding recipes to the shopping list

### ISSUE THREAD

**Issue by level20peon** [TandoorRecipes/recipes#2504]
### Tandoor Version

06a08dcf6e981dd09f0c7f469410805d49ba9d18

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

When adding a recipe to shopping from (1) the recipe list and (2) the recipe details page, ingredients marked as "ignore shopping" are added to the shopping list (salt, for example). I double checked and the ingredients in question are still marked as "ignore shopping" in the ingredient admin interface.

![image](https://github.com/TandoorRecipes/recipes/assets/14050847/d8d4281c-dab0-4cf6-9a7f-70ff56eedc88)

![image (1)](https://github.com/TandoorRecipes/recipes/assets/14050847/9432c067-28fe-42c1-8ab3-a13639989af9)

**Comment by level20peon** [comment]
I just updated to the latest master (9decf3cf148f55428a3a37861437b01e86b6a1ec) and the issue still persists.

**Comment by vabene1111** [comment]
As long as the issue is open I would expect that to happen

**Comment by level20peon** [comment]
true, but I thought I'd mention it because it might have been fixed in all the cleaning up you probably did on the release yesterday :)
