### ISSUE TITLE
remove letters after add food to shopping list

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#2506]
### Is your feature request related to a problem? Please describe.

In shopping list I can search for a food and add it to shopping list
![image](https://github.com/TandoorRecipes/recipes/assets/29805669/78fea452-bb28-4d71-a119-7d5321f802f1)

After clicking on add and jump back to food field the text is still there.

### Describe the solution you'd like

Clear the field after adding food to shopping list.

**Comment by Swllydogtaylor123** [comment]
I appreciate you for that receipt I'll put it up
