### ISSUE TITLE
All foods nutrition data deleted after merging any foods

### ISSUE THREAD

**Issue by panoskpv** [TandoorRecipes/recipes#2513]
### Tandoor Version

Latest

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

I added nutrition data in several foods. After I merged two foods all data for all foods disappeared. I tried the same process few times with the same results.

**Comment by vabene1111** [comment]
interesting, i will need to fix that

**Comment by vabene1111** [comment]
fixed, was an oversight when i changed the models
