### ISSUE TITLE
Importing a community curated list leads to an error 

### ISSUE THREAD

**Issue by panoskpv** [TandoorRecipes/recipes#2514]
### Tandoor Version

Latest

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When I try to import a community list in greek (el) I get the following error 'There was an error creating a resource!' and nothing is added. When I try to import english version of this list I get the same error, foods, categories etc. are added but foods are added without nutrion data.

**Comment by vabene1111** [comment]
can you please post some logs from your container so that i can see whats breaking for you?

**Comment by panoskpv** [comment]
After your comment i checked the logs and i got dublicate slug error. I removed all added items and for those i wanted to keep i just deleted the open slug field in admin settings. Now i get the below:

{'selected_version': 'el', 'selected_datatypes': ['food', 'unit', 'category', 'property', 'store', 'conversion'], 'update_existing': True, 'use_metric': True}

Internal Server Error: /api-import-open-data/

Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 306, in _commit

    return self.connection.commit()

psycopg2.errors.ForeignKeyViolation: insert or update on table "cookbook_foodproperty" violates foreign key constraint "cookbook_food_properties_food_id_4c533fef_fk_cookbook_food_id"

DETAIL:  Key (food_id)=(211) is not present in table "cookbook_food".

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner

    response = get_response(request)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view

    return view_func(*args, **kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view

    return self.dispatch(request, *args, **kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch

    response = self.handle_exception(exc)

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception

    self.raise_uncaught_exception(exc)

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

    raise exc

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch

    response = handler(request, *args, **kwargs)

  File "/opt/recipes/cookbook/views/api.py", line 1455, in post

    response_obj['food'] = len(data_importer.import_food())

  File "/opt/recipes/cookbook/helper/open_data_importer.py", line 193, in import_food

    FoodProperty.objects.bulk_create(property_food_relation_list, ignore_conflicts=True, unique_fields=('food_id', 'property_id',))

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 796, in bulk_create

    with transaction.atomic(using=self.db, savepoint=False):

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/transaction.py", line 262, in __exit__

    connection.commit()

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 330, in commit

    self._commit()

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 305, in _commit

    with self.wrap_database_errors:

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 306, in _commit

    return self.connection.commit()

django.db.utils.IntegrityError: insert or update on table "cookbook_foodproperty" violates foreign key constraint "cookbook_food_properties_food_id_4c533fef_fk_cookbook_food_id"

DETAIL:  Key (food_id)=(211) is not present in table "cookbook_food".

**Comment by m-oezokyay** [comment]
I just set up an instance with the latest version and ran into a similar issue. I haven't tried today's build (pulling images takes a loooong time on my NanoPi), but I don't see any recent commits to _open_data_importer.py_, so this might help:

```stdout: {'selected_version': 'de', 'selected_datatypes': ['food', 'unit', 'category', 'property', 'store', 'conversion'], 'update_existing': True, 'use_metric': True}
stderr: Internal Server Error: /api-import-open-data/
stderr: Traceback (most recent call last):
stderr:   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
stderr:     response = get_response(request)
stderr:   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
stderr:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
stderr:   File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
stderr:     return view_func(*args, **kwargs)
stderr:   File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
stderr:     return self.dispatch(request, *args, **kwargs)
stderr:   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
stderr:     response = self.handle_exception(exc)
stderr:   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
stderr:     self.raise_uncaught_exception(exc)
stderr:   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
stderr:     raise exc
stderr:   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
stderr:     response = handler(request, *args, **kwargs)
stderr:   File "/opt/recipes/cookbook/views/api.py", line 1483, in post
stderr:     response_obj['food'] = len(data_importer.import_food())
stderr:   File "/opt/recipes/cookbook/helper/open_data_importer.py", line 135, in import_food
stderr:     'supermarket_category_id': self.slug_id_cache['category'][self.data[datatype][k]['store_category']],
stderr: KeyError: 'category-dry-goods'```

**Comment by vabene1111** [comment]
thanks, i recently did not have much time for this but need to take another round now that there are quite a few objects added to the repository.

**Comment by Kixel** [comment]
Hi, i have the same issue on this version:
Current Version: [1.5.4](https://github.com/vabene1111/recipes/releases/tag/1.5.4)
Ref: [c78b7a69288179202a2a054b19f1de5a2790f4dd](https://github.com/vabene1111/recipes/commit/c78b7a69288179202a2a054b19f1de5a2790f4dd)
with the "de" dataset. How can i get you some logs for this?
I'm running tandoor via a stack (docker compose) in portainer with the reommended docker compose file. It's a quite fresh install (2 days old iirc), running on Lubuntu 22.04LTS.

**Comment by AxaliaN** [comment]
Yeah same here, while importing any locale's data set.

**Comment by BugDeliverer** [comment]
Right now the import fails due to a wrong entry:

Server log:
> web_recipes_1    | ValueError: Field 'fdc_id' expected a number but got '170931-ground'.

Solution:
1. Open food '**Ground Black Pepper**',
2. change value in field '**FDC ID**' to '**170931**'

**Comment by vabene1111** [comment]
yes there are a few of those in the database that need to be changed, I need to also change the plugin to only allow numbers not strings or at least fail the validation for unallowed characters

**Comment by vabene1111** [comment]
ok so just looked into fixing this, this is actually a larger issue

open data requires FDC ID, some foods in FDC can be further refined/specified -> lack FDC ID -> contributers put - something into the ID to differentiate different foods. 

Need to find a proper solution for that

**Comment by BugDeliverer** [comment]
Thanks for your prompt effort and happy new year!
So to solve the current issue either the existing IDs in the open dataset should be changed to integer or datatype in tandoor should be reverted to string.
I think the FDC ID should stay integer and malformed entries should be conformed. As far as I understood this is the only way to keep the links/query with the FDC database working. If there is no correspondent food in the database the FDC ID should be left empty. In case of refined/specified food a note within the recipe can be used.
In case it has to stay an individual food, the usage of the same FDC ID on different foods must be enabled.

**Comment by vabene1111** [comment]
thanks for the ideas, I removed the unique constraint from FDC ID in open data plugin and added some functions to the admin to easily fix these kinds of issues. 

Next thing needs to be preventing invalid inputs from the beginning on but I am very short on time and kinda remember that there was a reason for having the FDC ID a string in open data or at least I need to also change the build script if I change it.

**Comment by BugDeliverer** [comment]
Thank you for investing time in this issue.
After updating to the latest (develop) release tandoor still expects integer hence fails importing the open data. Did you miss changing the data type?
In addition I tried to edit 'wrong' FDC IDs - unfortunately I can not edit food that someone else created.

**Comment by vabene1111** [comment]
the changes I made are not yet live, I only updated the open data plugin which will be updated on the hosted instance once the current develop has been released and found stable, then I can fix the wrong entries 

sorry that this is something that takes so long but I am extremely short on time and need to invest it where its the most pressing and all the open data stuff, while being important for the future of tandoor, is still in kinda of an experimental stage.

**Comment by Blackclaws** [comment]
As 1.5.12 was released just three days ago is this something that could be fixed in the next release of the open-data set? I really want to try out Tandoor and I'd rather import a large list of premade ingredients than enter them all manually.

Honestly this sort of import is a big win if it works well :)

**Comment by vabene1111** [comment]
ok so I have fundamentally reworked how the importer works and tested every combination. You can now also import only selected datasets. From my testing everything seemd to work for now, I am sure there are some edge cases but overall it should work for most of you. 

If you encounter any issues after the next release please raise individual issues with proper logs so I can find out whats broken.
