### ISSUE TITLE
When deleting one nutritinal properly of a food, page refreshes and nothing is saved

### ISSUE THREAD

**Issue by panoskpv** [TandoorRecipes/recipes#2515]
### Tandoor Version

Latest

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When I edit a food and I add all nutritional properties clicking on the relevant button, if i then click to the garbage bin icon to delete a property, page refreshes and no change is saved.

**Comment by vabene1111** [comment]
i just tested this and it all works, have you hit save after deleting the properties? if no the deletion is not saved so you can basically "cancel" it.

**Comment by panoskpv** [comment]
When i delete one property automatically the page refreshes and I get back to the food page with all food listed.

**Comment by vabene1111** [comment]
that is interesting, i cannot reproduce what you are saying

1. open food page
2. open food editor
3. add all properties (4 in my case)
4. add values for all properties
5. delete one property
6. click save
7. everything works

are you on the latest version? what kind of browser are you using?

**Comment by panoskpv** [comment]
I am on the latest docker image. I tried firefox in android(fennec) and ubuntu desktop and brave android. I initially tried to delete a property before adding any numbers. If I add numbers to all properties then i can delete the last ones without problem. However, even in this case if i delete the first one this bug happens again.

**Comment by panoskpv** [comment]
Ok. As soon as i will apply the update I will let you know. Thank you for your efforts.

**Comment by panoskpv** [comment]
[Screencast from 2023-06-26 23-22-11.webm](https://github.com/TandoorRecipes/recipes/assets/84382461/03e4c532-cc87-4cfd-84e7-232a6a4d66a3)
Unfortunately no luck after the update.

**Comment by vabene1111** [comment]
ok so i have one idea, the element was a `<button>` i changed it to be `<a>` maybe that caused the issue, because i can not reproduce it and i do not see any other explanation as there really is just one line of code behind that button. 

It will be in the next release, please feel free to let me know if it works

**Comment by panoskpv** [comment]
Using the latest version of Tandoor, above issue was fixed.

Thank you for your time and this very usefull tool.
