### ISSUE TITLE
decimals in properties issue

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#2518]
from @dsm1212 

I realized you are still working on this so not submitting an issue, but the few things I tried to enter as a food just won't take. Here's a simple one. Baking powder at 1tsp (or 4.6g) has 1.3g of carbs. I tried to enter this multiple ways and none will work correctly. 4.6g/1.3g is an error saving. 1tsp/1.3g won't save correctly, it says success but ends up saving 1g/1.3g and with that impossible combo for 1tsp in recipe it show 0.05g of carbs which is odd. 46g/13g will save but the carb calculation for 1tsp in a recipe is 0. Probably I'm not doing the right thing with units.

> opening a new issue as it has nothing to do with the other thread where this was posted

**Comment by vabene1111** [comment]
can confirm this is buggy

first of all food amounts did not support decimals, i added that but there is something else broken, looking into what it is

**Comment by vabene1111** [comment]
fixed the other issue as well

**Comment by dsm1212** [comment]
Thanks, is better but i'm still easily getting incorrect results. Couple of examples:

1. I set all purpose flour to 120g having 16g protein and 92g carb. I had to use 120g because I could not get 1cup to save. It seems like once you save the unit on that field it cannot be changed?
2. I added conversion of 120g to 1cup.

In a recipe which calls for 1.5 cups of all-purpose flour I get the correct totals for carbs and protein.
In a recipe for 1.25 cups of all-purpose flour I get zeros.
In a recipe for 2 cups of all-purpose flour I get zeros.
In a recipe for 2.5 cups of all-purpose flour I get zeros.

In all cases I'm drilling to the recipe by selecting "16 recipes" under all-purpose flour.

**Comment by vabene1111** [comment]
ok thanks, i need to look into that, reopening for now

**Comment by vabene1111** [comment]
i think all of this might be releated to a bug in the frontend. I wasn't abel to fully test this as i need to leave my desk now but i pushed the fix on beta (which is currently pretty stable). 

The problem was that the food editor would always show gram as i had a small piece of code setting the frontend to "g" regardless of what it actually was. so you probably had cups set but it was showing grams. I did it to set the default unit to g but forgot to check if anythign else was already present. 

If you want you can try out if the issue is fixed, if not i will when i get the time to do so

**Comment by dsm1212** [comment]
Sorry, I never switched to beta. I'm not seeing any difference on mainline (yet).

**Comment by dsm1212** [comment]
Ah, I take that back, it is better. What I'm seeing now is that some recipes I used the word cups when it was > 1 cup and my conversion is for cup. I added an identical conversion for cups and now it works. This is fine, but I mention only because you might want to add volume equalities globally. Then you could automatically include plurals as well as common things like 3tsp == 1Tbl so we don't have to add them everywhere.

Is it possible to  manually add another property?  Sodium, Potassium in particular. These have an impact on kidneys and some people count them, if I'm going to enter this stuff I'd like to enter these as well.

Thanks!

**Comment by vabene1111** [comment]
if you have plurals or not depends on what units you created. if you created cup and cups seperately you will need to add your own conversions, but you can also add cup with plural cups and only need one. 

regarding properties: you can add as many properties as you like on the property type page

**Comment by dsm1212** [comment]
Sorry I poked around and I can't figure out what this means: "you can also add cup with plural cups and only need one". Are you just saying use the plural all the time or is there a feature to somehow add cup along with cups and it will treat like one unit? I don't see many options on the unit editor. Just "name, description and Open Data Slug". Is open data slug some way to extend to plurals? thx

**Comment by vabene1111** [comment]
![image](https://github.com/TandoorRecipes/recipes/assets/6819595/1e107a0e-4c1c-4c56-86dd-c0b6d491fe33)

it should look like this with plural on the second line. Add "cup" as name "cups" as plural. Maybe i could add cup as a base unit as well but i think its a bit disputed how large a cup actually is

**Comment by dsm1212** [comment]
Wierd that is not what I see. I only have name, description, and open data slug. Maybe I should switch to beta?

**Comment by langbein-daniel** [comment]
> Wierd that is not what I see. I only have name, description, and open data slug. Maybe I should switch to beta?

I'm not on beta (version 1.5.4) and I can enter plural names of ingredients. Can you double check the version you are running on @dsm1212? You can view it in Tandoor through the `System` menu entry.

**Comment by dsm1212** [comment]
Current Version: [1.5.4]

Here is my edit unit window:

![image](https://github.com/TandoorRecipes/recipes/assets/7332569/2337d85e-c2f0-4ae0-b8be-e6a10f3a77ab)

**Comment by dsm1212** [comment]
Oh, wait, I'm choosing + from the units window. Are we talking about the Ingredients window? I have not used that yet. Foods seems to list all my ingredients so I'm not sure what the ingredients window does :-(. It has nothing in the list there right now.

**Comment by dsm1212** [comment]
Ok even though I'm not 100% sure what this window does, I got it to work. If I add the plural and then merge the plural to the singular it ends up in the right place. Very nice, thanks!

**Comment by vabene1111** [comment]
That is super strange, there used to be a setting of plurals should show or not but that was removed a few versions ago. Need to look into the code to see why this happens

**Comment by vabene1111** [comment]
ok so i looked at the code, i cannot find any condition that would hide the plural field. There was one in old versions so i suspect there could be a caching thing if you are on the latest version. 

Can you check that you have the latest version installed and maybe clear the browser cache? this way there should not be any units left where you cannot edit the plural.

**Comment by dsm1212** [comment]
I had already tried those things and I wiped my static files and used incognito, but did you see my last update? I can get to the window with the plurals from the ingredients window. From the units window I get the version without the plural. My version is 1.5.4.-SteveOn Aug 7, 2023, at 1:37 AM, vabene1111 ***@***.***> wrote:﻿
ok so i looked at the code, i cannot find any condition that would hide the plural field. There was one in old versions so i suspect there could be a caching thing if you are on the latest version.
Can you check that you have the latest version installed and maybe clear the browser cache? this way there should not be any units left where you cannot edit the plural.

**Comment by vabene1111** [comment]
yea I saw your message but was unsure what it meant. Need to look again but both windows should call the same function 🤔

**Comment by dsm1212** [comment]
FWIW to this day I still don't see plurals on the edit window from the unit list. I can only get at them from selecting the unit in the ingredient window and chosing edit. The other odd thing is after editting a plural from the ingredient window if I choose a different unit the list of recipes updates correctly but if I then pick edit on the new unit no windnow comes up. I have to refresh the tab to edit a second unit from the ingredient window.

**Comment by dsm1212** [comment]
Upgraded to latest and I can edit plurals in the units page :-)
