### ISSUE TITLE
UI glitches: search result hover, quick action button, iPhone home bar

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#2520]
### Tandoor Version

1.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

I noticed some minor UI glitches and wanted to collect them here. All of this is seen on Safari on MacOS and iPhone.

## Recipe Description Hover 
![tandoor](https://github.com/TandoorRecipes/recipes/assets/7606307/a75e6275-2c37-4c5d-b7a0-2337385cd7de)
The description doesn't fit in the image space and spills into the space around it.

By the way: Since a few versions ago, I really miss seeing the recipe ratings on the search page. I think there's enough room in the image for another pill that displays the rating.
I would also appreciate an option to display all the keywords in the search results, since I'd like to see the recipe author, for instance.

## Quick Action Button 
https://github.com/TandoorRecipes/recipes/assets/7606307/2a1dc135-6974-47e6-9734-db7e800d9fcc
The quick action button doesn't move with the rest of the page when pulling down or scrolling to the top.

Also, as the above video shows, the home bar at the bottom of the iPhone interface interferes with the navigation icon texts.

**Comment by vabene1111** [comment]
thanks for the report. 

regarding the recipe card: i always wanted to make it configurable, so at some point you might be able to choose what you like to see :)

**Comment by vabene1111** [comment]
solved for now, will likely be further improved when migrating to the new frontend
