### ISSUE TITLE
Copied ingredients have linked edit fields

### ISSUE THREAD

**Issue by MeneDev** [TandoorRecipes/recipes#2532]
### Tandoor Version

1.5.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

cloudflare tunnel

### Bug description

After copying an ingredient in the edit view, editing any of the fields of either the original or the copy will edit the corresponding other field as well.

https://github.com/TandoorRecipes/recipes/assets/5398875/eeba2984-e712-4851-9a38-aa1243a340df

**Comment by vabene1111** [comment]
thanks for reporting, need to look into if a deep clone is performed to unlink the objects
