### ISSUE TITLE
Disable E-Mail verification or change E-Mail verification message

### ISSUE THREAD

**Issue by kl4ppdrachen** [TandoorRecipes/recipes#2534]
### Issue

Hey, 

I would use Tandoor for my friends, family and me to share all of our recipes. Tandoor and the verification e-mail are working, but I have two questions.

1. It is possible to disable the E-Mail verification? The people I invite to this cookbook are all know people, and I would only share one time the link to create an account. So, in my opinion, there don't need the verification over an E-Mail.
2. When this is not working (or a good option), how can I change the E-Mail message from the verification E-Mail? In my received Mail I got "example.com" and I want to change it. I googled a little bit, but unlucky, I didn't find how to do it.

```
Hallo von example.com!

Du erhältst diese E-Mail, weil der Nutzer Test1 von example.com deine E-Mail-Adresse als seine angab, um sie mit seinem Konto zu verknüpfen.

Um dies zu bestätigen, rufe bitte folgende Adresse auf: 

Danke dass du example.com nutzt!
example.com
```

Thanks and greeting

### Tandoor Version

1.4.5

### OS Version

Linux 5.15.93-rockchip64

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Environment file

```shell
DEBUG=0
SQL_DEBUG=0
ALLOWED_HOSTS=*
SECRET_KEY=
TIMEZONE=Europe/Berlin
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=postgresql
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=
POSTGRES_DB=djangodb
FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0
ENABLE_SIGNUP=0
ENABLE_PDF_EXPORT=0
EMAIL_HOST=
EMAIL_PORT=465
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=
EMAIL_USE_TLS=0
EMAIL_USE_SSL=1
DEFAULT_FROM_EMAIL=
ACCOUNT_EMAIL_SUBJECT_PREFIX= '[Kochbuch] '
```

**Comment by smilerz** [comment]
if you don't configure the email settings it will work as you desire.

**Comment by kl4ppdrachen** [comment]
But when someone is logging in after creating the account, there is a popup (light blue) that says to confirm the E-Mail. This was my question, whether it is possible to disable this (and the E-Mail stuff).

**Comment by smilerz** [comment]
yes - don't configure email on Tandoor

**Comment by kl4ppdrachen** [comment]
![grafik](https://github.com/TandoorRecipes/recipes/assets/47184285/4a741277-878d-4eec-8ecb-d15aeb35fa4d)

I comment it in .env out, but the popup is still showing up.

**Comment by smilerz** [comment]
did you rebuild the container after modifying the env?  you might also need
to manually edit it out the email addresses associated with user accounts
in admin.

**Comment by kl4ppdrachen** [comment]
Created a new docker container. Tried It again, but the same popup. No problem, I told them to ignore this ;)
