### ISSUE TITLE
Guest User is able to copy recipe

### ISSUE THREAD

**Issue by vspaziani** [TandoorRecipes/recipes#2547]
### Tandoor Version

1.5.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I invited a user as a guest which should have 'read only' access to recipes. When the user views a recipe they are able to click the three dots and select 'copy to new recipe' which actually copies the current recipe to another one with the proved name. Expected behavior is that they are denied modifying the space since they are guests.

**Comment by vabene1111** [comment]
thanks for the report. This was actually even reflected in the tests, but I do think you are right, it would be better to give read only access to guests only. 

will change this with the next update.
