### ISSUE TITLE
Sum ingredients at the top of the page

### ISSUE THREAD

**Issue by henrydatei** [TandoorRecipes/recipes#2548]
### Is your feature request related to a problem? Please describe.

I have a recipe where I need sugar in several steps (100g in step 1, 3 teaspoons in step 2, 150g in step 3). When I open the recipe on the top of the the page I get a list of all ingredients needed for the recipe but in this example I see there 3x sugar in different amounts. 

### Describe the solution you'd like

It would be great if instead of having 3x sugar I would like to see sugar as an ingredient only once with an aggregated amout (250g + 3 teaspoons in this example, or, if conversion is possible, 262.5g sugar (conversion by https://www.thecalculatorsite.com/cooking/teaspoons-grams.php)).

**Comment by smilerz** [comment]
Duplicate
