### ISSUE TITLE
Upgrade postgres database 11-alpine to 15-apline

### ISSUE THREAD

**Issue by damomato** [TandoorRecipes/recipes#2550]
### Issue

I noticed in the latest release for the docker-compose file that for the postgres db the 15-alpine tag should now be used instead of alpine 11 tag.

How do we migrate over to 15-alpine? When I try to pull that image to replace it I get the following error. Obviously I'm not fantastic at this stuff.

```
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 15.3.
```

### Tandoor Version

1.5.4

### OS Version

Synology DSM 7.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

**Comment by smilerz** [comment]
There are a couple of supported methods to upgrade the database files.  You can review them [here](https://www.postgresql.org/docs/current/pgupgrade.html).
