### ISSUE TITLE
Serving Size adjustment

### ISSUE THREAD

**Issue by MeneDev** [TandoorRecipes/recipes#2551]
### Is your feature request related to a problem? Please describe.

Often when I import recipes the claimed servings don't match my hunger.
Currently I can adjust the serving size: when I edit a recipe I can change the servings from 2 to 1. Next time I prepare the meal I can set the servings to 2 and will get twice as much as the original recipie.

### Describe the solution you'd like

Ideally I can adjust the servings by a factor.

Example: There are three dots next to the "Servings" field. In the context menu for the three dots, there is an entry "adjust ingredient amounts". A popup appears, asking "Adjust all ingredients by a factor of [text field accepting fractions]"

**Comment by smilerz** [comment]
you can already change the servings and have it scale the recipe

**Comment by MeneDev** [comment]
Yes, but when I edit the recipe I can only enter integers, and when I view it I would need to remember different decimals for each recipe, or am I missing something?

**Comment by smilerz** [comment]
If a recipe lists the servings as 4 and you want to make 50% more you make it 6.  General consensus is the UI is already overly cluttered - its ultimately vabene's call, but I don't think there is willingness to add buttons for math anyone can do in their head.

**Comment by MeneDev** [comment]
I agree that the UI has a lot going on already. My point is less about the math, more about different factors that I would need to remember for different recipes.
I take most recipes from one site and import them. The servings are usually 2, we often increase it to 3, but sometimes 2 is plenty already. Sure the math is trivial, but a way to adjust a recipe so I can "normalize" a newly imported recipe to the rest of my collection strikes me as something of great value to make my collection more reliable and avoid food waste.
But yes, it’s yet another thing that needs some UI 😅 
Maybe there’s a more elegant way? A natural point in time to make adjustments would be after preparing a receipt, but in the "Log Recipe Cooking" this would be surprising. Maybe the "Copy to new receipt" could have an adjustment factor?

**Comment by vabene1111** [comment]
so what i wanted to do for a long time and likely will do when working on the editor again is to add a quick "scale up" / "scale down" button to the recipe directly. That way you can, if you always want something different, just have tandoor calculate 20% more of everything and save it to the recipe. That way you can change the base amount to something that fits a certain number of servings you like and then you can easily double/halve or whatever that amount in the view if more or less people join you for dinner.

**Comment by vabene1111** [comment]
i noticed its already written down so moved this here #1872

**Comment by MeneDev** [comment]
That sounds perfect, sorry for missing the RecipeEditor collection issue!

**Comment by vabene1111** [comment]
no worries, it was not clear what was meant with that short note anyway 😂
