### ISSUE TITLE
PWA - Keyboard not showing on iOS 

### ISSUE THREAD

**Issue by joshsolman** [TandoorRecipes/recipes#2552]
### Tandoor Version

1.5.4

### Setup

Unraid

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Everything works when accessing Tandoor in Safari/Chrome/Firefox however when saving it as a progressive web app on my iPhone 13 Pro. The keyboard does not appear. Stays only at the bottom. I dont have this issue with other web apps.

**Comment by vabene1111** [comment]
@smilerz i know you use the PWA on IOS as well, do you have the same problem?

**Comment by MaxJa4** [comment]
Just tried it out of curiosity on an iPhone 12 Pro. No issues.
By PWA you mean "Save to Home Screen" or something like that, right?

**Comment by smilerz** [comment]
> @smilerz i know you use the PWA on IOS as well, do you have the same problem?

I"ve seen this behavior and other oddities with all of my selfhosted PWA apps.  Least often with Tandoor honestly, most of the time clearing the Safari cache resolves any issues.  Occassionally it requires deleting the PWA and re-adding it.

**Comment by vabene1111** [comment]
closing this as it appears to be an iOS bug/is not reproducible
