### ISSUE TITLE
Public Recipe Pages

### ISSUE THREAD

**Issue by martinjuhasz** [TandoorRecipes/recipes#2561]
### Issue

Hey,

i'm wondering if i'm missing something. 
Is there a setting to show recipes to website visitors without login? 
i would love to be able to share just my recipes with people without an account.

### Tandoor Version

latest

### OS Version

unraid

### Setup

Docker / Docker-Compose

### Reverse Proxy

jwilder's nginx proxy

**Comment by vabene1111** [comment]
you can create a "share link" to a recipe and you can also send invite links with the group "guest" to friends but there is no "public" viewing of recipes currently implemented. As this would also require a pretty significant refactoring of the software this is currently not planned.
