### ISSUE TITLE
Add a cooking view

### ISSUE THREAD

**Issue by bloedboemmel** [TandoorRecipes/recipes#2564]
### Describe the solution you'd like

I don't know if you are familiar with the recipe-manager Whisk. They offer a step by step view for every recipe. I know this is quite a big change for existing recipes, but it would help a lot. 
![image](https://github.com/TandoorRecipes/recipes/assets/58067119/529cdba5-6918-49a7-b40b-679fce7439c3)

**Comment by vabene1111** [comment]
this request comes up every now and then and i agree, its rather useful and interesting. I have linked it to thje project working on the view, will take a look then.
