### ISSUE TITLE
Recipe view recipe image is too small

### ISSUE THREAD

**Issue by ignas2526** [TandoorRecipes/recipes#2565]
### Tandoor Version

1.5.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

When recipe contains few ingredients, recipe image will be as big as the recipe list. And sometimes that's just too small.

After some tinkering, I found that removing `{ 'max-height': ingredient_height }` resolves the issue. https://github.com/TandoorRecipes/recipes/blob/782dd4cb17fd213b33afeee657db8ce18b20c08e/vue/src/components/RecipeViewComponent.vue#L105C80-L105C80

I did some testing and I found that overall it looks much better without that line both on desktop and mobile phones. I think it should be the default behavior, unless I'm missing something. At very least, can there be an option to disable this line.

EDIT:
also adding this to ether image or line 100 adds a bit of spacing between the image and the ingredient list on small devices, making things look nicer:
` mb-sm-2 mb-md-0`

**Comment by vabene1111** [comment]
thanks for the feedback and solution ideas, will look at this when reworking the recipe view
