### ISSUE TITLE
as admin: cannot access /system when currently viewing a space of another user

### ISSUE THREAD

**Issue by llasse** [TandoorRecipes/recipes#2572]
### Tandoor Version

1.5.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

When logged in as admin and currently looking at a Space that belongs to another user I cannot access the /system panel (admin works fine..) as it states I do not have the right permissions.
Once I switch to my own Space I can access it allright.

**Comment by vabene1111** [comment]
fixed, system page will only require superuser status from now on
