### ISSUE TITLE
Android 'share to' Tandoor recipe import

### ISSUE THREAD

**Issue by rjwonder** [TandoorRecipes/recipes#2573]
### Is your feature request related to a problem? Please describe.

I usually browse recipes on my mobile and when I find a recipe which I would like to add to Tandoor I copy the url and paste in Tandoor url import. 

### Describe the solution you'd like

Instead of copy url, open Tandoor import and paste it, it would be very convenient if I could share the url to Tandoor using the android share function. It's what e.g. anylist is using

Probably a bit similar to the booklet function?

**Comment by vabene1111** [comment]
Thanks for the request, sadly I am pretty certain that this can't be done with PWA's, maybe the community app could implement such a feature.

Need to look into it and will inform the community app people.

**Comment by rjwonder** [comment]
Thanks, I wasn't aware of untare. Will try it to see if it has other features useful to me

**Comment by neferin12** [comment]
There seems to be a way to do this if the app is a pwa that meets chromes install criteria, which I think tandoor is, isn't it?

[https://developer.chrome.com/en/articles/web-share-target/](https://developer.chrome.com/en/articles/web-share-target/)

If you don't want to look into that yourself, I can try to implement it myself and create a pull request if I am successful, I've been planning on testing the share (target) API anyways.

**Comment by vabene1111** [comment]
That is super cool, I did not know this worked. Feel free to give it a try if you want to work with it anyway, if not I will at some point.

**Comment by rjwonder** [comment]
Thanks, tried it out for the first time today. Works perfectly when I got pwa working (https required!)
