### ISSUE TITLE
Custum Properties order

### ISSUE THREAD

**Issue by Miha-2** [TandoorRecipes/recipes#2578]
### Is your feature request related to a problem? Please describe.

Currently food properties are ordered based on creation order (or some other random way?). Reading the info in this order is kinda unclear and messy.

### Describe the solution you'd like

I would like a way to reorder property types without deleting and recreating them.
Maybe an up/down arrow in property type menu.

**Comment by Miha-2** [comment]
Never mind, I found you can customize this for each recipe.

**Comment by Miha-2** [comment]
I guess that order only works for manually set properties. It would bi nice to have custom order for auto calculated also.

**Comment by vabene1111** [comment]
yes, this is a open topic. I also want you to be able to group them. I noted that down in some other issue so closing this one but will be getting back to this at some point.
