### ISSUE TITLE
Incorrect per servings Properties calculation

### ISSUE THREAD

**Issue by Miha-2** [TandoorRecipes/recipes#2579]
### Tandoor Version

1.5.4

### Setup

Synology

### Reverse Proxy

No reverse proxy

### Bug description

![image](https://github.com/TandoorRecipes/recipes/assets/52750967/08ba3ee3-6f01-4062-a535-6887d0627fea)
When manually setting recipe properties, the amount you input is "per servings". I'm not native speaker but to me that is unclear if that means "per (one) serving" or "for all servings".

Either way in the bottom picture we can see the same "per servings" text presenting different data.
![image](https://github.com/TandoorRecipes/recipes/assets/52750967/0ed80300-35f0-428f-b3ad-e1d5da78b615)

And "total" text representing previous "per servings" data.
![image](https://github.com/TandoorRecipes/recipes/assets/52750967/cbec76ac-96b8-4f88-8a98-b642f7ab0615)

**Comment by vabene1111** [comment]
thanks, i think i changed that during develoment, might have mixed something up. The text means "per one serving",I am pretty sure that is the way its understood for native speakers but please someone correct me if "per serving" is ambigues and I can change it.

**Comment by smilerz** [comment]
> thanks, i think i changed that during develoment, might have mixed something up. The text means "per one serving",I am pretty sure that is the way its understood for native speakers but please someone correct me if "per serving" is ambigues and I can change it.

"per serving" unambiguously means per one serving

**Comment by Miha-2** [comment]
> "per serving" unambiguously means per one serving

I understood that, I just wasn't sure about "per servings" with that "s" at the end. My confusion came mostly from different functionalities under same text.

**Comment by vabene1111** [comment]
i think the "s" is a typo, also i agree that from the screenshots it looks like there is also a calculation error
