### ISSUE TITLE
Translation of Properties

### ISSUE THREAD

**Issue by Micha10** [TandoorRecipes/recipes#2582]
### Tandoor Version

1.5.4

### Setup

Synology

### Reverse Proxy

No reverse proxy

### Bug description

For tracking I'm using english versions of the browsers Chrome and LibreWolf.

I changed Tandoor to german language. Everything is german but the properties of the receipe are english;

```
Eigenschaften
pro Portion 
Fat	0,00	g	
Carbohydrates	0,00	g	
Proteins	0,00	g	
Calories	0,00	kcal	

```

This is while editing a new/current receipe and while viewing a saved one.

It should be

Fett
Kohlenhydrate
Eiweiß
Kalorien

Thank you for Tandoor!

**Comment by vabene1111** [comment]
you can change the properties names on the properties page. Future instances should have translated properties, just the first version did not container translations yet
