### ISSUE TITLE
Exporting all receipes: immediately expired

### ISSUE THREAD

**Issue by Micha10** [TandoorRecipes/recipes#2583]
### Tandoor Version

1.5.4

### Setup

Synology

### Reverse Proxy

No reverse proxy

### Bug description

Exporting one receipe is working.

If exporting all receipes, you see one short moment the link "download" (Herunterladen) and half a second later it shows

If download did not start automatically: ~~Herunterladen~~ (Expired)

The browser did not start the download!

I've tried Chrome and Librewolf and had that issue with both.

If I open the browsers developertool and put the focus i.e in the network-tab "name" column, it's working correctly, If the focus stays in the main windows, the error occurs.

Message in the console window:

```
TypeError: Cannot read properties of undefined (reading 'click')
    at o.startDownload (export_response_view.js:1:21538)
    at o.<anonymous> (export_response_view.js:1:21782)
    at Array.<anonymous> (chunk-vendors.js:1060:31079)
    at Cn (chunk-vendors.js:1060:30474)
```

**Comment by vabene1111** [comment]
there is an old issue regarding this topic. We were not able to reproduce this yet but it does not happen all the time so there wasn't enough pressure to work on a fix immediately. the whole system of importing and exporting needs some work done to improve efficiency and reliability.

**Comment by robot-rover** [comment]
I am also experiencing this bug, I'd be willing to help troubleshoot and/or reproduce things

**Comment by vabene1111** [comment]
feel free to test around, if you find a way to reproduce it I can likely fix it.
