### ISSUE TITLE
Food Edit Modal Bug

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#2584]
### Tandoor Version

db4f2db

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

1. Open Food Edit Modal
2. Close Modal (with or without save)
3. Open Move, Merge or Merge & Automate Modal
4. Nothing Happens
5. Food Edit Modal also no longer opens

**Comment by vabene1111** [comment]
i think i might not be resetting the "open" variable when closed without doing anything, thanks for the report

**Comment by vabene1111** [comment]
ok so merge and move were not working at all, fixed that

**Comment by TWART016** [comment]
Was this the bug that I cannot open food / edit? In version 1.56 and beta it is not possible.
