### ISSUE TITLE
Imported Recipes has no Recipe Image

### ISSUE THREAD

**Issue by scifijunk** [TandoorRecipes/recipes#2587]
### Tandoor Version

latest Image as of 8/21/2023 4:08 PM. The system page only displays Tandoor (HEAD ) and Debug which does not tell me the version of Tandoor I'm running but if I had to guess it would be 1.5.5

### Setup

Kubernetes

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

When importing a Recipe all seems fine until you save the Recipe. The Recipe Image is 404'ed. When right-clicking on the Recipe Image and clicking open image in new tab I am presented with the following.

![image](https://github.com/TandoorRecipes/recipes/assets/95538539/2db5c5b0-3b6d-44e9-a471-f1a5c7d984b6)

Otherwise, it works just fine as you can see below.

![image](https://github.com/TandoorRecipes/recipes/assets/95538539/8feb8b33-6f87-4abd-9f0a-dc256efef10e)

It seems to be looking in media and not mediafiles. I attempted to use the MEDIA_URL Environment variable but it did not work as I would still get the 404 error.

### Relevant logs

```shell
10.42.0.1 - - [21/Aug/2023:16:05:41 -0500] "GET /media/recipes/dbd1fbdb-0b17-40a2-b608-0f5bbd756b6b_1.jpg HTTP/1.1" 404 22165 "https://cookbook.chadwaltercummings.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
```

**Comment by smilerz** [comment]
are you sharing /media on the nginx proxy manager?

**Comment by scifijunk** [comment]
Do you mean as a custom location?

**Comment by smilerz** [comment]
As a webserver serving static content.

**Comment by scifijunk** [comment]
Well my setup is as follows

Router -> Nginx Proxy Manager (as a stand-alone server running the docker Image) -> 3 node k3s cluster

My Nginx Proxy Manager points to the node port of the Tandoor Image.

System page has the following

System Information
Tandoor (HEAD )
commit ba361a8a27657799bfc67540de24b211e4f86394
Author: Miha Perpar 
Date:   Fri Aug 11 13:05:51 2023 +0000

    Translated using Weblate (Slovenian)
    
    Currently translated at 59.0% (307 of 520 strings)
    
    Translation: Tandoor/Recipes Frontend
    Translate-URL: http://translate.tandoor.dev/projects/tandoor/recipes-frontend/sl/

Media Serving Ok
Everything is fine!
Secret Key Ok
Everything is fine!
Debug Mode Ok
Everything is fine!
Database Ok
Everything is fine!

Debug

Gunicorn Media: False
Sqlite: False
Debug: False

SERVER_PROTOCOL:HTTP/1.1
REMOTE_ADDR:10.42.0.1
SERVER_PORT:8080

HTTP_HOST:cookbook.chadwaltercummings.me
HTTP_X_FORWARDED_SCHEME:https
HTTP_X_FORWARDED_PROTO:https
HTTP_X_FORWARDED_FOR:My IP Address
HTTP_X_REAL_IP:My IP Address
HTTP_SEC_CH_UA:"Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
HTTP_DNT:1
HTTP_SEC_CH_UA_MOBILE:?0
HTTP_UPGRADE_INSECURE_REQUESTS:1
HTTP_USER_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
HTTP_SEC_CH_UA_PLATFORM:"Windows"
HTTP_SEC_FETCH_SITE:same-origin
HTTP_SEC_FETCH_MODE:navigate
HTTP_SEC_FETCH_DEST:empty
HTTP_REFERER:https://cookbook.chadwaltercummings.me/search/
HTTP_ACCEPT_ENCODING:gzip, deflate, br
HTTP_ACCEPT_LANGUAGE:en-US,en;q=0.9
HTTP_COOKIE:shopping_settings=%7B%22ui%22%3A%7B%22entry_mode_simple%22%3Atrue%7D%2C%22settings%22%3A%7B%22entrymode%22%3Atrue%7D%7D; mealplan_settings=%7B%22displayPeriodUom%22%3A%22month%22%2C%22displayPeriodCount%22%3A1%2C%22startingDayOfWeek%22%3A0%2C%22displayWeekNumbers%22%3Atrue%7D; csrftoken=jtVaIhWngQz0wbqS3g7UGzgOtFPlyyUU; sessionid=mxggeln9fwxrq0ub7kwgqjtjgf9z586q

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7feedcf36320>
wsgi.version:(1, 0)
wsgi.multithread:True
wsgi.multiprocess:True
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x7feedcf34a00>
wsgi.url_scheme:http

**Comment by smilerz** [comment]
It appears you don’t have gunicorn serbm g the media. What web server is hosting the image files?

**Comment by scifijunk** [comment]
The image files are in the mediafiles in the Tandoor image. Turning on Gunicorn Media yields the same results.

**Comment by smilerz** [comment]
The media files need to be served by a webserver - the [recommended method](https://docs.tandoor.dev/install/docker/#nginx-vs-gunicorn) is to disable gunicorn for this purpose and host using nginx or other webserver.

If enabling gunicorn serving media still has an issue - please review the issues referenced [here](https://docs.tandoor.dev/faq/#why-are-images-not-loading).

**Comment by scifijunk** [comment]
Well I took a look at https://docs.gunicorn.org/en/stable/design.html#how-many-workers to give me better understanding of how GUNICORN_WORKERS and GUNICORN_THREADS work. I think having just the said link in the .env.template leaves a lot to be desired. With that being said it does now display the Recipe Image.

Thank you
