### ISSUE TITLE
Unable to import 499 recipes 

### ISSUE THREAD

**Issue by pippo73** [TandoorRecipes/recipes#2594]
### Tandoor Version

vabene1111/recipes:latest

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

I am trying to import 499 recipes from recipekeeper pro. I've imported the zip file but only 120 are imported :-(

**Comment by vabene1111** [comment]
given no sample data and not logs i cannot help you or fix this. Please provide additional information (for example the one shown in the UI), container logs and best a sample file containing recipes that cannot be imported so i can take a look

**Comment by pippo73** [comment]
> given no sample data and not logs i cannot help you or fix this. Please provide additional information (for example the one shown in the UI), container logs and best a sample file containing recipes that cannot be imported so i can take a look

Hello, If you will give me mail, I will be glad to share with you the zip file and if you tell me wich logs you need I will be glad to provide them.

BTW, the weight, of the product seems not added correctly, but this is an other discussion we can check later ;-)

**Comment by vabene1111** [comment]
you can send sample data to info@tandoor.dev

For logs the first thing would be the logs shown on the importer page, then the ones of the docker container but if I have the sample data thats sufficent if I can reproduce the issue.

**Comment by pippo73** [comment]
> you can send sample data to [info@tandoor.dev](mailto:info@tandoor.dev)
> 
> For logs the first thing would be the logs shown on the importer page, then the ones of the docker container but if I have the sample data thats sufficent if I can reproduce the issue.

I've sent you the file by mail as requested. If you need I can send you also the logs.

**Comment by vabene1111** [comment]
thanks, i will look into it when i find the time.

**Comment by vabene1111** [comment]
ok just ran your import, seems like the issue was resolved in the meantime, sorry for the late reply

**Comment by pippo73** [comment]
> ok just ran your import, seems like the issue was resolved in the meantime, sorry for the late reply

No problem. Tnx
