### ISSUE TITLE
Separate ingredient list from steps

### ISSUE THREAD

**Issue by tehniemer** [TandoorRecipes/recipes#2607]
### Is your feature request related to a problem? Please describe.

Heavily related to #2266 and dissatisfaction with the solution provided by #2539 

I'm really struggling with having to enter ingredients at the step level and the solution to hide it from the step is a bandaid in my opinion. The implementation leaves undesirable results such as: 

- It takes many steps to editing ingredients after they are hidden, you have to save, exit, and return to the edit screen after unhiding them before they will show up again.
- It is not obvious how to get them to show up after they are hidden for users that are not intimately familiar with the feature.
- There is no way to hide step ingredients en masse if recipes were imported in an un-hidden state.

### Describe the solution you'd like

Create a separate field where ingredients and quantities can be entered that is not at the step level. Ingredients can still be linked to a step from the "master" list.

An additional feature could be allowing adding of ingredients at the step level and populate and sum their quantities to the "master" list.

**Comment by smilerz** [comment]
Refactoring the entire application is not going to considered.
