### ISSUE TITLE
Links in media serving warning broken.

### ISSUE THREAD

**Issue by tehniemer** [TandoorRecipes/recipes#2610]
### Documentation link

https://github.com/TandoorRecipes/recipes/releases/tag/0.8.1

### Affected section

System

### Issue description

The link in the media serving warning in the image below points to the documentation link referenced in this issue which has broken links for `traefik-nginx` and `nginx-proxy` docker configurations. The links should be https://github.com/TandoorRecipes/recipes/blob/master/docs/install/docker/traefik-nginx/docker-compose.yml and https://github.com/TandoorRecipes/recipes/blob/master/docs/install/docker/nginx-proxy/docker-compose.yml respectively

![image](https://github.com/TandoorRecipes/recipes/assets/11021632/f37c010b-4f23-4ea1-b5f7-ce4af019c165)

**Comment by alienishi** [comment]
please assign this issue to me

**Comment by vabene1111** [comment]
thanks, fixed
