### ISSUE TITLE
Is there plans to design the app in such a way that plays nicely with CSP? 

### ISSUE THREAD

**Issue by wrjlewis** [TandoorRecipes/recipes#2616]
### Is your feature request related to a problem? Please describe.

Hi

I have a content security policy on my webserver, that disallows inline script and styles, as recommended. Tandoor has an incredible amount of both which makes it unrealistic to add the corresponding hashes so that they are classed as exceptions.

As far as I can see, one must use 'unsafe-inline' on both script-src-elem and style-src-elem, to allow Tandoor to function correctly. This is a very unrecommended setup, as opens the door for all sorts of XSS, etc. 

Am I doing something wrong, or will there be plans to change the app design to have scripts and css in their own separate files, in future? 

### Describe the solution you'd like

Will there be plans to change the app design to have scripts and css in their own separate files, in future?

**Comment by vabene1111** [comment]
tandoor uses vue for its frontend, these files are loaded as seperate external files

Other than that there are a few smaller utility script here and there that are inline directly. While we are slowly migrating a way from old views with smaller scripts inside them I dont see it as realistic to avoid them completely.
