### ISSUE TITLE
Server Error (500) -  WARNING:django.request:Method Not Allowed: /api/recipe/9/image/ 

### ISSUE THREAD

**Issue by wrjlewis** [TandoorRecipes/recipes#2618]
### Tandoor Version

sudo python3 version.py:  getting tandoor version fatal: no tag exactly matches 'd42d784aeb0595bbc0ed47eb8bbc27ba61b0787d' writing version info [{'name': 'Tandoor ', 'version': "commit d42d784aeb0595bbc0ed47eb8bbc27ba61b0787d\nMerge: 28f18fbc ce84b3b3\nAuthor: vabene1111 \nDate:   Tue Aug 29 13:09:38 2023 +0200\n\n    Merge branch 'develop'\n", 'website': 'https://github.com/TandoorRecipes/recipes', 'commit_link': 'https://github.com/TandoorRecipes/recipes/commit/d42d784aeb0595bbc0ed47eb8bbc27ba61b0787d', 'ref': 'd42d784aeb0595bbc0ed47eb8bbc27ba61b0787d', 'branch': 'master\n', 'tag': ''}]

### Setup

Manual Setup

### Reverse Proxy

Apache2

### Bug description

Trying to upload image when importing a recipe results in server error 500

Checking out the error logs in the app I get the following:

```
WARNING:django.request:Method Not Allowed: /api/recipe/9/image/
ERROR:django.request:Internal Server Error: /api/recipe/9/image/
Traceback (most recent call last):
  File "/var/www/recipes/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/var/www/recipes/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/recipes/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/recipes/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/recipes/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/recipes/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/recipes/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/recipes/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/recipes/cookbook/views/api.py", line 959, in image
    filetype = mimetypes.guess_extension(serializer.validated_data['image'].content_type) or filetype
AttributeError: 'NoneType' object has no attribute 'content_type'
```

**Comment by wrjlewis** [comment]
Sure, thanks.

it’s this recipe I was trying:
https://www.bbcgoodfood.com/recipes/creamy-pesto-chicken-roasted-tomatoes

**Comment by smilerz** [comment]
I'm using the latest commit from develop and it works fine.  Make sure you've updated all dependencies and rebuilt the vue frontend (yarn install & yarn build)

**Comment by wrjlewis** [comment]
Thanks, I’ve done that. That’s part of the install steps, this is the first time I’ve used tandoor so this isn’t just a recent thing for me.
Something about the method not being allowed through django seems like a bit of  smoking gun

**Comment by wrjlewis** [comment]
Or perhaps something to do with my reverse proxy not putting the right headers through, that seems to be something that trips people up a lot

**Comment by smilerz** [comment]
if you go to /system you will see all the headers that django detects.  if you share that list here I might be able to point you in a direction.

**Comment by wrjlewis** [comment]
`Gunicorn Media: False
Sqlite: False
Debug: False

SERVER_PROTOCOL:HTTP/1.1
REMOTE_ADDR:
SERVER_PORT:443

HTTP_HOST:(removed)
HTTP_ACCEPT_ENCODING:gzip
HTTP_X_FORWARDED_FOR:(removed)
HTTP_CF_RAY:8029696e0bc124da-LHR
HTTP_X_FORWARDED_PROTO:https,https
HTTP_CF_VISITOR:{"scheme":"https"}
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_SEC_FETCH_SITE:same-origin
HTTP_PRIORITY:u=3, i
HTTP_SEC_FETCH_MODE:navigate
HTTP_ACCEPT_LANGUAGE:en-GB,en;q=0.9
HTTP_USER_AGENT:Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1
HTTP_REFERER:(removed
HTTP_SEC_FETCH_DEST:document
HTTP_COOKIE:csrftoken=(removed); sessionid=(removed)
HTTP_CDN_LOOP:cloudflare
HTTP_CF_CONNECTING_IP:(removed)
HTTP_CF_IPCOUNTRY:GB
HTTP_X_FORWARDED_HOST:(removed), (removed)
HTTP_X_FORWARDED_SERVER:(removed)
HTTP_CONNECTION:Keep-Alive

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f98c3323be0>
wsgi.version:(1, 0)
wsgi.multithread:False
wsgi.multiprocess:False
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x7f98c3322ad0>
wsgi.url_scheme:https

     `

**Comment by smilerz** [comment]
I assume the FOWARDED_FOR and FORWARDED_HOST are accurate

I think this is the problem:

`HTTP_X_FORWARDED_PROTO:https,https` .

I saw this somewhere else where the protocol was added twice and created issues.  I don't know apache so am not certain how to help from there.

Your allowed protocols is also more restrictive than I have, with image types noticeably missing:

`HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
`

**Comment by wrjlewis** [comment]
👏  You are quite right! The additional 'https' was causing the issue here. The root cause being that I had the header configured as 'add' rather than 'set' in my apache2 configuration, or I could remove that line completely since it's being set elsewhere. 

This led me to my next error, where the image was clearly uploaded and can be seen in the right directory on the server but django gives a 404.

`WARNING:django.request:Not Found: /static/assets/test.txt`

^ I tested putting a test.txt file in the same place with the same permissions as other assets which load currently, yet still I get 404 and the above error when trying to load the test file. Any hints on what it could be?

**Comment by wrjlewis** [comment]
> Content in `/static/` is served by middleware by default and won't serve anything that it doesn't expect to be there.
> 
> Media files need to be served by a webserver - the default configuration uses nginx or gunicorn (not recommended). Without knowing more about your specific setup its hard to be specific. But in short the tandoor media directory (`/opt/recipes/mediafiles` in docker) needs to be exposed to your apache server and mounted at `/media/`

Thank you, hit the nail on the head. 

I hadn't added config to exclude the two paths from the proxypass, for those wondering this is my working config relating to tandoor, for apache2:

```
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader add X-Forwarded-Host %{REMOTE_HOST}s
        ProxyPreserveHost  On

        ProxyPass /static/ !
        ProxyPass /media/ !

        Alias /static/ /var/www/recipes/staticfiles/
        Alias /media/ /var/www/recipes/mediafiles/

        ProxyPass / unix:/var/www/recipes/recipes.sock|http://127.0.0.1/
```
