### ISSUE TITLE
Autoselect available unit or food when typing

### ISSUE THREAD

**Issue by rinosaur681** [TandoorRecipes/recipes#2626]
### Tandoor Version

1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When typing in a unit or food as an ingredient in a recipe, most of the time it doesn't auto-highlight the item already used in the past. 

For example when putting in Tablespoon, once I type "table" it would be good to just be able to press Enter and it choose Tablespoon. However every time it creates a new unit called Table instead. This is because the create has higher priority than items already in the database I guess.

![Untitled](https://github.com/TandoorRecipes/recipes/assets/93617243/8ddaf4be-a29b-4bb1-ae93-b3cbdd8f419d)

**Comment by smilerz** [comment]
That's a third party component and doesn't support that behavior.
