### ISSUE TITLE
Chinese language UI request & how to make a contribution to Chinese translation?

### ISSUE THREAD

**Issue by toyqiu** [TandoorRecipes/recipes#2627]
### Describe the solution you'd like

Chinese is my native language. I can understand English, but I want the process of preparing my dishes to have less pressure.

**Comment by vabene1111** [comment]
hi, feel free to head on over to translate.tandoor.dev and contribute to the chinese translation data. 

See https://docs.tandoor.dev/contribute/#contribute-translations

Once you feel like a good amount of translations is in just post an issue with the langauge code you finalized and I will make sure that it is included in the language switcher in tandoor.
