### ISSUE TITLE
db upgrade error

### ISSUE THREAD

**Issue by update-freak** [TandoorRecipes/recipes#2635]
### Is your feature request related to a problem? Please describe.

It would be great if tandoor could support the current version of postgres v16, then I did not have to store multiple images of different postgres versions for my different docker containers.

### Describe the solution you'd like

Support of the latest postgres version

**Comment by smilerz** [comment]
Have you tried it and it doesn't work?

**Comment by update-freak** [comment]
yes I tried with postgres:latest. I think this is currently the v16.
In the docs the docker compose is described with postgres:15-alpine.
Or should I use postgres:16-alpine?

**Comment by smilerz** [comment]
Not sure that matters.  What errors are you getting?

**Comment by update-freak** [comment]
With postgres:16-alpine I got this error:

![Bild1](https://github.com/TandoorRecipes/recipes/assets/40196995/e3e4b29e-f589-450d-ac01-44c386b857f8)

**Comment by smilerz** [comment]
Please provide logging details of the container(s) that failed to be created.

**Comment by update-freak** [comment]
I'm not sure if this is the correct log.
I copied this one from Portainer -> Notifications:

`failed to deploy a stack: Network tandoor_default Creating Network tandoor_default Created Container Tandoor-DB Creating Container Tandoor-DB Created Container Tandoor Creating Container Tandoor Created Container Tandoor-NGINX Creating Container Tandoor-NGINX Created Container Tandoor-DB Starting Container Tandoor-DB Started Container Tandoor-DB Waiting Container Tandoor-DB Healthy Container Tandoor Starting Container Tandoor Started Container Tandoor Waiting Container Tandoor Error dependency failed to start: container Tandoor is unhealthy`

Please let me know when this is not the correct log file. Thanks

**Comment by smilerz** [comment]
This isn't a tandoor issue.  The containers were all created fine, you received an error creating the network.  
If I had to guess you are probably reusing a port.

**Comment by smilerz** [comment]
Can you please share the container logs from Tandoor and the db.

**Comment by update-freak** [comment]
it fails to create the container for tandoor and the db, so no possibility to share the log, right?
here is the docker compose. Maybe you will find a mistake there.

`version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: Tandoor-DB
    hostname: tandoor-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "recipes", "-U", "recipesuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    user: 1026:100
    volumes:
      - /volume1/docker/tandoor/db:/var/lib/postgresql/data
    env_file:
      - stack.env
    restart: always

  tandoor:
    image: vabene1111/recipes:latest
    container_name: Tandoor
    hostname: tandoor
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
    user: 1026:100
    volumes:
      - /volume1/docker/tandoor/staticfiles:/opt/recipes/staticfiles
      - /volume1/docker/tandoor/mediafiles:/opt/recipes/mediafiles
      - /volume1/docker/tandoor/nginx:/opt/recipes/nginx/conf.d
    env_file:
      - stack.env
    restart: always
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:mainline-alpine
    container_name: Tandoor-NGINX
    hostname: nginx-tandoor
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1
    volumes:
      - /volume1/docker/tandoor/staticfiles:/static:ro
      - /volume1/docker/tandoor/mediafiles:/media:ro
      - /volume1/docker/tandoor/nginx:/etc/nginx/conf.d:ro
    ports:
      - 9815:80
    env_file:
      - stack.env
    restart: always
    depends_on:
      tandoor:
        condition: service_healthy`

**Comment by smilerz** [comment]
The logs you shared state that all containers were created and started.  Without some details about what went wrong I'm not sure how to help you.

**Comment by update-freak** [comment]
I shut down the NAS, wait one night and did a reboot.
Now the creating process of the docker container in portainer was successful.
I can not explain the behaviour, but now it works.
So I will close this ticket.
