### ISSUE TITLE
Import from RecipeSage JSON-File not working

### ISSUE THREAD

**Issue by eskahone** [TandoorRecipes/recipes#2637]
### Tandoor Version

1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When using the import function for the app RecipeSage an error occurs and nothing is imported except the title of the recipe. 
![Screenshot 2023-09-20 174328](https://github.com/TandoorRecipes/recipes/assets/74679226/83b09643-17a6-4479-b1bd-bc74082c689c)
![Screenshot 2023-09-20 175212](https://github.com/TandoorRecipes/recipes/assets/74679226/56950cec-856f-4266-ba1b-e2f0f10eb9a0)

The export in RecipeSage is performed as described in the Tandoor documentation. This is the json-file that was created during the RecipeSage export:
`[{"@context":"http://schema.org","@type":"Recipe","datePublished":"2023-09-18T15:01:39.011Z","description":"","image":["https://chefbook-prod.s3.us-west-2.amazonaws.com/1695049278767-e686241419fc0c"],"name":"Wild Bourguignon","prepTime":"","recipeIngredient":["1 Handvoll getrocknete Pilze, Steinpilze oder Herbsttrompeten","1 Fl guter Rotwein","150 g Speck, fein gewürfelt","1 rote Zwiebel","4 El Butterschmalz, oder Öl, je nach Gescmack","1 El Zucker","2 Knoblauchzehen, fein gehackt","1 Zweig Rosmarin","3 Stängel Petersilie","1 Lorbeerblatt","4 Zweige Thymian","8 kleine Möhren","250 g kleine Schalotten","300 g gemischte Pilze, bevorzugt Steinpilze und Champignons","500 ml Wildfond"],"recipeInstructions":[{"@type":"HowToStep","text":"Getrocknete Pilze in heißem Wasser einweichen."},{"@type":"HowToStep","text":"Speck im Bräter kross ausbraten, beiseite legen."},{"@type":"HowToStep","text":"Zwiebel im ausgebratenen Fett goldbraun rösten und ebenfalls beiseite stellen."},{"@type":"HowToStep","text":"Aus den Kräutern einen Strauß binden oder in ein Kräutersäckchen geben."},{"@type":"HowToStep","text":"Ganz leicht gesalzene Fleischstücke im Bräter in mehreren Schüben braun anbraten und beiseite legen."},{"@type":"HowToStep","text":"Backofen auf 160°C Umluft vorheizen."},{"@type":"HowToStep","text":"Das ganze Fleisch mit fein gehacktem Knoblauch in den Bräter legen, mit Mehl bestäuben und dabei umrühren."},{"@type":"HowToStep","text":"Rotwein, bzw. Marinierflüssigkeit und Fond angießen und aufkochen lassen."},{"@type":"HowToStep","text":"Getrocknete Pilze abgießen, die Flüssigkeit dabei gefiltert (Sieb, Küchenkrepp) auffangen."},{"@type":"HowToStep","text":"Kräuter und eingeweichte Pilze nebst aufgefangener Flüssigkeit in den Bräter geben und alles mit Deckel insgesamt 3,5 Stunden schmoren lassen (wer verspricht daran zu denken, gibt die Kräuter erst 1/2 Stunde vor Ende der Garzeit hinzu)."},{"@type":"HowToStep","text":"In der Zwischenzeit, die  Möhren in etwas Butterschmalz 15 Minuten  karamellisieren."},{"@type":"HowToStep","text":"Schalotten hinzugeben und alles weitere 15 Minuten sanft karamellisieren, anschließend beiseite legen."},{"@type":"HowToStep","text":"Pilze nach Größe halbieren oder vierteln und in Butterschmalz kräftig goldbraun anschmoren, dann bissfest weiter schmoren und beiseite legen."},{"@type":"HowToStep","text":"In der Zwischenzeit auch mal nachschauen, ob noch genug Flüssigkeit im Topf ist, gegebenenfalls etwas heißes Wasser nachgießen."},{"@type":"HowToStep","text":"Das fertige Fleisch aus dem Ofen nehmen, Pilze, Zwiebeln, Speck und Möhren hinzugeben, Kräuter entfernen und sanft auf dem Herd köcheln lassen."},{"@type":"HowToStep","text":"Pfeffern und abschmecken, nach Bedarf salzen."},{"@type":"HowToStep","text":"Dazu essen Franzosen gern Kartoffelpü oder Baguette – wir in jedem Fall lieber Pasta."}],"recipeYield":"","totalTime":"","recipeCategory":[],"creditText":"Das entspannte Menü","isBasedOn":"https://www.s-kueche.com/2018/12/wild-bourguignon/","comment":[{"@type":"Comment","name":"Author Notes","text":""}]}]`

**Comment by vabene1111** [comment]
Thanks for letting me know. Maybe something changed and I need to update the importer
