### ISSUE TITLE
No way to create a new user

### ISSUE THREAD

**Issue by larieu** [TandoorRecipes/recipes#2640]
### Tandoor Version

last

### Setup

Synology

### Reverse Proxy

No reverse proxy

### Bug description

Installed as per 
https://docs.tandoor.dev/install/synology/

At first boot asked to create a superuser ( all ok )

I am able to log in with the superuser ( no prb)
If I go  
Top Right corner > superuser acc > Admin > (Site administration) > [Authentication and Authorization] > Users 

No "Add user" button available

**Comment by smilerz** [comment]
Add users from the Space Settings in the top right menu.
