### ISSUE TITLE
Draft recipes for meal plan

### ISSUE THREAD

**Issue by wolflu05** [TandoorRecipes/recipes#2641]
### Is your feature request related to a problem? Please describe.

I want to use the meal plan feature, but I have not all of my recipes entered in tandoor. Adding them just with a title is kind of bad, because then they show up in the recipes discovery too.

### Describe the solution you'd like

Recipes can be marked as a draft so they do not show for recipes discovery or search, only in the recipes select fields. If adding a recipe to a meal which does not exist, create it and mark it as draft. Then you can either go through all of your drafts and add some description to it sometime or select it again the next time you cook it.

### Describe alternatives you've considered

Add it as a normal recipe.

**Comment by smilerz** [comment]
You can create a meal plan with a title only and without a linked recipe.

**Comment by wolflu05** [comment]
Oh sorry, should have checked this before on tandoor web. I tried it with Untare, and it was not that obvious that this is possible. This works too, thank you for your quick reply.
