### ISSUE TITLE
Issue when creating new property types

### ISSUE THREAD

**Issue by UmerAR** [TandoorRecipes/recipes#2644]
### Tandoor Version

1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Whenever I try to create a new property type it gives me an error saying "There was an error creating resource"

**Comment by vabene1111** [comment]
Note from disxord: order field missing, show that it is required

**Comment by UmerAR** [comment]
Yep fixed it, Thanks for letting me know, didnt know it was required!
