### ISSUE TITLE
Format the computed per serving nutrition numbers

### ISSUE THREAD

**Issue by dsm1212** [TandoorRecipes/recipes#2662]
### Tandoor Version

commit d42d784aeb0595bbc0ed47eb8bbc27ba61b0787d Author: vabene1111  Date:   Tue Aug 29 13:09:38 2023 +0200      Merge branch 'develop'

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

Really minor request: The nutrition per serving values are displaying with 16 decimal accuracy. Can you format these to just a couple decimal places? Thx

**Comment by vabene1111** [comment]
yes that should definitely be run trough the formatter.

**Comment by dsm1212** [comment]
Oddly I still get long numbers most of the time. See below. Is this what you fixed?

![image](https://github.com/TandoorRecipes/recipes/assets/7332569/60fa2904-b458-4694-bdab-b4901e1fa988)

**Comment by dsm1212** [comment]
Maybe latest doesn't have the fix yet. I've got:

Tandoor (HEAD )
commit d42d784aeb0595bbc0ed47eb8bbc27ba61b0787d
Author: vabene1111 
Date:   Tue Aug 29 13:09:38 2023 +0200

    Merge branch 'develop'

**Comment by dsm1212** [comment]
Doh, I see this is the same commit I posted against originally. I guess I should try develop?

**Comment by smilerz** [comment]
> Doh, I see this is the same commit I posted against originally. I guess I should try develop?

It appears that you are on the develop branch - just not a current commit.

**Comment by dsm1212** [comment]
I checked I'm using latest and the last commit was that aug 29 merge from develop. Is develop safe to switch to?

**Comment by smilerz** [comment]
Beta is safer and you can switch to main branch once it's released.

**Comment by dsm1212** [comment]
> Beta is safer and you can switch to main branch once it's released.

I managed to get to beta after upgrading postgres from 11 to 15. And this fix is present.

The postgres import/export commands in the doc don't mention that the password needs to be reset via sql for djangouser after import. This is a well known issue with postgres so I was able to find the answer pretty quickly.

Thanks!
