### ISSUE TITLE
Space Settings should be visible to admin assigned user in space

### ISSUE THREAD

**Issue by AliveDevil** [TandoorRecipes/recipes#2663]
### Is your feature request related to a problem? Please describe.

If a space is owned by user A, and user B is assigned to that space as admin, following features are missing or not working:
- Link to manage a space
- If manually navigating to "/space-manage/id" user B,
  - can only see themselves in space-manage
  - cannot edit any information for that space

### Describe the solution you'd like

If a user is assigned admin-permissions for a space I'd expect that user to be able to manage that space just like the owner can (for me there is no difference in owner/admin-permissions).
In fact: Space-Owners are just a tag on that space.
E.g. Creating a space from disabled super user admin account "system", then assigning user A and user B as admins (none of those two users is the owner of that space), none can edit any information of that space, although permission level should suffice to change space image, message, invite/kick users and change permission level.

### Additional context

Steps to reproduce:

- Create "admin"-super user
- Create A superuser
- Create B user
- Create space "Name" from admin super user
- Assign admin permissions to A and B
- Login as A in Django-Admin and disable admin user (dummy user, to move the owner field to someone else than A or B)
- Try to change any space settings from frontend (Django-Admin works fine)

**Comment by vabene1111** [comment]
thanks for the well written ticket and idea.

the difference between admin and owner is on purpose for now, I plan on adding a more in depth permission system in the future but for now it is this way.

**Comment by AliveDevil** [comment]
> thanks for the well written ticket and idea.

I hate it when users create garbage tickets on others projects (when I'm searching for issues/resolutions I'm encountering) or those I work on (famous "Doesn't work for me" - "What doesn't work?" - no response).

Trying to get as much out of my head to convey my ideas/issues, that there is no missing information that has to be requested afterwards.

> in the future
Lookig forward, for now going through the Django-Admin works as a workaround.
