### ISSUE TITLE
Hide properties

### ISSUE THREAD

**Issue by Blue20210921** [TandoorRecipes/recipes#2688]
### Is your feature request related to a problem? Please describe.

I do not use the properties.
I am not interested in Fat, Carbohydrates, Proteins & Calories.
So it would be nice to have the option to hide this view.

### Describe the solution you'd like

A checkbox in the cosmetic settings to hide this part.

### Additional context

![IMG_20231021_104716](https://github.com/TandoorRecipes/recipes/assets/91151271/44be9a9c-efe5-4481-ab2f-93e9f84c624c)

**Comment by VaibhavSharma24** [comment]
I think we can add a toggle button and hide all this data in it so that whosoever want to see the information can see and who doesn't want will not it will also make the page more clear and will enhance the overall user experience

**Comment by Blue20210921** [comment]
That would be perfect 🙂
Thanks

**Comment by smilerz** [comment]
> I think we can add a toggle button and hide all this data in it so that whosoever want to see the information can see and who doesn't want will not it will also make the page more clear and will enhance the overall user experience

That's fine - but the setting needs to persist in settings.

**Comment by VaibhavSharma24** [comment]
Sure sure we will keep this in mind


> > I think we can add a toggle button and hide all this data in it so that whosoever want to see the information can see and who doesn't want will not it will also make the page more clear and will enhance the overall user experience
> 
> That's fine - but the setting needs to persist in settings.

**Comment by VaibhavSharma24** [comment]
> That would be perfect 🙂 Thanks

@Blue20210921 Are you working on this ? I would be more than happy if I could contribute anything to it.

**Comment by Blue20210921** [comment]
> > That would be perfect 🙂 Thanks
> 
> @Blue20210921 Are you working on this ? I would be more than happy if I could contribute anything to it.

Me? No, sorry I don't know anything about programming. I thought you would do that. Sorry my English is not very good 😅

**Comment by VaibhavSharma24** [comment]
> > > That would be perfect 🙂 Thanks
> > 
> > 
> > @Blue20210921 Are you working on this ? I would be more than happy if I could contribute anything to it.
> 
> Me? No, sorry I don't know anything about programming. I thought you would do that. Sorry my English is not very good 😅

Oh No problem I am happy to work on this if @smilerz approves the idea ?

**Comment by smilerz** [comment]
Submit a PR and if it is good enough it'll be merged.

**Comment by vabene1111** [comment]
or just delete the 4 types if you dont use them, then they will not show

**Comment by smilerz** [comment]
> or just delete the 4 types if you dont use them, then they will not show

I deleted all 4 property types from my instance and they still show.
![image](https://github.com/TandoorRecipes/recipes/assets/1808639/d7ff983f-067e-479a-9638-b45c704476c1)

**Comment by smilerz** [comment]
Your latest change fixed it.
