### ISSUE TITLE
No Import possible from greenforce.com

### ISSUE THREAD

**Issue by borisholowka** [TandoorRecipes/recipes#2696]
### Tandoor Version

1.5.6

### Import URL

https://www.greenforce.com/blogs/vegane-rezepte/grusel-burger

### When did the issue happen?

Always when i try to import from greenforce.com

### Response / message shown

```shell
Failure

There was an error fetching a resource!
```

**Comment by smilerz** [comment]
The importer is a library maintained upstream.  However, that site doesn't use structured data so there isn't anything they can do to enable importing from that site.

**Comment by borisholowka** [comment]
ok, then I guess I have to switch back to apps like Recipies Keeper to make this work, which I didn't really want to do.

**Comment by blowk** [comment]
Like smilerz mentioned there is no structured data on the website.
However, you still can manually import/create the data to make the recipe or write a script to scrape to data from greenforce.com if you want.

**Comment by vabene1111** [comment]
feel free to add support for it using this library https://github.com/hhursev/recipe-scrapers
