### ISSUE TITLE
Shopping list copy to cliboard not working

### ISSUE THREAD

**Issue by k-jell** [TandoorRecipes/recipes#2697]
### Tandoor Version

1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

I am using the `latest` docker image and copying a shopping list to the clipboard doesn't work at all. The "Copy to Clipboard" option as well as the "Copy as Markdown Table" option don't do anything. I click the menu option but nothing happens. There is nothing in the logs, but the clipboard stays empty. Tried it on an Arch-Linux machine (using i3) with Firefox and Chromium and also on a Windows machine, but no success.

**Comment by smilerz** [comment]
We can't guarantee everything works well on Firefox, but I tried it successfully on both Edge and Chrome.  
Is there anything in the browser console?  Double check your security settings as well to ensure the browser has access to your clipboard.

**Comment by k-jell** [comment]
Just tested it in Chromium again (should work just as it works in Chrome right?) and I indeed get errors in the browser console:
```
chunk-vendors.f97ae76c89ae.js:1060 TypeError: Cannot read properties of undefined (reading 'writeText')
    at o.clipboard (shopping_list_view.a1bf212c9cef.js:1:49518)
    at yn (chunk-vendors.f97ae76c89ae.js:1060:29985)
    at HTMLAnchorElement.r (chunk-vendors.f97ae76c89ae.js:1060:11763)
    at a._wrapper (chunk-vendors.f97ae76c89ae.js:1060:68081)
wn @ chunk-vendors.f97ae76c89ae.js:1060
vn @ chunk-vendors.f97ae76c89ae.js:1060
Fn @ chunk-vendors.f97ae76c89ae.js:1060
yn @ chunk-vendors.f97ae76c89ae.js:1060
r @ chunk-vendors.f97ae76c89ae.js:1060
a._wrapper @ chunk-vendors.f97ae76c89ae.js:1060
```
Also the top of the shopping list looks like this:
![image](https://github.com/TandoorRecipes/recipes/assets/42188452/57aef77d-3bac-46f4-be77-c2d171615c8e)

Same error in Firefox btw.

**Comment by smilerz** [comment]
I just installed a fresh version of tandoor from the master branch (1.5.6) and chromium and confirmed that it works.

Try deleting the entire local cache and confirm that the browser doesn't limit access to the clipboard in some way.

**Comment by k-jell** [comment]
Ok, I think I have figured it out. I am running tandoor on my home server in the local network without HTTPS. Apparently the clipboard api needs a secure context to work: 

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

So either localhost or HTTPS can be secure contexts and the clipboard should work there.

**Comment by smilerz** [comment]
Good to know. Thanks.
