### ISSUE TITLE
Recipe export error "There was an error loading a resource!" in develop

### ISSUE THREAD

**Issue by BstAA** [TandoorRecipes/recipes#2698]
### Tandoor Version

vabene1111/recipes:develop

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Lost recipe export functionality in "develop" branch.
Message "There was an error loading a resource!"

Full functional in "latest"

**Comment by smilerz** [comment]
please share logs after enabling debug

**Comment by BstAA** [comment]
Hope this is the right information

`
tandor-web_recipes-1    | Internal Server Error: /export/
tandor-web_recipes-1    | Traceback (most recent call last):
tandor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
tandor-web_recipes-1    |     response = get_response(request)
tandor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
tandor-web_recipes-1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tandor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
tandor-web_recipes-1    |     return view_func(request, *args, **kwargs)
tandor-web_recipes-1    |   File "/opt/recipes/cookbook/views/import_export.py", line 125, in export_recipe
tandor-web_recipes-1    |     return render(request, 'export.html', {'pk': pk})
tandor-web_recipes-1    | UnboundLocalError: local variable 'pk' referenced before assignment
tandor-web_recipes-1    | Internal Server Error: /export/
tandor-web_recipes-1    | Traceback (most recent call last):
tandor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
tandor-web_recipes-1    |     response = get_response(request)
tandor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
tandor-web_recipes-1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tandor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
tandor-web_recipes-1    |     return view_func(request, *args, **kwargs)
tandor-web_recipes-1    |   File "/opt/recipes/cookbook/views/import_export.py", line 125, in export_recipe
tandor-web_recipes-1    |     return render(request, 'export.html', {'pk': pk})
tandor-web_recipes-1    | UnboundLocalError: local variable 'pk' referenced before assignment
tandor-web_recipes-1    | 192.168.208.4 - - [27/Oct/2023:16:17:55 +0200] "POST /export/ HTTP/1.0" 500 70678 "https://rezepte-.de/export/?r=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
tandor-nginx_recipes-1  | 172.18.0.3 - - [27/Oct/2023:14:17:55 +0000] "POST /export/ HTTP/1.1" 500 70678 "https://rezepte-.de/export/?r=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69" "109.250.18.140"
tandor-nginx_recipes-1  | 172.18.0.3 - - [27/Oct/2023:14:17:55 +0000] "GET /static/webfonts/poppins_latin_700.woff2 HTTP/1.1" 304 0 "https://rezepte-.de/static/themes/tandoor.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69" "109.250.18.140"
tandor-web_recipes-1    | 192.168.208.4 - - [27/Oct/2023:16:17:55 +0200] "GET /static/webfonts/poppins_latin_700.woff2 HTTP/1.0" 304 0 "https://rezepte-.de/static/themes/tandoor.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"

`

By the way: Howto disable nginx access log

**Comment by BstAA** [comment]
Please reopen. 
See comment on #2699
