### ISSUE TITLE
Problem with importing PDF

### ISSUE THREAD

**Issue by che-rusker** [TandoorRecipes/recipes#2716]
### Tandoor Version

1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

I get "There was an error creating a resource!" when importing any of my (many) PDF-recipes. Example attached.

What might go wrong here?

I can import recipe from (some) webseites.

[zimtkissen100-pdf.pdf](https://github.com/TandoorRecipes/recipes/files/13242979/zimtkissen100-pdf.pdf)

**Comment by nough** [comment]
There is currently no support for importing pdf files, unless you're referring to storing them as external files?
