### ISSUE TITLE
Import from Ploetzblog not working

### ISSUE THREAD

**Issue by che-rusker** [TandoorRecipes/recipes#2719]
### Tandoor Version

1.5.6

### Import URL

https://www.ploetzblog.de/rezepte/alle-rezepte

### When did the issue happen?

When pressing the search button with the url

It is a pity that the import from THE german breadbaking-blog does not work. Hopefully this will be healed soon.

### Response / message shown

```shell
Failure
There was an error fetching a resource!
```

**Comment by smilerz** [comment]
Site importing handled [here](https://github.com/hhursev/recipe-scrapers).  However, there isn't any structure data so doubt there is much they'll be able to do about it.

**Comment by che-rusker** [comment]
Ploetzblog is on typo3 now, no longer on WordPress. Maybe that is a problem.
But there are identifiable divs, no?

**Comment by che-rusker** [comment]
Oh, and what about this one?

#2717
