### ISSUE TITLE
properties

### ISSUE THREAD

**Issue by casimpunkt** [TandoorRecipes/recipes#2720]
### Tandoor Version

1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

If you use the “Copy to new recipe” function in recipe1 and then change the “properties” in this new recipe2, the properties in the original recipe1 will also be changed.

**Comment by vabene1111** [comment]
thanks for the report, I think i know why this might be the case

**Comment by silamon** [comment]
Upon cloning, by creation of the recipe the id of the properties is not cleared.
