### ISSUE TITLE
How can I add all of my recipes to a new book?

### ISSUE THREAD

**Issue by languagemaniac** [TandoorRecipes/recipes#2723]
### Issue

It's been quite a journey, I have a physical book I wanted to import to tandoor, so I got the digital edition of it, converted it to a txt file, and divided it with a script so I could have all the recipes in individual files, and then with another script, I formatted them to pepperplate's txt output format (just registered there for this purpose, to see how it was formatted), so I could then zip all of them into a single zip file, and import them, Couldn't think of a better way to do this, but it has worked nicely.

So I just imported over 200 recipes from that book and I'd like to add them all to a cookbook. I imported them in 2 sets so all those recipes have the tags "import 1" and "import 2" on them.

When creating a new cookbook, I see there's a field called "Recipe filter" that says "Include recipes from recipe filter in addition to manually assigned ones.", but I haven't found any information on how to use it. Whatever I type there doesn't do anything. I would like to filter by "import 1" and "import 2".

Is it even possible? How does this recipe filter work? I'd appreciate some help as I plan to do this with more books,

I'd also appreciate some information about how to import a digital pdf to tandoor. External recipes? I tried creating a dropbox token but after that, I couldn't make tandoor sync and read the pdf (didn't know how to set the path, that's probably it), so I did it that way, via pepperplate import option.

### Tandoor Version

1.5.6

### OS Version

Windows 10 64bit

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

**Comment by smilerz** [comment]
1. Search for the recipes you want in the book.
2. Click "Save Filter" (expand the Advanced Search section) - a pop up will ask you to name the filter
3. It should now be available in Recipe Books.

**Comment by languagemaniac** [comment]
> 1. Search for the recipes you want in the book.
> 2. Click "Save Filter" (expand the Advanced Search section) - a pop up will ask you to name the filter
> 3. It should now be available in Recipe Books.
> 
> 
> For the PDF question, I suggest opening a discussion topic or joining discord.  It's likely to be overlooked in issues (I don't use it so can't point you in the right direction.)

Thanks, it worked. I will try asking over on discord about the pdf question.
