### ISSUE TITLE
Docker image latest tag and latest-raspi to do not reference the same version

### ISSUE THREAD

**Issue by sthuber90** [TandoorRecipes/recipes#2726]
### Tandoor Version

latest-raspi

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

The `latest` tag of the Docker image has been published two months ago and references to the release 1.5.6 whereas the `latest-raspi` tag still refers to 1.4.12. From the changelog details I would expect the `latest-raspi` build to have been fixed with the 1.5.4 release

**Comment by vabene1111** [comment]
interesting, i need to check on that, maybe it failed when i released it, I think I might remember anther cryptography fail back then

**Comment by sthuber90** [comment]
@vabene1111 Sorry to ask but were you able to check in on the issue?

**Comment by silamon** [comment]
You can use the latest tag instead of the latest-raspi tag. 
The architectures from the latest-raspi tag are published under the latest tag.

**Comment by vabene1111** [comment]
thanks for the clarification, we changed things around a bit a while ago and I kinda forgot how we did it. 

the normal latest tag supports all 3 architectures https://hub.docker.com/layers/vabene1111/recipes/latest/images/sha256-7a54e82bf8cc5dfb2787e64effe778d1d8c32a3563b6b5725f2bf82d8cbba5b2?context=repo

**Comment by sthuber90** [comment]
@vabene1111 thank you. You should probably update the documentation then ![image](https://github.com/TandoorRecipes/recipes/assets/4415930/8e7dfd31-89b7-42e9-9b6c-53be5cbe2488)

**Comment by KartOMania** [comment]
did you change something regarding the latest-raspi and ARM32v6 support? 

A few days ago i was able to `docker compose up` tandoor on my raspberry pi zero W. I ran into code 139s while running it after a few minutes. Set backs or it beeing impossible was to be expected. I was well aware of the warning on your raspberry 32 bit comments in the docs) 

While trying to figure out how to go about that, i flashed a new install of raspberrypi OS. Now i am trying to get tandoor running again but it stops me when using `docker compose up`, quickly letting me know that there is no matching manifest `no matching manifest for linux/arm/v6 in the manifest list entries`. Maybe that is related to your latest changes? in the docker-compose.yml i was referencing the  `    image: vabene1111/recipes:latest-raspi`
![grafik](https://github.com/TandoorRecipes/recipes/assets/62652724/bc904c69-2eeb-49b9-a45a-220695a2b664)

I assume my ARM32v6 is just too outdated to be supported. any insights appreciated

**Comment by sthuber90** [comment]
So, I've tested the `latest` tag on my raspberry and it seems to work. The page loads, I can search and create recipes. The commit ID in the system page matches the one of the 1.5.10 release. All looks good to me, except that I stumbled over the issue #2791 as well and was worried I messed up my installation. It's correct that this issue here has been closed and to me it seems safe and a good idea to update the documentation.

![grafik](https://github.com/TandoorRecipes/recipes/assets/4415930/1147bea8-3121-4f53-b9d9-8eae53ca41ce)


Thank you for your support and this project 🙏

**Comment by vabene1111** [comment]
@KartOMania that might be the case, I had hoped that just using `latest` as @sthuber90  described should work even on older raspi setups but given the architectures on the docker tag I think its only arm/v7 thats supported. 

So 32bit is supported on raspi but just if using arm v7 not v6 


according to wikipedia that means that all raspis besides version 1 and the first generation zero should be supported. https://de.wikipedia.org/wiki/Raspberry_Pi#Eigenschaften

**Comment by vabene1111** [comment]
I updated the docs accordingly (develop), if anything in this thread here is incorrect please open a new issue and reference this one. 

If you do open a new issue make sure to provide proper information about your setup.

**Comment by KartOMania** [comment]
@vabene1111 
> according to wikipedia that means that all raspis besides version 1 and the first generation zero should be supported. https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications

i since then purchased a raspi pi zero w 2 and there i got the same setup running. It has a 64 bit capable prozessor but i am running the "stable" 32 bit raspi os 11 bullseye on it. Tandoor is running fine on it. Just a tadbit slow but still fast enough. Just an info that this works as intended. I went for the `latest-raspi` build there.

**Comment by KartOMania** [comment]
i'll see about what i can do to get it running on my zero w (1) with `:latest`
