### ISSUE TITLE
Ingredients with the same type in the overview doesn't sum up

### ISSUE THREAD

**Issue by Arthedian** [TandoorRecipes/recipes#2732]
### Tandoor Version

v1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

When I split recipe into multiple steps, then set ingredient to each step and save the Recipe. When I am viewing it, In the overview list of ingredients, some ingredients has multiple rows instead of summing it in one.

**Comment by smilerz** [comment]
Duplicate

**Comment by Arthedian** [comment]
Thank you for such quick response. Can I Ask to which task it is duplicate, so I can track the progress?
