### ISSUE TITLE
missing "how to" get started

### ISSUE THREAD

**Issue by kai-uwe-rommel** [TandoorRecipes/recipes#2734]
### Affected section

Installation

### Issue description

I set up a fresh new instance. I could not see anywhere in the docs what the initial login is.
I ended up creating a "superuser" like documented in the FAQ, logged in with it and created a new space.
This is weird, it should be easier to get started.

**Comment by vabene1111** [comment]
if you enter the url of your server into the browser you are brought to the setup page (only before the first user is created), so this should work without any further explanation.

**Comment by kai-uwe-rommel** [comment]
Well, but it did not. I got in finally, but found that way to be awkward.
Perhaps I did something wrong. For such cases, a short description should go into the documentation.
Thanks!
