### ISSUE TITLE
Unit conversion database import

### ISSUE THREAD

**Issue by yassendobrev** [TandoorRecipes/recipes#2735]
### Documentation link

https://github.com/TandoorRecipes/open-tandoor-data

### Affected section

Features

### Other

Unit conversion

### Issue description

The Tandoor open data repository mentions importing the database into a local Tandoor instance, but I cannot find any instructions on how to do that. How can I import the unit conversions into my local installation?

**Comment by yassendobrev** [comment]
Petitgnoll6 pointed out on Discord, that there is an import function under `Space Settings` --> `Open Data Import`. However, the import function seems to be broken currently.

**Comment by vabene1111** [comment]
yes it is very WIP, it does work to some degree but has quite a few edge cases that need smoothing
