### ISSUE TITLE
show details in shopping list on iPhone

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#2741]
### Tandoor Version

1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

In left handed mode it is not possible to show details of a shopping list item. With clicking on the ">" the item gets checked as completed. 

In right handed mode it is possible.

**Comment by vabene1111** [comment]
thanks, the shopping list UI needs some major overhaul, I will consider this when doing it
