### ISSUE TITLE
UI: Time Badges block Description

### ISSUE THREAD

**Issue by flomero** [TandoorRecipes/recipes#2743]
### Tandoor Version

1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

the time badges on recipe cards block the description, which comes up on hover:

![image](https://github.com/TandoorRecipes/recipes/assets/49640251/332124d7-1d72-4ae7-bc57-d567055514b9)

expected behavior:

![image](https://github.com/TandoorRecipes/recipes/assets/49640251/5aeeb9a8-ea56-430f-a647-9aecaaeddaf3)

while on it I noticed, that the overlay doesn't cover the whole image. Is there a specific reason for `.content-overlay` to have `height: 99%;` on it instead of 100%?

would gladly create a pull request if this gets assigned to me ✌🏼

**Comment by vabene1111** [comment]
i kinda suck at css so I copied that from some tutorial, so no idea why its 99%. I changed it to 100%. 

Is there an easy fix for the layering as well? Feel free to open a PR or just post the css here and I will include it.

**Comment by vabene1111** [comment]
thanks, that does the trick
