### ISSUE TITLE
Prevent the editing page from closing when there are unsaved changes

### ISSUE THREAD

**Issue by gjgress** [TandoorRecipes/recipes#2749]
### Is your feature request related to a problem? Please describe.

The other day I spent 2 hours working on a recipe, forgot to save as I went, and accidentally Ctrl+W'd and lost everything. I was surprised there was no edit protection. The page closed without warning me about unsaved changes, and I lost all progress.

### Describe the solution you'd like

Seems to be a rather simple implement, just need to include a script like [this](https://thewebdev.info/2021/03/06/how-to-warn-user-before-leaving-a-web-page-with-unsaved-changes/) in the forms javascript.

I forked the project and started a development server, but I can't seem to find the file where I would add this script. The closest I found was in /cookbook/templates/forms/edit_internal_recipes.html ,  but the actual app where the form is managed seems to be elsewhere.

Happy to contribute the change myself if I can be pointed in the right direction.

**Comment by smilerz** [comment]
The file you are looking for is `vue/src/apps/RecipeEditView/RecipeEditView.vue`

**Comment by vabene1111** [comment]
This feature is implemented and I just tested it and it works. what browser are you using?

**Comment by gjgress** [comment]
Huh. You're right, I am entirely unable to replicate this issue now. I have NO idea what happened then.

Sorry for the mistake!

**Comment by vabene1111** [comment]
no worries, I kinda have a feeling that there must be and edge case somewhere because I remember (a long time ago) also not getting a confirmation, but since I am listening to changes on the complete recipe object that cannot really be the case ... I will keep an eye on similar reports that might pop up
