### ISSUE TITLE
Meal plan api error - could not create meal plan

### ISSUE THREAD

**Issue by theflyer08** [TandoorRecipes/recipes#2756]
### Tandoor Version

1.5.9

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx

### Bug description

In Android & iOS App utare following error occurs adding a recipe to the mean plan: meal plan api error - could not create meal plan.
Furthermore, there is an error message opening the app: type "Null" is not a subtype of type 'string' in type case. 
The error should be associated with the new tandoor version, since utare was not updated on Android and iOS today, while this image has been installed on docker today: vabene1111/recipes:latest

Thank you for your help.

**Comment by smilerz** [comment]
Errors with the mobile apps needs to be addressed with the creator of those apps.
