### ISSUE TITLE
Database is not Postgres SQL but in docker compose it is

### ISSUE THREAD

**Issue by update-freak** [TandoorRecipes/recipes#2762]
### Tandoor Version

1.5.9

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Synology intern Reverse Proxy

### Bug description

![2023-11-30 20_30_15-Kochbuch-Setup](https://github.com/TandoorRecipes/recipes/assets/40196995/2fbccbfc-2a22-48e0-a504-681f238d887b)

I installed Tandoor attached docker compose (and also tried the develop version from 30.11.2023) and always get an "info" in the databse section that I have no Postgres SQL database. But according to the docker compose I expected to have an Postgres SQL database. I'm not sure if I did something wrong in the configuration or if this is a bug.

[compose.txt](https://github.com/TandoorRecipes/recipes/files/13517019/compose.txt)
[Recipes.conf.txt](https://github.com/TandoorRecipes/recipes/files/13517020/Recipes.conf.txt)
[stack.env.txt](https://github.com/TandoorRecipes/recipes/files/13517022/stack.env.txt)

**Comment by smilerz** [comment]
duplicate #2752
