### ISSUE TITLE
Public link not loading properly

### ISSUE THREAD

**Issue by bobokun** [TandoorRecipes/recipes#2769]
### Issue

I currently have Tandoor setup with swag reverse proxy, using Authentik as external authentication. When I try to create a public link it does not load the page properly when sharing with others.

In Authentik I've created these Unauthenticated paths:
```
^/view/recipe/.*
^/api/.*
```

See screenshot of what it looks like when trying to load the page incognito:
![image](https://github.com/TandoorRecipes/recipes/assets/12660469/5981b4b4-16c3-46cc-8eb3-5c951615e04f)

### Tandoor Version

ad1e64fb9a07af0fc9dea68d61cf7084f8dd6c50

### OS Version

Unraid 6.12.4

### Setup

Unraid

### Reverse Proxy

SWAG

**Comment by smilerz** [comment]
Tandoor requires all users to be authenticated.
