### ISSUE TITLE
Diet Doctor import does not import steps

### ISSUE THREAD

**Issue by sevmonster** [TandoorRecipes/recipes#2780]
### Tandoor Version

v1.5.10

### Import URL

https://www.dietdoctor.com/recipes/classic-keto-hamburger

### When did the issue happen?

When pressing the search button with the url

**Comment by smilerz** [comment]
Web Imports are maintained at https://github.com/hhursev/recipe-scrapers

**Comment by sevmonster** [comment]
Should probably put that on the issue template.

**Comment by smilerz** [comment]
@vabene1111 - he's probably right

**Comment by sevmonster** [comment]
@smilerz Would this be an issue for this repo?

https://github.com/hhursev/recipe-scrapers/issues/959#issuecomment-1869300734

**Comment by smilerz** [comment]
> @smilerz Would this now be an issue for this repo since it looks like instructions are currently being correctly returned in `recipe-scrapers`?
> 
> [hhursev/recipe-scrapers#959 (comment)](https://github.com/hhursev/recipe-scrapers/issues/959#issuecomment-1869300734)

It'll properly import instructions (as a single step) once the recipe-scrapers version has been bumped.

**Comment by sevmonster** [comment]
14.53.0 includes the `wild_mode` fixes, and Tandoor beta branch includes 14.53.0. What bump are we waiting for?

**Comment by sevmonster** [comment]
Sorry, I for some reason read 14.53 instead of 14.52 which is what is actually written. I'll just build it myself to test.

**Comment by sevmonster** [comment]
I built the latest beta + open recipe data with `recipe-scrapers` bumped to 14.53. The steps do appear but now attempting the import fails and leaves the database in an inconsistent state. Recipe search no longer works and viewing the created recipe resource results in a 500 error. Anything I should do to debug this?
