### ISSUE TITLE
switch between spaces in mobile app

### ISSUE THREAD

**Issue by Boerdi0602** [TandoorRecipes/recipes#2783]
### Issue

When using the app i am not able to switch between the spaces in properties -> spaces. 
I can only see the space I opened on my Notebook.
When I switch the space on my Notebook and get back to my mobile device I can see that i selected anothter space on my notebook and this is now my current space in mobile app.
Is it possible to see all spaces in the mobile app to switch between these?

### Tandoor Version

1.5.9

### OS Version

HassIO 2023.11.2

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

**Comment by smilerz** [comment]
We don't have anything to do with the app.
