### ISSUE TITLE
Meal Plan To-Date should change when From-Date changes

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#2786]
### Describe the solution you'd like

If you change the From-Date on the meal plan modal the To-Date should change keeping the difference between the two consistent.
e.g. If From/To starts with date 12/5/2023 and From is changed to 12/7/2023 the To-Date should change accordingly.  

Optionally, make this behavior a user setting.

**Comment by smilerz** [comment]
I'm open to a number of different options - the outcome I'd prefer is to never touch the 'To Date' as I don't use multi-day meals.

**Comment by vabene1111** [comment]
done :)
