### ISSUE TITLE
Can't edit recipes

### ISSUE THREAD

**Issue by update-freak** [TandoorRecipes/recipes#2788]
### Tandoor Version

1.5.10

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Synology Reverse Proxy

### Bug description

I can not edit my recipes (there is no button or menu)
This effects imported ones and also new created ones (see screenshot).
Tested with current Chrome and Edge.

![2023-12-08 11_14_02-Spätzle-Pfanne - Profil 1 – Microsoft​ Edge](https://github.com/TandoorRecipes/recipes/assets/40196995/ddc0e582-dbc2-41dc-ab88-f5d0f0b49a10)

Setup files:
[Recipes.conf.txt](https://github.com/TandoorRecipes/recipes/files/13612826/Recipes.conf.txt)
[stack.env.txt](https://github.com/TandoorRecipes/recipes/files/13612828/stack.env.txt)
[compose.txt](https://github.com/TandoorRecipes/recipes/files/13612825/compose.txt)

**Comment by smilerz** [comment]
Have you cleared your cache?  Are there errors in the logs or console?

**Comment by update-freak** [comment]
Yes, I also tried to clear cache.
Here are the logs:

[Tandoor_logs.txt](https://github.com/TandoorRecipes/recipes/files/13614421/Tandoor_logs.txt)
[Tandoor-DB_logs.txt](https://github.com/TandoorRecipes/recipes/files/13614422/Tandoor-DB_logs.txt)
[Tandoor-NGINX_logs.txt](https://github.com/TandoorRecipes/recipes/files/13614423/Tandoor-NGINX_logs.txt)

**Comment by smilerz** [comment]
and the console logs?

**Comment by update-freak** [comment]
Thanks.
Ok, that's strange because my docker compose already contains `user: 1026:100`.

But I found something out:
I tried it now also with v1.5.9 (clean install => removed existing files) --> Here I can edit the recipes
![2023-12-08 16_16_01-Suchen](https://github.com/TandoorRecipes/recipes/assets/40196995/3b92c59e-b82f-4874-b2c2-88ad6accd84b)
(screenshot from v1.5.9)
In v1.5.10 (clean install), I can not edit the recipes

Here the logs from v1.5.9 to compare:
[Tandoor_logs-1.5.9.txt](https://github.com/TandoorRecipes/recipes/files/13616036/Tandoor_logs-1.5.9.txt)
[Tandoor-DB_logs.1.5.9.txt](https://github.com/TandoorRecipes/recipes/files/13616040/Tandoor-DB_logs.1.5.9.txt)
[Tandoor-NGINX_logs.1.5.9.txt](https://github.com/TandoorRecipes/recipes/files/13616042/Tandoor-NGINX_logs.1.5.9.txt)

**Comment by update-freak** [comment]
I tried to give the access to the user "Everyone" (Reading + Writing) for the tandoor-folder (and all the folders/files below). This did not work.
But the folder `/opt/recipes/cookbook` is not mapped on the Synology NAS, so how is this connected to the permissions on Synology NAS?

**Comment by smilerz** [comment]
` /volume1/docker/tandoor/staticfiles` is on Synology.

**Comment by update-freak** [comment]
ah ok, yes ` /volume1/docker/tandoor/staticfiles` is on Synology.
Jop, I also tried it with a restart of the container, but same problem.

**Comment by smilerz** [comment]
If the logs are still reporting a permissions error then permissions aren't set correctly - I don't have a synology so can't troubleshoot it.  But I suspect that your user setting on the container is causing the problem.

**Comment by update-freak** [comment]
ok, no problem.
For me it's still strange that for v1.5.9 I have the same error `PermissionError: [Errno 13] Permission denied: '/opt/recipes/cookbook/static/django_js_reverse/reverse.js'` and there it works

**Comment by ctrlaltdelete007** [comment]
Same here, version 1.5.9 is working, with latest version i also cannot edit the recipes, because the button is missing.

**Comment by update-freak** [comment]
Do you see the cause of the problem from that permission screenshots

![tandoor](https://github.com/TandoorRecipes/recipes/assets/40196995/0dad374d-2975-454b-b7e8-293bdcf35eb0)
![tandoor2](https://github.com/TandoorRecipes/recipes/assets/40196995/1e11f81a-7f4c-41bb-bfdb-eb70a1b23642)

**Comment by smilerz** [comment]
Only the whatever user is greyed out has write access - the group and everyone else is read only

**Comment by update-freak** [comment]
Found a solution.
When I don't use `user: 1026:100` in the docker compose I can edit the recipes and don't get the error in the logs.
So from my side this issue could be closed.

**Comment by mathroule** [comment]
> Found a solution. When I don't use `user: 1026:100` in the docker compose I can edit the recipes and don't get the error in the logs. So from my side this issue could be closed.

I had the same issue, indeed removing the user from the docker compose for the tandoor container did the trick. Thanks

**Comment by mathieu-lemay** [comment]
Removing the user from the docker compose file works, but it would be nice to be able to run it with a regular user and not root

**Comment by update-freak** [comment]
Indeed would be nice to be able to use the non root user

**Comment by mc-knife** [comment]
facing the same issue with tandoor as an yunohost app, see my description and [logs of the issue](https://forum.yunohost.org/t/permission-broken-after-tandoor-app-update-cant-edit-recipes-anymore/28308) in yunohost forum. one strange thing: tandoor 1.5.10 was still working. editing broke with update to 1.5.11
i would appreciate getting editing feature back. i like editing ;-)

**Comment by smilerz** [comment]
> facing the same issue with tandoor as an yunohost app, see my description and [logs of the issue](https://forum.yunohost.org/t/permission-broken-after-tandoor-app-update-cant-edit-recipes-anymore/28308) in yunohost forum. one strange thing: tandoor 1.5.10 was still working. editing broke with update to 1.5.11 i would appreciate getting editing feature back. i like editing ;-)

If you are unable to edit it is because your app is deployed incorrectly.  To correct this issue please open a new issue and supply all of the requested details.

**Comment by mc-knife** [comment]
thanks for your quick reply @smilerz and your suggestion to check yunohost integration of the app. i try to get support for that possible deployment failure back in the yunohost forum. let us see if something happens there. will let you know here.
