### ISSUE TITLE
Using PostgreSQL but status say: SQLite

### ISSUE THREAD

**Issue by somera** [TandoorRecipes/recipes#2790]
### Tandoor Version

commit abf8f791360b2bc4a5c7d011877668679bcbb3f2

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

This is

```
docker run -d \
  -v "$(pwd)"/staticfiles:/opt/recipes/staticfiles \
  -v "$(pwd)"/mediafiles:/opt/recipes/mediafiles \
  -p 8877:8080 \
  -e SECRET_KEY=xxx \
  -e DB_ENGINE=django.db.backends.postgresql \
  -e POSTGRES_HOST=xxx \
  -e POSTGRES_PORT=5432 \
  -e POSTGRES_USER=xxx \
  -e POSTGRES_PASSWORD=xxx \
  -e POSTGRES_DB=xxx \
  -e ENABLE_PDF_EXPORT=1 \
  --name recipes_1 \
  vabene1111/recipes
```

how I run TandoorRecipes.

But in the status page I get the Info, that I'm not using PostgreSQL

![image](https://github.com/TandoorRecipes/recipes/assets/8334250/281db666-578f-46b1-8e02-e083961d20ee)

Which is wrong. Cause I see the tables and the data in the PG.

And in the status page I don't see the TandoorRecipes. Only the commit.

![image](https://github.com/TandoorRecipes/recipes/assets/8334250/dd4acfb0-b12d-4862-bb83-186fbcb2f53a)

**Comment by smilerz** [comment]
Duplicate.

**Comment by somera** [comment]
Duplicate #1936

**Comment by mfschumann** [comment]
I am seeing the same warning. According to [the docker install documentation](https://docs.tandoor.dev/install/docker/#docker) the command used here should be perfectly fine, so I would consider the observed behavior a bug; if not in the app, then in the documentation.

**Comment by somera** [comment]
I'm asking me, why this "old" issue will not be fixed.

**Comment by smilerz** [comment]
A) it's not old
B) there's already a PR for it.
