### ISSUE TITLE
Invalid URL when trying to import a recipe

### ISSUE THREAD

**Issue by jvanbruegge** [TandoorRecipes/recipes#2795]
### Tandoor Version

1.5.10

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

NixOS, HAProxy

### Bug description

After upgrading tandoor from 1.4.9 to 1.5.6/1.5.10 the recipe importer has stopped working. I tried with different recipes from the same and from other sites. I always get "Invalid URL" as error.
Going back to 1.4.9 the same recipes work without issues. As example, I tried importing [this](https://www.chefkoch.de/rezepte/1434491248280605/Rosenkohl-mit-Speck.html)

### Relevant logs

```shell
Dec 09 21:34:27 nixos gunicorn[63385]: [2023-12-09 21:34:27 +0000] [63385] [INFO] Starting gunicorn 21.2.0
Dec 09 21:34:27 nixos gunicorn[63385]: [2023-12-09 21:34:27 +0000] [63385] [INFO] Listening at: http://127.0.0.1:8410 (63385)
Dec 09 21:34:27 nixos gunicorn[63385]: [2023-12-09 21:34:27 +0000] [63385] [INFO] Using worker: sync
Dec 09 21:34:27 nixos gunicorn[63387]: [2023-12-09 21:34:27 +0000] [63387] [INFO] Booting worker with pid: 63387
```

**Comment by vabene1111** [comment]
I just imported your recipe without any issues so this must be related to your setup. Please set DEBUG to 1 in your envrionment and post the log again, also take a look at the browser console network request response, there might be some clues as to why this happens. I dont really think anything major was changed on the importer 🤔

**Comment by jvanbruegge** [comment]
The debug log also just says: `Bad Request: /api/recipe-from-source/`
The actual request in the browser looks normal (using some other random recipe):
```json
{"url":"https://www.chefkoch.de/rezepte/3599211541199502/Entenkeulen-aus-dem-Ofen.html","data":""}
```
The response is just the error:
```json
{"error":true,"msg":"Ungültige URL"}
```

**Comment by jvanbruegge** [comment]
Ok, after searching the codebase where the error is thrown, I've found the issue. Upstream NixOS has updated the validators package to `0.22.0` while tandoor needs `0.20.0`. Pinning the version fixes the import

**Comment by jvanbruegge** [comment]
I've opened a PR to fix this: https://github.com/NixOS/nixpkgs/pull/273354

**Comment by somera** [comment]
I have the same issue

```
stderr 06.01.2024 11:13:15 Bad Request: /api/recipe-from-source/
stderr 06.01.2024 11:13:15 Bad Request: /api/recipe-from-source/
```
