### ISSUE TITLE
Regression bug : logic change on "postgres" variable, impacting system template

### ISSUE THREAD

**Issue by glennsantacruz** [TandoorRecipes/recipes#2798]
### Tandoor Version

1.5.10

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

Commit breaks/changes logic : 
https://github.com/TandoorRecipes/recipes/commit/e89c1742fbf14c611ed9b1cde508ec8baf859e25#

cookbook/views/views.py  - line 312.  The prior logic set the "postgres" value to *false* if a valid postgres driver was used. The updated code changes the value to *true* if a valid postgres driver is used. This impacts the "system" status URL logic, resulting in a false error message about the Database not being a supported version.

**Comment by smilerz** [comment]
duplicate

**Comment by smilerz** [comment]
#2791
#2790
#2775
#2762
#2752
