### ISSUE TITLE
UI Scaling issue on Smartphones when editing a recipe

### ISSUE THREAD

**Issue by kladderadeng** [TandoorRecipes/recipes#2806]
### Tandoor Version

1.5.10

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

When you edit a recipe and the window width goes below a certain width, UI elements are overlapping and you can not see anymore what you are editing in your recipe. This is a problem now an all our Smartphones, no matter if we use them in portrait or landscape.

I can even replicate it with Edge on the Desktop. I went to the Dev Tools and tried various widths to show you the results.

This is when editing with a width of 993x683 pixels:
![image](https://github.com/TandoorRecipes/recipes/assets/111387593/0b8bdc26-c78b-4b0b-bb11-bd0113296db5)

Now reduce to 991x683
![image](https://github.com/TandoorRecipes/recipes/assets/111387593/248e867e-6112-48a1-81cb-97216cfa834b)

As you can see, it looks pretty messed up and we cannot even see what the 1.700g are for.

Now reduce to 766x683:
![image](https://github.com/TandoorRecipes/recipes/assets/111387593/487e3157-cf7a-41b3-8cc1-57a8de012c83)

It is even worse now and this is how it looks on our Android Smartphones, no matter if we use portrait or landscape.

We are not 100% sure on which version the problems started, but it must have been very recently. Either with the current version or one version before is what we suspect.

**Comment by smilerz** [comment]
duplicate #2781

**Comment by kladderadeng** [comment]
> duplicate #2781

Sorry @smilerz. I should also have searched through the closed issues. I just did not expect to find it there, running the new version. Seeing this is fixed I am looking forward to the next release. Thank you very much :-) 👍
