### ISSUE TITLE
Compatibility with organizr

### ISSUE THREAD

**Issue by languagemaniac** [TandoorRecipes/recipes#2814]
### Is your feature request related to a problem? Please describe.

Hi, I found a thing called [Organizr`](https://github.com/causefx/Organizr) that helps me have all the websites my pi serves on one single page quite easily. 

I felt very identified when I read these words in their website

"Do you have quite a bit of services running on your computer or server? Do you have a lot of bookmarks or have to memorize a bunch of ip's and ports? Well, Organizr is here to help with that. Organizr allows you to setup "Tabs" that will be loaded all in one webpage. You can then work on your server with ease. "

But it looks like tandoor recipes is not compatible with organizr. When I try to add it, it shows "url failed approval for iframe"

Don't know what an iframe is, so don't know what I'm really asking for or if it would be easy to implement. Please excuse my ignorance.

Adding tandoor recipes to organizr is still convenient for me anyways because it doesn't display there but organizr lets me open it in a new window, so it still works like a shortcut. 

### Describe the solution you'd like

Tandoor recipes would show in organizr

**Comment by akamicah** [comment]
If you're using a reverse proxy (i.e. nginx), you can set;

```
add_header X-Frame-Options "ALLOW-FROM home.lan";
add_header Content-Security-Policy "frame-ancestors home.lan";
```

(where home.lan is whatever you're using)

![Screenshot_20240819_083353](https://github.com/user-attachments/assets/585f5fd5-732f-49f1-9527-e1a1e023c106)

**Comment by vabene1111** [comment]
this sounds like a solution so i would say go with that.
