### ISSUE TITLE
Can't delete spaces

### ISSUE THREAD

**Issue by Petitgnoll6** [TandoorRecipes/recipes#2816]
### Tandoor Version

1.5.9

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I did a couple of spaces to test tandoor-data import (one for en, one for de, one for french, etc).

I wanted to delete those test spaces, but 2 of them i add a server error 500 (by deleting from space settings).
I tried to delete from admin page: told me it cannot delete cause it would delete XXXX things that are protected, all of those things were propretys.
Tried deleting the propretys types, server error.
Deleting the foods didnt delete the propretys.
So I deleted all the proprety from admin page, 100 per 100 cause it would make an error if I delete all of them at once (2000+ proprety). Below a 1000, i could delete them all at once.

Once all the proprety gone, I could delete the spaces.

Step to reproduce:
- Create a new space
- Import EN/DE/FR open data
- Try to delete the space => error 500

**Comment by vabene1111** [comment]
would be great if you could provide some logs, would make fixing this much easier

**Comment by blakejalexander** [comment]
I also have the same issue, can't provide logs, but I can recreate an MVP. Just let me know what files you would need and where I can upload them.

**Comment by vabene1111** [comment]
ok fixed some issues with space deletion
