### ISSUE TITLE
Recipe as Ingredient, further implementation suggestions

### ISSUE THREAD

**Issue by KartOMania** [TandoorRecipes/recipes#2820]
### Is your feature request related to a problem? Please describe.

I have a basic recipe for Pizza dough. 

Now i have 5-10 different toppings that i gave their own recipe each. But since they all reference the Basic dough i am putting in the same Ingredients and steps for the dough. 

there is the option to link a recipe to an ingredient, it seems not to have any effect:
![grafik](https://github.com/TandoorRecipes/recipes/assets/62652724/92e97a6e-92a1-4e3d-9449-02f200cadc92)
i can't reference this in other recipies in their ingredient list's popup

i also tried adding the recipe itself in a step of a pizza recipe ![grafik](https://github.com/TandoorRecipes/recipes/assets/62652724/e67e43f5-525e-4356-bbf7-2b3ddf96fefa)
which leads to this, wich is almost perfect but sadly doesn't allow for me to add those to the main ingredient list. 
![grafik](https://github.com/TandoorRecipes/recipes/assets/62652724/50065cac-9c77-4480-a853-c74da9fe26e1)

### Describe the solution you'd like

Allow for the option to add the ingredients of a recipe selected in a step to also add to the list of main ingredients (possible via a toggle when editing the recipe

### Describe alternatives you've considered

Right now there is the option to link a recipe with an ingredient `pizzadough`. I was expecting that now whenever i add that ingredient `pizzadough` to a recipe that it would automatically add or at least offer me to add (via toggle button) the ingredients of the `pizzadough` recipe to the Pizza#7 recipe's inredient list. 

### Additional context

The Portion size is defined in the dough Recipe
![grafik](https://github.com/TandoorRecipes/recipes/assets/62652724/aff0358f-5897-4a63-8fed-77c0b00de05e)
somehow being able to manipulate that to adapt numbers would also be fantastic

**Comment by smilerz** [comment]
duplicate #1993

**Comment by KartOMania** [comment]
Thank you! My brain was working in german when looking for clues to search for when looking for others with this issue :D

**Comment by KartOMania** [comment]
https://github.com/TandoorRecipes/recipes/pull/2212 this looks like it will do just great :)
