### ISSUE TITLE
Very poor performance

### ISSUE THREAD

**Issue by igor47** [TandoorRecipes/recipes#2828]
### Tandoor Version

abf8f791360b2bc4a5c7d011877668679bcbb3f2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

seeing very poor performance with not too many recipes. for instance, here's one example of a search page. my instance has maybe 7 to 9 recipes right now and this request took 15 seconds:
![image](https://github.com/TandoorRecipes/recipes/assets/200575/e1d3c53f-d37b-4097-aca2-253cf46d7832)

i was originally just serving static files with gunicorn, but moved it to nginx with no improvement in performance. i also tried increasing the number of gunicorn workers.

another example with a best-case scenario of around 2 seconds, which is still very slow and laggy:
![image](https://github.com/TandoorRecipes/recipes/assets/200575/2978ece8-0f22-49c2-89be-cfb720f3b003)

i can repro by just shift-reloading from `/search/`

### Relevant logs

```shell
i don't see anything specific in the logs. there's occasional timeouts, but them seem unrelated to slow requests. for example:

tandoor.purr-1  | [2023-12-23 01:39:08 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:67)
tandoor.purr-1  | [2023-12-23 01:39:09 +0000] [1] [WARNING] Worker with pid 67 was terminated due to signal 9
```

**Comment by LeGmask** [comment]
I'm facing the same issue, and the app only has two recipes

**Comment by smilerz** [comment]
Try rebuilding the recipe index in Admin (under the recipe objects)

**Comment by Hoffelhas** [comment]
> Try rebuilding the recipe index in Admin (under the recipe objects)

Couldn't find this, how do you do this exactly?

**Comment by Hoffelhas** [comment]
Ah there it is! Thank you. Was able to re-index 'recipe', and also delete any unused values at 'Steps'.

After doing this the Recipes page doesn't seem to load any faster. Similarly to [LeGmask](https://github.com/LeGmask), I only have two recipes yet, but it already takes ~5 seconds to load the page.

**Comment by smilerz** [comment]
these are typically indicative of low memory conditions.  Are you running this on a low powered device and with Postgres on the same system?

```
tandoor.purr-1  | [2023-12-23 01:39:08 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:67)
tandoor.purr-1  | [2023-12-23 01:39:09 +0000] [1] [WARNING] Worker with pid 67 was terminated due to signal 9
```

**Comment by igor47** [comment]
> these are typically indicative of low memory conditions. Are you running this on a low powered device and with Postgres on the same system?

for me, no. i *am* running postgres on the same system, but the machine has 16G ram with around 9GB free, and an 8-core intel i7 generally running > 90% idle

**Comment by smilerz** [comment]
> > these are typically indicative of low memory conditions. Are you running this on a low powered device and with Postgres on the same system?
> 
> for me, no. i _am_ running postgres on the same system, but the machine has 16G ram with around 9GB free, and an 8-core intel i7 generally running > 90% idle

Your django instance running out of memory - you'll need to troubleshoot why that is.

**Comment by mikemathewson** [comment]
My performance issues stemmed from having too many old shopping list entries in the database. I deleted them all and now everything is snappy again.

- /admin/cookbook/shoppinglistentry/
- /admin/cookbook/shoppinglistrecipe/

Select all and then under Action select Delete (you may need to repeat for each page of listings). WARNING: This will clear out everything in your shopping list.
