### ISSUE TITLE
DEBUG=1 not working

### ISSUE THREAD

**Issue by somera** [TandoorRecipes/recipes#2829]
### Tandoor Version

commit abf8f791360b2bc4a5c7d011877668679bcbb3f2

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

I have often problem with recipes import. The help is restart the container 2-3 times and than it works. Without any changes. Than I added

`-e DEBUG=1`

to see more DEBUG informations. And I see that this is set

![image](https://github.com/TandoorRecipes/recipes/assets/8334250/febca241-c864-4500-9c19-5c97aee96be7)

But there is no more DEBUG logging. This is my expectation when I call `docker logs recipes_1`. I'm right?

**Comment by vabene1111** [comment]
There is more logging but this sound like some weired edge case so this might not be logged even if debug is activated.

**Comment by vabene1111** [comment]
Regarding the issue itself please open a seperate issue or try to investigate your setup especially network
