### ISSUE TITLE
Wrong System Info Database

### ISSUE THREAD

**Issue by falcon10001** [TandoorRecipes/recipes#2832]
### Tandoor Version

latest

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Hello,

I migrated sucessfully from Postgres11 to Postgres15 and everything seem to work fine, but in System Info I got a yellow warning:
Diese Anwendung läuft nicht mit einer PostgreSQL Datenbank. Dies ist in Ordnung, wird aber nicht empfohlen, da einige Funktionen nur mit einer PostgreSQL-Datenbanken funktionieren.

At the moment It seems to be cosmetik, but just to let you know. Don´t know, what exactly is checked.

**Comment by smilerz** [comment]
Duplicate
