### ISSUE TITLE
/system says my db isnt a postgres db but I am using postgres db

### ISSUE THREAD

**Issue by leon1995** [TandoorRecipes/recipes#2836]
### Tandoor Version

abf8f791360b2bc4a5c7d011877668679bcbb3f2

### Setup

Manual Setup

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

`/system` tells me, that `This application is not running with a Postgres database backend. This is ok but not recommended as some features only work with postgres databases.`
But I am using a postgres database
![Screenshot 2023-12-27 at 21 58 44](https://github.com/TandoorRecipes/recipes/assets/15685899/6e5236c7-ce9e-4969-85b6-bb68e629ce41)

`.env` file:
```
# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
# DB_OPTIONS= {} # e.g. {"sslmode":"require"} to enable ssl
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
# ---------------------------- AT LEAST ONE REQUIRED -------------------------
POSTGRES_PASSWORD=<redacted>
POSTGRES_PASSWORD_FILE=
# ---------------------------------------------------------------
POSTGRES_DB=djangodb
```

**Comment by smilerz** [comment]
duplicate

**Comment by RaphaelJenni** [comment]
@smilerz It would be nice to know by which issue this is duplicated. I haven't found the issue yet.

**Comment by smilerz** [comment]
> @smilerz It would be nice to know by which issue this is duplicated. I haven't found the issue yet.

#2791
#2790
#2775
#2762
#2752
#2798 
#2832
