### ISSUE TITLE
Add support for language specific recipes

### ISSUE THREAD

**Issue by arnonm** [TandoorRecipes/recipes#2839]
### Is your feature request related to a problem? Please describe.

Unrelated to the UI of the interface, I'd like Tandoor to be able to handle a recipe in language A and another in language B. This is most visible in RTL languages where the UI of the specific recipe has to adapt from RTL/LTR accordingly, but also relevant for LTR languages 

### Describe the solution you'd like

- Add a language field to the recipe itself. It can default to the UI language that the user has set when entering it, or allow user to select language
- Add the same for import process and edit process
- Based on the language of the recipe, show the recipe in the right direction

**Comment by vabene1111** [comment]
Same as language specific units
