### ISSUE TITLE
Add support for multi-language units

### ISSUE THREAD

**Issue by arnonm** [TandoorRecipes/recipes#2840]
### Is your feature request related to a problem? Please describe.

Currently, units are non-language specific. So addition of the word cup in english, spanish or french will create different fields.
This requires the user to add the units in each language of the recipe

### Describe the solution you'd like

Make units language specific and have a lange slug attached. Allow all units from different languages to by tied in together

**Comment by vabene1111** [comment]
Since the data structure of tandoor is already pretty complicated and one instance is typically only used by people speaking one language this will likely not be implemented

You can however have automation to automatically replace one language with another on import.
