### ISSUE TITLE
Ingredient quantity fields massively oversized in recipe editor, blocking ingredient name field

### ISSUE THREAD

**Issue by SoleInvictus** [TandoorRecipes/recipes#2843]
### Tandoor Version

1.5.10

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

I just started a fresh install of Tandoor but have been using it for years. When I attempt to import or create a new recipe, the quantity field for each ingredient is so large that it blocks the ingredient name field, making it unusable. I've tried this in Vivaldi and Chrome and have the same issue in both browsers.
![Screenshot_20231229_094340_Vivaldi Browser](https://github.com/TandoorRecipes/recipes/assets/39067872/4ef94a90-32d1-4ed5-94b6-2bcccb70d9b5)

**Comment by smilerz** [comment]
duplicate

**Comment by vabene1111** [comment]
@smilerz I dont see another issue mentioning this, do you know what it was called? 

fixed in #bf61b6474e22576f78f6e3ab9f7fac64f0638382

**Comment by smilerz** [comment]
I don't remember if it was an issue, discussion or discord.

**Comment by vabene1111** [comment]
ok perfect, than for now this is closed and if we find it we can close it, I am pretty sure I saw the same issue somewhere else es well but I thought it was my brothers phone 😂

**Comment by SoleInvictus** [comment]
Found it! It's [2781](https://github.com/TandoorRecipes/recipes/issues/2781).

Thanks for all your help and for this program in general. I'm very grateful!

**Comment by vabene1111** [comment]
perfect, thanks :)
