### ISSUE TITLE
Option to disabel Username and Password Auth

### ISSUE THREAD

**Issue by markussiebert** [TandoorRecipes/recipes#2851]
### Is your feature request related to a problem? Please describe.

Hi, as I successfully configured social auth with Tandoor, I would like to disable the username/password auth.  

### Describe the solution you'd like

It would be great if there would be a simple flag via environment variable that disables the login prompt.

### Describe alternatives you've considered

no

**Comment by Kaaybi** [comment]
Sounds like it's a duplicate of #2359
