### ISSUE TITLE
Import Browser Plugins (Chrome + Firefox)

### ISSUE THREAD

**Issue by snickers2k** [TandoorRecipes/recipes#2861]
### Is your feature request related to a problem? Please describe.

- Importing from sites like chefkoch.de or Allrecipes.com works amazingly great by copy&paste,
but takes time

### Describe the solution you'd like

- import chrome + firefox plugin

**Comment by tomtjes** [comment]
Are you aware of the bookmarklet? See respective tab at `your-tandoor.xyz/data/import/url`

**Comment by snickers2k** [comment]
> /data/import/url

yes i am. this is exactly what i refered to with "importing sites works amazingly".

but instead of simply clicking an chrome-plugin-icon to add the current site to tandoor,
opening tandoor manually, copy the url, paste the url etc adds a lot of steps, killing the "workflow" while searching for recipes.

here is a picture of linkwarden (for bookmarks) with pretty much what i requested for tandoor
<img width="403" alt="Bildschirmfoto 2024-01-06 um 13 05 43" src="https://github.com/TandoorRecipes/recipes/assets/5986024/150f058b-82a6-4732-9958-ef473f5771a2">

**Comment by smilerz** [comment]
You don't have to do any of that with the bookmarklet.

**Comment by rompe** [comment]
I'm pretty sure OP is *not* aware of the bookmarklet.
