### ISSUE TITLE
Show icon of source

### ISSUE THREAD

**Issue by syphernl** [TandoorRecipes/recipes#2862]
### Describe the solution you'd like

If a recipe originates from a website it would be nice if there was an option to show the (fav)icon of that website on the recipes in the overview (e.g. in the top-right / bottom-right corner).

**Comment by vabene1111** [comment]
that would mean that either we safe the logo on any import in a file which would result in quite a few files or we do a web request to the site we imported from every time a recipe is shown/opened which is both a privacy issue, a performance issue and probabl difficult as sites tend to start blocking you after a while, so while this is a nice idea I dont think we are going to implement it. 

Thanks for the idea tough, will keep it in mind
