### ISSUE TITLE
Bad Request: /api/recipe-from-source/ when import recipe

### ISSUE THREAD

**Issue by somera** [TandoorRecipes/recipes#2865]
### Tandoor Version

commit abf8f791360b2bc4a5c7d011877668679bcbb3f2

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When I try import a recipe I get

```
stderr 06.01.2024 11:13:15 Bad Request: /api/recipe-from-source/
stderr 06.01.2024 11:13:15 Bad Request: /api/recipe-from-source/
```

With `Debug: True` I don't see more log informations.

![image](https://github.com/TandoorRecipes/recipes/assets/8334250/b38bb5b8-8aaf-41e5-b342-6edaec1b673f)

Yesterday I restartet my whole Mini-Server and after ~24h I get this error. I know, When I restart the docker container it will work. I have this bug for the 2nd or 3rd time.

I can login. I can see the recipes. I can search for the recipes. But I can't import new recipe.

```
docker run -d \
  --restart unless-stopped \
  -v "$(pwd)"/staticfiles:/opt/recipes/staticfiles \
  -v "$(pwd)"/mediafiles:/opt/recipes/mediafiles \
  -p 8877:8080 \
  -e SECRET_KEY=xxx \
  -e DB_ENGINE=django.db.backends.postgresql \
  -e POSTGRES_HOST=xxx \
  -e POSTGRES_PORT=5432 \
  -e POSTGRES_USER=django \
  -e POSTGRES_PASSWORD=xxx \
  -e POSTGRES_DB=djangodb \
  -e ENABLE_PDF_EXPORT=1 \
  -e EMAIL_HOST=xxx \
  -e EMAIL_PORT=xxx \
  -e EMAIL_HOST_USER=xxx \
  -e EMAIL_HOST_PASSWORD=xxx \
  -e EMAIL_USE_TLS=0 \
  -e EMAIL_USE_SSL=1 \
  -e DEFAULT_FROM_EMAIL=xxx \
  -e DEBUG=1 \
  --name recipes_1 \
  vabene1111/recipes
```

```
$ lsb_release -a
LSB Version:    core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
$ uname -a
Linux nuc-mini-pentium 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default
```

```
Gunicorn Media: True
Sqlite: True -> WRONG. I'm using PostgreSQL 16
Debug: True

SERVER_PROTOCOL:HTTP/1.1
REMOTE_ADDR:xxx
SERVER_PORT:8080

HTTP_HOST:nuc-mini-pentium:8877
HTTP_CONNECTION:keep-alive
HTTP_UPGRADE_INSECURE_REQUESTS:1
HTTP_DNT:1
HTTP_USER_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
HTTP_REFERER:http://nuc-mini-pentium:8877/data/import/url
HTTP_ACCEPT_ENCODING:gzip, deflate
HTTP_ACCEPT_LANGUAGE:de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
HTTP_COOKIE:NX-ANTI-CSRF-TOKEN=0.3261584581075543; search_settings3=%7B%22advanced_search_visible%22%3Afalse%2C%22explain_visible%22%3Afalse%2C%22search_input%22%3A%22%22%2C%22search_internal%22%3Afalse%2C%22search_keywords%22%3A%5B%7B%22items%22%3A%5B%5D%2C%22operator%22%3Atrue%2C%22not%22%3Afalse%7D%2C%7B%22items%22%3A%5B%5D%2C%22operator%22%3Afalse%2C%22not%22%3Afalse%7D%2C%7B%22items%22%3A%5B%5D%2C%22operator%22%3Atrue%2C%22not%22%3Atrue%7D%2C%7B%22items%22%3A%5B%5D%2C%22operator%22%3Afalse%2C%22not%22%3Atrue%7D%5D%2C%22search_foods%22%3A%5B%7B%22items%22%3A%5B%5D%2C%22operator%22%3Atrue%2C%22not%22%3Afalse%7D%2C%7B%22items%22%3A%5B%5D%2C%22operator%22%3Afalse%2C%22not%22%3Afalse%7D%2C%7B%22items%22%3A%5B%5D%2C%22operator%22%3Atrue%2C%22not%22%3Atrue%7D%2C%7B%22items%22%3A%5B%5D%2C%22operator%22%3Afalse%2C%22not%22%3Atrue%7D%5D%2C%22search_books%22%3A%5B%7B%22items%22%3A%5B%5D%2C%22operator%22%3Atrue%2C%22not%22%3Afalse%7D%2C%7B%22items%22%3A%5B%5D%2C%22operator%22%3Afalse%2C%22not%22%3Afalse%7D%2C%7B%22items%22%3A%5B%5D%2C%22operator%22%3Atrue%2C%22not%22%3Atrue%7D%2C%7B%22items%22%3A%5B%5D%2C%22operator%22%3Afalse%2C%22not%22%3Atrue%7D%5D%2C%22search_units%22%3A%5B%5D%2C%22search_units_or%22%3Atrue%2C%22search_rating_gte%22%3Atrue%2C%22timescooked_gte%22%3Atrue%2C%22makenow%22%3Afalse%2C%22makenow_count%22%3A0%2C%22cookedon_gte%22%3Atrue%2C%22createdon_gte%22%3Atrue%2C%22updatedon_gte%22%3Atrue%2C%22viewedon_gte%22%3Atrue%2C%22sort_order%22%3A%5B%7B%22id%22%3A3%2C%22text%22%3A%22Name%20(A-z)%22%2C%22value%22%3A%22name%22%7D%5D%2C%22pagination_page%22%3A1%2C%22keywords_fields%22%3A1%2C%22foods_fields%22%3A1%2C%22books_fields%22%3A1%2C%22rating_fields%22%3A1%2C%22units_fields%22%3A1%7D; PHPSESSID=ofm6h24cu3i6100utflsi4s5gs; my_grafana_session=4a415bb4b9b6fed2827ffcbf940cd90d; grafana_session_expiry=1704559946; csrftoken=So69OMoLpMkoQKHadUA8mrakuRHWWlma; sessionid=tno76qv9bjusap2j2gngm4j1ziixj7ol

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f0e8684f8b0>
wsgi.version:(1, 0)
wsgi.multithread:True
wsgi.multiprocess:True
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x7f0e8626beb0>
wsgi.url_scheme:http
```

### Relevant logs

I don't see any usefull log informations. And I run my instance with `-e DEBUG=1`. But here is the log.

[recipe.log](https://github.com/TandoorRecipes/recipes/files/13850560/recipe.log)

**Comment by somera** [comment]
I logged in -> error. I logged out and in -> error.

**Comment by somera** [comment]
Now I saw this after I try to login

![image](https://github.com/TandoorRecipes/recipes/assets/8334250/79c81943-9f31-445a-96f3-17021edfb1f8)

**Comment by somera** [comment]
After container stop, remove and start the import isn't working. I get allways the same error
```
stderr 06.01.2024 11:13:15 Bad Request: /api/recipe-from-source/
stderr 06.01.2024 11:13:15 Bad Request: /api/recipe-from-source/
```
for different logins.

**Comment by somera** [comment]
This is not a browser problem. I tested Chome (120.0.6099.200) and FF (121.0).

**Comment by smilerz** [comment]
In order to holder assurance you will need to share detailed configuration of your setup and all of the log files.

**Comment by somera** [comment]
@smilerz updated the issue. In the logs are NULL informations. with `-e DEBUG=1` I get no more log data. Why?

Is that enough?

**Comment by somera** [comment]
And I try to import https://www.lecker.de/schlesischer-sauerkrauteintopf-mit-pilzen-128228.html .

**Comment by smilerz** [comment]
You are running tandoor and Postgres with no reverse proxy of any kind.  Is that correct?  Do you get an error while importing a recipe or signing in?   It's not clear.

**Comment by somera** [comment]
I connected to the container and did this:

```
$ docker exec -it recipes_1 /bin/sh
...
/tmp # wget https://www.lecker.de/schlesischer-sauerkrauteintopf-mit-pilzen-128228.html
/tmp # ls -al
total 80
drwxrwxrwt    1 root     root          4096 Jan  6 18:13 .
drwxr-xr-x    1 root     root          4096 Jan  6 18:11 ..
-rw-r--r--    1 root     root         70150 Jan  6 18:13 schlesischer-sauerkrauteintopf-mit-pilzen-128228.html
```

After this I can import the recipe. I didn't change anything.

And I don't see more debug with `-e DEBUG=1` when I import, browse or search. Looks like an parameter withou any function.

**Comment by somera** [comment]
> You are running tandoor and Postgres with no reverse proxy of any kind. Is that correct? Do you get an error while importing a recipe or signing in? It's not clear.

Yes, PostgreSQL without any proxy. I get the errors, which you can see in the recipe.log. Same was shown in the browser. Nothing more. There is no extended logging.

Not it works and I didn't change anything. This was not the first time I has this problem. But first time that I reported it.

What should I see with `-e DEBUG=1`?

**Comment by smilerz** [comment]
Please answer my two questions.

**Comment by somera** [comment]
I answered your questions.

- https://github.com/TandoorRecipes/recipes/issues/2865#issuecomment-1879777978
- issue title: Bad Request: /api/recipe-from-source/ **when import recipe**
- and here: https://github.com/TandoorRecipes/recipes/issues/2865#issuecomment-1879635803

I had a lot of problems. But it started with import recipe.

And I asked often why with `-e DEBUG=1` I see the same amout of log entries. Why?

**Comment by smilerz** [comment]
The debug parameter works just fine.

How did you login?  And how did you create the user that you are logged in as?

**Comment by somera** [comment]
> The debug parameter works just fine. Is there any output in the browser console?

![image](https://github.com/TandoorRecipes/recipes/assets/8334250/9e0daae0-c51b-4ba5-abd6-6bb71b824668)

> How did you login? And how did you create the user that you are logged in as?

I created 4 users
- admin -> created after first start. This was weeks ago.
- 3 normal users

I added them here: url:8877/admin/auth/user/ (Django administration)

As I had the problem, I tested it with the normal and admin user and two different browsers. Both has the problem.

And when I'm logging in I check always "Stay logged in"
![image](https://github.com/TandoorRecipes/recipes/assets/8334250/defc9f28-fef8-4a23-b835-422e6608477c)

But I deleted the cookies and logged out.

**Comment by smilerz** [comment]
Creating users with Django admin isn't supported. Please delete them and invite users using the form on Space Settings.

**Comment by somera** [comment]
> Creating users with Django admin isn't supported. Please delete them and invite users using the form on Space Settings.

Sorry. My mistake. I invited them. I fogot this.

**Comment by somera** [comment]
But to my (self fixed problem). As it was there I saw
```
stderr 06.01.2024 11:13:15 Bad Request: /api/recipe-from-source/
stderr 06.01.2024 11:13:15 Bad Request: /api/recipe-from-source/
```
in the container logs.

In browser I saw
![image](https://github.com/TandoorRecipes/recipes/assets/8334250/888af5ce-2abb-400e-acf9-055dce79a164)

My expectation was to see some exception when this happend in the logs.

**Comment by somera** [comment]
In the last weeks I could import ~50 recipes. But sometimes the containers has problem. I would say that withou any specific logging it's not possible to find the problem.

**Comment by smilerz** [comment]
You are welcome to submit PRs to make debug logging more robust. 

In the meantime please delete the users you created incorrectly and recreate them as instructed and see if you continue to have the problem.

**Comment by somera** [comment]
I would leave the issue open for the next 1-2 weeks and keep an eye on it.

**Comment by vabene1111** [comment]
so I have fixed at least one issue with the link provided as it had malformed servingSize data, everything else seems to work .

**Comment by somera** [comment]
I moved my docker container to other VM. I found some problems when the docker container runs on the same VM like Pi-Hole. I can't explain it why. 2 of my 12 containers has the problems. After I moved it, it works without any issues now for ~2 weeks.
