### ISSUE TITLE
Configuration docs linked in .env.template does not exist

### ISSUE THREAD

**Issue by aarondoet** [TandoorRecipes/recipes#2868]
### Documentation link

https://docs.tandoor.dev/system/configuration/

### Affected section

System

### Issue description

The [.env.template](https://github.com/TandoorRecipes/recipes/blob/develop/.env.template) mentions that it only lists the required options and to check on https://docs.tandoor.dev/system/configuration/ for the full docs, however that page does not exist. I could not find any other page in the docs with that information.

**Comment by vabene1111** [comment]
both the comment in .env and the docs are still only on the dev and beta branch, once released the docs will be there.
