### ISSUE TITLE
Nested recipes should be able to be added in portions

### ISSUE THREAD

**Issue by anytimesoon** [TandoorRecipes/recipes#2869]
### Is your feature request related to a problem? Please describe.

When I import a recipe as a step in another recipe, I would like to be able to say that I only want to import x number of portions.

### Describe the solution you'd like

In my particular use case, I have recipes for cake frostings, which typically make far more than I would ever need for a single cake. It would be nice to be able to have say that the carrot cake only needs 1 portion of the frosting, but the coffee cake requires 2 portions of the frosting.

It would also be nice if the quantities of the nested recipe could scale with those of the parent recipe. If I'm making a bigger carrot cake, I want to know how much I will need for the frosting.

**Comment by smilerz** [comment]
Duplicate #910
