### ISSUE TITLE
Import from RecipeKeeper fails

### ISSUE THREAD

**Issue by strobi-foto** [TandoorRecipes/recipes#2876]
### Tandoor Version

1.5.10

### Setup

Synology

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I try to import my RecipeKeeper export file (zip-file, roundabout 700 recipes) in my empty Tandoor Recipe instance. After importing a few recipes the import fails with the attached error from the import log. I have tried a couple of times, have deleted the existing space and created a new space, tried a new export file of RecipeKeeper, all the time with the same error. The import creates 12-15 recipes, then fails. It's not an explicit recipe which causes the failure - I have deleted the "failure" recipe in RecipeKeeper, created a new export file and started a new import. The import runs 1 or 2 recipes forwards and fails on an other recipe. What's remarkable: the recipe, which causes the import failure, is empty and has only the recipe title but no content.

### Relevant logs

```shell
130 - 10-Minuten-Soße mit Basilikum 
131 - 15-Minuten-Soße mit Sesam und Gemüse 
132 - 20-Minuten-Soße mit Gorgonzola 
133 - 25-Minuten-Soße mit Hackfleisch 
134 - 3-ERLEI WURST VOM GRILL MIT SELBSTGEMACHTEN BRÖTCHEN & BBQ-SOBE 
135 - Allgäuer Kartoffelauflauf 
136 - Amarena-Kirsch-Torte 
137 - Ananas-Kokos-Torte 
138 - Ananas-Kokosspeise 
139 - Ananas-Limetten-Rolle 
140 - Ananas-Marzipankuchen: 
141 - Ananas-Rührkuchen 
142 - Ananascreme 
143 - Apfel-Baiser-Torte 
144 - Apfel-Calvados-Eis 
145 - Apfel-Caramel-Torte 
ERROR An unexpected error occurred during the import. Please make sure you have uploaded a valid file.
Imported 16 recipes.
```

**Comment by vabene1111** [comment]
thats interesting, failing completly should never really happen. If you want you can send me your export via email (probably a download link with that many recipes) and I can take a look at it. 
But can't guarantee thats going to be very fast, not sure when I will find the time to do it.

**Comment by strobi-foto** [comment]
Thanks - mail with download link is on the way...

**Comment by vabene1111** [comment]
thank you, got it

**Comment by vabene1111** [comment]
ok just tested a large recipekeeper import, i think this was resovled in the meantime by some other fix because all 500 recipes worked correctly.
