### ISSUE TITLE
Drop-down list in merge editor stops at "C"

### ISSUE THREAD

**Issue by jchimene** [TandoorRecipes/recipes#2879]
### Tandoor Version

abf8f791360b2bc4a5c7d011877668679bcbb3f2

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Expected: All foods are displayed in drop-down list when attempting a merge
Actual: List goes from A - C

Tested in Firefox, Safari

Steps to reproduce:
1. Pick a food from the Food editor
2. Open Ingredient editor for that food
3. Select "merge"
4. Attempt to merge with a food whose name starts with any letter after "C"

**Comment by jchimene** [comment]
Version doesn't appear on the "System" page.
From GitHub, version is 1.5.10

**Comment by smilerz** [comment]
The drop down only lists the first 25(?) foods. You have to search for additional options.

**Comment by jchimene** [comment]
Nice! Thanks for the quick reply!
