### ISSUE TITLE
Unable to delete food when there is no recipe

### ISSUE THREAD

**Issue by jchimene** [TandoorRecipes/recipes#2880]
### Tandoor Version

HEAD

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Cannot delete incorrect food after import

Steps to reproduce:
1. Create some recipes using the import feature.
1. Clean up descriptive foods using "import and edit". For example, replace "Kosher Salt to taste" or "Ground Black pepper to taste" with either "Salt" or "Black Pepper".
1. Review Food list. Such descriptive foods as "Kosher Salt to taste" or "Ground Black pepper to taste" will not be associated with a recipe. Attempts to delete such descriptive foods fail. A toaster-style popup appears stating the food is still in an (unnamed) recipe.

Steps to reproduce:
1. Create some recipes via import.
1. Import and edit the recipes, cleaning up descriptive foods by replacing them with actual foods.
2. Observe that descriptive foods are not attached to any recipe.
1. Export recipes.
1. Delete all recipes.
1. Observe that descriptive foods created above are still attached to non-existent recipes.
1. Import recipes
3. Observe that descriptive foods created above are still attached to non-existent recipes.

**Comment by smilerz** [comment]
They are still attached to an ingredient. You can use admin to remove unattached steps and ingredients and it will alllow you to delete the food.

**Comment by jchimene** [comment]
Thanks for the quick reply! I will look more into admin.
