### ISSUE TITLE
Base template causes crash with 'WSGIRequest' object has no attribute 'space' at initial setup

### ISSUE THREAD

**Issue by ebwinters** [TandoorRecipes/recipes#2881]
### Issue

Hi - first time user looking to contribute! I am hitting the following issue after a clean setup using the contrib docs here: https://docs.tandoor.dev/contribute/#contributing-code

Verified using python 3.10, did successful pip install of all requirements, ran migrations and **was even able to load the sign up page and create a user**. After creating a user, I cannot get around this error when running server `python3 manage.py runserver`:

<img width="1015" alt="image" src="https://github.com/TandoorRecipes/recipes/assets/4297028/5a792dca-696f-4c90-8b83-36b207702611">

I noticed #2751  is very similar to my issue, and indeed the issue happens in the same file, at a different line.
The line in question is: `if request.space:`

### Tandoor Version

Latest code cloned from develop branch

### OS Version

Mac OS Monterey 12.3

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

**Comment by vabene1111** [comment]
I think this might not be a setup issue, I am not sure if I missed the edge case when building the new theme system.

The case would be signed in users that don't have a space yet. I can fix that easily but not sure when, will try to be quick

**Comment by vabene1111** [comment]
fixed on development branch

**Comment by ebwinters** [comment]
@vabene1111 awesome, thanks for the quick turnaround. Looking forward to picking up an issue

**Comment by vabene1111** [comment]
Thank you for trying to help, it would be great to get help on anything that is related to bug fixes especially on the front end

**Comment by ebwinters** [comment]
@vabene1111 I've created pr !2884
