### ISSUE TITLE
Edit Dialog in Import screen does not work

### ISSUE THREAD

**Issue by DanielHabenicht** [TandoorRecipes/recipes#2882]
### Tandoor Version

1.5.10

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

1. Go to the import site
2. Import a website e.g. https://www.chefkoch.de/rezepte/325861114877862/Maronenbraten-mit-Pilzen-und-Nuessen.html
3. Edit the first ingredient 
4. Try click the "Ok" Button
5. Nothing happens
![image](https://github.com/TandoorRecipes/recipes/assets/13590797/949cee48-b99c-4e6e-a0a4-db6ac6b954b3)

Also, there is no output in the console.

**Comment by smilerz** [comment]
The editor works but doesn't close after clicking ok. If you click off the modal you can continue importing as normal.

**Comment by vabene1111** [comment]
improved in next version
