### ISSUE TITLE
PostgreSQL 15: This application is not running with a Postgres database backend.

### ISSUE THREAD

**Issue by cl0rm** [TandoorRecipes/recipes#2883]
### Tandoor Version

Commit abf8f791360b2bc4a5c7d011877668679bcbb3f2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

pure nginx

### Bug description

I have upgraded from an older version (I think it was late Aug 2023) to the Dec2 build.
It didn't boot up because I was still using Postgres 11. I updated to 15 and migrated the db.
Now, everything works again, however the System Page states 

Info: not running postgres

However I clearly am.

I am passing
 - DB_ENGINE=django.db.backends.postgresql
to the container in my docker-compose (and it seems to have effect as the DB connection is established and the data are read)

This seems to be evaluated from cookbook/views.py

```python
    postgres = settings.DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql'
    if postgres:
        ...
    else:
        database_status = 'info'
        database_message = _(
            'This application is not running with a Postgres database backend. This is ok but not recommended as some features only work with postgres databases.')
```
something there seems to not work correctly

### Relevant logs

```shell
no relevant logs. The logs do not mention anything wrong with the DB
```

**Comment by smilerz** [comment]
Duplicate

**Comment by cl0rm** [comment]
duplicate of which issue. I can't find it?
