### ISSUE TITLE
v1.5.11: ModuleNotFoundError: No module named 'allauth.socialaccount.providers.keycloak'

### ISSUE THREAD

**Issue by Dominion0815** [TandoorRecipes/recipes#2890]
### Tandoor Version

1.5.11

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

since version 1.5.11 keycloak isn't supported?

Error message:
ModuleNotFoundError: No module named 'allauth.socialaccount.providers.keycloak'

**Comment by smilerz** [comment]
Upstream library [dropped support for keycloak](entryEditing_inital_servings: Number,).
