### ISSUE TITLE
Recipe Images Missing after Update to 1.5.11

### ISSUE THREAD

**Issue by davidancalagon** [TandoorRecipes/recipes#2896]
### Tandoor Version

1.5.11

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Half to 75% of all recipe images are now 404'd after an upgrade to 1.5.11 last night.  The images are present in the mediafiles/recipes folder with proper permissions, so I can only assume that the latest update broke something.

Log file simply shows similar to the following over and over:

[20/Jan/2024:16:20:50 -0500] "GET /media/recipes/ac2aad49-7bb7-4a4b-a24e-581abfb4cd3d_810.jpg HTTP/1.1" 404 21860 "http://192.168.1.204:8080/search/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

However, once I browse to the image directory, the referenced images are present and have been for months.

**Comment by smilerz** [comment]
How are you serving the media images?

**Comment by davidancalagon** [comment]
I'm not sure I understand the question.  When a recipe is put into the system, an image is uploaded and stored within the mediafiles/recipes directory in the docker container, which is bound to a directory on the docker host.  I access teh recipe web UI via a reverse proxy; however, I've tried this going straight to the IP:port and cutting out the NPM middleman without success.  Everything worked without issue until this latest update.

**Comment by smilerz** [comment]
Please share you env and compose.  If you have disabled gunicorn (default config) you have to setup a webserver of some kind to serve images.

**Comment by davidancalagon** [comment]
TZ=America/New_York
POSTGRES_PORT=30432
POSTGRES_USER=[REDACTED]
POSTGRES_DB=recipes
SECRET_KEY=[REDACTED]
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=192.168.1.254
POSTGRES_PASSWORD=[REDACTED]
DEBUG=0
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=C.UTF-8
GPG_KEY=[REDACTED]
PYTHON_VERSION=3.10.13
PYTHON_PIP_VERSION=23.0.1
PYTHON_SETUPTOOLS_VERSION=65.5.1
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/049c52c665e8c5fd1751f942316e0a5c777d304f/public/get-pip.py
PYTHON_GET_PIP_SHA256=7cfd4bdc4d475ea971f1c0710a5953bcc704d171f83c797b9529d9974502fcc6
PYTHONUNBUFFERED=1

gunicorn is not disabled in the env variables.  As I stated, these images have been working fine since I set up this app in docker months ago, but suddenly stopped after this update with no changes whatsoever to the configuration.  It was updated automatically by watchtower via docker.

**Comment by davidancalagon** [comment]
From the System page, under Debug, is this:

Gunicorn Media: False
Sqlite:  False 
        PostgreSQL: 14.09 
        Debug: False

Is there a way to activate this so that I don't have to set up a separate web server?  Why is it that half my images are showing and the other half are not right now, and that this only happened after the latest update?

**Comment by smilerz** [comment]
I believe gunicorn is disabled if not explicitly enabled.  You can confirm on the System page.

**Comment by smilerz** [comment]
> From the System page, under Debug, is this:
> 
> 
> 
> Gunicorn Media: False
> 
> Sqlite:  False 
> 
>         PostgreSQL: 14.09 
> 
>         Debug: False
> 
> 
> 
> Is there a way to activate this so that I don't have to set up a separate web server?  Why is it that half my images are showing and the other half are not right now, and that this only happened after the latest update?

GUNICORN_MEDIA=1 though this configuration isn't fully supported.

**Comment by davidancalagon** [comment]
My friend, your help is greatly appreciated.  GUNICORN_MEDIA=1 got it all back up and running.  Thanks!
