### ISSUE TITLE
Meal plan navigation broken in v1.5.11

### ISSUE THREAD

**Issue by bhdouglass** [TandoorRecipes/recipes#2897]
### Tandoor Version

1.5.11

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

The meal plan navigation buttons no longer work as of upgrading to v1.5.11. Both forward and backwards and the jump to date buttons have no effect. I tested this in both firefox and chrome on android. I'm happy to provide any further information needed. Thank you in advance!

Update: This does not appear to be an issue on my desktop Firefox.

**Comment by vabene1111** [comment]
should be fixed in the next version

**Comment by bhdouglass** [comment]
Wonderful, thank you!
