### ISSUE TITLE
Cannot add foods to Shoppinglist in Chrome on Smartphone in v1.5.11

### ISSUE THREAD

**Issue by KairaMiu** [TandoorRecipes/recipes#2901]
### Tandoor Version

v1.5.11

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Error message shown: 
![image](https://github.com/TandoorRecipes/recipes/assets/3818579/a60e459e-6390-4615-b7aa-e76cf952e641)

On other browser/environments:
- Chrome on PC works
- Firefox on Smartphone works
- Desktop website on Smartphone does NOT work

Is it intended, that there is no "not easy mode" to add ingredients on Smartphone? Neither in mobile view nor in desktop mode. I loved adding it this way :)
![image](https://github.com/TandoorRecipes/recipes/assets/3818579/c2209352-5436-424e-852f-ee647251aca2)

**Comment by vabene1111** [comment]
so i just set my instance to 1.5.11 and i can add in simple mode on my smartphone in chrome just fine. Can you set `DEBUG=1` in your env and check if there are any additional logs on the server or client that might provide more information ?

**Comment by KairaMiu** [comment]
No further logging with `DEBUG=1`. The only thing that is logged in the event of an error is the following:
```
{URL} - - [24/Jan/2024:18:21:07 +0100] "POST /api/shopping-list-entry/ HTTP/1.0" 400 108 "{DOMAIN}/list/shopping-list/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"`
```

When it works on the PC, the log looks like this::
```
{URL} - - [24/Jan/2024:18:25:43 +0100] "POST /api/ingredient-from-string/ HTTP/1.0" 200 57 "{DOMAIN}/list/shopping-list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
{URL} - - [24/Jan/2024:18:25:43 +0100] "POST /api/shopping-list-entry/ HTTP/1.0" 201 769 "{DOMAIN}/list/shopping-list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```

For some reason one post request is missing.
Strange that it doesn't happen to you. Could it be that I have configured something incorrectly?

**Comment by smilerz** [comment]
are there messages in the browswer console?

**Comment by KairaMiu** [comment]
Here the messages from android browser console:
```
shopping_list_view.b04e38106df8.js:1 started loading locale messages
shopping_list_view.b04e38106df8.js:1 finished loading messages in  7  ms
shopping-list/:437 service worker not in navigator
(anonymous) @ shopping-list/:437
load (async)
(anonymous) @ shopping-list/:429
shopping_list_view.b04e38106df8.js:1 [Violation] 'setInterval' handler took 55ms
chunk-vendors.ec4fffc9516b.js:1054 
        
        
       POST http://kairamiu.ddns.net:65153/api/shopping-list-entry/ 400 (Bad Request)
(anonymous) @ chunk-vendors.ec4fffc9516b.js:1054
xhr @ chunk-vendors.ec4fffc9516b.js:1054
ye @ chunk-vendors.ec4fffc9516b.js:1054
request @ chunk-vendors.ec4fffc9516b.js:1054
(anonymous) @ chunk-vendors.ec4fffc9516b.js:1054
(anonymous) @ api-chunk.3a50a6e89ddf.js:1
(anonymous) @ api-chunk.3a50a6e89ddf.js:1
Promise.then (async)
createShoppingListEntry @ api-chunk.3a50a6e89ddf.js:1
addEntry @ shopping_list_view.b04e38106df8.js:1
addItem @ shopping_list_view.b04e38106df8.js:1
wr @ chunk-vendors.ec4fffc9516b.js:1054
n @ chunk-vendors.ec4fffc9516b.js:1054
o._wrapper @ chunk-vendors.ec4fffc9516b.js:1054
```

**Comment by vabene1111** [comment]
interesting that the first request is missing, the first one takes the "simple input" and converts it into the proper ingredient. I have done so much work on shopping that I will not investigate this further until the new version has been released, if the problem still persists there we need to find out whats wrong here. 

Closing this for now, please reopen should this persist when the new shopping is released (1-2 month from now)
