### ISSUE TITLE
Changing the User Agent of the import request

### ISSUE THREAD

**Issue by WillemMe** [TandoorRecipes/recipes#2902]
### Is your feature request related to a problem? Please describe.

I was trying to import a recipe from a large Dutch supermarket Allerhande. But was not able to import the recipe. 
Through some digging I discovered that they were blocking robot like User Agents, one's that wget or curl would create. If supplied a more standard user agent it does work.

### Describe the solution you'd like

Possible environment variable to set a custom user agent.

### Describe alternatives you've considered

I would gladly implement this myself, but through some digging through the code I was not able to find which methods is called to do the requests

**Comment by smilerz** [comment]
the user agent is set by the recipes-scraper, the bookmarklet was created for this use case.

**Comment by WillemMe** [comment]
Thank you! I was not aware of the bookmarklet feature. They also seem to reject the recipes-scraper user agent. I'm wondering how their backwards compactibility is going.

**Comment by Calimerorulez** [comment]
Can someone help me, please?

I'm new to Tandoor, but I'm trying to import my first Allerhande recipe, but I'm getting a 500 error... Maybe it's related to this issue, but I can't seem to debug.

**Comment by smilerz** [comment]
> Can someone help me, please?
> 
> I'm new to Tandoor, but I'm trying to import my first Allerhande recipe, but I'm getting a 500 error... Maybe it's related to this issue, but I can't seem to debug.

That site works fine, please open a new issue providing all of the necessary logs and configurations to troubleshoot your problem.
