### ISSUE TITLE
Adding an item to the shopping list does not work anymore on mobile

### ISSUE THREAD

**Issue by andrin55** [TandoorRecipes/recipes#2904]
### Tandoor Version

1.5.11

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Adding a new item to the shopping list fails in a mobile browser with:
```
There was an error creating a resource!
{"food":["This field is required."],"ingredient":["Incorrect type. Expected pk value, received str."]}
```

This worked fine in the previous version and still works fine in a regular desktop browser.

Mobile Browser: Firefox 121.1.0 on Android 13

Interestingly, if the shopping list is viewed in a mobile browser, only a field "Food" is visible instead of the traditional "Count / Unit / Food" selection in previous versions:
![IMG_20240125_111740](https://github.com/TandoorRecipes/recipes/assets/2856476/2bde544f-8c53-49cf-996d-b6b532f97e39)

**Comment by smilerz** [comment]
duplicate #2901
