### ISSUE TITLE
import recipe from json not working

### ISSUE THREAD

**Issue by jjauzion** [TandoorRecipes/recipes#2907]
### Tandoor Version

1.5.11

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

cloudron

### Bug description

I'm trying to import recipe from a json file and it doesn't work. I don't have any error in the app but only the recipe title is imported.

I tried to export an existing recipe from Tandoor to get the valid json format Tandoor is using, then I copy paste the json into the import field in Tandoor (Import Recipe > Source) but it doesn't work neither.

Here is [an example](https://jsoneditoronline.org/#left=cloud.0542c7a4debb4880ae8181a751b08919) of a json file I exported from Tandoor(so good json format) and I can't import it back into Tandoor.

In the log there is an error (see below)

Any idea ? I tried to find the expected json format in the doc but I didn't find it

### Relevant logs

```shell
Jan 06 15:13:37Traceback (most recent call last):
Jan 06 15:13:37File "/app/code/tandoor/cookbook/helper/recipe_url_import.py", line 203, in get_from_scraper
Jan 06 15:13:37recipe_json['properties'] = get_recipe_properties(request.space, scrape.schema.nutrients())
Jan 06 15:13:37File "/app/code/.venv/lib/python3.10/site-packages/recipe_scrapers/_schemaorg.py", line 208, in nutrients
Jan 06 15:13:37for key, val in nutrients.copy().items():
Jan 06 15:13:37AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by tomtjes** [comment]
For me, importing json that is formatted according to [schema.org](https://schema.org/Recipe) work well. For importing the Tandoor format, you probably need to use the app import tab rather than the source import.

**Comment by smilerz** [comment]
JSON documents must match with ld+json format

**Comment by kaiffeetasse** [comment]
I have the exact same problem and even after exporting a recipe from Tandoor I am not able to import it:

```
recipes-web_recipes-1    | Traceback (most recent call last):
recipes-web_recipes-1    |   File "/opt/recipes/cookbook/helper/recipe_url_import.py", line 203, in get_from_scraper
recipes-web_recipes-1    |     recipe_json['properties'] = get_recipe_properties(request.space, scrape.schema.nutrients())
recipes-web_recipes-1    |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
recipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/recipe_scrapers/_schemaorg.py", line 208, in nutrients
recipes-web_recipes-1    |     for key, val in nutrients.copy().items():
recipes-web_recipes-1    |                     ^^^^^^^^^^^^^^
recipes-web_recipes-1    | AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by smilerz** [comment]
> I have the exact same problem and even after exporting a recipe from Tandoor I am not able to import it:
> 
> ```
> recipes-web_recipes-1    | Traceback (most recent call last):
> recipes-web_recipes-1    |   File "/opt/recipes/cookbook/helper/recipe_url_import.py", line 203, in get_from_scraper
> recipes-web_recipes-1    |     recipe_json['properties'] = get_recipe_properties(request.space, scrape.schema.nutrients())
> recipes-web_recipes-1    |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
> recipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/recipe_scrapers/_schemaorg.py", line 208, in nutrients
> recipes-web_recipes-1    |     for key, val in nutrients.copy().items():
> recipes-web_recipes-1    |                     ^^^^^^^^^^^^^^
> recipes-web_recipes-1    | AttributeError: 'NoneType' object has no attribute 'copy'
> ```

how are you trying to import an exported recipe?

**Comment by kaiffeetasse** [comment]
When I remove the "nutrition" part from the JSON I am able to get one step further and there are no errors in the log but then only the name of the recipe is visible and all steps / ingredients are missing

**Comment by smilerz** [comment]
> I tried both uploading the json file from the export in **App -> Tandoor -> Import** and also pasted the JSON directly under **Source -> Import** with the same result

The Tandoor import requires zip format.  Importing via source is for webpage or ld+json format only.

**Comment by smilerz** [comment]
are you trying to import to the same version of Tandoor the recipe was exported from?

There is no way currently to export to ld+json format.

**Comment by kaiffeetasse** [comment]
Yes, I am trying to import it to the exact same instance. I already tried with checking the "duplication prevention"-checkbox and also deleting the original recipe before, this won't make a difference.

**Comment by smilerz** [comment]
Please share the export and the version of Tandoor you are running.

**Comment by kaiffeetasse** [comment]
I am running Tandoor 1.5.17, commit f14acc371d7cf7ac7bcd6c1bd102f7d3c6a6b2b8

[export_2024-06-24.zip](https://github.com/user-attachments/files/15956922/export_2024-06-24.zip)

**Comment by smilerz** [comment]
that export doesn't have any data

**Comment by kaiffeetasse** [comment]
Sorry, it seems I attached the wrong one. The original export is now working but when I unzip and re-zip it, I get another error, apparently there is a problem with my zip but I guess thats another issue. Thanks!

```
recipes-web_recipes-1    | Traceback (most recent call last):
recipes-web_recipes-1    |   File "/opt/recipes/cookbook/integration/integration.py", line 161, in do_import
recipes-web_recipes-1    |     recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
recipes-web_recipes-1    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
recipes-web_recipes-1    |   File "/opt/recipes/cookbook/integration/default.py", line 17, in get_recipe_from_file
recipes-web_recipes-1    |     recipe_zip = ZipFile(file)
recipes-web_recipes-1    |                  ^^^^^^^^^^^^^
recipes-web_recipes-1    |   File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1341, in __init__
recipes-web_recipes-1    |     self._RealGetContents()
recipes-web_recipes-1    |   File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1408, in _RealGetContents
recipes-web_recipes-1    |     raise BadZipFile("File is not a zip file")
recipes-web_recipes-1    | zipfile.BadZipFile: File is not a zip file
recipes-web_recipes-1    | Traceback (most recent call last):
recipes-web_recipes-1    |   File "/opt/recipes/cookbook/integration/integration.py", line 161, in do_import
recipes-web_recipes-1    |     recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
recipes-web_recipes-1    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
recipes-web_recipes-1    |   File "/opt/recipes/cookbook/integration/default.py", line 17, in get_recipe_from_file
recipes-web_recipes-1    |     recipe_zip = ZipFile(file)
recipes-web_recipes-1    |                  ^^^^^^^^^^^^^
recipes-web_recipes-1    |   File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1341, in __init__
recipes-web_recipes-1    |     self._RealGetContents()
recipes-web_recipes-1    |   File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1408, in _RealGetContents
recipes-web_recipes-1    |     raise BadZipFile("File is not a zip file")
recipes-web_recipes-1    | zipfile.BadZipFile: File is not a zip file
```
