### ISSUE TITLE
iPad Air Gen1 Won’t Render Most Pages

### ISSUE THREAD

**Issue by archedraft** [TandoorRecipes/recipes#2908]
### Tandoor Version

Latest Commit: b0ca2ff228e26e4f22f5d613c81f2164076489eb

### Setup

Unraid

### Reverse Proxy

SWAG

### Bug description

commit b0ca2ff228e26e4f22f5d613c81f2164076489eb
Author: vabene1111 
Date:   Tue Jan 23 15:55:26 2024 +0100

Tandoor works perfectly from a computer browser or iPhone or newer iPads. On my original iPad Air Gen 1 with a screen resolution of 2048x1536, the top gold ribbon appears but the rest of the pages are just white. I can click to the different pages such as meal-plan, shopping or books and it goes to the pages but it’s all blank. The only page that does fully load is the system page. I’ve tried clearing all the cache and downloading a different web browser but the exact same thing happens on the other web browser. Any suggestions on how to get the page to fully render?

**Comment by smilerz** [comment]
Old versions of safari aren't computable with modern JavaScript functions.
