### ISSUE TITLE
Support for searching recipes name via Unicode Character Encoding

### ISSUE THREAD

**Issue by vh13294** [TandoorRecipes/recipes#2913]
### Is your feature request related to a problem? Please describe.

When I am using Unicode-encoding-character I can't search for it. The search result would be empty.

### Describe the solution you'd like

Is it possible to change the database format for the recipes name from ASCII to Unicode? 
I think it's the new standard now and Unicode is backward compatible with ASCII.

I think, in django you could do that by adding migration file [use utf-8 instead of ascii]

**Comment by vabene1111** [comment]
can you give an example of what you mean by unicode characters? because the field is already unicode and should work. 

What database are you using, please provide proper version/setup information

**Comment by vh13294** [comment]
So I normally add some symbols to my recipes names so that I can easily search for it.
I can give you a few example.

[Fried Chicken ✩✩]  (unicode dingbat font)

So when I type "✩✩" into the search box, it won't show up.

**Comment by vabene1111** [comment]
ok i think this might actually not be a problem of unicode support but of the search itself. There are quite a few options controlling search results to allow for fuzzy, trigram, full text and more. While that helps for many cases it has a negative effect on others. 

In the settings there is a page for search settings, you might try applying different presets or tuning the sliders a bit to get better results. Also there are some known issues with the search even without unicode characters that we are going to adress at some point but there sadly are a few other things ahead of that.

**Comment by vh13294** [comment]
Well, indeed it's a search algorithm settings.
I'll close the issue for now!

**Comment by vabene1111** [comment]
Can you tell me which settings you used to get it working for you?

**Comment by vh13294** [comment]
I turned on the fuzzy search and every bit of settings that allow the search to show more results rather than narrow it down.

**Comment by vabene1111** [comment]
Thanks
