### ISSUE TITLE
Automation not running on first ingredient

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#2927]
### Tandoor Version

1.5.12

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

A `food replace` automation (and possibly other types too) doesn't get applied to the first food in a recipe's ingredient list.

Steps to reproduce:
- create `food replace` automation with `parameter 1 = .*`, `parameter 2 = pasta`, `parameter 3 = potatoes`, `order=1`
- import recipe from source:

```
{
  "name": "Pasta",
  "recipeIngredient": [
    "200g pasta",
    "200g pasta",
    "200g pasta",
    "200g pasta"
  ],
  "recipeInstructions": [
    {
      "@type": "HowToStep",
      "text": "Cook the penne pasta in a large pot of boiling salted water until al dente, according to package instructions."
    }
  ]
}

```

result:
<img width="376" alt="Screenshot 2024-02-02 at 13 58 41" src="https://github.com/TandoorRecipes/recipes/assets/7606307/00532f74-9c38-47db-b2e8-aa3eb7148c1b">
Pasta has been replaced in all occasions except the first.

**Comment by vabene1111** [comment]
That is strange, will take a look, should probably also add a test not only for the individual parts but also some. Examples like this one

**Comment by vabene1111** [comment]
interesting, I could have sworn I reproduced this on the first test but its working fine for both food replace and food alias. 

![image](https://github.com/TandoorRecipes/recipes/assets/6819595/5c15fc06-1891-48af-8e52-7c4ac611f26c)

![image](https://github.com/TandoorRecipes/recipes/assets/6819595/3455f5df-e75b-4654-aca0-05bb7d0e4277)

Can you post a picture of your automation / try again to see if anything might be different? Automations do use caching to some degree so that must be taken into account.

**Comment by tomtjes** [comment]
Spun up a new instance: it works. On my production instance: still no luck.

**Comment by smilerz** [comment]
Are there other automations on pasta?

**Comment by tomtjes** [comment]
Pasta was just a simplified example after I noticed that a more complex automation didn't affect a first ingredient of a recipe.

Here's one that shouldn't interfere with anything else.

![Screenshot 2024-02-06 at 11 20 05](https://github.com/TandoorRecipes/recipes/assets/7606307/0d3a7684-198f-4217-a367-dc75b9f871f1)

```
{
  "name": "Pasta",
  "recipeIngredient": [
    "100g 123456",
    "200g 123456",
    "300g 123456",
    "400g 123456"
  ],
  "recipeInstructions": [
    {
      "@type": "HowToStep",
      "text": "Cook the penne pasta in a large pot of boiling salted water until al dente, according to package instructions."
    }
  ]
}
```

![Screenshot 2024-02-06 at 11 18 20](https://github.com/TandoorRecipes/recipes/assets/7606307/8940c595-1140-4a92-b8c2-349357ac6bc5)

Same result whether the order parameter is 100 or 9000.
