### ISSUE TITLE
Search doesn't work for all recipes

### ISSUE THREAD

**Issue by marmata** [TandoorRecipes/recipes#2929]
### Tandoor Version

1.5.12

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

### Bug description

When searching for a recipe, some recipes are not found. Here attached you can find:
* a view with some of the recipes I have.
* A search (Gateau) which doesn't return any result
* A search (Rotolo) which returns a result which is not in title (which is ok) but then
* A search (Cornetti) which doesn't return any result, altough the recipe is found when looking for "rotolo"
* A search that works (Amatriciana)
 
I would say probably 50% of the recipes have this issue
![2024-02-03 18_17_25-Cerca](https://github.com/TandoorRecipes/recipes/assets/3251511/42e82356-4807-4dc4-bcc0-d48dafd334c9)
![2024-02-03 18_15_12-Window](https://github.com/TandoorRecipes/recipes/assets/3251511/07d1791e-2170-4c7b-b13d-58aec281fb90)
![2024-02-03 18_15_02-Window](https://github.com/TandoorRecipes/recipes/assets/3251511/7edefc78-a02c-4afc-aa8a-e88b27b8c003)
![2024-02-03 18_14_37-Window](https://github.com/TandoorRecipes/recipes/assets/3251511/c38a5932-6ead-4a08-a582-60f03b9ad64c)
![2024-02-03 18_14_13-Window](https://github.com/TandoorRecipes/recipes/assets/3251511/771811f0-abe9-4546-8a15-2d152bd379e2)

**Comment by smilerz** [comment]
What are your search settings?

**Comment by marmata** [comment]
Here they below. Basically all blank.
However I then tried the Fuzzy preset and it's now working correctly  (altough i.e. rotolo doesn't find me the cornetti recipe anymore). But the old settings should work anyway right? What was I missing?
![2024-02-03 21_07_56-Settings](https://github.com/TandoorRecipes/recipes/assets/3251511/7584d543-e190-4126-b20f-3afa1b95a28f)
![2024-02-03 21_08_06-Settings](https://github.com/TandoorRecipes/recipes/assets/3251511/da68b228-9b6d-427c-866a-02a1079b3b28)

**Comment by smilerz** [comment]
As originally set it didn't search any fields.

**Comment by marmata** [comment]
Ok but then why something was found and something else not?

I'm Winston Wolf, I solve problems.
