### ISSUE TITLE
Foods and Units tables constantly fill up with low-quality entries from newly added recipes. Please change the handling of parsed ingredients to prevent this.

### ISSUE THREAD

**Issue by dchawisher** [TandoorRecipes/recipes#2934]
### Is your feature request related to a problem? Please describe.

I used the Open Data Import feature to populate my Foods and Units tables with good data: "Cauliflower," "Canola Oil," "tbsp," and so on. Then I used the web import to add a recipe for pork tenderloin. Now Tandoor thinks that:

- `black pepper` is something different from `Black Pepper`
- `to 1¼-pound pork tenderloins` is a kind of food
- `1-` is a unit of measure

I can't simply ignore these entries because they show up in dropdowns. I can get rid of them using a merge rule, but the next time I add a recipe there will be new ones (maybe the next recipe will call for `1¼- to 1½-pound pork tenderloins`, and Tandoor will interpret `1¼-` as a new unit of measure and `to 1½-pound pork tenderloins` as a new kind of food.

This is frustrating because although Tandoor's Foods and Units tables enable some of its coolest features, like substitutions and mass-to-volume conversions, the tendency of those tables to fill up with garbage entries makes them essentially unusable.

A related problem is that when Tandoor's recipe interface parses an ingredient incorrectly, that impacts the usability of the recipe. For example, the ingredient's actual name might be hidden in a comment, or the units might not display correctly. In those cases it would generally be better to display that ingredient's original text without adding any special formatting.

### Describe the solution you'd like

Bad ingredient parsing should not make a recipe harder to read or edit. When a recipe is imported, or when an ingredient is manually added, Tandoor should not create 'Food' and 'Unit' table entries automatically. Ingredients should be treated as lines of plaintext rather than as structured data until the structured data is confirmed to be high-quality, in whole or in part, by (a) the user manually matching the ingredients to existing foods and units, (b) automatic matching of the ingredient against existing foods, or ideally (c) some combination of those.

### Ideal Solution

The ideal solution would go like this. Say I import a recipe for scrambled eggs that calls for "1 pat butter," "2 jumbo eggs," "crème fraîche," and "1 tin caviar". Tandoor parses these ingredients by comparing them to my existing foods library. Other than applying some fairly simple rules (e.g. "bread, white" matches "white bread"), it requires strict matches, which works as follows:

- I have `Butter` in my foods table and `Pat` in my units table, so "1 pat butter" parses automatically.
- I have `Egg` in my foods table, but "jumbo" is new, so "2 eggs" parses and "jumbo" goes into the comments field.
- I have `Creme Fraiche` in my foods table, so "crème fraîche" parses automatically, despite the accents.
- I don't have `Caviar` in my foods table or `tin` in my units table. "1 tin caviar" is treated as plain text.

There are a number of edge cases and several defensible ways of handling them. To return to the example of "1 pat butter," suppose I don't have a unit that matches `pat`. One possibility is to put "pat" in the comments field. Another is to display the ingredient as plaintext until the entire thing is manually parsed into quantity/unit/food/comment form. Or Tandoor could assume that everything between the quantity and the food (in this case, "pat") is a unit (again, **without** creating an entry in the Units table) and everything after the food is a comment. As long as there is a clear visual indication of what has been matched to what, and matching mistakes are easily corrected, any of these approaches would be fine.

Another edge case would relate to foods like "salt" or "sugar" that are often contained in the names of other ingredients (for instance, "salt flakes" or "brown sugar"). For those foods the best solution might be a stricter matching mode activated on a per-food basis.

### An Easier Solution

Add an option to disable or sharply limit Food and Unit parsing. Let us enter ingredients as text without messing with dropdowns. Treat each ingredient line item as plaintext for grocery shopping. 

There are some straightforward bells and whistles that would be nice, like a heuristic to identify the quantity number for ingredients scaling (just use the first number, delimited by spaces, -, etc.) and a heuristic for grocery aisle sorting (based on Open Data Import). But even a pure plaintext approach would be more usable on a day-to-day basis than the current situation.

### Additional context

My current recipe manager, Paprika, does this very well. It uses some very simple heuristics to identify the quantity component of each ingredient (for ingredient scaling) and has a list of common foods and the grocery aisles they are found in (for organizing shopping lists), and has an imperial-to-metric conversion that is pretty good at identifying common units. But it displays ingredients as plaintext, and the ingredients of one recipe do not affect any other recipe. This makes Paprika less powerful than Tandoor in some cases, but it also makes Paprika reliably usable in a way that Tandoor currently is not.

**Comment by smilerz** [comment]
There are a number of capabilities available to manage foods and units including merging and automations.

**Comment by dchawisher** [comment]
> There are a number of capabilities available to manage foods and units including merging and automations.

I realize this. I mentioned these features in my issue. As I noted, merges and automations are inadequate to solve the problem, since they apply to specific foods and specific units, and nonstandardized inputs are, by their nature, nonstandardized. As I said in the issue:

> I can get rid of [the low-quality entries] using a merge rule, but the next time I add a recipe there will be new ones (maybe the next recipe will call for 1¼- to 1½-pound pork tenderloins, and Tandoor will interpret 1¼- as a new unit of measure and to 1½-pound pork tenderloins as a new kind of food.)

**Comment by smilerz** [comment]
Parsing ingredients is a non-trivial task, especially in a language agnostic way.  The methods that you mention aren't feasible or simply create a new set of problems.

**Comment by dchawisher** [comment]
I agree that parsing ingredients is non-trivial. I would describe it as aggressively non-trivial. That is why it makes little sense to parse everything by default and to allow incorrectly parsed ingredients to be a usability problem.

**Comment by vabene1111** [comment]
thanks for the detailed post explaining your problem. This issue has existed for a long time and is perfectly clear to me. I thought about different solutions over the years, like yours or like for example adding a "strict" mode but all of them have their issues (e.g. what to do with batch imports). 

In the end I have yet to find a solution that solves all of the problems thats why nothing has been implemented yet. Everyone is welcome to propose solutions but they have to take every different kind of user (tech savy to first time user/"grandma" and feature (single import, batch import, source import, app import, bookmarklet import, normal use of the parser, UI for mobile, UI for desktop, ...) into account.

**Comment by dchawisher** [comment]
Thanks for explaining your reasoning, @vabene1111 . How about this: Disable the dropdowns for unit and ingredient entry. Replace them with an autocomplete that only shows once the user has typed several characters, whether they are editing the text of an existing ingredient or adding a new ingredient to the list. 

That gets us about 70% of the way there, and in general it would be a big usability improvement, even putting aside the problem of garbage food and unit entries. If I click on an ingredient like `to 1¼-pound pork tenderloins`, I expect to be able to simply delete the text `to 1¼-pound` rather than getting a dropdown. Instead having the field cleared and replaced with a dropdown of all of my foods is not useful:
![image](https://github.com/TandoorRecipes/recipes/assets/22660616/5d07f9ed-b0bd-4dd2-992d-9830bca9abea)
![image](https://github.com/TandoorRecipes/recipes/assets/22660616/d3a40212-3248-4ed6-b0f7-e7aade296e9f)

another change that would get us to 95%, without losing any functionality: track whether a Food or Unit has ever been manually edited (i.e. created by Open Data import or created/modified using the Foods or Units interface rather than the Recipe interface), and treat items differently if they have been. If we say that items that have been manually edited are High Quality entries, Tandoor could:

- Show only High Quality entries in the relevant autocompletes.
- Let us "clean up" the Foods and Units tables by deleting all non–High Quality entries that are not currently used in any recipes. (automatically would be ideal, but even a "clean up" button on the Foods and Units pages would be helpful.)

Both of those changes seem like they would be relatively straightforward. (I could definitely be wrong about that—I don't mean to be insulting.) Further down the road, it could be possible to let us create automations that apply specifically to non–High Quality foods (e.g., if the name contains "salt," sort it in the "spices" aisle on grocery lists.) But this is very much a "nice to have" rather than a major usability improvement.

**Comment by vabene1111** [comment]
thanks for the feedback, I will come back to this as it is something that annoys me too, just now sure when.

**Comment by timsschoen** [comment]
In a similar vein, why isn't there a dropdown of known foods in the import dialogue when clicking on an ingredient and manually changing the food?

I just went through the experience of wanting to avoid the issue presented in this thread, by importing a recipe and then going through each item in the import dialogue. I still now have duplicates, because I was unable to perfectly match some foods with typing them into the dialogue. Maybe this would be a first step for solving this issue?
