### ISSUE TITLE
Export recipe from 1.2.7 to 1.5.10 does not work

### ISSUE THREAD

**Issue by Phil997** [TandoorRecipes/recipes#2946]
### Issue

Hello I want to move all my recipes from one server to my new server. There I have the version 1.5.10 and in the old one 1.2.7.

The export work, i can export all recipes in a .zip file and have many folders which are .zip files, too with the recipe.json and the image. But the import does not work.

* When i go in + import -> Source and paste the content from the recipe.json there, i get this error: `There was an error importing the recipe!`
* When i go go + import -> App, select Tandoor and browser for the file i get redirected to the next page where i get the information 0 from 0 recipes imported with this error: `ERROR An unexpected error occurred during the import. Please make sure you have uploaded a valid file. Imported 0 recipes. `

What should I do?, the documentation is not very helpful.

This is my recipe.json:
```json
{"name":"Rotkohl","description":"","keywords":[{"name":"gemüse","icon":null,"description":"","created_at":"2022-06-11T17:06:09.717117+02:00","updated_at":"2024-01-13T15:55:59.963190+01:00"}],"steps":[{"name":"","instruction":"Den Rotkohl klein schneiden und mit den restlichen Zutaten gut vermengen. \n  \nÜber Nacht ziehen lassen.\n\nIm Schnellkochtopf ca. 10 Minuten kochen oder ca. 1 Stunde im normalen Topf.","ingredients":[{"food":{"name":"Rotkohl","ignore_shopping":false,"supermarket_category":null},"unit":{"name":"kg","description":null},"amount":1.0,"note":"","order":0,"is_header":false,"no_amount":false},{"food":{"name":"Zucker","ignore_shopping":false,"supermarket_category":null},"unit":{"name":"g","description":null},"amount":125.0,"note":"","order":1,"is_header":false,"no_amount":false},{"food":{"name":"Salz","ignore_shopping":false,"supermarket_category":null},"unit":{"name":"TL","description":null},"amount":1.0,"note":"","order":2,"is_header":false,"no_amount":false},{"food":{"name":"Apfelessig","ignore_shopping":false,"supermarket_category":null},"unit":{"name":"ml","description":null},"amount":180.0,"note":"","order":3,"is_header":false,"no_amount":false},{"food":{"name":"Gewürznelke(n)","ignore_shopping":false,"supermarket_category":null},"unit":null,"amount":4.0,"note":"","order":4,"is_header":false,"no_amount":false},{"food":{"name":"Lorbeerblätter","ignore_shopping":false,"supermarket_category":null},"unit":null,"amount":2.0,"note":"","order":5,"is_header":false,"no_amount":false}],"time":0,"order":0,"show_as_header":true}],"working_time":15,"waiting_time":1080,"internal":true,"nutrition":null,"servings":4,"servings_text":"servings"}
```

When my .json has a uncorrect format, how i can export i correctly?

### Tandoor Version

1.5.10

### OS Version

vabene1111/recipes:1.5.10

### Setup

Kubernetes

### Reverse Proxy

Others (please state below)

### Other

Nginx ingress controller

**Comment by smilerz** [comment]
Imports are sticky to the version - you have to import to Tandoor 1.2.7.

**Comment by Phil997** [comment]
What is the best way to transfer recipes from an older version of the app to a new version?

**Comment by smilerz** [comment]
export/import database.  Either by exporting from source, importing then upgrading or upgrading, exporting then importing.
