### ISSUE TITLE
public/shared recipes / data exchange

### ISSUE THREAD

**Issue by hcientist** [TandoorRecipes/recipes#295]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
Perhaps I could mark data in my instance as `public` or `publishable` or something and these items would be available for all other instances to import them?

**Describe alternatives you've considered**
There could be many ways to do it, including a completely separate project that doesn't muddy the aim of this one, but that maybe tried to use the data model here as a standard. Anyway, I think it'd be neat for people to be able to share books, recipes, or even smaller data entries across instances.

**Additional context**
N/A

**Comment by vabene1111** [comment]
i like the idea. There has been a request for public setups for a while but a lot of work needs to be done in the permission handling system to actually properly seperate different kinds of access levels. 

After that some kind of federation system can be implemented.

**Comment by vabene1111** [comment]
not part of the application scope for now and the forseeable future but i will keep this idea in mind, just closing because its too far away
