### ISSUE TITLE
Can't import en or other community data (There was an error creating a resource!)

### ISSUE THREAD

**Issue by Routout** [TandoorRecipes/recipes#2952]
### Issue

Only en-US import is working. Is it me or something else?

### Tandoor Version

1.5.13

### OS Version

Proxmox 8.1.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

**Comment by Routout** [comment]
Got this when trying to import en data

`ValueError: Field 'fdc_id' expected a number but got '170931-ground'.
::ffff:192.168.1.102 - - [17/Feb/2024:13:32:29 +0100] "POST /api-import-open-data/ HTTP/1.1" 500 261056 "http://192.168.1.199:82/space-manage/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"`

**Comment by smilerz** [comment]
Duplicate #2514
