### ISSUE TITLE
Hello Fresh recipes

### ISSUE THREAD

**Issue by rsch136** [TandoorRecipes/recipes#2954]
### Tandoor Version

1.5.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

When importing recipes from hellofresh.de, all ingredients are imported as "2 * amount-unit-ingredient", instead of "amount unit ingredient"
![image](https://github.com/TandoorRecipes/recipes/assets/44471683/00a6c106-9361-48cf-9ee1-21b808e23e4e)

The recipe scraper returns the ingredients like this:
![image](https://github.com/TandoorRecipes/recipes/assets/44471683/1a5729bf-d3e0-40ef-b270-f4e5d99ea05d)

Hello Fresh is the only site that I've used that has this issue. This is the URL: https://www.hellofresh.de/recipes/honig-teriyaki-burger-mit-scharfer-mayo-613f11cc9d6c9a4b7c2c3f6a

**Comment by smilerz** [comment]
Can you update the description to include the page you are importing from. Thanks.

**Comment by rsch136** [comment]
@smilerz Sure! Have added it.

**Comment by smilerz** [comment]
Do you have any automations setup?

![image](https://github.com/TandoorRecipes/recipes/assets/1808639/519163c8-11f5-43f7-a91d-73461993142a)

**Comment by rsch136** [comment]
I have some "merge & automate" for individual ingredients. What version are you using? I can update if you think that might fix the problem.

**Comment by smilerz** [comment]
I tried in both the latest release and the develop branch.  The odds that this is a bug in tandoor/any version are basically zero. 

Double check your automations and make sure there aren't any regex automations.

**Comment by rsch136** [comment]
OK. I'm not sure what a regex automation is. The automations were all created using the (experimental) "Merge & Automate" feature and look like this: 
![image](https://github.com/TandoorRecipes/recipes/assets/44471683/da473421-8fc1-478f-946f-301103385620)
I'm going to try to use the API to delete all of them just to see if that helps.

**Comment by rsch136** [comment]
Instead of deleting the automations, I disabled them. However, this did not affect the import at all and I am still having the same issue. I've also tried using different browsers, but I also do not see any error messages in the dev tools.

**Comment by smilerz** [comment]
You won't see anything in the browser, this all happens at the back end. 

You can try upgrading to the current version.  But I can't think of any code that would change strings in that way.

**Comment by rsch136** [comment]
Quick update: I've been trying to update the version but there were at least two breaking changes between version 1.5.4 and current (1.5.13) so it's been slow going.

I agree that it probably won't help because I think the problem already existed before I updated to 1.5.4 but it's worth a try. Once the update is through (but doesn't help), I'll delete the automations an try that

**Comment by smilerz** [comment]
Besides the postgres upgrade - what other breaking change is there?

**Comment by rsch136** [comment]
Updating to latest (1.5.13) fixed the issue for me. Might not have been the update though. I also got the DuplicateMealType error when updating the DB: https://github.com/TandoorRecipes/recipes/issues/2939
I also have not re-enabled the automations yet.
But! It works now and that's the best 😄

**Comment by smilerz** [comment]
glad it got resolved!
