### ISSUE TITLE
Search parameter `new=true` doesn't work

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#2962]
### Tandoor Version

 1.5.13

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

In search, it doesn't make a difference whether `new=true` or `new=false` is set. After the defined number of recently accessed recipes, the list continues with recipes in alphabetical order.

### Relevant logs

```shell
log only shows API requests, no errors.


::ffff:172.18.0.4 - - [20/Feb/2024:02:51:20 +0100] "GET /api/recipe/?query=&internal=false&random=false&new=true&page=1&page_size=25&include_children=true&num_recent=5 HTTP/1.0" 200 20145 "http://redacted/search/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
::ffff:172.18.0.4 - - [20/Feb/2024:02:51:20 +0100] "GET /static/webfonts/poppins_latin_700.woff2 HTTP/1.0" 304 0 "http://redacted/search/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
::ffff:172.18.0.4 - - [20/Feb/2024:02:51:20 +0100] "GET /static/assets/recipe_no_image.svg HTTP/1.0" 304 0 "http://redacted/search/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
::ffff:172.18.0.4 - - [20/Feb/2024:02:51:20 +0100] "GET /api/user-preference/1/ HTTP/1.0" 200 654 "http://redacted/search/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
::ffff:172.18.0.4 - - [20/Feb/2024:02:51:26 +0100] "GET /static/assets/recipe_no_image.svg HTTP/1.0" 304 0 "http://redacted/search/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
```

**Comment by smilerz** [comment]
the new parameter works as expected - recipes created within 7 days show up first, then the remainder of the list shows up as normal.

**Comment by tomtjes** [comment]
Ah my bad, I misunderstood what it's supposed to do

**Comment by smilerz** [comment]
> Ah my bad, I misunderstood what it's supposed to do

what were you expecting?

**Comment by tomtjes** [comment]
Or did I? In the UI the parameter is called `Sort by new` if I'm not mistaken. Maybe rename it `Recently added`?
<img width="287" alt="Screenshot 2024-02-19 at 21 57 17" src="https://github.com/TandoorRecipes/recipes/assets/7606307/55b5402d-7624-4c7a-854f-e20547890f45">

**Comment by smilerz** [comment]
Maybe 'show recently added first'

**Comment by tomtjes** [comment]
Yeah, except they're not shown first when you also have `recently viewed` set to non-zero.

Yes, I use that dropdown frequently. But I'm annoyed by the default view which shows me 5 recently viewed recipes as configured and then always the same set of recipes that happened to be first in the alphabet. What I actually want is to set a default search order that still shows recently viewed first.

**Comment by smilerz** [comment]
I think there is a feature request somewhere to allow for setting a default sort order.  At the very least it's on my personal backlog of enhancements.
