### ISSUE TITLE
recipe names not visible in plan view using superman theme

### ISSUE THREAD

**Issue by anytimesoon** [TandoorRecipes/recipes#2971]
### Tandoor Version

1.5.13

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

Recipe names are difficult to read in the plan view using the superman theme on desktop. See screenshot below

![Screenshot from 2024-02-22 22-12-13](https://github.com/TandoorRecipes/recipes/assets/22013119/8a5f0596-4f0d-44d6-99d3-00e0d2c09a4f)

Probably due to the containing `span` having the `font-light` class.

**Comment by vabene1111** [comment]
thanks, we are currently migrating to vue3 in the frontend which will remove the superman theme as it currently is. Thus I am closing this as there will be no more updates for the old frontend.
