### ISSUE TITLE
Unit in plural is no longer available

### ISSUE THREAD

**Issue by Thulkash** [TandoorRecipes/recipes#2973]
### Tandoor Version

1.5.12

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

We can't edit anymore the plural for units. It was possible before.
![image](https://github.com/TandoorRecipes/recipes/assets/46101710/68e90ccb-c057-483a-94d7-02558b39affb)
![image](https://github.com/TandoorRecipes/recipes/assets/46101710/3413043f-61c3-4498-824a-3b73c5b8c69c)

**Comment by vabene1111** [comment]
fixed in next release

**Comment by Thulkash** [comment]
Thanks!
