### ISSUE TITLE
works fine with firefox nightly but not with chrome

### ISSUE THREAD

**Issue by BPplays** [TandoorRecipes/recipes#2981]
### Issue

on the same url for both. ive restarted chrome and cleared site data

on chrome it says:
There was an error updating a resource!
{"detail":"CSRF Failed: CSRF token from the 'X-Csrftoken' HTTP header incorrect."}

on chrome in the logs for tandoor it says:
Forbidden: /api/food/
::ffff:192.168.96.1 - - [26/Feb/2024:06:13:01 -0800] "POST /api/food/ HTTP/1.1" 403 82 "https://tandoor.MY_CENSORED_DOMAIN.TLD/list/food/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

but on firefox in the logs for tandoor it says:
::ffff:192.168.96.1 - - [26/Feb/2024:06:14:02 -0800] "GET /api/food-inherit-field/ HTTP/1.1" 200 267 "https://tandoor.MY_CENSORED_DOMAIN.TLD/list/food/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
::ffff:192.168.96.1 - - [26/Feb/2024:06:14:02 -0800] "GET /api/supermarket-category/?query= HTTP/1.1" 200 2 "https://tandoor.MY_CENSORED_DOMAIN.TLD/list/food/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
::ffff:192.168.96.1 - - [26/Feb/2024:06:14:02 -0800] "GET /api/unit/?query=&page=1&page_size=25&simple=1 HTTP/1.1" 200 52 "https://tandoor.MY_CENSORED_DOMAIN.TLD/list/food/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
::ffff:192.168.96.1 - - [26/Feb/2024:06:14:02 -0800] "GET /api/recipe/?query=&page=1&page_size=25&simple=1 HTTP/1.1" 200 387 "https://tandoor.MY_CENSORED_DOMAIN.TLD/list/food/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
::ffff:192.168.96.1 - - [26/Feb/2024:06:14:02 -0800] "GET /api/food/?query=&root=0&page=1&page_size=25&simple=1 HTTP/1.1" 200 132 "https://tandoor.MY_CENSORED_DOMAIN.TLD/list/food/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
::ffff:192.168.96.1 - - [26/Feb/2024:06:14:02 -0800] "GET /api/food-inherit-field/ HTTP/1.1" 200 267 "https://tandoor.MY_CENSORED_DOMAIN.TLD/list/food/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
::ffff:192.168.96.1 - - [26/Feb/2024:06:14:05 -0800] "POST /api/food/ HTTP/1.1" 201 454 "https://tandoor.MY_CENSORED_DOMAIN.TLD/list/food/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"

### Tandoor Version

1.5.13

### OS Version

Linux (debian 12)

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

**Comment by smilerz** [comment]
please share your env, compose file and the list of headers list in DEBUG at /system

**Comment by BPplays** [comment]
the .env has just in the docs i have other custom stuff in the .env for variables like folder locations for bind mounts too
.env:
# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
SECRET_KEY=censored

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_DB=djangodb
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=censored

ALLOWED_HOSTS=*
TANDOOR_PORT=14330

CORS_ALLOW_ALL_ORIGINS=1

CSRF_TRUSTED_ORIGINS = [https://*.MY_CENSORED_DOMAIN.TLD]



# ldap
LDAP_AUTH=1
# AUTH_LDAP_SERVER_URI=ldaps://ipa1.MY_CENSORED_DOMAIN.TLD:636
AUTH_LDAP_SERVER_URI=ldap://ipa1.MY_CENSORED_DOMAIN.TLD:389
AUTH_LDAP_BIND_DN=uid=generic_ldap_bind,cn=users,cn=accounts,dc=censored,dc=org
AUTH_LDAP_BIND_PASSWORD=U9XdrC3X3jdTRuiShWHvfN7JeCk3ZgvL7dTPMWZg3NuSuAEqdPzKiy8r8L6wW3B7
AUTH_LDAP_USER_SEARCH_BASE_DN=cn=users,cn=accounts,dc=censored,dc=org

AUTH_LDAP_USER_SEARCH_FILTER_STR=(uid=%(user)s)
AUTH_LDAP_USER_ATTR_MAP={'first_name': 'givenName', 'last_name': 'sn', 'email': 'mail'}
AUTH_LDAP_ALWAYS_UPDATE_USER=1
AUTH_LDAP_CACHE_TIMEOUT=3600

docker-compose.yml:
version: "3"
services:
  db_recipes:
    restart: always
    # image: postgres:15-alpine
    image: postgres:15
    user: "0:0"
    volumes:
      - ${DOCKER_VOLUMES_FOLDER}/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - UID=0
      - GID=0
      - TZ=${GLOBAL_TZ}
      

  web_recipes:
    restart: always
    image: vabene1111/recipes
    ports:
      - 14330:14330
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ${DOCKER_VOLUMES_FOLDER}/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    environment:
      - UID=0
      - GID=0
      - TZ=${GLOBAL_TZ}

  # nginx_recipes:
  #   image: nginx:mainline-alpine
  #   restart: always
  #   ports:
  #     - 14330:80
  #   env_file:
  #     - ./.env
  #   environment:
  #     - UID=0
  #     - GID=0
  #     - TZ=${GLOBAL_TZ}
  #   depends_on:
  #     - web_recipes
  #   volumes:
  #     # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
  #     - nginx_config:/etc/nginx/conf.d:ro
  #     - staticfiles:/static:ro
  #     - ${DOCKER_VOLUMES_FOLDER}/tandoor/mediafiles:/media:ro

volumes:
  nginx_config:
  staticfiles:


debug:
Gunicorn Media: False
Sqlite:  False 
        PostgreSQL: 15.06 
        Debug: True

SERVER_PROTOCOL:HTTP/1.1
REMOTE_ADDR:::ffff:192.168.112.1
SERVER_PORT:14330

HTTP_CONNECTION:close
HTTP_HOST:tandoor.MY_CENSORED_DOMAIN.TLD
HTTP_X_FORWARDED_FOR:192.168.1.50
HTTP_X_FORWARDED_HOST:tandoor.MY_CENSORED_DOMAIN.TLD
HTTP_X_FORWARDED_METHOD:GET
HTTP_X_FORWARDED_PORT:443
HTTP_X_FORWARDED_PROTO:https
HTTP_X_FORWARDED_SERVER:tandoor.MY_CENSORED_DOMAIN.TLD
HTTP_X_FORWARDED_SSL:on
HTTP_X_FORWARDED_URI:/system/
HTTP_X_ORIGINAL_METHOD:GET
HTTP_X_ORIGINAL_URL:https://tandoor.MY_CENSORED_DOMAIN.TLD/system/
HTTP_X_REAL_IP:192.168.1.50
HTTP_SEC_CH_UA:"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"
HTTP_SEC_CH_UA_MOBILE:?0
HTTP_SEC_CH_UA_PLATFORM:"Windows"
HTTP_UPGRADE_INSECURE_REQUESTS:1
HTTP_DNT:1
HTTP_USER_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
HTTP_SEC_FETCH_SITE:same-origin
HTTP_SEC_FETCH_MODE:navigate
HTTP_SEC_FETCH_USER:?1
HTTP_SEC_FETCH_DEST:document
HTTP_REFERER:https://tandoor.MY_CENSORED_DOMAIN.TLD/search/
HTTP_ACCEPT_ENCODING:gzip, deflate, br
HTTP_ACCEPT_LANGUAGE:en-US,en;q=0.9,ja;q=0.8
HTTP_SEC_GPC:1
HTTP_COOKIE:csrftoken=KYlqfF0Q8fK72zS8zf5wWTlKnraBn7yi; csrftoken=ULkywFSPArNbK11NSNr8KVsvtDvbf4Zp; sessionid=s3c8yeeb44q1su1y8dmprj2k7elr90f2

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fb6820c3580>
wsgi.version:(1, 0)
wsgi.multithread:True
wsgi.multiprocess:True
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x7fb6820c2e30>
wsgi.url_scheme:http

**Comment by smilerz** [comment]
I can't recreate the issue.  What else is unique about your setup?

The only thing that looks suspicious is you have two csrf tokens

`csrftoken=KYlqfF0Q8fK72zS8zf5wWTlKnraBn7yi; csrftoken=ULkywFSPArNbK11NSNr8KVsvtDvbf4Zp;`

**Comment by BPplays** [comment]
> The only thing that looks suspicious is you have two csrf tokens

thats what i ment by "it seems to have set more then one"

clearing my cookies fixed that, it works now.
i was having some trouble getting it set up with my reverse proxy so maybe that caused some weirdness before i fixed it.
