### ISSUE TITLE
PlantoEat Import prep/cooktime + structure header becomes ingredient

### ISSUE THREAD

**Issue by cgiacofei** [TandoorRecipes/recipes#2982]
### Tandoor Version

1.5.13

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

When importing from Plan to Eat, the `Prep Time` and `Cook Time` fields are not being pulled in. Instead they are included in the recipe directions.

Also the `Directions:` text in the export file that notes the beginning of recipe steps is being included as an ingredient at the end of the list.

Sample Recipe to Import:
```
Title: Grandmother’s Buttermilk Cornbread
Serves: 1
Source: https://www.allrecipes.com/recipe/76594/grandmothers-buttermilk-cornbread/
Photo Url: https://plantoeat.s3.amazonaws.com/recipes/27505371/3828bbb4b3b6121756bc1fa136e0b7cd54409b6c-original.jpg?1612965286
Prep Time: 15 Min
Cook Time: 40 Min
Course: Breads
Ingredients:
1/2 cup butter
2/3 cup white sugar
2 eggs
1 cup buttermilk
1/2 teaspoon baking soda
1 cup cornmeal
1 cup all-purpose flour
1/2 teaspoon salt
Directions:
Preheat oven to 375 degrees F (175 degrees C). Grease an 8 inch square pan.
Melt butter in large skillet.
Remove from heat and stir in sugar.
Quickly add eggs and beat until well blended.
Combine buttermilk with baking soda and stir into mixture in pan.
Stir in cornmeal, flour, and salt until well blended and few lumps remain.
Pour batter into the prepared pan.
Bake in the preheated oven for 30 to 40 minutes, or until a toothpick inserted in the center comes out clean.
```

**Comment by vabene1111** [comment]
thanks for the report, to be honest I am not the best at writing parsers for these kinds of structured text, also these formats tend to be somewhat soft in definition, but I will look into improving this (or anyone who knows a bit of python can if they want :) )

**Comment by smilerz** [comment]
> Where is the relevant code for this? I'd be happy to take a look if I can find some free time.

`cookbook/integration/plantoeat.py`

**Comment by ellezhu1** [comment]
Is this still free to work on? I have some experience with Python and parsing.

**Comment by smilerz** [comment]
> Is this still free to work on? I have some experience with Python and parsing. 

Feel free to submit a PR
