### ISSUE TITLE
"option" Ingredient type

### ISSUE THREAD

**Issue by BPplays** [TandoorRecipes/recipes#2986]
### Is your feature request related to a problem? Please describe.

some recipes have an option in the Ingredients such as 'Filling of choice' in [Wikibooks Onigiri](https://en.wikibooks.org/wiki/Cookbook:Onigiri).

### Describe the solution you'd like

i would like to be able to add an 'option' in the Ingredients list with available options that you can add and then can choose from a drop-down menu when you are viewing the recipe

**Comment by deflucaseng** [comment]
Would it be possible for me to work on this?

-L

**Comment by vabene1111** [comment]
given the already immense technical complexity of tandoor I will not implement/merge this feature at this point. I do see the usefulness but currently that is not an options (especially since it brings a lot of complexity with shopping, properties, ...)
