### ISSUE TITLE
import collections

### ISSUE THREAD

**Issue by snickers2k** [TandoorRecipes/recipes#3017]
### Is your feature request related to a problem? Please describe.

would be great to have the ability to import whole collections into tandoor for supported sites

https://www.chefkoch.de/rezeptsammlung/896538/Auflaeufe.html
for example

### Describe the solution you'd like

"one-click" import for collections

### Describe alternatives you've considered

importing hundreds of favorite recipes by "hand" (bookmarklet)

**Comment by smilerz** [comment]
site scraping is handled by https://github.com/hhursev/recipe-scrapers
