### ISSUE TITLE
Missing `libldap-dev` (and other system dependencies) in Contributing guide

### ISSUE THREAD

**Issue by frereit** [TandoorRecipes/recipes#3022]
### Documentation link

https://docs.tandoor.dev/contribute/#django

### Affected section

Other (please state below)

### Other

Contributing

### Issue description

The Django installation / dev setup instructions currently instruct to use `pip install -r requirements.txt`.

However, this (at least on my Debian 12 machine) fails because the `lber.h` header is missing.

```
      Modules/common.h:15:10: fatal error: lber.h: No such file or directory
         15 | #include <lber.h>
            |          ^~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
```

On Debian 12, this can be fixed with `sudo apt install libldap-dev`. I haven't checked how to get this header on other distros.

This raises the question wether or not to include "system" dependencies like this in the documentation. At least the Devcontainer dockerfile specifies a list of dependencies which should probably be at least mentionened in the documentation:

 ```
#Install all dependencies.
RUN apk add --no-cache postgresql-libs postgresql-client gettext zlib libjpeg libwebp libxml2-dev libxslt-dev openldap git yarn
```

**Comment by smilerz** [comment]
Every OS and distribution and even version is going to have a variable set of additional dependencies.  Which is why manual installation of any kind isn't supported.
