### ISSUE TITLE
Configurable start screen for PWAs

### ISSUE THREAD

**Issue by sirinsidiator** [TandoorRecipes/recipes#3026]
### Is your feature request related to a problem? Please describe.

I run an instance of tandoor in docker so my family can use it as a shared shopping list. They don't really use any of the other features, so up until now I have changed the manifest.json for the PWA to automatically load the shopping list first. This was done by mounting a modified file into the docker container in docker-compose.yml:
```yml
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - /root/tandoor/mediafiles:/opt/recipes/mediafiles
      - /root/tandoor/manifest.json:/opt/recipes/cookbook/templates/manifest.json:ro
```

Starting from yesterdays update this is no longer possible, since the manifest is now dynamically generated inside view.py. 

### Describe the solution you'd like

What I'd like to have is a way to configure the start_url or rather the start screen for PWAs.

Some ideas that come to mind:
- Revert back to use the manifest.json as a template and dynamically insert theming variables into it
- Add an environment variable to allow changing start_url for the whole installation and use that in the web_manifest function
- Point the start_url to a new route (e.g. ./pwa_start) and redirect to a different view based on a setting (either globally or per user)

### Describe alternatives you've considered

For now I have opted to replace view.py in the same fashion as the manifest.json before, but that is obviously less than ideal since it will likely cause problems whenever watchtower automatically updates the image the next time and something has changed in view.py.

### Additional context

It seems the old manifest.json was not deleted when the new web_manifest function was added, which was quite confusing when I tried to figure out why my old method no longer worked.

Aside of that the shortcut for the shopping list is still pointing to the old url in the new manifest (./list/shopping-list instead of ./shopping)

**Comment by vabene1111** [comment]
thanks, I noticed the URL being broken as well. I fixed it for the next release.

Can't you use these shortcuts for those in your family that just use the shopping list?

But I also solved your problem. There is a per user setting for which page to start one. I changed the PWAs start link to `/` which means that start setting now takes action. Also I fixed that the setting was no longer shown in the settings.

**Comment by sirinsidiator** [comment]
As far as I am aware, the shortcuts would require them to long tap on the app icon to access them and not change the default behaviour? That's not something they'd think of every time they open the app, so not really a viable solution.

So, many thanks for the user setting. Looking forward to the next version!

**Comment by vabene1111** [comment]
Ah ok, on android you can just add the shortcuts to your home screen as well. Anyway, should be solved
