### ISSUE TITLE
Help trying to import Allerhande (ah.nl)

### ISSUE THREAD

**Issue by Calimerorulez** [TandoorRecipes/recipes#3033]
### Issue

Hi,

I just installed Tandoor, and now I'm trying to import my first recipe, from Allerhande (ah.nl).

When entering the URL, Tandoor automatically generates the 'www.ah.nl' keyword, the recipe images is broken, and when I click Import, I'm getting the following error:

`There was an error creating a resource!`

Logging shows:

```
2024-03-13 19:42:14 +0100] [11074] [DEBUG] POST /api/recipe-from-source/
[2024-03-13 19:43:00 +0100] [11074] [DEBUG] POST /api/recipe/
Bad Request: /api/recipe/
WARNING:django.request:Bad Request: /api/recipe/
```

### Tandoor Version

1.5.14

### OS Version

Debian 12

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Environment file

```shell
# ---------------------------------------------------------------------------
# This template contains only required options.
# Visit the docs to find more https://docs.tandoor.dev/system/configuration/
# ---------------------------------------------------------------------------

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
SECRET_KEY=**************************

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=localhost
POSTGRES_DB=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=tandoor
POSTGRES_PASSWORD=********
STATIC_URL=/staticfiles/
```

### Relevant logs

```shell
[2024-03-13 19:42:14 +0100] [11074] [DEBUG] POST /api/recipe-from-source/
[2024-03-13 19:43:00 +0100] [11074] [DEBUG] POST /api/recipe/
Bad Request: /api/recipe/
WARNING:django.request:Bad Request: /api/recipe/
```

**Comment by smilerz** [comment]
please share the entire container log and the output from the browser console

**Comment by Calimerorulez** [comment]
I've used the manual installation method, I will try the Docker install first.

**Comment by Calimerorulez** [comment]
Ok, reinstalled freshly via docker-compose.

My Chrome console says:

![image](https://github.com/TandoorRecipes/recipes/assets/1130552/7c6b54ba-9a83-4dc3-aded-71cfa5303795)

Imported URL: 
`https://www.ah.nl/allerhande/recept/R-R1192984/zoet-pittige-gehaktballetjes-met-wokgroente-en-rijst`

Webrecipies container log:

```
::ffff:172.18.0.4 - - [13/Mar/2024:21:06:47 +0100] "POST /api/recipe-from-source/ HTTP/1.0" 200 418 "http://192.168.5.122/data/import/url" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
Bad Request: /api/recipe/
WARNING:django.request:Bad Request: /api/recipe/
::ffff:172.18.0.4 - - [13/Mar/2024:21:06:55 +0100] "POST /api/recipe/ HTTP/1.0" 400 41 "http://192.168.5.122/data/import/url" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
Bad Request: /api/recipe/
WARNING:django.request:Bad Request: /api/recipe/
```

**Comment by jannik-hi** [comment]
> The website seems to use a non-standard format - you can request that it be added at https://github.com/hhursev/recipe-scrapers

Hi @smilerz, there seemed to be problems with the import script for ah.nl recipes a few months ago ([link](https://github.com/hhursev/recipe-scrapers/issues/990)), but they are apparently resolved. I also checked out the recipe-scrapers package myself and it works fine. However, I get the same error as OP when trying to import into Tandoor ("There was an error creating a resource!").

I use the hosted version btw. Is it possible that the recipe-scrapers package for the hosted version of Tandoor is not yet updated and thus the import fails? Or is this a general error that also occurs on self-hosted instances of tandoor?

**Comment by smilerz** [comment]
> Hi @smilerz, there seemed to be problems with the import script for ah.nl recipes a few months ago ([link](https://github.com/hhursev/recipe-scrapers/issues/990)), but they are apparently resolved. I also checked out the recipe-scrapers package myself and it works fine. However, I get the same error as OP when trying to import into Tandoor ("There was an error creating a resource!").
> 
> I use the hosted version btw. Is it possible that the recipe-scrapers package for the hosted version of Tandoor is not yet updated and thus the import fails? Or is this a general error that also occurs on self-hosted instances of tandoor?

You can check the version of any library by looking at `requirements.txt` - the version of the library is going to depend on which version you are running.

**Comment by jannik-hi** [comment]
> You can check the version of any library by looking at `requirements.txt` - the version of the library is going to depend on which version you are running.

I guess, I didn't explain my situation well enough. I am not hosting myself, but instead, use the paid, centrally hosted version on https://app.tandoor.dev, which means I can neither see which version of Tandoor I am using nor have access to the `requirements.txt`. Or am I missing anything on the website to take a look at those information?

**Comment by smilerz** [comment]
> I guess, I didn't explain my situation well enough. I am not hosting myself, but instead, use the paid, centrally hosted version on https://app.tandoor.dev, which means I can neither see which version of Tandoor I am using nor have access to the `requirements.txt`. Or am I missing anything on the website to take a look at those information?

The hosted version is not on the latest version of the library, I don't know when the defect you are experiencing was fixed.
