### ISSUE TITLE
Change font size / zoom factor

### ISSUE THREAD

**Issue by M0ebiu5** [TandoorRecipes/recipes#3037]
### Is your feature request related to a problem? Please describe.

I would like to use tandoor on a tablet - but the font is too small 

### Describe the solution you'd like

A parameter in the settings or configuration where i can adjust the font size or zoom factor

**Comment by vabene1111** [comment]
thanks for your feedback. I don't think I have ever seen such a feature in a web app, usually people just use the zoom or accessibility features of the device/browser to change the font size as everything is responsive. 

Do you feel like this is insufficient, if so why?

**Comment by M0ebiu5** [comment]
thanks for your quick response!
My use case is: tandoor runs as add-on in home assistant. It is integrated into the dashboard and i use the fully kiosk browser where zoom is disabled - the system should not provide too many ways to mess with it :)
So it would be nice if i could pre-configure the font size or zoom level...

I've already looked @ the css files - but there is some caching going on and plenty of files, so i could not yet figure out how to adjust the files for example:
body {transform: scale(1.2); }

**Comment by vabene1111** [comment]
You can upload a custom css file trough the space settings, I guess that should do the trick.

**Comment by vabene1111** [comment]
on top in the toolbox select "user files" and upload a file there first. I need to build an input that allow uploading directly

**Comment by M0ebiu5** [comment]
It worked - thanks for your nice support and the great app!

ps: without internet access, tandoor does not load - is this intended?

**Comment by vabene1111** [comment]
I think most dependencies should resolve locally, but there was one library I think that is currently broken so might be the case
