### ISSUE TITLE
Recipe instructions all show undefined

### ISSUE THREAD

**Issue by syphernl** [TandoorRecipes/recipes#3043]
### Tandoor Version

1.5.14

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Bug description

After upgrading to `1.5.14` the recipe instructions all show `undefined`:

![image](https://github.com/TandoorRecipes/recipes/assets/639906/5b4b490a-a6a5-48cc-9f2f-477097674d8c)

The `steps.[].instructions` seems to be returned by the API just fine but aren't shown in the UI.
The instructions show up fine in Untare.

**Comment by smilerz** [comment]
clear the local cache

**Comment by smilerz** [comment]
You either have an old versions of app still cached locally or there is some other setup problem.  Are there errors in the console log?

**Comment by syphernl** [comment]
> You either have an old versions of app still cached locally or there is some other setup problem. Are there errors in the console log?

There are no errors in the console log, only informational ones about the amount of time it took to load messages and `Manifest: Enctype should be set to either application/x-www-form-urlencoded or multipart/form-data. It currently defaults to application/x-www-form-urlencoded`.
If I edit a recipe the instructions show up just fine in the textarea

**Comment by syphernl** [comment]
This is working again with `1.5.15`.
