### ISSUE TITLE
Markdown preview does not match what is displayed when viewing recipe

### ISSUE THREAD

**Issue by AnderssonPeter** [TandoorRecipes/recipes#3056]
### Tandoor Version

1.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

This is displayed when viewing the recipe
![image](https://github.com/TandoorRecipes/recipes/assets/1308309/e9e44663-8024-4767-b11f-faaf9446a01d)
But when editing it displays the following:
![image](https://github.com/TandoorRecipes/recipes/assets/1308309/d801aaa8-b13e-4a57-be6e-0b05b8a6bcd6)
The indentation of the points is lost?

**Comment by smilerz** [comment]
duplicate

**Comment by AnderssonPeter** [comment]
You are right I'm so sorry for creating a duplicate, if anyone else finds this here is the correct issue https://github.com/TandoorRecipes/recipes/issues/2628
