### ISSUE TITLE
Can not import recipe from pinterest

### ISSUE THREAD

**Issue by ajfriesen** [TandoorRecipes/recipes#3096]
### Tandoor Version

1.5.16

### Import URL

https://www.pinterest.de/pin/406731410112789290/sent/?invite_code=fbc94e6677e84456aa0eb6878cc0f75f&sender=406731547505462843&sfo=1

### When did the issue happen?

After adding the link and clicking on the search button

### Response / message shown

```shell
There was an error importing the recipe!
Es konnten keine passenden Daten gefunden werden.
```

**Comment by smilerz** [comment]
The recipe scraper that we use doesn't support unstructured recipes.
