### ISSUE TITLE
Align step name and instructions vertically

### ISSUE THREAD

**Issue by Yannickvdv** [TandoorRecipes/recipes#3110]
### Is your feature request related to a problem? Please describe.

Currently, by default, steps without ingredients align left while those with ingredients are shifted to the right of the ingredients. 

![tandoor view](https://github.com/TandoorRecipes/recipes/assets/22369014/0c0fd978-d012-4593-96a5-e3b3b0a67ab9)

Here you see how step 3's instructions and are shifted left while the other steps are aligned further right. To me, this layout seems inconsistent and somewhat unnatural to read.

### Describe the solution you'd like

I propose we shift the steps without ingredients to the same horizontal location so that the page has a distinct separation between instructions and ingredients. Something like this (quickly changed the CSS to give a rough idea):

![tandoor edited view](https://github.com/TandoorRecipes/recipes/assets/22369014/52c8962c-2d1a-4595-9e42-b44bda49f0f0)

Here you see how the step 3's name and instructions no longer breaks up the page but flow alongside the other steps.

### Describe alternatives you've considered

Alternatively, the ingredients could even be floating to the left of the main content, but this might be a bit more tricky to do consistently over different viewports.

![afbeelding](https://github.com/TandoorRecipes/recipes/assets/22369014/deccce0c-ffac-4cc7-aa4f-bad880af285b)

**Comment by smilerz** [comment]
The entire front end is being redeveloped.  The layout hasn't yet been determined.
