### ISSUE TITLE
Shortcut ctrl+suppr delete whole space 

### ISSUE THREAD

**Issue by Tecnelm** [TandoorRecipes/recipes#3117]
### Tandoor Version

1.5.17

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

During editing a recipe, when doing the shortcut ctrl+del, the whole text is deleted instead of next word:
![bug](https://github.com/TandoorRecipes/recipes/assets/34011127/9c89be97-1199-4035-98c2-78f815999313)

**Comment by smilerz** [comment]
duplicate #2174
