### ISSUE TITLE
Trying to import recipes from Website www.tatiemaryse.com

### ISSUE THREAD

**Issue by SirTerrific** [TandoorRecipes/recipes#3128]
### Tandoor Version

1.5.17

### Import URL

https://www.tatiemaryse.com/recette-du-chou-saute-au-porc-caramelise-selon-tatie-maryse/

### When did the issue happen?

When I tried to import

### Response / message shown

```shell
There was an error importing the recipe!
Aucune information utilisable n'a été trouvée.
```

**Comment by vabene1111** [comment]
it appears that the page you are trying to import from does not provide any kind of machine readable data. Sadly that means that tandoor cannot import anything from that page.
