### ISSUE TITLE
Mealie Import does not include ingredients

### ISSUE THREAD

**Issue by Kurisutian** [TandoorRecipes/recipes#3148]
### Tandoor Version

1.5.17

### Setup

Kubernetes

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I did export all of my recipes from Mealie (v1.5.1) as described to import it to Tandoor. As described I went to the import page and uploaded the exported archive. The import started and all reciped (46 at this time) were imported. However checking them revealed that only the instructions were imported but none of the recipes contained any ingredients or amount of ingredients. So I am missing all facts and numbers from the imports.

**Comment by ellezhu1** [comment]
Can you send an example recipe file to replicate this bug?

**Comment by vabene1111** [comment]
related #2456
