### ISSUE TITLE
Whole recipe Food properties

### ISSUE THREAD

**Issue by TheJoSam** [TandoorRecipes/recipes#3156]
### Is your feature request related to a problem? Please describe.

Not every source of Recipes adds Food properties to their page and such it is nearly impossible to add properties

### Describe the solution you'd like

I would like to add Food properties for the complete recipe not every Ingredien

### Describe alternatives you've considered

It could be possible to add something like an Table of Nutrients for the whole Recipe

**Comment by vabene1111** [comment]
thats possible right under the picture using advanced options in the recipe editor
