### ISSUE TITLE
Link portion of sub recipe in recipe 

### ISSUE THREAD

**Issue by fabads** [TandoorRecipes/recipes#3157]
### Tandoor Version

1.5.7

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Not sure my issue is well placed here...
Let say I write a Ganache recipe. It's difficult to determine portions, I would prefer to define a weight of Ganache (eg 500g).

Then let's create a recipe of a nice cake using this Ganache. In the step I link to the existing recipe but where can I say I need 0.5 portion (or 250g)?

It would be easier to comminalize base recipes used in more complex cakes.

You followed me?

**Comment by smilerz** [comment]
duplicate #910
