### ISSUE TITLE
Add possibility to export recipes per command

### ISSUE THREAD

**Issue by update-freak** [TandoorRecipes/recipes#3158]
### Is your feature request related to a problem? Please describe.

It would be great to have the possibility to have an automatic export function of the recipes.
Therefore it would be good to have an export command, which can be triggered through e.g. synology task manager to do the export e.g. every friday at 01:00.

### Describe the solution you'd like

For example for paperless-ngx there is a command like that
`bash -c "docker exec Paperless-ngx document_exporter ../export -z"`
Something similar for Tandoor would be nice.

### Describe alternatives you've considered

manual export by hand. But this is time consuming

**Comment by smilerz** [comment]
What's the use case?  Export is not a reliable backup mechanism.

**Comment by update-freak** [comment]
My intension was indeed the backup of the recipes when there is a problem with the database and/or tandoor.
Therefore currently I export my receips every month.
Is there a better way in doing this snapshots of the receips? (If yes, which steps I have to follow)
Idea was to trigger an automatic export every month that I did not have to do that manually.

**Comment by smilerz** [comment]
Backup the database.

**Comment by update-freak** [comment]
ok, then I will do it via database backup. Thanks
