### ISSUE TITLE
Self-host without docker-compose in cloud services

### ISSUE THREAD

**Issue by vittis** [TandoorRecipes/recipes#3159]
### Issue

Hey, so I'm trying to host Tandoor app. The recommended way to deploy it is it via docker-compose (https://docs.tandoor.dev/install/docker/).

The compose file has 3 images, the app itself, the db (postgres) and nginx. I managed to run it locally without any problems.

But now I'm trying to host in Render and/or Fly.io. They don't support deploy via docker-compose, but support from docker images in registry.

So I was able to individually deploy a postgres instance and individually deploy the Tandoor image container. I was able to connect them too.

This worked and I can see the app live but there are some problems like the images I upload don't appear correctly (missing image icon). I'm suspecting that's because I skipped the nginx part.

So how would I tie everything together? I dont know much how nginx works.

Is there another recommended way to deploy it in these services (Render, Fly.io)?

### Tandoor Version

Latest

### OS Version

Not relevant

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

**Comment by smilerz** [comment]
We will only support docker installations.

**Comment by vittis** [comment]
> We will only support docker installations.

But these services (Render/Fly.io) are all via docker, only not docker-compose. 

But I'm a bit lost in how to setup the nginx part of things there

**Comment by smilerz** [comment]
you can join the discord server and check if anyone can yelp walk you through troubleshooting.
