### ISSUE TITLE
Conversion for foods without unit not possible

### ISSUE THREAD

**Issue by jannik-hi** [TandoorRecipes/recipes#3165]
### Tandoor Version

1.5.17

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

Setup: Homeassistant Add-On

### Bug description

Hi there,

while getting into food properties and the handy auto calculation featue I encountered the following problem: If I have foods in the ingredient list that don't have a unit, such as "1 cucumber" or "2 onions", it is not possible to get their food properites calculated, because I cannot set a conversion from 1 _(no unit)_ to e.g. 150 g. If I try that, I get the following error:
`Fehler
Beim Erstellen einer Ressource ist ein Fehler aufgetreten!
{"base_unit":["Dieses Feld darf nicht null sein."]}`

Unfortunately, those unitless ingredients are exisiting a lot, especially for imported recipes. I could go through my recipes and change the units from _None_ to "piece(s)" or something similar, but I think that if it's possible to add amounts without units, it should also be possible to use all the corresponding features, such as the unit conversion, with it.

Looking forward to your thoughts on this.

**Comment by smilerz** [comment]
Use a unit like 'whole' or a size like 'small'

**Comment by aarondoet** [comment]
Using a unit like `whole` does make it possible, but I would consider it a workaround for a missing feature, not as the intended way. A recipe telling me to use `0.5 whole cucumbers` feels off. The unit conversion should allow `no unit` as a valid unit.

**Comment by vabene1111** [comment]
I do understand your take but the unit conversion system is already very complicated. Adding a special conversion case for no unit could also lead to non obvious behavior when accidentally doing somthing without a unit. 

So for now no unit conversions without units. 

Also pcs is really common in recipes.

I think one could make units "inviisble" in the recipe view to just have them for technical purposes but that would be confusing as well so ...
