### ISSUE TITLE
Can't create or update recipes with keywords

### ISSUE THREAD

**Issue by anytimesoon** [TandoorRecipes/recipes#3167]
### Tandoor Version

1.5.17

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

I can no longer create or update recipes with keywords. If try to create a new recipe, I can, as long as it has no keywords. If I try to update a recipe that already has keywords, it fails. In the logs, it says this 

`django.db.utils.IntegrityError: duplicate key value violates unique constraint "kw_unique_name_per_space"
DETAIL:  Key (space_id, name)=(1, bread) already exists.`

To be clear, this recipe already had the keyword `bread`, I just wanted to change the quantities of an ingredient. The update made no changes to the keyword list.

### Relevant logs

```shell
ERROR:django.request:Internal Server Error: /api/recipe/100/
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "kw_unique_name_per_space"
DETAIL:  Key (space_id, name)=(1, breakfast and brunch) already exists.
```

**Comment by smilerz** [comment]
If you go to the admin interface do you see the keyword 'bread' more than once?

**Comment by anytimesoon** [comment]
I can. There seems to be quite a few duplicates there. Not sure how that could have happened, especially given the constraint on the db

**Comment by smilerz** [comment]
> I can. There seems to be quite a few duplicates there. Not sure how that could have happened, especially given the constraint on the db

the constraint was added later (though I don't remember when) and some logic was added to improve case-insensitivity on keywords

**Comment by anytimesoon** [comment]
Does a recipe search for keywords by id, or by name? I'm asking to figure out if I can just delete the duplicates from the db without losing any keywords in my recipes

**Comment by smilerz** [comment]
> Does a recipe search for keywords by id, or by name? I'm asking to figure out if I can just delete the duplicates from the db without losing any keywords in my recipes

by ID - do you have multiple duplicates for the same keyword?  (i.e. bread 3 times)

**Comment by smilerz** [comment]
Actually, nevermind, doesn't matter.
- rename all duplicates to something unique (bread, bread1, etc)
- navigate to `/list/keywords/` merge the duplicate keywords via the context menu or drag-and-drop

**Comment by anytimesoon** [comment]
got it. Thank you

**Comment by vabene1111** [comment]
this was sadly a rare edge cases caused by the migrations away from icons in keywords, sorry for the inconvenience.
