### ISSUE TITLE
Use default setting to pre-fill the meal type when adding recipe to meal-plan

### ISSUE THREAD

**Issue by Hoffelhas** [TandoorRecipes/recipes#3172]
### Is your feature request related to a problem? Please describe.

When creating / adding a new recipe to the meal-plan, you need to enter the meal type in order to save the new entry. Currently, I only have one meal type: 'dinner'. Even though I only have one type, I can't seem to find a way to pre-fill this value as default when adding multiple entries for the week, Automating this would greatly improve user-friendliness.

### Describe the solution you'd like

Ideally, I would like to configure a default meal type, which is then pre-selected when adding a new recipe to the meal-plan. Under 'Settings - Meal Plan' would be an ideal place to configure this.

### Describe alternatives you've considered

No alternative feature available as far as I'm aware

**Comment by smilerz** [comment]
You can set a default meal plan type.

**Comment by Hoffelhas** [comment]
Found it.

For future reference: go to 'Settings - Meal Plan'. Under 'Meal types, edit the one you're interested in, enable 'Default' and save.
