### ISSUE TITLE
API endpoint to see what recipe(s) are planned for only today

### ISSUE THREAD

**Issue by Hoffelhas** [TandoorRecipes/recipes#3173]
### Is your feature request related to a problem? Please describe.

I'm looking for a way to extract what recipe is planned for 'today' through the API. Going to 'https://tandoor.bks110.nl/api/meal-plan/' however only gives a total overview of everything in the meal-plan. The software (Homepage docker) reading the API callback on my end isn't able to do any required filtering, which means I'm not able to isolate what recipe is planned for 'today'.

### Describe the solution you'd like

Ideally I would like to use an API endpoint like 'meal-plan-today', which gives a similar result as 'meal-plan' but limited to the results from today.

**Comment by smilerz** [comment]
All of the APIs have parameters to filter results.

**Comment by smilerz** [comment]
How are you constructing the url?
