### ISSUE TITLE
Ability to move and copy recipes between spaces

### ISSUE THREAD

**Issue by j007bond007** [TandoorRecipes/recipes#3176]
### Is your feature request related to a problem? Please describe.

I have a shared space for friends and family and each household has their own space (for meal planning, shopping lists and the recipes they don't wish to share). It would be very useful to be able to copy and/or be able to move recipes between spaces for this reason, giving more flexibility in how this great app can be used.

### Describe the solution you'd like

To implement the ability to copy and move recipes between spaces.

### Describe alternatives you've considered

You can export and import recipes but the workflow is not friendly or efficient for end users.

**Comment by smilerz** [comment]
Duplicate #1935
