### ISSUE TITLE
Social sign up does not use correct URL in text

### ISSUE THREAD

**Issue by zodac** [TandoorRecipes/recipes#3179]
### Tandoor Version

1.5.17

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

This is a purely visual issue, the flows are working fine.

When I sign up to create an account in Tandoor using social authentication (I am using Authentik, and the openid_connect provider), once I have successfully signed in and am about to create an account, the sign up page references the website name as **example.com** rather than the actual domain.

![image](https://github.com/TandoorRecipes/recipes/assets/2502611/1a49d71d-ee9e-4ad9-872a-016ebacd9926)

Can the URL be picked up from somewhere, or is there an environment variable I could set to have this display the correct URL?

Thanks!

### Relevant logs

```shell
This is the snippet from my docker-compose.yml file defining the social authentication:

...
SOCIAL_PROVIDERS: "allauth.socialaccount.providers.openid_connect"
SOCIALACCOUNT_PROVIDERS: |
  {
    "openid_connect": {
      "SERVERS": [
        {
          "id": "authentik",
          "name": "Authentik",
          "server_url": "authentik_url",
          "token_auth_method": "client_secret_basic",
          "APP": {
            "client_id": "client_id",
            "secret": "client_secret"
          }
        }
      ]
    }
  }
REMOTE_USER_AUTH: "1"
SOCIAL_DEFAULT_ACCESS: "1"
SOCIAL_DEFAULT_GROUP: "guest"
...
```

**Comment by smilerz** [comment]
Duplicate #2736

**Comment by zodac** [comment]
Is there an environment variable that can set this value directly, or can it only be done through the admin UI?

**Comment by smilerz** [comment]
No.
