### ISSUE TITLE
Recipe import for APP: Mealie does not import recipes

### ISSUE THREAD

**Issue by myhubacct** [TandoorRecipes/recipes#3186]
### Tandoor Version

Tandoor (HEAD) - 1.5.17 -- commit f14acc371d7cf7ac7bcd6c1bd102f7d3c6a6b2b8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx on the host system

### Bug description

* Trying to import recipes form a freshly created Malie backup. Mealie is on Version 1.8.0 and the picture shows the Import page
![Import page](https://github.com/TandoorRecipes/recipes/assets/26323549/e441317c-3492-4724-bd7d-3d49cdbb8cff)

* The Tandoor import procedure runs without any visible error message and does show up with zero imports on the result page. ![Import Result page](https://github.com/TandoorRecipes/recipes/assets/26323549/ee6a7eba-c8f7-44db-b623-13a0abfd124c)
* have attached the corresponding logs of all three Tandoor docker container 
[logs.txt](https://github.com/user-attachments/files/15837924/logs.txt)

Thanks in advance

**Comment by Maximilian1512** [comment]
I do have exactly the same problem. Found no solution till now.

**Comment by vabene1111** [comment]
see #2456 

sorry there has not been a fix yet, its a lot of work and I did not have time to do it yet

**Comment by danktankk** [comment]
add another one to the list.  no hurry, but I cant use the app.  all my recipes are in mealie.  :(

**Comment by hardj300** [comment]
Confirmed same exact issue for me.  I was going to switch but I guess I will not until this is fixed.  Thanks and take care.
