### ISSUE TITLE
Management of (saved) search filters

### ISSUE THREAD

**Issue by myhubacct** [TandoorRecipes/recipes#3187]
### Documentation link

n/a

### Affected section

Does not exist yet

### Issue description

Searching for information how to work with the recipes filters. It seems they can be used within Books for filtering. I am created some of them, but I do not find a documentation on how to manage them. So I can not even find how to delete the ones with wrong title nor I am able to find how to adjust the search criteria.

**Comment by myhubacct** [comment]
great, at least deletion is possible. Could you elaborate a bit, how I can find this magic links at my own? Have I missed something in the documentation?

**Comment by smilerz** [comment]
You don't need to do anything.
