### ISSUE TITLE
Link to import/export documentation in website FAQ is bad (404)

### ISSUE THREAD

**Issue by Michael2MacDonald** [TandoorRecipes/recipes#3193]
### Tandoor Version

N/A

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

N/A

### Bug description

In the FAQ section of the tandoor website (https://tandoor.dev/), under "Which applications/services can I import from?", the link to "view the currently supported Importer" leads to a 404 page:

Current link address (leads to 404):
https://docs.tandoor.dev/features/import_export.html

Expected link address:
https://docs.tandoor.dev/features/import_export/

**Comment by smilerz** [comment]
Can you screenshot where you see this?  I can't find that string of text ('Which applications/services can I import from') anywhere.

**Comment by Michael2MacDonald** [comment]
![Screenshot_20240703_173830](https://github.com/TandoorRecipes/recipes/assets/34051815/cf72faba-4c77-4ae8-bd3f-a5291ddcb21d)

**Comment by smilerz** [comment]
@vabene1111 this is on the hosted site and not part of the code base.

**Comment by vabene1111** [comment]
Thanks, I will look into this

**Comment by vabene1111** [comment]
fixed, thanks for the report
