### ISSUE TITLE
Issue with units imported from gousto.co.uk

### ISSUE THREAD

**Issue by ThomasHFWright** [TandoorRecipes/recipes#3194]
### Tandoor Version

1.5.17

### Import URL

https://www.gousto.co.uk/cookbook/chicken-recipes/sticky-orange-chicken

### When did the issue happen?

Gousto.co.uk seems to have a funny way of displaying units of ingredients based on their packaging sizing which leads to undesirable behaviour during import, with Tandoor trying to import units such as "320g", "Brown", and "1" and moving the actual units into the ingredient name

From gousto:
<img width="264" alt="image" src="https://github.com/TandoorRecipes/recipes/assets/26573181/37fad8dc-b9ab-44a6-b860-e36e645dadaa">

While importing into Tandoor:
<img width="986" alt="image" src="https://github.com/TandoorRecipes/recipes/assets/26573181/c958c224-20da-4f39-9c62-617dc7d8d108">

**Comment by smilerz** [comment]
scraping websites is handled upstream at `https://github.com/hhursev/recipe-scrapers` they might be able to fix it there.
