### ISSUE TITLE
Search does not deliver any results

### ISSUE THREAD

**Issue by danst0** [TandoorRecipes/recipes#3195]
### Tandoor Version

1.5.17

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Search does not deliver any results. I have a recipe with spinach in plain view. When I type spinach in the search field all items including the relevant one disappear.

### Relevant logs

```shell
There seem to be no errors in any of the three containers (db, web, nginx).
```

**Comment by smilerz** [comment]
what are you search settings?

**Comment by danst0** [comment]
Ok. There are search settings... I turned on fuzzy search and now it works; thank you!
