### ISSUE TITLE
Move ingredient button in recipe edit (post creation or import) very small

### ISSUE THREAD

**Issue by youreunwelcome** [TandoorRecipes/recipes#3197]
### Tandoor Version

1.5.17

### Setup

Manual Setup

### Reverse Proxy

Others (please state below)

### Other

NGINX manual config

### Bug description

When clicking to drag ingredients in the edit recipe interface (already created or imported) the actual clickable area is only the actual double arrow character, not the entire button area. It appears that the padding is not usable as a clickable area. Not a major bug at all, but a minor inconvenience (especially on high PPI screens) to have to pinpoint click to get it to move. 
![diagram](https://github.com/TandoorRecipes/recipes/assets/16448983/fcc6b5a2-7190-4362-ae85-e34480c283ab)
As seen in this image, the box made by the dotted lines is what must be clicked; the whole box defined by the padding causes a change in the character color but when clicked does not move the ingredient. (at least in Firefox, which is my browser.)

**Comment by vabene1111** [comment]
I am rewriting the frontend, so no more fixes for the old, but I have/will keep bad drag and drop handles in mind :) thanks for the feedback.
