### ISSUE TITLE
Markdown fractions don't display correctly

### ISSUE THREAD

**Issue by IReclaimer** [TandoorRecipes/recipes#3206]
### Tandoor Version

1.5.17

### Setup

Manual Setup

### Reverse Proxy

Others (please state below)

### Other

Nginx

### Bug description

When creating or editing a recipie, it is possible to use the Markdown fraction code to display a fraction. This works in the preview of the edit:
![Screenshot 2024-07-03 235536](https://github.com/TandoorRecipes/recipes/assets/7721854/00fcd0ab-6c0d-40f7-b8fb-9357166350cd)

However the preview doesn't represent what is displayed on the recipie page:
![Screenshot 2024-07-03 235637](https://github.com/TandoorRecipes/recipes/assets/7721854/a11a18a7-d522-4808-9a9a-9e8fc84f3fa4)

**Comment by smilerz** [comment]
Duplicate. The md editor and the parser are different libraries.
