### ISSUE TITLE
Home Assistant Connector

### ISSUE THREAD

**Issue by pbathuk** [TandoorRecipes/recipes#3213]
### Issue

Hi,

I've only recently started using Tandoor, and so far I'm liking it. I've recently tried to setup the connections to my home assistant instance (which I do note says beta) and I and getting some weird issues, so wanted to see if others have the same issue or not?

## Intermittent update (tandoor -> HA)
The first issue is that if I add items to my shopping list, sometimes (seems to be if it is a fresh boot of my dockers) it will work, but most of the time I will add things on tandoor and nothing is added to HA. And that is with leaving it for an hour or so as well 

## no return sync (HA->Tandoor)
Not sure if this is a feature, but if I tick / remove or add in HA to do list tandoor never updates. Again waiting a few hours to see if it was a sync timing issue. 

I've managed to setup HA using the rest API route from HA to Tandoor to grab the next meal etc.. so both can "see" each other.

Any help is gratefully received.. as ideally I want to have a single shopping list built (in HA), that my family can use, but if someone adds a meal it will then add the ingredients etc etc.

Thanks

### Tandoor Version

1.5.18

### OS Version

Ubuntu 24.04 

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Environment file

```shell
# ---------------------------------------------------------------------------
# This template contains only required options.
# Visit the docs to find more https://docs.tandoor.dev/system/configuration/
# ---------------------------------------------------------------------------
# random secret key, use for example `base64 /dev/urandom | head -c50` to gener>
SECRET_KEY=(shhh it's a secret)
# allowed hosts (see documentation), should be set to your hostname(s) but migh>
# ALLOWED_HOSTS=recipes.mydomain.com
# add only a database password if you want to run with the default postgres, ot>
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_DB=djangodb
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=(password)
ALLOWED_HOSTS=tandoor.example.ltd
TZ=Europe/London
DEBUG=1
DISABLE_EXTERNAL_CONNECTORS=0
EXTERNAL_CONNECTORS_QUEUE_SIZE=200
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=465
EMAIL_HOST_USER=(email)
EMAIL_HOST_PASSWORD=(app pass)
EMAIL_USE_TLS=0
EMAIL_USE_SSL=1
DEFAULT_EMAIL_ADDRESSS=(email address)
```

### Docker-Compose file

```shell
services:
  db_recipes:
    container_name: db_recipes
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default
  web_recipes:
    container_name: web_recipes
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/doc>
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - default
  nginx_recipes:
    container_name: nginx_recipes
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/doc>
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro
    networks:
      - default
      - my_bridge
volumes:
  nginx_config:
  staticfiles:
networks:
  my_bridge:
    driver: bridge
    name: my_bridge
    external: true
```

### Relevant logs

```shell
(I will grab these later)
```

**Comment by vabene1111** [comment]
so the sync is one way, so backsync is expected to not work. regarding the other way maybe @mikhail5555 is able to help you debug this.

**Comment by pbathuk** [comment]
[_nginx_recipes_logs.txt](https://github.com/user-attachments/files/16156792/_nginx_recipes_logs.txt)
[_db_recipes_logs.txt](https://github.com/user-attachments/files/16156793/_db_recipes_logs.txt)
[_web_recipes_logs.txt](https://github.com/user-attachments/files/16156794/_web_recipes_logs.txt)


I've attached some logs from just now.
These have DEBUG=0 - as I see that it says on the admin page to have this turned to 0.

However when I did add a receipe nothing went through to HA at all this time.

When I had DEBUG=1 overnight it worked the 1 way Tandoor -> HA nicely
So wonder if it is the DEBUG flag that is somehow causing the one way sync to fail.

**Comment by pbathuk** [comment]
On the one way, thanks for explaining.. I was hoping it would automatically mark them as done if in HA.. rather than having to clean up the shopping list in Tandoor seperately - but that is my misunderstanding, so thanks for resolving

**Comment by pbathuk** [comment]
Ah sorry about that. Yeah I could not find any log files, so took the ones from the docker containers. 
If you can guide me as to how to enable logging, more than happy to do it.

Thanks

**Comment by vabene1111** [comment]
thanks for keeping an eye on this, closed until we hear any feedback

**Comment by pippo73** [comment]
Hello, as @mikhail5555 asked my I'm back with this problem.
Actually I'm running 
Tandoor (HEAD) - 1.5.19 in a docker configuration 

Home Assistant
    Core 2024.9.1
    Supervisor 2024.09.1
    Operating System 13.1
    Frontend 20240906.0


    
In my test I've tried to add some items in tandoor, but nothing happened in HA.
If you need any other infos, just me ask what can I do.

Attached you can find the Tandoor conf file and some logs.
[Tandoor.zip](https://github.com/user-attachments/files/16996334/Tandoor.zip)

**Comment by pippo73** [comment]
Here are the debug of my HA 
[tandoor.zip](https://github.com/user-attachments/files/17009407/tandoor.zip)

> Also, it seems the debug log include your bearer token that's used in the request. My bad on that point, but you should likely remove/replace the API key you have currently configured for it.

How to do it? could you explain me pls

> Which kind of 'list' are you using, is it a manual created one 

to do your request I've used the default list 
`Todo entity : todo.shopping_list`

But in previous tests, I've tried to do it also with tandoor specific list.

**Comment by pippo73** [comment]
[Tandoor.zip](https://github.com/user-attachments/files/17009584/Tandoor.zip)

good morning :-) 

here is the ha log with a fresh new list created now.
