### ISSUE TITLE
Serious Eats import fails

### ISSUE THREAD

**Issue by bjo81** [TandoorRecipes/recipes#3223]
### Tandoor Version

1.5.18

### Setup

Manual Setup

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

The import of https://www.seriouseats.com/ajitsuke-tamago-japanese-marinated-soft-boiled-egg-recipe fails when trying to import via the URL. When I copy the whole sourcecode and paste it, the recipe get's recognized.

Issue also appeared with docker-compose setup

### Relevant logs

```shell
Nothing is logged regarding the issue.
```

**Comment by smilerz** [comment]
Import for that recipe seems to work fine on 1.5.18.  What is logged in the browser console?

**Comment by bjo81** [comment]
![grafik](https://github.com/user-attachments/assets/faef185b-3fc0-45f6-9e30-9aa2e0bff546)

The browserconsole only shows:

```
started loading locale messages [import_view.js:1:32420](https://recipes.schafweide.org/static/vue/js/import_view.js)
finished loading messages in  19  ms [import_view.js:1:32602](https://recipes.schafweide.org/static/vue/js/import_view.js)
``

**Comment by smilerz** [comment]
Don't know what to tell you at this point - the import works fine  

![image](https://github.com/user-attachments/assets/59351398-356f-4b6d-ab33-3b4aa7259724)
