### ISSUE TITLE
API call fails when selecting two keywords in AND mode

### ISSUE THREAD

**Issue by Forceu** [TandoorRecipes/recipes#3224]
### Tandoor Version

1.5.18

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

Podman/Nginx

### Bug description

No recipes are displayed when I search for two tags with the AND operation. The API returns 404 on the call.

Example:

`https://tandor.server/api/recipe/?query=&keywords_and=44&keywords_and=9&internal=false&random=false&page=2&page_size=25&include_children=true`

### Relevant logs

> HTTP 404 Not Found
> Allow: GET, POST, HEAD, OPTIONS
> Content-Type: application/json
> Vary: Accept
> 
> {
>     "detail": "Invalid page."
> }

**Comment by Forceu** [comment]
Ah interesting, yes that was indeed the reason.

Wouldn't it be better to automatically go back to page 1 if you change the search parameters? That would prevent this error (and less technical users don't know that it is an error, as it is not caught. The UI still shows the loading animation).

**Comment by smilerz** [comment]
the front-end is being refactored, search will behave a bit differently and shouldn't be a problem.

**Comment by Forceu** [comment]
Okay, thanks for the quick response! 🙂
