### ISSUE TITLE
Paying subscription with gift cards

### ISSUE THREAD

**Issue by serrq** [TandoorRecipes/recipes#3242]
I would like to pay subscription with crypto currencies, and these shops allows it.

• https://www.coinsbee.com/en/shop
• https://www.bitrefill.com/eu/en/gift-cards/

**Comment by vabene1111** [comment]
Hi, thank you for your request and for wanting to support tandoor. Sadly I currently cannot offer subscriptions with gift cards. What you might be able to do is buy a pre-paid credit or debit card which would work similarly.

**Comment by vabene1111** [comment]
Hi, thank you for your feedback. Discovering new recipes is explicitly not what tandoor wants to do. It is meant to serve as a empty book that allows people to easily and nicely add what they find all over the internet/world to it. 

Discovering recipes would require some kind of content moderation which as a single person also responsible for all the development is something I cannot do. Also there are thousands of places much more specialised and skilled at providing content.

**Comment by vabene1111** [comment]
Hi, if you need more storage please contact me for a custom plan via info@tandoor.dev

As mentioned there is no plan to add gift card payment.
