### ISSUE TITLE
Don't style outline for buttons

### ISSUE THREAD

**Issue by hcientist** [TandoorRecipes/recipes#3244]
### Tandoor Version

v1.5.18

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

The styles for focused buttons including (at least) [`.btn:focus`](https://github.com/TandoorRecipes/recipes/blob/develop/cookbook/static/themes/tandoor.min.css#L2302) and [button:focus](https://github.com/TandoorRecipes/recipes/blob/develop/cookbook/static/themes/tandoor.min.css#L311) override other styles in the project for focused buttons and effectively remove the `outline` which results in a degraded (and inaccessible) user experience. Additionally the `-webkit-focus-ring-color` isn't standard (and is invalid in Firefox). Consider using [`focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) where necessary, but avoiding styling this without associated accessibility tests.

**Comment by smilerz** [comment]
All button styling comes from bootstrap-vue or some other upstream component.
