### ISSUE TITLE
Option to move ingredient to different step

### ISSUE THREAD

**Issue by Sebbyyy** [TandoorRecipes/recipes#3247]
### Is your feature request related to a problem? Please describe.

When I am trying to move ingredients from my previously poorly imported recipes, if the next step is more than the visible page away - I am unable to drag it to the next step.

### Describe the solution you'd like

The easiest option would be on the clickable options for the ingredients to include an option to move to step with a dropdown list. 

However,  even an improved edit UI would also be beneficial. Maybe a zoomed out with everything smaller that is easier to navigate between steps could be beneficial into the future.

### Describe alternatives you've considered

I normally use my main computer rather than laptop which does make it less of a problem but I just seem unable to zoom on tandoor or anything on my laptop.

### Additional context

Small feature which many may find helpful

**Comment by smilerz** [comment]
The front end is being rewritten, no changes to the current UI will be implemented.  In the meantime, you can increase the size of the page (Ctrl + on Chrome/Edge) until both steps are visible.
