### ISSUE TITLE
AI integration

### ISSUE THREAD

**Issue by H04h04** [TandoorRecipes/recipes#3252]
### Is your feature request related to a problem? Please describe.

A lot of the smaller details can be automated with ai. For example, ai can assign food categories automatically to make organizing grocery lists easier. It can also automate meal planning with brief promos using recipes entered, or by describing food on hand. 

### Describe the solution you'd like

ChatGPT integration to automate or simplify the aforementioned tasks. If a new recipe has an onion in it, ai can recognize that it is produce and assign it to that category for the shopping list. 

### Describe alternatives you've considered

A ton of manual labor.

**Comment by smilerz** [comment]
Duplicate

**Comment by H04h04** [comment]
I’m missing it. I searched for it but never saw something like what I suggested. That’s ok - but so I am aware, is it already implemented or just a request at this point?

**Comment by H04h04** [comment]
> Duplicate

I’m missing it. I searched for it but never saw something like what I suggested. That’s ok - but so I am aware, is it already implemented or just a request at this point?
