### ISSUE TITLE
Meal planner date shifts

### ISSUE THREAD

**Issue by endangered-maritime-walrus** [TandoorRecipes/recipes#3254]
### Tandoor Version

1.5.18

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

cloudflare zero trust

### Bug description

Tried to search, apologies if it is a duplicate.

When I assign a recipe to a day, it shifts to the day before.
Time of test: Aug 11 2024 8PM
Open Meal planner
Click on desired date (Aug 13)
Fill out pop up with recipe, meal type, etc. (date is correct here)
Click save, it immediately shows up as a meal for Aug 12.

When clicking back into the recipe on the incorrect date (Aug 12) it lists Aug 12 as the assigned date.

I have tried it on my computer, phone, wife's phone, all result in the same issue. Tried from both local instance and through the Cloudflare proxy

Are there settings I should change to keep this from happening?

The only walk-around I have found is after adding them, drag them to the day after the desired date, though if I go into the popup and click save, it jumps a day back also.

Thanks.

**Comment by vabene1111** [comment]
Hi, thanks for the post. I think there is some edge case in the current implementation. This has been mostly re-implemented for the vue 3 version (where I did not yet find any edge cases) so there is not going to be a fix for the current branch.

**Comment by IcedQuinn** [comment]
I just had this happen in 1.5.24 (da49280ef23ec9ecec99f635b0c1afc36bf7b33c)

If I insert meals in to a calendar entry it just ignores the date upon save. It really wants to stack them first date to last date and the actual order I put entries in as well as the dates gets ignored.

**Comment by AdrianAyastuy** [comment]
I'm having the same issue. When I add a new entry to the meal plan is move to the day before. Could it be a time-zone issue?
```
commit a0c8b39f0cacc030115ed14683d2a17e0e13f709
Author: vabene1111 
Date:   Sat Feb 1 08:08:55 2025 +0100

    Merge branch 'develop'
```

**Comment by PeterGIN** [comment]
I agree this is likely a time zone issue. I can clearly see this if I add a comment to a recipe. My local time is 9:30 PM (America/Chicago) and the comment timestamp is 4:30 AM the next day. 

I tried adding `TZ=America/Chicago` to the docker `.env` file and the YAML configuration file but that didn't change the behavior
