### ISSUE TITLE
Grab img from url

### ISSUE THREAD

**Issue by xboxhaxorz** [TandoorRecipes/recipes#3255]
### Describe the solution you'd like

Since we can import recipes from url, why not the img as well if we have a recipe but no img

**Comment by vabene1111** [comment]
thanks for the request. I see where it is coming from but this would require quite a bit of extra frontend and backend logic while copying the link to paste it into tandoor is probably pretty much the same amount of work than "save as" on the image and selecting it in tandoor. 

Closing this for now but I always wanted to refactor the "image upload" system so maybe when i get to that I will implement something like this.
