### ISSUE TITLE
Remove imported from line

### ISSUE THREAD

**Issue by xboxhaxorz** [TandoorRecipes/recipes#3256]
### Describe the solution you'd like

If the recipe site has been deleted the link wont work, so the ability to remove that line would be great

**Comment by smilerz** [comment]
Source URL is listed in 'Additional Options'

**Comment by rucksman** [comment]
Although I can delete the link, it still says "Imported from". How to get rid of this line as well?

**Comment by vabene1111** [comment]
will not be changed in old version, New version should be fixed if not feel free to report once its out #2976
