### ISSUE TITLE
Possibility to add pictures to individual steps

### ISSUE THREAD

**Issue by ssc85** [TandoorRecipes/recipes#3265]
### Is your feature request related to a problem? Please describe.

Problem is to only subscribe the steps within a recipe by text. Adding images for individual steps could be an helpful addition.

### Describe the solution you'd like

I would like to add individual pictures / images within the steps (directly add the pictures within the recipe editor)

### Additional context

![image](https://github.com/user-attachments/assets/5e4b2e41-7875-4b9f-8f63-343693a210ae)

**Comment by vabene1111** [comment]
you can do that by adding a markdown picture `![text](url)` or by adding a file ("Datei") to the step. I plan on improving this in the future

**Comment by ssc85** [comment]
OK, but then I have to manually upload it in advance and refer to it by using the "url" - right? 

I just thought of some "copy" & "paste"(like it works for example on github).

**Comment by vabene1111** [comment]
you have to upload it and either refer to it by URL (which is a bit tedious) or select it from the file search. Both options aren't great, I will improve the file picker in the new version, the editor is a bit more complicated but thats also something I would like to improve. For now this is sadly as good as it gets
