### ISSUE TITLE
Improve serving quantity slider

### ISSUE THREAD

**Issue by jknndy** [TandoorRecipes/recipes#3266]
### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/c3f06d00-a62a-4f8b-8901-9e20bdb6b88b)

1. Possibly improve servings slider by adding a few quick select options (1/2, 2x, 3x)
2. Update the original quantity (*[24] in this example*) to be selectable which would reset to original recipe servings.
3. Lastly, I think this element could benefit from having `Serving Size` placed above it to match the style of `Preparation` and `Waiting`

### Additional context

I'm interested in contributing to this project but am not very familiar with Vue. As this is a fairly simple implementation I will draft an implementation myself if there is interest in this changeset!

**Comment by vabene1111** [comment]
this will be entirely changed in the new vue3 version so no changes to the old slider will happen. The new one is a lot better I think :)
