### ISSUE TITLE
API endpoint returning installed Tandoor version

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#3269]
### Is your feature request related to a problem? Please describe.

I'm maintaining an [Apple Shortcut](https://routinehub.co/shortcut/12612/) that helps with recipe imports. It tries to determine the ideal way to import each recipe, among other things by checking if a scraper exists for the respective domain. Currently, it assumes that the latest set of scrapers from hhursev/recipe-scrapers is used in Tandoor. Ideally, it would query the user's Tandoor version, analyze the respective requirements.txt and then retrieve the list of scrapers available in the installed version.

### Describe the solution you'd like

An API endpoint that returns metadata about the installation, such as the version tag and/or commit. If it would also return an array of third-party libraries and their versions, i.e. everything in requirements.txt, that would make my life even easier.

### Describe alternatives you've considered

Manually updating my Shortcut to use the scraper versions included in the latest Tandoor version and limiting compatibility of the Shortcut to the latest Tandoor version.

**Comment by vabene1111** [comment]
Hi, just use the `/openapi/` endpoint, it contians the version as one of the first parameters. There is a ?format=json parameter if you prefer that. 

Please let me know if that helps :)

**Comment by tomtjes** [comment]
> Hi, just use the `/openapi/` endpoint

Perfect, thank you! (I think @smilerz tried to point me there before, but I misunderstood it as using /docs/api at the time.)

**Comment by vabene1111** [comment]
no worries :) it shows the same version as on the system page btw. so if running any development or beta it will be just a hash
