### ISSUE TITLE
Pull nutrition facts from open food facts

### ISSUE THREAD

**Issue by gudvinr** [TandoorRecipes/recipes#327]
**Is your feature request related to a problem? Please describe.**
Manual input of information which already there is always frustrating and people are generally like to avoid routine.  
Recently nutrition information for recipes was added but you still should enter this information even though nutritional values already were calculated by someone but there aren't many sources from where you can pull this information.  
There's [FoodData Central](https://fdc.nal.usda.gov/) for USA but not everyone lives in US so this pretty much useless for most of the people. FDC has both API and data dumps. However, FDC has data on raw ingredients.  
One possible open alternative is [Open Food Facts](https://github.com/openfoodfacts) which has apps for users to crowd source this info. OFF also has an API and you can download database dumps as well.  
MyFittnessPal has [private API](https://www.myfitnesspal.com/api) and it seems like they have pretty decent database which, as you may guess, private.

**Describe the solution you'd like**
I suggest to implement abstract "nutrition value retrieval service" and as an implementation base use OFF API

**Describe alternatives you've considered**
You can input nutritional information manually but that's not really an alternative.

**Comment by vabene1111** [comment]
When adding the nutition information system we debated if we wanted to go per recipe or per ingredient. 
We decided to just have information per recipe as per ingredient would be to much work.

With this we could technically pull all ingredients from their API (or have a function to download their dataset) and then calulate the recipe nutritional values based on its ingredients which would be really nice.

**Comment by gudvinr** [comment]
@vabene1111 yeah, that's will be very convenient. It is huge PITA to count calories for home cooked food.  
As a bonus you could also help OFF and implement feature to _send_ nutritional values about food that not exists in their database for those who are willing to

**Comment by vabene1111** [comment]
That is an excellent idea 👍
