### ISSUE TITLE
Markdown fractions show correctly in editing but not in Recipe View

### ISSUE THREAD

**Issue by its-schmii** [TandoorRecipes/recipes#3281]
### Tandoor Version

1.5.19

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

### Bug description

When writing fractions with markdown in the recipe editing / creation they display correctly in the Markdown preview.
However, when viewing the recipe the Markdown-Formula is shown instead of rendering the fraction.

Fraction code used:
`$\frac{2}{3}$`

**Comment by smilerz** [comment]
Duplicate #3206
