### ISSUE TITLE
i cant import any recipes from a specific website

### ISSUE THREAD

**Issue by giannis371** [TandoorRecipes/recipes#3292]
### Tandoor Version

1.5.19

### Setup

Manual Setup

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

As the title says i when i try to import a recipe from akispetretzikis.com for example 
https://akispetretzikis.com/en/recipe/5075/gkoylas i get error 
"there was an error importing the reciepe".
But its strange because before 6 months ago it was working. 
From other websites i can import also import recipes, the error occurs only on this website.

**Comment by smilerz** [comment]
Duplicate #3267

**Comment by smilerz** [comment]
Site isn't supported. You can request someone to look to see if it can be added at https://github.com/hhursev/recipe-scrapers

**Comment by giannis371** [comment]
It is in the list. Doesn't this mean it is supported?

**Comment by smilerz** [comment]
I apologize - it is listed in the scrapers, but appears something has changed.  the initial page is a loading page without any recipe data.  You will still need to open a ticket on `recipe_scrapers` though

**Comment by giannis371** [comment]
I did. They ask me which version recipe_scrapers is used in tandoor. How can I check this?
Thanks

**Comment by smilerz** [comment]
library versions are defined in `requirements.txt`

`recipe-scrapers==15.0.0`

**Comment by giannis371** [comment]
Thanks!
