### ISSUE TITLE
"There was an error creating a resource!" only for some links

### ISSUE THREAD

**Issue by Plop** [TandoorRecipes/recipes#3298]
### Tandoor Version

1.5.19

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Hi,

I'm trying to import a recipe, but I have an error : "There was an error creating a resource!". The recipe I'm trying to import is there : https://l-herboriste.com/wtf-seitan-de-farine-lavee/

When I try to import other recipes from this website, or other websites, I do not have any issue.

I can't find anything in the containers' logs.

Thanks for your help

**Comment by smilerz** [comment]
Duplicate #3267
