### ISSUE TITLE
Summarize Ingredients

### ISSUE THREAD

**Issue by JackboyPlay** [TandoorRecipes/recipes#3299]
### Is your feature request related to a problem? Please describe.

![grafik](https://github.com/user-attachments/assets/14be119e-98b0-4f4d-96db-9dbf552728a9)
As can be seen in the image above, the same ingredient - used in different steps - is also displayed separately at the list of the needed ingredients for a recipe.

### Describe the solution you'd like

I want that the quantities of the same ingredient used in different steps will be summarized in the summation at the beginning of a recipe.

### Additional context

This is related to the reddit post I've found: [Reddit](https://www.reddit.com/r/selfhosted/comments/1acfahq/tandoor_recipes_summarise_the_ingredients_of/)

Thank you for your amazing work :) . I know you stated in the reddit post, that it is summarized in the shopping list but since I am using tandoor only as a recipe manager in my local network this doesn't really help me out.

**Comment by custardcreamdream** [comment]
This combining of ingredients _does_ happen when creating a shopping list from the recipe, but having it in the summary as well would help with the _mise en place_.

**Comment by MOHAMMED-IQRAMUL** [comment]
Could You Elaborate More as the table i see is already Summarized one, (It just has Duplicates) ?
