### ISSUE TITLE
Dynamic URLs don't include `SCRIPT_NAME`

### ISSUE THREAD

**Issue by l0b0** [TandoorRecipes/recipes#3300]
### Tandoor Version

1.5.19

### Setup

Manual Setup

### Reverse Proxy

Others (please state below)

### Other

Plain nginx

### Bug description

After configuring Tandoor with `SCRIPT_NAME=/tandoor` and `STATIC_URL=/tandoor/static/`, and then proxying the web site through nginx, the _static source_ of the web page contains URLs with the correct "/tandoor" prefix. For example, `curl --cookie /tmp/cookies.txt --cookie-jar /tmp/cookies.txt --fail --header 'Origin: http://my-host.my-domain' --show-error --silent --location https://my-host.my-domain/tandoor/search/ | grep /new` matches a single URL: `/tandoor/new/recipe/`. However, when going to the same page in a browser, only the link in the "+" drop-down on the *top* of the page points to that page.

The "+ Create" link in the middle of the page instead has a `href` of `/new/recipe/`, and so does the "NEW RECIPE" link shown by clicking the search hamburger menu.

### Relevant logs

```shell
tandoor-recipes-pre-start[10644]:   No migrations to apply.
systemd[1]: Started Tandoor Recipes server.
gunicorn[10728]: [2024-09-12 21:51:44 +1200] [10728] [INFO] Starting gunicorn 23.0.0
gunicorn[10728]: [2024-09-12 21:51:44 +1200] [10728] [INFO] Listening at: http://127.0.0.1:8002 (10728)
gunicorn[10728]: [2024-09-12 21:51:44 +1200] [10728] [INFO] Using worker: sync
gunicorn[10731]: [2024-09-12 21:51:44 +1200] [10731] [INFO] Booting worker with pid: 10731
gunicorn[10731]: /nix/store/s2cs53dn9bijfg4y3dnfdsbawr783y81-python3.11-django-4.2.16/lib/python3.11/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning: DateTimeField MealPlan.to_date received a naive datetime (2024-09-12 00:00:00) while time zone support is active.
gunicorn[10731]:   warnings.warn(
gunicorn[10731]: /nix/store/chfkad6sdkhs67fbr836knhr616a0xyl-python3.11-djangorestframework-3.14.0/lib/python3.11/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'cookbook.models.CustomFilter'> QuerySet.
gunicorn[10731]:   paginator = self.django_paginator_class(queryset, page_size)
```

**Comment by smilerz** [comment]
Your reverse proxy needs to set the script-name header.

**Comment by l0b0** [comment]
> Your reverse proxy needs to set the script-name header.

It is. The system page reports `HTTP_X_SCRIPT_NAME:/tandoor`

**Comment by smilerz** [comment]
Subfolder works with script name set. Unfortunately manual installs aren't supported. 

You can try running collect static and rebuilding vue to see if that resolves the issue.

**Comment by l0b0** [comment]
`sudo /var/lib/tandoor-recipes/tandoor-recipes-manage collectstatic` fails because the filesystem is read-only (it's trying to modify the Nix store, which is verboten). As for "rebuild vue", how do I do that?

**Comment by smilerz** [comment]
Same way as when you installed tandoor. 

If you can't collectstatic tandoor isn't going to work correctly.
