### ISSUE TITLE
Tandoor Website tells me that free plan has no limits for users and recipes

### ISSUE THREAD

**Issue by tscode** [TandoorRecipes/recipes#3303]
### Tandoor Version

Current version at tandoor.dev

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

Official tandoor.dev website

### Bug description

Thanks for the awesome platform!
Just a minor bug report, which I didn't find reported before: I recently registered at [tandoor.dev](https://tandoor.dev) and created a free space. When I go to [tandoor.dev/manage](https://tandoor.dev/manage), I see the following:

![tandoor-bug](https://github.com/user-attachments/assets/5737900a-5ac2-4e71-b60c-4bf06a4a851c)

As far as I understand the spaces system, it should be 1/1 and 2/10, right? Observed both with Firefox on Arch Linux and Vanadium on Graphene OS.

**Comment by vabene1111** [comment]
thank you very much, I will need to look into why this displays wrongly.

**Comment by vabene1111** [comment]
thank you, I actually had misconfigured the defaults and a bug in the display. both fixed now.
