### ISSUE TITLE
Date changes when adding recipe to meal plan

### ISSUE THREAD

**Issue by ensjens** [TandoorRecipes/recipes#3304]
### Tandoor Version

1.5.19

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I am trying to add recipes to the meal planner, but they get saved to the incorrect day.

For example, on the Meal-Plan page, I click on September 14 to get to the "Create meal plan entry" page.
After selecting a recipe and confirming that Start Date and End Date are both September 14, I click "Save"
The recipe shows on the calendar on September 13 (One day prior to the selected date)
If I click on the recipe and then click "Save" again, upon refreshing the Meal-Plan page, the recipe moves again one day back to September 12.

I've attached a short screen capture showing this bug.

https://github.com/user-attachments/assets/692dcfff-19c2-4882-bdf3-ac1cc74bce17

**Comment by smilerz** [comment]
Duplicate
