### ISSUE TITLE
Shoppinglist export exports already checked items

### ISSUE THREAD

**Issue by dassystem** [TandoorRecipes/recipes#3310]
### Tandoor Version

1.5.19

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

I have 8 items on my shopping list. When exporting it (via CSV or copy to clipboard) I have a list of 28 items. This larger list includes already bought / checked items. 

Not sure if this is somehow releated to https://github.com/TandoorRecipes/recipes/issues/3217 because I also have extreme issues syncing my list between devices / users. But this export problem is happening on the same machine (browser).

**Comment by vabene1111** [comment]
this might be something I forgot when refactoring the new UI. I do not think I will fix this in the current version but leave it for the Vue 3 release to be fixed, as the export is used somewhat rarely (nobody reported this in several month). Sorry for that but I need to manage my time. 

Still thanks for reporting.
