### ISSUE TITLE
Mealplan entries for Recipes without picture don't display properly

### ISSUE THREAD

**Issue by NiklasMM** [TandoorRecipes/recipes#3311]
### Tandoor Version

1.5.19

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

Yunohost, nginx

### Bug description

Recipes without images don't display correctly when used in mealplan entries: The text is shifted slightly down so that half the title is hidden
![image](https://github.com/user-attachments/assets/a9282927-fa74-4a71-8f46-dd0578b9f051)

**Comment by vabene1111** [comment]
thanks, I will fix this with the release of the new UI and Vue 3, so closing this for now.
