### ISSUE TITLE
Show Ingredient Notes By Default

### ISSUE THREAD

**Issue by royaltongue** [TandoorRecipes/recipes#3312]
### Is your feature request related to a problem? Please describe.

Currently, ingredient note are hidden behind hovering the mouse over the speech bubble icon next to the ingredient:
![image](https://github.com/user-attachments/assets/aa1591fc-5ff7-4eec-aafc-c15941f783ac)

This can cause issues for users who aren't specifically looking for these notes or don't even realize the notes are there in the first place.

### Describe the solution you'd like

Create a Space-wide setting to enable or disable showing ingredients notes by default.

### Additional context

Untare (the unofficial Android app) already shows ingredient notes by default. In the app, the notes are shown within parenthesis next to the ingredient:
![SmartSelect_20240919_230951](https://github.com/user-attachments/assets/c7ed4a08-efbc-4d0b-a88d-bcc2526a2140)

Alternatively, notes could just be shown further to the right of the ingredient name. Excuse the semi-bad mockup:
![image](https://github.com/user-attachments/assets/ac1b427d-afab-4b96-bd68-fb6db66fd01f)

**Comment by smilerz** [comment]
Duplicate

**Comment by royaltongue** [comment]
Is there an issue number you can link that this is a duplicate of? I didn't see anything while searching
