### ISSUE TITLE
Unable to Use URL Importer

### ISSUE THREAD

**Issue by jlteel** [TandoorRecipes/recipes#3320]
### Issue

I have installed Tandoor using Docker Compose and it all seems to work fine, _except_ the URL importing functionality. Literally zero URLs work. I have tried every reputable recipe site I can think of, plus my own Mealie site. This is the second time I've tried to evaluate Tandoor, and each time I have had this same problem. What am I doing wrong?

### Tandoor Version

1.5.19

### OS Version

Docker, unknown

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

**Comment by smilerz** [comment]
you've provided exactly zero information, not sure what type of help you expect anyone to provide
