### ISSUE TITLE
Autocomplete in Shopping List modul

### ISSUE THREAD

**Issue by dyxen** [TandoorRecipes/recipes#3321]
### Tandoor Version

1.5.19

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

On this new version (It was working in previous - i think 1.4.xx) autocomplete on Shopping list don't work anymore.
I tried on Desktop browser and also on Android.
For example when I start typing "Tando" or "bug" or "report" it not showing "Tandoor bug report" item to choose from. There is nothing. On previous version it showed elastic search for all the foods contained "Tando" and I just clicked what I wanted to add.

I'm a missing some settings or autocomplete is not working on this version?

Shopping menu
![tandoor1](https://github.com/user-attachments/assets/bf3356e1-31d0-45fe-a9a2-655ec920620b)

Example 2:
![image](https://github.com/user-attachments/assets/77418544-d6a1-4110-83ca-9daa90906cb6)

Foods settings
![tandoor2](https://github.com/user-attachments/assets/a8847439-9f88-4bb1-9d90-a09e50435faf)

If you need any additional info I will gladly provide.

### Relevant logs

```shell
/
```

**Comment by vabene1111** [comment]
this is kinda a feature/technical limitation. But I need to improve that. The new input accepts amount, unit and food in one string and automatically converts it into the 3. Sadly that means I can not autocomplete easily and need to build some kind of custom component. 

For now it will stay this way and I will close this but I hope to find a soltuion at some point.

**Comment by Xyaren** [comment]
This should be reopended.

I struggle when having different "styles":

- Milk
- Milk, lacrose free


The latter just get's added as Milk by the "magic"

**Comment by dyxen** [comment]
For now im using foods menu and search there. There elastic search works and you can easily add to shopping list.

**Comment by smilerz** [comment]
>  Also it should be able to open the app on the phone directly to the shopping list, but that's another issue.

![Image](https://github.com/user-attachments/assets/d2dde2aa-3008-46f1-9ac0-0aff38dceac1)
