### ISSUE TITLE
Meal plan re-adds items to shopping list after checking them off

### ISSUE THREAD

**Issue by jmawet** [TandoorRecipes/recipes#3342]
### Tandoor Version

1.5.19

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When adding meal plans to the shopping list, I am no longer able to check off ingredients for more than a few minutes. The next refresh it will just add them back. 

### Relevant logs

```shell
Gunicorn Media: False
Sqlite:  False 
        PostgreSQL: 15 
        Debug: True
```

**Comment by vabene1111** [comment]
interesting, I am basically always using meal plan based shopping lists and never had this issue. Can you check the browser console if any errors are shown when you check of the shopping list items?

**Comment by jmawet** [comment]
```
started loading locale messages
shopping_list_view.js:1 finished loading messages in  3  ms
shopping_list_view.js:1 loaded local user settings age 172898.395 
shopping_list_view.js:1 refreshing user settings from API
shopping_list_view.js:1 loaded local user settings age 172898.396 
shopping_list_view.js:1 refreshing user settings from API

manifest.json:1 Manifest: Enctype should be set to either application/x-www-form-urlencoded or multipart/form-data. It currently defaults to application/x-www-form-urlencodedUnderstand this warning
shopping/:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">Understand this warning

13 shopping_list_view.js:1 running autosync
```

That last line "running autosync" pops up once I start checking items off the shopping list. The number (13 at the time of copy/paste) keeps increasing every 10-15 seconds. By the time I typed out this sentence it increased to 15. It seems like maybe this autosync is not working properly, so it's not saving in the db that it's checked off? I'll leave that browser tab open and I'll update here if anything changes in the console

**Comment by jmawet** [comment]
Although if I check from other devices, the items did get checked off. So some amount of syncing must be working. I'll update if the items get added back to the shopping list (they usually do)

**Comment by vabene1111** [comment]
interesting, I do not see any immediate error so this will likely be some kind of logical issue. I am sorry but given my time constraints I will have to refer you to the new version once that is out at some point. There I will have to rewrite the sync logic anyway and will put additional effort into avoiding sync conflicts. 

see https://github.com/TandoorRecipes/recipes/issues/2976

**Comment by vabene1111** [comment]
so I thought about this a bit more when working on the new shopping list and noticed that the timestamps used to filter the results that are fetched are generated on the client. Is it possible that your server time and client times differ to some degree (even a few seconds might suffice). 

If so, if you want to help debug this, feel free to sync the clocks on your server and your clients (by just doing an ntp update on both) and see if your issue is resolved. 

For the new implementation I will need to find a way to be Independent of the client time, I have some ideas for that
