### ISSUE TITLE
Firefox Mobile - Navbar issues

### ISSUE THREAD

**Issue by PureLoneWolf** [TandoorRecipes/recipes#3343]
### Tandoor Version

1.5.19

### Setup

Unraid

### Reverse Proxy

No reverse proxy

### Bug description

I just moved back to Firefox based browsers recently and noticed today that on mobile (tested with FF and IceRaven) the navbar seems to float somewhere towards the bottom of the page when it's in portrait mode, until it reaches the end of the recipe and then it won't show me the last line of the recipe and takes up twice as much space as it does on Chrome based browsers.

On Chrome based browsers, it's flawless.  If I switch to landscape, it seems to work fine too.

I have attached 2 images.  1 shows the navbar "floating" with more recipe below it and the other shows that it reached the end of the file, and then seems to take up the double space.

![Screenshot_20241004_141948_Iceraven](https://github.com/user-attachments/assets/1346386f-52fe-49ed-a993-4845fc82a219)
![Screenshot_20241004_141855_Iceraven](https://github.com/user-attachments/assets/331f9b90-984c-4569-8b3a-7ae1f69e811a)

It doesn't seem to do it on every recipe, but I can't see anything consistent between recipes where it does it. 

Can I turn it off somehow?  

I am running these browsers on Android, in case that makes any difference and all browsers are fully up to date.

Thanks  in advance

**Comment by vabene1111** [comment]
Thanks for the report, this will be fixed in the new version. See https://github.com/TandoorRecipes/recipes/issues/2976
