### ISSUE TITLE
When attempting to delete an unnamed step, the step name is one less than the current step (off by one error)

### ISSUE THREAD

**Issue by cj-wong** [TandoorRecipes/recipes#3345]
### Tandoor Version

1.5.19

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

### Bug description

1. Attempt to delete an unnamed step. In this example, let's say it's step 4.
2. The dialog prompt asks `Are you sure you want to delete Step "3"?` It should say `Step "4"`.

Example:
![Screenshot 2024-10-04 235828](https://github.com/user-attachments/assets/86d8b9cb-186e-476d-b289-1e16e9e8aef7)

Notes:
- If the step is named, the prompt correctly uses the step name.
- The correct step is deleted when selected. In the example above, step 4 would be deleted, not step 3.

**Comment by ARRY7686** [comment]
Hello I want to contribute to this project pls assign me this issue

**Comment by vabene1111** [comment]
Hi, thanks for the report. since we are working on the new fronend this will no longer be fixed 

see https://github.com/TandoorRecipes/recipes/issues/2976
