### ISSUE TITLE
Expanded Recipe Nesting

### ISSUE THREAD

**Issue by Bwartastic** [TandoorRecipes/recipes#3346]
### Is your feature request related to a problem? Please describe.

# Feature Request: Linked Recipe as Ingredient with Portion Adjustment

## Context

I am a **Chef** trialling Tandoor to serve recipes to staff in a more accessible way than my usual kitchen software allows.

In professional kitchens, I manage recipes by breaking them down into individual components. For example, for a **BBQ Brisket Burger with Slaw**, I create separate recipes for:

- **Slow Cooking Rub/Braise Base**
- **Slow Cooking the Brisket**
- **BBQ Marinade**
- **Slaw Base**
- **Slaw Mayonnaise**
- **Burger Bun**
- **Potato Chips**
- **Chip Seasoning**
- **Final Assembly Recipe**

This component-based approach makes sense in a high-volume environment where ingredients are batch-prepped and reused across different dishes.

## Current Solution

Tandoor currently allows me to add an entire recipe into a 'step', but **there is no portion adjustment**. While this feature is useful, it doesn't fully solve the problem when managing recipes that depend on scaled quantities of components.

## Proposed Feature

I am requesting a feature where **recipes can be linked as ingredients** within another recipe, such that:

1. **The linked recipe appears in the ingredient summary** with the option to display that recipe's required ingredients with scaled portioning, for when not making in advance.
2. **The linked recipe is hyperlinked** so users can click through to view the detailed recipe if needed, but it remains organized within the ingredient summary for the current recipe.

### 1. Streamlined Workflow

- **Portion control**: Ensures that portions are automatically adjusted when a recipe is used as an ingredient, saving time and preventing errors.
- **Efficient organization**: Allows chefs to manage complex dishes made from multiple sub-recipes while keeping everything neatly grouped.

### 2. More Efficient Sharing of Components for All Users

- **Reuse of ingredients**: This feature would benefit all Tandoor users, not just professional chefs. Home cooks and small-scale users can easily reuse core ingredients (e.g., sauces, marinades, or bread) across multiple recipes without needing to re-enter them each time.
- **Simplified recipe management**: Users can create standalone recipes for commonly used components and include them in other recipes, streamlining the process of recipe creation and reducing duplicate entries.
- **Improved collaboration**: When sharing recipes, linked components will ensure that recipients can easily access and reuse components themselves, fostering a more collaborative cooking environment.

**Comment by tomtjes** [comment]
Some of what you’re requesting is already implemented. Go to your Foods list and create a new food “Slaw Base”. In the edit modal you can link it with your Slaw Base recipe. Now you can use Slaw Base as an ingredient.

**Comment by Bwartastic** [comment]
> Some of what you’re requesting is already implemented. Go to your Foods list and create a new food “Slaw Base”. In the edit modal you can link it with your Slaw Base recipe. Now you can use Slaw Base as an ingredient.

I did not know this was a feature! This takes me request 99% of the way there. Thank you.

**Comment by smilerz** [comment]
Duplicate #2284
