### ISSUE TITLE
Error importing recipe from source

### ISSUE THREAD

**Issue by whizzoo** [TandoorRecipes/recipes#3351]
### Tandoor Version

1.5.19

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

Using your demo site, but the same on my Docker setup.

### Bug description

I am trying to import the following recipe from source, but Tandoor throws this error: "There was an error importing the recipe!"

`<script type="application/ld+json">{"@context":"https://schema.org","@type":"Recipe","isPartOf":{"@id":"https://www.ah.nl/allerhande#website"},"author":{"@type":"Organization","@id":"https://www.ah.nl/allerhande#organization","name":"Albert Heijn"},"name":"Regenbooglasagne","alternateName":"","URL":"https://www.ah.nl/allerhande/recept/R-R1200481/regenbooglasagne","totalTime":"PT1H10M","image":["","https://static.ah.nl/static/recepten/img_RAM_PRD192444_1224x900_JPG.jpg"],"description":"Met deze lasagne eet je alle kleuren van de regenboog! De kleurige laagjes zijn niet alleen een feest voor het oog, maar ook voor je buik. Mogen wij aanschuiven?","keywords":"vooraf te maken, oven, pasta, hoofdgerecht, wat eten we vandaag","recipeYield":"4","recipeCategory":"hoofdgerecht","recipeCuisine":"","suitableForDiet":[],"nutrition":{"@type":"NutritionInformation","calories":"895 kcal energie","fatContent":"49 g vet","saturatedFatContent":"23 g waarvan verzadigd","carbohydrateContent":"60 g koolhydraten","proteinContent":"46 g eiwit"},"recipeIngredient":["3 el milde olijfolie","400 g verse spinazie","200 g zuivelspread naturel","500 g biologische gekookte bieten","1.5 el balsamicoazijn","1 middelgrote ui","300 g half-om-halfgehakt","390 g basis tomatensaus Italiaanse kruiden","12 bladen biologische lasagnebladen volkoren","350 g pompoen lasagnebladen","200 g geraspte milde kaas 45+","4 el water"],"recipeInstructions":[{"@type":"HowToStep","position":1,"name":"stap 1","text":"Verwarm de oven voor op 200 ºC."},{"@type":"HowToStep","position":2,"name":"stap 2","text":"Verhit de olie in een koekenpan, voeg de spinazie in delen toe en laat slinken. Laat de spinazie uitlekken, hak grof en meng met de zuivelspread. "},{"@type":"HowToStep","position":3,"name":"stap 3","text":"Breng op smaak met peper en eventueel zout."},{"@type":"HowToStep","position":4,"name":"stap 4","text":"Snijd de rode bieten in stukken, doe samen met de balsamicoazijn in de hakmolen en maal grof. Snipper de ui."},{"@type":"HowToStep","position":5,"name":"stap 5","text":"Verhit de rest van de olie in een hapjespan en bak de ui 2 min. op middelhoog vuur."},{"@type":"HowToStep","position":6,"name":"stap 6","text":"Voeg het gehakt toe en bak 3-5 min. rul. Voeg de tomatensaus toe en roer door."},{"@type":"HowToStep","position":7,"name":"stap 7","text":"Breng op smaak met peper en eventueel zout."},{"@type":"HowToStep","position":8,"name":"stap 8","text":"Bedek de bodem van de ovenschaal met een dun laagje tomatensaus. "},{"@type":"HowToStep","position":9,"name":"stap 9","text":"Bedek met de helft van de lasagnebladen, de rest van de tomatensaus, de andere helft van de lasagnebladen, de pompoenlasagnebladen en de spinazie."},{"@type":"HowToStep","position":10,"name":"stap 10","text":"Dan weer de helft van de lasagnebladen, het bietenmengsel en de rest van de lasagnebladen. "},{"@type":"HowToStep","position":11,"name":"stap 11","text":"Meng de zuivelspread met de geraspte kaas en het water en verdeel erover. "},{"@type":"HowToStep","position":12,"name":"stap 12","text":"Bestrooi met de rest van de kaas. Bak de lasagne in 35-40 min. gaar. Dek de lasagne eventueel na 25 min. af met aluminiumfolie als-ie te donker wordt."},{"@type":"HowToStep","position":13,"name":"stap 13","text":"Haal uit de oven en laat 5 min. staan voor het serveren. "}],"aggregateRating":{"ratingValue":4.279071,"ratingCount":172},"datePublished":"2024-08-16"}</script>`

Looking at the console output of my docker container, it seems to be related to the "org_url" parameter that recipe scrapers uses.

### Relevant logs

```shell
ERROR:django.request:Internal Server Error: /api/recipe-from-source/

Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner

    response = get_response(request)

               ^^^^^^^^^^^^^^^^^^^^^

  File "/opt/recipes/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/recipes/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view

    return view_func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/recipes/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view

    return self.dispatch(request, *args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/recipes/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch

    response = self.handle_exception(exc)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/recipes/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception

    self.raise_uncaught_exception(exc)

  File "/opt/recipes/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

    raise exc

  File "/opt/recipes/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch

    response = handler(request, *args, **kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/recipes/cookbook/views/api.py", line 1461, in post

    scrape = scrape_html(html=data, org_url=url, supported_only=False)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/recipes/venv/lib/python3.12/site-packages/recipe_scrapers/__init__.py", line 842, in scrape_html

    host_name = get_host_name(org_url)

                ^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/recipes/venv/lib/python3.12/site-packages/recipe_scrapers/_utils.py", line 288, in get_host_name

    return url_path_to_dict(url.replace("://www.", "://"))["host"]

           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^

TypeError: 'NoneType' object is not subscriptable
```

**Comment by smilerz** [comment]
Looks like the website is blocking the scrape.

**Comment by whizzoo** [comment]
@smilerz I think it might, but shouldn't the snippet have enough information to create the recipe anyway?

**Comment by smilerz** [comment]
> @smilerz I think it might, but shouldn't the snippet have enough information to create the recipe anyway?

The webpage retrieved reads "Access Denied"

**Comment by whizzoo** [comment]
@smilerz This is true, but is there a need to access the website at all if the snippet contains all the recipe information? When I enter the URL in Tandoor I expect it to fail (and it does), but I was thinking that for the snippet it would work because it just needs to parse the JSON.

When I try the same in recipe scrapers, the recipe gets parsed
![image](https://github.com/user-attachments/assets/b7e647bb-ce76-4888-a535-95a1e3c370fe)
