### ISSUE TITLE
Meal Plan Calendar Places Meal a Day ahead after Refresh

### ISSUE THREAD

**Issue by stoltenbergnathan** [TandoorRecipes/recipes#3355]
### Tandoor Version

1.5.20

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When creating a meal plan and setting the date range the meal at first shows up on the correct dates in the calendar. After refreshing the page the meal plan moves backwards a day. When opening the edit page for the meal plan and pressing save (without changing the dates) and then refreshing the meal plan again moves back. This can be repeated until the current day.

**Comment by smilerz** [comment]
duplicate #2171

**Comment by AlanMW** [comment]
What @stoltenbergnathan is experiencing is a similar but different issue that I was able to resolve by adding the `TZ=America/Chicago` environmental variable... it should likely be a default in the compose / .env file for fresh installs.

**Comment by stoltenbergnathan** [comment]
@AlanMW after setting a TZ in the `.env` file my problem went away.

**Comment by vabene1111** [comment]
while this is a fix for you who are using this only in a single timezone it appears that this must be an issue for all clients in a different timezone than the server. 

I will need to look into that.

**Comment by zkhcohen** [comment]
> while this is a fix for you who are using this only in a single timezone it appears that this must be an issue for all clients in a different timezone than the server.
> 
> I will need to look into that.

This issue appeared between version [1.5.15](https://github.com/TandoorRecipes/recipes/releases/tag/1.5.15) and version [1.5.20](https://github.com/TandoorRecipes/recipes/releases/tag/1.5.20), not as far back as November 2022. Furthermore, my time zone and configuration haven't changed between the versions.

Shouldn't this issue be reopened and tagged as a bug for tracking purposes? I'm unsure why it was closed.

**Comment by vabene1111** [comment]
probably should but I am drowning in issues. I have using only timezone aware datetime stamps on the agenda for #2976 and hope i dont forget it
