### ISSUE TITLE
Import Website via Chat GPT share link

### ISSUE THREAD

**Issue by krowvin** [TandoorRecipes/recipes#3362]
### Is your feature request related to a problem? Please describe.

After spending a while to find a decent gingerbread recipe I just decided to use AI to give me a recipe base. 

I tried to import this into the website link importer and got an error. (Fairly generic)

### Describe the solution you'd like

Please allow importing via public shared AI chats for link imports. 

### Describe alternatives you've considered

Copy and paste works okay but it doesn't do the auto formatting and placing of recipe steps. 

### Additional context

Sample Link:

https://chatgpt.com/share/670b001d-15bc-8002-a2a9-1b3f1c3f15a5

**Comment by smilerz** [comment]
The import library requires the source site to provide data in a structured format.
