### ISSUE TITLE
How to get and use access tokens for api requests

### ISSUE THREAD

**Issue by a-waider** [TandoorRecipes/recipes#3370]
### Issue

Hello,

in addition to https://github.com/TandoorRecipes/recipes/issues/3249 I want to create a service which syncs the recipes with KptnCook. I was already able to download the recipes from KptnCook and now need to upload them via the API to Tandoor.

All API requests should be behind some authentication and I found two different APIs for that purpose:
- /api-auth-token: Gives me a permanent redirect which then gives me a 405 with this response `{"detail":"Method \"GET\" not allowed."}`
```
curl --data '{"username":"username","password":"password"}' https://tandoor.dev/api-token-auth -v -L
```
- /api/access-token: Gives me a 403 with this response `{"detail":"Authentication credentials were not provided."}`
```
curl --data '{"username":"username","password":"password"}' https://tandoor.local.haus/api/access-token -v -L
```

Could someone elaborate how to get an API token?

Also I didn't saw any references on how to use these API tokens. Is the usage documented anywhere?

Thanks!

### Tandoor Version

1.5.20

### OS Version

Docker

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

**Comment by smilerz** [comment]
Under the api section of /settings/

**Comment by a-waider** [comment]
@smilerz There is no section called /settings

**Comment by smilerz** [comment]
> @smilerz There is no section called /settings

That's the url.  Or you can navigate via the menu.
