### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by Cochonnes** [TandoorRecipes/recipes#3371]
### Tandoor Version

1.5.20

### Import URL

https://www.chefkoch.de/rezepte/197781083682428/Schneller-Nudelauflauf.html

### When did the issue happen?

When importing recipes from a URL (chefkoch.de, hellofresh.com). 
I tried with other URLs too. At first they gave the same error but after something happened I was able to import them. Cant say for sure if it was related to container restart or not. 

### Response / message shown

```shell
Failure
There was an error importing the recipe!
Invalid Url

and from "Network":

POST /api/recipe-from-source/

HTTP 403 Forbidden
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Authentication credentials were not provided."
}
```

**Comment by Cochonnes** [comment]
I use a fork of Nginx Proxy Manager with Crowdsec. Tho it worked fine for a while before it suddenly stopped working. I have only updated Tandoor to the latest version like 2 weeks ago. Besides that I made no changes.

**Comment by smilerz** [comment]
for whatever reason your reverse proxy is interfering with the django session and losing authentication.  You will need to seek help with that issue elsewhere though.

**Comment by Cochonnes** [comment]
Thanks for that direction tho. I think I might have found the issue. After importing a recipe, crowdsec decided to ban an IP. After removing it from the ban list, I was able to import again. Only weird thing is, that the banned IP is appareantly related to Hetzner and none of my services are related to them. Anyways, I think that's the cause, thanks for the help.
