### ISSUE TITLE
Ingredients of steps are not added together for ingredient summary

### ISSUE THREAD

**Issue by Exterminas** [TandoorRecipes/recipes#3376]
### Tandoor Version

1.5.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

The ingredient summary does not add the same ingredients together (see screenshot with 2x "Zucker").
As long as there are no comments I would expect that the entries are getting added/merged.
![image](https://github.com/user-attachments/assets/f43d0979-ed35-4bd3-85eb-8b1d70dc771c)

**Comment by smilerz** [comment]
Duplicate
