### ISSUE TITLE
images are not imported while importing .paprikarecipe file

### ISSUE THREAD

**Issue by Kashif-Nadeem** [TandoorRecipes/recipes#3393]
### Tandoor Version

vabene1111/recipes:latest

### Import URL

We import from .paprikarecipe file

### When did the issue happen?

We newly installed Tandoor using docker compose file and used nginx reverse proxy. We exported recipes from paprika as .paprikarecipe files and imported them inside tandoor. Images are not imported while recipes are imported.

Please guide us to solve this issue.

### Response / message shown

```shell
I don't find any specific error in server logs.
```

**Comment by vabene1111** [comment]
I think this has already been fixed with #3361
Will release that update soon
