### ISSUE TITLE
Ingredient autosort from import implemented on recipe edit

### ISSUE THREAD

**Issue by Sebbyyy** [TandoorRecipes/recipes#3405]
### Is your feature request related to a problem? Please describe.

Streamlining recipe edit if inappropriately made

### Describe the solution you'd like

The autosort of ingredients that is available on recipe import to be implemented on recipe edit too and the ingredients once selected on recipe import, the page can scroll. However, if you pick up an ingredient on recipe edit - the page is locked from scrolling. I assume this is an HTML setting or something?

### Describe alternatives you've considered

Zooming out. Reimporting. All can work but are very fiddly and not good.

**Comment by vabene1111** [comment]
I dont see why autosort would be required in recipe edit as this is the page where you manually edit stuff as auto sort is a very rudamentary sorting. Scrolling and all other UI issues will be sorted out only in #2976

**Comment by mamoit** [comment]
I know that this ticket is closed, but I just wanted to explain my user experience.

Some blogs don't support auto import, and they are too niche or disorganized to be bothered to implement an importer.
The ones I've encountered usually have the ingredient list at the top and then a sequence of steps.
I have previously made the mistake importing all the ingredients into the first step while being sure that I could auto sort them after the fact given that I had done it previously in imported recipes.
I needed to look for and find this issue to realise that the auto sort is indeed not available while editing a recipe.

**Comment by vabene1111** [comment]
I understand thee desire but in my opinion the auto sort function is simply to bad to be used in the recipe directly. It only works if an food is mentioned by its name in the steps text and if it cant find it it will put everything in the first step. I am not sure if more people would mess up their recipes by using this than actually fixing them 🤔
