### ISSUE TITLE
Editing Recipe Issue

### ISSUE THREAD

**Issue by redstormsju** [TandoorRecipes/recipes#3414]
### Tandoor Version

1.5.24

### Setup

Docker / Docker-Compose

### Reverse Proxy

jwilder's nginx proxy

### Bug description

When editing a recipe, the Save, View, Save & View, Delete buttons are not responding.  Getting "Failure
There was an error updating a resource!"

### Relevant logs

```shell
Logs do not show this error!
```

**Comment by redstormsju** [comment]
> Do you have DEBUG enabled? Does anything appear in the browser console?

DEBUG mode is not enabled!  If I click on save one to many times, eventually I get 504 Error, Server Timed out....perhaps I have to give it some time to process the edit and save after clicking it the first time?  It's been more responsive than this before today.

**Comment by redstormsju** [comment]
> Can you enable DEBUG, restart the container and confirm that the issue persists?

Will do!  I just edited a recipe and click on save & view, it took about 15 -30 second delay in processing the request. 
 I will enable DEBUG now and restart and see if it responds the same.

**Comment by redstormsju** [comment]
> Can you enable DEBUG, restart the container and confirm that the issue persists?

Ok....enabled DEBUG, restarted the container!  Seems to be a bit quicker to respond to the command to Save & View!  
Is keeping DEBUG enabled safe enough or should I go back to disabled?  It seemed that when disabled, the command to save just too a bit longer than it seems to be doing with debug enabled!

**Comment by smilerz** [comment]
I always keep DEBUG always enabled.  I doubt many would notice a difference.

**Comment by redstormsju** [comment]
> I always keep DEBUG always enabled. I doubt many would notice a difference.

Thank You! I keep it enabled...so far it seems that the response to clicking the action buttons at the bottom of the page when editing a recipe has a quicker response to when debug is off.
