### ISSUE TITLE
Auto-Planner button not accessible in mobile resolutions

### ISSUE THREAD

**Issue by rodgerabbit** [TandoorRecipes/recipes#3415]
### Tandoor Version

1.5.24

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

The button / functionality to auto create a meal plan is only visible in a menu that can only be reached on resolutions higher than 992px. I would expect the functionality to be there at the "+"button in smaller resolutions. 

Desktop view:
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/a30b171f-82b8-4d64-aa05-e8e8140863b2">

Mobile view (<992 px)
<img width="641" alt="image" src="https://github.com/user-attachments/assets/0f019a4c-340c-4ee8-aa09-fa361a46e651">

**Comment by vabene1111** [comment]
will be fixed in #2976

**Comment by Lemeri123** [comment]
is this issue still unresolved?? @vabene1111 , @rodgerabbit
