### ISSUE TITLE
iframe not working

### ISSUE THREAD

**Issue by 6RomN6** [TandoorRecipes/recipes#3430]
### Issue

Hi

I use a  Tandoor CT on Proxmox. The CT is made with the script form here: [Proxmox VE Helper Scrips](https://community-scripts.github.io/ProxmoxVE/scripts?id=tandoor)

I would like to embeed Tandoor in a iFrame in my visualisation of my Home Automation (ioBroker) 

I have modified allready different things an in the meantime i get a Header were xFrame are not deny

I modified /etc/nginx/conf.d/tandoor.conf

>  `location / {
        proxy_set_header Host $http_host;
        proxy_pass http://unix:/opt/tandoor/tandoor.sock;
        add_header X-Frame-Options "Allow-From http://192.168.1.10/" ;
        add_header Content-Security-Policy "frame-ancestors http://192.168.1.10/" ;
        proxy_hide_header X-Frame-Options;
    }
'

the same i added at /etc/nginx# nano sites-enabled/default

but it still not works, i'm not sure if it is the right place to ask but i have no more ideas to fix the problem

### Tandoor Version

1.5.24

### OS Version

Debian

### Setup

Others (please state below)

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Other

[Proxmox VE Helper Scrips](https://community-scripts.github.io/ProxmoxVE/scripts?id=tandoor)

**Comment by smilerz** [comment]
https://docs.tandoor.dev/install/homeassistant/

**Comment by 6RomN6** [comment]
For me is not clear, how a home assistent add on can help me. Because there is no homeassistant server in my system, i just wan't to add a iframe into a website in my local network and i search where it is blocked?

**Comment by Blackspell01** [comment]
```
proxy_hide_header X-Frame-Options;
add_header Content-Security-Policy "frame-ancestors https://xxx.yyy.de" always;
```

where xxx.yyy.de is the site tandoor should be embedded into an iframe works for me perfectly
