### ISSUE TITLE
Ingredient Note Icon collides with step text

### ISSUE THREAD

**Issue by cgspeck** [TandoorRecipes/recipes#3440]
### Tandoor Version

1.5.24

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

On certain devices and certain browser window sizes the ingredient note icon collides with step text when viewing a recipe, making it difficult to read, like in the screenshot below.

Affected browsers:

* Chrome 131.0.6778.140 on Windows 11
* Firefox 133.0.3 on Windows 11

Affected devices:

* Pixel Tablet

It is not desirable to have to resize the browser window and also not possible in some cases (i.e. the Pixel Tablet)

![image](https://github.com/user-attachments/assets/0feff2e4-efca-4b09-80cf-a527e85f814e)

**Comment by vabene1111** [comment]
will not be fixed in old version #2976
