### ISSUE TITLE
Improve printed recipe layout

### ISSUE THREAD

**Issue by AliveDevil** [TandoorRecipes/recipes#3441]
### Is your feature request related to a problem? Please describe.

When printing a recipe it is possible, that a step title and step instructions is broken up by page bounds.

### Describe the solution you'd like

Step title and step content should be joined by "break-inside: avoid"

### Additional context

In `app.min.css`:
```
@media (print) {
  .recipe__step {
    break-inside: avoid;
  }
}
```
Or something like:
```
@media (print) {
  .step__name { break-after: avoid; }
  .step__details { break-before: avoid; }
}
```

**Comment by vabene1111** [comment]
hi, thanks for the feedback, makes sense. As I am rewriting the frontend this will not be implemented in the old branch. #2976
