### ISSUE TITLE
Missing SupermarketView when building manually

### ISSUE THREAD

**Issue by plecos** [TandoorRecipes/recipes#3443]
### Tandoor Version

latest

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

I am building manually.  I have cloned the git repo, and am at the stage to build the vue.  I get the following error:

`
Module not found: Error: Can't resolve '/var/www/html/recipes/vue/src/apps/SupermarketView/main.js' in '/var/www/html/recipes/vue'
`

I looked for this folder, and cannot find it.  I re-cloned to another directory, and it is missing there as well.

**Comment by plecos** [comment]
I happen to have an older copy that does have the folder (dated 4/30/2023), so it appears to be missing from the master branch.

**Comment by smilerz** [comment]
Manual installation can be found [here](https://docs.tandoor.dev/install/manual/). 

Unfortunately no further support is provided, too many variables in manual installation for us to be effective.
