### ISSUE TITLE
Combine ingredients and quantities on the ingredients list

### ISSUE THREAD

**Issue by micotta** [TandoorRecipes/recipes#3444]
### Is your feature request related to a problem? Please describe.

Currently if an ingredient is called for in multiple steps, the ingredient will appear twice in the recipe ingredients list. This is confusing and unwieldy to look at.
![vivaldi_1UPObtgdqq](https://github.com/user-attachments/assets/750a16f5-8c78-48b6-ac08-f1e12b0aa3b5)

Here is the list of ingredients where some, like smoked paprika, appear in multiple steps:
![vivaldi_H1Erc3tzEJ](https://github.com/user-attachments/assets/11e901c3-b40d-477a-8292-c3114ad04994)

### Describe the solution you'd like

A toggleable option on the recipe editor that allows for Tandoor to combine the ingredients and their quantities when a user views the recipe.

### Describe alternatives you've considered

Not adding ingredients in more than one step, but this defeats the purpose of assigning ingredients to a step

**Comment by smilerz** [comment]
Duplicate
