### ISSUE TITLE
It's possible to repeat properties for the same food

### ISSUE THREAD

**Issue by igorsantos07** [TandoorRecipes/recipes#3447]
### Tandoor Version

1.5.24

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

1. open a food edit page
2. press the red "add all properties" button more than once
3. get surprised with repeated properties all over

That button should only add properties absent from the current food.
Bonus points if such buttons had tooltips, so we understand better specially what the red button does.

**Comment by vabene1111** [comment]
irrelevant because auf #2976
