### ISSUE TITLE
List users inside the main UI

### ISSUE THREAD

**Issue by igorsantos07** [TandoorRecipes/recipes#3452]
### Is your feature request related to a problem? Please describe.

Related trouble to create new users have been reported in the past (#3257, #2348 are the ones I found easily, besides my own headache). That's probably the reason why there's even a FAQ about this.

### Describe the solution you'd like

Why not create a quick list of Users, showing the Spaces they belong to, and a note "to invite a user, go to the Space Settings"?
This could go on the top-right menu, and solve the issue of users looking around like John Travolta :joy: 

### Describe alternatives you've considered

Creating a fully-fledged user editing page shouldn't be necessary, as every user can edit their own data and one can be created/deleted from the Spaces. However, if that seems easy enough, being able to manage that from a centralized list could be useful.

### Additional context

I would also suggest adding a link to the Docs and FAQ pages directly in the bottom of the top-right menu - along with the GitHub link, for instance.

**Comment by smilerz** [comment]
Spaces are private listing users across spaces won't ever be supported.

**Comment by igorsantos07** [comment]
A simple sentence "no we won't", without even explaining a single reason? :disappointed: 

There's a list of Spaces on the menu. The database is a single one. The menu also has "System" and "Admin" entries, which are totally administrative. Why "won't ever be supported" an administrative list of users, showing the spaces they belong to? What's the blocker?

As you could read above, I gave a couple of reasons why users get confused, to the point even a FAQ needed to be written because people kept asking the same confusing thing. Please, look at the problem instead of simply closing the issue, leaving confusing behavior on the system without second thought.
Remember: if your system needs a manual, it means it's not clear to the user. Interfaces should be intuitive, not questioned about. My idea, while still flexible, would be enough to point to new users a way to find what they're looking for, without needing to hunt down a FAQ.
