### ISSUE TITLE
Import from websites, formating of instructions is lost

### ISSUE THREAD

**Issue by maggotnap** [TandoorRecipes/recipes#3453]
### Tandoor Version

Tandoor (HEAD) - 1.5.24 (Self Hosted)

### Import URL

https://iamhomesteader.com/jalapeno-corn-nuggets/#wprm-recipe-container-146755

### When did the issue happen?

The import works great, but a few oddities. : 

1. A separate summary line is being added into the instructions (see below highlighted line)
2. The numbering bullet get stipped and is not inserted (See below green dot)
  
Could be my setup or settings, but I can't see how to force the formating to be imported.

External website instructions- (https://iamhomesteader.com/jalapeno-corn-nuggets/#wprm-recipe-container-146755)
![image](https://github.com/user-attachments/assets/e2c8026e-e079-4eb3-b443-bcd5815fae20)

Imported recipe
![image](https://github.com/user-attachments/assets/bb602125-44a8-4caa-b5c0-fa9a5a940a4f)

**Comment by vabene1111** [comment]
sadly if the format gets trough or not is dependent on the data the website provides, there is not much I can do if the data is bad.

**Comment by maggotnap** [comment]
What if all the imported webpages have the same behavior and output?
This doesn't seem to be a isolated issue for one webpage.

Thanks
