### ISSUE TITLE
Simplify Docker Setup with SQLite

### ISSUE THREAD

**Issue by Silther** [TandoorRecipes/recipes#3455]
### Describe the solution you'd like

It would simplify the setup if we could use an integrated SQLite database without the need to run separate services like postgres and nginx.
SQLite is for more than enough, as setup for a family or group of of friends will most likely not have enough recipes to reach the limit of SQLite

### Additional context

I would never suggest such a big change, but as the frontend gets fully rewritten, the backend could also get an overhaul.

**Comment by smilerz** [comment]
just don't create the postgres and nginx containers

**Comment by smilerz** [comment]
The tandoor container would look exactly the same with the addition of a port.  The webservice runs on port 8080, expose it on whichever port makes sense in your environment. 
You cannot change the user the container is running as.
