### ISSUE TITLE
Add up ingredients

### ISSUE THREAD

**Issue by Silther** [TandoorRecipes/recipes#3456]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/a6f53454-1636-44b7-8cf6-b48b79e5f85e)

If I have 50g sugar in Step 1 and 30g in Step 2 it currently shows me 50g, 30g and does not add it up to 80g in the recipe ingredients list.

### Describe the solution you'd like

It would be nice if it could add up the ingredients **without** comments be default and would allow to add up the ingredients **with** an comment via a setting.

### Additional context

for example
``` 
step 1
10 g sugar comment ""
step 2
20 g sugar comment ""
step 3
30 g sugar comment "can be reduced without effecting the consistency"
step 4
40 g sugar comment "use brown sugar"
```

sugar from step 1-3 can be combined and added up but the comment in step 4 is more important so I toggled the add-up for this ingredient of.

maybe that makes it to complex or there is a better way to do it.

**Comment by smilerz** [comment]
duplicate
