### ISSUE TITLE
Allow flexible amounts of ingredients

### ISSUE THREAD

**Issue by Silther** [TandoorRecipes/recipes#3457]
### Is your feature request related to a problem? Please describe.

Some recipes use flexible amounts of ingredients like 50-70g of sugar, would be nice if that could be added.

### Describe the solution you'd like

you could add an minimal amount and max amount to the database.
that could be done two via separate fields (which you could reach the same way you can disable Amounts) or automatically switch to flex amount if some one enters "70-90" and take the value before "-" as min and after as max amount.

normal fix amounts would have min_amount=may_amount

**Comment by smilerz** [comment]
this is a duplicate request too.  but I'll note this won't ever be implemented.  Adds complexity for no good reason.
