### ISSUE TITLE
Sorting/search should always ignore accents

### ISSUE THREAD

**Issue by igorsantos07** [TandoorRecipes/recipes#3458]
### Is your feature request related to a problem? Please describe.

This is probably building on top of #344 and #1436.
Simply put, accented chars go to the end of the sorting order, instead of following the main letter "inside" the accent symbol.
Similarly, searching for a word missing the accent doesn't yield the accented recipe, but usually it should - Cookmate does, for instance (IIRC, it's French-based).

### Describe the solution you'd like

I'm not familiar with Django, but I would guess such a robust system could have a better solution for those issues.

That said, an agnostic solution I've seen in the past is creating slug fields, or "sanitized search" fields based on the title and possibly the foods too.
That way, `Arroz à  Piamontese` (notice the "accidental" double-spacing) would be actually sorted by a field with `arroz_a_piamontese`, thus coming before `Arroz com brócolis` (sorted by `arroz_com_brocolis`). Not sure how useful a complete slug would be, but it's usually an easy way to sanitize spacing, punctuation and accented chars.

Care should be taken to not replace accented chars with meaningless chars, though, as this would ruin sort and search as well - no `arroz-com-br-colis`, for instance.

**Comment by smilerz** [comment]
These settings are available under search settings.
