### ISSUE TITLE
Hitbox adjustment

### ISSUE THREAD

**Issue by Silther** [TandoorRecipes/recipes#3460]
### Is your feature request related to a problem? Please describe.

A small improvement to make it easier to click at the first character of a new line as the hitbox for that is very small

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/7ba2a262-0bbc-4748-a70a-1696fdb1839a)

allow clicking a few millimetres in front of the first letter of a line to put the mouse pointer there

**Comment by vabene1111** [comment]
there will be no more changes to the current version because of #2976
