### ISSUE TITLE
food deletion fails

### ISSUE THREAD

**Issue by Silther** [TandoorRecipes/recipes#3462]
### Tandoor Version

1.5.24

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Cloudflared

### Bug description

the food "milc" was created by "paste ingredients".
because of spelling errors I created new food elements but deleting the old ones did not work, i double checked that they no longer are in any recipe.
![image](https://github.com/user-attachments/assets/cc586291-c080-4e35-b1ae-8e168a56f1ca)

**Comment by vabene1111** [comment]
must be fixed in #2976

**Comment by smilerz** [comment]
as a work around you can:
- merge them with another food (`/list/food/`)
- `Delete Steps not part of a Recipe` and `Delete Ingredients not part of a Recipe` in the admin interface (in `Steps` and `Ingredients` respectively).  This will allow you to delete the orphaned foods.
