### ISSUE TITLE
Calendar export

### ISSUE THREAD

**Issue by tdvantine** [TandoorRecipes/recipes#402]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.
**Describe the solution you'd like**
Export all of the meal plan to ical instead of just a week. Stretch goal, have it be updatable, which yes would require that Recipes/Tandoor have a cal server to be able to do so, but would be great to be able to update the meal plan and it update in calendar.  
**Describe alternatives you've considered**
Possible a docker add on, but that wouldn't be useful for the manual install folks.

**Comment by vabene1111** [comment]
a caldav server would actually be pretty cool .. i have absoultly no idea on how that would work but the idea is very interesting ..

maybe one day i will get around to this but dont expect this to happen soon sadly 🙈

**Comment by tdvantine** [comment]
I have imported the dev branch into VS Code to go through and see how the current cal function works and that is super simple set up it seems. (given i have just started django and know a little python) but would something like this ([Radicale](https://pypi.org/project/Radicale/)) be of use?

**Comment by vabene1111** [comment]
Radicale looks good i guess and yes the current implementation is extremly basic 😂 

The thing i am considering is that i do not want to inflate this project to much by adding more and more dependencies. 
I am not sure how much the caldav feature would be used by different users thus it would be great if it was an add on to the core application, but that would mean that i needed to add some kind of addon support 😂 

i guess you could play around with it on a sepearte branch and we would see how large/complicated it becomes

**Comment by tdvantine** [comment]
I haven't looked into it so I could be very wrong, but hopefully one could maybe ditch icalendar in place of Radicale, but that is just a presumption.
I wouldn't be very fast at implementing it, just because I would be learning as I go, but I am not opposed to it at all.

**Comment by vabene1111** [comment]
play around if you want and if not i will leave this issue open and some day come back to it :)

**Comment by tdvantine** [comment]
Ok, thought of a different approach, haven't looked into which would be easier to implement but instead of reinventing the wheel and having a local hosted calendar server, use google calendar/ical calendar and supply a link to Tandoor/recipes that allows it to write to that calendar...thus the calendar is hosted elsewhere. NOW, that said, I much much much prefer a selfhosted option than having the likes of that large number company or the pesky fruit company with more data than they already have.

**Comment by vabene1111** [comment]
i guess one would have to ivestigate how caldav really works, i think it is basically just a pretty formatted text file, should not be to hard to supply that but maybe i am wrong.

Integration with only google is definitely not possible, i would need to be something universal as many people who self host run their own calendar (including me)

**Comment by MarcusWolschon** [comment]
Would a public URL to download the .ics export without having to log in first be a first step?
(With some kind of random access token in the URL)
That URL could then be added as an external calender to Google, Outlook, ... whatever.
So you have a selectable calendar for your meals in your favorite calender application.

**Comment by tdvantine** [comment]
Potentially a great first step. Its been a hot minute since this was opened, so i dont fully remember everything, but i believe Tandoor stores on a week by week, and not a full calendar, but yes anything is better than nothing!

**Comment by vabene1111** [comment]
how would this work ? you would add a "remote" ics to your calendar and that ICS would always container the current and last/next week for example ?

would the old entries if removed from the ICS get removed from the calendar ? 

if so this would indeed be a pretty simple solution.

**Comment by MarcusWolschon** [comment]
I don't know if it works.
 Should be easy to test with a hosted, static .ics file and then replacing that file

**Comment by vabene1111** [comment]
yes, i noted this questions for myself to test or if anyone wants to help for someone else to test and write down the answers for when i implement this.

**Comment by delize** [comment]
Happy to help test this when implemented. Really looking forward to a ical/caldev/ics implementation where the import calendar feature is imported into Google Calendar dynamically. :)

**Comment by vabene1111** [comment]
merged this with another issue
