### ISSUE TITLE
Apostrophes showing up as unicode hex characters

### ISSUE THREAD

**Issue by jt196** [TandoorRecipes/recipes#423]
### Version

Version: 0.14.2

### Bug description
On import, apostrophes show up as unicode hex characters: `&#x27;` and `&#8217;`

If I try to import [this recipe](https://thewoksoflife.com/homemade-chiu-chow-sauce/), apostrophes appear correctly in the instructions, but show up as `&#x27;` (unicode hex text for apostrophe) in the ingredients list, both in editing and preview mode. 

Importing [this recipe](https://cookieandkate.com/overnight-oats-recipe/), apostrophes show up as `&#8217;` (unicode hex single quote) in the instructions text. This looks alright in the preview of the recipe, but not so nice in editing mode.

**Comment by vabene1111** [comment]
i noticed something similar yesterday with a recipe a friend of mine imported .. will need to see where this comes from, i think its also having problems with umlauts

**Comment by jt196** [comment]
![image](https://user-images.githubusercontent.com/8290163/108528941-dc025500-72cb-11eb-819f-e7152c9ad71a.png)

Also titles, and ampersands.

**Comment by smilerz** [comment]
Not sure when this resolved, but appears to no longer an issue in the latest devlop commit

**Comment by vabene1111** [comment]
maybe the refactoring to recipe scrapers fixed this 🤔 maybe @jt196 can test again bur for me this works fine now as well
