### ISSUE TITLE
Source URL separate field

### ISSUE THREAD

**Issue by jt196** [TandoorRecipes/recipes#424]
**Is your feature request related to a problem? Please describe.**
Paprika has a separate field for the source URL, it would be nice to have something like this. Current behaviour is to add the source URL to the instructions text. 

**Describe the solution you'd like**
Add a separate source URL field that is populated when importing from a website. 

**Additional context**
Further down the road, this separation of data could be quite helpful in creating lists populated by recipes from different sites. 

In addition to the Source URL, Paprika has a 'source' field as well. I use this to add a more descriptive name to the source, or if the recipe has come from a book, I'll write the author name/title of the book here.

**Comment by vabene1111** [comment]
#668

**Comment by mhoenes** [comment]
In addition to a source URL field, it would be nice to have 2 more dedicated source fields for:

- the offline source (book/magazine/tv show etc.).
- the author/chef (although this could probably also be achieved by creating a tag hierarchy).

Ideally, those fields would be searchable.

**Comment by vabene1111** [comment]
i think both of these use cases could very well be solved by tags dont you ? this would also make it super easy to search and its even a very logical approach. But i will look into it when adding the source field.

**Comment by mhoenes** [comment]
The author/chef use case works pretty well for me with tags. I tried it.
For the offline source, I feel the possible values would be too numerous. Creating a tag for every single one might become tedious.

For both use cases, in the end, it comes down to how many different values one wants to manage. To a certain extent, tags are very well feasible.

**Comment by smilerz** [comment]
@mhoenes I'd consider using hierarchical tags for your offline sources.
TV
-TV Show 1
--Espisode 123
-TV Show 2

You can manage tags for the things you care about (some shows you want to keep track of, others can just get dropped into TV)  Much depends on how much data you want to maintain and how you want to search/discover your recipes.

<img width="187" alt="image" src="https://user-images.githubusercontent.com/1808639/144288219-27365f78-1c37-4ffe-adc7-8e6ba7f07e53.png">

**Comment by vabene1111** [comment]
source field is imported with the new importer
