### ISSUE TITLE
Add More Nutritional Value Fields

### ISSUE THREAD

**Issue by kushfest** [TandoorRecipes/recipes#436]
**Is your feature request related to a problem? Please describe.**
At present the nutritional values section only accepts 4 types of values, leaving no place to input other commonly tracked nutrition data. 

**Describe the solution you'd like**
It would be great to be able to input more nutrition data, as it can be important for various health and wellness related reasons. This fuller list would be a great start to cover many use cases:

Serving Size
Calories
Sugars
Carbohydrates
Cholesterol
Fiber
Protein
Sodium
Saturated Fat
Unsaturated Fat
Total Fat

**Describe alternatives you've considered**
Even better would be the ability for users to customize the nutrition fields, so they track what they want to. 
It would be awesome to have nutrition imported with recipes!

**Comment by vabene1111** [comment]
thanks for moving this into an issue. This will definitly be somethign were you can artifical nutrirional information values but i will take some time for me to add it.

There are also plans to pull data automatically from some kind of api

**Comment by MarcusWolschon** [comment]
Real world sample data in ld+json format:

`"nutrition":{"@type":"NutritionInformation","calories":"569 kcal","carbohydrateContent":"64 g","fatContent":"20 g","proteinContent":"26 g"}`

**Comment by vabene1111** [comment]
closing this because its mentioned in healt refactor
