### ISSUE TITLE
Import recipes with multiple instruction steps

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#476]
**Describe the solution you'd like**
Allow URL import of multiple steps once hhursev/recipe-scrapers#283 is complete.

**Additional context**
Likely depends on #177 as well.

**Comment by vabene1111** [comment]
the problem here is that steps are a very loosely defined thing on different websites. Some pages put every super small thing like "add water" "add salt" into separate steps while others use them the same way as i have set them up as more general parts of a recipe.

It would be cool to preserve those steps but i fear that it will be rather hard to make such a system work for all pages.
Nonetheless going to leave this open, definitely an area where the importer can be improved.

**Comment by smilerz** [comment]
> the problem here is that steps are a very loosely defined thing on different websites. Some pages put every super small thing like "add water" "add salt" into separate steps while others use them the same way as i have set them up as more general parts of a recipe.

totally agree with that - I'm curious to see how the recipe_scraper addresses it.  My guess (hope) is that each scraper is adapted to how that site manages steps.

It probably isn't workable without a way to easily collapse steps in case it over generalizes.

**Comment by vabene1111** [comment]
The scraper is really cool and i guess it handles the pages that are supported very well but i kinda hate the feeling that the lack of structure on those pages forces us to have hardcoded scrapers for individual sites 😂

**Comment by smilerz** [comment]
> The scraper is really cool and i guess it handles the pages that are supported very well but i kinda hate the feeling that the lack of structure on those pages forces us to have hardcoded scrapers for individual sites 😂

I've seen enough "standards" that it doesn't even remotely surprise me anymore.

**Comment by MarcusWolschon** [comment]
A way forward would be to already extend the preview-page that is shown after the scraper is done.
Add a label, that in the "steps" textarea everything separated by 2 newline will become a step.
That way the code is ready when the scaper outputs steps later
and the users can already do this now.
In a quick fashion when importing many receipts in a row. 
(e.g. new users moving their receipts over, who should get a good impression of Tandoor)

Limitations: All ingredients will be attached to the first step and steps will import without titles.
This limitation however is not likely to changes anyway.

**Comment by vabene1111** [comment]
i want to rewrite the preview page or even better use the standard recipe editor to do that but thats a larger job. I will try to look at this somewhat soon

**Comment by birdwing** [comment]
> Limitations: All ingredients will be attached to the first step and steps will import without titles. This limitation however is not likely to changes anyway.

Instead of "without titles" could the titles default to "Step 1", "Step 2", etc...
That would make it easier to follow

**Comment by smilerz** [comment]
Multistep recipes already default to step 1, step 2, .....

**Comment by vabene1111** [comment]
This is already working in the new importer :) closing this as I have a collective issue for that.
