### ISSUE TITLE
Feature: Guest Account / View without login

### ISSUE THREAD

**Issue by hakoerber** [TandoorRecipes/recipes#49]
Hello,

I propose a feature that allows viewing the recipes/cookbooks without a login. Could also be handled via a guest account.

I'm not sure how this would work with the current user handling in the application. If we come to a conclusion here I'd take a look how I could implement this feature.

P.S. That you for the great project!

**Comment by vabene1111** [comment]
Yes, i was thinking about something like this too. 

There are two options i see here: 

1. make a application wide setting that enables or disables public browsing and viewing of recipes. 

2. Use different permission levels for different users (and thus allow creating "guest" accounts for users with only viewing access). We would need to enable/configure some groups in the django auth framework and add the group permission checks to all functions (some work but nothing impossible). 

I think option 2 is preferable since exposing the whole application publicly is probably not what anyone wants but must people will probably want to give a hand full of users accesss.

What we then need to decide if we create user groups (e.g. guest, user, admin) with fixed permissions or if we go all in and create Permission for every type of object/function (e.g. batch edit, viewing <recipes/tags/ingredients/units/..>, ...) which is a lot of work and also needs to be considered for future updates ...

**Comment by hakoerber** [comment]
Hey, thank you for your response!

I'd actually prefer option 1. I currently got the app running publicly and it would be really great to be able to send a link to someone so they can view the recipe without any logins. If this is locked down to strictly read-only access I don't see a way to abuse it.

To try out option 2, I created a new group (`guest`) and gave it only the "view" permissions. Still, a user assigned to that group could still add/change recipces. Does that mean that permissions are currently not enforced?

If we go with option 2, I'd prefer this suggestion of yours:

> [...] we create user groups (e.g. guest, user, admin) with fixed permissions [...]

So for me personally, I wouldn't need more than this simple setup. Admins that can add users, storage backends etc, "users" that can add/change recipes and "guests" that have read-only access.

If you are interested, I will go ahead and try to implement something like this. What do you think?

**Comment by vabene1111** [comment]
i guess option 1 and 2 aren't exclusive so we can do both.

The only problem i see for option one, or at least something we need to be really careful about, is the creation of share links and loading of documents from the storage backends. I have always paid attention to security but the application also was never audited/i am no professional django developer.

I think fixed groups as you describe them are good:

- guest: search/view recipes, comment
- users: everything except admin
- admin: create/manage users, create storage sources, create storage monitors

the exact definitions of who should be able to do what are debatable. Do you want to try working on this ? its quite a big feature and if you decide that you wanna try it i wouldn't do much for a little while so we dont get to many merge conflicts (as you basically need to touch every function).

**Comment by hakoerber** [comment]
Ok, if you don't mind I'd take on this topic. I'll need to find some time though, and I also need to get familiar with the codebase (didn't do much Django stuff before). I cannot promise anything though. When I'm unsure about architectural decisions I'll get back to you. I think we should just leave this issue open for communication.

But please don't suspend your work on this project because of that :sweat_smile:. Merge conflicts are only my problem, so don't hesitate to continue developing this awesome project. And as I said, I cannot promise that I'll get this done at all, so I'd have a bad conscience if you delayed new features just because of me.

**Comment by vabene1111** [comment]
No worries and no rush! This is my first FOSS project to really get attention and contributions and i love to see people who like the thing i build mostly for myself.

If you want you can add me on discord and i can quickly walk you trough the codebase and maybe we can make the first few basic architecture decisions together. Username is vabene1111#5492, if you prefer any other platform just let me know.

**Comment by hakoerber** [comment]
> This is my first FOSS project to really get attention and contributions and i love to see people who like the thing i build mostly for myself come together and make it even greater.

Awesome, that's the spirit :+1: 

Thank you for the offer about discord. I'll ping you when I got time.

**Comment by vabene1111** [comment]
Ok so i have started work on this feature on the dev branch and a basic version is up and running. Feel free to play around and give feedback wherever you find necessary. 

some basic documentation can be found here https://github.com/vabene1111/recipes/wiki/Permission-System

**Comment by hakoerber** [comment]
Wow, nice! Really nice work! :tada: 

I'll try it out on my instance today.

In the last few days I read through the django documentation. If you're interested, I'd try to implement the second idea: Being able to view recipes (and maybe other entities) without any login. Of course this should be opt-in, e.g. via an environment variable like `ENABLE_ANONYMOUS_VIEW`.

What do you think?

**Comment by vabene1111** [comment]
definitly, should also be quite easy to implement as i used a decorator/mixing for the group checks thus you could add some code there that checks a setting and allows everything that guests can do without login. 

Or add a group called anonymous to the checks. 

The only thing you need to be careful about and that will need torough testing is that is use the group checks not only for the groups but also to check if the user is logged in and thus has certain properties that anonymous users dont have (e.g. a function might assume that because the group check passed that a username exists)

**Comment by mixedbreed** [comment]
Good idea with guest account, but would it also be an idea to set no authentication against specific ip/subnet?
Would like to present the page to Home Assistant or a screen with no need for authentication.
Thank you for your project!
My wife really appreciate it!

**Comment by mixedbreed** [comment]
Hi!
Anonymous view and guest account would be much appreciated. 
But would also like the possibility to have no authentication against certain ip/subnet.
Would like to present recipes to Home Assistant or a screen.
Thanks for your work, we (myself and my wife) really appreciate it!

**Comment by vabene1111** [comment]
I think a feature like home assistant/screens should not be based on unauthenticated endpoints but rather on a nice (REST) API or do you have any special requirements that make that not feasible ? 

The API itself could have several auth schemes e.g. basic auth or a token based authentication. IP whitelisting is, considered ip spoofing isn't to hard, probably a security risk.

**Comment by mixedbreed** [comment]
I agree with you, normally I don't see recipes as a state secret, but it could be a stepping stone in an environment. I have no special requirements, I have no programing skills of to day so would be nice if it's easily integrated.

**Comment by vabene1111** [comment]
ok, i think that both of your requirements could be satisfied without sacrificing any security or usability.

**Comment by bobokun** [comment]
While waiting for this to be implemented would we be able to achieve the same results as a "Guest mode" by enabling Django Allauth with a public provider like Google? Then people can login with Google and view but not edit.

**Comment by vabene1111** [comment]
yes this would be possible.

This might be a problem tough in the next release where a multi Tennant mode is added. I will need to look into how allauth signups can be integrated with that.

**Comment by vabene1111** [comment]
ok the follwowing two options have been added for the next release to allow OAuth signups to automatically get basic permissions

```
# Should a newly created user from a social provider get assigned to the default space and given permission by default ?
# ATTENTION: This feature might be deprecated in favor of a space join and public viewing system in the future
# default 0 (false), when 1 (true) users will be assigned space and group
# SOCIAL_DEFAULT_ACCESS = 1

# if SOCIAL_DEFAULT_ACCESS is used, which group should be added
# SOCIAL_DEFAULT_GROUP=guest
```

**Comment by romainrbr** [comment]
Hello,

Quick workaround to have an anonymous login-less account by default:
1. Create an account named `Guest` (or whatever else), and give it Guest permissions
2. Add this header to your vhost `proxy_set_header REMOTE-USER Guest;`
3. (Optional) Create a different vost without the header for authentificated users only

@vabene1111 : is there any security issues created by doing so ?

**Comment by vabene1111** [comment]
Interesting approach. Generally i am pretty confident that the security of the application is good but it has never been audited. 

The main concern i had is that all endpoints verify authentication but some might fail on proper permission checks. But i have implemented a lot of tests recently when adding the spaces feature so i hope that everything is secure

**Comment by timdonovanuk** [comment]
Until Authelia (for SSO) gets oauth support I'm looking to disable login. Is the best way still @romainrbr https://github.com/vabene1111/recipes/issues/49#issuecomment-826320872 here?

**Comment by vabene1111** [comment]
This is probably still the best way. Disabling login can simply be done by not giving anyone accounts except for the authelia reverse proxy account so that should be fine.

**Comment by fatflyingpigs** [comment]
Noticed this is tagged as a 1.0 milestone and 1.0.0 was released 4 days ago. Has this issue been implemented in the current release?

**Comment by vabene1111** [comment]
No it hasn't, i am not sure why i added that a long time ago and never thought about that again, this will likely not happen very soon as it is a major architectural decision with a lot of work which for now is better spend on other features (at least i think so). Sorry if this is important for you but for now other things have priority, but thanks for the milestone info, i will need to update that)

**Comment by DoTheEvo** [comment]
Kinda sad that its complicated and not in foreseeable future.
I finally got my cookbook up and I cant just give my family and friends the url.
Or show site to someone when we are at their machine.

Its a hurdle of invitation and logins and what feels like a commitment to people and by people, when we barely know each other and all you wanna do is show them the recipe you made last weekend.

I would geoblock at firewall level or dns (cloudflare) level, so if I am fine with security of it.. it really should not be a biggie, but I understand that it could be complicated and architectural issue

**Comment by bobokun** [comment]
> I finally got my cookbook up and I cant just give my family and friends the url.
Or show site to someone when we are at their machine.

Maybe an alternative would be to be able to click a share icon on a specific recipe that would generate a read-only link so we can share that recipe with friends/family?

**Comment by vabene1111** [comment]
That is already available

**Comment by smilerz** [comment]
> So this will never be a thing with Tandoor?

Extremely unlikely.

**Comment by ulliohura** [comment]
Are there any new Informations how to get logged in without entering the password.
I dont get it done with vhost because not knowing what to do, but i would like to use tandoor implemented in home assistant dashboard. The need to log in is annoying.
