### ISSUE TITLE
Add support for docker secrets

### ISSUE THREAD

**Issue by ahgraber** [TandoorRecipes/recipes#519]
Reopening #157 -- in order to add support for docker secrets, you have to parse environmental variables, look for the secret identifier, and then set the environmental variable from the secret in `/run/secrets`.

Looking at the dockerfile, it seems that you'd have to add this script to the image, and then call it from `boot.sh`.

If using sh, here's a script that does exactly this -- the identifier is `__FILE` (double-underscore FILE), so that would be what is referenced in docker-compose.yml.  This should work for you and the comments should help work out the logic to debug if necessary.

```sh
#!/bin/sh

# logic cribbed from linuxserver.io: 
# https://github.com/linuxserver/docker-baseimage-ubuntu/blob/bionic/root/etc/cont-init.d/01-envfile

# iterate over environmental variables
# if variable ends in "__FILE" (double-underscore FILE)
for FULLVAR in $(env | grep "^.*__FILE="); do
    # trim "=..." from variable name
    VARNAME=$(echo $FULLVAR | sed "s/=.*//g")
    echo "[secret-init] Evaluating ${VARNAME}"

    # set SECRETFILE to the contents of the variable
    # Use 'eval hack' for indirect expansion in sh: https://unix.stackexchange.com/questions/111618/indirect-variable-expansion-in-posix-as-done-in-bash
    # WARNING: It's not foolproof and is an arbitrary command injection vulnerability 
    eval SECRETFILE="\$${VARNAME}"

    # echo "[secret-init] Setting SECRETFILE to ${SECRETFILE} ..."  # DEBUG - rm for prod!
    
    # if SECRETFILE exists
    if [[ -f ${SECRETFILE} ]]; then
        # strip the appended "__FILE" from environmental variable name
        STRIPVAR=$(echo $VARNAME | sed "s/__FILE//g")
        # echo "[secret-init] Set STRIPVAR to ${STRIPVAR}"  # DEBUG - rm for prod!

        # set value to contents of secretfile
        eval ${STRIPVAR}=$(cat "${SECRETFILE}")
        # echo "[secret_init] Set ${STRIPVAR} to $(eval echo \$${STRIPVAR})"  # DEBUG - rm for prod!
        
        export "${STRIPVAR}"
        echo "[secret-init] Success! ${STRIPVAR} set from ${VARNAME}"
        
    else
        echo "[secret-init] ERROR: Cannot find secret in ${VARNAME}"
    fi
done
```

If you decide to use S6 as a process supervisor, I can provide a script that supports that as well.

**Comment by ahgraber** [comment]
If it would be helpful, I can try to make a PR for this.

**Comment by vabene1111** [comment]
Thank you, but i dont really see a reason to do this. The current option works perfectly fine and does not need a while script to parse and setup stuff. From my experience with selfhosting other services many of them use environment variables and it appears to be a perfectly fine and reasonable solution. 

There is most certainly a reason why docker secrets are cool but there are so many things that are more important than this that i dont really feel like spending time on this right now.

I can leave this issue open to come back to it in the future but currently this wont be implemented. A PR would also not be merged, as i need to understand, test und document it and thats also currently simply not possible with the time i have.

**Comment by mark-monteiro** [comment]
For reference for anyone who comes across this, support for secrets was eventually added at some point. The current configuration docs list several variables that support a `_FILE` suffix: https://docs.tandoor.dev/system/configuration

At the moment, these appear to be supported/documented:
- SECRET_KEY_FILE
- POSTGRES_PASSWORD_FILE
- AUTH_LDAP_BIND_PASSWORD_FILE
- EMAIL_HOST_PASSWORD_FILE
- S3_SECRET_ACCESS_KEY_FILE
