### ISSUE TITLE
Secret recipes

### ISSUE THREAD

**Issue by kz5ee** [TandoorRecipes/recipes#575]
**Is your feature request related to a problem? Please describe.**
Sharing recipes with friends is great but you really don't want your friends to have grandma's spicy meatball recipe since it's a family secret.

**Describe the solution you'd like**
The ability to share a specific recipe with only certain users/groups would allow you to share Bertha's famous cheesecake recipe with only those of whom are allowed to have it while keeping it organized with the rest of your recipes.

**Comment by vabene1111** [comment]
haha this is a really cool feature idea which i have not thought about yet. It is kinda hard to implement with the current architecture but its definitely something i will keep in mind in the future.

**Comment by kz5ee** [comment]
I can see it being tricky to implement.

To me the most important part of the idea is the marking of a recipe as private/secret, which would be to me the more straightforward to implement.  A bit field to the relevant table in the database, a checkbox on the create/edit page, and a page saying the recipe is marked as private just as a cursory thought on implementing that part of the feature.  I'm not sure how much refactoring that would require with current architecture.

Sharing with users/groups will definitely take far more planning before it's ready to begin implementation.

The demo looks good and once I've got some spare time I'll install it on one of my RasPi's. This project looks a lot better than a fair amount of the paid options out there.

**Comment by vabene1111** [comment]
thanks for the feedback. It would definitely be something that can be implemented, both sharing and private use but there are many little places where filtering would need to occur (selection in the meal plan, shopping list, etc.) and many possible places where data could leak which would need to be sorted out. 

That said it is certainly not impossible. I guess there will be the point where the whole permission system is reworked a little and this will be something that i will think of then.

For now, if you really need it, you could create two tennants (spaces) and store all the secret stuff in one of them. Sadly switching between spaces on one account is not yet possible so you would have to create two accounts which is kind of annoying. But this is also something planned for the future.

**Comment by kz5ee** [comment]
I don't really need it now since I'd be the only one using it, but that's not a bad workaround.  Once I get some free time I'll get the system set up.

**Comment by vabene1111** [comment]
awesome, let me know if you need any help
