### ISSUE TITLE
Recipe Ingredient Overview sum setting

### ISSUE THREAD

**Issue by momab** [TandoorRecipes/recipes#595]
### Version
Version: 0.15.2

### Bug description
When having different Steps within a recipe, adding the same ingredient with different measurements (not the unit) results in them showing up separately in the ingredients overview.

Example:
#### Overview
- 100g Reis
- 20g Nudeln
- 20g Reis

#### Step 1
- 100g Reis
- 20g Nudeln

#### Step 2
- 20g Reis

**Comment by vabene1111** [comment]
this behavior is intended. Basically there are two uses for the overview: 

1. see what you need. For this your behavior would be the most useful
2. cook with just the structured ingredient overview. For example i like baking bread and i only use the overview which has some headers to divide the different parts so i dont need to read the instructions.

There should be some rather old issue where this is discussed, basically there needs to be a per recipe setting to control if the overview sums up the ingredients or not

**Comment by sdfg2** [comment]
Given each instruction step can have its own set of ingredients, that provides the structured ingredient overview.  The summary overview would be best served as a combined list for shopping/preparing etc.

**Comment by vabene1111** [comment]
Ok so I added a setting to turn on / off the ingredient overview at the start of a recipe, it will still not sum up anything as its meant to serve as a structure but you can easily add the recipe to the shopping list to get a sum of ingredients. For now this will need to suffice as i dont want to increase the editor complexity more than needed, maybe once i got to rewriting the editor i will look into adding a sum view as well.

**Comment by sdfg2** [comment]
This shouldn't be set as closed-completed, as it's not what the report is about.  It's about adding a sum setting, not optionally showing the overview.  Please re-open, or set to completed-won't-fix so people know to search for alternatives.
