### ISSUE TITLE
Mobile view doesn't always place step instructions below ingredients

### ISSUE THREAD

**Issue by JorelAli** [TandoorRecipes/recipes#608]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.15.2

### Bug description

If you create a normal recipe with multiple steps and view the recipe on a mobile device, such as on an Android device, the instructions are written next to the ingredients instead of underneath the ingredients. An example of this can be viewed on the demo application [here](https://app.tandoor.dev/view/recipe/76). This makes viewing recipes a lot more difficult on a mobile device than it should be!

This can be reproduced easily on desktop by opening the Chrome dev tools, selecting device emulation and choosing "Pixel 2".

-----

**How it should look:**
![image](https://user-images.githubusercontent.com/4613171/117547482-b9a8e980-b027-11eb-9581-db02edba5c3a.png)

**How it actually looks (incorrect):**
![image](https://user-images.githubusercontent.com/4613171/117547472-ad249100-b027-11eb-9ed5-54f2a0d4a16b.png)

**Comment by vabene1111** [comment]
i guess i will need to change some breakpoints here so that it breaks earlier
