### ISSUE TITLE
Error Collection

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#682]
Send client errors to database so that instance administrators can share/review errors happening on clients 

- [ ] create model
- [ ] add to client functions

**Comment by smilerz** [comment]
You may not want to log to the DB - it'll create a lot of database traffic, grow the DB, etc, etc.
The [logging framework](https://docs.djangoproject.com/en/3.2/topics/logging/) that comes with DJANGO goes to files.

I use a couple open source web-apps that all seem to use the same approach - keep them in files and allow a user to open the text documents.
![image](https://user-images.githubusercontent.com/1808639/135147316-d3800888-888b-4a89-9164-9f91e43abac0.png)

**Comment by vabene1111** [comment]
interesting approach as well, i see that files could be better especially if django already includes some rotation and so on .. i think it is important that users can generate something like a debug report so that when i try to reproduce issues i can quickly find information i need.

**Comment by smilerz** [comment]
> i think it is important that users can generate something like a debug report so that when i try to reproduce issues i can quickly find information i need.

yeah, it's been on my list too - switching back and forth between dev/prod to troubleshoot issues is a pain.  There are a couple of other nice things about the python logger.  It starts a new file at app start (and set size to rotate, and how many to keep) so you can get the whole lifecycle without explaining to the user what to look for.

**Comment by vabene1111** [comment]
ok so there are several options to go about this (msg to user, msg in broser log, log to db, log to file). I like neither of those really since they all have their drawbacks. Since no soultion is really good i decided to go with the easisest for now and show the error message inside the toast when its a json message and only if debug is enabled to not spam normal users. 

from now on if the standard toast function is used inside catch blocks of any kind of request it should include an error object. This should probably be sufficent to debug most frontend issues, additionally this also logs to the local console for easier copying.
