### ISSUE TITLE
Markdown in Recipe Description

### ISSUE THREAD

**Issue by jenga201** [TandoorRecipes/recipes#691]
**Is your feature request related to a problem? Please describe.**
The markdown is not rendered in the recipe description.
I would like to have a formatted description when viewing the Cookbook.

My use case is to have an easily click-able hyperlink to the video guide for the recipe.

**Describe the solution you'd like**
Markdown is rendering perfectly within the steps of the recipe.
Also apply this to the recipe description.

**Comment by Alexsaphir** [comment]
Same issue with the steps titles

**Comment by vabene1111** [comment]
So while i understand that having markdown in the description would be nice (which simply is not yet implemented but will be), i do not understand how markdown would work in a step title ? The title only has a few characters and i do not see how they would profit from markdown rendering ?

**Comment by vabene1111** [comment]
i decided to keep the UI a little cleaner/simpler to not add markdown to the description. This allows me to show the description in places with limited view size without worrying of breaking existing recipes/formats.
