### ISSUE TITLE
Add bulk import a recipe collection from AllRecipes

### ISSUE THREAD

**Issue by enticedwanderer** [TandoorRecipes/recipes#702]
**Is your feature request related to a problem? Please describe.**
Looking to migrate to self hosted Tandoor (awesome project btw) away from AllRecipes profile/collection. I don't have means to do a bulk import from an AllRecipes profile without manually importing each recipe individually.

**Describe the solution you'd like**
Unfortunately, AllRecipes does not have a bulk export function (duh). However, it is fairly easy to scrape out the collection/favorites page on your profile to get a list of URLs pointing to each recipe, and a category they belong to. Then its a matter of just importing each individual recipe in an automated way. This can probably be scripted in the first pass (willing to give it a go), already have list of 200 or so URLs from a quick js scriptlet, just need to a separate script the import via APIs. A native bulk import would make this much more practical for other end users. I can see similar use case for Epicurious, but I personally didn't use it so out of scope.

**Describe alternatives you've considered**
Scripting out of band with the `bookmarklet-import` API.

**Additional context**
Probably the biggest stumbling block will be ensuring that the bulk import doesn't end up injecting a bunch of garbage if it ends up messing up the scraping. Generally, I've seen most problems around ingredients parsing/formatting (a separate issue), but having a bulk preview page as an intermediary, before committing would be nice. Another approach could be a confidence score  and presenting to the user any inputs that were below the acceptable threshold but that's likely now overkill and would need to be supported by the underlying scraper to begin with.

Given, that we can relatively easily fix incorrect ingredients after the fact this is far less important.

Quick and dirty browser js snippet to produce list of importable recipe URLs from any one category of your profile page:

```javascript
var linkSet = [...new Set(Array.from($("a[href*='/recipe/']")).map(h => h.href))]
console.info(linkSet.join("\n"))
```

**Comment by vabene1111** [comment]
thanks, i will look into how allrecipes can be imported

**Comment by vabene1111** [comment]
removing this from the milestone for now, this is likely a very complicated topic which does definitly have its useses but is not a top priority for now. 

I think this needs to be implemented as a general bulk import of urls/html files with maybe a pre defined parsing rule set (possible something around the manual importer that exports the current configuration and allows you to apply it to a bulk import)

can be done while reworking the import export system to the new frontend.

For now i recommend using a simple script to turn all links into PDF's and using them as external recipes

**Comment by vabene1111** [comment]
implemented with import export refactor
