### ISSUE TITLE
Simple way to add used-up foods to shopping list while/after cooking

### ISSUE THREAD

**Issue by philip-n** [TandoorRecipes/recipes#710]
**Is your feature request related to a problem? Please describe.**
Cooked a recipe today and used up the last rice (I thought there was more, but was wrong). Would have loved an easy way to put more rice on a shopping list while cooking, or directly after, without having to remember myself.

**Describe the solution you'd like**
In the "log cooking", offer a way to add ingredients of the logged recipe to the shopping list. E.g. add a button "Restock" that takes you to a list of all ingredients, with a cart-button next to each that allows to put it onto the shopping list (ideally: in arbitrary quantities).

This way, it should not bother anybody when it is not needed, but during logging you could habitually think about "was there something that I used up..." and add it to a shopping list.

**Describe alternatives you've considered**
Offer a cart-button next to each ingredient right in the recipe view, so you can add to the shopping list immediately while cooking. I don't like this idea, because it is rarely needed (I guess), clutters the UI and might be triggered by accident.

**Comment by vabene1111** [comment]
I like the idea very much!

I was planning on adding a little overlay/modal to the ingredient list to quickly edit the name, description or whatever. The button could be included there but i also like the idea of including it in the log cooking feature. 

Will see what can be done about this

**Comment by vabene1111** [comment]
this can probably easily be implemented once @smilerz finished the shopping rework as adding new stuff then simply requires adding entries and not linking them to a defined list. 

We just need to decide how an interaction option in the ingredient list would look. Custom right click, long click on mobile, three dots, just a click and scrap the checkbox or allow checkbox only on the checkbox icon .. 

this goes hand in hand with #892
