### ISSUE TITLE
add sort parameters to search

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#785]
sort by date added, last cooked, rating

**Comment by Programie** [comment]
Should also allow sorting alphabetically.

It should also be possible to configure the default sorting (per user) so we don't have to change the sorting every time. For example, I want to sort recipes alphabetically by default.

**Comment by vabene1111** [comment]
i think we should store that setting in local storage, just as the others as often (at least for me) preferences differ for mobile and desktop usage

**Comment by smilerz** [comment]
this was implemented at some point
