### ISSUE TITLE
Create simple Recipe List API

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#827]
Full Recipe API has gotten really fat, for simple uses (showing associated recipes with keywords/foods) a simplified API should be available with minimal attributes.

**Comment by vabene1111** [comment]
there are actually already two versions of the recipe API, the list returns far less detail than the detail view. Do you think the current list is still to big ?

**Comment by smilerz** [comment]
For performance reasons, I think so.  In order to facilitate search and make a content rich view there are a lot of expensive calculated fields.  The payload can get large as well as it is now returning a bunch of search related metadata.

My thought is to separate the full text search to a dedicated API and return the listRecipes API to something closer to default (though probably still enhanced with stuff like ratings, last cooked and similar)

**Comment by vabene1111** [comment]
yes i thought about the calculations as well .. maybe one could also work with some moderate result caching to that these calculations get cached as search tends to return the same results many times in a small time window. 

I dont really want to change the current list too much but putting the frontend full text search into a separate call might work.
