### ISSUE TITLE
Clear searched keyword when it is deleted

### ISSUE THREAD

**Issue by erikabourque** [TandoorRecipes/recipes#879]
I imported recipes, and then deleted the import keyword.  When returning to the search page, it was empty because it was still filtering with the deleted keyword.  The keyword should be removed from current search parameters when it is deleted.

**Comment by vabene1111** [comment]
ah yes that makes sense, i recently fixed one other issue with the keywords in search saving. This should be easy to implement

**Comment by vabene1111** [comment]
@smilerz you changed this so that the generic facets api call resolves the pre existing facets (which is good), i think the best solution to this would be to filter the results (`RecipeSearchView L455`) for keywords still having "Loading .." as their name and removing them from the search_settings variable/cookie as well or am i missing somethign ?

**Comment by smilerz** [comment]
>  i think the best solution to this would be to filter the results (`RecipeSearchView L455`) for keywords still having "Loading .." as their name and removing them from the search_settings variable/cookie as well or am i missing somethign ?
I wouldn't do anything automatically honestly - adding code to detect if recipes have been loaded then removing missing keywords, then triggering a new recipe search seems like a lot of extra complexity to replace just manually removing the deleted keywords.  Maybe some tweaks in recipe search to not filter on non-existent keywords/foods/etc.

**Comment by vabene1111** [comment]
ok so i just tested it, it does already ignore keywords that do not exist but there seems to be an issue that you cannot remove it from the input unless you hit the "reset search" button. 

This can easily be tested by using `?keyword=500` or some other non existent ID on the search as a GET parameter. Will need to fix the import, maybe same issue as before with the ID type being string not int

**Comment by smilerz** [comment]
OK, I see it now.  We can switch those fields to computed fields and pass a filtered list (add a hidden attribute to pre-loaded terms) that only filteres when the length of recipes > 0
