### ISSUE TITLE
Connection Time Out

### ISSUE THREAD

**Issue by JHarding86** [TandoorRecipes/recipes#880]
## Issue
Please describe your problem here

I get an "ERR_CONNECTION_TIMED_OUT" when attempting to go to the nginx web server

## Setup Info
Version: recently pulled, cant determine because it doenst work
OS: Ubuntu 20.02

Other relevant information regarding your problem (proxies, firewalls, etc.)
I want to run this behind HAProxy, but with these issues, I have just been running locally to try and get it working. One step at a time :)

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
[env.txt](https://github.com/vabene1111/recipes/files/7141418/env.txt)

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
[docker-compose.txt](https://github.com/vabene1111/recipes/files/7141420/docker-compose.txt)

### Logs
If you feel like there is anything interesting please post the output of `docker-compose logs` at
container startup and when the issue happens.
[log.txt](https://github.com/vabene1111/recipes/files/7141402/log.txt)

**Comment by smilerz** [comment]
@JHarding86 can you connect to Tandoor on port 8080?

**Comment by JHarding86** [comment]
I cannot. "ERR_CONNECTION_FAILED"

**Comment by smilerz** [comment]
Is that also true if you comment out the docker config for NGINX?

**Comment by JHarding86** [comment]
Still get "ERR_CONNECTION_FAILED"

Ned Docker Compose file:
[docker-compose.txt](https://github.com/vabene1111/recipes/files/7144569/docker-compose.txt)

**Comment by smilerz** [comment]
do you have a name service locally that allows you to resolve "db_recipes"?  That line in the .env probably needs switched to an IP address.

**Comment by JHarding86** [comment]
Are you talking about the "ALLOWED_HOSTS" variable?

**Comment by smilerz** [comment]
in .env this one
![image](https://user-images.githubusercontent.com/1808639/132876100-064bb956-18dc-4268-91b5-4435c632d51b.png)

**Comment by JHarding86** [comment]
I changed the POSTGRES_HOST variable to the ip address of the machine. I have all the containers running on the same machine (I also tried "localhost" and "0.0.0.0"). Now I'm getting these errors... I dont get these errors when the POSTGRES_HOST is "db_recipes".

```
  return func(*args, **kwargs)
web_recipes_1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
web_recipes_1  |     connection = Database.connect(**conn_params)
web_recipes_1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
web_recipes_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_recipes_1  | django.db.utils.OperationalError: could not connect to server: Connection refused
web_recipes_1  |        Is the server running on host "192.168.1.77" and accepting
web_recipes_1  |        TCP/IP connections on port 5432?
```

**Comment by smilerz** [comment]
if that error wasn't happening before that probably wasn't it then.  sorry.  maybe @vabene1111 has a better idea of what is going on.

**Comment by JHarding86** [comment]
@smilerz - Thank you for your help!

**Comment by JHarding86** [comment]
@vabene1111 any ideas here?

**Comment by vabene1111** [comment]
ok so i dont see any issues regarding the database in you logs, it looks like it is initialized properly and all migrations ran. 

Do your logs contain multiplke restarts of the service because i see the initialization several times ?

Please revert the dabase host variable back to db_recipes or change it to the IP of the docker container (which might change to hostname is better).

What is interesting is that i do not see any connection attemts in the logs you post. For me it looks like the requests are not even hitting the nginx or recipes application. Please try to add 
```
ports:
      - 8080:8080
```
to `web_recipes` and see if you can access tandoor on port 8080 of your machine (with your machines IP or hostname or localhost). 

A pure feeling of me is telling me that the requests do not hit any of the containers and might be handled by some other service on your machine, but i do not know that for sure

**Comment by JHarding86** [comment]
Adding:

```
ports:
      - 8080:8080
```

to the web_recipes docker worked. 

No other service on this machine is using port 80. In my experience, if two services try and use the same port, the second one that attempts to open it will fail.
![image](https://user-images.githubusercontent.com/12802227/132949113-67d11114-807e-45f7-9407-6978ff1faaee.png)

What is the purpose of the nginx container if the web_recipes is also a web server? Does it add a layer of security somehow or is it used purely for reverse proxying?

I ask because I use HAProxy as my reverse proxy. Would dropping the nginx docker and just setting up HAProxy to point straight at web_recipes be just as safe and  fast?

**Comment by vabene1111** [comment]
> No other service on this machine is using port 80. In my experience, if two services try and use the same port, the second one that attempts to open it will fail.

yes thats correct

if direct port 8080 works i think something is misconfigured with the nginx which is weired as the config is provided automatically. Could you pot the log output at the momemt you make the request and it fails ?

the purpose of the nginx container, to say it shortyl (i need to make an faq entry for this), is that gunicorn (the web server in the web_recipes container) is not meant to be outward facing and does not implement many of the things a real web server like nginx/apache does to handle loads/traffic better. you are probably fine removing it but i do not recommend it as the developers of gunicorn themself not recommend running it on its own. Nginx also does not introduce much overhead so it does not hurt to have it (except in cases like this were it does not work 😂 )

I am optimisitc that we can get your setup working, also with HA proxy.

**Comment by JHarding86** [comment]
Nothing happens in the logs when the connection fails or times out.

The nginx configuration directory has nothing in it, I think that is a little strange, even after starting up the container... /var/lib/docker/volumes/tandoornginx_config/_data

Multiple different attempts to connect to port 80 were attempted in this log:
[logs.txt](https://github.com/vabene1111/recipes/files/7148314/logs.txt)

And here is my new docker-compose.yml (I left the 8080 port on the web_recipes just so I could use it for the time being)
[docker-compose.txt](https://github.com/vabene1111/recipes/files/7148315/docker-compose.txt)

**Comment by JHarding86** [comment]
Maybe this is an extra clue, none of the images that I upload are ever viewable on the recipe page. When I perform the image upload the image can be seen on the page, but once I "save and view", the image doesn't show...

![image](https://user-images.githubusercontent.com/12802227/132969878-b1624fc8-9366-4f18-9b52-b5ec0cea251d.png)

**Comment by vabene1111** [comment]
hmm this sounds like your nginx is definitely broken in some way, maybe the config indeed did not manage to make its way onto your system. You could try downing all continers, running `docker prune -a` and `docker volume prune` to make sure every data related to tandoor (except its database/images) is deleted and then just start the containers again so the volumes are recreated and the file hopefully makes its way to you

**Comment by smilerz** [comment]
@JHarding86 can you update to 1.0.3 and confirm if you are still having an issue?  If you are please post the logs from the tandoor container with `DEBUG=1` enabled in .env and include the logs from the browser console.

**Comment by JHarding86** [comment]
I will take a look at this in the coming days. Holidays are getting busy!

**Comment by smilerz** [comment]
closed due to lack of info
