### ISSUE TITLE
Allow meal plan to be viewed across weeks

### ISSUE THREAD

**Issue by smilerz** [TandoorRecipes/recipes#922]
**Is your feature request related to a problem? Please describe.**
When you are looking at meal plans at the end of the week its frustrating to have to roll back and forth full weeks.

**Describe the solution you'd like**
Either make the dates a carrousel (back and forth 1 or 2 days at a time) or shift to anchoring it on today or yesterday instead of Sunday.

**Comment by vabene1111** [comment]
this is already implemented for the new meal plan by @Kaibu , feel free to take a look at it, you can have weeks/months and you can decide how many (on the settings tab). The latest version has this includeded, its /plan_new/ (also linked on the old plan i think)

**Comment by smilerz** [comment]
I didn't realize that was there - is it intended to show 2 [weeks/months] at a time?

**Comment by smilerz** [comment]
I didn't realize that was there!  IMO this button should only move a day when in week view and a week in month view.
![image](https://user-images.githubusercontent.com/1808639/135459691-aa4fc0bc-392a-47b5-a07e-6988e1e9a3b8.png)

Maybe there is something off in mine - but the meal plan is full screen and the 'settings' are below that.  
![image](https://user-images.githubusercontent.com/1808639/135459807-4334c2ac-effa-4b86-8b3b-c526d6351887.png)

**Comment by vabene1111** [comment]
the change with the tabs was added yesterday so either you are one day behind or the frontend code is still cached

having a day offset is actually something that @Kaibu and i talked about when starting this feature and its just not yet done but using the small button for that is actually a very good idea i think. The alternative is having a setting input box for that similar to the current meal plan implementation.

**Comment by Kaibu** [comment]
I'm not quite sure how to handle this, the calender module handles this behaviour by allowing you to set a starting day of the week.

Otherwise the button moves depending on the selected period in the settings. I however agree that the "move 12 periods" button is pretty useless.

**Comment by smilerz** [comment]
Is it possible to add a choice to starting day of the week to something like 'Today' or 'Yesterday'? That would alleviate most of the annoyance of looking at days that are in the past without having to fiddle with settings.  Or we can close the request as unnecessary because other people use the view differently than I do - I'm fine either way.

**Comment by Kaibu** [comment]
I think that's the best option, I'll add that

**Comment by Kaibu** [comment]
I've now implemented said behaviour (and added tooltips), let's see if it's intuitive since it loops over at the end of the week.
