### ISSUE TITLE
Books - Not working since 0.17 update

### ISSUE THREAD

**Issue by PureLoneWolf** [TandoorRecipes/recipes#954]
### Version
0.17 running in a docker on Unraid

### Bug description
I have 3 books:
Components (Contains around 30 recipes)
Shop (Contains around 135 recipes)
Personal (Contains around 100 recipes).

Since the update this morning, clicking on Shop or Personal sits with the spinning icons for over 3 minutes without anything coming up and my Unraid server CPU goes through the roof and forcing me to restart the docker to regain access to Recipes.

If I click on Components first, it takes around 30 seconds to populate the book.  At which point, clicking on either of the other 2 will take around 45-60 seconds, but they will then list the 30 recipes from Components and not their own recipes.

The rest of the app seems to be working absolutely flawlessly

**Comment by Kaibu** [comment]
Hotfix for lazy loading is up, I'd say it looks just as good but loads instantly now with 80 recipes
