### ISSUE TITLE
Bookmarklet, import from source fails/broken in Firefox

### ISSUE THREAD

**Issue by frudolph77** [TandoorRecipes/recipes#968]
### Version
development on https://app.tandoor.dev/

### Bug description
When I drag 'n drop an item from the tree on the right side to the field in the recipe, I'm instantly get redirected ~~to the image or~~ a `null` page. Hitting the back button in the browser mostly removes all already copied item.

Small Update:
Drag 'n drop from a TAB on the right side:
- JSON  redirects to the `null` page
- HTML  side works like a charm, but there are no images available.
- IMAGE redirects to the image

Firefox Version: 93.0

In Chrome there is no issue.

**Comment by vabene1111** [comment]
ok i just tested this with the latest version of the importer and it seems to have resolved this issue
