### ISSUE TITLE
Possibly missing SSL lib for Email SSL

### ISSUE THREAD

**Issue by nicedevil007** [TandoorRecipes/recipes#969]
### Version
0.17.2 (latest)
### Bug description
after entering all values for the invitation and clicking on the save button this appears:

![image](https://user-images.githubusercontent.com/17103076/138130467-fc57806b-a8f6-4265-b5b5-a32a7d20c355.png)

**Comment by nicedevil007** [comment]
My deployment still looks like this :)

```
version: "3"

volumes:
  db:
  static:
  media:
  nginx_config:
  
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      TIMEZONE: Europe/Berlin
      POSTGRES_PORT: 5432
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: [HIDDEN]
      POSTGRES_DB: djangodb

  web_recipes:
    image: vabene1111/recipes
    restart: always
    volumes:
      - static:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - media:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    environment:
      ALLOWED_HOSTS: "*"
      SECRET_KEY: [HIDDEN]
      TIMEZONE: Europe/Berlin
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: db_recipes
      POSTGRES_PORT: 5432
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: [HIDDEN]
      POSTGRES_DB: djangodb
      FRACTION_PREF_DEFAULT: 1
      COMMENT_PREF_DEFAULT: 1
      SHOPPING_MIN_AUTOSYNC_INTERVAL: 5
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: [HIDDEN]
      EMAIL_HOST_PASSWORD: [HIDDEN]
      EMAIL_USE_TLS: 0
      EMAIL_USE_SSL: 1
      DEFAULT_FROM_EMAIL: [HIDDEN]
      ACCOUNT_EMAIL_SUBJECT_PREFIX: "[Kochbuch] "
      ENABLE_SIGNUP: 1
      SOCIAL_DEFAULT_ACCESS: 0
      SORT_TREE_BY_NAME: 1
      GUNICORN_MEDIA: 0
      DEBUG: 1

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 8070:80
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - static:/static
      - media:/media
```

**Comment by vabene1111** [comment]
ok so the configuration looks fine .. i am not 100% sure, i used google as well for a few weeks, have you tried using TLS 1 and SSL 0 with the appropriate ports for google smtp ?

**Comment by nicedevil007** [comment]
Not yet, was waiting for your response, because I thought that this was the right setting for gmail.

Today I tried creating a new account for my girlfriend without an invitation link.

Same error happens there! If I reload the page I was able to login but still crazy behavior. On the 3rd account for a friend I got the 500 http error again :/

**Comment by vabene1111** [comment]
ok that is very interesting, that seems like it has nothing to do with the email setup. So just to understand you correctly, you enter basically just the group the user is supposed to have and create the link and then when saving the issue happens ?

or does it happen when the user tries to sign up ? 

Can you try if changing nothing in the invitation form works and if so which change creates the issue for you, i have tested a few combinations but maybe i have missed something.

**Comment by nicedevil007** [comment]
For your first question => yes.
For your second question => not "or", it is "and" :D
For your last question => I didn't change anything in the invitation form, just entered the mail for the person I want to invite.

**Here a description for question nr. 2:**
As you can see my signup is allowed withing the docker environment variables.
I click on register, type in all my userstuff (name, mail and so on) and all what I get back is:

![image](https://user-images.githubusercontent.com/17103076/139707761-dedfdf4b-2c4c-4d7d-8e8e-65558173275a.png)

I tryed it with my real url dns and I tryed it with the local IP... both the same. So NGINX shouldn't be the issue right ;)

**Comment by nicedevil007** [comment]
Ok I tested now with TLS and that seems to work for invitation and for "normal" registering.
Maybe you can fix this with a better message to not use SSL in deployment or clear this up in the install instructions?

**Comment by nicedevil007** [comment]
> @nicedevil007 email configuration is going to be provider specific, what works with google won't necessarily work with anyone else.

That's true, but SSL works with every docker container I deployed so far WITH the same provider (gmail). So tandoor is the first that won't work with SSL and needs TLS now?

**Comment by vabene1111** [comment]
interesting, i just could not connect to google when i tried SSL so i tought they might only accept TLS but maybe the container is just missing the appropriate libraries/packages to also use SSL for email (which confuses me as there are several SLL libs present but maybe there is still one missing).

I will look into this and see if the correct lib can be added (and which one it is)

**Comment by smilerz** [comment]
@nicedevil007 the SSL port for gmail is 465 - 

I have confirmed that the following configuration works with gmail
```
    - EMAIL_HOST=smtp.gmail.com
    - EMAIL_PORT=465
    - EMAIL_USE_TLS=0
    - EMAIL_USE_SSL=1
```

**Comment by TWART016** [comment]
I use
```
 - EMAIL_HOST=smtp.gmail.com
 - EMAIL_PORT=587
 - EMAIL_USE_TLS=1
 - EMAIL_USE_SSL=0
```
